### ISSUE TITLE
Done button not appearing in 'Add Payment Method' screen

### ISSUE THREAD

**Issue by jchand** [stripe/stripe-ios#1003]
## Summary

Noticing an issue where it's impossible to add a new payment method because the Done button is missing:

![add_pay_method](https://user-images.githubusercontent.com/3281141/43370517-4d8a2686-934e-11e8-887b-940f10d4d305.PNG)

This happens only once I already have one card added, and I try to add another:

![list_pay_methods](https://user-images.githubusercontent.com/3281141/43370520-50fe970c-934e-11e8-9227-3c2e3f7fa36d.PNG)

## iOS version
11.0

## Installation method
CocoaPods

## SDK version
12.0.0

**Comment by danj-stripe** [comment]
Hi @jchand,

This sounds like it's probably an integration problem, and we'll need to see the code you're using to present & manage the Add Payment view controller.

You can write into Stripe support at https://support.stripe.com/email/login and they'll be happy to help you integrate Stripe into your application & work through any issues.

Thanks,
Dan
