### ISSUE TITLE
Undeclared 'STPSourceTypeBitcoin:'

### ISSUE THREAD

**Issue by jzhw0130** [stripe/stripe-ios#1006]
## Summary

Use of undeclared identifier 'STPSourceTypeBitcoin'; did you mean 'STPSourceTypeUnknown'?

## Code to reproduce

Just build

## iOS version

9.0+

## Installation method

Cocaspod

## SDK version
target 'Milo' do
  pod 'Stripe', '~> 13.1.0'
  inherit! :search_paths
end

![screen shot 2018-08-07 at 9 40 29 am](https://user-images.githubusercontent.com/12521790/43749329-40df0666-9a26-11e8-87cf-7a1c954034b4.png)

![screen shot 2018-08-07 at 9 42 26 am](https://user-images.githubusercontent.com/12521790/43749333-4807f4ca-9a26-11e8-997d-01823b792ff1.png)

**Comment by danj-stripe** [comment]
Hi @jzhw0130 ,

We removed bitcoin support in v13.0.0. There are some more details in the Migrating guide: https://github.com/stripe/stripe-ios/blob/master/MIGRATING.md

Thanks,
Dan

**Comment by jzhw0130** [comment]
No No

It is not a migrate issue.
I just use the latest version(V13.1.0) directly.

The error exists inside the library, not my application code. 
Pl check again.

<img width="1067" alt="screen shot 2018-08-08 at 10 32 53 am" src="https://user-images.githubusercontent.com/12521790/43813037-9b1e1c9a-9af6-11e8-945c-05a207359840.png">
<img width="955" alt="screen shot 2018-08-08 at 10 33 10 am" src="https://user-images.githubusercontent.com/12521790/43813045-9fec4d78-9af6-11e8-8d5f-fc14a3849806.png">
