### ISSUE TITLE
How to force invalid state on STPPaymentCardTextField when user leaves the textfield

### ISSUE THREAD

**Issue by jlubeck** [stripe/stripe-ios#1007]
I'm having some users that for some reason are trying to enter a credit card with 15 digits instead of 16. But the STPPaymentCardTextField doesn't show as red, because the state is Incomplete instead of Invalid.

I understand that while the user is typing, we don't want to show them an invalid card until they are done typing, but after they leave the field, if the card is invalid, it should turn to invalid, instead of incomplete.

Hopefully you'll agree and make a change for it, but in case you don't, is there a way I can force this state on the field?

I can see that `isValid` is false on `paymentCardTextFieldDidEndEditing`, so half way there. But I can't find a way to show the invalid state when I see that.

Thank you!

**Comment by csabol-stripe** [comment]
Hi @jlubeck, thanks for the report! I'm actually working on a patch updating some `STPPaymentCardTextField` behaviors and issues that should address this. I will update this issue with the Pull Request when it is ready!

**Comment by jlubeck** [comment]
Oh sweet! Perfect timing. Thanks for the fast reply!

**Comment by csabol-stripe** [comment]
We've just released [v13.2.0](https://github.com/stripe/stripe-ios/releases/tag/v13.2.0) that now marks incomplete card numbers as invalid. Thanks for the report and let us know if you run into any other issues!
