### ISSUE TITLE
Keyboard issues when selecting state

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#1016]
## Summary
I've upgraded Stripe from version 11.5.0 to 13.2.0, saw a problem appear on the "Shipping" screen.
When selecting a state in the US in version 11.5.0 it allowed selecting from a selector that included all 

This helped made sure that:
1. The states were written in the same format of 2 letter (for example California was always "CA).
2. Easy to select

In version 13.2.0, it requires users to write themselves the state. This can lead to confusion as it's not clear if states should be written as 2 letters or for state name ("CA" or "Calfornia").

I'm not sure why this change was made. Is there a way to revert this? 

## iOS version
12.0 

## Installation method
cocoa pods

## SDK version
13.2.0

**Comment by csabol-stripe** [comment]
Hi @odedharth, would you be able to provide some more detail on where you are seeing this regression? Is it in STPShippingAddressViewController? We have a country selector in there but I'm trying to track down if we ever also had a state selector

**Comment by odedharth** [comment]
@csabol-stripe Sorry, it's actually ok.
