### ISSUE TITLE
Stripe.h compile error -> #import "STPPaymentIntent.h"; STPPaymentIntent.h is missing

### ISSUE THREAD

**Issue by SteveLeviathan** [stripe/stripe-ios#1019]
## Summary

`Stripe.h` compile error:
Header import -> `#import "STPPaymentIntent.h";`    
`STPPaymentIntent.h` is missing.

## Installation method

CocoaPods
## SDK version

`13.1.0` and `13.2.0`

**Comment by danj-stripe** [comment]
Hi @SteveLeviathan,

I'm unable to reproduce your problem. I've created brand new projects, both Objective-C & SWIFT, and used cocoapods to install `13.2.0`.

I'm able to `#import <Stripe/Stripe.h>` successfully, and even used the `retrievePaymentIntentWithClientSecret:completion:` method to fetch & print a `STPPaymentIntent` object.

If you're able to provide some more details, I may be able to help you resolve this, or you can write into https://support.stripe.com/email/login

Thanks,
Dan

**Comment by danj-stripe** [comment]
I'm glad you got it figured out! I believe we've got our podspec set up correctly, so I suspect either an Xcode glitch (maybe it didn't pick up the changed project?), or something with the Cocoapods gem.

I don't think we've seen similar issues previously, but we'll keep an eye out.

Dan
