### ISSUE TITLE
STPPaymentCardTextField not firing change delegate method when deleting across fields 

### ISSUE THREAD

**Issue by tkirby** [stripe/stripe-ios#1021]
I'm seeing odd behavior from STPPaymentCardTextField when deleting across field boundries, the first delete in the previous text field doesn't fire change method. And it looks like it's not doing some internal housekeeping as well. Here is a [video](https://www.youtube.com/watch?v=8m4_goJT5jk&feature=youtu.be) illustrating what I'm seeing using the demo example from [CreditCardForm-iOS]( https://github.com/orazz/CreditCardForm-iOS). i have not modified it at all so you should see the same results if you install and run it.

I don't know how to get Stripe version. It's whatever "pod Stripe" includes.

**Comment by danj-stripe** [comment]
Hi @tkirby,

Thanks for the bug report. I'm able to reproduce the problem, and I've filed a bug for it on our internal issue tracker.

Dan
