### ISSUE TITLE
STPPaymentContext swallows error on failed ephemeral key creation

### ISSUE THREAD

**Issue by peterringset** [stripe/stripe-ios#1022]
## Summary
The call to create an ephemeral key can fail. In this case the payment context's delegate needs to be notified so that it can do the appropriate reloading. It seems however that the payment context swallows this error, and the delegate is never notified.

## Code to reproduce
Create an `STPPaymentContext` and set it's delegate. Make a bogus implementation of the ephemeral key creation, and call completion handler with a bogus error, `completion(nil, NSError(domain: "Stripe", code: 21, userInfo: nil))`

## iOS version
iOS 12

## Installation method
Carthage

## SDK version
v13.1.0

## Other information
-

**Comment by danj-stripe** [comment]
Hi @peterringset,

Thanks for the bug report. You've found an unhandled edge case, and I've written up a bug in our internal tracker to get it fixed. However, I think we can give you a workaround.

First, make sure you're setting `paymentContext.hostViewController` after creating the `STPPaymentContext`:

```swift
let paymentContext = STPPaymentContext(...)
...
paymentContext.hostViewController = ...
```

Next, wrap your bogus implementation in a dispatch async block:
```swift
func createCustomerKey(withAPIVersion apiVersion: String, completion: @escaping STPJSONResponseCompletionBlock) {
        DispatchQueue.main.async {
            completion(nil, NSError(domain: "Stripe", code: 21, userInfo: nil))
        }
```

Now your `STPPaymentContextDelegate` should be receiving `paymentContext:didFailToLoadWithError:` notifications. https://stripe.github.io/stripe-ios/docs/Protocols/STPPaymentContextDelegate.html#/c:objc(pl)STPPaymentContextDelegate(im)paymentContext:didFailToLoadWithError:

----

It's *only* when the ephemeral key call fails *before* the `hostViewController` has been set that the error is being swallowed. When you call `completion(nil, error)` immediately & synchronously, that happens every time. Just moving the `completion(nil, error)` to the end of the run loop should be enough to fix it.

If there's a chance that your actual `createCustomerKey` implementation can fail immediately & synchronously, you'll want to keep that dispatch async call in. I think most real implementations are async already, and won't hit this bug.

Thanks!
Dan
