### ISSUE TITLE
handleURLCallback(url) return false when return from alipay.

### ISSUE THREAD

**Issue by wangjiejacques** [stripe/stripe-ios#1023]
## Summary
```swift
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        let stripeHandled = Stripe.handleURLCallback(with: url)
        if (stripeHandled) {
            return true
        } else {
            // This was not a stripe url – do whatever url handling your app
            // normally does, if any.
        }
        return false
    }
```
I use this code to handle url returned by alipay, is it normal that `Stripe.handleURLCallback(with: url)` return false ?
the url is as the following 
`appname://safepay/?%7B%22memo%22:%7B%22result%22:%22%22,%22ResultStatus%22:%226001%22,%22memo%22:%22Cancelled%20by%20Customer%22%7D,%22requestType%22:%22safepay%22%7D`

## Code to reproduce
```swift
let url = URL(string: "appname://safepay/?%7B%22memo%22:%7B%22result%22:%22%22,%22ResultStatus%22:%226001%22,%22memo%22:%22Cancelled%20by%20Customer%22%7D,%22requestType%22:%22safepay%22%7D")!
// stripeHandled is false, it should be true.
let stripeHandled = Stripe.handleURLCallback(with: url)
```

## iOS version
iOS 12

## Installation method
Pod

## SDK version
13.2.0

**Comment by csabol-stripe** [comment]
hi @wangjiejacques,
Sorry to hear you're having issues. The code to reproduce you've provided is expected to return false since Stripe doesn't have an opportunity to register for the callback. Would you be able to provide some more information on how you are hitting this error? Feel free to reach out to Stripe support at https://support.stripe.com/contact if you would be more comfortable sharing additional info there :)

**Comment by ajithkumark771** [comment]
I'm facing same problem in stripe sdk 15.0.1 . The return url was correct  ,but checking it on stripeHandle returns false which expected to return true.
url->  appName://stripe-redirect?payment_intent=pi_1EWzqLD4QE47FF1gaM1I&payment_intent_client_secret=pi_WFFFFV4554DDH5uxO4qjqSK&source_type=card

**Comment by csabol-stripe** [comment]
Hi @ajithkumark771, would you be able to supply some code to reproduce the issue you are seeing? Also feel free to bring this up with our support team at https://support.stripe.com/contact

**Comment by erichsu** [comment]
With Stripe iOS SDK 14.0 here.


```swift
func aliPay(_ order: Order) {

    let url: String = "app://stripe-redirect"

    let price: UInt = 100
    let param: STPSourceParams = STPSourceParams.alipayParams(withAmount: price, currency: order.currency.rawValue, returnURL: url)

    STPAPIClient.shared().createSource(with: param) { (source: STPSource?, err: Error?) -> Void in

        if let source: STPSource = source {
            // TODO: charge source
        }
    }
}
```

The expected callback URL should be `app://stripe-redirect?redirect_merchant_name=XXXX`. 
However, We were getting this URL on `AppDelegate.application:open:options` => `app://safepay/?%7B%22memo%22:......`

```swift
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any]) -> Bool {

    // url : app://safepay/?%7B%22memo%22:%7B%22result%22:%22%22,%22ResultStatus%22:%226001%22,%22memo%22:%22%E7%94%A8%E6%88%B6%E4%B8%AD%E9%80%94%E5%8F%96%E6%B6%88%22%7D,%22requestType%22:%22safepay%22%7D
    let stripeHandled = Stripe.handleURLCallback(with: url)
    // ERROR: stripeHandled is false
}
```

**Comment by csabol-stripe** [comment]
Thanks @erichsu ! I'm going to try to reproduce what you are seeing

**Comment by erichsu** [comment]
> Thanks @erichsu ! I'm going to try to reproduce what you are seeing

Kindly remind you that it's only happened in live mode with AliPay App interaction.
Test mode works fine as usual

**Comment by csabol-stripe** [comment]
@erichsu would you mind testing with 
`let url: String = "app://"`
i.e. without the `stripe-redirect` and letting me know if that works for you?

**Comment by erichsu** [comment]
@csabol-stripe unfortunately it doesn't work...

If you check the function `stp_matchesURLComponents` in `NSURLComponents+Stripe.m`.

```objc
- (BOOL)stp_matchesURLComponents:(NSURLComponents *)rhsComponents {
    BOOL matches = ([[self.scheme lowercaseString] isEqualToString:[rhsComponents.scheme lowercaseString]]
                    && [[self.host lowercaseString] isEqualToString:[rhsComponents.host lowercaseString]]
                    && [self.path isEqualToString:rhsComponents.path]);

    if (matches) {
        NSDictionary<NSString *, NSString *> *rhsQueryItems = rhsComponents.stp_queryItemsDictionary;

        for (NSURLQueryItem *queryItem in self.queryItems) {
            if (![rhsQueryItems[queryItem.name] isEqualToString:queryItem.value]) {
                matches = NO;
                break;
            }
        }
    }

    return matches;
}
```

The URL won't match because even the scheme is same `app://`, the host `nil`(app:// from source) is not match to `safePay`(app://safepay/?..... from callback URL)

**Comment by csabol-stripe** [comment]
@erichsu thanks for checking. We're currently investigating the `redirect_url` handling on our backend

**Comment by yuki-stripe** [comment]
The Alipay app requires the return URL to be `your-app-scheme://safepay/` (replace `your-app-id` with your actual app scheme). 

I'm unable to test at this time whether the webview redirects to this URL as well.  I'm working on documenting this now.
