### ISSUE TITLE
How to get Charge Id in iOS

### ISSUE THREAD

**Issue by asharmaVelsof** [stripe/stripe-ios#1024]
![screen shot 2018-10-01 at 12 26 22 pm](https://user-images.githubusercontent.com/43741245/46275541-05937800-c57b-11e8-97dc-a5768b18a990.png)
I am integrating Stripe in iOS Swift 4.0. I have installed the SDK using Cocoa pods. I have completed the integration and everything is working fine. 
The only issue I am facing is that : How can I get Charge Id after Complete transaction in Stripe.
I am able to get Source Id (Last line of screenshot attached). Is there any way to get Charge Id of Stripe Transaction in iOS ??

**Comment by danj-stripe** [comment]
Hi @asharmaVelsof,

The SDK does not have any method for retrieving the Charge.

Your backend is responsible for creating the `Charge`, and it looks like it's doing so through `MyAPIClient.sharedClient.completeCharge()`. If there are pieces of data you need your server to send back to the mobile client, I'd recommend adding it there.

I'm not sure what you're planning to use the `Charge.id` for, but you should also consider if it's something your backend can do for you - maybe you don't need to send it to the client at all.

For more help with your integration, you can write into https://support.stripe.com/email/login

Thanks!
