### ISSUE TITLE
Error 'The network connection was lost' each time retrieve source on real device

### ISSUE THREAD

**Issue by huyLamOffy** [stripe/stripe-ios#1025]
## Summary

We use Stripe to integrate Alipay in-app. Every time we get call back redirect, we use func retrieveSource() to retrieve and check chargeable status. Make a test on real device, it usually gets error "The network connection was lost", but it works well on the simulators
## Code to reproduce

STPAPIClient.shared().retrieveSource(withId: id, clientSecret: clientSecrect, completion: completion)
## iOS version

11.3
## Installation method

pod
## SDK version

13.2.0

**Comment by danj-stripe** [comment]
Hi @huyLamOffy,

That error makes it sound like your device has network connectivity problems. As far as I know that specific error message is coming from Foundation, via the `NSURLSession` that the Stripe SDK is using.

Our support team is available to help with integration issues. There might be something different or unusual about the way you've integrated that's causing the SDK to have connection trouble. You can find them at [https://support.stripe.com/email/login](https://support.stripe.com/email/login),

Thanks, Dan
