### ISSUE TITLE
validateCvc:error: method returns NO for 3-digit AMEX CID code

### ISSUE THREAD

**Issue by simX** [stripe/stripe-ios#103]
We're seeing an issue with American Express cards.  Apparently, there are two "security codes" on American Express cards: a 4-digit CVV2 code on the front, and a 3-digit "CID" code on the back.

Since most other cards have the CVV2 code printed on the back of the card, we have some users who instinctively use that code for AMEX cards as well, even though it's technically not the CVV2 code.  When validating the 3-digit CID code, the validateCvc:error: method returns NO.

However, there seems to be a difference with the Stripe APIs.  We have a web client that calls the Stripe APIs directly, and they seem to _accept_ the 3-digit CID code for American Express cards.  We can successfully vault cards this way.  For example, this URL:

https://api.stripe.com/v1/tokens?card[number]=371449635398431&card[exp_month]=12&card[exp_year]=2020&card[cvc]=222&key=pk_test_someFakeKey&payment_user_agent=stripe.js&_method=POST

returns a 200 OK response, indicating the card has been vaulted.

In addition, we found a similar issue in PaymentKit that was already reported: https://github.com/stripe/PaymentKit/issues/15

The specific culprit seems to be line 284 of validateCvc:error:

>    BOOL validLength = ((cardType == nil && [ioValueString length] >= 3 && [ioValueString length] <= 4) ||
>            ([cardType isEqualToString:@"American Express"] && [ioValueString length] == 4) ||
>            (![cardType isEqualToString:@"American Express"] && [ioValueString length] == 3));

**Comment by jflinter** [comment]
Ah, sorry for the delay. I ended up bundling it as part of a larger
refactor, which I just pushed out (version 3.0.0). Enjoy!

On Mon, Dec 29, 2014 at 5:19 PM, Simone Manganelli <notifications@github.com
