### ISSUE TITLE
Enable deleting selectedPaymentMethod.

### ISSUE THREAD

**Issue by wangjiejacques** [stripe/stripe-ios#1032]
## Summary

From the stripe api [documentation](https://stripe.com/docs/api/cards/delete), the user can delete the selected card, but this is not allowed in the sdk, why this ?
```
if (paymentMethod == self.selectedPaymentMethod) {
    // Cannot detach selected payment method
    return YES;
}
```

## Code to reproduce
```
if (paymentMethod == self.selectedPaymentMethod) {
    // Cannot detach selected payment method
    return YES;
}
```

## iOS version
iOS 12

## Installation method
Pod

## SDK version
13.2.0

**Comment by csabol-stripe** [comment]
Fix is in master. Thanks!
