### ISSUE TITLE
Incorrect cvv validation for amex cards

### ISSUE THREAD

**Issue by DimaKorol** [stripe/stripe-ios#1034]
As I know the only valid length for amex cards is 4, so 3 is should be invalid

https://github.com/stripe/stripe-ios/blob/46e99bbeb454c9ff435de1b1818c340b0ea60566/Tests/Tests/STPCardValidatorTest.m#L235

**Comment by csabol-stripe** [comment]
Hi @DimaKorol – see #440

> This is actually a common misconception about American Express cards - while the majority of them have 4-digit CVCs, there are several types of amex card that have a 3-digit CVC. Many amex cards also have a 3-digit "CID" printed on the front, which also works for verification purposes. As such we have to be slightly ambiguous in our validation.
