### ISSUE TITLE
Getting error: "Your PKPaymentRequest.merchantCapabilities needs be set to the value: PKMerchantCapability3DS"

### ISSUE THREAD

**Issue by lily-Wan** [stripe/stripe-ios#1039]
## Summary

 I have set 
``request.merchantCapabilities = PKMerchantCapability3DS | PKMerchantCapabilityCredit | PKMerchantCapabilityDebit |PKMerchantCapabilityEMV;``,
but i still got an error
 ``Your PKPaymentRequest.merchantCapabilities needs be set to the value: PKMerchantCapability3DS``

## Code to reproduce

> NSArray *supportedNetworks = @[PKPaymentNetworkAmex,         PKPaymentNetworkMasterCard,PKPaymentNetworkVisa,PKPaymentNetworkChinaUnionPay];
    PKPaymentRequest *payRequest = [[PKPaymentRequest alloc]init];
    payRequest.countryCode = @"CN";     //国家代码
    payRequest.currencyCode = @"CNY";       //RMB的币种代码
    payRequest.merchantIdentifier = @"merchant.com.iuiga.app";  //申请的merchantID
    payRequest.supportedNetworks = supportedNetworks;   //用户可进行支付的银行卡
    payRequest.merchantCapabilities = PKMerchantCapability3DS | PKMerchantCapabilityCredit | PKMerchantCapabilityDebit |PKMerchantCapabilityEMV;
    NSDecimalNumber *subtotalAmount = [NSDecimalNumber decimalNumberWithMantissa:1275 exponent:-2 isNegative:NO];   //12.75
    PKPaymentSummaryItem *subtotal = [PKPaymentSummaryItem summaryItemWithLabel:@"商品价格" amount:subtotalAmount];
    NSDecimalNumber *totalAmount = [NSDecimalNumber zero];
    totalAmount = [totalAmount decimalNumberByAdding:subtotalAmount];
    PKPaymentSummaryItem *total = [PKPaymentSummaryItem summaryItemWithLabel:@"IUIGA" amount:totalAmount];  
    NSMutableArray *summaryItems = [NSMutableArray arrayWithArray:@[subtotal, total]];
    payRequest.paymentSummaryItems = summaryItems;  

## iOS version

12.0
## Installation method

cocoapods
## SDK version

11.5.0

## Other information

Here is the entire output error
> Error Domain=com.stripe.lib Code=50 "Your PKPaymentRequest.merchantCapabilities needs be set to the value: PKMerchantCapability3DS." UserInfo={com.stripe.lib:ErrorMessageKey=Your PKPaymentRequest.merchantCapabilities needs be set to the value: PKMerchantCapability3DS., com.stripe.lib:StripeErrorTypeKey=invalid_request_error, NSLocalizedDescription=Your PKPaymentRequest.merchantCapabilities needs be set to the value: PKMerchantCapability3DS.}

**Comment by danj-stripe** [comment]
Hi @lily-Wan,

I believe it's erroring due to this line:
```objective-c
payRequest.merchantCapabilities = PKMerchantCapability3DS | PKMerchantCapabilityCredit | PKMerchantCapabilityDebit |PKMerchantCapabilityEMV;
```

I think it'll start working if you change it to:

```objective-c
merchantCapabilities = PKMerchantCapability3DS;
```

Dan

**Comment by lily-Wan** [comment]
I found out that was because  Stripe don't support unionpay in china
