### ISSUE TITLE
Apple Pay + Stripe Connect

### ISSUE THREAD

**Issue by gurgeous** [stripe/stripe-ios#104]
I think we need to be able to pass the stripe user's publishable key to `createTokenWithPayment`. Right now it will use `defaultPublishableKey`, which won't work for Stripe Connect.

For the time being I can work around this by just setting the defaultPublishableKey before creating the token, but that's a hack...

**Comment by jflinter** [comment]
This is resolved as of version 3.0.0 - now, you can just create a different `STPAPIClient` for each publishable key you want to use. Reading more carefully, though, I'm pretty certain you just want to use customer sharing for this - if one of your merchants were to rotate their publishable keys, your integration would break.
