### ISSUE TITLE
Need something like Android sdk's CardMultilineWidget to accept multiline inputs

### ISSUE THREAD

**Issue by rajishere** [stripe/stripe-ios#1044]
## Summary
Need something like Android sdk's CardMultilineWidget to accept multiline inputs 

## Other information
Hi Team, 

In our app, the experience of adding card details is better when its multiline vs one. We are already consuming something similar to that in Android using the ```com.stripe.android.view.CardMultilineWidget``` widget. Is it possible to take it as a feature request for iOS as well.

Thank you,
Raj

**Comment by danj-stripe** [comment]
Hi @rajishere,

Thanks for the feature request! I've added it to our internal JIRA (IOS-1101).

Thanks,
Dan

**Comment by diptiganatra** [comment]
@danj-stripe Is this feature added for iOS?
