### ISSUE TITLE
Unable to change localization of stripe ui from app setting.

### ISSUE THREAD

**Issue by NutanNiaraula** [stripe/stripe-ios#1049]
I know stripe has localization file for its UI. When I change the device language Norwegian localizations are applied. But I can't find any setting within the library to change this dynamically. Is this not implemented yet or am I missing something?

**Comment by aa-stripe** [comment]
@NutanNiaraula Does your app have a Norwegian localization added to it?

**Comment by csabol-stripe** [comment]
Gonna close this one. If you are still experiencing an issue with localization you can reach out to our support team at https://support.stripe.com/contact
