### ISSUE TITLE
Problem when i'm trying to add a card with  pushPaymentMethodsViewController()

### ISSUE THREAD

**Issue by gleyd** [stripe/stripe-ios#1056]
## Summary

Hello, when i use the controller self.paymentContext?.pushPaymentMethodsViewController(), i can get the credit cards of an user, i can delete credit cards of an user, but when i'm trying to add credit card, i put all info and click "ok", i have a infinite spinner load and i cannot add card. i already used this code in august, this code worked. Can you help me please ?

## Code to reproduce

 let settingsVC = SettingsViewController()

  override func viewDidLoad() {
        super.viewDidLoad()
        initView(idProduct: "32",name: "productName", type:"type", price: 200, settings: settingsVC.settings)
}
   func initView(idProduct: String,name: String, type:String, price: Int, settings: Settings) {
        
        let stripePublishableKey = self.stripePublishableKey
        let backendBaseURL = self.backendBaseURL
        
        assert(stripePublishableKey.hasPrefix("pk_"), "You must set your Stripe publishable key at the top of CheckoutViewController.swift to run this app.")
        assert(backendBaseURL != nil, "You must set your backend base url at the top of CheckoutViewController.swift to run this app.")
        self.name = name
        self.idProduct = idProduct
        self.theme = settings.theme
        MyAPIClient.sharedClient.baseURLString = self.backendBaseURL
        
        // This code is included here for the sake of readability, but in your application you should set up your configuration and theme earlier, preferably in your App Delegate.
        let config = STPPaymentConfiguration.shared()
        config.publishableKey = self.stripePublishableKey
        //config.appleMerchantIdentifier = self.appleMerchantID
        config.companyName = self.companyName
        config.requiredBillingAddressFields = .none
        config.requiredShippingAddressFields = .none
        config.additionalPaymentMethods = settings.additionalPaymentMethods

        // Create card sources instead of card tokens
        config.createCardSources = true;
        let customerContext = STPCustomerContext(keyProvider: MyAPIClient.sharedClient)
        let paymentContext = STPPaymentContext(customerContext: customerContext,
                                               configuration: config,
                                               theme: settings.theme)
        let userInformation = STPUserInformation()
        paymentContext.prefilledInformation = userInformation
        paymentContext.paymentAmount = price
        paymentContext.paymentCurrency = self.paymentCurrency
        
        let paymentSelectionFooter = PaymentContextFooterView(text: "")
        paymentSelectionFooter.theme = settings.theme
        paymentContext.paymentMethodsViewControllerFooterView = paymentSelectionFooter
        
        let addCardFooter = PaymentContextFooterView(text: "")
        addCardFooter.theme = settings.theme
        paymentContext.addCardViewControllerFooterView = addCardFooter
        
        self.paymentContext = paymentContext

  
        var localeComponents: [String: String] = [
            NSLocale.Key.currencyCode.rawValue: self.paymentCurrency,
            ]
    self.paymentContext?.delegate = self
        paymentContext.hostViewController = self
        
    
    }

@IBAction func selectCard(_ sender: Any) {
        self.paymentContext?.pushPaymentMethodsViewController()

    }
    
## iOS version
12.1
## Installation method
pod
## SDK version
14.0.0

**Comment by danj-stripe** [comment]
Hi @gleyd,

I understand that you're getting an infinite spinner while trying to use the Add Card functionality of the SDK. The code sample you've provided looks reasonable, so I'm not sure what's going wrong.

You should reach out to Stripe support using one of the options at https://support.stripe.com/ and they can help you figure this out.

Dan

**Comment by gleyd** [comment]
i delete this extension in my code, for resolve this problem 

extension STPAddCardViewController {
    
    // We can't swizzle in initialize because it's been deprecated in Swift 3.1.
    // Instead, we have to call this method before STPAddCardViewController appears.
    static func startMockingAPIClient() {
        let originalSelector = #selector(apiClient)
        let swizzledSelector = #selector(swizzled_apiClient)
        swizzle(self, originalSelector, swizzledSelector)
    }
    
    // Expose the private `apiClient` property as a method
    @objc func apiClient() -> STPAPIClient? {
        return nil
    }
    
    @objc func swizzled_apiClient() -> STPAPIClient? {
        return MockAPIClient()
    }
}

**Comment by danj-stripe** [comment]
Thanks for the update, and I'm glad you figured it out. That definitely looks like it'd break things.
