### ISSUE TITLE
How get STPPaymentContext  attributes  in Controllers , i would like to get "customerContext.customer.stripeID" 

### ISSUE THREAD

**Issue by dajdouj10** [stripe/stripe-ios#1057]

**Comment by aliriaz-stripe** [comment]
Hi dajdouj10,
STPCustomerContext doesn't expose its STPCustomer property publicly, instead it handles all customer updates through ephemeral keys.
If you are already using STPCustomerContext and implementing its delegate, you can get the customer ID from the ephemeral key response.
If you have more questions, do write in to https://support.stripe.com/email and we'd be happy to help you out there!
Cheers!
