### ISSUE TITLE
Change color button on PaymentMethodsViewController and AddCardViewController

### ISSUE THREAD

**Issue by gleyd** [stripe/stripe-ios#1058]
## Summary
Hello,
How can I change textColor on button in navBar at PaymentMethodsViewController and AddCardViewController ?
Thank you
## iOS version
12.0.1
## Installation method
Pod

## SDK version
14.0.0

**Comment by csabol-stripe** [comment]
Hi @gleyd,
The navigation bar button items are stylized with `STPTheme` using the `accentColor`, `secondaryForegroundColor`, `font`, and `emphasisFont`. Feel free to contact our support if you experience any issues getting this setup! cc: @aliriaz-stripe @fred-stripe
