### ISSUE TITLE
Error: function not found (Code: 141, Version: 1.2.20)

### ISSUE THREAD

**Issue by allen8300** [stripe/stripe-ios#110]
Hi, there, I followed every step by your tutorial, while when I tried to pay by "4242 4242 4242 4242", I kept getting this error "Error: function not found (Parse error Code: 141, Version: 1.2.20)", I also check similar closed question from this link "https://github.com/stripe/stripe-ios/issues/63", but still nothing useful,  any other guidance?

Thanks in advance.

**Comment by jflinter** [comment]
Hey, it sounds like you haven't set up your Parse account correctly. Unfortunately it's hard to say how without more context, but make sure you reread https://github.com/stripe/stripe-ios#parse . All Parse does in the example is create a charge with the Stripe API, so you can also set up your own server to do this yourself and use an `NSURLSession` to send it your token. For more help you can also contact support@stripe.com .
