### ISSUE TITLE
Postal code required for Saudi Arabia (countryCode: SA)

### ISSUE THREAD

**Issue by jackcsk** [stripe/stripe-ios#1125]
## Summary
Saudi Arabia has a postal code, but the STPPostalCodeValidator.countriesWithNoPostalCodes array listed it as one of those without:
https://github.com/stripe/stripe-ios/blob/master/Stripe/STPPostalCodeValidator.m

## Code to reproduce
n/a

## iOS version
any

## Installation method
cocoapods

## SDK version
14.0.0

## Other information
  - references
    - https://address.gov.sa/en/address-format/overview
    - https://en.wikipedia.org/wiki/List_of_postal_codes
  - same issue on Android:
    - https://github.com/stripe/stripe-android/issues/769

**Comment by csabol-stripe** [comment]
Thanks for the report! Merged a fix
