### ISSUE TITLE
it is autometically added scan card button. How can I disable That button In Swift 4???

### ISSUE THREAD

**Issue by himanshuvankar** [stripe/stripe-ios#1126]
## Summary
i just integrated stripe for payment that was runninng fine.but when I install a app on device that was show me a "Scan Card" button. When i tapped that button open a card scanner and that was not working fine. so how can i disable that "Scan Card" button????

## Code to reproduce
import Stripe
if paymentMethodCode == "stripe"{
                let theme = STPTheme()
                theme.accentColor = UIColor.blackClr
                let addCardViewController = STPAddCardViewController(configuration: STPPaymentConfiguration.shared(), theme: theme)
                addCardViewController.title = "Carte Bancaire"
                addCardViewController.delegate = self  addCardViewController.cardheader
                self.navigationController?
                    .pushViewController(addCardViewController, animated: true)
              }
//MARK : - Stripe payment

extension PaymentVC:STPAddCardViewControllerDelegate,CardIOPaymentViewControllerDelegate{
    
  func addCardViewControllerDidCancel(_ addCardViewController: STPAddCardViewController) {
        self.navigationController?.popViewController(animated: true)
    }
    
    func addCardViewController(_ addCardViewController: STPAddCardViewController, didCreateToken token: STPToken, completion: @escaping STPErrorBlock) {
        self.navigationController?.popViewController(animated: true)
        print("token ",token)
        guard let orderId = confirmVC.data?.orderID else {
            return
        }
        let param:[String : Any] = ["orderid":orderId,"token":token.tokenId]  
    }
}

## Installation method
Via Install A POD.

**Comment by aliriaz-stripe** [comment]
Hi himanshuvankar,
Unfortunately, at this time, the SDK doesn't support disabling/hiding the Scan Card button.
One possible approach you could opt for in your application is to swizzle the `scanReadCardWithCamera` method and return false.
Hope that helps!

**Comment by jdsocialsmart** [comment]
Hi, The StripeiOS SDK Pod installation autmatically install the dependency of CardIO and it is available with payment methods? I need to implement the Stripe ios SDK with CardIO implementation using Swift5. Can you please guide me the latest Stripe ios SDK with Cardio. 

Thanks!
