### ISSUE TITLE
Port Stripe-iOS to Flutter

### ISSUE THREAD

**Issue by marcglasberg** [stripe/stripe-ios#1129]
We need Stripe-iOS ported to Google's [Flutter](https://flutter.io/).

There are 2 ways of doing that: 

1. One is to use platform-channels, so that a Dart layer interfaces with the original Stripe-iOS code, in Swift or Objective-C (see: https://flutter.io/docs/development/platform-integration/platform-channels). 

2. Another is to port it to native Dart.

Note: Since Flutter is for iOS and Android, please also see: https://github.com/stripe/stripe-android/issues/795

Currently there are some individuals trying to start something in that regard (https://pub.dartlang.org/packages/stripe_payment and https://pub.dartlang.org/packages/stripe_api), but that's incipient and I believe the Flutter community actually deserves official support from Stripe.

Flutter reached stable 1.0 and is growing very fast. We need Stripe there too.

**Comment by csabol-stripe** [comment]
@marcglasberg Thanks for the info and request! As @mshafrir-stripe mentioned, we likely won't have time to look at this in the near term, but I've filed an additional internal ticket to track investigating this for iOS

**Comment by angelocapone** [comment]
Are there any updates on this?

**Comment by msarkrish** [comment]
Any update on flutter stripe plugin in 2020?

**Comment by csabol-stripe** [comment]
Hi! A Stripe Flutter SDK isn't currently on our roadmap for 2020 but it is something we are actively monitoring developer interest in.

**Comment by Albert221** [comment]
+1, we're frequently using Stripe in our Flutter apps at @leancodepl and we'd love to have a good SDK for that instead of relying on fixed forks of 3rd parties. Both for iOS and Android.

**Comment by Arkangel12** [comment]
> Hi! A Stripe Flutter SDK isn't currently on our roadmap for 2020 but it is something we are actively monitoring developer interest in.

Maybe this could help you to know the number of developments and developers that could use Stripe SDK while you are still monitoring. Look at this [image](https://miro.medium.com/max/1400/1*vf_MidTWVahlez0h27E8bQ.png) from early August.

You can read the whole post [here](https://medium.com/flutter-community/what-does-a-flutter-developer-look-like-in-2020-59a7147024af)

**Comment by thorsten-stripe** [comment]
We're working with the Flutter community on a new package: https://github.com/flutter-stripe/flutter_stripe

It is currently in beta, but we'd love for you to test it out and provide feedback there. Thanks.
