### ISSUE TITLE
STPAddCardViewController top spacing on iOS9

### ISSUE THREAD

**Issue by jolson474** [stripe/stripe-ios#1130]
## Summary

On iOS 9 the STPAddAddCardViewController content is up behind the nav bar without an inset which results in the card icon being clipped.   This does not occur on iOS 12.  (Suspect iOS 10 as well, but am not able to verify that)

Not a huge deal, but thought you'd want to deliver best possible experience to users.

## Code to reproduce

Bring up STPAddCardViewController on iOS9 (e.g. `stripePaymentContext.pushPaymentMethodsViewController() `)
## iOS version

9.3 Simulator.  
## Installation method

CocoaPods
## SDK version

` - Stripe (14.0.0)`
## Other information

<img width="504" alt="screen shot 2019-02-04 at 7 11 04 pm" src="https://user-images.githubusercontent.com/3170557/52247899-63c9c200-28b1-11e9-8530-48e9772e8b25.png">
<img width="504" alt="screen shot 2019-02-04 at 7 08 39 pm" src="https://user-images.githubusercontent.com/3170557/52247935-8cea5280-28b1-11e9-9670-6caa0398cb78.png">

**Comment by csabol-stripe** [comment]
@jolson474 Thanks for the report -- this is definitely something I'd like to fix in the next release and am tracking internally

**Comment by davidme-stripe** [comment]
Though we've dropped support for iOS 9, this is still happening on iOS 10 + iPhone 5s. (It's fine on iOS 11.)

**Comment by davidme-stripe** [comment]
We dropped iOS 10, too. Closing this out.
