### ISSUE TITLE
Stdc++ file issue 

### ISSUE THREAD

**Issue by Repair-Desk** [stripe/stripe-ios#1134]
Unfortunately we are not able to use libstdc++.6.0.9. lib file in Xcode 10 and your "Stripe" integration still using it . if Stripe want to set any other manually setting then we are ready to go with that but we need permanent solutions on that
I am using  pod 'Stripe'

if you have to suggest any version where it is fixed then it would be great for us

**Comment by csabol-stripe** [comment]
Hi @Repair-Desk ,
Could you clarify which version of the SDK you are currently integrating with? We already have `CLANG_CXX_LIBRARY = libc++` for our build configuration so I wouldn't expect this to be an issue. In the meantime it sounds like you can copy libstdc++ from Xcode 9 to unblock (e.g. https://stackoverflow.com/questions/50694822/xcode-10-ios-12-does-not-contain-libstdc6-0-9)
