### ISSUE TITLE
STPPaymentCardTextField w/ appropriate keyboard for iPad

### ISSUE THREAD

**Issue by troypayne** [stripe/stripe-ios#1136]
I've tried using a plug-in-play custom keyboard along with STPPaymentCardTextField for iPad but it doesn't play nicely. This custom keyboard simply uses very large numeric buttons for easy input. I think this would be a nice value add if automatically baked in

**Comment by csabol-stripe** [comment]
Hi @troypayne,

Are you using a third-party keyboard, i.e. not the standard iOS one? If so could you share which keyboard you're using so we can take a look at our end? Any screenshots you could provide would also be greatly appreciated :)

**Comment by troypayne** [comment]
@csabol-stripe not a custom hardware keyboard, custom software keyboard. I've attached a screenshot of a similar product that uses a custom soft keyboard for this very thing. Since we're actively building a POS with the new Stripe Terminal, it's nice to have this option for speed whenever card reader issues come up. 

See attached:
![img_0014 1](https://user-images.githubusercontent.com/3412692/52876030-e1989380-3123-11e9-9abd-bd19fd5c8657.PNG)

**Comment by csabol-stripe** [comment]
@troypayne I've filed an internal ticket for us to track potentially adding something like this in the future, but as it's not currently scheduled I'm going to close this issue. If there is an issue integrating with a specific custom keyboard that you are trying to use let us know and we'll see what we can do :)
