### ISSUE TITLE
Custom Source

### ISSUE THREAD

**Issue by lightninglu10** [stripe/stripe-ios#1144]
According to the Stripe docs, we can create a custom source. Since the stripe SDK doesn't have wechat, we want to create the source with wechat.

The Android SDK exposes this method: https://github.com/stripe/stripe-android/blob/master/stripe/src/main/java/com/stripe/android/model/SourceParams.java#L238-L240

To create a custom source. Does the iOS SDK have something similar? It looks like there's a bunch of enum types laying around: "STPSourceTypeAlipay", that I'm not quite sure what it does. If we want to create a wechat integration, is there an easy way to do so?

**Comment by csabol-stripe** [comment]
Hi @lightninglu10 ! Sorry we have not responded yet! You should be able to leave the `type` property of `STPSourceParams` as `STPSourceTypeUnknown` and then call `-(void)createSourceWithParams:(STPSourceParams *)params completion:(STPSourceCompletionBlock)completion` on `STPAPIClient`. We are also working on adding native wechat pay support
