### ISSUE TITLE
Dont get any payment methods beside apple pay and credit cards using build-in UI

### ISSUE THREAD

**Issue by MaiquanNguyen** [stripe/stripe-ios#1153]
<img width="1092" alt="payment methods" src="https://user-images.githubusercontent.com/4607287/54741771-08019100-4bf2-11e9-9b82-8a4cc2cb60f2.png">

I am following the instruction from here https://stripe.com/docs/mobile/ios, but beside apple pay and credit cards, other payment methods does not appear. Although i already enable them in dashboard. 
When creating stripe customer, we only set email for it. Is anything we need to send alongside email when create or retrieving customer ?
iOS SDK version: 15.0.0
iOS screenshot
![screen-shot](https://user-images.githubusercontent.com/4607287/54741977-a1c93e00-4bf2-11e9-95aa-e93e20afa49a.png)

**Comment by aliriaz-stripe** [comment]
Hi @ MaiquanNguyen , currently STPPaymentOptionsViewController only supports Apple Pay and cards at the moment. 
STPCard, STPSource and STPApplePay are the only supported STPPaymentOptions [0] on STPPaymentOptionsViewController.

[0] https://stripe.dev/stripe-ios/docs/Protocols/STPPaymentOption.html
