### ISSUE TITLE
Received unknown parameter error when confirming PaymentIntent using SDK

### ISSUE THREAD

**Issue by RobinSiep** [stripe/stripe-ios#1163]
## Summary
I'm encountering an issue when confirming a payment intent (by calling `STPAPIClient.shared().confirmPaymentIntent()`). I'm trying to use a credit card as a payment method.

```
Error Domain=com.stripe.lib Code=50 "Received unknown parameter: payment_method_data[card][token]" UserInfo={com.stripe.lib:ErrorMessageKey=Received unknown parameter: payment_method_data[card][token], com.stripe.lib:StripeErrorCodeKey=parameter_unknown, com.stripe.lib:StripeErrorTypeKey=invalid_request_error, com.stripe.lib:ErrorParameterKey=paymentMethodData[Card][Token], NSLocalizedDescription=Received unknown parameter: payment_method_data[card][token]}
```

Although I'm not quite sure, I think this might be a bug. Apologies if I'm actually just misunderstanding something but I believe I'm just following the steps laid out in the documentation. As I'm using the SDK rather than calling the API directly the `invalid_request_error` comes unexpected.

Thanks in advance!

## Code to reproduce
I'm doing the following, while using `STPAddCardViewControllerDelegate`:
```
let paymentIntentParams = STPPaymentIntentParams(clientSecret: clientSecret)

...

func addCardViewController(_ addCardViewController: STPAddCardViewController, didCreateToken token: STPToken, completion: @escaping STPErrorBlock) {
	let cardParams = STPPaymentMethodCardParams()
	cardParams.token = token.tokenId
  let paymentMethodParams = STPPaymentMethodParams(card: cardParams, billingDetails: nil, metadata: nil)
  paymentIntentParams?.paymentMethodParams = paymentMethodParams
	completion(nil)
	addCardViewController.dismiss(animated: true)
}

@IBAction func pay(_ sender: TransitionButton) {
    payUsingIntent()
}
    
func payUsingIntent() {
    let client = STPAPIClient.shared()
    client.confirmPaymentIntent(with: paymentIntentParams!, completion: { (paymentIntent, error) in
        if let error = error {
			// This is where I catch the error.
            print(error)
        } else if let paymentIntent = paymentIntent {
            if paymentIntent.status == .requiresAction {
                if let redirectContext = STPRedirectContext(paymentIntent: paymentIntent, completion: {_, _ in }) {
                    self.redirectContext = redirectContext
                    // opens SFSafariViewController to the necessary URL
                    redirectContext.startRedirectFlow(from: self)
                } else {
                    print("No redirectContext")
                }
            } else {
                print("No action required")
            }
        }
    })
}
```

## iOS version
iPhone Xs running iOS 12.2

## Installation method
Using Carthage.

## SDK version
15.0.0

## Other information
Using API version `2019-03-14`.

**Comment by aliriaz-stripe** [comment]
Hi @RobinSiep , thanks for writing in!
This was a bug on v15.0.0, the fix made it in to v15.0.1, upgrading to v15.0.1 should work for you!

**Comment by RobinSiep** [comment]
Updating to v15.0.1 did the trick, thanks for the fast response!

**Comment by indigothm** [comment]
Still have this issue. I am using:
`cardParams.token = token.tokenId`
with token collected from 'didCreateToken' method.  The code is almost identical to the one above. Stripe version 15.0.1

**Comment by indigothm** [comment]
Full code:
`func addCardViewController(_ addCardViewController: STPAddCardViewController, didCreateToken token: STPToken, completion: @escaping STPErrorBlock) {

        let cardParams = STPPaymentMethodCardParams()
        cardParams.token = token.tokenId
        let paymentMethodParams = STPPaymentMethodParams(card: cardParams, billingDetails: nil, metadata: nil)

        //let paymentMethodParams = STPPaymentMethodParams(card: cardParams, billingDetails: billingDetails, metadata: nil)
        let clientSecret = paymentIntentData?.token ?? "" //recieve from the API
        let paymentIntentParams = STPPaymentIntentParams(clientSecret: clientSecret)
        paymentIntentParams.paymentMethodParams = paymentMethodParams
        //paymentIntentParams.returnURL = "your-app://stripe-redirect"

        let client = STPAPIClient.shared()
        client.confirmPaymentIntent(with: paymentIntentParams, completion: { (paymentIntent, error) in
            if let error = error {
                // handle error
                print(error)
            } else if let paymentIntent = paymentIntent {
                // see below to handle the confirmed PaymentIntent
                if paymentIntent.status == .requiresAction {
                    guard let redirectContext = STPRedirectContext(paymentIntent: paymentIntent, completion: { clientSecret, redirectError in
                        // Fetch the latest status of the Payment Intent if necessary
                        STPAPIClient.shared().retrievePaymentIntent(withClientSecret: clientSecret) { paymentIntent, error in
                            // Check paymentIntent.status
                            print(paymentIntent)
                        }
                    }) else {
                        // This PaymentIntent action is not yet supported by the SDK.
                        return;
                    }
                    // Note you must retain this for the duration of the redirect flow - it dismisses any presented view controller upon deallocation.
                    self.redirectContext = redirectContext

                    // opens SFSafariViewController to the necessary URL
                    redirectContext.startRedirectFlow(from: self)
                } else {
                    // Show success message
                    print("Success")
                }
            }
            self.navigationController?.popViewController(animated: true)
        })


    }`

**Comment by renatamakuch** [comment]
@indigothm did you find a solution? I struggle with this issue
@aliriaz-stripe I'm on newest version and still occurs, I have very similar integration like in comment above
