### ISSUE TITLE
Payment context payment options vc appears but never loads

### ISSUE THREAD

**Issue by bryanboyko** [stripe/stripe-ios#1165]
## Summary
paymentContext.presentPaymentOptionsViewController() presents a vc modally that shows loading state and never finishes loading. No errors are logged at all while XCode is running the app, including when each of the below three steps take place.

## Code to reproduce

1. Build STPCustomerEphemeralKeyProvider and corresponding endpoint. 

2. Setup STPCustomerContext and STPPaymentContext

```
...
        self.stripeClient = stripeClient
        self.customerContext = STPCustomerContext(keyProvider: stripeClient)
        self.paymentContext = STPPaymentContext(customerContext: customerContext)
        super.init()
        self.setupStripeContexts()
    }
    
    
    //MARK: Stripe contexts
    
    func setupStripeContexts() {
        
        paymentContext.paymentAmount = treatment.price
        paymentContext.paymentCurrency = treatment.priceCurrency
        paymentContext.delegate = self
    }
```

3. Check for publishable key and make call to presentPaymentOptionsViewController()

```
        guard !STPPaymentConfiguration.shared().publishableKey.isEmpty else {
            Logger.error("Please assign a value to `publishableKey` in StripeConstants.swift and make sure it is used to setup Stripe in AppDelegate.")
            return
        }
        
        
        if paymentContext.hostViewController == nil {
            paymentContext.hostViewController = viewController
        }
        // Present the Stripe payment methods view controller to enter payment details
        paymentContext.presentPaymentOptionsViewController()
```

## iOS version
12.1.4

## Installation method
Cocoapods

## SDK version
15.0.0

## Other information
- After resolving ephemeral key provider errors, it seems likely that the key provider is working as intended. 
- Both keys are correct because calls to create customers from the app (using test publish key) to my server (with the private key) are showing new customers in my Stripe dashboard.

**Comment by aliriaz-stripe** [comment]
Hi @bryanboyko , I tried to reproduce by following the steps you listed but I'm not able to reproduce this issue on my end.

Usually, The STPPaymentOptionsViewController constantly loading hints at an issue with the way you're implementing the createCustomerKey() delegate method on STPCustomerEphemeralKeyProvider. That would mean STPCustomerContext was not able to pre-fetch the customer.
You can refer to the docs on how to implement `createCustomerKey()`: https://stripe.com/docs/mobile/ios/standard#ephemeral-key

To verify that your STPCustomerContext is initialized properly, try calling `customerContext.retrieveCustomer` and logging out the `customer` or `error`. If it is properly initialized, you should get back an STPCustomer object in the completion block.
