### ISSUE TITLE
How to retrieve error from STPAddCardViewController didCreateToken

### ISSUE THREAD

**Issue by ibhavin** [stripe/stripe-ios#1166]
I have implemented `STPAddCardViewControllerDelegate` method as below:
```
func addCardViewController(_ addCardViewController: STPAddCardViewController, didCreateToken token: STPToken, completion: @escaping STPErrorBlock) {
        let token = token.tokenId
        print(token)
                
        self.navigationController?.popViewController(animated: true)
    }
```

Now, I want to know that if I got error in this method then how can I retrieve it.
I have to send tokenId, error or success message to my backend.

**Comment by ir-fuel** [comment]
I don't think you'll ever encounter an error where this will be called.
