### ISSUE TITLE
No cursor being shown on STPAddCardViewController

### ISSUE THREAD

**Issue by ir-fuel** [stripe/stripe-ios#1167]
This is using v15.0.1 (and was already the case in previous versions).

When showing `STPAddCardViewController` the fields do not contain a cursor. This is confusing for the user when there are multiple fields to fill out. I also did not find any property to modify this in the `STPTheme` class.

In the first screenshot I have the focus on the card number field, in the second one on the name field. It's not clear at all what field has the focus, unless you rely on the keyboard being shown (which no user will ever understand)

![IMG_9EC4FEF0F325-1](https://user-images.githubusercontent.com/1573715/56660487-e176c000-669f-11e9-971c-740ab661c011.jpeg)
![IMG_820C03F229EB-1](https://user-images.githubusercontent.com/1573715/56660491-e3408380-669f-11e9-89ab-67097958946d.jpeg)

**Comment by csabol-stripe** [comment]
Hi @ir-fuel, I've verified that I'm seeing the cursor on the add card screen in our Standard Integration app. Could you provide additional reproduction steps?

**Comment by davidme-stripe** [comment]
I'm closing this out, as we haven't received any other reports of it recently. It might have been an iOS bug. Please let me know if you see this again!
