### ISSUE TITLE
STPAddCardViewController Done button never in disabled state, but is disabled

### ISSUE THREAD

**Issue by ir-fuel** [stripe/stripe-ios#1168]
Version: 15.0.1

When using an `STPAddCardViewController` the `Done` button always looks as if it is enabled, even if the data to be sent out is incomplete. The behaviour is correct (the `Done` button does not respond to taps as long as all info isn't filled out) but it's confusing to the user because it looks as if `Done` can be pressed at all times (as you can with `Cancel` on the left hand side).

![IMG_820C03F229EB-1](https://user-images.githubusercontent.com/1573715/56660755-7da0c700-66a0-11e9-9c51-0a6d99c6a55b.jpeg)

**Comment by aliriaz-stripe** [comment]
Hi ir-fuel, on the vanilla version of STPAddCardViewController, the Done button does have a disabled state. Could you share how you are customizing the view controller on your end?

**Comment by ir-fuel** [comment]
This is what I do in my appDelegate

```
        STPTheme.default().accentColor = UIColor.white
        STPTheme.default().primaryBackgroundColor = UIColor.TTMain  // dark blue
        STPTheme.default().secondaryForegroundColor = UIColor.white

```

And I present the viewcontroller like this:
```
        let addCardViewController = STPAddCardViewController.init()
        addCardViewController.delegate = self
        
        let navigationController = UINavigationController(rootViewController: addCardViewController)
        
        navigationController.navigationBar.barTintColor = UIColor.TTMain  // dark blue
        navigationController.navigationBar.isTranslucent = false
        navigationController.navigationBar.tintColor = .white
        navigationController.navigationBar.titleTextAttributes = [NSAttributedStringKey.foregroundColor:UIColor.white]
        
        self.navigationController!.present(navigationController,animated:true)
```

**Comment by aliriaz-stripe** [comment]
Hi @ir-fuel , thanks for providing that!

The navigation bar button's disabled state is set from with `secondaryForegroundColor`. Currently, looks like you're setting both it and the `accentColor` to white, so it stays solid white in both cases. You should leave that out or set it to gray to see the disabled state.
