### ISSUE TITLE
Stripe checkout Webview extends under status bar

### ISSUE THREAD

**Issue by RTimal** [stripe/stripe-ios#117]
Hi, i just started using stripe checkout in my iOS app and the webview extends 
under the status bar. Is there an easy way to change this behavior using the current api? Thank you.

![screen shot 2015-02-12 at 12 09 41 am](https://cloud.githubusercontent.com/assets/1885682/6162137/951106ec-b24b-11e4-9a46-bf03b8683c77.png)

**Comment by jamesreggio** [comment]
Hi @RTimal, we're aware of the issue and will be fixing it on our end (in Checkout).

I'll leave this open until we've shipped a fix.

**Comment by RTimal** [comment]
@jamesreggio Thank you!

**Comment by Shayanzadeh** [comment]
Looks like they've fixed it! 😄
![img_1664](https://cloud.githubusercontent.com/assets/1910721/6383749/f6f078e2-bd4b-11e4-9f80-f02b785d867a.PNG)

**Comment by jflinter** [comment]
Indeed we have. Cheers!

**Comment by mbrochh** [comment]
@RTimal sorry to bother, could you describe how you managed to see that Checkout.js with mobile styles in a mobile WebView? For me it shows the usual stripe popup box when I place the Checkout.js button in a WebView.
