### ISSUE TITLE
createTokenWithConnectAccount uses old BETA Connect SDK - Cannot Create Connect Account

### ISSUE THREAD

**Issue by realityworks** [stripe/stripe-ios#1170]
## Summary

This is the current body of what the function sends : 
account[legal_entity][address][city]=SUFFERN&account[legal_entity][address][country]=US&account[legal_entity][address][line1]=250%20ROUTE%2059&account[legal_entity][address][line2]=&account[legal_entity][address][postal_code]=10901-5315&account[legal_entity][address][state]=NY&account[legal_entity][dob][day]=26&account[legal_entity][dob][month]=4&account[legal_entity][dob][year]=1954&account[legal_entity][first_name]=Peter&account[legal_entity][gender]=female&account[legal_entity][last_name]=Suwara&account[legal_entity][personal_id_number]=123-12-3123&account[legal_entity][phone_number]=%2B12312312312&account[legal_entity][ssn_last_4]=1231&account[legal_entity][type]=individual&account[legal_entity][verification][document]=file_1ETTRILmkxRCvNwwwZ7GKcvw&account[legal_entity][verification][document_back]=file_1ETTRILmkxRCvNwwRyUwIKEH&account[tos_shown_and_accepted]=true&muid=AA324BC5-2CD3-47D0-A79C-346E3F087412&time_on_page=230682

This is the incorrect format, for instance in the new Connect SDK, legal_entity should be individual.

**Comment by realityworks** [comment]
SDK Version 15.0.1

We are going to fork this framework as it looks like it's a bit behind and likely fix it ourselves. :)

**Comment by ChrisLahaye** [comment]
@realityworks could you contribute your change to this repo?

**Comment by realityworks** [comment]
Hi @ChrisLahaye I already have and I provided a pull request, it's awaiting review.

**Comment by ChrisLahaye** [comment]
@realityworks Great thank you! I have contacted support regarding this issue with a reference to this issue.

**Comment by realityworks** [comment]
No worries Chris. We needed it done anyway so you the Stripe team might end up using some of the code changes. The fork supports both methods (old and new).

**Comment by csabol-stripe** [comment]
@realityworks @ChrisLahaye sorry we haven't commented here yet. We are working on updating the pinned API version in this SDK, which will include the new Connect API. Look for it in our next release :)
