### ISSUE TITLE
Subscriptions with Connect

### ISSUE THREAD

**Issue by 7er0** [stripe/stripe-ios#1171]
I am allowing my users to create plans on their stripe accounts, I understand that they have to do so on their own stripe accounts with the header:

```
stripe.plans.create({
    amount: amount,
    interval: "month",
    product: {
    name: name
},
    currency: "chf",
}, {
    stripe_account: accountID,
})
...
```

I managed to do that so far, however, when trying to delete that plan with the standard API method for deleting a plan, I get the error: "No such plan: plan_XXX"

So, I tried the following (again with an account header):

```
stripe.plans.del(planID, {
    stripe_account: accountID,
}).then((plan) => {
    res.status(200).send(plan)
}).catch((err) => {
    console.log(err, req.body)
});
...
```

However, this does not seem to be the right method for this, as I am getting this error: "Unexpected token {"

What is the right method to delete a plan on a stripe account? Will I encounter the same problem when updating one?

What else do I need to take into account while implementing subscriptions in Stripe Connect? (Maybe give me some sources, as I am not able to find that many).

**Comment by aliriaz-stripe** [comment]
Hi 7er0, thanks for writing in!

This question is better suited to the Support team at https://support.stripe.com/contact , Please write in, the team there will be able to help you out! Also include the entire error message you're seeing.

Closing this issue as it isn't related to stripe-ios repo.
