### ISSUE TITLE
Payment intent not supported in stripe 15.0.1 sdk

### ISSUE THREAD

**Issue by ajithkumark771** [stripe/stripe-ios#1174]
Not redirecting to safari for getting OTP. Flow goes to the else case which shows payment intent action not supported by sdk. In below code , checking redirectcontext goes to the else case

```
if (paymentIntent.status == STPPaymentIntentStatusRequiresAction) {
                 // Note you must retain this for the duration of the redirect flow - it dismisses any presented view controller upon deallocation.
                 STPRedirectContext *redirectContext = [[STPRedirectContext alloc] initWithPaymentIntent:paymentIntent completion:^(NSString *clientSecret, NSError *redirectError) {
                     // Fetch the latest status of the Payment Intent if necessary
                     [[STPAPIClient sharedClient] retrievePaymentIntentWithClientSecret:clientSecret completion:^(STPPaymentIntent *paymentIntent, NSError *error) {
                         // Check paymentIntent.status
                     }];
                 }];
                 if (redirectContext) {
                     // opens SFSafariViewController to the necessary URL
                    
                     [redirectContext startRedirectFlowFromViewController:self];
                 } else {
control goes here -->                
                        [self dismissViewControllerAnimated:YES completion:nil];
                     // This PaymentIntent action is not yet supported by the SDK.
                 }
             } 
```

**Comment by spacemonkey92** [comment]
@ajithkumark771 
I have the same issue. Any update?

**Comment by ajithkumark771** [comment]
Hi,
  My issue is resolved automatically without making any change in code .
Now I'm facing problem with return URL. Can you briefly explain please
explain . I can help you with my code and reply mail mail from stripe
support.

**Comment by yoitsro** [comment]
I'm trying to retrieve a `PaymentIntent` with `STPAPIClient.shared().retrievePaymentIntent`, and the response does not return an error, but instead, when printing the `paymentIntent` response, this is what's printed:

```
Printing description of paymentIntent:
expression produced error: error: /var/folders/pr/c7mztdl11n30fb5d1198wrd40000gn/T/expr7-f8d47d..swift:1:87: error: 'STPPaymentIntent' is not a member type of 'Stripe'
Swift._DebuggerSupport.stringForPrintObject(Swift.UnsafePointer<Swift.Optional<Stripe.STPPaymentIntent>>(bitPattern: 0x110e88f10)!.pointee)
```

I'd guess this is associated to the issues above. Any ideas?

**Comment by yoitsro** [comment]
I'm also experiencing this problem. Any ideas?

**Comment by aliriaz-stripe** [comment]
Hi all, appreciate everyone writing in!

I'll be closing this as this isn't an SDK issue/bug but rather an integration issue. 
If you have this issue, please write in to https://support.stripe.com/contact and we'll help you out!

**Comment by yoitsro** [comment]
@ajithkumark771 @spacemonkey92 To fix this, ensure you're confirming your payment intent using `STPAPIClient.shared().confirmPaymentIntent()` and make sure your payment intent has `returnURL` set.
