### ISSUE TITLE
Carthage and Xcode build fails due to file name and reference mismatch.

### ISSUE THREAD

**Issue by Pahitos** [stripe/stripe-ios#1179]
## Summary
- Build fails because Xcode can't find a file due do a name/reference mismatch.
- Here the files on the left end with `iDEAL`, the references to the file on disk (on the right) also end with `iDEAL`, but the underlying file when you open the folder is named `Ideal`.
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/18669007/57400923-96ca6d00-71a2-11e9-86b3-147da0627a39.png">

## Code to reproduce
- N/A

## iOS version
- N/A

## Installation method
- Carthage

## SDK version
- 15.0.1

## Other information
- This issue leads to build failures on some devices, but not the others for some reason. I don't know what exactly causes Xcode to ignore the case sometimes, but the file name and Xcode references should match either way.

**Comment by yuki-stripe** [comment]
Hey @Pahitos!  Could you also show the build failure?  I'm unable to repro this.

**Comment by Pahitos** [comment]
@yuki-stripe we had to fix this issue by manually renaming the files in Xcode. If you look at the `STPPaymentMethodiDEAL` file (and a few others with `iDEAL` suffix), it's greyed out. Not exactly sure why, but on one of our fresh computers that we were setting up didn't like that and basically wouldn't build because a file was "missing".

**Comment by yuki-stripe** [comment]
@Pahitos Interesting!  I'm going to close the issue then, but by default the macOS filesystem is case insensitive - I wonder if that machine's filesystem isn't.
