### ISSUE TITLE
Move Checkout to a subspec

### ISSUE THREAD

**Issue by loudnate** [stripe/stripe-ios#118]
Since the webview checkout flow is optional, it would be great to allow it to be omitted by making it a subspec

**Comment by jflinter** [comment]
Cool, I've updated our podspec to reflect this. It's still a default subspec for now, but you can get around it by only including `Stripe/Core` in your Podfile.

This is still only on the master branch; I'll be releasing a new pod version in the next few days (we're changing some things around this code anyways).
