### ISSUE TITLE
handleURLCallback returns false with 3d secure test card

### ISSUE THREAD

**Issue by ir-fuel** [stripe/stripe-ios#1183]
I am having the an issue using the 4000 0000 0000 3220 test card.

This is the url being sent to my app:

`myapp://stripe-redirect?payment_intent=pi_1EbTOoLUYJ3xCVptrGLZNDjt&payment_intent_client_secret=pi_1EbTOoLUYJ3xCVptrGLZNDjt_secret_QwtA6qGlxBNdGKIy8GA6TGmbV&source_type=card`

When I run
`let stripeHandled = Stripe.handleURLCallback(with: url)`

the result is `false`, however on server side it all works and when checking the customer the payment is marked as `succeeded`

The result is that the web view with the 3d secure test stays on screen. As soon as I tap `Done` however the completion handler of `STPRedirectContext(paymentIntent: paymentIntent!, completion:` is called and everything works as it should.

Stripe SDK 15.0.1

**Comment by aliriaz-stripe** [comment]
Hi @ir-fuel , thanks for writing in!

I'll be closing this as this looks like an integration issue (and not an SDK issue), so will continue handling this over Support email.

**Comment by ir-fuel** [comment]
To me it looks like a bug in the SDK, but ok :)
