### ISSUE TITLE
Integrations' Readmes contain 404 links

### ISSUE THREAD

**Issue by krrisztian** [stripe/stripe-ios#1189]
The [standard integration Readme](https://github.com/stripe/stripe-ios/blob/master/Example/Standard%20Integration%20%28Sources%20Only%29/README.md) (guide) and the Custom Integration Readme contain a link that shows a 404 at step 5. (Deploy to Heroku).

I looked around and found a v14 of a ready-to-deploy-heroku example server but that doesn't work with the standard integration example project (I believe that one was for the custom integration version). Didn't try it with the custom one.

**Comment by yuki-stripe** [comment]
Thanks for reporting, fixed in https://github.com/stripe/stripe-ios/pull/1190
