### ISSUE TITLE
Crash on iOS 7 when accessing variable returned from paymentRequestWithMerchantIdentifier()

### ISSUE THREAD

**Issue by indoracer** [stripe/stripe-ios#119]
I'm seeing this crash using your latest SDK on a Swift app. Our deployment target is iOS 7 and we are seeing the crash when running iOS 7 (not 8). The crash (EXC_BAD_ACCESS) happens at: if test != nil or whenever I access the test variable next.

    let test = Stripe.paymentRequestWithMerchantIdentifier(Constants.ApplePayMerchantID)

    if test != nil {
        println("not nil")
    }

**Comment by jflinter** [comment]
This is an annoying side-effect of bridged Objective-C code: on pre-iOS8, `paymentRequestWithMerchantIdentifier` returns `nil`. Unfortunately, Swift imports this method signature as returning a `PKPaymentRequest!`, so when you try and access the variable you get a runtime error.

To fix this, simply change your code to
```
if let test = Stripe.paymentRequestWithMerchantIdentifier(Constants.ApplePayMerchantID) {
    println("not nil")
}
```

We'll be able to fix this as soon as Xcode 6.3 publicly released, as the new version of Clang supports [nullability annotations](http://nshipster.com/swift-1.2/#nullability-annotations). That should be another week or two (opening as a separate issue in #120).

For more information on all of this, check out the "working with nil" section of https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html .

Thanks for writing in!
