### ISSUE TITLE
STPCard brand 'amex' is unknown

### ISSUE THREAD

**Issue by tobyaherbert** [stripe/stripe-ios#1191]
Hey there, I've been upgrading an app to use the PaymentMethods API for saving cards and have noticed a small issue when using the ```brandFromString:``` method on ```STPCard```.

It looks like the raw value ```american express``` is used to represent an American Express card, but the new PaymentMethods API returns the brand ```amex``` which results in an unknown brand.

I've forked this library and have added ```amex``` as an additional clause in the if statement.

Should I submit a PR or is there a reason that this I shouldn't be checking the brand in this way?

Thanks :)

## Code to reproduce
[STPCard brandFromString:@"amex"] -> STPCardBrandUnknown

**Comment by yuki-stripe** [comment]
Thanks a ton for filing this!  

You are right - `STPPaymentMethodCard` needs its own map of API strings -> `STPCardBrand` values.  It looks like the two differences are 'amex' vs 'american express' and 'diners' vs 'diners card'. 

I'm fixing this in https://github.com/stripe/stripe-ios/pull/1195.

**Comment by tobyaherbert** [comment]
No problem!

Thanks. 👍
