### ISSUE TITLE
STPRedirectContext dismissing the presenting view controller when started from a modal view controller.

### ISSUE THREAD

**Issue by gwynantj** [stripe/stripe-ios#1199]
## Summary
When starting the redirect flow using the method documented here from a view controller that has already been presented modally: https://github.com/stripe/stripe-ios/blob/9ae593525c94d3a385305f25672894b1448cedc4/Stripe/PublicHeaders/STPRedirectContext.h#L176

The safari view controller is presented on the presenting view controller (modally) as seen here: https://github.com/stripe/stripe-ios/blob/9ae593525c94d3a385305f25672894b1448cedc4/Stripe/STPRedirectContext.m#L174

Now the problem arises when the redirect context is finished. When it tries to dismiss the modal view controller it actually dismisses the presenting view controller and not the presented view controller (SFSafariViewController). See here: https://github.com/stripe/stripe-ios/blob/9ae593525c94d3a385305f25672894b1448cedc4/Stripe/STPRedirectContext.m#L324

A fix would be to dismiss the safari view controller and not the presenting view controller.

i.e. like so?
```
[self.safariVC dismissViewControllerAnimated:YES completion:nil];
```

## Code to reproduce

Just start the redirect flow from a modally presented view controller. The modal view controller will be dismissed and the Safari view controller

## iOS version

iOS 12

## Installation method

Carthage

## SDK version

15.0.1

**Comment by yuki-stripe** [comment]
Hey @gwynantj!  

The docs for `dismissViewControllerAnimated:completion:` state: 

> The presenting view controller is responsible for dismissing the view controller it presented. If you call this method on the presented view controller itself, UIKit asks the presenting view controller to handle the dismissal.

My understanding is that we are using this API correctly - can you tell me more about your navigation stack here?  Are there other modals between the `presentingViewController` and the safari view controller?

**Comment by gwynantj** [comment]
Hey @yuki-stripe.

Yes I understand that the presenting view controller should be responsible of dismissing the view controller, but the problem I have is that the presenting view controller was presented modally. So in turn instead of dismissing the Safari view controller it will dismiss my presenting view controller and break the checkout flow.

I have no control over this because it's inside the stripe sdk. Another possible fix would be to have a delegate method to the client app and they can be responsible of dismissing the view controller.

**Comment by yuki-stripe** [comment]
I think I'm misunderstanding something - in a situation where ViewController A presents ViewController B presents ViewController C, you're saying calling `c.presentingViewController?.dismiss()` results in both C and B being dismissed?

**Comment by gwynantj** [comment]
Ok so the issue wasn't with the dismiss method at all, it was a timing issue.

Essentially STPRedirectContext tries to dismiss presentedViewController when it's complete and when it's deallocated. In my case both were happening nearly instantaneous which caused a double dismiss.

Closing due to the fact it's not the method causing the issue it's the way you try to dismiss the presented view controller when redirect is complete and when it's deallocated.
