### ISSUE TITLE
Extra step `Return to Merchant`

### ISSUE THREAD

**Issue by xieweizhi** [stripe/stripe-ios#1201]
## Summary
Some credit cards that will show extra page after 3ds authorized. This is reproducible.

![image](https://user-images.githubusercontent.com/1779863/59482090-eb47c300-8e99-11e9-95f1-0a82b8844e18.png)

Testing Card:
4000000000003063

Is this step required? Or can we customize it to return to {merchant name}?

Duplicate issue of this one for Android SDK.[issues/243](https://github.com/stripe/stripe-android/issues/243)

## iOS version
Simulator iOS 12.2

## Installation method
Cocoapods

## SDK version
15.0.1

**Comment by mshafrir-stripe** [comment]
@xieweizhi thanks for filing

**Comment by Reyske** [comment]
Same problem here, doens't even translate in other languages..

**Comment by yuki-stripe** [comment]
You can have this webview automatically dismiss itself or change which page the user is redirected to after the flow completes by passing a returnURL - see https://stripe.com/docs/mobile/ios/authentication#return-url

**Comment by caseyryan** [comment]
The page never dismisses and the button doesn't work. Even though I have a correct custom scheme. The url actually gets passed to my app, the only problem is that the webview remains  until I press a "close" button

**Comment by yuki-stripe** [comment]
Hi @caseyryan, 

Could you try forwarding the URL in your App/SceneDelegate as well? Here's some [sample code](https://stripe.com/docs/payments/grabpay/accept-a-payment#set-up-a-return-url) for that.

**Comment by caseyryan** [comment]
> Hi @caseyryan,
> 
> Could you try forwarding the URL in your App/SceneDelegate as well? Here's some [sample code](https://stripe.com/docs/payments/grabpay/accept-a-payment#set-up-a-return-url) for that.

Could you be more specific, please? This  URL leads to a huge document with a lot of code examples that are absolutely not related to the problem

**Comment by livnunes** [comment]
> 
> 
> > Hi @caseyryan,
> > Could you try forwarding the URL in your App/SceneDelegate as well? Here's some [sample code](https://stripe.com/docs/payments/grabpay/accept-a-payment#set-up-a-return-url) for that.
> 
> Hi! Could you be more specific, please? This URL leads to a huge document with a lot of code examples that are absolutely not related to the problem. If you just mean that I should set up a returnUrl, I did it. I even tried to pass https://google.com there instead of my deep link. It was successfully redirected to Google which means the link is really passing correctly. But it never closes the safari browser in the end. At least on iOS 14.2. I'm gonna test it on iOS 12 tomorrow

Hi, I'm having the same problem and currently using iOS 14.4, actually trying to redirect back to the app using an url like myapp://, but for some reason although the app receives and redirects to the url fine, the page doesn't close at all.
