### ISSUE TITLE
STPShippingAddressViewController does not use billing address if instrument is not an STPCard

### ISSUE THREAD

**Issue by karlr-stripe** [stripe/stripe-ios#1209]
## Summary

The Shipping view controller has a button "Use billing" that will copy the billing address of a card, to avoid the user needing to enter that information twice when e.g. going through the flow of using the STPPaymentContext to complete a payment. For example, with 

```
STPPaymentConfiguration.shared().requiredShippingAddressFields = [.postalAddress]
STPPaymentConfiguration.shared().requiredBillingAddressFields = STPBillingAddressFields.full
```

<img src="https://user-images.githubusercontent.com/38090489/60335621-439cbb80-9996-11e9-8f70-fa1ec907aa8d.png" width="50%" height="50%">
<img src="https://user-images.githubusercontent.com/38090489/60335629-48616f80-9996-11e9-88c2-eb89fc78d760.png" width="50%" height="50%">

However, it looks like this only works if using Card objects, and not Source(or PaymentMethods):

https://github.com/stripe/stripe-ios/blob/1c5505f30e035adf482e02112180ff859959a08b/Stripe/STPShippingAddressViewController.m#L51-L56

If you're not using Cards, then the option won't appear, which makes it less convenient for customers to check out.

## Code to reproduce

```
STPPaymentConfiguration.shared().requiredShippingAddressFields = [.postalAddress]
STPPaymentConfiguration.shared().requiredBillingAddressFields = STPBillingAddressFields.full
STPPaymentConfiguration.shared().createCardSources = true
```
and integrate the STPPaymentContext.

## iOS version

11.4
## Installation method

Carthage

## SDK version

15.0.1

**Comment by yuki-stripe** [comment]
@karlr-stripe Thanks for filing - tracking internally here https://jira.corp.stripe.com/browse/IOS-1278

**Comment by yuki-stripe** [comment]
Fixed in https://github.com/stripe/stripe-ios/pull/1278
