### ISSUE TITLE
'Stripe.Type' does not have a member named paymentRequestWithMerchantIdentifier

### ISSUE THREAD

**Issue by cartickn** [stripe/stripe-ios#124]
I am trying out the Swift sample and getting the following error.

'Stripe.Type' does not have a member named paymentRequestWithMerchantIdentifier

```
            let paymentRequest = Stripe.paymentRequestWithMerchantIdentifier(appleMerchantId)
```

'STPAPIClient' does not have a member named 'createTokenWithPayment'
```
        let apiClient = STPAPIClient(publishableKey: stripePublishableKey)
        apiClient.createTokenWithPayment(payment, completion: { (token, error) -> Void in
 ```

I have this Swift project set-up with Cocoapods with 'use_frameworks!' in pod file.

https://github.com/cartickn/Stripe-SwiftSample

Here is the sample project to reproduce the error. I'm sure this is programmer. I'd really appreciate any guidance to resolve this error.

**Comment by jflinter** [comment]
Hi there,
It seems like you've figured this out in https://github.com/cartickn/Stripe-SwiftSample/commit/980e8a765cd8735bd05a74e8f23b29194da9dcfc, so I'm going to close this for now. (For future people reading this, don't forget to add `Stripe/ApplePay` to your `Podfile` if you're going to use Apple Pay code, which our example apps do).
