### ISSUE TITLE
Nested Stripe3DS2.framework breaks app distribution with ERROR ITMS-90205, ERROR ITMS-90206

### ISSUE THREAD

**Issue by olegdanu-newstore** [stripe/stripe-ios#1241]
## Summary

Stripe release Version 16.0.0 introduces support to 3DS2 authentication. It comes as a nested framework inside the main Stripe.framework.
This breaks app distribution with errors: ERROR ITMS-90205, ERROR ITMS-90206.

## iOS version

12.2

## Installation method

* Carthage

## SDK version
  16.0.0

## Other information

<img width="377" alt="Screen Shot 2019-07-20 at 10 50 15" src="https://user-images.githubusercontent.com/15032228/61576052-4a25db00-aadd-11e9-9bde-f4e1e9c7fcdb.png">
<img width="1239" alt="Screen Shot 2019-07-20 at 10 50 29" src="https://user-images.githubusercontent.com/15032228/61576079-be607e80-aadd-11e9-9a79-2b8d27019f54.png">

**Comment by yuki-stripe** [comment]
Thanks for reporting this @olegdanu-newstore, we're looking into this.

**Comment by yuki-stripe** [comment]
@olegdanu-newstore I have a branch that removes `Stripe3DS2.framework` from `Stripe.framework` and instead adds it as a Cartfile dependency.  This appears to work on my test project, could you try changing your Cartfile to point to `yuki-carthage-fix` and letting me know if you still run into issues?

I believe you'll need to:
1. Change your Cartfile line to: `github "stripe/stripe-ios" "yuki-carthage-fix"`
2. Drag the `Carthage/Build/iOS/Stripe3DS2.framework` to Linked Frameworks and Libaries
3. Add Stripe3DS2 framework to `input.xcfilelist`, `output.xcfilelist`

**Comment by olegdanu-newstore** [comment]
@yuki-stripe looks like your proposed solution resolves the issue.

**Comment by olegdanu-newstore** [comment]
@yuki-stripe What are the plans for releasing this?

**Comment by yuki-stripe** [comment]
@olegdanu-newstore Glad to hear it works!  

We're working on a solution that won't require the separate `Stripe3DS2` dependency.  I'll let you know in this issue when that's ready - you'll probably need to undo what we did here and just update to the latest Stripe version e.g. 16.1.0.  I'd recommend waiting until then, but this should work in the mean time if you need it.

**Comment by yuki-stripe** [comment]
@olegdanu-newstore We just released [v16.0.1](https://github.com/stripe/stripe-ios/releases/tag/v16.0.1) that should fix this issue.  If that works for you too, can you close this issue?  Thanks!

**Comment by olegdanu-newstore** [comment]
@yuki-stripe thanks for the updates. I am not sure how fast I will be able to test this. So you can consider closing the ticket even before I confirm it working.

**Comment by rus64** [comment]
I was also experiencing this issue, just wanted to thank the team for fixing it so quickly!
