### ISSUE TITLE
stripe 16.0.0 issue

### ISSUE THREAD

**Issue by iKorich** [stripe/stripe-ios#1243]
STPCardParams.expiryMonth and STPCardParams.expYear is NSNumber instead NSUinteger

**Comment by yuki-stripe** [comment]
Hey @iKorich, could you explain the issue a bit more?

**Comment by iKorich** [comment]
hi @yuki-stripe, 

sorry STPPaymentMethodCardParams.

You need fill card paramms in UI, and after read it.

![debbug](https://i.imgur.com/PB5PZMH.png)

**Comment by iKorich** [comment]
Hi @yuki-stripe,

sorry, my mistake,
just found that STPCardParams switched to STPPaymentMethodCardParams
