### ISSUE TITLE
UI Examples do not compile

### ISSUE THREAD

**Issue by Drusy** [stripe/stripe-ios#1256]
## Summary
UI Examples do not compile using v16.0.1 tag.

## Code to reproduce
Tag v16.0.1 https://github.com/stripe/stripe-ios/releases/tag/v16.0.1

## iOS version
Any

## Installation method
As https://github.com/stripe/stripe-ios/blob/master/Example/UI%20Examples/README.md, open `Stripe.xcworkspace`

## Other information
`MockCustomerContext` override `STPCustomerContext` but override missing functions, such as `attachSource`, `selectDefaultCustomerSource`, `detachSource` resulting in the following error: `Method does not override any method from its superclass`

**Comment by davidme-stripe** [comment]
Thanks for reporting, @Drusy!
