### ISSUE TITLE
Stripe SDK changes Pods.xcode Xcode 10.2 & Greater

### ISSUE THREAD

**Issue by jwilliams-handy** [stripe/stripe-ios#1263]
## Summary
In versions of Xcode > 10.2 and installing Stripe via Cocoapods and including the `Pods` project in our repo we are seeing changes to our `project.pbxproj` that are being attributed to the Stripe SDK. After running a `pod install` and pushing up the changes, Xcode will make modifications to that file anytime the workspace is opened. There is an ongoing [issue](https://github.com/CocoaPods/CocoaPods/issues/8689) in the Cocoapods repo outlining this scenario happening to other developers. I was able to attribute it back to Stripe by removing pods in our `Podfile` one by one. 

## Code to reproduce
N/A

## iOS version
N/A

## Installation method
Cocoapods

## SDK version
We were currently using version 8.0.7. I found the issue started happening on version 8.0.5. I have tested this on the latest version 16.0.2 and it's still occurring.

## Other information
[This comment](https://github.com/CocoaPods/CocoaPods/issues/8689#issuecomment-486360917) explains how someone was able to stop making this reoccur. A similar fix could be done in this podspec.

**Comment by csabol-stripe** [comment]
@jwilliams-handy thanks for the heads up and investigation! We're tracking this internally now and keeping an eye on the cocoapods issue

**Comment by davidme-stripe** [comment]
I'm closing this out, as the related Cocoapods issue has been closed. We support Swift Package Manager now on Xcode 12, so you may want to try that and see if it resolves the issue.
