### ISSUE TITLE
Pod stripe 16.0.2 make APP crash

### ISSUE THREAD

**Issue by denglei022** [stripe/stripe-ios#1265]
I pod the Stripe 16.0.2 just now , it make APP crash. But  simulater testing OK.   When I pod 15.0.1 , it's no cash. 
There has no error log in console
## Code to reproduce 

 0x10293fdbc <+20>: ldr    x0, [x8, #0x260]
Thread 15: EXC_BAD_ACCESS (code=1, address=0x260)

## iOS version

iOS 12.2  iPhone 6S
## Installation method
pod

## SDK version
16.0.2

**Comment by csabol-stripe** [comment]
@denglei022 sorry to hear this is crashing for you! Would you be able to provide more details on when the crash is occurring? 

Also if you enable the `Exception breakpoint` in Xcode could you then provide us with the stack trace when the error occurs?

**Comment by denglei022** [comment]
I set Exception breakpoint , but I can't catch the error. 
This is my error screenshot. The console also has no error log, I don't know what happened.
<img width="1247" alt="WeChat48d74b61a818582d946d71152815b6b9" src="https://user-images.githubusercontent.com/15951751/62260798-d624f480-b445-11e9-8a97-b339bd5974ca.png">

**Comment by davidme-stripe** [comment]
Thanks for the screenshot, @denglei022. We're still looking into this one, but in the meantime I'd recommend you try again on v16.0.3. Also, does your app include OpenSSL directly?

**Comment by denglei022** [comment]
I get the same error when I use v16.0.3   . 
You are right !  The BaiduMapKit has libssl.a，so they have  conflicts. When I remove one of them, I will run success.So how can I solve  the problem ? I need all of them. You can pod 'BaiduMapKit', and you will know the error.  I hope you can fix it. Thanks.

![1564714258322](https://user-images.githubusercontent.com/15951751/62340967-0a66e680-b514-11e9-9a36-83e9f6e217c7.jpg)

**Comment by davidme-stripe** [comment]
This is really helpful, thanks! We’re looking into it now.

**Comment by davidme-stripe** [comment]
@denglei022, I'm having trouble reproducing the issue with the latest BaiduMapKit. I initialized a  BMKMapView and ran some 3D Secure 2 transactions, but I'm not seeing the same crash.

I've built a branch with a speculative fix, could you try it and let me know if it resolves your issue? In your Podfile, set:
`pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'davidme/test-ssl-prefix'`

**Comment by denglei022** [comment]
Thanks. I created a demo just now. And I pod all of them , everything is OK.
But when I used my own project, it crashed like before.I found the code that make crash.
`_bMapView = [[BMKMapView alloc]initWithFrame:self.view.frame];`
Then I tried pod `Stripe` 15.0.0 again, everything is OK.

Finally  I pod `Stripe` that you've built, that code won't make crash.
But the map display grid, and when I move the map , 
Sometimes it will crash.  I'm trying to solve them or find the reason. If you know the reason or fix it, please replay to me. Thank you very much.I am very anxious about that.
![1564816226417](https://user-images.githubusercontent.com/15951751/62408816-dddcc880-b600-11e9-9968-79b499744f0b.jpg)

**Comment by davidme-stripe** [comment]
Hey @denglei022, I've got something else for you to try. In your podfile, set:
`pod 'Stripe', :http => 'https://github.com/stripe/stripe-ios/releases/download/v16.0.2/stripe-ios-source-boringssl.zip' `

Then run `pod update` and, in Xcode, `Product -> Clean Build Folder`. Let me know if this fixes the crash you're seeing.

**Comment by denglei022** [comment]
Thanks!!!  Everything is OK.   You are awesome！

**Comment by davidme-stripe** [comment]
Great, thanks for your help in diagnosing this! We’ll get this change into our next release.

**Comment by denglei022** [comment]
If changed, this issue can be closed.

**Comment by davidme-stripe** [comment]
This is fixed in v16.0.4.
