### ISSUE TITLE
Xcode 10.1 invalid bitcode version

### ISSUE THREAD

**Issue by thomassenkman** [stripe/stripe-ios#1273]
## Summary
We updated to Stripe `v16.0.3`. It works well in debug, but when we try to archive our app in release mode with Xcode 10.1, we got this error:

> ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1001.0.46.4.0_0' Reader: '1000.11.45.5_0')', using libLTO version 'LLVM version 10.0.0, (clang-1000.11.45.5)' for architecture armv7

## Code to reproduce
N/A

## iOS version
N/A

## Installation method
Cocoapods

## SDK version
16.0.3

## Other information
N/A

**Comment by davidme-stripe** [comment]
Hi @thomassenkman, thanks for bringing this to our attention. We’ll build the next release with Xcode 10.1 to ensure compatibility. In the meantime, you should be able to work around this by using Xcode 10.2.

**Comment by thomassenkman** [comment]
Hi, thanks for having a look so quickly 👍
We can’t migrate to Xcode 10.2 because of an other dependency, we’ll wait for the next release then.

**Comment by davidme-stripe** [comment]
No worries, I've uploaded a branch to unblock you for now. In your Podfile, add `pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'davidme/xcode-101'`

**Comment by davidme-stripe** [comment]
This is fixed in v16.0.4.
