### ISSUE TITLE
use of "@import" break projects using

### ISSUE THREAD

**Issue by IvanBuravchenko95** [stripe/stripe-ios#1281]
## Summary
The bug is the same as in the related issue.
"Enable Modules (C and Objective-C)" feature is disabled in my build settings. So when I updated a pod, 12 files from pod are now broken with an error of "Use of '@import' when modules are disabled". I fixed this locally by checking if project has feature modules (see related issue) Can you please add this feature to fix when updating a pod? Thanks!

## iOS version
Doesn't matter

## Installation method
pod update Stripe (previously was 15.0.1)

## SDK version
16.0.3

## Related issue
https://github.com/stripe/stripe-ios/issues/220

**Comment by IvanBuravchenko95** [comment]
Affected classes:
STDSButtonCustomization.h
STDSCustomization.h
STDSFooterCustomization.h
STDSNavigationBarCustomization.h
STDSSelectionCustomization.h
STDSTextFieldCustomization.h
STPThreeDSButtonCustomization.h
STPThreeDSFooterCustomization.h
STPThreeDSLabelCustomization.h
STPThreeDSNavigationBarCustomization.h
STPThreeDSSelectionCustomization.h
STPThreeDSTextFieldCustomization.h

**Comment by yuki-stripe** [comment]
@IvanBuravchenko95 Thanks for reporting this, we can fix this in the next release.
