### ISSUE TITLE
Postal code issue with Canadian card asking for digits ZIP code

### ISSUE THREAD

**Issue by CallMeMeow** [stripe/stripe-ios#1282]
## Summary

Hello People,

We are currently using stripe to manage our payments in our iOS app and we are facing a problem around the postal code field of the `STPPaymentCardTextField` element. One of our customer has a Canadian card and it's asking her for a 4 to 6 digits ZIP code which can' t be a Canadian zip code. How is this field defined?

## Code to reproduce

```
private let paymentCardTextField = STPPaymentCardTextField()
self.paymentCardTextField.delegate = self
self.paymentCardTextField.postalCodeEntryEnabled = true
```

## iOS version

iOS 12.3.1

## Installation method

Cocoapods

## SDK version

15.0.1

## Other information

I have access to the payment intent if needed.
Found this that could be related:
https://github.com/stripe/react-stripe-elements/issues/20

**Comment by yuki-stripe** [comment]
Hi @CallMeMeow, 

Can you try setting `self.paymentCardTextField.countryCode = "CA"`?

**Comment by CallMeMeow** [comment]
Hi @yuki-stripe,

Oops, my bad I didn't see this property, it seems like it would solve our current use case but how would it work for customers that have US cards?

**Comment by yuki-stripe** [comment]
@CallMeMeow Could you set `countryCode` to the customer's country?   By default, we set it to user's current locale `[[NSLocale autoupdatingCurrentLocale] objectForKey:NSLocaleCountryCode]`.  https://github.com/stripe/stripe-ios/blob/d4e3170fab9ab940816ea28ea8084b48a842e764/Stripe/STPPaymentCardTextField.m#L339

**Comment by CallMeMeow** [comment]
@yuki-stripe We tried to change our region on our Apple ID yesterday to try to reproduce but it kept asking for a postal code and not a digital zip code. That being said, we might have messed up in our testing since the code you linked seems to be covering it.
For the time being setting the `countryCode` works for us!
Thank you very much for you help!
