### ISSUE TITLE
ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by jonassvalin** [stripe/stripe-ios#1288]
## Summary
We're attempting to update the stripes iOS SDK in our app to support Apple Pay. When attempting to build the application, we are seeing the following error(s):

```

❌  ld: symbol(s) not found for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

[10:35:59]: ▸       _STDSSL_PKCS7_get_CRLs in libStripe3DS2.a(pkcs7_x509.c.o)
[10:35:59]: ▸   "_STDSSL_pkcs8_pbe_decrypt", referenced from:
[10:35:59]: ▸       _PKCS12_handle_content_info in libStripe3DS2.a(pkcs8_x509.c.o)
[10:35:59]: ▸ ld: symbol(s) not found for architecture arm64
[10:35:59]: ▸ clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## iOS version
Have tried on 10.1 and 12.4, same issue for both.

## Installation method
Pods

## SDK version
16.0.4

## Other information
This seems to be related to some of the fixes you guys have already put out in the past few days with release 16.0.3 and 16.0.4. 

Based on what we saw in issue https://github.com/stripe/stripe-ios/issues/1266 we attempted to update to the latest iOS version, but it did not help.

**Comment by davidme-stripe** [comment]
Sorry for the trouble, we’re investigating this now.

**Comment by davidme-stripe** [comment]
It looks like your app or one of its dependencies may have Dead Code Stripping disabled. We've added this scenario to our tests, and we'll release an update later today that works with either setting.

**Comment by davidme-stripe** [comment]
This should be fixed in v16.0.5: Try it out and let us know if it resolves the issue.

**Comment by jonassvalin** [comment]
@davidme-stripe Hi David, sorry for the delayed response as I've been on holiday. We tried this out with the latest version and the code compiles properly now. Thanks for the fix!

**Comment by tudor07** [comment]
I still have this issue. Stripe v19.4.1

**Comment by davidme-stripe** [comment]
@tudor07 Please switch to v21.6.0 — the 3DS2 framework is open-source in that version, which significantly simplifies the build process.
