### ISSUE TITLE
STPCheckoutViewController Cancel Button

### ISSUE THREAD

**Issue by hakimny** [stripe/stripe-ios#129]
Hi There,

I have an issue with the cancel button when the view present itself, with a UINavigationBar that includes the Status Bar you need to keep hitting the "X" many time to trigger the dismiss event.

Any trick or workaround to solve this.

Thank you

Hakim

**Comment by jflinter** [comment]
We'll look into increasing the size of the tap target for that html element. Thanks for bringing this to our attention.
