### ISSUE TITLE
Update zip code format and placeholder based on card number in STPPaymentCardTextField

### ISSUE THREAD

**Issue by sregg** [stripe/stripe-ios#1292]
## Summary
The JS library seems to automatically switch between US Zip code (6 digits only) and postal code (free form string) based on the detected country of the credit card.
The Android SDK and iOS SDK don't see to have that behaviour.

## SDK version
16.0.4

**Comment by yuki-stripe** [comment]
Thanks for raising the issue @sregg, we're tracking this internally.

**Comment by davidme-stripe** [comment]
We've addressed this in v18.1.0. We don't want to rely on the detected country of the credit card, as the user's billing country may be outside that country. Instead, we always allow a free form string if we don't know the user's country, and we request the country before the postal code in address forms.
