### ISSUE TITLE
Webview based 3DSecure authentication always fails

### ISSUE THREAD

**Issue by Drusy** [stripe/stripe-ios#1295]
### Unexpected behavior

3D Secure authentication always fails in test mode even if "Complete Authentication" is pushed.
Return URL is configured, `Stripe.handleURLCallback(with: url)` is called and returns `true`

Error thrown is 
```
Error Domain=STPPaymentHandlerErrorDomain Code=5 "We are unable to authenticate your payment method. Please choose a different payment method and try again." UserInfo={NSLocalizedDescription=We are unable to authenticate your payment method. Please choose a different payment method and try again.}
```

### Expected behavior

The error should have `STPErrorMessageKey`, `STPStripeErrorTypeKey` with `insufficient_funds `

### Test card used

4000 0082 6000 3178 

This card requires authentication for one-time payments. All payments will be declined with an `insufficient_funds` failure code even after being successfully authenticated or previously set up.

## iOS version
iOS 12.4 | iOS 12.3.1

## Installation method
Carthage 

## SDK version
> github "stripe/stripe-ios" "v16.0.4"

**Comment by Drusy** [comment]
To complete the issue, all the other native authentication screens works like a charm

- 4000 0000 0000 3220 (Out of Band)
- 4000 0000 0000 3238 (One Time Passcode)
- 4000 0000 0000 3246 (Single Select)
- 4000 0000 0000 3253 (Multi Select)

Only the webview based authentication screen seem to have an unexpected behavior.

**Comment by yuki-stripe** [comment]
Thanks for the report @Drusy, we are fixing this right now in https://github.com/stripe/stripe-ios/pull/1291

**Comment by Drusy** [comment]
@yuki-stripe, the pull request added the error in `lastPaymentError` but the codes returned by the card `4000 0082 6000 3178` does not comply with the documentation.

I have:
`type: STPPaymentIntentLastPaymentErrorType.card` -> OK
`code: "card_declined"` -> OK, why not
`declineCode: nil` -> NOT OK, should be `insufficient_funds`

The documentation of the card `4000 0082 6000 3178` says we should expect a `insufficient_funds` decline code.

> This card requires authentication for one-time payments. All payments will be declined with an insufficient_funds failure code even after being successfully authenticated or previously set up.

**Comment by Pal-illuminz** [comment]
![Simulator Screen Shot - iPhone 6 - 2021-09-16 at 10 10 49](https://user-images.githubusercontent.com/75825421/133550563-cb0ee96f-a83a-4200-900e-40d42a6c47bb.png)

User not redirect to the app after failed or confirmation with the specific card.

**Comment by dhaval-dobariya** [comment]
@Pal-illuminz  I am also seeing this screen, any solution for this?
