### ISSUE TITLE
STPPaymentHandler - Cannot continue after the authentification failed 

### ISSUE THREAD

**Issue by nenadvulic** [stripe/stripe-ios#1299]
## Summary

In sandbox mode when `confirmPayment` is called and required a user authentification if this one failed, (the user click on `Failed authentification`), it's impossible to restart another authentification, event if [the intent is cancelled by the backend](https://stripe.com/docs/api/payment_intents/cancel) its seem's that the SDK considered the authentification is [still in progress ](https://github.com/stripe/stripe-ios/blob/6d17243be30b3d4630d86d3771d3d61141dd91e1/Stripe/Payments/STPPaymentHandler.m#L40)

## Code to reproduce

1. Create an intent with the backend
2. Called `- (void)confirmPayment:(STPPaymentIntentParams *)paymentParams
withAuthenticationContext:(id<STPAuthenticationContext>)authenticationContext
            completion:(STPPaymentHandlerActionPaymentIntentCompletionBlock)completion;` with the intent created as parameter and specify the `returnURL` with the app urlSchema
3. Click on `Fail Authentification` the return url is fired
4. Cancel the failed intent using https://stripe.com/docs/api/payment_intents/cancel
5. Create a new intent with the backend
6. Try to confirm it with  `- (void)confirmPayment:(STPPaymentIntentParams *)paymentParams
withAuthenticationContext:(id<STPAuthenticationContext>)authenticationContext
            completion:(STPPaymentHandlerActionPaymentIntentCompletionBlock)completion;`

## iOS version
iOS 12.4

## Installation method
cocoapod

## SDK version
16.0.3

**Comment by yuki-stripe** [comment]
Hi @nenadvulic,

Have you implemented your UIApplicationDelegate according to https://stripe.com/docs/mobile/ios/authentication#return-url?  It sounds like the SDK is not receiving the URL callback (this method is not called: https://github.com/stripe/stripe-ios/blob/6d17243be30b3d4630d86d3771d3d61141dd91e1/Stripe/Payments/STPPaymentHandler.m#L643).  

There shouldn't be a need to cancel the failed intent, as well.

**Comment by nenadvulic** [comment]
my bad thanks
