### ISSUE TITLE
STPAddCardViewController ZIP Code for Canadian Customers

### ISSUE THREAD

**Issue by payshake** [stripe/stripe-ios#1302]
Hi all,

I'm having an issue with my Canadian customers being prompted for a ZIP code on the STPAddCardViewController. The number pad and field validation make it impossible for customers to enter a postal code.

After digging around, I've found that the field is dependent on the user's defined Region in their device settings. This causes problems for users who may have moved, improperly setup their device, or are using the app in another country.

Is there any way for me to set the locale on STPAddCardViewController to match the device's current location? Alternatively, is there a way to force the ZIP code field to always be ASCII capable, rather than forced number pad? I'd rather my customers be able to pass a bad value and have the ZIP check fail on creating a token, rather than having them not be able to submit the form at all.

**Comment by yuki-stripe** [comment]
Hi @payshake,

Unfortunately I don't see a way to do that using `STPAddCardViewController`.  Internally, it uses `STPPaymentCardTextField`.  You can set its locale (and more) via https://stripe.dev/stripe-ios/docs/Classes/STPPaymentCardTextField.html#/c:objc(cs)STPPaymentCardTextField(py)countryCode.  

Setting this value to anything other than "US" causes it to display the default keyboard (https://github.com/stripe/stripe-ios/blob/d4e3170fab9ab940816ea28ea8084b48a842e764/Stripe/STPPaymentCardTextField.m#L361).

**Comment by payshake** [comment]
> Hi @payshake,
> 
> Unfortunately I don't see a way to do that using `STPAddCardViewController`. Internally, it uses `STPPaymentCardTextField`. You can set its locale (and more) via https://stripe.dev/stripe-ios/docs/Classes/STPPaymentCardTextField.html#/c:objc(cs)STPPaymentCardTextField(py)countryCode.
> 
> Setting this value to anything other than "US" causes it to display the default keyboard (
> 
> https://github.com/stripe/stripe-ios/blob/d4e3170fab9ab940816ea28ea8084b48a842e764/Stripe/STPPaymentCardTextField.m#L361
> 
> ).

Thanks Yuki,

I can't seem to access the `STPPaymentCardTextField` property of `STPAddCardViewController`. 

Just to be clear, I will need to replace `STPAddCardViewController` with our own UI leveraging `STPPaymentCardTextField` to fix this issue?

**Comment by davidme-stripe** [comment]
Sorry that this took so long to fix! We're addressing this in #1424.

**Comment by davidme-stripe** [comment]
This is fixed in v18.1.0!
