### ISSUE TITLE
Timeout value of 13 is less than 5

### ISSUE THREAD

**Issue by mikkoseppa** [stripe/stripe-ios#1310]
## Summary
When I try to confirm a PaymentIntent, I get an error: "Timeout value of 13 is less than 5". I have not set the timeout value so it is using the default value.

`Printing description of error:
Error Domain=STPPaymentHandlerErrorDomain Code=4 "There was an unexpected error -- try again in a few seconds" UserInfo={com.stripe.lib:ErrorMessageKey=There was an error in the Stripe3DS2 SDK., exception=Timeout value of 13 is less than 5, NSLocalizedDescription=There was an unexpected error -- try again in a few seconds}`

## Code to reproduce
```swift
let handler = STPPaymentHandler()
handler.confirmPayment(paymentIntentParams, with: context, completion: { (status, paymentIntent, error) in

})
```

## iOS version
12.1

## Installation method
Carthage

## SDK version
16.0.6

**Comment by mikkoseppa** [comment]
I get the same exact error even if I change `threeDSCustomizationSettings.authenticationTimeout`

**Comment by davidme-stripe** [comment]
Hi @mikkoseppa,

Can you try replacing `let handler = STPPaymentHandler()` with `let handler = STPPaymentHandler.sharedHandler`? I think that will solve the problem you're hitting. (And we should fix our API to prevent folks from creating an STPPaymentHandler directly!)

**Comment by mikkoseppa** [comment]
Thank you. That resolved the issue.
