### ISSUE TITLE
STPLegalEntityParams phone number not updating with token

### ISSUE THREAD

**Issue by Kevinw14** [stripe/stripe-ios#1313]
## Summary
I'm creating custom connect account's. When I go to update the accounts with the verification information. Everything gets updated except for phone number. The code below is what I'm using, creating a token, and sending it to my backend to update the account. First name, last name, SSN, all the others update like they should just not the phone number.

## Code to reproduce

```
let entityParams: STPLegalEntityParams = STPLegalEntityParams()
        
        entityParams.phoneNumber = "1234567890"

let accountParams = STPConnectAccountParams(legalEntity: entityParams)
        
        STPAPIClient.shared().createToken(withConnectAccount: accountParams) { (token, error) in
            if let error = error {
                print("ERROR: \(error.localizedDescription)")
                return
            }
            
            if let token = token {
                print("PHONE TOKEN: \(token)")
            }
        }
```

## iOS version
iOS 12.4

## Installation method
Cocoapods

## SDK version
15.0.1

**Comment by yuki-stripe** [comment]
Hi @Kevinw14 

I tried to repro this, and everything looks okay.  The call to update the Connect Account failed because the phone number was invalid (as expected).  Are you seeing an error when you call https://stripe.com/docs/api/accounts/update?

**Comment by Kevinw14** [comment]
I didn't want to put my phone number on here so I just put that string of numbers in the example above as a placeholder for how I'm formatting the number. When I put in my actual phone number it gives me a token, and I send that token to the backend. It returns an account object like it should but never updates it. I don't get any errors anywhere. 

```
stripe.accounts.update(body.accountID, {
    individual: {
      phone: body.phone
    }
  }, (err, account) => {

  })
```

I've used this to update it too and this will work, but just phone number token doesn't. Name, SSN, Address, and the other tokens work, just not phone number.

**Comment by yuki-stripe** [comment]
@Kevinw14 - Understood, this is super weird..could you send me the request id of the failing update call your backend is making?  I think you can find it by going to https://dashboard.stripe.com/test/logs? (or https://dashboard.stripe.com/logs for livemode) and clicking on the relevant request.  The ID looks like `req_yy5Fz2ez8PIJ9K`.  It's also sent as `request-id` in the header of the API response.

One thought, does the API version your backend match the client's (2015-10-12)?

**Comment by Kevinw14** [comment]
The backend API version is the latest one. I think 2019-08-14. I didn't realize that the client also had an API version.

I made two calls one changing the address & one changing the phone number

Address: req_aMRLo5Ls7sfdo9
Phone Number: ct_1FAhlZKAF1MayChZjfq4djLZ

It may be the mismatch of the API Versions. How do I update my client's API?

**Comment by yuki-stripe** [comment]
I have a PR to bump our API version that should go out next week https://github.com/stripe/stripe-ios/pull/1254.  

My last question is misleading though, sorry - a mismatch between client and backend *should* be okay.  I thought we're exercising some edge case here, but I can't repro it on my end.

I'm able to update the phone number of a connect account by first generating a token on the client using your code if I also include `entityParams.entityTypeString = "individual"`, and then using `curl` to hit the update account endpoint.

Instead of using your backend, I'm curious if this works if you try generating a token on your client and then updating via curl like:
```
curl -i https://api.stripe.com/v1/accounts/acct_YOUR_ACCOUNT \
                                  -u sk_YOUR_SECRET_KEY: \
                                  -d account_token=ct_CLIENT_GENERATED_TOKEN
```

Unfortunately I don't have any more ideas on this, and I don't think we're quite the right folks to help.  I'd recommend emailing support@ with a link to this issue (feel free to cc me).

**Comment by Kevinw14** [comment]
Weird, I wasn't able to update it from the curl either. Maybe it's something on my end that's causing it not to update.

**Comment by davidme-stripe** [comment]
I'd like to close this out for now to clean up our GitHub issues. If you're still hitting problems with the API, we'll be better equipped to help via the support@ channel.
