### ISSUE TITLE
Limit country list in STPShippingAddressViewController

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#1314]
Hello,

I have 2 questions:

1. The STPShippingAddressViewController country field is "United States" by default. Is there a way to control this? For example, If I know what is the country of the user beforehand, can I prefill this with a different country?

2. The country field is showing plenty of countries. Can I limit this list to a specific few countries?

Thanks,
Oded

**Comment by RolandasRazma** [comment]
for #1 you can set paymentContext.prefilledInformation with country you want

**Comment by davidme-stripe** [comment]
Sorry for auto-closing. This is fixed in master by #1327 and will go out with the next release.

**Comment by davidme-stripe** [comment]
This has been fixed in Stripe SDK 17.0.1. Please let me know if it works for you!
