### ISSUE TITLE
STPPaymentHandler.shared().confirmPayment error not always localized

### ISSUE THREAD

**Issue by aurelhubert** [stripe/stripe-ios#1325]
## Summary

When testing to confirm a payment with the next card (which should be declined after the authentication screen), the error `NSLocalizedDescription` is not translated in the correct language (I'm testing with a simulator in french).

> 4000 0084 0000 1629

```
STPPaymentHandler.shared().confirmPayment(paymentIntentParams, with: self, completion: { (status, paymentIntent, error) in
    print(error)
})
```

The print return:
```
Optional(Error Domain=STPPaymentHandlerErrorDomain Code=8 "Your card was declined." UserInfo={com.stripe.lib:ErrorMessageKey=There was an error confirming the Intent. Inspect the `paymentIntent.lastPaymentError` or `setupIntent.lastSetupError` property., NSLocalizedDescription=Your card was declined.})
```

But when I test with the next card (which is always refused), the error message is correctly translated:

> 4000 0000 0000 0002

```
Optional(Error Domain=com.stripe.lib Code=70 "Votre carte a été refusée." UserInfo={com.stripe.lib:ErrorMessageKey=Your card was declined., com.stripe.lib:StripeErrorCodeKey=card_declined, com.stripe.lib:StripeErrorTypeKey=card_error, com.stripe.lib:CardErrorCodeKey=com.stripe.lib:CardDeclined, NSLocalizedDescription=Votre carte a été refusée.})
```

Any ideas?

## iOS version
12.4

## SDK version
16.0.7

**Comment by aurelhubert** [comment]
@davidme-stripe Thanks for the quick reply! I was planning to use this code to manage the errors as a first step, I will follow the next releases of the SDK.

**Comment by StevenWatremez** [comment]
Hello, have you any information about the release date of this issue ?

**Comment by davidme-stripe** [comment]
Today, I hope.

**Comment by davidme-stripe** [comment]
It's out! Stripe 18.0.0 will send the user's display language to the server, and PaymentIntent errors should now be localized in all our supported languages.

**Comment by nguyenhuutinh** [comment]
hi @davidme-stripe , there is no `decline_code` in error response.
Can you tell me how to get the `decline_code` in declined case?

Thanks
Error Domain=com.stripe.lib Code=70 "Your card was declined" UserInfo={com.stripe.lib:ErrorMessageKey=Your card was declined., com.stripe.lib:StripeErrorCodeKey=card_declined, com.stripe.lib:StripeErrorTypeKey=card_error, com.stripe.lib:CardErrorCodeKey=com.stripe.lib:CardDeclined, NSLocalizedDescription=Your card was declined})
