### ISSUE TITLE
Binary Rejected --> Obfuscated selectors

### ISSUE THREAD

**Issue by VladimirBudniy** [stripe/stripe-ios#1330]
## Summary
iOS app was rejected with issue:

"Specifically, we noticed that this app’s integrated Stripe framework contains obfuscated selectors, including the following class-methods:
[RoXTMl YVzJpCJy]
[cIr9 setQsQwZw:]
[cIr9 g4ZlVDHA]"

## Installation method
CocoaPod

## SDK version
v16.0.1

**Comment by davidme-stripe** [comment]
Hi @VladimirBudniy, 

Version 16.0.0 contained some obfuscated selectors, but we've removed them in more recent versions. Try updating to 16.0.7 and submitting again. Sorry for the trouble!
