### ISSUE TITLE
Can't set billingDetails with createPaymentMethodWithPayment

### ISSUE THREAD

**Issue by aurelhubert** [stripe/stripe-ios#1331]
## Summary
I'm using the method `STPAPIClient.shared().createPaymentMethod(with: payment)` to create a payment with Apple Pay and I have set the billing details inside the payment object (in the field `billingContact`), but when the SDK receives the response from the API (in `STPAPIClient+ApplePay.m`), the `billingDetails` is set to nil and is `readOnly` (so it can't be updated after).

On Android, I do it with the next code for Google Pay:
```
val paymentData = PaymentData.getFromIntent(data!!)
val rawToken = paymentData?.paymentMethodToken!!.token
val stripeToken = Token.fromString(rawToken)

val paymentMethodCreateParams = PaymentMethodCreateParams.create(PaymentMethodCreateParams.Card.create(stripeToken.id), billingDetails)
val paymentIntentParams = ConfirmPaymentIntentParams.createWithPaymentMethodCreateParams(paymentMethodCreateParams, clientSecret, "...")
```

Is there currently a way to set it correctly?

## SDK version
16.0.7

**Comment by davidme-stripe** [comment]
Thanks for filing, @aurelhubert! We're fixing this in #1331.

**Comment by davidme-stripe** [comment]
Sorry for the auto-close. Try pointing your Podfile to our master branch, it should resolve this for you.

**Comment by aurelhubert** [comment]
I've tested again with the code on the master branch and it doesn't work for now. I've maybe missed something.

The `billingContact` is correctly set on the `PKPaymentRequest` object, but when the transaction succeed, the `PKPayment` doesn't have the information.

This is the way I call Apple Pay:
```
let merchantIdentifier = StripeManager.appleMerchantID
let paymentRequest = Stripe.paymentRequest(withMerchantIdentifier: merchantIdentifier, country: "FR", currency: "EUR")
let totalAmount = NSDecimalNumber(value: cart.totalAmount)
        
// Configure the line items on the payment request
paymentRequest.paymentSummaryItems = [...]
paymentRequest.billingContact = self.billingContact

if Stripe.canSubmitPaymentRequest(paymentRequest) {
    if let paymentAuthorizationViewController = PKPaymentAuthorizationViewController(paymentRequest: paymentRequest) {
        paymentAuthorizationViewController.delegate = self

        print("paymentRequest: \(paymentRequest.billingContact?.name)") // => Not nil
        print("paymentRequest: \(paymentRequest.billingContact?.emailAddress)") => Not nil

        print("Stripe: Present payment authorization view controller")
        // Present payment authorization view controller
        present(paymentAuthorizationViewController, animated: true)
    }
} else {
    // There is a problem with your Apple Pay configuration
    print("Stripe: There is a problem with your Apple Pay configuration")
}
```

And I receive the result here:
```
func paymentAuthorizationViewController(_ controller: PKPaymentAuthorizationViewController, didAuthorizePayment payment: PKPayment, completion: @escaping (PKPaymentAuthorizationStatus) -> Void) {
       
    print("payment: \(payment.billingContact?.name)") // => nil
    print("payment: \(payment.billingContact?.emailAddress)") => nil
    ...
}
```

And last thing, I don't see the `email` field set in the `billingDetailsFromPKContact` (in `STPAPIClient+ApplePay.m`) method, did you forget it?

Thanks!

**Comment by davidme-stripe** [comment]
Ah, sorry, I thought you were using `STPPaymentContext`. That class will do some amount of this configuration for you, but if you're using PKPayment directly, you'll want to set it up like this:

```
paymentRequest.requiredBillingContactFields = [.name, .postalAddress]
paymentRequest.requiredShippingContactFields = [.emailAddress, .phoneNumber]
```

You'll then want to check the billingContact property for the name/address, and the shippingContact property for the email/phone. I'm not clear on why .emailAddress and .phoneNumber can't be part of the billingContact, but this appears to be a limitation of the Apple Pay API.

It also seems that our `requiredBillingAddressFields` doesn't currently support requesting email addresses or phone numbers. We'll have to fix that on our end, along with `billingDetailsFromPKContact`.

**Comment by davidme-stripe** [comment]
Hey @aurelhubert, can you try the version in the `master` branch? I think it'll do what you're asking for.

**Comment by aurelhubert** [comment]
@davidme-stripe it seems to be okay now with the next code:
```
let shippingContact = PKContact()
shippingContact.emailAddress = user.email
paymentRequest.shippingContact = shippingContact
paymentRequest.requiredShippingAddressFields = [.email]
```

Thanks 👍
