### ISSUE TITLE
iOS ConfirmSetupIntent "Received unknown parameter client_secret"  error

### ISSUE THREAD

**Issue by imimoises** [stripe/stripe-ios#1337]
## Summary
Im testing my integration of Saving a card using stripe's SetupIntents, and I have followed all the steps located on the documentation, yet whenever I try to confirm the setup intent,  I get  this error

"Received unknown parameter client_secret" 

## Code to reproduce

```
let setupIntentParams = STPSetupIntentConfirmParams(clientSecret: clientSecret)
setupIntentParams.paymentMethodID = paymentMethod.stripeId // took the stripe's payment method from the previous step
let paymentManager = STPPaymentHandler.shared()
 
guard let appDelegate = UIApplication.shared.delegate as? AppDelegate else {
     return
}
  
paymentManager.confirmSetupIntent(setupIntentParams, with: appDelegate, completion: { [weak self] (status, setupIntent, error) in
      guard error == nil else {
                completion(error, false)
                return
       }
      // More code here
 })
```

## iOS version
The project is setup on iOS 11,
my device is iOS 12.3.1

## Installation method
CocoaPods

## SDK version
I was trying version 16.0.7, then I changed to 16.0.4 and the same happened

**Comment by yuki-stripe** [comment]
Hi @imimoises, 

Sorry you're having problems, I'd like to look into this for you. Could you email me (yuki@stripe.com) the clientSecret you're passing?

**Comment by ryanrizzo** [comment]
What was the answer to this? I got this issue when I changed my server to use process.env variable for the stripe test key

**Comment by aliriaz-stripe** [comment]
@ryanrizzo Could you write in to Stripe Support at https://support.stripe.com/contact ? 

Please include the code that you are using, any error messages (screenshots or pasted into a pastebin) and we can help you out!

**Comment by samirsd** [comment]
what was the answer to this?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????

**Comment by ryanrizzo** [comment]
There are test and prod keys for the client side and server side of the stripe integration. I flipped one but the other needed to be flipped as well.
