### ISSUE TITLE
2. 3 Performance: Accurate Metadata

### ISSUE THREAD

**Issue by denglei022** [stripe/stripe-ios#1339]
I used Stripe version 16.0.0 + .
This month I uploaded my app ,apple refused to review multiple times.These are infos:

Please note that this app’s Stripe framework support contains obfuscated class methods. including the previously noted [cIr9 setQVClr7i4:]. This may result in longer review times if these class methods are present in future binary submissions.

I don't know if your latest version solves this problem. If not , please resolve it as soon as possible. I need resubmit my app to App Store soon.Thank you.

**Comment by davidme-stripe** [comment]
Hey @denglei022, are you still using the 16.0.2 fork that I sent? You should try updating to 16.0.7: We removed the obfuscated class methods in 16.0.3.

**Comment by denglei022** [comment]
Thank you.That's a good news.
