### ISSUE TITLE
ApplePay test China UnionPay card is invalid: Error Domain=com.stripe.lib Code=60 

### ISSUE THREAD

**Issue by AxLentz** [stripe/stripe-ios#1340]
## Summary
Payment fails when payment method is ApplePay using China UnionPay card.

## Code to reproduce
```        
STPAPIClient.shared().createPaymentMethod(with: payment) { (paymentMethod, error) in
    if error != nil {
        print("createPaymentMethod\(error)")
        completion(.failure)
    } else {
        print(paymentMethod?.stripeId ?? "nil")
    }
}
```
Creation of payment method for generated ApplePay token (using China UnionPay card) fails. returns an error:
```
Error Domain=com.stripe.lib Code=60 "There was an unexpected error -- try again in a few seconds" UserInfo={com.stripe.lib:ErrorMessageKey=An unknown error occurred, com.stripe.lib:StripeErrorTypeKey=api_error, NSLocalizedDescription=There was an unexpected error -- try again in a few seconds}
```
Cards details can be found in [ApplePay test page](https://developer.apple.com/apple-pay/sandbox-testing/). 
E.g.
```
6222 2188 8761 2072
CVV: 102
Expiry: 12/2022
```
## iOS version
iOS 12.3

## Installation method
cocoapods

## SDK version
16.0.6

**Comment by davidme-stripe** [comment]
Hey, thanks for the report @AxLentz. We're currently investigating this and a few other issues with the Apple Pay sandbox cards. In the meantime, are you able to test using a real UnionPay card and your Stripe test mode keys?

**Comment by davidme-stripe** [comment]
Hi @AxLentz, thanks for the report. Disregard my last message — I thought you were using the Apple Pay sandbox cards. I'd like to investigate this more, can you contact our support channel (https://support.stripe.com/contact?email=true&topic=Something%20else) with the details of the request you were using to try to create the PaymentMethod?

**Comment by AxLentz** [comment]
ok, thank you very much!
