### ISSUE TITLE
UIWebView is deprecated

### ISSUE THREAD

**Issue by Marcin951** [stripe/stripe-ios#1342]
Hi, i using stripe for few months and yesterday i did update of my app, and the update is not published on due the UIWebView. I dont use anywhere in my app the webView, and the only pods use webKit is Stripe. This is the message from Apple https://imgur.com/a/XteJ4gQ Is this a problem on Stripe side, or have i somewhere old code on my app with the webView and that is my mistake?

**Comment by davidme-stripe** [comment]
Hi @Marcin951, thanks for filing. We haven't used UIWebView in the Stripe SDK since 2016. Which version of the Pod are you using? Are you sure you aren't linking in anything else that might bring in UIWebView?

**Comment by Marcin951** [comment]
I used version 15.01, but after update pods everything work :)

**Comment by davidme-stripe** [comment]
That’s great! I’ll close this out, thanks for letting us know.
