### ISSUE TITLE
3DS 2.0 UI with White "Cancel" Button

### ISSUE THREAD

**Issue by letrongtriet** [stripe/stripe-ios#1344]
Summary
3DS 2.0 view has `Cancel` button in white color and there is no way that user can notice.

## Code to reproduce
```
static private var paymentManager: STPPaymentHandler {
        let paymentManager = STPPaymentHandler.shared()
        paymentManager.apiClient = stripeClient
        paymentManager.threeDSCustomizationSettings = threeDSCustomization
        return paymentManager
    }
    
    static private var threeDSCustomization: STPThreeDSCustomizationSettings {
        let threeDSCustomization = STPThreeDSCustomizationSettings()
        let uiCustomization = STPThreeDSUICustomization()
        let navigationBarCustomization = STPThreeDSNavigationBarCustomization()
        
        navigationBarCustomization.textColor = ColorPalette.darkBlue
        navigationBarCustomization.isTranslucent = false
        navigationBarCustomization.font = UIFont.whimFontMedium(18)
        
        uiCustomization.navigationBarCustomization = navigationBarCustomization
        threeDSCustomization.uiCustomization = uiCustomization
        
        return threeDSCustomization
    }
```

## iOS version
12.4.0

## Installation method
Cocoapods

## SDK version
16.0.7

## Other information
![IMG_0061](https://user-images.githubusercontent.com/28629580/64102202-214d6280-cd78-11e9-9a4a-786bee8633c7.PNG)

**Comment by davidme-stripe** [comment]
Hi @letrongtriet, thanks for filing. This should use the color from `navigationBarCustomization.textColor`. What is the value of `ColorPalette.darkBlue`? From your screenshot, it seems like it might be `nil`.

**Comment by letrongtriet** [comment]
Hi @davidme-stripe , it is working for Title "Secure checkout" but not for "Cancel" button.
And from technical documentation, `textColor` does not work with "Cancel" (https://stripe.dev/stripe-ios/docs/Classes/STPThreeDSNavigationBarCustomization.html#/c:objc(cs)STPThreeDSNavigationBarCustomization(py)textColor)

**Comment by yuki-stripe** [comment]
Hey @letrongtriet,

To customize the cancel button, create a `STPThreeDSButtonCustomization` instance and [set it](https://stripe.dev/stripe-ios/docs/Classes/STPThreeDSUICustomization.html#/c:objc(cs)STPThreeDSUICustomization(im)setButtonCustomization:forType:) passing [STPThreeDSCustomizationButtonTypeCancel](https://stripe.dev/stripe-ios/docs/Enums/STPThreeDSCustomizationButtonType.html#/c:@E@STPThreeDSCustomizationButtonType@STPThreeDSCustomizationButtonTypeCancel) as the type argument.

**Comment by letrongtriet** [comment]
Thanks @yuki-stripe and @davidme-stripe for helping. It's resolved now.
