### ISSUE TITLE
[URGENT] No indicator shown for last used card

### ISSUE THREAD

**Issue by anishparajuli555** [stripe/stripe-ios#1345]
## Summary

I have a list of saved cards, but last used card visual indicator is missing in the card lists. Previously, the same code used to show the checkmark for the last card used, now it's missing after we are upgrading for SCA implementation.

## Code to reproduce
```
let customerContext = STPCustomerContext(keyProvider: StripeCreateCustomerService.sharedClient)
paymentContext = STPPaymentContext(customerContext: customerContext)
paymentContext.delegate = self
paymentContext.hostViewController =  ViewControllerUtility.getTopMostVC()
self.paymentContext.presentPaymentOptionsViewController()
```

## iOS version
ios 12.4

## Installation method
cocoa pods

## SDK version
Stripe (16.0.7)

## Other information
![Simulator Screen Shot - iPhone Xs Max - 2019-09-03 at 18 09 26](https://user-images.githubusercontent.com/7752578/64172998-fb0dec80-ce75-11e9-8c67-0d202219c8d9.png)

**Let us know if this feature requires an implementation in webservice**

**Comment by davidme-stripe** [comment]
We're working on a better story for this. For now, you should be able to track the user's default payment method yourself and set it on the STPPaymentContext's `defaultPaymentMethod` property. If you need a place to store the default payment method without maintaining your own datastore, I'd recommend using the customer object's `metadata` or `invoice_settings[default_payment_method]` fields.

**Comment by anishparajuli555** [comment]
@davidme-stripe We tried the later solution setting default_payment_method in metadata and invoice_settings but it didn't work. Any alternative solution besides storing locally?

**Comment by sadhakbj** [comment]
@david-stripe 
The implementation  in web services end is as described below:
Library used: stripe-php , version: 6.43.0

**Creating payment intent**

```
           $this->stripe->setApiKey($this->getStripeApiKey());

            if (isset($attributes['payment_intent_id'])) {
                $intent = $this->intent->retrieve(
                    $attributes['payment_intent_id']
                );
                $intent->confirm();
            } else {
                if (isset($attributes['payment_method_id'])) {
                    $intentPayload = $this->getPaymentIntentPayload($order, $attributes, $user);
                    $intent        = $this->intent->create($intentPayload);
                }
            }
            $intentResponse = $this->generatePaymentResponse($intent);
            if ($intentResponse[ 'requires_action' ] === false) {
                event(new PaymentCaptured($order, ['payment_method' => Payment::PAYMENT_METHOD_STRIPE]));
                $payment             = $this->paymentRepository->getByOrderId($order->id);
                $payment->order_type = Order::ORDER_TYPES[ $payment->order->order_type ];
            } else {
                $payment = new stdClass();
            }
            $payment->intent = $intentResponse;
```

**GetPaymentIntentPayload method**

```
    $data = [
            'payment_method'      => $attributes[ 'payment_method_id' ],
            'amount'              => $order->grand_total * 100,
            'currency'            =>  'usd',
            'confirmation_method' => 'manual',
            'confirm'             => true,
            'return_url'          => sprintf('%s://stripe-redirect', getCurrentBuildingName()),
            'use_stripe_sdk'      => true,
        ];

        if (!is_null($user->stripe_id)) {
            $data[ "customer" ]           = $user->stripe_id;
            $data[ "setup_future_usage" ] = "on_session";
        }
```

The implementation works with no issue on the android device. 

Do we need to make any changes on the API end ?

**Comment by yuki-stripe** [comment]
Hi @sadhakbj,

I don't think it's an issue with your backend.  I'd guess that `defaultPaymentMethod` is not set to a valid Payment Method ID.  It should start with `pm_`.

**Comment by anishparajuli555** [comment]
@yuki-stripe If so, what do you think should be the best way to handle this until the team releases an update? Can you recommend any previous stable version of iOS SDK?

**Comment by yuki-stripe** [comment]
@anishparajuli555 - sorry to hear that!  How do you determine the value you set for `defaultPaymentMethod`?  Could you give an example of a value and the code?

**Comment by anishparajuli555** [comment]
@yuki-stripe 

```
//for test purpose
class TestStorage {
    static var defaultPayment: String!
}
```

```
func paymentOptionsViewController(_ paymentOptionsViewController: STPPaymentOptionsViewController, didSelect paymentOption: STPPaymentOption) {
     TestStorage.defaultPayment = (paymentOption as? STPPaymentMethod)?.stripeId
}
```

```
let customerContext = STPCustomerContext(keyProvider: StripeCreateCustomerService.sharedClient)
paymentContext = STPPaymentContext(customerContext: customerContext)
paymentContext.delegate = self
if let temp = TestStorage.defaultPayment {
     paymentContext.defaultPaymentMethod = temp
}
paymentContext.hostViewController =  ViewControllerUtility.getTopMostVC()
let paymentMethodsViewController = STPPaymentOptionsViewController(configuration: STPPaymentConfiguration.shared(), theme: STPTheme.default(), customerContext: customerContext, delegate: self)
ViewControllerUtility.getTopMostVC()?.navigationController?.present(getStripeNavigationVC(rootViewController: paymentMethodsViewController), animated: true, completion: nil)
```

The card selected should show for the next payment but does not. 

<img width="989" alt="Screen Shot 2019-09-06 at 12 38 35 PM" src="https://user-images.githubusercontent.com/7752578/64407226-8ae4ae00-d0a3-11e9-8fda-f3eec3cdb439.png">

**Comment by yuki-stripe** [comment]
Ah super helpful @anishparajuli555, thanks.  You'll need to set `defaultPaymentMethod` on `STPPaymentOptionsViewController` instance, before you present it.  

From this sample code, it looks like you are not using `STPPaymentContext`, and you could delete it.  

If you *are* using `STPPaymentContext`, you should call `paymentContext.presentPaymentOptionsViewController` instead of creating your own.  

Hopefully this works for you, let me know!

**Comment by anishparajuli555** [comment]
@yuki-stripe Thanks, this works!
