### ISSUE TITLE
Unable to run the example project with nodejs backend. Issue with ephemeral keys

### ISSUE THREAD

**Issue by wy1024** [stripe/stripe-ios#1347]
## Summary

Unable to run the example project with nodejs(parse) backend. Failed at the ephemeral_keys step with error `Could not parse the ephemeral key response following protocol STPCustomerEphemeralKeyProvider. Make sure your backend is sending the unmodified JSON of the ephemeral key to your app.` even everything prints out correct

## Code to reproduce

Slightly modified the create customer key method to auth with my api.

```
Alamofire.request(url, method: .post, parameters: [
            "customerId": "cus_FkKDci1f8nidim" //created test customer id
            ], headers: ["X-Parse-Application-Id": PARSE_APP_ID, "X-Parse-Client-Key": PARSE_CLIENT_KEY])
            .validate(statusCode: 200..<300)
            .responseJSON { responseJSON in
                switch responseJSON.result {
                case .success(let json):
                    let jsonjson = json as? [String: AnyObject]
                    print(jsonjson)
                    completion(jsonjson!, nil)
                case .failure(let error):
                    completion(nil, error)
                }
        }
```
       
API code is really simple:
```
return await stripe.ephemeralKeys.create(
        {customer: request.params.customerId},
        {stripe_version: stripe_version}
    );
``` 

## iOS version

12.4

## Installation method

Downloaded full example project

## SDK version

commit id:
67cb62b9d7ecc3fb9d9a51f4c8d9d4b583bdcd6e
since it has alamofire

## Other information

Detail error
```
Optional(["result": {
    "associated_objects" =     (
                {
            id = "cus_FkKDci1f8nidim";
            type = customer;
        }
    );
    created = 1567581569;
    expires = 1567585169;
    id = "ephkey_1FEsm5K6xdXzUSATttjVQRPO";
    livemode = 0;
    object = "ephemeral_key";
    secret = "ek_test_YWNjdF8xRXpiSzJLNnhkWHpVU0FULGJFSFI4N3IwTWZ5aWFlQVFwRnRkMG5WWXZyTjV5WUY_00u30gJcRU";
}])
2019-09-04 00:19:29.862263-0700 Standard Integration[34760:2238809] *** Assertion failure in -[STPEphemeralKeyManager _createKey], /Users/yuewang/Desktop/stripe-ios-67cb62b9d7ecc3fb9d9a51f4c8d9d4b583bdcd6e/Stripe/STPEphemeralKeyManager.m:90
2019-09-04 00:19:29.869519-0700 Standard Integration[34760:2238809] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not parse the ephemeral key response following protocol STPCustomerEphemeralKeyProvider. Make sure your backend is sending the unmodified JSON of the ephemeral key to your app. For more info, see https://stripe.com/docs/mobile/ios/standard#prepare-your-api'
```

**Comment by wy1024** [comment]
On another note, not sure if related to the cause, but I have only implemented the `ephemeral_keys` backend method so far. I could not find a full nodejs backend example, only a ruby version, which makes development more difficult.

**Comment by aliriaz-stripe** [comment]
hi @wy1024, it looks like your backend isn't returning a JSON representation of the ephemeral key, which is what STPEphemeralKeyProvider expects as per the docs: https://stripe.com/docs/mobile/ios/standard#ephemeral-key.

Closing as this isn't a bug/issue on the SDK, please follow up with https://support.stripe.com/contact if you run into any further integration issues!
