### ISSUE TITLE
Refactor problem from 13.2.0 to 16.0.7

### ISSUE THREAD

**Issue by ffdez** [stripe/stripe-ios#1348]
## Summary
Updating a production app working with Stripe 13.2.0 version to 16.0.7 i found a problem.
I use `STPPaymentCardTextField` for get the client card.

## Code to reproduce

Current implementation is:
```
let params = self.stripeTextField.cardParams // STPCardParams
let sourceParams = STPSourceParams.cardParams(withCard: params)
STPAPIClient.shared().createSource(with: sourceParams) { (source, error) in
...
```

After update, cardParams returns a `STPPaymentMethodCardParams` and i can't call `STPSourceParams.cardParams` neither `STPAPIClient.createSource`

What should I change in this case?
I can't find documentation on how to refactor these classes in MIGRATING.md

## SDK version
13.2.0 to 16.0.7

**Comment by yuki-stripe** [comment]
Hi @ffdez,

v16.0.0 migrated our UI components from Sources to PaymentMethods, which replaces Tokens and Sources.  See https://stripe.com/docs/payments/payment-methods#transitioning.  I recommend you [migrate to the Payment Methods + Payment Intents API](https://stripe.com/docs/payments/payment-intents/migration/automatic-confirmation).  This is especially important [if you're affected by SCA](https://stripe.com/docs/strong-customer-authentication/doineed).

If you're not ready to migrate, you can still create the `STPSourceParams` manually like:
```
let card = STPCardParams()
card.number = stripeTextField.cardNumber
card.expMonth = stripeTextField.expirationMonth
card.expYear = stripeTextField.expirationYear
card.cvc = stripeTextField.cvc
let sourceParams = STPSourceParams.cardParams(withCard: card)
```
