### ISSUE TITLE
Top bar glitch

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#1350]
## Summary

The top bar is black when opening the Payment and Shipping screens. 

<img width="433" alt="Screenshot at Sep 04 15-01-16" src="https://user-images.githubusercontent.com/624023/64295022-1257e300-cf25-11e9-978b-d3349b74d89c.png">

## Code to reproduce
        self.paymentContext.presentPaymentOptionsViewController()

        self.paymentContext.presentShippingViewController()
## iOS version
iOS 13.1

## Installation method
Cocoapods 
iPhone X

## SDK version
Stripe 16.0.7

**Comment by yuki-stripe** [comment]
Hi @odedharth,

Thanks for the report!  We're working on a fix now.

**Comment by odedharth** [comment]
Thanks for the quick response. Seems that there is still a minor glitch, see it at the end of the video:
https://www.dropbox.com/s/v5sgbqntxb7o18d/RPReplay_Final1568066190.mov?dl=0

**Comment by davidme-stripe** [comment]
Thanks, I'm trying to repro it now. We should have a fix soon.

**Comment by davidme-stripe** [comment]
@odedharth I can't reproduce this exact issue locally, but can you try setting `theme.translucentNavigationBar = YES` on your STPTheme and let me know if it resolve the glitch for you? I'm seeing some similar graphical issues related to that setting on iOS 13.

**Comment by odedharth** [comment]
@davidme-stripe this fixed it, thanks!

**Comment by davidme-stripe** [comment]
Thank you! I think we'll make that the default in the next version.

**Comment by davidme-stripe** [comment]
This has been fixed in Stripe SDK 17.0.1.
