### ISSUE TITLE
macOS Catalyst support (with Swift Package Manager and Xcode 12)

### ISSUE THREAD

**Issue by davidme-stripe** [stripe/stripe-ios#1364]
If you'd like to use Stripe in your Catalyst apps, like and subscribe to this issue. We'll prioritize based on how much feedback we receive.

Caveat: Apple Pay doesn't appear to be supported in Catalyst apps as of the latest Catalina beta.

**Comment by davidme-stripe** [comment]
In the interest of unblocking folks while we work out a better framework distribution story, here's a workaround:

* Install Xcode 11.1 GM Seed or later.
* In your Podfile, set:
```
pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios', :branch => 'catalyst-preview'
```
(Note that this branch will *only* work on Catalyst, so you’ll need to switch to and from it when building your iOS app.)

* Run `pod update Stripe`, then open your project's .xcworkspace.
* In your project settings, in the General tab, under Deployment, enable the Mac checkbox.
* If you hit an error that "Signing for Stripe-Stripe requires a development team," click the Pods project in Xcode's left sidebar, select the Stripe-Stripe target, go to the "Signing & Capabilities" tab, then set a team.

**Comment by davidme-stripe** [comment]
We've attached `Stripe.xcframework` to release 18.0.0 of the SDK. You can drop that into Xcode and get support for building on iOS/iPadOS/Simulator/macOS with one framework package.

If you want to use Cocoapods, you'll need to use the above workaround for now. We should have a better solution once Cocoapods adds support for .xcframeworks.

**Comment by rocketnik** [comment]
What is the status on this. The branch you mentioned is version 17.x and we now have 19.x. The 19.x version does not come with a binary version x86_64 Mac, instead in contains x86_64 linked for Simulator. (I installed via cocoapods)

Error:

Building for Mac Catalyst, but linking in object file built for iOS Simulator, file '/Users/zark/[...]/FoodRunner/Pods/Stripe/InternalFrameworks/libStripe3DS2.a' for architecture x86_64

**Comment by davidme-stripe** [comment]
We added Swift Package Manager support in #1644, and that (along with Xcode 12) is now our recommended method for building a Catalyst app. We'll release a formal version soon, but for now you should be able to add Stripe as an SPM package on the `master` branch.

For Cocoapods, we're still waiting on .xcframework support, which should be coming in Cocoapods 1.10.

(And sorry @rocketnik, I just saw your message! Hopefully this addresses your question.)

**Comment by davidme-stripe** [comment]
This is out of beta in 20.0.0 with SPM, and will be in Cocoapods 1.10 once that's available.
