### ISSUE TITLE
Default Payment Method not loading in Standard Integration or selected by default in STPPaymentOptionsViewController STPC

### ISSUE THREAD

**Issue by halinebr** [stripe/stripe-ios#1366]
## Summary
Stripe Standard Integration not loading default source if the source is a Payment Method object.

## Code to reproduce
Via our backend, we're able to set the default payment method and verify it from the Stripe dashboard but in the iOS app using Standard Integration always loads Apple Pay first and is selected by default in STPPaymentOptionsViewController. In previous versions of the Stripe SDK (where we were using Sources & Cards) would select the correct source/card by default in STPPaymentOptionsViewController. 

## iOS version
12.2, 12.4

## Installation method
Cocoapods

## SDK version
17.0.0

**Comment by yuki-stripe** [comment]
Hi @halinebr,

Are you setting the [defaultPaymentMethod](https://stripe.dev/stripe-ios/docs/Classes/STPPaymentOptionsViewController.html#/c:objc(cs)STPPaymentOptionsViewController(py)defaultPaymentMethod) property in the app as well?

**Comment by halinebr** [comment]
Nope - have made that change and my problem is now gone. Thank you!

**Comment by MayankAgarwal04** [comment]
@yuki-stripe @halinebr 
Team, I am facing the same issue. If apple pay is not set then no card displays as default And if Apple pay is enable it is coming as selected. Please check the below screenshots.
Can we make a paymentMethod(**cards/Apple Pay**) selected and default from Front END?
**Note : we are using STPPaymentContext class for handling both Apple Pay and Credit Cards.**

**Comment by yuki-stripe** [comment]
@mayank-stripe I believe your issue is the same as https://github.com/stripe/stripe-ios/issues/1345

The short story is that there is no automatic default selected behavior.  We're working on adding this.  In the mean time, check the linked issue on how to manually implement the behavior.
