### ISSUE TITLE
How to mock the token when using STPPaymentOptionsViewController

### ISSUE THREAD

**Issue by yujia917** [stripe/stripe-ios#1368]
Hi:

I was using STPPaymentMethodsViewController before. I  override the function createToken(withCard card: STPCardParams, completion: STPTokenCompletionBlock? = nil) in the mock api client, so I can add and charge test cards. Everything worked fine.

I recently updated the Stripe API version to 17.0.0. The STPPaymentMethodsViewController is deprecated. Now I am using STPPaymentOptionsViewController. But the createToken function is never called. And I always got error: No such payment_method pm_xxxxxxxxxxxx when trying to add test card.

The UI Example provided on github mocked the customerContext too, which is not what I want. I want the test card to be added to the customer. 

How can I do it?

Thanks.
Yu

**Comment by yuki-stripe** [comment]
Hi @yujia917,

`STPPaymentOptionsViewController` migrated from Token to [PaymentMethod](https://stripe.com/docs/payments/payment-methods).  Instead of creating Tokens, it creates PaymentMethods.  

It sounds like you want to look at `createPaymentMethodWithParams:(STPPaymentMethodParams *)paymentMethodParams completion:(STPPaymentMethodCompletionBlock)completion`

**Comment by yujia917** [comment]
Hi Yuki:

Thanks a lot for reply.

I tried to override the function createPaymentMethodWithParams like following. The function got called when adding test card, but i still always got the error "No such payment_method". What did I miss?

```
override func createPaymentMethod(with paymentMethodParams: STPPaymentMethodParams, completion: @escaping STPPaymentMethodCompletionBlock) {
        guard let card = paymentMethodParams.card, let billingDetails = paymentMethodParams.billingDetails else { return }
        // Generate a mock card model using the given card params
        var cardJSON: [String: Any] = [:]
        var billingDetailsJSON: [String: Any] = [:]
        cardJSON["id"] = "\(card.hashValue)"
        cardJSON["exp_month"] = "\(card.expMonth ?? 0)"
        cardJSON["exp_year"] = "\(card.expYear ?? 0)"
        cardJSON["last4"] = card.number?.suffix(4)
        billingDetailsJSON["name"] = billingDetails.name
        billingDetailsJSON["line1"] = billingDetails.address?.line1
        billingDetailsJSON["line2"] = billingDetails.address?.line2
        billingDetailsJSON["state"] = billingDetails.address?.state
        billingDetailsJSON["postal_code"] = billingDetails.address?.postalCode
        billingDetailsJSON["country"] = billingDetails.address?.country
        cardJSON["country"] = billingDetails.address?.country
        if let number = card.number {
            let brand = STPCardValidator.brand(forNumber: number)
            cardJSON["brand"] = STPCard.string(from: brand)
        }
        cardJSON["fingerprint"] = "\(card.hashValue)"
        cardJSON["country"] = "US"
        let paymentMethodJSON: [String: Any] = [
            "id": "\(card.hashValue)",
            "object": "payment_method",
            "type": "card",
            "livemode": false,
            "created": NSDate().timeIntervalSince1970,
            "used": false,
            "card": cardJSON,
            "billing_details": billingDetailsJSON,
        ]
        let paymentMethod = STPPaymentMethod.decodedObject(fromAPIResponse: paymentMethodJSON)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.6) {
            completion(paymentMethod, nil)
        }
    }
```

**Comment by yuki-stripe** [comment]
@yujia917 I'd expect this error.  There is no payment_method being created here - you're overriding the method so that it instead returns this mock.  

What are you trying to do?  You might want to look at using the test cards here https://stripe.com/docs/testing#cards.

**Comment by yujia917** [comment]
Hi Yuki:

I am trying to add the test card to the customer. I still got the same error even I didn't override the createPaymentMethodWithParams function. I tried several test cards in the link you sent.

**Comment by yuki-stripe** [comment]
@yujia917 Ah okay, understood.  Could you tell me what method is giving this error, and show the code where you initialize the `STPPaymentOptionsViewController`?

**Comment by yujia917** [comment]
Hi Yuki:

I actually don't know which method threw that error. The following is the code of initializing STPPaymentOptionsViewController:

```
        let config = STPPaymentConfiguration()
        config.requiredBillingAddressFields = .zip
        config.canDeletePaymentOptions = true
        config.publishableKey = Constant.StripeAPIKey
        
        let apiKeyObject = StripeAPIClient.sharedClient
        let customerContext = STPCustomerContext(keyProvider: apiKeyObject)
        let viewController = STPPaymentOptionsViewController(configuration: config,
                                                             theme: self.theme,
                                                             customerContext: customerContext,
                                                             delegate: self)
        let navigationController = UINavigationController(rootViewController: viewController)
        navigationController.navigationBar.stp_theme = self.theme
        self.present(navigationController, animated: true, completion: nil)

```

This is the screen shot:
<img width="325" alt="Screen Shot 2019-09-10 at 4 44 20 PM" src="https://user-images.githubusercontent.com/12704261/64657897-45e5b200-d3ea-11e9-8275-14425377f5d7.png">

**Comment by yuki-stripe** [comment]
@yujia917 I would make sure that `StripeAPIClient.sharedClient` is using the right API key - it should be the one starting with `pk_` here https://dashboard.stripe.com/test/apikeys.

**Comment by yujia917** [comment]
Hi Yuki:

Thanks. One additional character was added to the end of the API key by mistake. It works now.

Thanks a lot.
