### ISSUE TITLE
STPPaymentHandler is crashing app

### ISSUE THREAD

**Issue by aqeel371** [stripe/stripe-ios#1376]
app crashes when i try to confirm payment with payment intent in stripe sdk [Version 17.0.1](https://github.com/stripe/stripe-ios/releases/tag/v17.0.1)

> STPPaymentHandler
```
let paymentManager = STPPaymentHandler.shared()
paymentManager.apiClient = STPAPIClient(publishableKey: Constants.stripe_key)
paymentManager.confirmPayment(withParams: paymentIntentParams, authenticationContext: self, completion: {
                                (status, paymentIntent, error) in
                                
                                switch (status) {
                                case .failed:
                                    print("failed")
                                case .canceled:
                                    print("canceled")
                                case .succeeded:
                                    print("success")
                                }
                                
                            })

```
it causes the exception in `STPAPIClient.m    L:210` 

Note: 

- i am using following cards 
1. `4000 0025 0000 3155`
2. `4242 4242 4242 4242`
3. `4000 0027 6000 3184`

**Comment by yuki-stripe** [comment]
Hey @aqeel371,

The assertion on that line suggests you are using a secret key instead of a publishable one.  You only want to include the publishable key (starts with pk_) in your app - you can grab it here https://dashboard.stripe.com/apikeys
