### ISSUE TITLE
Number field placeholder not visible correct

### ISSUE THREAD

**Issue by divsbhalala** [stripe/stripe-ios#1379]
![image](https://user-images.githubusercontent.com/12185309/65063739-7c986b00-d99c-11e9-85b5-d6efcaafbd85.png)
In stripe SDK-17.0.0
https://www.screenmailer.com/v/0aqmcYQBrGaxf5g

**Comment by davidme-stripe** [comment]
Thanks for the report, we're looking into this. To temporarily work around this, you could try setting your `numberPlaceholder` to the default value.

**Comment by davidme-stripe** [comment]
This is fixed in 18.0.0.
