### ISSUE TITLE
Valid token for invalid card (testing with Apple Pay)

### ISSUE THREAD

**Issue by Suz** [stripe/stripe-ios#138]
Why is this code returning a valid token? This card number should yield a `card_denied` error. 
I've also tried `@4000 0000 0000 0069`, which should yield a `expired_card` error. Both return tokens. The call also does generate an error if I set the `card.expMonth = 13` or the `card.cvc = 99` as suggested in the docs. 

    STPCard *card = [STPCard new];
    card.number = @"4000000000000002";  // should get 'card declined'
    card.expMonth = 12;
    card.expYear = 2020;
    card.cvc = @"123";
        
    [[STPAPIClient sharedClient] createTokenWithCard:card completion:^(STPToken *token, NSError *error) {
         .....

I'm working with ApplePay and ApplePayStubs in the simulator.

**Comment by jflinter** [comment]
Hey there,
With that test card number, you won't see a `card_declined` error until you actually attempt to create a charge with that token. This mirrors how this would behave in livemode: while we can tell you immediately (upon token creation) that, say, a card has an invalid expiration date, we might not know that the card will be declined until actually attempting to charge it. As such, while a bit confusing at first, this is the intended behavior.
