### ISSUE TITLE
Documentation Out of date

### ISSUE THREAD

**Issue by Sanunez** [stripe/stripe-ios#1380]
## Summary

Docs out of date with new Code Changes.

## Code to reproduce

MyAPIClient.swift on Standard Integration has been updated, but docs at: 
https://stripe.com/docs/mobile/ios/standard#using-ios-standard-ui-components
have not reflected the changes.

## Installation method

CocoaPods

## SDK version

17.01

**Comment by yuki-stripe** [comment]
Hi @Sanunez,

We're updating the docs now.  Please reach out if you have any questions in the mean time.

**Comment by davidme-stripe** [comment]
I believe the docs are now up to date.
