### ISSUE TITLE
iOS manual confirmation error

### ISSUE THREAD

**Issue by duzenko** [stripe/stripe-ios#1389]
I'm trying to wrap my head around the SDK and,  frustrating indeed, the bundled example fails on the function I need to replicate in my app.

`createAndConfirmPaymentIntentWithPaymentMethod` fails from the manual confirmation view with the error message `Invalid PaymentIntent status`

What does it mean and what can I do about it?

![image](https://user-images.githubusercontent.com/1481807/65592570-7c4d3080-df97-11e9-8273-cae163e3cbc4.png)

**Comment by davidme-stripe** [comment]
We recently made a change to this flow: If you've updated to 17.0.2 (or the current `master` branch), you'll need to update your [example-ios-backend](https://github.com/stripe/example-ios-backend) server to the latest 17.0.0. Similarly, if you just deployed the latest example-ios-backend to Heroku, you'll need to update your copy of the Stripe repository to 17.0.2.
