### ISSUE TITLE
Allow use of other card scan libraries

### ISSUE THREAD

**Issue by TomWFox** [stripe/stripe-ios#1395]
## Summary
The ability to easily integrate the CardIO library with the stripe SDK is great. However, as the CardIO library hasn't been maintained for a long time and has now been archived I don't think it makes sense to rely on it any more.

There are other options available for card scanning, the best I have found is [cardscan](https://github.com/getbouncer/cardscan-ios). It is actively maintained and is offered for free to small business/those who do not want to use the commercial fraud prevention offering.

I think it would be great to support CardScan as well as or instead of CardIO or maybe open up the `STPAddCardViewController` for easy custom integration?

**Comment by davidme-stripe** [comment]
Thanks for filing this! We're looking into adding CardScan support in the near future.

**Comment by TomWFox** [comment]
Awesome to hear, looking forward to it!

**Comment by kunshah** [comment]
Awesome to hear, Waiting for this integration!

**Comment by davidme-stripe** [comment]
We're tracking a replacement here: #1629

**Comment by davidme-stripe** [comment]
Our new [card scanner](https://github.com/stripe/stripe-ios#card-scanning-beta) is available in SDK 20.0.0.

**Comment by SudoPlz** [comment]
@davidme-stripe is that card-scanner implementation using card-io below the hood, or did you implement this from scratch?

**Comment by davidme-stripe** [comment]
It uses the built-in iOS OCR framework. The source is in STPCardScanner.swift, feel free to inspect and reuse it under the terms of the MIT License.
