### ISSUE TITLE
didCreatePaymentResult not getting called in Apple Pay Stripe Integration

### ISSUE THREAD

**Issue by MayankAgarwal04** [stripe/stripe-ios#1399]
## **Summary**
While calling **self.paymentContext.requestPayment()** apple pay dialog appears and on confirming **Pay with Passcode/FaceID** below delegate (**didCreatePaymentResult**) is not getting called. But If we cancel the Apple Pay Dialog **didFinishWith status** is getting called. 
In case of Credit cards below delegate (**didCreatePaymentResult**) is working fine, but when we choose **pay via Apple pay** it is not getting called. 

## **Code to reproduce**

// **Initialisation paymentContext**
**init()** {
            LUStripeClient.sharedClient.baseURLString = NetworkEndpoint.shared.selectedEndpointPath
            let config = STPPaymentConfiguration.shared()
            config.publishableKey = STPPaymentConfiguration.shared().publishableKey
            config.appleMerchantIdentifier = Constants.applePayMerchantID
            config.additionalPaymentOptions = .all
            config.requiredBillingAddressFields = .none
            
            let customerContext = STPCustomerContext(keyProvider:  LUStripeClient.sharedClient)
            paymentContext = STPPaymentContext(customerContext: customerContext,
                                               configuration: config,
                                               theme: .default())
        
            super.init(nibName: String(describing: LUBuyNowPopUpViewController.self), bundle: nil)
            self.paymentContext.delegate = self
            self.paymentContext.hostViewController = self
        }
--------------------------------------------------------------------------------------------
// On tap **Pay with Passcode/FaceID**
**func** payViaApplePay() {        
    self.paymentContext.paymentSummaryItems = [
           PKPaymentSummaryItem(label: "TOTAL", amount: NSDecimalNumber(value: 5000))        
     ]
      self.paymentContext.requestPayment()
}
--------------------------------------------------------------------------------------------
// **Delegate Implementation**
**func** paymentContext(_ paymentContext: STPPaymentContext, didCreatePaymentResult paymentResult: STPPaymentResult, completion: @escaping STPPaymentStatusBlock) {        
        
        // Create the PaymentIntent on the backend        
        
        LUStripeClient.createPaymentIntent(amount:"\(total)") { result in
            switch result {
            case .success(let result):
                // Confirm the PaymentIntent
                let paymentIntentParams = STPPaymentIntentParams(clientSecret: result["client_secret"] as! String)
                paymentIntentParams.paymentMethodId = paymentResult.paymentMethod.stripeId
                STPPaymentHandler.shared().confirmPayment(withParams: paymentIntentParams, authenticationContext: paymentContext) { status, paymentIntent, error in
                    switch status {
                    case .succeeded:
                        // Your backend asynchronously fulfills the customer's order, e.g. via webhook
                        // See https://stripe.com/docs/payments/payment-intents/ios#fulfillment
                        completion(.success, nil)                        
                        
                    case .failed:

                        completion(.error, error)  // Report error
                    case .canceled:
                        
                        completion(.userCancellation, nil)// Customer cancelled
                    @unknown default:
                        
                        completion(.error, nil)
                    }
                }
            case .failure(let error):
                
                completion(.error, error) // Report error from your API
                break
            }
        }
    } 

## **iOS version**
12.3

## **Installation method**
Installed via POD

## **SDK version**
17.0.1

@dackerman-stripe Can you please help me out here. I need to push this to production with Apple pay integration. 

**Note** : **We are testing in Sandbox environment, Also we are using STPPaymentContext class for handling both Apple Pay and Credit Cards**

 
![IMG_0687](https://user-images.githubusercontent.com/36412855/65954847-73130680-e464-11e9-94e1-36ab40fecf72.PNG)

**Comment by dackerman-stripe** [comment]
Hello, I'm cc-ing @davidme-stripe who might have been the intended mention!

**Comment by yuki-stripe** [comment]
Hey @MayankAgarwal04,

Are you testing on the simulator?  There's a bug in Apple Pay on the simulator, for at least Xcode 10.3.

**Comment by MayankAgarwal04** [comment]
@dackerman-stripe @davidme-stripe @yuki-stripe 
Thanks for quick response. Issue has been resolved now. I have created another sandbox tester and its working fine with it.
