### ISSUE TITLE
Missing PNG in stripe causing an error building the project

### ISSUE THREAD

**Issue by alvincrisuy** [stripe/stripe-ios#1409]
## Summary

<img width="360" alt="Screen Shot 2019-10-05 at 2 23 17 PM" src="https://user-images.githubusercontent.com/7260700/66250938-f93c8f00-e77b-11e9-899f-c503c16da82a.png">
<img width="1121" alt="Screen Shot 2019-10-05 at 2 23 28 PM" src="https://user-images.githubusercontent.com/7260700/66250939-f9d52580-e77b-11e9-8a2a-90aa4fa85a16.png">

## Code to reproduce

pod update

## iOS version

iOS 12.4.1

## Installation method

cocoapods

**Comment by yuki-stripe** [comment]
Hi @alvincrisuy,

I'm unable to repro this, it appears we are shipping those PNGs in the expected location.  Could you try re-installing the Stripe pod?

**Comment by davidme-stripe** [comment]
I'll close this for now, but let us know if you're still seeing that PNG error.
