### ISSUE TITLE
Add error logging to Checkout `logoImage` conversion

### ISSUE THREAD

**Issue by jamesreggio** [stripe/stripe-ios#141]
This function may fail, and it presently does so silently.

https://github.com/stripe/stripe-ios/blob/7715bff3ebe5b4a0e1b1b353ba2c9971d2c7c1ae/Stripe/Checkout/STPCheckoutInternalUIWebViewController.m#L60

It would help to log upon error, so that people are not confused at to why Checkout fails to display their logo.

**Comment by jflinter** [comment]
I believe the real underlying error here should be fixed by https://github.com/stripe/stripe-ios/pull/146, so closing this.
