### ISSUE TITLE
dark mode, done button is also dark. Shipping VC

### ISSUE THREAD

**Issue by Marcin951** [stripe/stripe-ios#1414]
## Summary
dark mode, shipping page, done button is dark too

## Code to reproduce
default shipping page in dark mode
https://imgur.com/a/rr432Yg light mode
https://imgur.com/a/Y7Jzurn dark mode
missing the done button

## iOS version
13.2

## Installation method
cocoapods

## SDK version
18.0

**Comment by yuki-stripe** [comment]
Hi @Marcin951 

So far, I'm unable to reproduce this.  Are you using a custom `STPTheme`?

**Comment by Marcin951** [comment]
No, i using STPTheme.default(), make sure you have shipment type .delivery by user or something like that

**Comment by yuki-stripe** [comment]
@Marcin951 

![image](https://user-images.githubusercontent.com/47796191/66414511-659ed480-e9ae-11e9-9cfb-1069491b3829.png)

This is the result I get on my device (iPhone X, 13.1.2) and on the simulator.  Could you provide more details to reproduce?  The code you use to configure and present the Shipping VC would be helpful too.

**Comment by Marcin951** [comment]
`@objc func buyAction (_ button: UIButton, event: UIEvent) {
            if loadedAllData == true{
                if paymentStatus == 0{
                    changePostionOfView = true
                    ignoreFirstTap = false
                    let supportedCountry: Set<String> = ["US"]
                    let configuration = STPPaymentConfiguration()
                    configuration.availableCountries = supportedCountry
                    configuration.companyName = "Name"
                    configuration.canDeletePaymentOptions = true
                    configuration.publishableKey = "KEY"
                    configuration.appleMerchantIdentifier = "Merchant"
                    configuration.requiredBillingAddressFields = STPBillingAddressFields.full
                    configuration.verifyPrefilledShippingAddress = true
                    let paymentOptionsViewController = STPPaymentOptionsViewController(configuration: configuration, theme: STPTheme.default(), customerContext: STPCustomerContext(keyProvider: self.customerContext), delegate: self)
                    navigationController?.pushViewController(paymentOptionsViewController, animated: true)
                    //  present(navigationController, animated: true)
                }else{
                    ProgressHUD.showError("This painting have one payment in process")
                }
            }
    
        }
    
    func shippingAddressViewControllerDidCancel(_ addressViewController: STPShippingAddressViewController) {
        navigationController?.popViewController(animated: true)
    }
    
    func shippingAddressViewController(_ addressViewController: STPShippingAddressViewController, didEnter address: STPAddress, completion: @escaping STPShippingMethodsCompletionBlock) {
        let upsGroundShippingMethod = PKShippingMethod()
       upsGroundShippingMethod.amount = 0.00
        upsGroundShippingMethod.label = "Delivery company"
        upsGroundShippingMethod.detail = "It is choosed by seller"
        upsGroundShippingMethod.identifier = "seller"

        

        if address.country == "US" {
            let availableShippingMethods = [upsGroundShippingMethod]
            let selectedShippingMethod = upsGroundShippingMethod

            completion(.valid, nil, availableShippingMethods, selectedShippingMethod)
        }
        else {
            completion(.invalid, nil, nil, nil)
        }
    }
    
    func shippingAddressViewController(_ addressViewController: STPShippingAddressViewController, didFinishWith address: STPAddress, shippingMethod method: PKShippingMethod?) {
        let alert = UIAlertController(title: "Do you confirm charge for: $50?", message: "Make sure about provided shippment information", preferredStyle: .alert)

        alert.addAction(UIAlertAction(title: "Confirm", style: .default, handler: { action in
            self.hideKeyboard()
           // ProgressHUD.show("Processing")
            var paymentContext = STPPaymentContext()
            paymentContext = STPPaymentContext(customerContext: STPCustomerContext(keyProvider: self.customerContext))
            paymentContext.delegate = self
            paymentContext.hostViewController = self
            paymentContext.paymentAmount = 5000 // This is in cents, i.e. $50 USD
            paymentContext.requestPayment()
        }))
        alert.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: { action in
            
        }))

        self.present(alert, animated: true)
    }
    
    
    
    func paymentOptionsViewController(_ paymentOptionsViewController: STPPaymentOptionsViewController, didFailToLoadWithError error: Error) {
        print(error)
        changePostionOfView = false
         dismiss(animated: true)
    }
    func paymentOptionsViewController(_ paymentOptionsViewController: STPPaymentOptionsViewController, didSelect paymentOption: STPPaymentOption) {
       
        if ignoreFirstTap == true{
        
               let configuration = STPPaymentConfiguration()
               let supportedCountry: Set<String> = ["US"]
               configuration.availableCountries = supportedCountry
               configuration.companyName = "Name"
               configuration.publishableKey = "KEY"
               configuration.appleMerchantIdentifier = "Merchant"
                configuration.shippingType = .shipping
        
               configuration.verifyPrefilledShippingAddress = false
               let contact: Set<STPContactField> = [.postalAddress,.phoneNumber]
               configuration.requiredShippingAddressFields = contact
             
        if let pm = paymentOption as? STPPaymentMethod {
         
               
               let add = STPAddress()
                add.city = pm.billingDetails?.address?.city
                add.country = pm.billingDetails?.address?.country
                add.postalCode = pm.billingDetails?.address?.postalCode
                add.line1 = pm.billingDetails?.address?.line1
                add.name = pm.billingDetails?.name
                add.state = pm.billingDetails?.address?.state
                add.line2 = pm.billingDetails?.address?.line2
                let userinfo = STPUserInformation()
                userinfo.shippingAddress = add
              
               let shipping = PKShippingMethod()
               shipping.amount = 0.00
               shipping.label = "Delivery company"
               shipping.detail = "It is choosed by seller"
               shipping.identifier = "seller"
               let shippingVC = STPShippingAddressViewController(configuration: configuration, theme: STPTheme.default(), currency: "usd", shippingAddress: userinfo.shippingAddress, selectedShippingMethod: shipping, prefilledInformation: userinfo)
               shippingVC.delegate = self
               DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(300), execute: {
                   self.navigationController?.pushViewController(shippingVC, animated: true)
               })
    }
        if let pm = paymentOption as? STPApplePayPaymentOption{
          
            let add = STPAddress()
        
              let userinfo = STPUserInformation()
              userinfo.shippingAddress = add
            
             let shipping = PKShippingMethod()
            shipping.amount = 0.00
             shipping.label = "Delivery company"
             shipping.detail = "It is choosed by seller"
             shipping.identifier = "seller"
             let shippingVC = STPShippingAddressViewController(configuration: configuration, theme: STPTheme.default(), currency: "usd", shippingAddress: userinfo.shippingAddress, selectedShippingMethod: shipping, prefilledInformation: userinfo)
             shippingVC.delegate = self
             DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(300), execute: {
                 self.navigationController?.pushViewController(shippingVC, animated: true)
             })
            }
        }else{
            ignoreFirstTap = true
        }
     func paymentOptionsViewControllerDidFinish(_ paymentOptionsViewController: STPPaymentOptionsViewController) {
           print("finish")
       }
            }
        
    func paymentOptionsViewControllerDidCancel(_ paymentOptionsViewController: STPPaymentOptionsViewController) {
        print("cancel")
        changePostionOfView = false
        navigationController?.popViewController(animated: true)
    }
    
    func paymentContext(_ paymentContext: STPPaymentContext, didFailToLoadWithError error: Error) {
        
    }
    
    func paymentContextDidChange(_ paymentContext: STPPaymentContext) {
        
    }
    
    func paymentContext(_ paymentContext: STPPaymentContext, didCreatePaymentResult paymentResult: STPPaymentResult, completion: @escaping STPPaymentStatusBlock) {
    }
    
    func paymentContext(_ paymentContext: STPPaymentContext, didFinishWith status: STPPaymentStatus, error: Error?) {
        
    }`

Sorry if code is a bit unreadable hah
Also my device is iPhone XS Max, iOS 13.2

**Comment by yuki-stripe** [comment]
Thanks @Marcin951.

From the screenshot, the navigationController's navigationBar is white when dark mode is enabled.  Could you show the code setting that navigationController up?  And is it dark when the `STPPaymentOptionsViewController` is presented?
