### ISSUE TITLE
Stripe Standard Integration not working after iOS 13.0 update

### ISSUE THREAD

**Issue by efsol-inc** [stripe/stripe-ios#1417]
## Summary
After the iOS 13.0 update, standard Stripe integration is not working. Everything goes well just before presenting Apple Pay sheet to user. The sheet never appears and it only produces the following log in console:

`[General] Connection to remote alert view service failed.`

## Code to reproduce
    - Standard Stripe integration for Apple pay as per Stripe documentation. 
    - The device that is capable of making payments via Apple pay. 
    - Triggering ApplePay will never show the ApplePay sheet.

## iOS version
   - iOS 13.0.0

## Installation method
   - Cocoapods

## SDK version
   - Stripe 18.0.0

UPDATE:
 The exact code works fine on iOS 12.0 and iOS 11.0 but doesn't work on iOS 13.0

**Comment by aliriaz-stripe** [comment]
Hi @efsol-inc , was this using the simulator?

**Comment by davidme-stripe** [comment]
This appears to be broken in the iOS 13 Simulator for everyone: https://stackoverflow.com/questions/57891144/applepay-error-connection-to-remote-alert-view-service-failed-on-ios-13

I'd recommend trying again on a real device.

**Comment by davidme-stripe** [comment]
This seems to be fixed in Xcode 11.2.

**Comment by efsol-inc** [comment]
Thank you @davidme-stripe! it has been fixed in Xcode 11.2, seems like this issue was on Apple's side and not Stripe.
