### ISSUE TITLE
Fix PTKTextField.h warnings in Xcode 6.3.1

### ISSUE THREAD

**Issue by intonarumori** [stripe/stripe-ios#142]
Please fix the following warnings for Xcode 6.3.1 in STPCard.m:

``
/.../Pods/Stripe/Stripe/STPCard.m:229:30: Comparison of address of 'NSCalendarIdentifierGregorian' not equal to a null pointer is always true
``

**Comment by jflinter** [comment]
This should be fixed as of version `4.0.2`, but please feel free to reopen if you're still seeing this issue.
