### ISSUE TITLE
Checkmark icon on top of Delete button

### ISSUE THREAD

**Issue by sushimatou** [stripe/stripe-ios#1421]
## Summary
When a card is selected in the card options tableview, edit mode is triggered, just after tapping the "red icon circle" on the left side:

the checkmark of the row is misplaced, in front of the delete button. A weird animation occurs also on this checkmark when deletion is completed by swiping or clicking on the delete button. 

## Code to reproduce
`STPPaymentOptionTableViewCell`, the `checkmark` position is not the right one, probably when `layoutSubviews()` is called.

## iOS version
iOS 13.0

## Installation method
Cocoapods with Xcode 10.3

## SDK version
Stripe 10.2

## Screenshot
![IMG_7529](https://user-images.githubusercontent.com/10923684/67222150-0a98c300-f42d-11e9-87d7-b5b22bed2cca.jpg)

**Comment by csabol-stripe** [comment]
@sushimatou thanks for the report! I've got a branch that fixes this, just dealing with some XCode issues then I'll get it merged in :)

**Comment by davidme-stripe** [comment]
This was fixed in v18.1.0!
