### ISSUE TITLE
Crash when adding a card

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#1426]
## Summary

The app crashes when clicking on "Add Card". It seems to happen with certain shipping addresses. 

## Code to reproduce
See in this video:
https://www.dropbox.com/s/5uofsjvpqoc11rf/stripe%20bug.MP4?dl=0

## iOS version
iOS 13

## Installation method
Cocoapods 

## SDK version
14.0.0

## Other information
The crash error is:
Fatal Exception: NSInternalInconsistencyException
Requested the number of rows for section (1) which is out of bounds

And it crashes on line 401 and 410 in STPAddCardViewController.
Line 401:
    NSInteger rowsInSection = [self.tableView numberOfRowsInSection:STPPaymentCardBillingAddressSection];

Line 410:
    NSInteger rowsInSection = [self.tableView numberOfRowsInSection:STPPaymentCardBillingAddressSection];

**Comment by davidme-stripe** [comment]
I can't reproduce this myself, but I have a guess as to what's causing it. Can you try using my branch for #1427?

In your Podfile, set pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'davidme/fix-ios13-tableviewdata', then run pod install.

**Comment by davidme-stripe** [comment]
I just realized you're on version 14.0, getting to the latest version might take some migration work. Maybe you can try doing this in your local copy of Stripe: https://github.com/stripe/stripe-ios/pull/1427/files

**Comment by odedharth** [comment]
@davidme-stripe yes, this solved it, thanks for the quick reply!
