### ISSUE TITLE
Native Swift SDK?

### ISSUE THREAD

**Issue by Andrewangeta** [stripe/stripe-ios#1436]
Thanks for all the hard work on this. I know it’s not easy and requires a lot of energy and effort. Question: Is there any plan to have a Native swift implementation? I just noticed the Android SDK is written in pure Kotlin which is amazing and is forward looking. Just wondering if there has ever been any talks or discussions potentially for a native swift SDK? It’s be pretty cool and would be nice to have a swift first approach to a stripe API for iOS.

**Comment by yuki-stripe** [comment]
Hi @Andrewangeta 

Yes, we're looking into this.  

To everyone interested - if there are any specific things you would like to see in a Swift version of the SDK, please share!

**Comment by Andrewangeta** [comment]
Nice!!!

**Comment by valexa** [comment]
In terms of specifics reusable SwiftUI views and/or Observable Combine models would be great !

**Comment by janekwunderlich** [comment]
Are you working on a new SDK right now?

**Comment by davidme-stripe** [comment]
News for folks following this issue: [We're converting the existing SDK to Swift](https://github.com/stripe/stripe-ios/issues/1680). The API surface hasn't changed, but we're planning to build on this to introduce new Swift-first APIs in the future.

**Comment by davidme-stripe** [comment]
We shipped this, and we're now slowly adding support for SwiftUI. Follow https://github.com/stripe/stripe-ios/issues/1204#issuecomment-761274383 for details.
