### ISSUE TITLE
Amex CVC check

### ISSUE THREAD

**Issue by iKorich** [stripe/stripe-ios#1441]
Hi guys,

continue thread https://github.com/stripe/stripe-ios/issues/890,

in STPCardValidator.m you have:

```
+ (NSUInteger)minCVCLength {
    return 3;
}
```

and that doesn't work for Amex card
please change it to 
```
+ (NSUInteger)minCVCLengthForCardBrand:(STPCardBrand)brand {
    switch (brand) {
        case STPCardBrandAmex:
        case STPCardBrandUnknown:
            return 4;
        default:
            return 3;
    }
}
```

**Comment by yuki-stripe** [comment]
Hi @iKorich,

It's possible for Amex cards to have a 3 digit CVC equivalent that is accepted by the Stripe API.  As far as I know this has not changed, and the current code is correct.

See https://github.com/stripe/stripe-ios/issues/103

**Comment by iKorich** [comment]
Hi @yuki-stripe ,

please check https://www.cvvnumber.com/cvv.html

**Comment by yuki-stripe** [comment]
@iKorich This value is referred to by American Express as a "Three digit Card Security Code (CSC)" here: https://global.americanexpress.com/faq?question=Do%20I%20need%20to%20do%20anything%20before%20using%20my%20Gift%20Card?

If you find the Stripe API does not accept this as the "CVC" value, please reopen this issue!
