### ISSUE TITLE
How to delete customer's payment method with payment method id

### ISSUE THREAD

**Issue by manishmatellio** [stripe/stripe-ios#1448]
i m using latest pod of stripe , I getting all payment methods list , but i stuck with delete payment method . please tell me how to delete payment method from saved payment methods. Please reply as soon as possible

**Comment by davidme-stripe** [comment]
Hey @manishmatellio, thanks for writing in. You should be able to delete PaymentMethods from the PaymentOptionsViewController UI by swiping left on them or using the `Edit` button. To delete one programmatically, you'll want to call `detachPaymentMethodFromCustomer:` on the `STPCustomerContext`. Let me know if this isn't working for you!

**Comment by manishmatellio** [comment]
thanks for reply. Done with  detachPaymentMethodFromCustomer. i done whole process with payment method. but want to need with card.


1 . New add card with customer 
    -- got stripeID with didCreatePaymentMethod

please tell me the **function name** for below steps, i m using  latest stripe version 
2.  Create customer with email id and stripe id add with customer ?
   --  stripe id pass with create customer 
3. get all card list attached with customer 
   -- need card information with card id
4. card delete  function ?
 -- need to card id for delete card from customer
Thanks

**Comment by yuki-stripe** [comment]
Hi @manishmatellio 

You can't create a Customer from the client, only the server using this API: https://stripe.com/docs/api/customers/create

You might also find this step helpful to do that: https://stripe.com/docs/payments/save-after-payment#ios-save-payment-method

To get all cards for a customer, you can use the `listPaymentMethodsForCustomerWithCompletion:` method on `STPCustomerContext`.

To delete cards, use the `detachPaymentMethodFromCustomer:completion:` as mentioned above.

**Comment by davidme-stripe** [comment]
Hi @manishmatellio, I just tested this, and detachPaymentMethodFromCustomer should work for both card source IDs and PaymentMethod IDs.

As for your other questions, this kind of support might be better handled via our support site at https://support.stripe.com/contact. Feel free to CC me on the email or ticket!

**Comment by rashdan** [comment]
How can we manage previously added cards in ios stripe? Means to delete the previously added card or select the card from previously added card lists. 
here is my code:

RCT_EXPORT_METHOD(showStripeModal: (NSString *) phone) {
  dispatch_async(dispatch_get_main_queue(), ^{
    client = [[StripeApiClient alloc] init];
    client.phone = phone;
    STPCustomerContext *customerContext = [[STPCustomerContext alloc] initWithKeyProvider: client];
    STPPaymentConfiguration *noBillingConfig = [[STPPaymentConfiguration alloc] init];
    noBillingConfig.requiredBillingAddressFields = STPBillingAddressFieldsNone;
    STPTheme *theme = [[STPTheme alloc] init];
    STPPaymentContext *paymentContext = [[STPPaymentContext alloc] initWithCustomerContext:customerContext configuration:noBillingConfig theme:theme];
    UIViewController *controller = RCTPresentedViewController();
    [RCTUtilsUIOverride setPresentedViewController:controller];

    paymentContext.hostViewController = controller;
    paymentContext.delegate = self;
    
    dispatch_async(dispatch_get_main_queue(), ^{
      [paymentContext presentPaymentOptionsViewController];
    });

  });
}

**Comment by faizqadri234** [comment]
How can we manage previously added cards in ios stripe? Means to delete the previously added card or select the card from previously added card lists.
i am always shown add card View. it dont show any previously added card list.

![Simulator Screen Shot - iPhone 11 - 2021-05-05 at 16 35 01](https://user-images.githubusercontent.com/83703685/117134988-c9be9000-adbf-11eb-9ffe-583e829d5f85.png)

here is my code:

```
RCT_EXPORT_METHOD(showStripeModal: (NSString *) phone) {
dispatch_async(dispatch_get_main_queue(), ^{
client = [[StripeApiClient alloc] init];
client.phone = phone;
STPCustomerContext *customerContext = [[STPCustomerContext alloc] initWithKeyProvider: client];
STPPaymentConfiguration *noBillingConfig = [[STPPaymentConfiguration alloc] init];
noBillingConfig.requiredBillingAddressFields = STPBillingAddressFieldsNone;
STPTheme *theme = [[STPTheme alloc] init];
STPPaymentContext *paymentContext = [[STPPaymentContext alloc] initWithCustomerContext:customerContext configuration:noBillingConfig theme:theme];
UIViewController *controller = RCTPresentedViewController();
[RCTUtilsUIOverride setPresentedViewController:controller];

paymentContext.hostViewController = controller;
paymentContext.delegate = self;

dispatch_async(dispatch_get_main_queue(), ^{
  [paymentContext presentPaymentOptionsViewController];
});
});
}
```
