### ISSUE TITLE
Crash: Application crashes when choosing a country

### ISSUE THREAD

**Issue by UlanovGeorge** [stripe/stripe-ios#1449]
## Summary
Application crashes when choosing a country

## Code to reproduce
Payment Method -> + Add New Card... -> Billing Address -> choose a country 

First country:
- United Kingdom
then:
- United Arab Emirates

repeat the choice of country several times  
United Kingdom <--> United Arab Emirates

## iOS version
11.0 - 13.2.3

## Installation method
lazy var customerContext: STPCustomerContext = STPCustomerContext(keyProvider: self)
lazy var paymentContext: STPPaymentContext = {
        let configuration = STPPaymentConfiguration.shared()
        configuration.publishableKey = "publishableKey"
        configuration.appleMerchantIdentifier = "appleMerchantIdentifier"
        configuration.requiredBillingAddressFields = .full
        return STPPaymentContext(customerContext: customerContext, configuration: configuration, theme: STPTheme.default())
    }()

 @IBAction func selectPaymentMethod() {
        paymentContext.presentPaymentOptionsViewController()
    }

## SDK version
pod 'Stripe', '~> 18.2.0'

## Other information
2019-11-26 15:49:53.593188+0200 Test[44444:444444] *** Assertion failure in -[UITableView _endCellAnimationsWithContext:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.54.4/UITableView.m:2012
2019-11-26 15:49:53.667116+0200 Test[44444:444444] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 1.  The number of rows contained in an existing section after the update (6) must be equal to the number of rows contained in that section before the update (6), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000011a97d1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001198b4031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000011a982472 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000113045652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   UIKit                               0x000000011710bd9b -[UITableView _endCellAnimationsWithContext:] + 19031
	5   UIKit                               0x0000000117126d33 -[UITableView _updateRowsAtIndexPaths:withUpdateAction:rowAnimation:usingPresentationValues:] + 1383
	6   UIKit                               0x0000000117126f5f -[UITableView deleteRowsAtIndexPaths:withRowAnimation:] + 121
	7   Stripe                              0x0000000115d98be4 -[STPAddCardViewController addressViewModel:removedCellAtIndex:] + 253
	8   Stripe                              0x0000000115d9fc61 -[STPAddressViewModel updatePostalCodeCellIfNecessary] + 1201
	9   Stripe                              0x0000000115da0aae -[STPAddressViewModel setAddressFieldTableViewCountryCode:] + 163
	10  Stripe                              0x0000000115d9eabd -[STPAddressFieldTableViewCell pickerView:didSelectRow:inComponent:] + 471
	11  UIKit                               0x0000000116fce527 -[UIPickerView _sendSelectionChangedForComponent:notify:] + 103
	12  UIKit                               0x0000000116fce769 -[UIPickerView _sendSelectionChangedFromTable:notify:] + 364
	13  UIKit                               0x00000001178d756e -[UIPickerTableView _scrollingFinished] + 187
	14  UIKit                               0x00000001170e59ec -[UIScrollView(UIScrollViewInternal) _delegateScrollViewAnimationEnded] + 82
	15  UIKit                               0x00000001170e5b7a -[UIScrollView(UIScrollViewInternal) _scrollViewAnimationEnded:finished:] + 311
	16  UIKit                               0x0000000117138467 -[UITableView _scrollViewAnimationEnded:finished:] + 53
	17  UIKit                               0x00000001178d6b49 -[UIPickerTableView _scrollViewAnimationEnded:finished:] + 45
	18  UIKit                               0x000000011717779f -[UIAnimator stopAnimation:] + 422
	19  UIKit                               0x0000000117177ee4 -[UIAnimator _advanceAnimationsOfType:withTimestamp:] + 282
	20  QuartzCore                          0x00000001158e5850 _ZN2CA7Display11DisplayLink14dispatch_itemsEyyy + 834
	21  QuartzCore                          0x0000000115a27a12 _ZL22display_timer_callbackP12__CFMachPortPvlS1_ + 248
	22  CoreFoundation                      0x000000011a90c4b9 __CFMachPortPerform + 169
	23  CoreFoundation                      0x000000011a90c3f9 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	24  CoreFoundation                      0x000000011a90c361 __CFRunLoopDoSource1 + 465
	25  CoreFoundation                      0x000000011a903f64 __CFRunLoopRun + 2532
	26  CoreFoundation                      0x000000011a90330b CFRunLoopRunSpecific + 635
	27  GraphicsServices                    0x000000011e9e5a73 GSEventRunModal + 62
	28  UIKit                               0x0000000116fea057 UIApplicationMain + 159
	29  Test                                0x000000010c2ae1cb main + 75
	30  libdyld.dylib                       0x000000011c073955 start + 1
	31  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by davidme-stripe** [comment]
Thanks for the report! We'll fix this ASAP.

**Comment by davidme-stripe** [comment]
It's fixed in the `master` branch, let me know if that works for you.

**Comment by UlanovGeorge** [comment]
Thanks! It works now
For implementation in the project we will wait for the release

**Comment by davidme-stripe** [comment]
It's out! Update to 18.3.0 to get the fix.

**Comment by UlanovGeorge** [comment]
Thanks!
