### ISSUE TITLE
STPPaymentCardTextField UI update on cardParams change

### ISSUE THREAD

**Issue by zykis** [stripe/stripe-ios#1451]
## Summary
STPPaymentCardTextField UI doesn't updated on settings cardParams

## Code to reproduce
let cardParams = STPCardParams()
cardParams.number = "4242424242424242"
self.paymentField.cardParams = cardParams

## iOS version
13.1

## Installation method
CocoaPods

## SDK version
18.2.0

**Comment by yuki-stripe** [comment]
Hi @zykis, thanks for creating a new issue.

I just tried this out on master and I can't reproduce this - setting `cardParams` on `STPPaymentCardTextField` immediately changes the UI.  

I did notice the code you gave has `STPCardParams` - I assume you mean `STPPaymentMethodCardParams`.  If you do mean `STPCardParams`, what version of the SDK are you using?

**Comment by zykis** [comment]
@yuki-stripe , sorry for your time, but I messed something up, indeed.
Tested it again - I am not able to use STPCardParams directly.
Changing it with STPPaymentMethodCardParams works as expected - UI updated.
Sorry about that.
