### ISSUE TITLE
CVV in STPPaymentCardTextField isn't secure entry.

### ISSUE THREAD

**Issue by KoushikTE** [stripe/stripe-ios#1452]
## Secure text entry expected
***
In **STPPaymentCardTextField** we're expecting `secure text entry` for `cvv` field. This is enabled in SDK for Android. But in iOS the cvv is in plain text. And I could not find any property that toggles it.
***
Since cvv raises security concerns, please help me find any property as mentioned (if any), or please add it.

### Thanks!

**Comment by yuki-stripe** [comment]
Hi @KoushikTE,

This isn't currently configurable.  We'll add this to our internal project planning for a future release.

**Comment by KoushikTE** [comment]
Okay. Thanks!

**Comment by pavan-ml-sg** [comment]
@yuki-stripe is it configured in recent SDK?

**Comment by jasmitSO** [comment]
Hey @yuki-stripe , @KoushikTE 
Is secure text entry configured in cvv field of STPPaymentCardTextField?

**Comment by davidme-stripe** [comment]
Sorry, but we don't plan to support this. The PCI standard doesn't recommend masking the CVC, so we keep it unmasked for better UX.
