### ISSUE TITLE
How do we get the Stripe token from StripeID in payment method to initiate the payment

### ISSUE THREAD

**Issue by MandeepSingh1** [stripe/stripe-ios#1454]
The createToken delegate method on STPAddCardViewController was changed to createPaymentMethod, from v16.0.0 onwards.
STPAddCardViewController now creates PaymentMethod objects, not Tokens. You would need to implement the createPaymentMethod function: https://stripe.dev/stripe-ios/docs/Protocols/STPAddCardViewControllerDelegate.html#/c:objc(pl)STPAddCardViewControllerDelegate(im)addCardViewController:didCreatePaymentMethod:completion:

**Explanation**:- But we need to send token to backend for payment.
Please suggest me how to get the token to initiate the payment. We are not able to get the token, we do have payment method object but how do we retrieve the token from payment method object. You guys haven't mention anywhere that from StripeID you can get the stripeToken using this method:-
Here is the response when we create the payment method, But my backend developer is asking from the token but where is the token in this response. We have to do the transaction and for your kind information in your charge method we have to pass the token. But from where we have to get that token.
Payment Method Object = {
  "id": "pm_123456789",
  "object": "payment_method",
  "billing_details": {
    "address": {
      "city": null,
      "country": null,
      "line1": null,
      "line2": null,
      "postal_code": "42424",
      "state": null
    },
    "email": "jenny@example.com",
    "name": null,
    "phone": "+15555555555"
  },
  "card": {
    "brand": "visa",
    "checks": {
      "address_line1_check": null,
      "address_postal_code_check": null,
      "cvc_check": null
    },
    "country": "US",
    "exp_month": 8,
    "exp_year": 2020,
    "fingerprint": "Xt5EWLLDS7FJjR1c",
    "funding": "credit",
    "generated_from": null,
    "last4": "4242",
    "three_d_secure_usage": {
      "supported": true
    },
    "wallet": null
  },
  "created": 123456789,
  "customer": null,
  "livemode": false,
  "metadata": {
    "order_id": "123456789"
  },
  "type": "card"
}

**Comment by aliriaz-stripe** [comment]
Hi @MandeepSingh1 

The iOS SDK starting v16.0.0 and above has defaulted the pre-built UI (such as STPAddCardViewController) to PaymentMethods, which are tokenized payment objects that are only supported on PaymentIntents to create charges. They do not work with /v1/charges.

Your backend developer can integrate PaymentIntents with the synchronous flow, as that models what /v1/charges does [0] (iOS app posts the PaymentMethod ID, server creates+confirms a PaymentIntent). 
Or better yet, our recommendation is to use the "automatic" flow with PaymentIntents [1], confirming them client-side with STPPaymentHandler.

If you can only use Tokens, then you can either create a token manually using STPAPIClient or use an SDK version that is before 16.0.0.

If you have any questions about integrations, please do write in to https://support.stripe.com/contact , github issues are mainly for reporting bugs/issues/feature requests in the SDK

[0] https://stripe.com/docs/payments/accept-a-payment-synchronously#ios and specifically https://stripe.com/docs/payments/accept-a-payment-synchronously#on-the-server
[1] https://stripe.com/docs/payments/accept-a-payment#ios
