### ISSUE TITLE
SDK 18.3.0 Requirements do not match

### ISSUE THREAD

**Issue by DanieleCux** [stripe/stripe-ios#1455]
## Summary
Hi, I am a GitHub newbie, I am not sure I should really open an issue on this, anyway: I am unable to install the latest sdk version, I get instead the version 17.0.2

## Code to reproduce
Create an empty iOS project, set iOS 9.2 as deployment target, and try to install the sdk using the usual "pod 'Stripe' ", in the Podfile and the "pod install" command

## iOS version
9.2

## Installation method
I tried to install the latest sdk, 18.3.0, after checking the related [tagged requirements](https://github.com/stripe/stripe-ios/tree/v18.3.0#requirements), and reading that the sdk
> ...is compatible with apps targeting iOS 9 or above

I am using iOS 9.2 as deployment target both in my project and as a specification in the Podfile and so I thought I was ok

I tried to force the installation of the latest version using in my Podfile
> pod 'Stripe', '18.3.0'

After running "pod outdated" as a preliminary check I had:
> [!] CocoaPods could not find compatible versions for pod "Stripe":
> Specs satisfying the `Stripe (= 18.3.0)` dependency were found, but they required a higher minimum deployment target.

I checked the [repository specification](https://github.com/stripe/stripe-ios/blob/master/Stripe.podspec) here on GitHub and I have found out a different requirement:
> s.ios.deployment_target = '10.0'

This is what prevents the desired outcome; is this deployment target the right one? Is the latest sdk only for apps targeting iOS 10 or above?

**Comment by aliriaz-stripe** [comment]
Hello @DanieleCux !

Stripe-iOS v18.0.0 dropped iOS 9 support: https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#1800-2019-10-04 so your minimum deploy target should be iOS 10 with v18.0.0 above.

If you want to target iOS 9, then it would have to be SDK v17.0.2.

**Comment by jdisho** [comment]
If you are targeting `>= iOS 10` and still have this issue,  try `pod install --repo-update`.

**Comment by DanieleCux** [comment]
Thank you, both of you: targeting iOS 10 all works perfectly as it is supposed to
