### ISSUE TITLE
Alipay Redirect URL Computation failed

### ISSUE THREAD

**Issue by chuanhd** [stripe/stripe-ios#1458]
## Summary
Im trying to use Alipay with Stripe but I got `Redirect URL computation failed` with default example of stripe-ios 

## Code to reproduce
`Non-Card payment Example` on example folder of this repo

## iOS version
iOS 12.4 on Simulator 

## Installation method
Use default example on this repo

## SDK version
18.3.0

## Other information

![Simulator Screen Shot - iPhone X - 2019-12-08 at 22 34 27](https://user-images.githubusercontent.com/1701022/70391843-186dcc00-1a0c-11ea-8f2c-45c2575969db.png)

**Comment by aliriaz-stripe** [comment]
Hi @chuanhd ! Thanks for writing in with details!

We've fixed an issue on Stripe's end with Alipay (but not in the iOS SDK) earlier today, please do try again and let us know if you're still running into this.
