### ISSUE TITLE
IDEAL payment from app.

### ISSUE THREAD

**Issue by jatinnakrani** [stripe/stripe-ios#1460]
Hello,

I want to integrate IDEAL in application. 

I am using swift 4.2 and XCODE 10.1

STPBankSelectionViewController not giving proper names of the bank(I have checked in web application. it's not same . eg "ing" bank code )

Question 1 : how can I get proper bank names.

![WebBank](https://user-images.githubusercontent.com/48938643/70516876-b7560d80-1b5d-11ea-83b1-a13c02fc02d7.png)
![MyAppBank](https://user-images.githubusercontent.com/48938643/70516878-b7560d80-1b5d-11ea-80e8-e1979e72e5f4.PNG)
=======

let temp4 = STPSourceParams.idealParams(withAmount: UInt(10.2), name: "jack", returnURL: "com.Gr***S***://stripe-redirect", statementDescriptor: "123", bank: "ing")

STPAPIClient.shared().createSource(with: temp4) { (tempSTPSource, tempError) in
                print(tempSTPSource)
                print(tempError)
                if let url : URL = tempSTPSource?.redirect?.url {
                    UIApplication.shared.open(url, options: [:]) { (flag) in
                        print(flag)
                    }
                }
}

this call back in AppDelegate.
func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
if (stripeHandled) {
            print(options)
            print(url)
            GFunction.sharedMethods.navigateUser()
            GFunction.ShowAlert(message: "***** booked successfully")
            return true
        } else {
            // This was not a stripe url, do whatever url handling your app
            // normally does, if any.
        }
        return false
}
=========
Question 2 : I am not getting success , though I taped on "AUTHORISE TEST PAYMENT" test

**Comment by php3sanatan** [comment]
Please once refer https://stripe.com/docs/sources/ideal url to get proper bank names.

**Comment by aliriaz-stripe** [comment]
Hello @jatinnakrani , for questions related to integrating the Stripe iOS SDK, please write in to https://support.stripe.com/contact and the team there can help you!

The github issues should only be used to report bugs/request features on Stripe iOS.
