### ISSUE TITLE
WeChat Pay example problem

### ISSUE THREAD

**Issue by chuanhd** [stripe/stripe-ios#1463]
## Summary
Test WeChat Pay with default `Non-Card payment example`. It never stop spinning

## Code to reproduce
Default `Non-Card payment example` on this git

## iOS version
iPhone 8 Plus
iOS 13.1.2
WeChat app installed

## Installation method
Project dependency

## SDK version

18.3.0

## Other information

The example app never stop spinning when create `STPRedirectContext` with WeChat Pay source. I notice that the WeChat Pay source does not have `nativeRedirectURL` value because source responsed from server does not have `ios_native_url` value. 

I double checked WeChat pay support document (https://stripe.com/docs/sources/wechat-pay). It say that I have to activate WeChat Pay in Dashboard but I can not enable it.
![Screen Shot 2019-12-16 at 22 30 26](https://user-images.githubusercontent.com/1701022/70919602-b9373980-2053-11ea-8e9a-589bee5f42b6.png)

Am I missing something or this function just not finish right now?

**Comment by yuki-stripe** [comment]
Hi @chuanhd 

You'll need to activate WeChat Pay before the example will work.  Please contact https://support.stripe.com/?contact=true to get help with that!

**Comment by chuanhd** [comment]
Hi @yuki-stripe ,

I can not reopen this issue. I have contacted with Stripe support. They said that I have to put my app on Live mode to activate WeChat pay. However, It still does not work.
`ios_native_url` value is still missing from Stripe's response. I tried to replace `ios_native_url` with `qr_code_url`. It open WeChat app and nothing happens after that. Could you help me figure out how to make it work?

Thank you!

**Comment by yuki-stripe** [comment]
Hi @chuanhd,

Sorry you're having trouble.  Mobile WeChat Pay support is in private beta; it sounds like it's still not enabled for your account (https://dashboard.stripe.com/account/payments/settings). 

Can you see this page https://stripe.com/docs/sources/wechat-pay/ios?

**Comment by chuanhd** [comment]
@yuki-stripe Thanks for your reply

I can not access your link https://stripe.com/docs/sources/wechat-pay/ios. Get 404 Not Found
Below is WeChat pay status on my account Dashboard
<img width="1093" alt="Screen Shot 2019-12-19 at 10 34 54 AM" src="https://user-images.githubusercontent.com/1701022/71142920-63c57d00-224b-11ea-90aa-7096816816d4.png">

**Comment by yuki-stripe** [comment]
@chuanhd Thank you for the screenshots and details, they're very helpful.  While WeChat Pay is activated for your account, the **mobile app (app to app) flow** is a separate feature in private beta — could you mention enabling the "WeChat Pay mobile app (app to app) flow" to Stripe support?  

I'm sorry for the trouble and the delayed response here.  We're working on making this less confusing.

**Comment by nahddw** [comment]
@chuanhd Hello, have you solved it.

**Comment by chuanhd** [comment]
@nahddw yes. I have done with WeChat Pay on iOS
Basically you have to contact Stripe support to enable WeChat app to app payment on your Dashboard and make sure you are using live publishable key

**Comment by nahddw** [comment]
@chuanhd  
Thank you for your answer.
I've enabled it but it doesn't work. I printed it and it returns null.

**Comment by yuki-stripe** [comment]
@nahddw Please reach out to support@stripe.com to be added to the private beta.
