### ISSUE TITLE
Stripe + Cardio all example links in the documentation are are broken 

### ISSUE THREAD

**Issue by perlasivakrishna** [stripe/stripe-ios#1465]
How to integrate a cardio with stripe so that once card is scanned the stripe should give a call back when card info is provided.

**Comment by davidme-stripe** [comment]
Sorry for the broken links — we'll get those fixed.

You'll want to follow the instructions on our [README](https://github.com/stripe/stripe-ios/#card-io), including installing the card.io SDK and running the script, then using our Basic Integration app from here: https://github.com/stripe/stripe-ios/tree/master/Example/Basic%20Integration

**Comment by davidme-stripe** [comment]
Fixed in #1493.
