### ISSUE TITLE
STPPaymentOptionsViewController + 3DS

### ISSUE THREAD

**Issue by Matsepura** [stripe/stripe-ios#1468]
Hi! How can I use STPPaymentOptionsViewController to add card, but I want to add card only with 3DS check. 
Maybe you have some property on config to turn this setup on?

**Comment by yuki-stripe** [comment]
Hi @Matsepura!

To clarify, you want to save cards so that you can charge them when the user is not in the app, is that correct?  

This feature is on our roadmap but not currently implemented.

**Comment by Matsepura** [comment]
Yes, I want to save card to make off-session payments later. 

:( 
Thank you. Hope you implement it faster!💪🏼🚀
