### ISSUE TITLE
Feature request - disable the ability to delete cards

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#1481]
Currently, it's possible to delete cards using the UI. This causes a problem, in which customers subscribe, and then remove their card, which creates a lot of past-due subscriptions. 

It would be helpful this disables this ability. Then customers will cancel their subscription, instead of deleting their card and being "past-due" subscribers.

**Comment by yuki-stripe** [comment]
Hi @odedharth!  

`STPPaymentContext` and `STPPaymentOptionsViewController` can be configured with `STPPaymentConfiguration`, which has a `canDeletePaymentOptions` property that should do what you're looking for.

**Comment by TYuan6** [comment]
Hey @yuki-stripe Is it possible to prevent users from removing a specific card on the Stripe payment element based on labels or metadata?

**Comment by yuki-stripe** [comment]
Hello @TYuan6, that's not possible today.

**Comment by urvir123** [comment]
can someone send me the usecases for card deletion scenarios?
