### ISSUE TITLE
Cannot add a new credit card using the SDK

### ISSUE THREAD

**Issue by mansoorshahsaid** [stripe/stripe-ios#1483]
## Summary
I'm using the basic integration of the Stripe SDK and I cannot add a credit card on to my Stripe customer account. Creating the Stripe account works fine and if I already have a credit card, 
then I can select it for payment. In short, every thing works in the SDK but I can't add a new credit card.

## Pictures of the issue

![Simulator Screen Shot - iPhone 8 - 2020-01-29 at 15 22 46](https://user-images.githubusercontent.com/22176322/73394365-7e0f6380-42ab-11ea-9023-b9df8b1d8c42.png)
![Simulator Screen Shot - iPhone 8 - 2020-01-29 at 15 22 52](https://user-images.githubusercontent.com/22176322/73394385-89fb2580-42ab-11ea-9063-3c227c2bdc58.png)

## iOS version
iOS 13.3

## Installation method

Through the basic integration guide: https://stripe.com/docs/mobile/ios/basic

## SDK version

Pod: 18.4.0, API: 2019-12-03, NPM: 8.8.0

## Other information

We're testing this on the Stripe test platform, trying to add the credit card 4242.

**Comment by yuki-stripe** [comment]
Hi @mansoorshahsaid 

Do you use Stripe Connect / set `stripeAccount` anywhere?

**Comment by mansoorshahsaid** [comment]
Hey @yuki-stripe, I'm not using Stripe Connect anywhere. I'm simply using Stripe Payments with the basic integration for iOS. We tested it on our Android app and everything works fine. There are no problems when adding a credit card. But on iOS, I keep getting this same error every time I'm trying to add a card.

Also what do you mean by set `stripeAccount`?

**Comment by yuki-stripe** [comment]
@mansoorshahsaid Ah I thought this could be related to Stripe Connect, but never mind!  

It looks like the PaymentMethod in the screenshot was created using one account, but the ephemeral key you provide is for a Customer created under a different account.  

Could you check that the SDK's publishable key and the server's secret key are for the same account?  You can view testmode keys here: https://dashboard.stripe.com/test/apikeys.

**Comment by mansoorshahsaid** [comment]
Ah yes, that was such a silly mistake! We double checked and in fact iOS was using a publishable key for a different Stripe account. We changed it to the right one and now everything works! 

Thanks a lot @yuki-stripe! Now everything is back to normal 😄

**Comment by WDODW** [comment]
Tests/installation_tests/cocoapods/with_frameworks_swift/test.sh" exited with 0.
14990.01s$ [ "$TEST_TYPE" != installation_carthage ] || ./Tests/installation_tests/carthage/test.sh
1500The command "[ "$TEST_TYPE" != installation_carthage ] || ./Tests/installation_tests/carthage/test.sh" exited with 0.
15010.01s$ [ "$TEST_TYPE" != documentation ] || ./ci_scripts/check_documentation.sh
1502The command "[ "$TEST_TYPE" != documentation ] || ./ci_scripts/check_documentation.sh" exited with 0.
