### ISSUE TITLE
Crash when entering bank card number

### ISSUE THREAD

**Issue by Goodman333** [stripe/stripe-ios#1486]
## Summary

I encountered a problem, we have two users crash when entering bank card number

## iOS version

iPhone 7 Plus, iOS 13.3
iPhone XS, iOS 13.3

## Installation method

Cocoapods

## SDK version

Stripe (18.0.0)

## Other information

<img width="1079" alt="WechatIMG7" src="https://user-images.githubusercontent.com/9305248/73905129-4458e100-48d9-11ea-95e1-b336a4c1e687.png">

**Comment by davidme-stripe** [comment]
Thanks for reporting this, I'm trying various inputs to reproduce the issue. Any additional information you can provide would be helpful!

**Comment by Goodman333** [comment]
> Thanks for reporting this, I'm trying various inputs to reproduce the issue. Any additional information you can provide would be helpful!

Thank you for replying, I will provide you with a complete crash file, hope this will be helpful
[010927ed81eb474c981e97964668216b-symbolicated.crash.zip](https://github.com/stripe/stripe-ios/files/4209398/010927ed81eb474c981e97964668216b-symbolicated.crash.zip)

**Comment by davidme-stripe** [comment]
I think this was fixed by #1519! Please re-open if you see it again.
