### ISSUE TITLE
Stripe error when trying to add a new credit card 

### ISSUE THREAD

**Issue by Vadimkomis** [stripe/stripe-ios#1497]
## Summary

One of our users tried to add a new credit card and he got the following error:
![Image from iOS](https://user-images.githubusercontent.com/6124787/74943586-9e21d680-53c2-11ea-81b0-4778803caf5e.jpg)

## Code to reproduce

I'm not sure how to reproduce it. When I tried it myself it worked fine, but I did see several users complain about this before 
## iOS version

iOS 13.3.1
## Installation method

Cocoapods 
## SDK version
13.2.0

13.2.0

**Comment by yuki-stripe** [comment]
Hey @Vadimkomis - this error happens when you don't set the SDK publishable key.  Can you confirm you call `Stripe.setDefaultPublishableKey` before you use the SDK (ie in `application:didFinishLaunchingWithOptions:`)?

**Comment by Vadimkomis** [comment]
@yuki-stripe  I was not doing that. I'm assuming adding that, should fix it, right ?

**Comment by yuki-stripe** [comment]
@Vadimkomis Yes, that should fix it.

**Comment by davidme-stripe** [comment]
Closing this out for now—let us know if you're still encountering this problem!
