### ISSUE TITLE
4.0.1 Could not build Objective-C Module

### ISSUE THREAD

**Issue by acwright** [stripe/stripe-ios#150]
I'm getting the following error after updating Stripe pod to 4.0.1: 'STPNullabilityMacros.h' file not found

![screen shot 2015-05-06 at 5 47 47 pm](https://cloud.githubusercontent.com/assets/608373/7505457/33b98824-f418-11e4-9dcf-a9eb22780c75.png)

**Comment by Suz** [comment]
+1 same here. 
I've tried uninstalling and reinstalling with Cocoapods, but still the same. I was hoping modifying search paths would help, but no luck so far.

**Comment by jflinter** [comment]
Thanks for bringing this up - I believe I've diagnosed the issue; working on a fix now.

**Comment by jflinter** [comment]
This should be fixed as of 4.0.2, which I just released. Going to close this for now, but feel free to re-open if anyone sees issues on 4.0.2. Thanks again for opening this, and sorry for any trouble!

**Comment by Suz** [comment]
Thank you!! That worked perfectly.
