### ISSUE TITLE
Navigation Bar in STPAddCardViewController doesn't show up sometimes

### ISSUE THREAD

**Issue by sajib-ghoshInnofied** [stripe/stripe-ios#1503]
When STPAddCardViewController is opened, the navigation bar which includes Cancel button and Done button doesn't show up sometimes. It happens 1 time out of 20 times (approx.). Otherwise it works fine. 

SDK version - 15.0.1
iOS version - 10.13.6

Could you please help me out.
Thanks in advance.

**Comment by aliriaz-stripe** [comment]
@sajib-ghoshInnofied  hello!

Can you paste only the relevant code for how you're setting up + navigating to the STPAddCardViewController in a pastebin link and send that over here? 

Please do include how you're modifying the STPTheme of the STPAddCardViewController and how you're presenting it

**Comment by sajib-ghoshInnofied** [comment]
Hi @aliriaz-stripe ,

Thanks for your response.

We are just simply presenting the UPCAddCardVC which is a subclass of STPAddCardViewController.

`let addCardViewController = UPCAddCardVC()
addCardViewController.delegate = self
navigationController?.pushViewController(addCardViewController, animated: true)`

And in the UPCAddCardVC, we are showing the navigation bar in **viewWillAppear** and hiding the navigation bar in **viewWillDisappear**.

`class UPCAddCardVC: STPAddCardViewController {
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.isNavigationBarHidden = false
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.isNavigationBarHidden = true
    }
}`

Kindly let me know what is wrong in this code.

Thanks

**Comment by TusharSharma651** [comment]
yourNavigationController.navigationBar.isHidden = false

**Comment by davidme-stripe** [comment]
I'm closing this out, but let me know if you're still experiencing this issue. I'd also recommend trying our new [Payments UI beta](https://stripe.com/docs/mobile/payments-ui-beta) in SDK version 21.5.0.
