### ISSUE TITLE
50% of our user get this Stripe error when trying to add a new credit card 

### ISSUE THREAD

**Issue by Vadimkomis** [stripe/stripe-ios#1514]
## Summary

About 50% of our users get this error when they try to add a new credit card:
![Image from iOS](https://user-images.githubusercontent.com/6124787/74943586-9e21d680-53c2-11ea-81b0-4778803caf5e.jpg)

## Code to reproduce

I'm not sure how to reproduce it. When I tried it myself it worked fine, but I do see many of our users get this issue.  

## iOS version

iOS 13.3.1

## Installation method

Cocoapods 

## SDK version
13.2.0

13.2.0

## Other information

Pervasively opened this issue: https://github.com/stripe/stripe-ios/issues/1497 but the solution did not help. 

I'm not sure if the issue is with the SDK version. But it sounds like the token becomes nil after being set after we load `STPAddCardViewController`

We get an error on the following end point:
`api.stripe.com/v1/tokens`

**Comment by davidme-stripe** [comment]
Hey @Vadimkomis, I think we need a little more information about your integration to debug this. Could you reach out via https://support.stripe.com/ while logged into the appropriate account? Feel free to CC my username @stripe.com.
