### ISSUE TITLE
Know when a new card was added - STPPaymentContextDelegate

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#1517]
Hello,

Will you be able to add a delegate function to STPPaymentContextDelegate that gets triggered after a new card was added? 

Looks like it exists on the [STPAddCardViewControllerDelegate](https://stripe.dev/stripe-ios/docs/Protocols/STPAddCardViewControllerDelegate.html#/c:objc(pl)STPAddCardViewControllerDelegate(im)addCardViewController:didCreatePaymentMethod:completion:), but not on STPPaymentContextDelegate.

**Comment by aliriaz-stripe** [comment]
hello @odedharth  , the `paymentContextDidChange` delegate method is triggered every time a Customer adds a new card when using STPPaymentContext

**Comment by odedharth** [comment]
Hi @aliriaz-stripe, it seems that it's also trigged every time someone opens the add payment method screen (even if they didn't end up adding a new card).

**Comment by davidme-stripe** [comment]
Closing this issue out, as we don't plan to add this functionality to `STPPaymentContextDelegate`. I'd recommend trying our new [Payments UI beta](https://stripe.com/docs/mobile/payments-ui-beta) in SDK version 21.5.0 along with SetupIntents for this use case.

**Comment by BorisNikolic** [comment]
@davidme-stripe It would be really nice to distinguish between COntext setup and adding a new card. Currently, this delegate function is being called in both cases. Any hints?
