### ISSUE TITLE
send amount to single user with addon

### ISSUE THREAD

**Issue by farazhaider88** [stripe/stripe-ios#152]
i want to know if the following case is possible using stripe 

suppose i need to buy 2 tickets for 200 and person A bought this for me than i gave amount 220, means 20 extra to person A for facilitating me.

**Comment by jflinter** [comment]
Broadly speaking, yes, that sounds possible (probably using [Stripe Connect](stripe.com/connect)). I don't think this is the best place to have this discussion, though, as it doesn't really pertain to our iOS SDK. I'd suggest emailing support@stripe.com and they'll be able to help you with the particulars of your integration.
