### ISSUE TITLE
Address forms to split full name into two fields

### ISSUE THREAD

**Issue by felixkli** [stripe/stripe-ios#1520]
Hi, could you consider (or add an option to) splitting the full name fields on the shipping forms into two separate fields for first name and last (family) name? In Asia, it is very common that the family name comes first and it is difficult to parse the full name properly without the proper differentiation. If we convert the address object into PKContact item, it will always parse the first word as the first name and everything else as the family name.

Thanks

**Comment by yuki-stripe** [comment]
Hi @felixkli,

Thanks for the report.  We're tracking this improvement internally.

**Comment by davidme-stripe** [comment]
We don't plan to support this in our UI, as it doesn't fit the shape of our API.

If you'd like to format name components into a `PKContact`, Apple's [PersonNameComponentsFormatter](https://developer.apple.com/documentation/foundation/personnamecomponentsformatter/1642979-personnamecomponents) can convert a string into a properly-formatted name in Chinese, Japanese, Korean, and most Latin languages.
