### ISSUE TITLE
Add handler before removing a card into the STPPaymentOptionsController

### ISSUE THREAD

**Issue by jose-t** [stripe/stripe-ios#1521]
## Summary

Hi,

I encounter a specific problem when I create a PaymentIntent via the Stripe API without confirming.
My users can add and remove cards from the STPPaymentOptionsController.
They can also validate an order that trigger a new PaymentIntent.
If the user removes a card attached to a PaymentIntent which is not confirmed, the PaymentIntent can never be confirmed.

The problem could be resolved if we have a handler when the user trying to remove a card in the STPPaymentOptionsController. Then we could catch and cancel the removal if the card is already attached to a PaymentIntent.

**Comment by yuki-stripe** [comment]
Hi @jose-t,

Would toggling [canDeletePaymentOptions](https://stripe.dev/stripe-ios/docs/Classes/STPPaymentConfiguration.html#/c:objc(cs)STPPaymentConfiguration(py)canDeletePaymentOptions) work for you?

To better understand the problem, I'm curious what the situation is where a user removes a card attached to an un-confirmed PaymentIntent.  I wouldn't have expected this to be a scenario.

**Comment by jose-t** [comment]
Hi @yuki-stripe,

`canDeletePaymentOptions` will not work for me because I give to the user the possibility to add or delete his credit cards whenever he wants. The STPPaymentOptionsController acts as a wallet.

The PaymentIntent is confirmed manually by a retailer and a user could delete his credit card during this time.
When a user validates an order, he is not aware that the payment is not validated. For him, he buys items with his credit card and he is not supposed to know if he accidentally deletes his card the payment will never succeed.

**Comment by yuki-stripe** [comment]
Thank you for the explanation, this is very helpful. We're tracking this internally.
