### ISSUE TITLE
NSInternalInconsistencyException:  Could not parse the ephemeral key response following protocol STPCustomerEphemeralKeyProvider

### ISSUE THREAD

**Issue by starboy84** [stripe/stripe-ios#1537]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not parse the ephemeral key response following protocol STPCustomerEphemeralKeyProvider. Make sure your backend is sending the unmodified JSON of the ephemeral key to your app. For more info, see https://stripe.com/docs/mobile/ios/standard#prepare-your-api

I have my Heroku project with backend there. but I am getting this error

**Comment by aliriaz-stripe** [comment]
Hello @starboy84 , this looks like a good question for the Support team as it is integration related (and not an SDK bug or issue). 

Please write in to https://support.stripe.com/contact with details of 

- the version of the iOS SDK you are using
- code snippets of your `createCustomerKey` implementation (shared via pastebin.com)
- code snippets of your server-side code that creates an ephemeral key (shared via pastebin.com)
- please remember to remove any API keys from your snippets

And we can help you out!
