### ISSUE TITLE
license file in 4.0.2

### ISSUE THREAD

**Issue by Suz** [stripe/stripe-ios#154]
getting an error when I switch branches:

[!] Unable to read the license file `/.../Pods/Stripe/LICENSE` for the spec `Stripe (4.0.2)`

Is LICENSE defined for this tag?

**Comment by jflinter** [comment]
Strange; none of those settings have changed in a while. What do you mean "getting an error when I switch branches?" Do you mean changing the contents of your `Podfile`, or something else?

**Comment by Suz** [comment]
I'm working on two feature branches:  feature-apple-pay and feature-vertical-art
steps:  checkout feature-vertical-art, pod update.  No problems -- project compiles and runs in simulator. 
checkout feature-apple-pay, pod update:  The update gives the license error (pasted above) and the project fails to compile. I think the compile errors vary. The latest one is /.../Pods/Stripe/Stripe/STPAPIClient.m:16:9: 'STPAPIConnection.h' file not found

**Comment by jflinter** [comment]
I'm assuming those two different branches have different `Podfile`s; mind pasting them here?

**Comment by Suz** [comment]
branch apple-pay (broken).... maybe it's the 7.0 target? but it was working yesterday before I created the other branch. 
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

xcodeproj 'Depict'

pod 'AFNetworking'
pod 'MagicalRecord'
pod 'SDWebImage'
pod 'Stripe'
pod 'Stripe/ApplePay'
pod 'ApplePayStubs'
pod 'PaymentKit'
pod 'google-cast-sdk'
pod 'AppsFlyer-SDK', '~> 2.5'
pod 'GoogleConversionTracking', '~> 3.1'
pod 'uservoice-iphone-sdk', '~> 3.2'
pod 'Intercom'

target :DepictTest do
    pod 'Specta'
    pod 'Expecta'
    pod 'Expecta+Snapshots'	    
    pod 'OCMock'
end

post_install do |installer|
    installer.project.targets.each do |target|
        puts target.name
    end
end
```

working branch: vertical-art
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

xcodeproj 'Depict'

pod 'AFNetworking'
pod 'MagicalRecord'
pod 'SDWebImage', :git => 'https://github.com/rs/SDWebImage.git', :commit => '9b8aa8a12d47e01aa'
pod 'Stripe'
pod 'PaymentKit'
pod 'google-cast-sdk'
pod 'AppsFlyer-SDK', '~> 2.5'
pod 'GoogleConversionTracking', '~> 3.1'
pod 'uservoice-iphone-sdk', '~> 3.2'
pod 'Intercom'

target :DepictTest do
    pod 'Specta'
    pod 'Expecta'
    pod 'Expecta+Snapshots'	    
    pod 'OCMock'
end

post_install do |installer|
    installer.project.targets.each do |target|
        puts target.name
    end
end
```

**Comment by jflinter** [comment]
Hmm, so I just created a brand-new project with that Podfile and it was able to compile just fine. A few suggestions:
- Is it possible you're using an old version of cocoapods itself? (Try running `gem install cocoapods` again).
- You could also try removing your `Pods` directory and your `Podfile.lock` and running `pod install` again.
- If you can create a small repository that reproduces the issue that you can share with me, I'm happy to take another look.
- If none of these things work, you can always install our SDK manually by following the directions at https://stripe.com/docs/mobile/ios#manual-installation .

Going to close this issue for now as it appears to be a problem with your specific installation, but happy to re-open if that ends up not being the case.
