### ISSUE TITLE
Setting STPPaymentOptionsViewControllerDelegate when using the payment context to create a MyViewController:STPPaymentOptionsViewController

### ISSUE THREAD

**Issue by Advozium** [stripe/stripe-ios#1544]
## Summary

I am wondering if it is possible to set the delegate of the `STPPaymentOptionsViewController` for the current view controller that is calling the `presentPaymentOptionsViewController()` function. My intent is to display the view for picking a credit card and then after the user is done, depending on whether or not they closed the view or picked an option, do something specific using the `STPPaymentOptionsViewControllerDelegate`. 

## Code to reproduce

My code right now calls the following to display the view that shows the payment options:

`self.paymentContext.presentPaymentOptionsViewController()`

Is there something like:

`self.paymentContext.presentPaymentOptionsViewController(delegate: self)`

So that in my current class, I can set it up as follows:

`class MyViewController:STPPaymentOptionsViewControllerDelegate {...}`

Then I can implement the delegate functions and then, depending on whether or not the user cancels or selects a card, do something specific.

## iOS version

iOS 13.4

## Installation method

Cocoapods

## SDK version

 `Stripe (19.0.1)`

**Comment by aliriaz-stripe** [comment]
Hello @Advozium !

This is currently not supported when using STPPaymentOptionsViewController via STPPaymentContext. The delegate methods for STPPaymentOptionsViewController are managed internally by STPPaymentContext and would not be exposed to your view controller that is presenting this

You can use the STPPaymentOptionsViewController itself and then you'll can implement its delegate methods.

**Comment by belov1** [comment]
Hello @Advozium !

How can I set STPPaymentOptionsViewControllerDelegate, when showing STPPaymentOptionsViewController this way:
```
let customerContext = STPCustomerContext(keyProvider: PaymentService())
let paymentContext = STPPaymentContext(customerContext: customerContext)
paymentContext.delegate = self

let controller = STPPaymentOptionsViewController(paymentContext: paymentContext)
let navVC = UINavigationController(rootViewController: controller)
viewController.present(navVC, animated: true, completion: nil)
```
I need to catch events `paymentOptionsViewControllerDidCancel` and `paymentOptionsViewController:didSelectPaymentOption:`.

If it's impossible to set delegate, how can I catch events on selecting card or tapping cancel button when initializing STPPaymentOptionsViewController with STPPaymentContext?

**Comment by mdeora** [comment]
Any update on this?

**Comment by aliriaz-stripe** [comment]
@belov1 Hello again!

STPPaymentOptionsViewController's `delegate` isn't settable, so the recommended way to implement it is to use the `initWithConfiguration(...)` initializers, which take the delegate as an argument to set internally.

If you are using STPPaymentContext, then it handles the delegate methods of STPPaymentOptionsViewController directly and doesn't expose them to your applications viewControllers.
