### ISSUE TITLE
Closing stripe checkoutController

### ISSUE THREAD

**Issue by hsavit1** [stripe/stripe-ios#155]
Hello, 

I can't close the checkoutController view controller, no matter what I do

When I press the button, the checkoutView area changes to "You're all done here. Close this tab to return to appname"

Is there any way to fix this??

Also can I change the image of that button somehow??? (sorry if im pushing it)

**Comment by hsavit1** [comment]
Ok. So if you put dismissViewController:Animated:Completion in the delegate method it will get called

**Comment by jflinter** [comment]
Glad you figured this out on your own. We designed this API this way to behave similarly to `PKPaymentAuthorizationViewController`, which you also are in charge of dismissing (doing it this way lets you do things like display another `UIViewController` in the `completion` block of your dismissal).
