### ISSUE TITLE
Error when using Swift Package Manage to add stripe-ios 19.1.0

### ISSUE THREAD

**Issue by sk92129** [stripe/stripe-ios#1554]
## Summary
Cannot add stripe-ios as dependency using Swift Package Manager GUI.

## Code to reproduce

Your web site says to use this url :
https://github.com/stripe/stripe-ios/releases/tag/v19.1.0
for the swift package manager but that does not work --"An unknown error occurred."

Instead I changed or shortened the url to just: 
https://github.com/stripe/stripe-ios

Then I see a prompt from Swift Package Manager to select a certain version,
Rules: Version up to next major 19.1.0, or branch or commit.
I picked the default of "Version up to next major 19.1.0"

When I use XCode 11.4.1 and try to add the Stripe-ios 19.1.0 as a dependency, I see this error.

Package resolution failed:
"stripe-ios" could not be resolved
https://github.com/stripe/stripe-ios/has no Package.swift manifest for version 19.1.0

## iOS version
13.3.1

MacOSX version 10.15.4
XCode 11.4.1

## Installation method
Attempting thru XCode swift package manager.

## SDK version
19.1.0

**Comment by davidme-stripe** [comment]
Sorry, but we don't support Swift Package Manager at the moment! We're hoping to add support once Swift 5.3 lands: https://github.com/stripe/stripe-ios/issues/1255

**Comment by yadallash** [comment]
Hi, I am interested in implementing stripe using SPM, any updates on providing support for it?

**Comment by ilazakis** [comment]
I recently integrated via SPM successfully  @yadallash

**Comment by BFMarks** [comment]
@davidme-stripe comment seems to be outdated based on the fact that stripe has a SPM: https://swiftpackageregistry.com/stripe/stripe-ios

**Comment by zzdravkin** [comment]
I think from 22.8.4 you can use SPM

**Comment by davidme-stripe** [comment]
Yes, this was resolved in #1255.
