### ISSUE TITLE
MIGRATING.md References Broken/Depreciated Documentation Link 

### ISSUE THREAD

**Issue by AustinFuller** [stripe/stripe-ios#1557]
## Summary
While using the migration documentation, a link with a heading shortcut (not sure on name, but when the link is in markdown and has `#` with some section) that is no long in the documentation. 

## Code to reproduce
Within: https://github.com/stripe/stripe-ios/blob/master/MIGRATING.md#migrating-from-versions--1600 

The link: https://stripe.com/docs/payments/payment-methods#transitioning 

The link does not resolve to a transitioning section as that section seems to have been removed from the docs

## Other information
Sorry to be over pedantic! Started migrating today and noticed the migrating doc was outdated here. Hoping to successfully make the jump from v14 to v19... 

Thanks guys!

**Comment by davidme-stripe** [comment]
Thanks for letting us know, I'll update the link! The new guide is here: https://stripe.com/docs/payments/payment-intents/migration
