### ISSUE TITLE
Number of lines in the description label of STPCheckoutViewController

### ISSUE THREAD

**Issue by hsavit1** [stripe/stripe-ios#156]
how can I change the word wrapping and the numberOfLines?

**Comment by hsavit1** [comment]
This is in reference to the NSString "purchaseDescription" in STPCheckoutOptions

**Comment by hsavit1** [comment]
there is no reference to the label, only the string

**Comment by jflinter** [comment]
Yeah, I'm afraid we don't currently expose that API (this isn't actually even backed by a `UILabel`, it's loaded in a webview).
