### ISSUE TITLE
'Postal' should be 'Postcode' for UK localization

### ISSUE THREAD

**Issue by kohlab** [stripe/stripe-ios#1568]
## Summary

Localization tweak required for UK English. "Postal" should be "Postcode". 

## Code to reproduce

1. Settings -> General -> Language & Region - change to United Kingdom / English (UK)
2. When entering a new card it asks for POSTAL. POSTCODE is correct. See image.
![IMG_2254](https://user-images.githubusercontent.com/2905860/81102262-9e634580-8ecc-11ea-983d-c6dee1844af5.PNG)

## iOS version

13.4.1

## Installation method

Carthage

## SDK version

v19.1.1

**Comment by yuki-stripe** [comment]
Hi @kohlab 

Thanks for the suggestion! We're working on getting this updated.

**Comment by yuki-stripe** [comment]
This is fixed in the latest release!
