### ISSUE TITLE
Carthage binary support --> Semantic Version strategy 

### ISSUE THREAD

**Issue by dcilia** [stripe/stripe-ios#1571]
## Summary

If an individual chooses to use Carthage to add the sdk as a dependency using a prebuilt binary in the releases page, the current versioning system is incompatible with Carthage spec.

ie: v19.2.0 is incompatible.
https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-project-specification

Suggestion to adopt Semantic Versioning Model for additionally flexibility and consistency.

## Installation method
Carthage

## SDK version
Any

**Comment by yuki-stripe** [comment]
Hi @dcilia,

Thanks for writing in! I'm not very familiar with this feature of Carthage - why not specify our github repo instead (https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#github-repositories)?

**Comment by davidme-stripe** [comment]
Fixing this in #1646

**Comment by davidme-stripe** [comment]
This is fixed in SDK 20.0.0.
