### ISSUE TITLE
Retrieve non-card payment methods attached to user

### ISSUE THREAD

**Issue by mikeDaoud** [stripe/stripe-ios#1573]
## Summary
I am trying to get a list of all the SEPA accounts attached to the user (for editing/selection by user) through the SDK, but seem to always only get cards.

## Code to reproduce

- Create and attach SEPA account to user.
- create an instance of `STPCustomerContext` and call `listPaymentMethodsForCustomerWithCompletion:` on it and observe the returned payment methods list.

## iOS version

all versions

## Installation method

Following the official integration guide.

## SDK version

v19.1.1

## Other information

I believe the issue is because in [this line here](https://github.com/stripe/stripe-ios/blob/1d6e621f445ecefb863772c5f547d19b5a70904b/Stripe/STPAPIClient.m#L655) the SDK always sets the param value `type` to `[STPPaymentMethod stringFromType:STPPaymentMethodTypeCard]` which results in retrieving only card payment methods .. when I tested calling the API setting `type` to `sepa_debit` It did return the list of the sepa accounts I attached to the user, so attaching the payment method is not the issue.

**Comment by yuki-stripe** [comment]
Hi @mikeAttia,

Thanks for writing in. Unfortunately, this is expected behavior; `STPCustomerContext` only supports retrieving cards. 

I'm going to leave this open to track the feature request.

**Comment by Elshad** [comment]
@yuki-stripe but then how do we can use Apple Pay for subscribing?

**Comment by davidme-stripe** [comment]
We don't plan to add SEPA support to STPCustomerContext, but we do have SEPA support in our new [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios) product.
