### ISSUE TITLE
Actually when landing on stripe payment ViewController card is already selected. But i want card should be unselected. Please suggest what should be done.

### ISSUE THREAD

**Issue by AyushKumar8286** [stripe/stripe-ios#1579]

**Comment by aliriaz-stripe** [comment]
Hello @AyushKumar8286 , could you write in with more details (like what ideal state you want to see here on the STPPaymentOptionsViewController) to the Support team at https://support.stripe.com/contact? 
Once you write in, we can have a look there and guide you!

Closing this issue as Github Issues for this repo should be used for bug reports or feature requests.
