### ISSUE TITLE
("The operation couldn’t be completed. (Cocoa error 3840.)")

### ISSUE THREAD

**Issue by allen8300** [stripe/stripe-ios#158]
Hey man, I was trying your latest Simple Example,  I followed and checked all the steps as you mentioned. 
While I failed with error: "oh no, an error: Optional("The operation couldn’t be completed. (Cocoa error 3840.)")". 

Can you help out?

Note: all the example apps require Xcode 6.1 to build and run.

Before you can run the app, you need to provide it with your Stripe publishable key.

If you haven't already, sign up for a Stripe account (it takes seconds). Then go to https://dashboard.stripe.com/account/apikeys.
Replace the stripePublishableKey constant in ViewController.swift (for the Simple app) or Constants.m (for the Custom app) with your Test Publishable Key.
Head to https://github.com/stripe/example-ios-backend and click "Deploy to Heroku" (you may have to sign up for a Heroku account as part of this process). Provide your Stripe test secret key for the STRIPE_TEST_SECRET_KEY field under 'Env'. Click "Deploy for Free".
Replace the backendChargeURLString variable in the example iOS app with the app URL Heroku provides you with (e.g. "https://my-example-app.herokuapp.com")
After this is done, you can make test payments through the app (use credit card number 4242 4242 4242 4242, along with any cvc and any future expiration date) and then view them in your Stripe Dashboard!

**Comment by jflinter** [comment]
It's pretty hard to know what's going wrong for you with the information you're providing here. Does your device have an internet connection? You could also put a breakpoint in `ViewController.swift`, line 72, and see what the stack trace is like.

**Comment by allen8300** [comment]
Er, every step is checked. The  error happens when uploading token to server. 
My server is base on HTTP, not HTTPS. Is this the reason? 
And My server code is grabbing from http://www.larryullman.com/2013/01/09/writing-the-php-code-to-process-payments-with-stripe/  .

**Comment by jflinter** [comment]
It sounds like your server isn't returning valid JSON. I'd suggest taking a look at http://stackoverflow.com/questions/14171111/cocoa-error-3840-using-json-ios, as that seems like the same issue you're having. If you're new to AFNetworking, here's a blog post that might explain things better: http://www.raywenderlich.com/59255/afnetworking-2-0-tutorial

As your problem isn't really related to our iOS SDK, I'm going to close this issue.
