### ISSUE TITLE
Strip pod does not compile on Xcode 11.5

### ISSUE THREAD

**Issue by kumareshsaran** [stripe/stripe-ios#1584]
## Summary
After just recently updating to the new Xcode 11.4 I am unable to build my project withe Stripe SDK pod. Compiler error given is:

`Incompatible block pointer types sending '__strong STPAPIResponseBlock _Nonnull' (aka 'void (^__strong)(__strong ResponseType, NSHTTPURLResponse *__strong, NSError *__strong)') to parameter of type 'void (^)(STPSource *__strong, NSHTTPURLResponse *__strong, NSError *__strong)'`

Above Error shows in the mentioned file
**File Name:** STPAPIClient.m
-->

## Code to reproduce
I just added the **Stripe** in my pod file then I run the pod install comment. after that, I try to build my project. But it doesn't compile

## iOS version
OS: 10.15.4
Xcode: 11.5

## Installation method
Using Cocoapod

## SDK version

Stripe - 15.0.1

## Other information
I have tried all method what I know. like reinstalling the pod. but it doesn't work.

**Comment by yuki-stripe** [comment]
Hi @kumareshsaran,

You'll want to update to v15.0.2.

**Comment by kumareshsaran** [comment]
It's Wroking
