### ISSUE TITLE
Billing Address Zip code keyboard type

### ISSUE THREAD

**Issue by dskibin** [stripe/stripe-ios#1586]
Hello
Is it possible to manage keyboardType for billing address zip code input? 
paymentCountry="US" does not work. We need to have phonePad keyboard type for the input.

**Comment by csabol-stripe** [comment]
Hi @dskibin, we currently don't offer a way to change the keyboard type for postal code entry. We actually recently changed the keyboard type to be numbers and punctuation to support non-US addresses (see https://github.com/stripe/stripe-ios/pull/1479)

**Comment by dskibin** [comment]
Hi @csabol-stripe 
Billing zip code is required property in our use case. You can see this at the picture
![File](https://user-images.githubusercontent.com/2069948/84362762-6b505800-abd6-11ea-84ac-8e443b8b196b.jpg)

It would be very helpful for us to be able to specify keyboard type (or at least have same logic for billing zip code like you have for shipping zip code). Thank you!

**Comment by csabol-stripe** [comment]
ah, this field should be configured the same as for the shipping postal code. I'll take a look

**Comment by csabol-stripe** [comment]
@dskibin to clarify, this is the keyboard that is displayed by default? (i.e. didn't switch to text after initial presentation) This should be displaying the numbers and punction keyboard by default

**Comment by dskibin** [comment]
> @dskibin to clarify, this is the keyboard that is displayed by default? (i.e. didn't switch to text after initial presentation) This should be displaying the numbers and punctuation keyboard by default

Yes by default. Sorry for late answer.
Btw here is another related question -- did you change layout for Postal Code input in latest version? 
Seems now it is located at same line as card details.

**Comment by davidme-stripe** [comment]
I believe we've fixed this in the latest version, and the `numbersAndPunctuation` keyboard is default worldwide. We don't use the `phonePad` type, as it's possible for a user in the US to have a billing address outside the US with an alphanumeric postal code. Let us know if you're still experiencing this issue with the latest SDK.
