### ISSUE TITLE
Failed to verify bitcode in Stripe.framework/Stripe: error: Platform None is not supported while distributing build

### ISSUE THREAD

**Issue by sajib-ghoshInnofied** [stripe/stripe-ios#1587]
## Summary

When I tried to distribute the app with AdHoc after archive, I got this error:

**Failed to verify bitcode in Stripe.framework/Stripe: error: Platform None is not supported**

I am using Xcode 10.1.

Please find the attachment below:

![Screen Shot 2020-05-31 at 2 05 28 PM](https://user-images.githubusercontent.com/15829311/83348755-e9963a00-a34c-11ea-8bdb-e0310ab2ccbe.png)

## Installation method
Pod

## SDK version

Stripe (19.2.0)

Could you please tell me why this error is showing?

Thanks in advance!

**Comment by csabol-stripe** [comment]
Hi @sajib-ghoshInnofied , my understanding is that this is usually an issue with including simulator slices in an archive, but that should not be happening if you've integrated the Stripe framework via cocoapods. Would you be able to share your Pod file and any other reproduction steps you have for this? I just tried archiving a simple project with the Stripe framework added via cocoapods in Xcode 10.1 and didn't hit this issue

**Comment by davidme-stripe** [comment]
I'm closing this out, but let us know if you're still experiencing this issue.
