### ISSUE TITLE
use_frameworks! requirement

### ISSUE THREAD

**Issue by Minasokoni** [stripe/stripe-ios#1590]
Is it possible to use the swift library without `use_frameworks!`? I'm on cocoapods 1.7.5 and Xcode v 11.4.1

**Comment by yuki-stripe** [comment]
Hi @Minasokoni,

I believe it's possible to use our SDK without `use_frameworks!`. You may also need to replace that line with `use_modular_headers!` if your app is in Swift. See [this page](http://blog.cocoapods.org/CocoaPods-1.5.0/).

**Comment by Minasokoni** [comment]
@yuki-stripe thanks!
