### ISSUE TITLE
STPCustomer sources array isn't filled with sources - empty array

### ISSUE THREAD

**Issue by milanrancic** [stripe/stripe-ios#1591]
## iOS version
All

## Installation method
Cocoapods

## SDK version
19.2.0

## Other information
We fetch customer using STPCustomerContext class. After the customer object is initialized and passed in completion handler, we see that "allResponseFields" dictionary contains bank accounts as well as correct default bank account. Problem is fact that "sources" variable is empty, so we have to manually parse allResponseFields. Problem on Android is even more problematic since there is no even allResponseFields.

**Comment by yuki-stripe** [comment]
Hi @milanrancic,

What is the key in `allResponseFields` that contains the Sources information?  You may also find the [listPaymentMethodsForCustomerWithCompletion:](https://stripe.dev/stripe-ios/docs/Protocols/STPBackendAPIAdapter.html#/c:objc(pl)STPBackendAPIAdapter(im)listPaymentMethodsForCustomerWithCompletion:) method useful.

Can you file a separate issue in the Android repo regarding `allResponseFields`? This is a good feature request!

**Comment by milanrancic** [comment]
Hi @yuki-stripe,

listPaymentMethodsForCustomerWithCompletion: doesn't return bank accounts. Bank accounts are not supported by Payment Methods API. That is expected behavior as described in the table in https://stripe.com/docs/payments/bank-debits-transfers. 
So, as advised on the doc page, we used Sources API to fetch bank account as a source of Customer object.
We fetch STPCustomer and check its "sources" param which is array but empty. STPCustomer has also allResponseFields: [AnyHashable : Any] dictionary which is JSON response representation used to create the object. When content of allResponseFields variable is inspected we see that it actually does contain "sources" JSON array which contains Bank account objects (see the debugger screenshot below).
![image](https://user-images.githubusercontent.com/35456589/85120279-4e91d100-b223-11ea-9028-5372a3c78caf.png)
![image](https://user-images.githubusercontent.com/35456589/85120509-9d3f6b00-b223-11ea-9b74-433527210de0.png)

Thank you for your response, we are feeling excited to have this SDK feature improved and looking forward to having the bank accounts right in the sources list so we can use it in ios apps.

**Comment by yuki-stripe** [comment]
@milanrancic - thank you for this context, super helpful!  I understand the issue now -STPCustomer` doesn't know about [Bank Account objects](https://stripe.com/docs/api/customer_bank_accounts).  

We're tracking adding support for this internally. In the mean time, unfortunately you will need to continue to manually parse `allResponseFields`.

**Comment by davidme-stripe** [comment]
Wanted to give an update here: We don't plan to add support for new Sources to STPCustomer, but we'll continue to support access to them via the `allResponseFields` accessor. We'd recommend using our new [PaymentIntent-based Bank Account APIs](https://stripe.com/docs/payments/ach-debit/migrations).
