### ISSUE TITLE
Return to Merchant button not working 

### ISSUE THREAD

**Issue by Sidn96** [stripe/stripe-ios#1597]
# Return to Merchant button does not get back to the App to complete Payment

## Summary
With the follow of Stripe documentation and Sample code given, I have implemented stripe 3DS security flow, registered URL Scheme and set return URL Scheme to stripe, but problem is, it doesn't get back to the app from webView after clicking on "Return to Merchant" button to complete payment.

I have tested my URL Scheme with different Apps to open My App from there.  It works fine.

```paymentIntentParams.returnURL = "payments-example://stripe-redirect" ```
What should I give instead of stripe-redirect? is it Viewcontroller class name or what?

(For extra information, after clicking on "Done" button it redirects to the app with payment failed status, and I currently working in Test mode)

Following Stripe docs: https://stripe.com/docs/payments/3d-secure#return-url

**Comment by aliriaz-stripe** [comment]
@Sidn96 hello! Github issues should be reserved for bugs or feature requests, this sounds like an integration issue and for those, the best approach is to write in to Support at https://support.stripe.com/contact or reach out to Stripe developers on #stripe channel on Freenode at https://webchat.freenode.net/

I'll be closing this here so we can continue on either channel above to solve your integration issues.

In the meantime, to unblock you quickly, have you specified a custom url scheme in your app [0] ?

If so, you need to specify your app's url scheme in the returnURL

`paymentIntentParams.returnURL = "your-url-scheme://stripe-redirect"`

If that doesn't work for you, please let me know what custom url scheme you have set and reach out to us on the 2 channels above and we'd love to unblock you!

[0] https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app

**Comment by eyoeldefare** [comment]
The point is, even if you don't specify your own url, by default, Stripe would redirect you back to the app after validation, which fails now.

**Comment by eyoeldefare** [comment]
> @Sidn96 hello! Github issues should be reserved for bugs or feature requests, this sounds like an integration issue and for those, the best approach is to write in to Support at https://support.stripe.com/contact or reach out to Stripe developers on #stripe channel on Freenode at https://webchat.freenode.net/
> 
> I'll be closing this here so we can continue on either channel above to solve your integration issues.
> 
> In the meantime, to unblock you quickly, have you specified a custom url scheme in your app [0] ?
> 
> If so, you need to specify your app's url scheme in the returnURL
> 
> `paymentIntentParams.returnURL = "your-url-scheme://stripe-redirect"`
> 
> If that doesn't work for you, please let me know what custom url scheme you have set and reach out to us on the 2 channels above and we'd love to unblock you!
> 
> [0] https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app

I am also experiencing this issue starting yesterday. I don't think its an issue with his integration at all. My guess is, the new IOS update did something to break something. I don't understand how you would close this so fast without any evidence this is not a software issue. Have you verified anything?

**Comment by Krow-Works** [comment]
can anyone tell me what this url scheme means , would have a tutorial on how to confirm , what it is , i'm lost
