### ISSUE TITLE
[STPRedirectContext - Click DONE/OK(iOS13) issue]

### ISSUE THREAD

**Issue by tuanndwork** [stripe/stripe-ios#1598]
## Summary

[iOS - STPRedirectContext] When I'm not authorize payment and press done will still return source status pending

## Code to reproduce

I'm using STPRedirectContext and startSafariViewControllerRedirectFlowFromViewController, I have issue:
 - I'm not authorize payment and press "Done/Ok(iOS13)" in header but stripe return source status is pending meanwhile should be canceled.
- What case will return canceled.

## iOS version

All version iOS

## Installation method

SDK

## SDK version

17.0.0

**Comment by Donhv** [comment]
+1. i have same issue

**Comment by yuki-stripe** [comment]
Hi @tuanndwork,

I believe this is expected behavior, and the Source transitions to the Canceled state only when it is first in the Chargeable state and then expires ([source](https://github.com/stripe/stripe-ios/blob/66935da611a1d1d714d2a7185739b8d578742d9e/Stripe/PublicHeaders/STPSourceEnums.h#L81-L85)).

**Comment by tuanndwork** [comment]
Hi @yuki-stripe,
But in this case, standing on the user side if not authorize card is desired, just cancel and back to select another payment method.
As it is currently returned as pending and under best practices, when pending we will poll 10 times in 10 seconds, and still display as in processing, despite the fact that there is no charge for that source.
So when this screen will be without the cancel order always, right?

**Comment by yuki-stripe** [comment]
@tuanndwork 

Ah, I appreciate the problem...what payment method is this for?  cc @aliriaz-stripe for Sources integration help.

I'd recommend migrating to [PaymentIntents](https://stripe.com/docs/payments/payment-intents), if possible.

**Comment by aliriaz-stripe** [comment]
Hey @tuanndwork !

Could you say more about what payment method you are integrating? Do you have a Token/Source/PaymentMethod ID I can have a look at? 

It would help to see a snippet of your code on how you're initializing STPRedirectContext.

**Comment by tuanndwork** [comment]
Hi @aliriaz-stripe,
Apply for all payment method (iDEAL, SOFORT, Bancontact, ...)
When startSafariViewControllerRedirectFlowFromViewController and view sreen as below

![PNG image](https://user-images.githubusercontent.com/67319472/86868805-9bb8e280-c0ff-11ea-9c1e-4a2921b35db5.png)
 
Users just want to cancel and back to the previous screen and choose another method, but can't because don't have any function cancel.
cc @yuki-stripe

**Comment by davidme-stripe** [comment]
This is unfortunately a limitation of the polling method we use for Sources — we'll need to poll repeatedly to check if the payment succeeded in the SFSafariViewController. We'd recommend migrating to PaymentIntents for better iDEAL support.
