### ISSUE TITLE
Handle next action presenting as .pageSheet then fails

### ISSUE THREAD

**Issue by yreaction** [stripe/stripe-ios#1602]
## Summary
We have seen a large increase in unsuccessful attempts to verify some VISA credit cards since June 30.
STPPaymentHandler.shared (). HandleNextAction partially displays and closes almost instantly.

## Code to reproduce
// PaymentViewModel
```
internal func handleNextActionWith(clientSecret: String) {
		guard let viewController = self.viewController, let card = self.card else { return }
		
		STPPaymentHandler.shared().handleNextAction(forPayment: clientSecret, authenticationContext: viewController, returnURL: nil) { [weak self] (status, responseIntent, error) in
			guard let welf = self else { return }
			switch (status) {
			case .succeeded:
				welf.performTransaction(with: card)
			case .canceled:
				welf.onSuccessHandler?(false, error?.localizedDescription ?? "Bid canceled")
			case .failed:
				welf.onSuccessHandler?(false, error?.localizedDescription ?? "Bid Failed")
				
			}
		}
	}
```

//ViewController
```
extension BidViewController: STPAuthenticationContext {
    func authenticationPresentingViewController() -> UIViewController {
        return self
    }
	
	func configureSafariViewController(_ viewController: SFSafariViewController) {
		viewController.modalPresentationStyle = .overFullScreen

	}
	
	func prepare(forPresentation completion: @escaping STPVoidBlock) {
		  completion()
	  }
}
```

## iOS version
13.4.1

## Installation method
Cocoa Pods

## SDK version
 19.0.1

## Other information
As you can see below, it does present as .pageSheet instead of .overFullScreen (		`viewController.modalPresentationStyle = .overFullScreen)`
![handleStepFailed](https://user-images.githubusercontent.com/518910/86899400-3e765e80-c10a-11ea-8b7f-992a4a620575.gif)

**Comment by csabol-stripe** [comment]
Hi @yreaction, the immediate dismissal is due to an error in the issuers Access Control Server (ACS), which is needed to run 3DS2.

The code here:
	```
func configureSafariViewController(_ viewController: SFSafariViewController) {
		viewController.modalPresentationStyle = .overFullScreen

	}
```
only applies when we display an SFSafariViewController instance. For native 3DS2, which this is, that is not the case and we don't currently offer a way to customize the modal presentation style. I will file a ticket internally to track that as a feature request :)

**Comment by yreaction** [comment]
Hey @csabol-stripe. 
Do you have any update regarding this? We're having a huge bad impact in our product since users can not 3DS2 properly

**Comment by davidme-stripe** [comment]
I'm closing this out, as I believe the issuer has solved this. Let us know if you're still experiencing this issue.
