### ISSUE TITLE
Use Shipping Methods View Controller

### ISSUE THREAD

**Issue by dfairaizl** [stripe/stripe-ios#1603]
## Summary
Hello! Wondering if it is possible to use only the view controller responsible for showing shipping methods/rates? I see this VC exists but its not exposed far as I can tell - or perhaps there is a different way of doing this? I have UI to allow for address selection already.

## Code to reproduce

```swift
let shippingRatesVC = STPShippingMethodsViewController()
```
![image](https://user-images.githubusercontent.com/663205/86954874-b5b8ec00-c124-11ea-908f-f1def8e23db9.png)

## iOS version
iOS 13 Xcode 11.5

## Installation method
cocoapods

## SDK version
v19.3.0

## Other information
Thank you!

**Comment by csabol-stripe** [comment]
Hi @dfairaizl , we don't currently expose `STPShippingMethodsViewController` in the public SDK so you would have to initialize an `STPShippingAddressViewController` instance with the `prefilledInformation.shippingAddress` property filled. But this would initially display the completed shipping address view and the user would have to press Next to advance to shipping method selection. I will file a ticket to internally track exposing `STPShippingMethodsViewController` or similar :)

**Comment by dfairaizl** [comment]
Hi @csabol-stripe thanks for getting back to me! I ended up building some custom UI around the experience but thanks for considering this - I'm sure it will be useful in the future (and less work!).
