### ISSUE TITLE
STPPaymentCardTextField resignFirstResponder not work

### ISSUE THREAD

**Issue by saudongctv** [stripe/stripe-ios#1604]
## Summary
When I input card number but not finish yet. Now if call resignFirstResponder, the keyboard flash but not hidden.
It'll be hidden in case we input all info. But can't hidden in case the data not full filled yet

**Comment by csabol-stripe** [comment]
Hi @saudongctv , is this an issue with manually calling `resignFirstResponder` on the `STPPaymentCardTextField` instance? I just tried running the following code and didn't run into any issues with the keyboard dismisal:
`    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        cardField.becomeFirstResponder()
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + .seconds(3)) {
            self.cardField.resignFirstResponder()
        }
    }`

**Comment by saudongctv** [comment]
Hi @csabol-stripe 

_is this an issue with manually calling resignFirstResponder on the STPPaymentCardTextField instance?_
Yes, it is.

Please check the attached video to see how's it work.

Here's my code to setup the STPPaymentCardTextField.
    @IBOutlet weak var paymentCardTextField: STPPaymentCardTextField!

Add toolbar inputAccessoryView

        let numberToolbar = UIToolbar(frame:CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: 50))
        numberToolbar.barStyle = .default
        numberToolbar.tintColor = UIColor.black
        numberToolbar.items = [
        UIBarButtonItem(title: "Cancel".localized(), style: .plain, target: self, action: #selector(cancelNumberPad)),
        UIBarButtonItem(barButtonSystemItem: .flexibleSpace, target: nil, action: nil),
        UIBarButtonItem(title: "Done".localized(), style: .plain, target: self, action: #selector(doneWithNumberPad))]
        numberToolbar.sizeToFit()
        paymentCardTextField.inputAccessoryView = numberToolbar

And when click done:
    @objc func doneWithNumberPad() {
        //Done with number pad
            self.paymentCardTextField.resignFirstResponder()
       }


resignFirstResponder only work in case all data filed.
Thanks.

[stripe_issue.mov.zip](https://github.com/stripe/stripe-ios/files/4941329/stripe_issue.mov.zip)

**Comment by daniellau415** [comment]
Hi @csabol-stripe 

My stripe version is 14.0.1 and I'm also experiencing the same issue with similar implementation using the toolBar. For me, the issue only happens the first time clicking the done button regardless whether or not the validation state is valid or invalid. It triggers when the manually setting up the params for `STPPaymentCardTextField`. like this
```
 stripeTextField.cardParams = myCardParams
```
I did some digging around the pod and found that for valid state
line 1328 `[[self nextFirstResponderField] becomeFirstResponder];` is called and maybe this is triggering the keyboard to reappear even after calling resignFirstResponder, endEditing, etc... on my views

However, this does not explain and I'm not entirely sure why keyboard doesn't hide the first time when we we try to resignFirstResponder on invalid state.

**Comment by davidme-stripe** [comment]
We've done a lot of work on keyboard dismissal issues in recent updates: Could you try this on SDK version 21.5.0 and reopen the issue if you're still experiencing it?
