### ISSUE TITLE
STPPaymentOptionsViewController need hide "Cancel" button.

### ISSUE THREAD

**Issue by pingusNikalex** [stripe/stripe-ios#1605]
In my project I presented STPPaymentOptionsViewController in one Tab of UITabBar, STPPaymentOptionsViewController always visible after selected specific tabbar and can't be dismissed. 
Question: how I can hide cancel button. Or change color of only cancel button.

**Comment by csabol-stripe** [comment]
Hi @pingusNikalex, would you be able to provide some sample code for how you're presenting the `STPPaymentOptionsViewController` from the tab bar or a screenshot containing the Cancel button that needs to be hidden? Thanks!

**Comment by Elshad** [comment]
@pingusNikalex it seems `STPPaymentOptionsViewController` add `cancel` button to its `navigationItem` on `viewDidLoad`. I think on `viewWillAppear` it is possible to hide navigation buttons

**Comment by davidme-stripe** [comment]
I'm closing this out, but let us know if you're still having trouble hiding the Cancel button. I'd also recommend trying our new [Payments UI beta](https://stripe.com/docs/mobile/payments-ui-beta) in SDK version 21.5.0.
