### ISSUE TITLE
Customer id nil

### ISSUE THREAD

**Issue by mohsinalimat** [stripe/stripe-ios#1607]
Hello,

When I add new card paymentContextDidChange method call but paymentContext.selectedPaymentOption?.customerId = nil 

why?

Thanks,
Mohsinali Matiya

**Comment by aliriaz-stripe** [comment]
Hello @mohsinalimat 

Could you share more? What do you get when you log out the value for `paymentContext.paymentMethod`?

**Comment by mohsinalimat** [comment]
po paymentContext.selectedPaymentOption


▿ Optional<STPPaymentOption>
  - some : <STPPaymentMethod: 0x600000282180; stripeId = pm_xxxxxxxxxxxxxxxxxxx; auBECSDebit = (null); bacsDebit = (null); billingDetails = <STPPaymentMethodBillingDetails: 0x60000368dcc0; name = (null); phone = (null); email = (null); address = <STPPaymentMethodAddress: 0x600000fe5ea0; line1 = (null); line2 = (null); city = (null); state = (null); postalCode = (null); country = US>>; card = <STPPaymentMethodCard: 0x60000086ab80; brand = Visa; checks = <STPPaymentMethodCardChecks: 0x6000023db900; addressLine1Check: (null); addressPostalCodeCheck: (null); cvcCheck: (null)>; country = US; expMonth = 1; expYear = 2025; funding = debit; last4 = 5556; fingerprint = (null); threeDSecureUsage = <STPPaymentMethodThreeDSecureUsage: 0x600002d48c40; supported: YES>; wallet = (null)>; cardPresent = (null); created = 2020-07-18 04:16:31 +0000; **customerId = (null);** ideal = (null); fpx = (null); sepaDebit = (null); liveMode = NO; metadata = {
}; type = card>

**Comment by aliriaz-stripe** [comment]
@mohsinalimat thanks for the additional info!

So `customerId` is a property on the STPPaymentMethod class, not on STPPaymentOption protocol

What you can do here is, cast the `selectedPaymentOption` to an STPPaymentMethod, then log out the `customerId`, something like 

```
        if let paymentMethod = paymentContext.selectedPaymentOption as? STPPaymentMethod {
            print(card)
            print(card.customerId)
        }
```

Let me know if that works for you!
