### ISSUE TITLE
Documentation and guidance for the upcoming required App Store questionnaire on what data this SDK collects

### ISSUE THREAD

**Issue by AustinConlon** [stripe/stripe-ios#1611]
From [Build trust through better privacy - WWDC 2020](https://developer.apple.com/videos/play/wwdc2020/10676/?time=906):

> Starting in fall 2020 when you submit your app to the App Store, you will need to fill out a questionnaire to describe how your app uses user data. The information you provide will be shown to users directly on your store page. This gives users the ability to see what an app does before they download it. They will be able to see if you collect a little data, or a lot of data, and if any of that data is used to track them. You should make sure to still provide further details to your users to explain your data usage, such as in your privacy policy or on your website. This information will be readily available on your App Store product page. It will also be shown for apps in the app stores on all platforms. If you have installed any third party code, such as an analytics or advertising SDK, you will also need to declare what data they collect and how it is used. Remember that SDKs run in-process of your app so they have access to the same permissions that your app does.

> And as a developer, you're responsible for the trust and handling of user data in your app, including any code that you include. And SDK developers, this would be a great time to update your documentation to make sure that developers understand what your SDK does. The developer documentation and questionnaire will be available later. In the meantime, reach out to your SDKs developers to make sure you understand how they may collect and use data.

**Comment by csabol-stripe** [comment]
Hi @AustinConlon , thanks for highlighting this change! We'll be taking a look at this over the coming weeks and I will update this ticket accordingly.

**Comment by AustinConlon** [comment]
[Details for app privacy questions now available](https://developer.apple.com/news/?id=hx9s63c5)

**Comment by mpdifran** [comment]
Any updates here? The deadline is coming up soon.

**Comment by csabol-stripe** [comment]
We're just waiting on a response from our legal team :) Hoping to provide an update this week!

**Comment by mpdifran** [comment]
Is there an update on this?

**Comment by cowgp** [comment]
@csabol-stripe – December 8th was the day Apple began requiring this.  2 days ago.   Any guidance would really be helpful here as new submissions to the App Store are now blocked until the data disclosure stuff is provided.

**Comment by davidme-stripe** [comment]
Hi, sorry for the delay! [Here's our new document on data usage in the iOS SDK](https://github.com/stripe/stripe-ios/blob/ea63062ffbe9a3fda417093724f0ddbdfa079d35/PRIVACY.md), which should help you answer these questions. We'll add this to the repo as `PRIVACY.md` in the next update.

**Comment by davidme-stripe** [comment]
We've uploaded a copy here as well: https://support.stripe.com/questions/stripe-ios-sdk-privacy-details
