### ISSUE TITLE
No option to ask to choose payment method everytime user wants to make the purchase

### ISSUE THREAD

**Issue by mdeora** [stripe/stripe-ios#1612]

**Comment by mdeora** [comment]
I have tried a workaround to it by using STPPaymentOptionsViewControllerDelegate.

But it would be nice to just have a flat in config about whether to ask user everytime the payment options to use.

**Comment by aliriaz-stripe** [comment]
@mdeora  hello! Could you say more, what does your checkout flow look like, what would you like it to do? 

Just a rough explanation would help here.

Also, I assume you are using STPPaymentOptionsViewController standalone, without STPPaymentContext? 

Also, what version of the SDK are you on? The functionality of STPPaymentOptionsViewController is different (either uses Cards or PaymentMethod objects) depending which version you are on
