### ISSUE TITLE
iOS - What is the value should put for the returnURL when paying with FPX method

### ISSUE THREAD

**Issue by kyweng** [stripe/stripe-ios#1615]
Hi, 

May I know what is the value should I put for the returnURL when paying with FPX method? It was switching to webview for the payment page after selecting the bank, after that, how can I detect the payment status and close the webview? 

Thanks for replying.

**Comment by yuki-stripe** [comment]
Hi @kyweng,

Take a look at these instructions here: https://stripe.com/docs/payments/3d-secure#return-url (don't worry about the 3D secure part - setting up `returnURL` is the same).
