### ISSUE TITLE
enablePostalCode & requireBillingAddress don't affect STPCheckoutViewController

### ISSUE THREAD

**Issue by mihalychk** [stripe/stripe-ios#163]
Hello

I use the next code:

STPCheckoutOptions * options = [[STPCheckoutOptions alloc] init];
options.publishableKey = PAYMENTS.stripePublishableKey;
options.purchaseDescription = NSLocalizedString(@"Some description", @"Wallet");
options.purchaseAmount = invoice.amount.unsignedIntegerValue * 100; // this is in cents
__options.enablePostalCode = @YES;__
__options.requireBillingAddress = @YES;__
STPCheckoutViewController * controller = [[STPCheckoutViewController alloc] initWithOptions:options];
controller.checkoutDelegate = self;

Various values in enablePostalCode & requireBillingAddress properties don't affect to STPCheckoutViewController. I need to get billing address and zip code from user.

Thanks a lot

**Comment by jflinter** [comment]
Hey, thanks for writing in!
This feature is still in beta, so it's currently disabled. We'll enable it remotely in the next 2 weeks or so; I'll close this issue when we do.
