### ISSUE TITLE
SDK Resources Size

### ISSUE THREAD

**Issue by clementpadovani** [stripe/stripe-ios#1630]
## Summary
Hey, this isn’t a bug per se but a general inquiry.

I’m inspecting my application prior to shipping it and found that your resources (namely Stripe.bundle) weigh almost a hefty megabyte.

You bundle 148 images which aren’t part of your asset catalog, thus these images get bundled despite App Thinning. 

Is there a specific reason as to why these aren’t part of an asset catalog?

Moreover, my app will only ship with a single localization (and work in a single market) and I haven’t set `CFBundleAllowMixedLocalizations`, do you see any objections as to deleting unnecessary localizations?

Thanks,

## Code to reproduce
N/A

## iOS version
N/A
## Installation method
Cocoapods

## SDK version
19.4.0

**Comment by davidme-stripe** [comment]
Thanks for the feedback! We're looking into this and other ways to shrink our SDK for App Clips, and we hope to have something soon.

In the meantime, I don't see any problem with deleting the unused localizations in your own app.

**Comment by davidme-stripe** [comment]
Fixed in #1643, which is in `master`. We'll get a release out soon.

**Comment by davidme-stripe** [comment]
This is fixed in SDK 20.0.0.

**Comment by clementpadovani** [comment]
thanks @davidme-stripe!

One last question regarding the bundled localization assets. 

I’m guessing that those bundled in `Stripe3DS2.bundle` are related to 3DS authentication.

Do you enforce the localization based on the card’s region or is it device-based?

Basically, can I safely delete the superfluous regions there too?

Thanks,
