### ISSUE TITLE
Stripe pod does not compile on Xcode 11.6

### ISSUE THREAD

**Issue by fesstheavenger** [stripe/stripe-ios#1632]
## Summary
I use Stripe in my project. I updated Xcode to version 11.6 and now I am not able to build my project. Here is error:

<img width="658" alt="Screen Shot 2020-08-26 at 14 12 29" src="https://user-images.githubusercontent.com/2928871/91297037-48c9e600-e7a6-11ea-904c-a674426587a1.png">

## iOS version
iOS 13.2

## Installation method
Cocoapods

## SDK version
Stripe 19.4.0

## Other information
I used different versions of Stripe, tried to reinstall pods but I got the same result

**Comment by amuresia** [comment]
I believe I am facing a similar issue on Xcode 12 Beta 6.
```
ld: building for iOS Simulator, but linking in object file built for iOS, file '.../Pods/Stripe/InternalFrameworks/libStripe3DS2.a' for architecture arm64
```
I am using Stripe 19.4.0 as well
I am able to build my app on the simulator and mobile devices but Xcode previews don't work because of the Stripe pod.

Would you like me to track in a different issue?

**Comment by davidme-stripe** [comment]
Thanks for filing, @fesstheavenger! This sounds a lot like #1525: Are you sure Xcode is building Stripe 19.4.0? If you check STPAPIClient.h (next to the STPAPIClient.m in the error from your screenshot), do you see `static NSString *const STPSDKVersion = @"19.4.0";`?

@amuresia, you're having a different problem: Swift Playgrounds on Xcode 12 won't work with the non-XCFramework version of our library, and Cocoapods won't support binary .xcframeworks until v1.10. You may want to try our Swift Package Manager branch for now: https://github.com/stripe/stripe-ios/pull/1633

**Comment by davidme-stripe** [comment]
Closing for now, please let me know if this keeps happening on 19.4.0.

**Comment by tudor07** [comment]
@davidme-stripe I still have this issue in v19.4.1
