### ISSUE TITLE
Invalid bitcode version with Xcode 11.3.1 release build (ios SDK Version 19.4.0)

### ISSUE THREAD

**Issue by serbanstef** [stripe/stripe-ios#1634]
## Summary

Error when trying to build for release with Xcode 11.3.1: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1103.0.32.62.0_0' Reader: '1100.0.33.17_0')', using libLTO version 'LLVM version 11.0.0, (clang-1100.0.33.17)' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Code to reproduce

Release build
## iOS version

n/a
## Installation method

cocoapods
## SDK version

Version 19.4.0

**Comment by davidme-stripe** [comment]
Hi @serbanstef, thanks for filing! A bug in Xcode 11.3 caused problems in our library, so we've moved our minimum version forward. You'll need to update to Xcode 11.6 to resolve this.

**Comment by davidme-stripe** [comment]
Closing for now, please let me know if you're still experiencing this issue.

**Comment by Gagan6696** [comment]
Hello @dackerman-stripe 
I am using xcode 11.1 and getting same issue.
Please tell me 
do i need to downgrade my stripe version from 19.4.0 to some specific version?

Please revert as soon as possible

thanks

**Comment by serbanstef** [comment]
In my case I downgraded to 19.0.1. Some other newer versions might work as well.

**Comment by davidme-stripe** [comment]
Hey @Gagan6696, can I ask if something is blocking you from moving to Xcode 11.7? I didn't *think* it made any changes that could make it incompatible with an Xcode 11.1 project, but I'd like to know if we're missing something!
