### ISSUE TITLE
Collecting Postal Code for Ireland

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#1635]
## Summary
Why is the shipping address collection screen doesn't collect postal codes for Ireland? 

There are addresses in Ireland with Postal Codes. I think it would be better to add the postal code field and give the option to keep it empty. 

## SDK version
19.0.1

**Comment by davidme-stripe** [comment]
We don't support adding Eircodes in Ireland, and they're not currently required when processing payments or sending mail. We'll keep this open to track adding support for them in a future update.

**Comment by odedharth** [comment]
Any update on this?

**Comment by davidme-stripe** [comment]
We'll support collecting Eircodes during address collection in [Payment Sheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet), our new UI product. Address collection isn't available yet, but it's on our near-term roadmap.

**Comment by davidme-stripe** [comment]
I believe PaymentSheet now supports Eircode collection.
