### ISSUE TITLE
No such module 'Stripe' in Basic Integration

### ISSUE THREAD

**Issue by gilrodar** [stripe/stripe-ios#1636]
## Summary

After downloading the repository and try to run the application Basic Integration is not compiled because it says it skips the Stripe module.

## Code to reproduce

No such module 'Stripe'

## SDK version

19.4.0

**Comment by davidme-stripe** [comment]
Hey @gilrodar, that's a very strange error! Could you help provide us with a little more information?
* How are you downloading the repo?
* Which version of Xcode are you running? Does it include the iOS SDK?
* Is Xcode giving you any additional logging information?

**Comment by gilrodar** [comment]
> Hey @gilrodar, that's a very strange error! Could you help provide us with a little more information?
> 
> * How are you downloading the repo?
> * Which version of Xcode are you running? Does it include the iOS SDK?
> * Is Xcode giving you any additional logging information?

I downloaded the complete repository as a zip, then I went to the Examples folder, opened Basic Integration and when I wanted to compile I got the error. 

When I open the Frameworks folder they look a little transparent.

The version of Xcode is 11.7

<img width="1152" alt="Captura de Pantalla 2020-09-03 a la(s) 16 50 10" src="https://user-images.githubusercontent.com/13817108/92177139-8e6d5b00-ee05-11ea-8659-a331ccdbd3c7.png">

**Comment by davidme-stripe** [comment]
Ah, sorry for the confusion! You'll need to open Stripe.xcworkspace in the root directory, then build the Basic Integration app from there.

**Comment by sachithamh** [comment]
project target >Build settings >( search -> FRAMEWORK_SEARCH_PATHS) add FRAMEWORK_SEARCH_PATHS to $(inherited)
and 
check  project target > General > check  Frameworks, Libraries, and Embedded Content. under that if you use a framework it should be there if not please add it

**Comment by northwindapps** [comment]
> Ah, sorry for the confusion! You'll need to open Stripe.xcworkspace in the root directory, then build the Basic Integration app from there.

Thank you, I see now.
