### ISSUE TITLE
Detected a case where constraints ambiguously suggest a height of zero for a table view cell's content view.

### ISSUE THREAD

**Issue by gilrodar** [stripe/stripe-ios#1637]
## Summary

`[Warning] Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a table view cell's content view. We're considering the collapse unintentional and using standard height instead. Cell: <STPPaymentOptionTableViewCell: 0x10a2f5760; baseClass = UITableViewCell; frame = (0 242.5; 414 44); autoresize = W; layer = <CALayer: 0x282bc2f80>>`

## Code to reproduce

```
let configuration = STPPaymentConfiguration.shared()
configuration.requiredBillingAddressFields = .none

let theme = STPTheme.default()

let customerContext = STPCustomerContext(keyProvider: MyAPIClient())

let viewController = STPPaymentOptionsViewController(configuration: configuration, theme: theme, customerContext: customerContext, delegate: self)
let navigationController = UINavigationController(rootViewController: viewController)
present(navigationController, animated: true)
```

## iOS version

iOS 13.7

## Installation method

Cocoapods

## SDK version

19.4.0

## Other information

The warning is displayed when STPPaymentOptionsViewController is presented

**Comment by davidme-stripe** [comment]
Thanks for reporting this warning — we'll try to get it fixed.

**Comment by davidme-stripe** [comment]
Closing this out, as we haven't seen any other reports recently. We'd recommend using [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet), our modern prebuilt payment UI.
