### ISSUE TITLE
Potential memory leak in STPCheckoutViewController

### ISSUE THREAD

**Issue by jflinter** [stripe/stripe-ios#164]
To reproduce, just present and dismiss it. Hopefully this isn't an internal WebKit issue...

**Comment by sheldonparkes** [comment]
Any progress in pinning this down?

**Comment by jflinter** [comment]
Haven't had time to poke yet with WWDC stuff, sorry. Hopefully will have time in the next week or two.

**Comment by jflinter** [comment]
Closed in #188, as checkout is now deprecated.

**Comment by sheldonparkes** [comment]
What has it been replaced with if it is deprecated now?

**Comment by jflinter** [comment]
Hey @sheldonparkes - I'd suggest you take a look at `STPPaymentCardTextField`, added in v5.1.0.
