### ISSUE TITLE
STPPaymentOptionsViewController always shows Cancel button, even when it was pushed onto the stack

### ISSUE THREAD

**Issue by kschins** [stripe/stripe-ios#1647]
The same left bar button item is presented regardless of how this view is presented from the STPPaymentContext. If pushed, I would expect to see the back button with an arrow or, even better, the previous view controller's title with the left chevron. Currently the button always says "Cancel"

The functionality works as expected, UI is incorrect.

**Comment by csabol-stripe** [comment]
hi @kschins, I'll take a look at this one :) I agree that it would make sense to use the system back button in this case

**Comment by 01234abhishek** [comment]
Hi 
I am trying to integrate STPPaymentOptionsViewController. Previously when user tapping on Button I am pushing the user to STPAddCardViewController now I am trying to push user on STPPaymentOptionsViewController. I have inherit the STPPaymentOptionsViewControllerDelegate and take the delegate methods like
@objc
public func paymentOptionsViewController(
  _ paymentOptionsViewController: STPPaymentOptionsViewController,
  didSelect paymentOption: STPPaymentOption
)
But I am unable to send the token to backend in this function. Checked the https://stripe.com/docs/mobile/ios/basic but Unable to setup the ephemeral key and also proceed with some construct thing. Please some one help me regarding this.
Thanks

**Comment by kschins** [comment]
@01234abhishek do you have your own server setup to handle creating ephemeral keys for your customers?

**Comment by 01234abhishek** [comment]
Yes we have. but I don't familiar with the procedure. Can you please guide me
Thanks

**Comment by kschins** [comment]
A good guide is provided by Stripe here: https://stripe.com/docs/mobile/ios/basic

A direct link to the backend example code for generating ephemeral keys is here: https://github.com/stripe/example-mobile-backend/blob/9ac448f8b5d49175d26c7b77fd6bd3c88703e838/web.rb#L25-L40

**Comment by davidme-stripe** [comment]
Sorry, but we're not investing development effort in STPPaymentOptionsViewController at this time. We'd recommend using [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet), our modern prebuilt payment UI.
