### ISSUE TITLE
STPBankAccount.h specify Currency as readonly

### ISSUE THREAD

**Issue by RTodorov** [stripe/stripe-ios#165]
Currency property on STPBankAccount.h is marked as readonly, should be readwrite right? on STPBankAccount.m it's readwrite.

Can you confirm which one is right?

**Comment by jflinter** [comment]
No, this is a property that you can't currently directly set. It's readwrite in the .m so that internally we can initialize a bank account from a server response.

**Comment by RTodorov** [comment]
I'm trying to tokenize a Bank Account! You don't let me tokenize Bank Account without setting currency.

How am I supposed to tokenize a bank account?

**Comment by jflinter** [comment]
Right now the only currency we support for bank account tokenization is
USD, which is what the API will default to.

**Comment by RTodorov** [comment]
I'm using Stripe Connect to tokenize bank accounts in UK.

If I don't set the currency your api returns me an error. I had to remove the readonly keyword, set currency to GBP and then it worked. That's why I opened the issue.

**Comment by jflinter** [comment]
Hey @RTodorov, my apologies - I was misinformed about our bank account tokenization API, which changed recently to allow international currencies. Your original solution is correct then - `currency` should be a `readwrite` property. I've changed this on the master branch, and should be cutting a new cocoapods release in the next week or two. Thanks for bringing this up, and sorry for the confusion!

**Comment by RTodorov** [comment]
Hi @jflinter, no worries, looking forward to the next release.
