### ISSUE TITLE
20.0.0 XCFramework - Missing binary for catalyst 

### ISSUE THREAD

**Issue by fermoya** [stripe/stripe-ios#1650]
The [Stripe.xcframework.zip](https://github.com/stripe/stripe-ios/releases/download/20.0.0/Stripe.xcframework.zip) available for version [20.0.0](https://github.com/stripe/stripe-ios/releases/tag/20.0.0) is missing catalyst symbols:
<img width="205" alt="Screenshot 2020-09-15 at 12 57 38" src="https://user-images.githubusercontent.com/11335612/93207562-0d8e5780-f753-11ea-8564-a833e7be2108.png">
Now the problem isn't missing symbols but missing framework for Catalyst:
<img width="860" alt="Screenshot 2020-09-15 at 13 00 07" src="https://user-images.githubusercontent.com/11335612/93207824-707fee80-f753-11ea-8862-d2eff4a0883e.png">

I can't use SPM for now, this is something we have triaged but we have some blockers so I'm using Stripe by installing manually.

_Originally posted by @fermoya in https://github.com/stripe/stripe-ios/issues/1640#issuecomment-692668787_

**Comment by davidme-stripe** [comment]
Thank you for reporting! This was intentional, as I was worried about support across our various package managers for .xcframeworks, but after testing them I think it will work. We'll add the Catalyst slice back into the .xcframework with the next minor update, probably right after Xcode 12 GM is out.

Unfortunately, the Stripe3DS2.xcframework bundled with the repo is built with Xcode 11, so it won't solve your issue in #1640. If we distributed an Xcode 12-built library, the bitcode version used wouldn't be compatible with Xcode 11. But here's a workaround:
1. Check out the `davidme/enable-catalyst` branch.
2. Download Stripe3DS2.xcframework from the URL in Package.swift. (This one is built with Xcode 12.)
3. Drop it in ./InternalFrameworks, replacing the existing .xcframework.
4. Run `./ci_scripts/export_builds.sh`, and copy `Stripe.xcframework` from the build directory.

This should get better in ~May 2021 when Apple starts requiring Xcode 12 for App Store submissions, but we'll keep monitoring for feedback — if more people run into this issue, we might start distributing separate Xcode 11 and 12 .xcframeworks.

**Comment by fermoya** [comment]
Thanks @davidme-stripe , I’ll try that. I’m not sure how many people will run into this too, it’s unusual to install a framework manually nowadays. But I’d say that developers tend to update Xcode ASAP, so in one month you might have 90% of users on Xcode 12. It would be helpful to have both binaries in case you still want to support Xcode 11

**Comment by fermoya** [comment]
@davidme-stripe [`Package.swift`](https://github.com/stripe/stripe-ios/blob/davidme/enable-catalyst/Package.swift) in `davidme/enable-catalyst` points to [version 19.9.9 of Stripe3DS](https://github.com/stripe-ios/stripe-3ds2-ios-releases/releases/download/v19.9.9/Stripe3DS2.xcframework.zip) which doesn’t include App Silicon symbols (catalyst arm64)

**Comment by davidme-stripe** [comment]
I just downloaded it again, and it looks like it does — if you decompress it, you should see an `ios-arm64_x86_64-maccatalyst` folder.

**Comment by fermoya** [comment]
apologies @davidme-stripe , you're right. I read too fast...

I'm having a problem, though. For starters, I need to change one of the conditions inside `./ci_scripts/export_builds.sh` to let me compile with _Xcode 12_. 
```
if ! xcodebuild -version | grep -q 'Xcode 12' &> /dev/null; then
  die "Please xcode-select a copy of Xcode 12."
fi
```
When executing, it gives me this error:
```
▸ Linking Stripe

❌  ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/fernando.moyaderivas/Downloads/stripe-ios-master/InternalFrameworks/libStripe3DS2.a' for architecture arm64



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I've noticed that inside `./InternalFrameworks` there's a file called `libStripe3DS2.a`. `Stripe.xcworkspace` links `libStripe3DS2.a`, not `Stripe3DS2.xcframework`. To execute the script, you also need to change this in _Build Phases_. When doing that, it skips this error but there's a new one after...

**Comment by davidme-stripe** [comment]
Are you using the `davidme/enable-catalyst` branch? That one should link with Stripe3DS2.xcframework instead of libStripe3DS2.a, and it also has removed that error from `export_builds.sh`.

**Comment by fermoya** [comment]
Apologies again @davidme-stripe , wrong branch. Anyway, same error at the end:
```
*** Building scheme "StripeiOS" in Stripe.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/fernando.moyaderivas/Downloads/stripe-ios-davidme-enable-catalyst/Stripe.xcworkspace -scheme StripeiOS -configuration Release -sdk iphonesimulator -destination platform=iOS\ Simulator,id=918E2D6E-44AB-4AAA-BD9D-CEA39D1B575C -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/fernando.moyaderivas/Downloads/stripe-ios-davidme-enable-catalyst)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/8x/_l6zk2sx7nl1yqvbrljf7ybn4h0ft0/T/carthage-xcodebuild.0cU0nG.log
```
And then in the log:
```
Ld /Users/fernando.moyaderivas/Library/Developer/Xcode/DerivedData/Stripe-cotvsvnxotsldyepvmvixosalwmg/Build/Intermediates.noindex/Stripe.build/Release-iphonesimulator/StripeiOS.build/Objects-normal/arm64/Binary/Stripe normal arm64 (in target 'StripeiOS' from project 'Stripe')
    cd /Users/fernando.moyaderivas/Downloads/stripe-ios-davidme-enable-catalyst
    /Users/fernando.moyaderivas/Downloads/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios11.0-simulator -dynamiclib -isysroot /Users/fernando.moyaderivas/Downloads/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk -L/Users/fernando.moyaderivas/Library/Developer/Xcode/DerivedData/Stripe-cotvsvnxotsldyepvmvixosalwmg/Build/Products/Release-iphonesimulator -L/Users/fernando.moyaderivas/Downloads/stripe-ios-davidme-enable-catalyst/InternalFrameworks -F/Users/fernando.moyaderivas/Library/Developer/Xcode/DerivedData/Stripe-cotvsvnxotsldyepvmvixosalwmg/Build/Products/Release-iphonesimulator -F/Users/fernando.moyaderivas/Downloads/stripe-ios-davidme-enable-catalyst/InternalFrameworks -filelist /Users/fernando.moyaderivas/Library/Developer/Xcode/DerivedData/Stripe-cotvsvnxotsldyepvmvixosalwmg/Build/Intermediates.noindex/Stripe.build/Release-iphonesimulator/StripeiOS.build/Objects-normal/arm64/Stripe.LinkFileList -install_name @rpath/Stripe.framework/Stripe -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/fernando.moyaderivas/Library/Developer/Xcode/DerivedData/Stripe-cotvsvnxotsldyepvmvixosalwmg/Build/Intermediates.noindex/Stripe.build/Release-iphonesimulator/StripeiOS.build/Objects-normal/arm64/Stripe_lto.o -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -fapplication-extension -ObjC -lStripe3DS2-static-sim -framework Contacts -framework CoreLocation -framework Foundation -framework PassKit -framework Security -framework WebKit -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/fernando.moyaderivas/Library/Developer/Xcode/DerivedData/Stripe-cotvsvnxotsldyepvmvixosalwmg/Build/Intermediates.noindex/Stripe.build/Release-iphonesimulator/StripeiOS.build/Objects-normal/arm64/Stripe_dependency_info.dat -o /Users/fernando.moyaderivas/Library/Developer/Xcode/DerivedData/Stripe-cotvsvnxotsldyepvmvixosalwmg/Build/Intermediates.noindex/Stripe.build/Release-iphonesimulator/StripeiOS.build/Objects-normal/arm64/Binary/Stripe
ld: library not found for -lStripe3DS2-static-sim
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/fernando.moyaderivas/Library/Developer/Xcode/DerivedData/Stripe-cotvsvnxotsldyepvmvixosalwmg/Build/Intermediates.noindex/Stripe.build/Release-iphonesimulator/StripeiOS.build/Objects-normal/arm64/Binary/Stripe normal arm64
(1 failure)
```

**Comment by davidme-stripe** [comment]
Ah, sorry, I'm not sure why that error isn't happening with Swift Package Manager. You can work around this by renaming each of the 3 `.a` slice files in the Stripe3DS2.xcframework to `libStripe3DS2.a` (removing the `-static-sim` bits), then modifying the 3 `LibraryPath` keys in Stripe3DS2.xcframework/Info.plist to `libStripe3DS2.a` as well.

I'll build a new .xcframework with these changes soon.

**Comment by davidme-stripe** [comment]
Here's an [updated Stripe3DS2.xcframework](https://github.com/stripe-ios/stripe-3ds2-ios-releases/releases/download/20.0.1/Stripe3DS2.xcframework.zip) built with Xcode 12 GM.

Weirdly, it looks like they removed support for Catalyst+arm64 in Xcode 12 GM, though it does still build an arm64 slice for the simulator.

**Comment by fermoya** [comment]
I think I can't build this myself. At the end of the script, it tries to sign the the archives before creating the xcframework. I've commented those lines (101-109 and 116-144) and the xcframework gets generated but I'm not sure if it should have been signed or not. This could lead to problems on submission to the App Store

**Comment by davidme-stripe** [comment]
I don't think that matters: The final app is signed by you at the archive step, and the signature on any attached frameworks is overwritten.

**Comment by fermoya** [comment]
@davidme-stripe is this meant to be merged into `master`? As soon as you start using the Xcode 12, at some point they’ll reenable the Big Sur compilation and you’ll start compiling for both Apple Silicon and Intel.

**Comment by davidme-stripe** [comment]
Yep! We plan to distribute compiled binaries for Catalyst/arm64 as soon as Apple re-enables the Big Sur SDK in Xcode.

**Comment by davidme-stripe** [comment]
Please try [Stripe 20.1.0](https://github.com/stripe/stripe-ios/releases/tag/20.1.0), it should fix this. The default Stripe.xcframework.zip is built with Xcode 12, and we're also shipping a Stripe-Xcode11.xcframework.zip for Xcode 11.
