### ISSUE TITLE
Setting textContentType on STPPaymentCardTextField crashes app

### ISSUE THREAD

**Issue by daihovey** [stripe/stripe-ios#1652]
## Summary

App crashes if I try and set the `textContentType` of the `STPPaymentCardTextField` to be `.creditCardNumber`.

Is it not meant to be set?

```*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[STPPaymentCardTextField setTextContentType:]: unrecognized selector sent to instance 0x7fe68f4dc3a0'```

## Code to reproduce

```
lazy var cardTextField: STPPaymentCardTextField = {
        let cardTextField = STPPaymentCardTextField()
        cardTextField.postalCodeEntryEnabled = false
        cardTextField.backgroundColor = UIColor(red: 0.960, green: 0.964, blue: 0.972, alpha: 1)
        cardTextField.textColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.7)
        cardTextField.placeholderColor = UIColor(red: 0.812, green: 0.827, blue: 0.863, alpha: 1.0)
        cardTextField.borderColor = UIColor.clear
        cardTextField.borderWidth = 0.0
        cardTextField.textErrorColor = UIColor.red
        cardTextField.cornerRadius = 10.0
        cardTextField.textContentType = .creditCardNumber
        cardTextField.delegate = self
        return cardTextField
    }()
```

## iOS version

iOS 14 GM

## SDK version

`19.2.0`

**Comment by csabol-stripe** [comment]
Hi @daihovey, `STPPaymentCardTextField` does not conform to `UITextInputTraits` so doesn't have a `textContentType` property. It actually contains several sub text fields with varying types (e.g. postal code, cvv, etc.) so this is expected :) Thanks!
