### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by farhanmunir50** [stripe/stripe-ios#1656]
To use apple pay I have upgraded stripe sdk and its working fine on simulator. When we build for Archive its fails with the following error. 

Xcode: 11.2
STPSDKVersion = @"20.0.0";
Using stripe framework as dependency.

../ExternalLibraries/Frameworks/Stripe.framework/Stripe, missing required architecture armv7 in file ../ExternalLibraries/Frameworks/Stripe.framework/Stripe (2 slices)
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_STPCardValidator", referenced from:
      objc-class-ref in TestUV.o
      objc-class-ref in TestUV1.o
  "_OBJC_CLASS_$_STPCardParams", referenced from:
      objc-class-ref in TestUV.o
  "_OBJC_CLASS_$_Stripe", referenced from:
      objc-class-ref in TestUV3.o
      objc-class-ref in TestUV.o
  "_OBJC_CLASS_$_STPApplePayContext", referenced from:
      objc-class-ref in TestUV3.o
  "_OBJC_CLASS_$_STPAPIClient", referenced from:
      objc-class-ref in TestUV3.o
      objc-class-ref in TestUV.o
      objc-class-ref in TestUV1.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Ariandr** [comment]
Hi @farhanmunir50 
Probably you support iOS 10 (iPhone 5/5c which have `armv7` architecture), but Stripe 20.0.0 dropped support for it.

You can use Stripe 19.x.x because it supports iOS 10.
