### ISSUE TITLE
No debug symbols in executable (-arch arm64)

### ISSUE THREAD

**Issue by gilrodar** [stripe/stripe-ios#1658]
## Summary

After archiving the application I skip this warning.

<img width="1250" alt="Captura de Pantalla 2020-09-28 a la(s) 14 58 48" src="https://user-images.githubusercontent.com/13817108/94480108-6cb08b00-019b-11eb-81aa-39a69b9483a5.png">

## iOS version

14.0.1

## Installation method

Swift Package Manager

## SDK version

20.0.0

**Comment by davidme-stripe** [comment]
Thanks! This seems like it might be another `type: .dynamic` bug in SPM. It looks like it's building Stripe.framework to a `Release-iphoneos` folder, which is surprising if it's trying to build debug symbols.

**Comment by gilrodar** [comment]
I saw this different, your library is the only one that appears "Enbed & Sing".

<img width="807" alt="Captura de Pantalla 2020-09-29 a la(s) 13 55 13" src="https://user-images.githubusercontent.com/13817108/94603270-a34dda80-025b-11eb-84d8-9eace7c84cdf.png">

**Comment by Max-Job** [comment]
any news?

**Comment by davidme-stripe** [comment]
Please try Stripe 20.1.0, it should fix this. Note that you'll have to remove and re-add Stripe from the `Frameworks, Libraries, and Embedded Content` section of your target's settings after updating, and you'll need to apply a [code-signing workaround](https://github.com/stripe/stripe-ios/issues/1673) until Xcode 12.2 is out.

**Comment by gilrodar** [comment]
Thanks but now show me this.

<img width="981" alt="Captura de Pantalla 2020-10-15 a la(s) 17 36 50" src="https://user-images.githubusercontent.com/13817108/96193145-2bdfa280-0f0d-11eb-82fe-d45f00131841.png">

**Comment by davidme-stripe** [comment]
Ah, very sorry, I must have missed that after moving the Stripe3DS2 resources into Stripe3DS2.framework. We'll fix it soon. #1675

**Comment by davidme-stripe** [comment]
This is fixed in 20.1.1.

**Comment by gilrodar** [comment]
Works for me. Thanks 👍
