### ISSUE TITLE
Swift simple example fails when it should succeed and vise-versa

### ISSUE THREAD

**Issue by robseward** [stripe/stripe-ios#166]
I'm new to this, so sorry if I'm misunderstanding something, but I think a conditional in the Apple Pay flow in the iOS example is incorrect.

Here's the line: https://github.com/stripe/stripe-ios/blob/master/Example/Stripe%20iOS%20Example%20(Simple)/ViewController.swift#L80

My understanding is it should be like this:

```swift 
apiClient.createTokenWithPayment(payment, completion: { (token, error) -> Void in
            if error == nil {
                  //create backend charge with token
                  //on success call completion with success status
                  return
            }
            //completion with failure status
}
```

While instead the conditional in the current code reads `if error != nil` instead of `if error == nil`.

**Comment by jflinter** [comment]
Yep, that is indeed a huge typo on our end, thanks for pointing that out!

You mentioned you're new to things - would you be interested in submitting a pull request that fixes this? Happy to help you do it if you're interested. If not, I'll fix things up myself.

**Comment by robseward** [comment]
Sure! I'll submit a pull request shortly.
