### ISSUE TITLE
'Library not loaded' error using SPM

### ISSUE THREAD

**Issue by gsapienza** [stripe/stripe-ios#1670]
I am trying to install Stripe as a dependency in a package that I use between a few different app targets. When installing on a device I encounter this error:

`dyld: Library not loaded: @rpath/Stripe.framework/Stripe
  Referenced from: /private/var/containers/Bundle/Application/133983A2-47A4-4336-82CD-24AE19BC033D/Breeze.app/Breeze
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib`

I can remedy the situation by embedding and signing the Stripe library in the app directly, but I have not had to do that with other dynamic libraries installed using SPM

## iOS version
iOS 14.0

## Installation method
Swift Package Manager

## SDK version
20.0.0

**Comment by davidme-stripe** [comment]
Hey @gsapienza, thanks for filing! Do the other SPM libraries include `type: .dynamic` in their Package.swift? I think this might be another SPM bug related to a dependency chain that includes a dynamic library.

**Comment by davidme-stripe** [comment]
Please try Stripe 20.1.0, it should fix this. Note that you'll have to remove and re-add Stripe from the `Frameworks, Libraries, and Embedded Content` section of your target's settings after updating, and you'll need to apply a [code-signing workaround](https://github.com/stripe/stripe-ios/issues/1673) until Xcode 12.2 is out.

**Comment by gsapienza** [comment]
Thanks @davidme-stripe! 20.1.0 fixes this for me. And to answer your question, yes the other libraries did include `type: .dynamic`
