### ISSUE TITLE
Can't contitnue to pay with 3DS v2 again. The SDK doesn't recognize the PaymentIntent action type.

### ISSUE THREAD

**Issue by cythb** [stripe/stripe-ios#1672]
## Summary

I got a error showed that:

```
10:19:57 ❤️ ERROR [payment]: Optional(Error Domain=STPPaymentHandlerErrorDomain Code=0 "There was an unexpected error -- try again in a few seconds" UserInfo={com.stripe.lib:ErrorMessageKey=The SDK doesn't recognize the PaymentIntent action type., NSLocalizedDescription=There was an unexpected error -- try again in a few seconds, STPIntentActionUseStripeSDK=<STPIntentActionUseStripeSDK: 0x6000022b6e80; directoryServer = (null); directoryServerID = (null); directoryServerKeyID = (null); serverTransactionID = (null); directoryServerCertificate = (null); rootCertificateStrings = (null); threeDSSourceID = (null); type = stripe_3ds2_challenge; redirectURL = (null)>})
```

This doesn't make sense.

## Code to reproduce

1. pay with 4000000000003220.
2. kill the app when the 3DS v2 popup.
3. pay again with 4000000000003220.

The `intents` is a response from our server. 
```
STPPaymentHandler.shared().handleNextAction(forPayment: intents, authenticationContext: self, returnURL: nil) { [weak self] (status, _, error) in
            log.error("[payment]: \(error)")
        }
```

## iOS version

iOS 14.0.1

## Installation method

pod 

## SDK version

19.2.0

## Other information

I noticed that the same request returned different data twice.

[request and response.zip](https://github.com/stripe/stripe-ios/files/5375297/request.and.response.zip)

**Comment by yuki-stripe** [comment]
Hi @cythb,

Thanks for the report, I've repro'd this and am investigating.

**Comment by yuki-stripe** [comment]
We're working on a fix for this issue. As a temporary workaround until we release a bugfix, you could:
* Recreate the PaymentIntent
* Confirm with a new Payment Method (ie don't reuse the Payment Method ID)

**Comment by cythb** [comment]
Thank you for your response.
I've solved the problem this way for now.

```
let parmas = STPPaymentIntentParams(clientSecret: intents)
// !!!: I have to set a different value each time.
parmas.returnURL = "rohan://pay/confirm/\(intents)/\(Date().timeIntervalSince1970)"
STPPaymentHandler.shared().confirmPayment(withParams: parmas, authenticationContext: self, completion: completion)
```

The verification against SCA works fine for now. But there is one strange thing, my `returnURL` must be different every time.

**Comment by davidme-stripe** [comment]
This should be fixed in the latest SDK update. Let us know if you're still experiencing this issue!
