### ISSUE TITLE
"No code signature found" error when using Swift Package Manager

### ISSUE THREAD

**Issue by davidme-stripe** [stripe/stripe-ios#1673]
Because of [an Xcode bug](https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/34), you may need to apply a workaround to properly sign an app that imports the Stripe SDK via Swift Package Manager. [PSPDFKit has a visual guide of the workaround](https://pspdfkit.com/guides/ios/current/knowledge-base/library-not-found-swiftpm/), though if you import Stripe into another SPM package, you may need [an additional workaround](https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/29) to use the proper code signing identity.

This is fixed in Xcode 12.2. I'll close this issue once Xcode 12.2 is out.

**Comment by DimDL** [comment]
Xcode 12.2 is out, I think you can close this one !

**Comment by SergejLogis** [comment]
We are running `Stripe 20.1.1` via SPM on `Xcode 12.2` but facing issues. If we try to install app on the device without any fixes, it fails with the very same error: _"No code signature found"_. But if we apply `PSPDFKit` fix then app installs, but crashes on launch with _"Library not loaded"_ error. 
Deadline for the build with integrated Stripe SDK is approaching quickly but we can't even install the app on a device... 😰 
Any help or suggestion would be highly appreciated! 🙏 Thank you.
