### ISSUE TITLE
Stripe3DS2 with App Clips using SPM

### ISSUE THREAD

**Issue by gsapienza** [stripe/stripe-ios#1676]
This is likely an Xcode bug but I thought I'd put it here in case I was wrong. One problem with the new config of the SPM manifest using a static library is that the Stripe3DS2 framework becomes embedded in the App Clips folder when building. Xcode does not raise any errors with this config, until it needs to compile for Bitcode where it then presents a duplicate symbol error.

Here is a screenshot of the file config in the app bundle, and I have attached a sample project with the issue as well. To see the problem, simply build the main app scheme, then view the .app package contents.

<img width="882" alt="Screen Shot 2020-10-18 at 9 44 35 PM" src="https://user-images.githubusercontent.com/2574192/96392969-bb928480-118b-11eb-814a-d3d2bf3ec411.png">

[Dynamic Library Issue.zip](https://github.com/stripe/stripe-ios/files/5398589/Dynamic.Library.Issue.zip)

## iOS version
iOS 14

## Xcode version
12.0

## Installation method
Swift Package Manager

## SDK version
20.1.0

**Comment by davidme-stripe** [comment]
Thanks for the sample project! This does sound like another Xcode bug, but I'll investigate it on our end too. Cocoapods 1.10 might be the easiest solution for this once it's out of beta.

**Comment by davidme-stripe** [comment]
Sorry, I should have come back to this: This is a known Xcode issue, and there's a workaround in #1705. We're also looking into improvements we can make on our end to avoid this.

**Comment by davidme-stripe** [comment]
The Stripe3DS2 dependency is now distributed as source instead of a binary, which should resolve this issue. Please update to version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0).
