### ISSUE TITLE
Presenting STPPaymentOptionsViewController executes the delegate paymentOptionsViewController:didSelectPaymentOption: 

### ISSUE THREAD

**Issue by ahmadfs** [stripe/stripe-ios#1678]
## Summary
When presenting STPPaymentOptionsViewController, the delegate (paymentOptionsViewController:didSelectPaymentOption: ) is getting called automatically. As a result, we get returned the STPPaymentMethod object which contains the payment method details. When this is returned, we check if the payment method has changed, remained the same or if it is Apple Pay. Because we are getting a null value for STPPaymentMethod.stripeId when Apple Pay is selected, we are unable to cleanly determine if the payment method was unselected or Apple Pay was chosen. 

Ideally, we want to see this behavior:
1. Don't execute didSelectPaymentOption delegate when presenting the STPPaymentOptionsViewController
2. Execute the delegate when the user has actually selected a payment method. 
3. If payment method selected is Apple Pay, then return the type to indicate Apple Pay was selected. 

If it helps, in our use case, we want user to authorize an Apple Pay payment method so they can be charged at a later time depending on their usage via payment intents we create on our backend. This is similar to the metered billing use-case. Right now, we have to get token from Apple Pay (frontend), tokenize (backend), convert to payment method (backend) and attach to customer (backend). This isn't ideal. 

## iOS version
iOS12+

## Installation method
Using cocoapods

## SDK version
20.0.0+

**Comment by yuki-stripe** [comment]
Hi @ahmadfs 

If Apple Pay is selected, `paymentOptionsViewController:didSelectPaymentOption:` returns an `STPApplePayPaymentOption` object instead of an `STPPaymentMethod`. e.g.

```
- (void)paymentOptionsViewController:(STPPaymentOptionsViewController *)paymentOptionsViewController
              didSelectPaymentOption:(id<STPPaymentOption>)paymentOption {
   if ([paymentOption isKindOfClass:[STPApplePayPaymentOption class]]) {
      // User selected Apple Pay
   }

}


```
