### ISSUE TITLE
Stripe linting problem

### ISSUE THREAD

**Issue by armandsavotins** [stripe/stripe-ios#1681]
Since Xcode 12 when Stripe is included as s.dependency in some podspec linting fails with error:

```
The following build commands failed:
    	CompileSwift normal x86_64 /Users/username/Documents/E-Life/Projekti/Monetizr/Stripe-lint-test/Source/StripeTest.swift
    	CompileSwift normal arm64 /Users/username/Documents/E-Life/Projekti/Monetizr/Stripe-lint-test/Source/StripeTest.swift
    	Ld /Users/username/Library/Developer/Xcode/DerivedData/App-ercfyrfvdehmrnfiohzugpvsklqn/Build/Intermediates.noindex/Pods.build/Release-iphonesimulator/Stripe.build/Objects-normal/arm64/Binary/Stripe normal arm64
    (3 failures)
   Testing with `xcodebuild`. 
 -> StripeTest (1.0)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
```
Tested with 

* Cocoapods version - 1.10.0, 1.10.0.rc.1, 1.9.0
* Stripe version - 20.1.0, 20.0.0
* Xcode version - 12.1 (12A7403)

Test project can be found https://github.com/armandsavotins/Stripe-lint-test

**Comment by davidme-stripe** [comment]
Thanks for the sample project! We'll have an update out to support Cocoapods 1.10 + Xcode 12 very soon.

**Comment by davidme-stripe** [comment]
This is fixed in 20.1.1. Let me know if you're still experiencing the issue!

**Comment by armandsavotins** [comment]
Not sure why, but can't see version 20.1.1

` -> StripeTest (1.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (CocoaPods could not find compatible versions for pod "Stripe":
  In Podfile:
    StripeTest (from `/Users/armandsavotins/Documents/E-Life/Projekti/Monetizr/Stripe-Lint-Test`) was resolved to 1.0, which depends on
      Stripe (~> 20.1.1)

None of your spec sources contain a spec satisfying the dependency: `Stripe (~> 20.1.1)`.`

**Comment by davidme-stripe** [comment]
Hm, it's showing as available on the Cocoapods CDN for me and https://cocoapods.org/pods/Stripe. Can you try `pod repo update`?

**Comment by armandsavotins** [comment]
Yeah right, caching issue. Linting problem resolved.
