### ISSUE TITLE
Allowed credit card brands

### ISSUE THREAD

**Issue by juanuribeo13** [stripe/stripe-ios#1682]
## Summary
I'm using `STPPaymentCardTextField` for card entry but we don't support all credit card brands so I want to be able to set the brands that are supported and have the field validate if the card entered is from a supported brand or not.

## Code to reproduce
N/A

## iOS version
N/A

## Installation method
Cocoapods

## SDK version
I'm using version 20.1.0 at the moment.

## Other information
I already added support for this on [this fork](https://github.com/soulcycle/stripe-ios/tree/acceptedCardBrands) and wanted to get the conversation started to see if you're interested in getting it into the main repo.

**Comment by davidme-stripe** [comment]
Thanks for the request! We'd rather not offer this client-side, as it'd be possible for a user with a jailbroken device to subvert such a block. I'd recommend using [Radar for Fraud Teams](https://stripe.com/radar/fraud-teams), which would let you write a `Block if :card_brand: = 'blockedBrandName'` rule to block specific networks.

Alternatively, you can use [manual confirmation](https://stripe.com/docs/payments/accept-a-payment-synchronously#ios). In step 4, before confirming the PaymentIntent, you can inspect the `card.brand` from the PaymentMethod and block the charge as needed.

**Comment by juanuribeo13** [comment]
I see, yeah we are blocking the unsupported brands on the server but also want the users to see in the front that the entered card is invalid so they don't fill up all the form just to get an error.

Thanks for taking a look at it 😉
