### ISSUE TITLE
Build Failure when integrating via Carthage

### ISSUE THREAD

**Issue by stherold** [stripe/stripe-ios#1685]
## Summary
The following error occurs when integrating the SDK via Carthage 0.36.0 (`carthage update stripe-ios --use-ssh --platform iOS`):

```shell
ld: library not found for -lStripe3DS2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by davidme-stripe** [comment]
Hi stherhold! A few ideas:

* Are you using Xcode 11? The pre-compiled binaries are built for Xcode 12, so you may need to tell Carthage to build from source. Try `carthage update stripe-ios --no-use-binaries --use-ssh --platform iOS`.
* Your Carthage cache may be picking up Stripe3DS2 from an older version of the Stripe SDK: Try cleaning out the `Carthage` folder in your project and the `~/Library/Caches/org.carthage.CarthageKit` folder.

If that doesn't work, could you run carthage with `--verbose` and attach the output? Thanks!

**Comment by stherold** [comment]
> Hi stherhold! A few ideas:
> 
> * Are you using Xcode 11? The pre-compiled binaries are built for Xcode 12, so you may need to tell Carthage to build from source. Try `carthage update stripe-ios --no-use-binaries --use-ssh --platform iOS`.
> * Your Carthage cache may be picking up Stripe3DS2 from an older version of the Stripe SDK: Try cleaning out the `Carthage` folder in your project and the `~/Library/Caches/org.carthage.CarthageKit` folder.
> 
> If that doesn't work, could you run carthage with `--verbose` and attach the output? Thanks!

You where right it was the old Carthage cache 🤦‍♂️  A simple removal of the Carhage folder solved the issue. But many others might run into this problem too so I leave the issue open and leave it up to you to close it at some time.

**Comment by davidme-stripe** [comment]
Good point, I'll leave this open for a bit. Thanks for filing!

**Comment by Mortgy** [comment]
I got the same error using pods 

```ld: library not found for -lstripe3DS2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
