### ISSUE TITLE
Property attributes 'nonnull' and 'weak' are mutually exclusive

### ISSUE THREAD

**Issue by davidrothera** [stripe/stripe-ios#169]
Issues building in XCode 7.0 (beta)

Issue comes from STPCheckoutInternalUIWebViewController.h line 22

**Comment by jflinter** [comment]
Thanks; closed in 48f4e3181fb81275a5c63182813dc562e98d7ac9

**Comment by billinghamj** [comment]
@jflinter could you publish it to npm please?

**Comment by jflinter** [comment]
(I assume you mean cocoapods, @billinghamj? :smile:)

I think it's a bit aggressive to publish releases just for people using a beta version of Xcode - if you'd like to use it until then, I'd suggest using our master branch - just add the following line to your `Podfile`:

```ruby
pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git'
```
