### ISSUE TITLE
App does not install when using Stripe Swift package instead of Cocoapod

### ISSUE THREAD

**Issue by hspindell** [stripe/stripe-ios#1696]
## Summary
When using Swift Package instead of Cocoapods, unable to install app on physical device with "No code signature found". Installs fine on simulator with same iOS version. Provisioning profile is correct as when I use the Stripe cocoapod I am able to use the SDK just fine and install on physical device.

`Unable to install "App name"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
--
No code signature found.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402620388
User Info: {
    DVTRadarComponentKey = 261622;
    MobileDeviceErrorCode = "(0xE800801C)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000012340393f DTDKCreateNSErrorFromAMDErrorCode + 220
	1   DTDeviceKitBase                     0x0000000123442124 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 155
	2   DVTFoundation                       0x000000010792fb43 DVTInvokeWithStrongOwnership + 71
	3   DTDeviceKitBase                     0x0000000123441e65 -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1440
	4   IDEiOSSupportCore                   0x00000001232b2d28 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.292 + 3513
	5   DVTFoundation                       0x0000000107a5e2aa __DVT_CALLING_CLIENT_BLOCK__ + 7
	6   DVTFoundation                       0x0000000107a5fecc __DVTDispatchAsync_block_invoke + 1191
	7   libdispatch.dylib                   0x00007fff6a4586c4 _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x00007fff6a459658 _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00007fff6a45ec44 _dispatch_lane_serial_drain + 597
	10  libdispatch.dylib                   0x00007fff6a45f5d6 _dispatch_lane_invoke + 363
	11  libdispatch.dylib                   0x00007fff6a468c09 _dispatch_workloop_worker_thread + 596
	12  libsystem_pthread.dylib             0x00007fff6a6b3a3d _pthread_wqthread + 290
	13  libsystem_pthread.dylib             0x00007fff6a6b2b77 start_wqthread + 15
);
}
--
System Information
macOS Version 10.15.7 (Build 19H2)
Xcode 12.0.1 (17220)`

## iOS version
iOS 14.0

## Installation method
![image](https://user-images.githubusercontent.com/2597158/97230511-4a5c5e00-1797-11eb-9511-7d1a4bda0f4e.png)

## SDK version
20.1.1

**Comment by davidme-stripe** [comment]
Hello, thanks for filing! This is a known issue with Xcode 12.0: You can resolve it by installing the Xcode 12.2 beta or using [this workaround](https://github.com/stripe/stripe-ios/issues/1673).

**Comment by gilrodar** [comment]
I run the app with Xcode 12.1 and I have the same issue.

**Comment by SergejLogis** [comment]
We run Xcode 12.2 and still facing the very same issue...

**Comment by davidme-stripe** [comment]
Hi! The Stripe3DS2 dependency is now distributed as source instead of a binary, which should resolve this issue. Please update to version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0).
