### ISSUE TITLE
Update "Billing Address" section verbiage to "Billing Information"

### ISSUE THREAD

**Issue by allanchowbus** [stripe/stripe-ios#1697]
## Summary
When only requiring Zip Code, especially in countries with alphanumeric postal codes, people are getting confused by the bold section header "Billing Address" and attempt to enter in a whole address and then get a message saying that the postal code is invalid.  Ultimately, potential customers end up giving up.

Suggest updating the wording to "Billing Information" so that people will see the "Postal Code" field label more explicitly.

**Comment by davidme-stripe** [comment]
Thank you for filing! I agree that this is confusing: We're currently working on ways to improve these labels based on [W3C WAI guidance](https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text).

**Comment by davidme-stripe** [comment]
This is addressed in our new [Payments UI beta](https://stripe.com/docs/mobile/payments-ui-beta) in SDK version 21.5.0.
![A screenshot of the Payments UI beta](https://b.stripecdn.com/docs/assets/overview-complete.f08cdac19b6948ac6035828dd35c59aa.png)
