### ISSUE TITLE
Build failure when installing 20.1.1 with CocoaPods due to missing Stripe3DS2

### ISSUE THREAD

**Issue by ricsantos** [stripe/stripe-ios#1698]
## Summary

Updating to Stripe 20.1.1 via CocoaPods (1.9.1), project does not compile due to error:
`ld: framework not found Stripe3DS2`

## Code to reproduce

Create a new project in Xcode, add this podfile:
```
platform :ios, '13.0'

target 'StripeTest' do
  use_frameworks!

  pod 'Stripe'
end
```

## iOS version

iOS 14.1, Xcode 12.1

## Installation method

CocoaPods

## SDK version

20.1.1

## Other information

I have deleted all derived data and cleaned the build folder, restarted Xcode.

**Comment by ricsantos** [comment]
Update: downgrading to Stripe 20.1.0 resolves this, so it appears to be an issue only with the latest release (20.1.1).

**Comment by davidme-stripe** [comment]
Please update to Cocoapods 1.10 with `sudo gem install cocoapods`. Unfortunately, we had to break compatibility with Cocoapods 1.9 in order to properly support Xcode 12. (Xcode 11 still works too, but  also requires Cocoapods 1.10.) Sorry for the inconvenience!

**Comment by ricsantos** [comment]
Oh yeah, I did see that in the change logs, but for some reason my brain felt that 1.10 was < 1.9.x. Doh.

Thanks for the quick reply!

**Comment by davidme-stripe** [comment]
No worries, I've made that mistake too! :) I'll leave this open for a bit in case anyone else runs into this issue.

**Comment by vishnuharidas** [comment]
Codemagic suddenly stopped building my Flutter project with the [stripe_payment](https://pub.dev/packages/stripe_payment) plugin, and this was causing it.

I manually set the Cocoapods version to 1.10.0 in Codemagic under the "Build" section, and the error disappeared.

**Comment by davidme-stripe** [comment]
The Stripe3DS2 dependency is now distributed as source instead of a binary, which should resolve this issue, even when using pre-1.10 versions of Cocoapods. Please update to version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0).
