### ISSUE TITLE
Can't redirect to app with 3Ds2

### ISSUE THREAD

**Issue by AldoJuniorSimoncini** [stripe/stripe-ios#1700]
## Summary
![3ds_working](https://user-images.githubusercontent.com/17861781/97471878-7cadbd00-1949-11eb-90f8-a1cde9bda9da.gif)
![3ds2_notworking](https://user-images.githubusercontent.com/17861781/97471895-80d9da80-1949-11eb-871e-a74a702c9352.gif)

I can't  complete a redirect flow with 3Ds2 Test card n. 4000 0000 0000 3220.
Everything works fine with 3Ds cards but with 3Ds2 when I land in the test page with "fail" and "complete" buttons, tapping
one of that buttons I can't go back to app (returnUrl is properly set and works with 3Ds1).

## iOS version
14.1

## Installation method
Swift Package Manager

## SDK version
Stripe 20.1.1

**Comment by davidme-stripe** [comment]
Hello! Thank you for the bug report (and the GIFs!). This may be a better question for our support team at https://support.stripe.com.
I do have one thought: How are you creating and confirming this PaymentIntent? If you're handling confirmation on the server-side, you may need to enable the `use_stripe_sdk` parameter when creating the PaymentIntent to enable native 3DS2 support. https://stripe.com/docs/payments/accept-a-payment-synchronously#ios-create-payment-intent

**Comment by AldoJuniorSimoncini** [comment]
thank you so much @davidme-stripe I solved. I changed my implementation using PaymentHandler instead of redirectContext and set that use_stripe_sdk parameter
