### ISSUE TITLE
App Store Connect Operation Error - CFBundleIdentifier Collision

### ISSUE THREAD

**Issue by AldoJuniorSimoncini** [stripe/stripe-ios#1701]
## Summary
Trying to upload to app store connect I receive following errors. 
As you could see when archiving process finish, I have two Stripe3DS2.framework

<img width="1030" alt="Schermata 2020-10-23 alle 18 37 29" src="https://user-images.githubusercontent.com/17861781/97472900-a5828200-194a-11eb-8b75-2d5a95cfd4b8.png">

![IMAGE 2020-10-28 18:17:12](https://user-images.githubusercontent.com/17861781/97472941-afa48080-194a-11eb-9754-f4958b094c4b.jpg)

## iOS version
14.1
xcode 12.1

## Installation method
Swift Package Manager

## SDK version
Stripe 20.1.1

**Comment by davidme-stripe** [comment]
Hi AldoJuniorSimoncini! A few ideas:
* If you're switching from a different package manager, did you make sure to remove Stripe from the various other parts of your project, Cocoapods, or Carthage settings?
* This might be an Xcode bug. You can add a post-build script to remove the erroneous Stripe3DS2.framework from your PlugIns folder, like this: https://github.com/firebase/firebase-ios-sdk/issues/6472#issuecomment-707793520

**Comment by AldoJuniorSimoncini** [comment]
Hi @davidme-stripe, yes I switched from cocoapods, I'll try your suggestion, thank you for your quick reply

**Comment by AldoJuniorSimoncini** [comment]
Seems like it's not a dependency manager switch problem, but with the script it works, thankyou @davidme-stripe
