### ISSUE TITLE
Unable to Archive

### ISSUE THREAD

**Issue by EliteTechnicalCare** [stripe/stripe-ios#1704]
## Summary

When archiving using the Stripe SDK (Swift Package Manager) it will error out in the end stating

> Ignoring file /Users/davidhakki/Library/Developer/Xcode/DerivedData/EliteBiller-cbzvisjaayiyssdyjoyurpgvqltt/Build/Intermediates.noindex/ArchiveIntermediates/EliteBiller/BuildProductsPath/Release-maccatalyst/Stripe3DS2.framework/Stripe3DS2, building for Mac Catalyst-arm64 but attempting to link with file built for Mac Catalyst-x86_64

<img width="419" alt="Screen Shot 2020-10-30 at 10 34 30 AM" src="https://user-images.githubusercontent.com/12222977/97717738-80e9ef80-1a9b-11eb-8140-fa815e0177be.png">

## iOS version

iOS 13

## Installation method

Swift Package Manager

## SDK version

20.1.1

**Comment by davidme-stripe** [comment]
Hello! Is this on Xcode 12.2? We aren't building Catalyst-arm64 slices at the moment, as they're not supported by any released version of Xcode, and I don't believe the App Store will accept them at the moment. Could you use Xcode 12.1 to archive for now?

**Comment by EliteTechnicalCare** [comment]
I am on the current release of Xcode 12.2, I tested it on intel Mac for now and I am getting a different error

```
ld: warning: directory not found for option '-L/Users/david/Library/Developer/Xcode/DerivedData/EliteBiller-bdutqagofmvlkjhckuimrsizkkxt/Build/Intermediates.noindex/ArchiveIntermediates/EliteBiller/BuildProductsPath/Release-maccatalyst/XCFrameworkIntermediates/Stripe3DS2'
ld: library not found for -lstripe3DS2
```

Will we still have to use Xcode 12.1 (it was working on this version)

**Comment by davidme-stripe** [comment]
We'll release an update for Xcode 12.2 very soon, sorry for the hassle!

**Comment by EliteTechnicalCare** [comment]
No worries thanks for the quick update. Meanwhile I redownloaded 12.1

**Comment by davidme-stripe** [comment]
Try again with Xcode 12.2 and Stripe 21.0.0 — we've added full support for Catalyst on Apple silicon.

**Comment by davidme-stripe** [comment]
Following up on this: The Stripe3DS2 dependency is now distributed as source instead of a binary, which should make this integration less painful. Please update to version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0).
