### ISSUE TITLE
Xcode archive build with SPM creates IPA that App Store does not accept

### ISSUE THREAD

**Issue by HunterHillegas** [stripe/stripe-ios#1705]
## Summary

Adding the Stripe iOS SDK via SPM and then including it in an iOS app includes three copies of the SDK in the built archive that App Store Connect rejects as invalid.

## Code to reproduce

Add iOS SDK via SPM to a project that includes an iOS app as well as a watchOS app and several extensions.

Verify that the Stripe SDK is only set to be included in the actual iOS app.

Archive the app.

Review the output. The Stripe3DS2.framework folder is in three places: Frameworks, PlugIns, and Watch.

Attempt to submit to Apple. App Store Connect reports several errors - it does not like the copies under PlugIns and Watch. It also complains that there are multiple copies of the same framework.

## iOS version

iOS 14.1

## Installation method

Swift Package Manager

## SDK version

20.1.1 according to Xcode.

## Other information

Tried this on both Xcode 12.1.1 release candidate and Xcode 12.2 beta.

**Comment by davidme-stripe** [comment]
Hi, sorry for the trouble! This is an Xcode bug, but you can add a post-build script to remove the extraneous Stripe3DS2.framework from the PlugIns and Watch folders, as detailed here: https://github.com/firebase/firebase-ios-sdk/issues/6472#issuecomment-707793520

**Comment by HunterHillegas** [comment]
> Hi, sorry for the trouble! This is an Xcode bug, but you can add a post-build script to remove the extraneous Stripe3DS2.framework from the PlugIns and Watch folders, as detailed here: [firebase/firebase-ios-sdk#6472 (comment)](https://github.com/firebase/firebase-ios-sdk/issues/6472#issuecomment-707793520)

That worked, thanks!

**Comment by mrkvans** [comment]
I think this issue is resolved now... 

The recent Xcode update might have helped. 

I was able to successfully upload my app without the errors listed above (which I had without resolution for over a week). 

But, I had to remove the Stripe Swift Package, then re-add it to my project before it would work properly.

**Comment by davidme-stripe** [comment]
This workaround should be the same in 21.0.0, but you'll want to remove the extra `Stripe.framework` instead. This will hopefully be fixed in an upcoming version of Xcode, but we're also investigating workarounds on our end.

**Comment by innomal** [comment]
@davidme-stripe Thanks for workaround however i haven't been able to remove the extra `Stripe.framework` with step mentioned on Firebase issue link. I have added below script on Run Script phase of Build phases and i still get duplicate stripe error when uploading on AppStoreConnect.
```
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/PlugIns/Stripe.framework"
rm -rf "${TARGET_BUILD_DIR}/${TARGET_NAME}.app/Frameworks/Stripe.framework"
```

**Comment by davidme-stripe** [comment]
The Stripe3DS2 dependency is now distributed as source instead of a binary, which should resolve this issue. Please update to version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0).
