### ISSUE TITLE
Can't build with Localizations   zh-Hant.lproj

### ISSUE THREAD

**Issue by KhanhThoNguyen** [stripe/stripe-ios#1706]
## Summary
Can't build with error
Pods/Stripe/Stripe/Resources/Localizations/zh-Hant.lproj: No such file or directory (in target 'Stripe-Stripe' from project 'Pods')
## Installation method
pod 'Stripe'  

## SDK version
pod --version
1.10.0

**Comment by davidme-stripe** [comment]
Hi @KhanhThoNguyen! This sounds like your Cocoapods cache might be corrupt, as the zh-Hant localization definitely exists in our repo. Can you delete the Pods folder, `pod cache clean`, and `pod install` again?
