### ISSUE TITLE
Stripe not allow second payment form same saved card that shown in stripe payment view ... but payment from other card allow 

### ISSUE THREAD

**Issue by NomanUmar** [stripe/stripe-ios#1713]

**Comment by aliriaz-stripe** [comment]
@NomanUmar hello, I don't see any details here, can you add details like your code snippets, screenshots, steps to reproduce, the Stripe-iOS SDK version, etc?

**Comment by NomanUmar** [comment]
1- i can add payment successfully with a card against a stripe customer key 
2- when i select same card against same customer key noting happen but allow payment for other saved card

**Comment by NomanUmar** [comment]
@aliriaz-stripe

**Comment by aliriaz-stripe** [comment]
@NomanUmar Could you give me detailed reproduction steps? The steps above are too concise for me to know how you're integrated. 

You'll have to provide me 

- what UI components you're integrated against (e.g. STPPaymentMethodsViewController, STPPaymentContext, etc)
- what steps I have to take to reproduce 1/ and 2/ above
- what version of the iOS SDK you're using
- copy-paste of your code snippet to show what it is doing after implementing the relevant delegate methods from Stripe's SDK (e.g. didCreatePaymentResult() , etc)

**Comment by NomanUmar** [comment]
paymentContextDidChange not calling if selects the already selected card

let customerContext = STPCustomerContext(keyProvider: StripePayment.stripeClient!)
        let config = STPPaymentConfiguration.shared()
        config.publishableKey = App.Config.stripeKey
        config.companyName = Constants.appName
        config.requiredBillingAddressFields = .none
        config.requiredShippingAddressFields = .none
        let paymentContext = STPPaymentContext(customerContext: customerContext,configuration : config,theme : .default())
        paymentContext.delegate = self
        paymentContext.hostViewController = delegate?.stripeController
        paymentContext.modalPresentationStyle = .fullScreen
        paymentContext.presentPaymentOptionsViewController()

if i can use STPPaymentOptionsViewController then paymentOptionsViewControllerDidFinish called we have no param same as in func paymentContext(_ paymentContext: STPPaymentContext, didCreatePaymentResult paymentResult: STPPaymentResult, completion: @escaping STPPaymentStatusBlock)  so how we made payment

**Comment by aliriaz-stripe** [comment]
@NomanUmar appreciate you sharing this detail!

The STPPaymentContext's `didChange()` delegate method doesn't trigger again if the same card is selected again, as the selected payment method hasn't changed. You can get the existing selected from `paymentContext.selectedPaymentOption` property.

**Comment by NomanUmar** [comment]
Solved by using 
   customerContext = STPCustomerContext(keyProvider: MyAPIClient())
        
        let config = STPPaymentConfiguration.shared()
        config.additionalPaymentOptions = .default
        config.companyName = "App Name"
        config.requiredBillingAddressFields = .none
        config.requiredShippingAddressFields = .none

 let viewController = STPPaymentOptionsViewController(configuration: config,
                                                             theme: .default(),
                                                             customerContext: self.customerContext!,
                                                             delegate: self)
        
        
let navigationController = UINavigationController(rootViewController: viewController)
        present(navigationController, animated: true, completion: nil)




class ViewController :UIViewController,STPPaymentOptionsViewControllerDelegate{

var currentPaymentMethod: STPPaymentOption?

func paymentOptionsViewController(_ paymentOptionsViewController: STPPaymentOptionsViewController, didFailToLoadWithError error: Error) {
        
        self.dismiss(animated: true, completion: nil)
        
    }
    
    func paymentOptionsViewControllerDidFinish(_ paymentOptionsViewController: STPPaymentOptionsViewController) {
        
        
        
        self.dismiss(animated: true, completion: nil)

       var params:STPPaymentMethodParams?
        var paymentStripeId: String?
        if let source = currentPaymentMethod as? STPPaymentMethod {
            paymentStripeId = source.stripeId
        }else if let card = currentPaymentMethod as? STPCard {
            paymentStripeId = card.stripeID
        }
        
        
        if let card = currentPaymentMethod as? STPPaymentMethodParams {
            params = card
        }

apiCall(){

response in 
switch response {
                
                case .success(let clientSecret):
                    // Assemble the PaymentIntent parameters
                    let paymentIntentParams = STPPaymentIntentParams(clientSecret: clientSecret as! String)
                    self.paymentSecret = secret
                    paymentIntentParams.paymentMethodId = paymentStripeId
                    paymentIntentParams.paymentMethodParams = params
                    
                    
                    STPPaymentHandler.shared().confirmPayment(withParams: paymentIntentParams, authenticationContext: self) { status, paymentIntent, error in
                        
                        
                        switch status {
                        case .succeeded:
                            self.jobPostRequest()
                        case .failed:
                            GCD.async(.Main) {
                                self.stopActivity()
                            }
                            self.simpleAlert(title: "", msg: "Stripe Issue")
                        case .canceled:
                            print("Cancel")
                        @unknown default:
                            return
                        }
                    }
                    
                case .failure(let error):
                    self.paymentSecret = ""
                    GCD.async(.Main) {
                        self.stopActivity()
                    }
                    print(error)
                    self.simpleAlert(title: "", msg: "Stripe Issue")     // Report error from your API
                    break
                }


}



}

func paymentOptionsViewController(_ paymentOptionsViewController: STPPaymentOptionsViewController, didSelect paymentOption: STPPaymentOption) {
        self.currentPaymentMethod = paymentOption
    }
    
    
    
    func paymentOptionsViewControllerDidCancel(_ paymentOptionsViewController: STPPaymentOptionsViewController) {
        
        self.dismiss(animated: true, completion: nil)
        
    }

}

@aliriaz-stripe
