### ISSUE TITLE
Initializers aren't public for several types in 21.0.0.

### ISSUE THREAD

**Issue by Andrewangeta** [stripe/stripe-ios#1716]
## Summary
Quite a few initializers aren't marked as `public` in the 21.0.0 release.

` STPBankAccountParams`, `STPCardParams` are the 2 I see in my current project.
Also `STPPaymentCardTextField`'s `delegate` property is also not marked `public`.

## Installation method
SPM

## SDK version
21.0.0

**Comment by davidme-stripe** [comment]
Yikes, thanks so much for filing this. Something went wrong in our API audit, we'll roll our default version back to 20.1.1 while we investigate.

**Comment by davidme-stripe** [comment]
This should be fixed in 21.0.1.
