### ISSUE TITLE
Standard/Basic Integration not allowing addition of Discover cards as payment instruments

### ISSUE THREAD

**Issue by halinebr** [stripe/stripe-ios#1717]
## Summary

Our iOS App uses Standard Integration for Stripe transactions. We've had two different users enter their Discover card and the integration immediately displays the card number as erroneous and does not allow the user to add the payment instrument. I cannot find any logs on the Stripe dashboard that indicate the card is being rejected/not passing some validation, but I do see that a request is being made to some internal API to validate the card that I am assuming the cards are failing? We're able to attach the payment method on our custom integration on Android and via our web client as well and transactions with the card are working as expected. 
Discover Stripe test cards work as expected in Basic Integration...

## Code to reproduce

I did attempt to create a new iOS app with Basic Integration, but it appears that links on this repo's README for instructions and on your documentation site are dead. I added this integration so long ago to my production app that I don't remember how to retrace my steps....

## iOS version

iOS 13.3.1, iOS 13.7.0, also on iOS 14.2 simulator 

## Installation method

Cocoapods

## SDK version

20.1.1.1

**Comment by paulasjes-stripe** [comment]
Hi @halinebr, thanks for filing! 

There was an issue with this SDK version that temporarily caused some Discover cards to fail validation. This has been resolved on our backend, so you won't need to update your SDK to get the fix.

As for the README links, they were unavailable yesterday during the deployment of SDK 21.0.1, but they should be pointing to the new content now.

Feel free to reopen this issue if you are still having difficulty or seeing problems!
