### ISSUE TITLE
Framework size for AppClips

### ISSUE THREAD

**Issue by woodymelling** [stripe/stripe-ios#1719]
Currently when installed through cocoapods, the 21.0.1 framework is above 9MB, and the 20.0.* framework is about 5MB. This makes it almost impossible to include Stripe functionality in an AppClip, where the total uncompressed size of the app needs to be < 10MB. 

Would it be possible to either reduce the size of the main framework, or have a framework that only includes Core functionality that would be required for an appclip, like token creation and Apple Pay? Getting this down to a MB or two would make it much easier to include in an AppClip.

**Comment by davidme-stripe** [comment]
Hi @woodymelling! We're working on a minimal version of the SDK for App Clips, but we don't have a release date to share just yet.

That said, SDK 21.0.1 should have a worst-case size of 3.5MB uncompressed after [App Thinning](https://developer.apple.com/documentation/xcode/reducing_your_app_s_size#//apple_ref/doc/uid/DTS40014195-CH1-MEASURE). Are you seeing larger sizes?

**Comment by woodymelling** [comment]
Hi @davidme-stripe, thanks for the update about a minimal Stripe SDK for App Clips, that's very good news.

I am seeing a 9.2MB Stripe.framework after app thinning when installing version 21.0.1 from cocoapods, however I'm not sure that my process for getting that number is 100% correct.

My process is this:

Archive the app, and distribute it as a "development" build. Select the AppClip, select "All Compatible Device Variants" with "Rebuild from Bitcode" checked. Sign it, and export it to my desktop.

When looking at the App Thinning report, the size of my AppClip is 18.6 MB. To see the size of the Stripe.framework, I go to the .ipa file, rename it as a .zip, unzip it, and the inspect the package contents of the file in the Payload. 

In there, there is a folder with the Stripe.framework in it, which has a size of 9.2 MB, with the executable being 7.1MB.

<img width="637" alt="Screen Shot 2020-11-24 at 10 02 13 AM" src="https://user-images.githubusercontent.com/10538759/100127214-20e92d80-2e3c-11eb-902d-c5376c1ed29c.png">

**Comment by davidme-stripe** [comment]
Hey @woodymelling, sorry it took me so long to get back to you! I managed to reproduce this locally, and I think what's going on is that you're not selecting the "Rebuild from Bitcode" and "Strip Swift symbols" boxes in the export dialog.

![image](https://user-images.githubusercontent.com/52758633/101228375-4baf5f00-3650-11eb-85ea-410db6115d01.png)

When I leave those unchecked in a Cocoapods-built app, I get the results you're seeing, but when I enable them I get the expected 3.5MB size.

But I was wrong on which size Apple uses: They use the uncompressed _universal_ variant of the thinned framework, including resources for all devices. This is actually 5MB, so we'll need to work to shrink this even more.

**Comment by ahmadfs** [comment]
I am running into the same problem and I don't see the option to strip symbols when doing 'App Thinning' process. Any suggestions?

**Comment by davidme-stripe** [comment]
Wanted to give an update here:

* Version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0), released today, shaves off a few hundred KB of image assets.
* You can save an additional ~250KB by removing unused localizations: https://gist.github.com/vinhnx/c39c2da1022f74ee0869
* I'm seeing the best size results when using static frameworks in Swift Package Manager or Cocoapods.
* We're still working on a minimal version of the SDK, but we don't have any updates on when it will be released.

**Comment by leojkwan** [comment]
> * We're still working on a minimal version of the SDK, but we don't have any updates on when it will be released.

Any updates on timeline for this @davidme-stripe ? Thanks- would love to get Stripe working on app clips.

**Comment by DjBalagur** [comment]
Version after 20.1.1 really very large and we use old version. @davidme-stripe you can load to TestFlight app with Stripe version 21.0.1 or 21.2.0 and, for example, several images and Alamofire. We had issue from Apple ITMS-90865: Thinned app clip size is too large. But App Thinning show uncompressed around 3.5MB.

**Comment by NicholasJCameron** [comment]
Version 15.0.3 was only 24M then version 17.0.4 was over 110M what the heck happen there. Good to hear a simplified version coming soon!

**Comment by NicholasJCameron** [comment]
@davidme-stripe  Any updates on this minified version / any other tricks like removing the localization you could suggest

**Comment by NicholasJCameron** [comment]
Any update on this @davidme-stripe  ? Patiently waiting

**Comment by davidme-stripe** [comment]
Hello @NicholasJCameron! There was an update in https://github.com/stripe/stripe-ios/issues/1820#issuecomment-866336502, including a prototype minimal SDK for Cocoapods. If you're encountering other issues with the size of your App Clip, it might help to make sure your target version is iOS 12.2 or later, and that your Swift language is set to 5.0 or later.

We're still working to modularize the SDK. The first part of this, splitting off `StripeCore` (which can't be used on its own), landed in SDK version 21.7.0. From there, we intend to split off Apple Pay support into a separate module for App Clips, and after that we'll do the same with our UI products and API bindings.

We're not ready to share a schedule yet, but we understand that the SDK is too large for some apps, and we definitely want to address that in the near future.

**Comment by NicholasJCameron** [comment]
@davidme-stripe  Awesome David thanks for the response. Appreciate the efforts your team is putting into this. Thanks

**Comment by zac** [comment]
In my testing my App Clip size as reported by Apple in TestFlight went from 12.9MB (when including Stripe 21.4.0) down to 7.32MB. So about 5.6MB solely attributable to Stripe.

That makes it pretty hard to support in a medium to large App Clip, so I too would love to see a minified version to unlock more App Clip use-cases! Thanks for the continued effort on such a high-quality framework 👍

**Comment by davidme-stripe** [comment]
We've added a `StripeApplePay` module to the [latest version of the SDK](https://github.com/stripe/stripe-ios/releases/tag/21.12.0). It adds ~1MB to the uncompressed size of an App Clip.

You can adopt this by following our [Apple Pay integration guide](https://stripe.com/docs/apple-pay). We've also added instructions to help you [migrate an existing STPApplePayContext integration to the new module](https://stripe.com/docs/apple-pay?platform=ios#app-clips).

Sorry for the very long wait! We recognize that SDK size is still a problem, so our next goal is to split [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment) into a separate module.

**Comment by NicholasJCameron** [comment]
Awesome David, well done, great start nonetheless.

Cheers.

**Comment by zac** [comment]
@davidme-stripe Thanks for the update!

I'm seeing our App Clip as 7.87MB before integrating `StripeApplePay` and 10.7MB after. So around 3MB added to the binary size (as Apple calculates it) by adding in `StripeApplePay`. Definitely better than the 5.6MB I noted before, but also (unfortunately for us!) over the limit.

Could I be doing something incorrectly or looking at the wrong numbers? That seems pretty far off what you've seen of 1MB.

**Comment by davidme-stripe** [comment]
@zac Thanks for the report, it definitely shouldn't be 2.37MB! According to our [size reporting script](https://github.com/stripe/stripe-ios/blob/master/Tests/installation_tests/size_test/size_report.rb), StripeApplePay should add 350kb to a compressed .ipa, or 856kb uncompressed.

We're measuring based on the [App Thinning Size Report](https://developer.apple.com/documentation/xcode/reducing-your-app-s-size) from Xcode. As I understand it, Apple uses the uncompressed size of the thinned universal variant. A few ideas:
* Is the binary being built for multiple architectures? I think Xcode will only generate arm64 iOS binaries these days, so this is unlikely.
* Your App Clip should use a target version of iOS 14 or later. If you set it to a much earlier version and don't use other Swift code in your App Clip, adding StripeApplePay may cause Xcode to embed a copy of the Swift standard library.
* Which package manager are you using? It's possible that we missed an issue with some configuration of Cocoapods or Carthage.

**Comment by davidme-stripe** [comment]
The next update will split the Payments SDK into separate modules, allowing to embed only the components you need. More details and a beta link here: https://github.com/stripe/stripe-ios/issues/1820#issuecomment-1279365907

**Comment by davidme-stripe** [comment]
We released this today as [23.0.0](https://github.com/stripe/stripe-ios/releases/tag/23.0.0). We've also posted a [migration guide](https://stripe.com/docs/mobile/ios/sdk-23-migration?lang-ios=swift) with module size information and tips for migrating to the latest version.
