### ISSUE TITLE
In Stripe iOS default Payment Method Selection UIView Controller, How to edit it? Why there is no option that allows user to ask if they want to save the card for future use or no , by default stripe saves the card after first transaction

### ISSUE THREAD

**Issue by saudanwar3** [stripe/stripe-ios#1720]

**Comment by davidme-stripe** [comment]
Hi @saudanwar3, thanks for the feedback! We'll take this into consideration as we make updates to this controller. If you're having trouble using the SDK, I'd recommend reaching out to our support team at https://support.stripe.com/?contact=true.
