### ISSUE TITLE
Redefinition of module 'Stripe3DS2'

### ISSUE THREAD

**Issue by glaures-ioki** [stripe/stripe-ios#1721]
## Summary
I just updated to version 21.0.1 using Carthage. I managed to fix all issues thanks to the migration guide and helpful warnings/error messages. The app is actually running well on the simulator but when I try to run the app on an actual device I get the following error:

![Capture d’écran 2020-11-24 à 11 34 43](https://user-images.githubusercontent.com/65161952/100082907-1719f700-2e49-11eb-96f2-33cf4f9f15a1.png)

I tried the usual stuff: remove derived data, clean Carthage cache, restart Xcode... but still the same 😞

## Code to reproduce
A project importing the SDK using Carthage and running the app on an actual device ?

## iOS version
14.2

## Installation method
Carthage

## SDK version
21.0.1

**Comment by stherold** [comment]
This is already covered by https://github.com/stripe/stripe-ios/issues/1685

**Comment by davidme-stripe** [comment]
Hi @glaures-ioki! I can't reproduce this locally, though I have a speculative fix, I'll send it out soon.

It looks like it's possible that Stripe3DS2 is being included separately in your project somehow: Just to make sure, are you seeing `Stripe3DS2.framework` in your target's `Frameworks, Libraries, and Embedded Content` settings? You should only have `Stripe.framework` there.

**Comment by glaures-ioki** [comment]
Hey David, 

> are you seeing Stripe3DS2.framework in your target's Frameworks, Libraries, and Embedded Content settings? 

No, only `Stripe.framework`.

Maybe it could be related to our project structure: Stripe is imported into a framework which is then imported into the app. But we have been using Stripe for more than two years now and this never caused any issue before.

**Comment by davidme-stripe** [comment]
> Stripe is imported into a framework which is then imported into the app.

Thanks for the info, I think this is the problem! We'll find a way to make this work.

**Comment by kohlab** [comment]
I'm seeing the same same symptoms – runs in the simulator fine, fails when trying to build an Archive for release. I'm using Xcode 12; have cleared DerivedData, caches, and cleaned the project itself; and I have built everything in Carthage with `--no-use-binaries` set.  

Unlike @glaures-ioki, however, I'm only importing Stripe into my main project's files, not any intermediate frameworks. 

The specific errors I'm seeing when building the project are:

```
/Users/dylan/Dev/OurApp/client/Carthage/Build/iOS/Stripe.framework/Modules/module.modulemap:12:8: error: redefinition of module 'Stripe3DS2'
module Stripe3DS2 { }
       ^
/Users/dylan/Library/Caches/org.carthage.CarthageKit/DerivedData/12.1_12A7403/stripe-ios/21.0.1/Build/Intermediates.noindex/ArchiveIntermediates/StripeiOS/BuildProductsPath/Release-iphoneos/include/module.modulemap:1:8: note: previously defined here
module Stripe3DS2 {

```

**Comment by davidme-stripe** [comment]
We're continuing to investigate this. We have a tentative plan to simplify the framework's build process, but it'll take another week or so.

As a workaround, I'd recommend pinning to version 20.1.1, or using Cocoapods/SPM/manual installation instead.

**Comment by ChechkovEugene** [comment]
Confirm this issue, on version 21.1.0

**Comment by davidme-stripe** [comment]
Hello! The Stripe3DS2 dependency is now distributed as source instead of a binary, which should resolve this issue. Please update to version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0).
