### ISSUE TITLE
Missing required module `Stripe3DS2` in Unit Test target

### ISSUE THREAD

**Issue by stasivanov** [stripe/stripe-ios#1723]
## Summary
Building unit test target fails to me with `<unknown>:0: error: missing required module 'Stripe3DS2'`. It only fails with 21.0.1+ version. Works fine on 20.1.1. Also, building a regular target works fine even with 21.0.1 pod version.

## Installation method
Cocoapods v 1.10.0

## SDK version
21.0.1

## Other information
In unit test target in test files, I'm using `@testable import <MyMainModule>`.

**Comment by stasivanov** [comment]
nvm, fixed by adding this to Podfile
```
target 'testTests' do
        inherit! :search_paths
end
```

**Comment by karanayyana** [comment]
I still have this issue with Xcode 12.2
was there anything else that we have to do? podfile change didnt help me
