### ISSUE TITLE
STPPaymentCardTextField background color applies to card number field as well

### ISSUE THREAD

**Issue by ollikas** [stripe/stripe-ios#1727]
## Summary
Setting STPPaymentCardTextField.backgroundColor will apply it to the whole view as well as the number field. This results in number field background being colored twice and colors with transparency will appear in wrong tone.
## Code to reproduce

Upon digging into the STPPaymentCardTextFiled code background var setter has following code
set {
      super.backgroundColor = newValue
      self.numberField.backgroundColor = newValue
    }

## iOS version
iOS 14.2
## Installation method
Cocoapods
## SDK version
21.0.1

**Comment by davidme-stripe** [comment]
Thanks for filing this! We don't currently support colors with transparency in this field, but we'll take a look to see how we could better support this in the future. For now, would it work to pre-mix your intended form background color with the background color behind it, and set that with an alpha of 1.0?

**Comment by davidme-stripe** [comment]
Closing this, as we haven't heard back in a while and don't plan to support colors with transparency.

**Comment by vpontis** [comment]
@davidme-stripe just a note that we would love this feature. We aren't able to premix the color of the input and background because the background is not a single color. 

We managed a workaround for now but it's something that would be nice to have :)
