### ISSUE TITLE
STPPaymentOptionsViewController allows adding duplicate cards

### ISSUE THREAD

**Issue by dhruvsbhatt** [stripe/stripe-ios#1728]
During checkout process, I first use STPPaymentOptionsViewController to add card. But it also allows to save same cards thus making duplicate entries.

## Code to reproduce

self.paymentContext.pushPaymentOptionsViewController()
## iOS version

iOS 14.0

## Installation method

Via cocoapods
## SDK version

Stripe 21.1.0
## Other information

![Screen Shot 2020-12-08 at 6 26 18 PM](https://user-images.githubusercontent.com/2063976/101486581-e4144f00-3982-11eb-9b6c-2ddd7f3e1bcc.png)

**Comment by aliriaz-stripe** [comment]
@dhruvsbhatt hello!

STPPaymentOptionsViewController doesn't de-duplicate any cards by default so this is expected that it will add duplicate cards.

Closing as it isn't a bug in the SDK, please let me know if you have questions/suggestions!

**Comment by dhruvsbhatt** [comment]
@aliriaz-stripe Thanks for confirming, wouldn't it be helpful to provide a way to handle it if STPPaymentOptionsViewController doesn't de-duplicate any cards by default ?
