### ISSUE TITLE
STPCardParams & STPPaymentMethodCardParams

### ISSUE THREAD

**Issue by luktgo** [stripe/stripe-ios#1730]
Hey guys, i'm having an issue with creating creating a payment method.

Seems that I'm doing everything by docs, but after creating a payment method from CardParams, cardholder name is lost.
E.g
```
let cardParams = STPCardParams()
cardParams.number = "4242424242424242"
cardParams.expYear = expYear
cardParams.expMonth = expMonth
cardParams.cvc = cvv
cardParams.currency = Currency.code
cardParams.name = "Luke SKYWALKER"

let paymentParams = STPPaymentMethodCardParams(cardSourceParams: cardParams) 
let paymentMethodParams = STPPaymentMethodParams(card: paymentParams, billingDetails: nil, metadata: nil)

STPAPIClient.shared.createPaymentMethod(with: paymentMethodParams) { paymentMethod, error in 
...
```
I get a successful response, but I already see from the request that cardholder name is missing. In fact I think it gets lost after creating `STPPaymentMethodCardParams` from `STPCardParams`. And I see that `STPPaymentMethodCardParams` doesn't have anything name related.

So I guess my question is how to pass a cardholder name when creating a paymentMethod.
I really hope I am using the SDK correctly, your help would be really appreciated!

I'm testing on Xcode 12.2, iOS14.2, have `Stripe 21.1.0` via SPM.

**Comment by yuki-stripe** [comment]
Hi @luktgo, 

Sorry for the trouble here! Could you point me to the docs you used? 

You're correct, `STPCardParams` is based on an older ("Sources") API and does not fully 'convert' into an `STPPaymentMethodCardParams` - everything besides the 4 card properties in your example.

Instead, you'll want to:
- create a separate `STPPaymentMethodBillingDetails` object to store details like the name.
- Set the currency value on the `PaymentIntent` API object you need to create on the backend.

```
let cardParams = STPPaymentMethodCardParams()
cardParams.number = "4242424242424242"
cardParams.cvc = "123"
cardParams.expMonth = NSNumber(value: 12)
cardParams.expYear = NSNumber(value: 24)

let billingDetails = STPPaymentMethodBillingDetails()
billingDetails.name = "Luke"

let paymentMethodParams =  STPPaymentMethodParams(card: cardParams, billingDetails: billingDetails, metadata: nil)
```

I recommend following https://stripe.com/docs/payments/accept-a-payment#ios as a guide.

**Comment by luktgo** [comment]
Could be my bad, i think i've combined logic from here:
https://stripe.com/docs/mobile/ios/sources
and here
https://stripe.com/docs/payments/accept-a-payment-synchronously

Since I'm not using cardTextField and have UI fields of my own.

Also I do found a line somewhere in the docs that said, "Note that cardHolder name should not be included in metadata, but rather in CardParams “name” field." So I rejected the BillingDetails on that point.

Anyway, thank you very much and happy holidays!
