### ISSUE TITLE
Infinite loop on small screen device when STPPaymentCardTextField.cvcPlaceholder is long

### ISSUE THREAD

**Issue by rocketnik** [stripe/stripe-ios#1731]
Tested on
Device iPhone SE 1st Gen, iOS 13.5.1
Simulator iPhone SE 1st Gen, iOS 13.4

It is possible to create an infinite loop on the main thread resulting in app not responding.

Steps to reproduce:
- create an STPPaymentCardTextField (e.g. via interface builder)
- make the leading/trailing distance to the screen 15pt each
- set the STPPaymentCardTextField.cvcPlaceholder to something long (e.g. "Kreditkartenprüfnummer")
- Run the app
- Enter 4242 4242 4242 4242 424 242

The app will go into an infinite loop.
It does not happen, if the cvcPlaceholder is set to "CVC" - maybe it could happen, if the STPPaymentCardTextField was smaller.

## Installation method
cocoapods

## SDK version
21.1.0

**Comment by rocketnik** [comment]
App haning

![IMG_0009](https://user-images.githubusercontent.com/8329809/102014058-640c3180-3d54-11eb-84f4-607a6ebddf8e.PNG)

**Comment by rocketnik** [comment]
Instruments showing a lot of cpu cycles

<img width="1396" alt="Screen Shot 2020-12-12 at 22 40 47" src="https://user-images.githubusercontent.com/8329809/102014100-8ef68580-3d54-11eb-9a96-217a4ee4feda.png">
<img width="1396" alt="Screen Shot 2020-12-12 at 22 40 57" src="https://user-images.githubusercontent.com/8329809/102014106-91f17600-3d54-11eb-876b-3fe035e3cf32.png">

**Comment by yuki-stripe** [comment]
Hi @rocketnik,

Thanks for the thorough report - looks like this was introduced in v21.0.0.  I have a fix that will be in the next release

**Comment by davidme-stripe** [comment]
Sorry for the delay! This should be fixed in version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0).
