### ISSUE TITLE
Unresolved external in react-native project using stripe-ios

### ISSUE THREAD

**Issue by djMax** [stripe/stripe-ios#1732]
## Summary
While trying to compile a project using react-native and SDK version 21.1.0, I get this error:

Undefined symbols for architecture x86_64:
  "(extension in Foundation):__C.NSScanner.scanUpToString(Swift.String) -> Swift.String?", referenced from:
      static Stripe.STPPhoneNumberValidator.formattedRedactedPhoneNumber(for: Swift.String, forCountryCode: Swift.String?) -> Swift.String in libStripe.a(STPPhoneNumberValidator.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Code to reproduce
I have not produced a standalone test yet, but it seems this happens on a vanilla RN project.

## iOS version
13, 14

## Installation method
CocoaPods

## SDK version
21.1.0

## Other information
I am trying to use the Stripe SDK from a swift file in a react-native app, which is likely somehow related.

**Comment by djMax** [comment]
Any thoughts on this one, or things you'd like me to do to follow up? If I modify this code in STPPhoneNumberValidator:

```
    if #available(iOS 13.0, *) {
      prefix = scanner.scanUpToString("*") as NSString?
    } else {
      #if !TARGET_OS_MACCATALYST
      scanner.scanUpTo("*", into: &prefix)
      #endif
    }
```

to essentially remove the use of scapUpToString, it compiles and functions.

```
    if #available(iOS 13.0, *) {
      scanner.scanUpTo("*", into: &prefix)
    } else {
      #if !TARGET_OS_MACCATALYST
      scanner.scanUpTo("*", into: &prefix)
      #endif
    }
```

It really does seem like it SHOULD work as is, and perhaps is somehow related to ios version targets (I've tried setting them but that didn't help, but I know there are 50 places it might belong).

**Comment by djMax** [comment]
This seems to be the issue, though I can't claim to understand it.

https://github.com/react-native-community/upgrade-support/issues/62#issuecomment-622985723

**Comment by davidme-stripe** [comment]
Thanks for the detailed report! From the linked issue, it looks like React Native may be compiling against the wrong version of the Swift standard library. I'll investigate.

**Comment by davidme-stripe** [comment]
I still can't reproduce this locally, but it seems like the linked workaround of removing `"\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\""` from the `LIBRARY_SEARCH_PATHS` build configuration setting is working.

**Comment by jp928** [comment]
@davidme-stripe 
I removed all entries in LIBRARY_SEARCH_PATHS

then react-native-linear-gradient failed in build.

Library not found for -lBVLinearGradient

**Comment by davidme-stripe** [comment]
I believe React Native has fixed this on their end — they shouldn't be specifying Swift 5.0 on newer versions of Xcode.
