### ISSUE TITLE
No such module 'Stripe3DS2'

### ISSUE THREAD

**Issue by dathu7728** [stripe/stripe-ios#1734]
## Other information

No such module [['Stripe3DS2']]
![Screen Shot 2020-12-16 at 12 53 32 PM](https://user-images.githubusercontent.com/15993908/102317601-d02da600-3f9d-11eb-85a1-4d8b950b33d1.png)

**Comment by davidme-stripe** [comment]
Hi @dathu7728, thanks for filing! What version of Cocoapods are you running? The latest version of the framework requires Cocoapods 1.10, which was released relatively recently.

**Comment by dathu7728** [comment]
now running 1.8.4, ok will update Cocoapods 1.10. Thank you.

**Comment by davidme-stripe** [comment]
The Stripe3DS2 dependency is now distributed as source instead of a binary, which should resolve this issue. Please update to version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0).

**Comment by robertodaviduk** [comment]
Same issue here

I made a custom Swift package and I need to implement some features from Stripe..

On my case I add this to my Package.swift

.package(url: "https://github.com/stripe/stripe-ios.git", from: "21.9.0")

And I am getting the next error:

<img width="1271" alt="Captura de Pantalla 2021-11-11 a la(s) 10 59 12" src="https://user-images.githubusercontent.com/25305761/141310734-8b48f2d0-1c79-475c-b4a2-186f76e2ab0d.png">

**Comment by csabol-stripe** [comment]
Hi @robertodaviduk, have you also declared Stripe as a product dependency for your target? Your Package.swift should look like this
```
import PackageDescription

let package = Package(
    name: "StripeDependentPackage",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "StripeDependentPackage",
            targets: ["StripeDependentPackage"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(name: "Stripe", url: "https://github.com/stripe/stripe-ios.git", from: "21.9.0")
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "StripeDependentPackage",
            dependencies: [.product(name: "Stripe", package: "Stripe")]),
        .testTarget(
            name: "StripeDependentPackageTests",
            dependencies: ["StripeDependentPackage"]),
    ]
)
```

**Comment by mevdev** [comment]
Where do I get this Stripe3DS2?

I just added the Swift Package and added "import Stripe" and it hits me with:
`Missing required module 'Stripe3DS2'`

Can you point me to Stripe2DS2?

**Comment by yuki-stripe** [comment]
Hello @mevdev, Stripe3DS2 is in the repo [here](https://github.com/stripe/stripe-ios/tree/master/Stripe3DS2) and defined as a dependency of the Stripe module [here](https://github.com/stripe/stripe-ios/blob/ef0c465f84402af07565d637ffb5952d3d2cc37b/Package.swift#L35-L53).

**Comment by mevdev** [comment]
Thanks @yuki-stripe. So that means that I should not be getting that error simply by adding the line:
`import Stripe`?
<img width="684" alt="Screen Shot 2022-07-12 at 10 12 11 AM" src="https://user-images.githubusercontent.com/2013678/178552316-4f0fd63e-ce5e-46bc-bb09-245774e45546.png">

<img width="673" alt="Screen Shot 2022-07-12 at 10 12 25 AM" src="https://user-images.githubusercontent.com/2013678/178552372-cce2dc16-c3a0-464d-9ba0-d160d53fd9a7.png">

**Comment by joshuakcockrell** [comment]
### For import via Package.swift file 

This was occurring for me because I forgot to add it as a dependency of the target

<img width="704" alt="swift pm stripe" src="https://github.com/stripe/stripe-ios/assets/8979400/baa1c550-5e66-46e0-9f5a-87a087a3390e">
