### ISSUE TITLE
!Urgent! Stripe3DS2.xcframework.zip not found

### ISSUE THREAD

**Issue by KevinTMiller** [stripe/stripe-ios#1735]
## Summary
Unable to build due to missing framework

## iOS version
All

## Installation method
SPM and Cocoapods

## SDK version
Tested versions affected: 20.0.0, 21.0.0, 21.1.0

## Other information
Unable to compile / build our project with stripe-ios dependency due to this issue. It looks like the framework is no longer hosted at the url listed in the Package.swift: https://github.com/stripe-ios/stripe-3ds2-ios-releases/releases/download/v21.0.0/Stripe3DS2.xcframework.zip

**Comment by FrancoisObob** [comment]
CC: @yuki-stripe, we are currently experiencing the same issue. 

otherwise thanks for the great work on the repo 💪

**Comment by davidme-stripe** [comment]
Hello, sorry for the trouble! This is a known issue with 20.0.0: You should be able to use version [20.1.1](https://github.com/stripe/stripe-ios/releases/tag/20.1.1) with Swift Package Manager, which is otherwise identical to 20.0.0. You can also upgrade to the latest version, [21.1.0](https://github.com/stripe/stripe-ios/releases/tag/21.1.0).

**Comment by FrancoisObob** [comment]
Hi @davidme-stripe, thanks for the quick answer.

Just tested both versions, both ended up with the same error:

![image](https://user-images.githubusercontent.com/5428399/102636242-67236b00-4122-11eb-99f7-b829398a0cab.png)

**Comment by davidme-stripe** [comment]
Hi, sorry about that! Try 20.0.0 again, we fixed the issue on our end.

**Comment by davidme-stripe** [comment]
As for the issue with `framework not found Stripe3DS2` on 21.1.0, we're receiving reports of that from some integrations but can't reproduce them locally using Cocoapods or SPM. We're going to simplify our distribution of the SDK soon, which should eliminate those issues.

**Comment by FrancoisObob** [comment]
Confirmed: 20.0.0 on SPM work fine now!, thanks!

**Comment by FrancoisObob** [comment]
@davidme-stripe and I confirmed that 21.0.0 and 21.1.0 still got the issue.

**Comment by davidme-stripe** [comment]
Actually, have you tried updating Cocoapods? The latest version of the framework requires Cocoapods 1.10, which was released relatively recently.

**Comment by FrancoisObob** [comment]
We do not use Cocoapods but Swift Package Manager.

**Comment by davidme-stripe** [comment]
The Stripe3DS2 dependency is now distributed as source instead of a binary, which should resolve this issue. Please update to version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0).
