### ISSUE TITLE
Support for Brazilian Installments 

### ISSUE THREAD

**Issue by carlosdelamora** [stripe/stripe-ios#1736]
## Summary
I am requesting a new feature to support Brazilian credit cards installment plan payments. Its a lost business opportunity to not include this form of payment given that almost no one in Brazil will buy something that does not use installments. Read for example what Stripe competitors say about that (Adyen)[https://www.adyen.com/knowledge-hub/guides/global-payment-methods-guide/local-payment-methods-in-latin-america/brazil-payments#how] 
"Card use in Brazil is relatively high and Brazilians rarely pay for anything outright. Most online transactions are paid in installments. "

Note that proposed solutions like subscriptions or charging the card multiple times on a schedule is not the correct solution. I would like to receive the full amount of the product I sold and is the credit card business or the creditor the one who will take the risk of not getting pay in full.

**Comment by davidme-stripe** [comment]
Hello, thanks for the request! This page is only for issues related to the Stripe iOS SDK — if you'd like support for installments in Brazil, I'd recommend asking at https://support.stripe.com/ or emailing support@stripe.com. They should be able to help you out!

**Comment by GREENVTECH** [comment]
Any update to support Brazilian installment?

**Comment by gugiserman** [comment]
any news on this? 😭

**Comment by dnet5** [comment]
They held a beta about 2 years ago with that. But then it was abandoned. A shame. They are integrating a lot of BNPL (buy now, pay later) solutions. But Brazil's installments are precisely the same, but without a third party like Klarna of Afterpay.

After more than 4 years in Brazil, it's more than time to deliver that.
