### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by AnmolRattan007** [stripe/stripe-ios#1737]
Error at STPCardValidationState/possibleBrands/brands = binRanges.map(\.brand)

**Comment by davidme-stripe** [comment]
Hello, thanks for filing! This may be a dupe of https://github.com/stripe/stripe-ios/issues/1724, which we're still investigating. Are you using Flutter?

**Comment by AnmolRattan007** [comment]
@davidme-stripe I'm using Swift. Also, can I implement Stripe with a lower version like  '20.1.1'?

**Comment by davidme-stripe** [comment]
I can't reproduce this, but I made a speculative fix in version [21.2.0](https://github.com/stripe/stripe-ios/releases/tag/21.2.0). Please give it a try!
