### ISSUE TITLE
Swipe back gesture from STPPaymentOptionsViewController doesn't reset STPPaymentContext state property

### ISSUE THREAD

**Issue by akaraatanasov** [stripe/stripe-ios#1742]
## Summary

When closing a Payment Options screen (this happens only when it's pushed) by swiping from left to right (swipe back gesture), the Payment Options screen cannot be pushed again. When closing the screen by tapping the "Cancel" button everything works as expected.

## Steps to reproduce:
1. Push Payment Options screen by calling `paymentContext.pushPaymentOptionsViewController()`.
2. Close the Payment Options screen, but instead of tapping Cancel, swipe back to the previous screen.
3. The Payment Options screen cannot be pushed anymore.

## iOS version
Device: iPhone XS, iOS 14.2
Simulator: iPhone 11, iOS 14.3

## Installation method
SPM

## SDK version
21.1.0

## Other information

After reading `STPPaymentContext` and `STPPaymentOptionsViewController`, I think the issue may be that when swiping back, `paymentOptionsViewControllerDidCancel()`is never called and the `appropriatelyDismiss` completion handler in `STPPaymentContext`, which resets the payment context `state` property to `.none`, is never executed. Therefore, next time the user tries to push again the controller, the `state == STPPaymentContextState.none` check fails and nothing gets pushed.

**Comment by yuki-stripe** [comment]
Hi @akaraatanasov,

Thanks for the report, we're tracking this internally.

**Comment by davidme-stripe** [comment]
Closing this, as we're not investing development effort into STPPaymentOptionsViewController at this time. We'd recommend switching to [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet), our modern prebuilt payment UI.
