### ISSUE TITLE
Error while building Stripe3DS2 in Carthage

### ISSUE THREAD

**Issue by kohlab** [stripe/stripe-ios#1743]
## Summary
As per a [previous issue (#1721)](https://github.com/stripe/stripe-ios/issues/1721), I'm rebuilding Stripe iOS with Carthage. When it gets to Stripe3DS2, the following prints:

```
*** Building scheme "StripeiOS" in Stripe.xcworkspace
*** Building scheme "Stripe3DS2" in Stripe.xcworkspace
*** Skipped building SwiftCLI due to the error:
Dependency "SwiftCLI" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Udumft/SwiftCLI/issues/new
```

## Code to reproduce
Insert this line in your Carthage file:

`github "stripe/stripe-ios" ~> 21.2
`

Then do `carthage update --platform iOS --no-use-binaries --use-netrc`

## iOS version
14.2

## Installation method
Carthage

## SDK version
21.2.0

**Comment by davidme-stripe** [comment]
Hey @kohlab, I don't think anything on our end imports `SwiftCLI`. It sounds like one of the other dependencies in your Cartfile may be importing it, and the error for it is showing up before the other dependency's name. Can you share your complete Cartfile?

**Comment by kohlab** [comment]
I thought I'd only changed the Stripe versions, but yes, in hindsight that could well be.

```
github "hackiftekhar/IQKeyboardManager" ~> 6.0
github "Alamofire/Alamofire" ~> 5.2
github "jdg/MBProgressHUD" ~> 1.1.0
github "patchthecode/JTAppleCalendar" ~> 8.0
github "marmelroy/PhoneNumberKit" ~> 3.1
github "kizitonwose/CountryPickerView" ~> 3.1
github "MessageKit/MessageKit" ~> 3.4
github "MessageKit/MessageInputBar" ~> 0.4
github "stripe/stripe-ios" ~> 21.2
github "facebook/facebook-ios-sdk" ~> 8.2
github "mapbox/MapboxGeocoder.swift" ~> 0.13
github "mapbox/mapbox-navigation-ios" ~> 1.1
```

**Comment by davidme-stripe** [comment]
This looks like the culprit: [mapbox-navigation-ios](https://github.com/mapbox/mapbox-navigation-ios/blob/master/Cartfile) imports [mapbox-directions-swift](https://github.com/mapbox/mapbox-directions-swift/blob/main/Cartfile), which imports SwiftCLI. It might work to just remove `--platform iOS` from your `carthage update` command, which would allow it to build for non-iOS platforms.

**Comment by kohlab** [comment]
Thanks!
