### ISSUE TITLE
"Done" button is invisible when entering characters in "Postal" field

### ISSUE THREAD

**Issue by ChechkovEugene** [stripe/stripe-ios#1744]
## Summary
On the Card details entering screen when i entering any character in the Postal field "Done" button disappears. When delete all from Postal code - button appears again. It seems that button is enabled but invisible. Because if i tap on the space where button should be - it's working.
It seems that is only for the first card If i'm adding details for the second card all is fine. Button "Done" is visible all the time

## Steps to reproduce
In the video

## iOS version
iPhone 8, iOS 14.3

## Installation method
Manual installation

## SDK version
21.1.0

https://user-images.githubusercontent.com/2751087/103878373-04990b80-50df-11eb-993e-c5a5a2e90f27.MP4

**Comment by yuki-stripe** [comment]
Hi @ChechkovEugene,

Thanks for the report, we're tracking this internally.

**Comment by ChechkovEugene** [comment]
Closing an issue. Found a problem on our internal NavigationController
