### ISSUE TITLE
Card scanner does not support localisation of NSCameraUsageDescription 

### ISSUE THREAD

**Issue by glaures-ioki** [stripe/stripe-ios#1745]
## Summary
Even after enabling card scanning on an iOS 14.3 device, the feature is not available. This is due to the way `cardScanningAvailableCameraHasUsageDescription` is implemented: it only looks for `NSCameraUsageDescription` in `Bundle.main.infoDictionary`. 

`Bundle.main.localizedInfoDictionary` should be checked too.

## Code to reproduce
Any project using a localised `info.plist` file instead of having `NSCameraUsageDescription` hardcoded in `info.plist`.

## iOS version
14.3

## Installation method
Carthage

## SDK version
21.2.0

**Comment by davidme-stripe** [comment]
Hi @glaures-ioki! Sorry about that, we'll fix this and release an update soon.

**Comment by davidme-stripe** [comment]
This was fixed in [21.2.1](https://github.com/stripe/stripe-ios/releases/tag/21.2.1).
