### ISSUE TITLE
XCode 12.3 (12C33) Carthage build using --use-xcframeworks fails with Could not find module 'Stripe' for target 'armv7-apple-ios'

### ISSUE THREAD

**Issue by bogdancochioras** [stripe/stripe-ios#1747]
## Summary
I tried building the framework using the new soon to be released --use-xcframeworks parameter for Carthrage, see pull request https://github.com/Carthage/Carthage/pull/3106 which should allow building xcframeworks for XCode 12.3 which i'm using. Other frameworks that i'm using don't have this issue.

After building the xcframeworks I have the following issue in XCode: Could not find module 'Stripe' for target 'armv7-apple-ios'; found: arm64, arm64-apple-ios. Both 

## Code to reproduce
carthage update stripe-ios --platform ios --use-xcframeworks

Output: 
*** Checking out stripe-ios at "21.2.0"
*** xcodebuild output can be found in /var/folders/hb/dgq2l0lj5pg33bqb1_hy8sr00000gr/T/carthage-xcodebuild.FbHTWb.log
*** Downloading stripe-ios.framework binary at "Version 21.2.0"
*** Building scheme "StripeiOS" in Stripe.xcworkspace
*** Building scheme "Stripe3DS2" in Stripe.xcworkspace

## iOS version
12.4.3

## Installation method
Carthage 0.37.0 from pull request https://github.com/Carthage/Carthage/pull/3106 and make install locally

## SDK version
21.2.0

**Comment by davidme-stripe** [comment]
Hello, thanks for filing this! It looks like Xcode is looking for a `armv7-apple-ios` slice in the `.xcframework`, which shouldn't be built in an app targeting iOS 11. Is your app targeting iOS 10? The current version of the Stripe SDK only supports iOS 11 or later.

**Comment by CochiorasBogdan** [comment]
@david-stripe Yes the issue was that I was targeting iOS 10 and I saw support was dropped. I reverted to v19.4.0 which supports iOS 10 and there were no more issues. So my bad that I missed the iOS 10 note from the README. This can be closed. Thank you!
