### ISSUE TITLE
wrong code on validationStateForExpiration()

### ISSUE THREAD

**Issue by iKorich** [stripe/stripe-ios#1748]
## Summary
there are no way to get incomplete error code

## Code to reproduce
fill card number only and validate a card, 
month/year is empty = invalid, month empty = invalid, year is empty = invalid, invalid date = invalid

## iOS version
14.0

## Installation method
cocoapods

## SDK version
ios 21.2.0

**Comment by davidme-stripe** [comment]
Hi @iKorich! Could you share the code you're using to validate a card? I'm seeing `.incomplete` when calling `STPCardValidator.validationState(forExpirationYear:inMonth:)` with incomplete values.

**Comment by davidme-stripe** [comment]
Closing this out for now, but let me know if you're still experiencing the issue.
