### ISSUE TITLE
Received unknown parameter: client_secret

### ISSUE THREAD

**Issue by poorvasingh04** [stripe/stripe-ios#1754]
## Summary
I have integrate Stripe sdk as per iOS documentation available here - https://stripe.com/docs/mobile/ios/basic
But when I am requesting payment at the end. It returns error- 
`Error Domain=com.stripe.lib Code=50 "Received unknown parameter: client_secret" UserInfo={com.stripe.lib:StripeErrorCodeKey=parameter_unknown, com.stripe.lib:StripeErrorTypeKey=invalid_request_error, NSLocalizedDescription=Received unknown parameter: client_secret, com.stripe.lib:ErrorParameterKey=clientSecret, com.stripe.lib:ErrorMessageKey=Received unknown parameter: client_secret}`

## Code to reproduce
https://stripe.com/docs/mobile/ios/basic

## iOS version
14.0

## Installation method
Cocoapod

## SDK version
21.2.0

## Other information
I am just using AddCardViewController to add the card and then requesting the payment with client_secret received from paymentIntent. I am not using Shipping address. I don't need it. I am testing with my test keys and I have correctly configured the test key both in AppDelegate and in server while initializing Stripe (and they both match as well).

**Comment by davidme-stripe** [comment]
It sounds like you might be trying to confirm the payment with your publishable key: Your `pk_test` publishable key should go in your client, and the `sk_test` secret key should go on the server.

**Comment by poorvasingh04** [comment]
@davidme-stripe Thanks for clearing this. I was using sk_test secret key for both client and server. Now it works for me.

**Comment by 50gramx** [comment]
> Hi @poorvasingh04! It sounds like you might be trying to confirm the payment with your publishable key: Your `pk_test` publishable key should go in your client, and the `sk_test` secret key should go on the server.

Your comment helped. Documentation can be improved. Thanks.

**Comment by MaheshRathod4** [comment]
> Hi @poorvasingh04! It sounds like you might be trying to confirm the payment with your publishable key: Your `pk_test` publishable key should go in your client, and the `sk_test` secret key should go on the server.

This is worked for me. Thank you very much you saved my day.
