### ISSUE TITLE
'STPCardParams' cannot be constructed because it has no accessible initializers - v21.2.1

### ISSUE THREAD

**Issue by RazvanMaris** [stripe/stripe-ios#1756]
## Summary

I am encountering the following compile-time issue when trying to create an STPCardParams object:
'STPCardParams' cannot be constructed because it has no accessible initializers

LE#1: after integrating Stripe in a new dummy project, STPCardParams interface contained a constructor and instantiating a STPCardParams worked ok.
So currently I am looking for some guidance on why this is happening in my 'working' project.

LE#2: I've also integrated manually the xcframeworks found in one of the threads in this github repo. This way I've managed to see the interface of STPCardParams as it should be (i.e. having a constructor) but when trying to initialize the object, I still get the same "cannot be constructed" error.

## Code to reproduce

let cardParams = STPCardParams()
## iOS version

iOS 13.2, Xcode 12.3

## Installation method

Installed via Carthage 0.37 using --use-xcframeworks flag.

## SDK version

Stripe v21.2.1

## Other information

When command-clicking STPCardParams, the interface looks like:

` @objc public class STPCardParams : NSObject, NSCopying {

    /// The card's number.
    @objc public var number: String?

    /// The last 4 digits of the card's number, if it's been set, otherwise nil.
    @objc public func last4() -> String?

    /// The card's expiration month.
    @objc public var expMonth: UInt

    /// The card's expiration year.
    @objc public var expYear: UInt

    /// The card's security code, found on the back.
    @objc public var cvc: String?

    /// The cardholder's name.
    /// @note Changing this property will also changing the name of the
    /// param's `address` property.
    @objc public var name: String?

    /// The cardholder's address.
    /// @note Setting `address` to a new value will also change the `name` property to
    /// be the value of `address.name`. However, changing `address.name` directly will
    ///not* change `name`.
    @objc public var address: Stripe.STPAddress

    /// Three-letter ISO currency code representing the currency paid out to the bank
    /// account. This is only applicable when tokenizing debit cards to issue payouts
    /// to managed accounts. You should not set it otherwise. The card can then be
    /// used as a transfer destination for funds in this currency.
    @objc public var currency: String?

    /// The first line of the cardholder's address
    @objc public var addressLine1: String?

    /// The second line of the cardholder's address
    @objc public var addressLine2: String?

    /// The city of the cardholder's address
    @objc public var addressCity: String?

    /// The state of the cardholder's address
    @objc public var addressState: String?

    /// The country of the cardholder's address
    @objc public var addressCountry: String?

    /// :nodoc:
    @objc override dynamic public var description: String { get }

    /// :nodoc:
    @objc public func copy(with zone: NSZone? = nil) -> Any
} `

**Comment by RazvanMaris** [comment]
LE#3: I've integrated manually the xcframeworks downloaded from v21.2.1 release page (https://github.com/stripe/stripe-ios/releases/tag/21.2.1) and finally when calling the constructor of STPCardParams there was no compile-time issue.

**Comment by csabol-stripe** [comment]
@RazvanMaris there are some known issues with Carthage (we have a fix that we'll include with the next release), but I've not seen this particular issue. Is it possible that the Cartfile or Cartfile.resolved are pointing to a different version?

We did see errors like this in Version 21.0.0, but we quickly unshipped that version to address them

**Comment by davidme-stripe** [comment]
Closing this for now, let us know if you're still experiencing this issue.
