### ISSUE TITLE
UnionPay marked as invalid on iOS

### ISSUE THREAD

**Issue by sumitmundra** [stripe/stripe-ios#1759]
When entering a UnionPay card number (e.g 6200000000000005) on iOS the form mark it as invalid where on Android it is marked as valid

STPPaymentCardTextField().isValid Give invalid 

SDK version : 21.2.1

![Simulator Screen Shot - iPhone 8 - 2021-02-04 at 14 44 09](https://user-images.githubusercontent.com/4879986/106870759-7ae95780-66f7-11eb-82dc-5e93f6c72301.png)

## iOS version

iOS 13 and iOS 14

## Installation method

cocoapods

## SDK version
 SDK version : 21.2.1

**Comment by csabol-stripe** [comment]
Thanks for the report @sumitmundra. This behavior should be specific to Stripe's test cards which are handled differently than live cards, but I have a fix for this that we'll include in the next release. In the meantime if you are interested in testing 19 digit UnionPay card support you can try `6205500000000000004`

**Comment by cythb** [comment]
@csabol-stripe  Hi, I have the same problem. Now is there a way for me to test the 16 digit UnionPay card?

**Comment by cythb** [comment]
I use this card to test `6205500000000000004`, but I got this error:[](error)
![Xnip2021-02-10_15-25-44](https://user-images.githubusercontent.com/1787428/107478389-5c320780-6bb4-11eb-91db-07f1c8829acb.jpg)

**Comment by csabol-stripe** [comment]
Ah my fault @cythb I forgot that the test card number I shared above isn't enabled for all accounts :\ I'll look into finding a test card number that should work but this may have to wait until our next release

**Comment by davidme-stripe** [comment]
This is fixed in [21.3.0](https://github.com/stripe/stripe-ios/releases/tag/21.3.0).
