### ISSUE TITLE
Stripe Apple Pay crash due to format does not match expected client secret

### ISSUE THREAD

**Issue by UmerAfzal1** [stripe/stripe-ios#1760]
I'm following this https://stripe.com/docs/apple-pay
Also upload certificate on stripe portal and using test key then i tapped apple pay button show dialog and tapped "Pay with Passcode" and start loading after some time crashed app and showing error in debug section "Assertion failed: secret format does not match expected client secret formatting.: file Stripe/STPAPIClient.swift, line 593". "

## Summary
 While using stripe apple pay when i make payment then app crash and showing error "Assertion failed: secret format does not match expected client secret formatting.: file Stripe/STPAPIClient.swift, line 593".

## Code to reproduce
let paymentRequest = StripeAPI.paymentRequest(withMerchantIdentifier: STPPaymentConfiguration.shared.appleMerchantIdentifier!, country: "US", currency: "USD")

    paymentRequest.paymentSummaryItems = [
        PKPaymentSummaryItem(label: "iTem 1", amount: NSDecimalNumber(value: 10.0))),
    ]
    
    // Initialize an STPApplePayContext instance
    if let applePayContext = STPApplePayContext(paymentRequest: paymentRequest, delegate: self) {
        // Present Apple Pay payment sheet
        applePayContext.presentApplePay(on: self)
    }
    else{
        // There is a problem with your Apple Pay configuration
        let alert = self.showAlert(withTitle: "Error", andMessage:"Unable to make Apple Pay transaction.", completion: self.alertAction)
        self.present(alert, animated: true)
        } 

## iOS version
14.2

## Installation method
Cocoapods 

## SDK version
21.2.1

**Comment by jacobsapps** [comment]
Bumping as I'm having the exact same problem

**Comment by jacobsapps** [comment]
@UmerAfzal1  how did you solve it?
