### ISSUE TITLE
Card number, cvv, expiry, and all billing address details validation before add card by STPAddCardViewController

### ISSUE THREAD

**Issue by tnpaul** [stripe/stripe-ios#1762]
## Summary

I am using STPAddCardViewController for adding a card in Stripe. Since I wanted to show my own customised "Done" button instead of Stripe's "rightBarButtonItem" Done button so I added STPAddCardViewController as a child view controller in my own ViewController and transferred my "Done" button action to Stripe's "rightBarButtonItem" Done button by following code

```
private var stripeDefaultVC: STPAddCardViewController!
    
var doneNavigationBarButton: UIBarButtonItem? {
      return stripeDefaultVC.navigationItem.rightBarButtonItem
}

@objc func tapDone() {
      if let selector = doneNavigationBarButton?.action {
          stripeDefaultVC.perform(selector, with: doneNavigationBarButton)
      }
}

```

Now when I tap my "Done" button, it actually calls Stripe's "rightBarButtonItem" Done button action. But now I have lost the Stripe's default functionality of enabling/disabling "Done" button based on filling required fields. Since user can tap on my Done button now any time (because it will always be enabled) so the API call from the SDK is made and user is shown an error message which comes from Stripe's server which I can not control.

## Question/Feature Request 
Does Stripe SDK have any mechanism built in, which can provide validation for each field (including card number, cvv, expiry, and all billing address details) so that I can check for validation in my "Done" button action. If it does not, then I would like to request for this feature so that user can be shown a meaningful and localised message or even enable/disable the customised "Done" button based on validation.

## iOS version
14.4

## Installation method
Cocopods

## SDK version
21.2.1

**Comment by davidme-stripe** [comment]
Hi @tnpaul! We're in the process of [rebuilding this UI](https://stripe.com/docs/mobile/payments-ui-beta), so we're not likely to support replacing the `Done` button in this way. Would our new UI work for your use case? If not, it might be better to build your own custom UIViewController using STPPaymentCardTextField or the new SwiftUI equivalent.

**Comment by tnpaul** [comment]
@davidme-stripe Thank you for the reply. Could you please let me know if using STPPaymentCardTextField will remain PCI compliant because we can read the card number from the STPPaymentCardTextField and can be printed in the console as well. 

If using STPPaymentCardTextField is fine in terms of PCI compliant then could you please provide any documentation for the same to show people in my company.

**Comment by davidme-stripe** [comment]
I'd recommend sending them the [Mobile SDK section of our integration security guide](https://stripe.com/docs/security/guide). If you pass the `STPPaymentMethodCardParams` or `STPPaymentMethodParams` from `STPPaymentCardTextField` to `STPAPIClient.shared.createPaymentMethod()` as shown in our integration guides, you can inform your PCI auditor that card numbers pass directly from your customers to Stripe. You shouldn't access the raw card number, as that may make you responsible for additional PCI DSS requirements.

**Comment by tnpaul** [comment]
Thank you for the clarification. Closing the issue.
