### ISSUE TITLE
'new' is unavailable: You cannot directly instantiate an STPToken. You should only use one that has been returned from an STPAPIClient callback.

### ISSUE THREAD

**Issue by Nattatech** [stripe/stripe-ios#1764]
## Summary
Getting this error at build time in Xcode 12.5 beta 2
'new' is unavailable: You cannot directly instantiate an STPToken. You should only use one that has been returned from an STPAPIClient callback.

## Code to reproduce
Error on STPAPIClient.m file of Stripe SDK

## iOS version
iOS 14.5

## Installation method
pod install

## SDK version
Stripe (14.0.1)
But I also tested with latest sdk version but getting same issue

## Other information
I try many sdk versions but not getting any change in error. It's same

**Comment by davidme-stripe** [comment]
Hi @Nattatech, thanks for filing!

* Can you share the code for what you're attempting to do? It sounds like you're trying to create an STPToken on the client side, but you should instead create one via STPAPIClient.
* If you're not creating an STPToken correctly, is it possible that you've accidentally included STPAPIClient.m into your own app's target? Cocoapods should build it as a Pod, and you should only encounter that error if you're trying to create an STPToken directly.

**Comment by davidme-stripe** [comment]
@Nattatech, can you update to version 21.3.0? I'm not seeing this issue in that version. We'll work on a solution for older versions.

**Comment by davidme-stripe** [comment]
We've released [14.0.2](https://github.com/stripe/stripe-ios/releases/tag/v14.0.2), [15.0.3](https://github.com/stripe/stripe-ios/releases/tag/v15.0.3), and [17.0.4](https://github.com/stripe/stripe-ios/releases/tag/v17.0.4) to resolve this. But please upgrade to 21.3.0 if you can!

**Comment by joshbuhler** [comment]
@davidme-stripe - I'm also seeing this issue in Stripe 21.3.1, using Xcode 12.5 beta 3. I'm adding Stripe via Carthage (`carthage update --use-submodules --no-build`). My app builds with no problems in Xcode 12.4, but 12.5 beta 3 generates the following errors:

```
.../Carthage/Checkouts/stripe-ios/Stripe/STPAPIClient.m:556:62: 'new' is unavailable: You cannot directly instantiate an STPSource. You should only use one that has been returned from an STPAPIClient callback.
.../Carthage/Checkouts/stripe-ios/Stripe/STPAPIClient.m:580:68: 'new' is unavailable: You cannot directly instantiate an STPSource. You should only use one that has been returned from an STPAPIClient callback.
.../Carthage/Checkouts/stripe-ios/Stripe/STPAPIClient.m:646:68: 'new' is unavailable: You cannot directly instantiate an STPCard. You should only use one that has been returned from an STPAPIClient callback.
.../Carthage/Checkouts/stripe-ios/Stripe/STPAPIClient.m:646:85: 'new' is unavailable: You cannot directly instantiate an STPSource. You should only use one that has been returned from an STPAPIClient callback.
.../Carthage/Checkouts/stripe-ios/Stripe/STPAPIClient.m:782:75: 'new' is unavailable: You cannot directly instantiate an STPPaymentIntent. You should only use one that has been returned from an STPAPIClient callback.
.../Carthage/Checkouts/stripe-ios/Stripe/STPAPIClient.m:821:76: 'new' is unavailable: You cannot directly instantiate an STPPaymentIntent. You should only use one that has been returned from an STPAPIClient callback.
.../Carthage/Checkouts/stripe-ios/Stripe/STPAPIClient.m:833:76: 'new' is unavailable: You cannot directly instantiate an STPPaymentIntent. You should only use one that has been returned from an STPAPIClient callback.
```

**Comment by davidme-stripe** [comment]
@joshbuhler Stripe 21.3.1 is written in Swift, so it shouldn't have the `STPAPIClient.m` file referenced in that error. Can you delete your Carthage folder and retry?

**Comment by joshbuhler** [comment]
@davidme-stripe - I tried that, and didn't have much success there either. I did manage to get my app building using SPM to import though, with some issues. I've written those up here: https://github.com/stripe/stripe-ios/issues/1772

**Comment by totodot** [comment]
@davidme-stripe Hi could you update v19.4.0 to work with xcode 12.5?

**Comment by davidme-stripe** [comment]
@totodot v19.4.1 should work with Xcode 12.5.

**Comment by clifflinmao** [comment]
I'm using Xcode 12.5, when I upgrade Stripe to 23.1.0, but getting this error from Stripe:

![image](https://user-images.githubusercontent.com/57075803/117522902-867e4000-afbe-11eb-9db9-0a7a41ba7be5.png)
