### ISSUE TITLE
STPPaymentHandler.shared().handleNextAction can return status == .failed but no handleActionError

### ISSUE THREAD

**Issue by mvarie** [stripe/stripe-ios#1769]
## Summary
Sometimes, when using `STPPaymentHandler.shared().handleNextAction` with test card `4000 0000 0000 3063` which requires 3DS, the completion block is called with a seemingly inconsistent set of parameters:
- `status == .failed`
- `paymentIntent ==` populated and seemingly normal
- `handleActionError == nil`

It is unclear at this stage why the `status` is `.failed`, as no error object is offered.

## Code to reproduce
I have been unable to identify a situation where this can be consistently reproduced.

My best guess is that cases that return an empty error `handleActionError == nil`, but a _seemingly_ valid and populated `paymentIntent`, and a `.failure`status, pass by this line:

https://github.com/stripe/stripe-ios/blob/73306f38a5c5e9c3706c0abd27b619e8b99edb6e/Stripe/STPPaymentHandler.swift#L555

.. but it's kind of a wild guess. 

## iOS version
14.4 , on physical device (iPhone 8)

## Installation method
Swift Package Manager

## SDK version
21.3.1

## Other information
I wish I had more information to offer - I'll keep on monitoring these calls and see if I can find out more.

**Comment by csabol-stripe** [comment]
@mvarie thanks for the report, I'll see if I can find anything that looks suspicious here. If you manage to reproduce, could you look at the status of the returned PaymentIntent?

**Comment by mvarie** [comment]
@csabol-stripe the issue originates where your code checks if `authenticationPresentingViewController` can be presented on – in the two cases where it can't, you set `canPresent = false`, and then set an error message string, `errorMessage = 
         "error message..."`.

However, you then check `if !canPresent && error != nil { .. `  and unfortunately `error` is nil; the `errorMessage` string never makes it to the caller and it's lost.

I was sometimes asking your sdk to present on a controller that was already presenting (my bad) but I never got the error message - that's why I was confused and trying to find a problem with the payment flow. 

https://github.com/stripe/stripe-ios/blob/73306f38a5c5e9c3706c0abd27b619e8b99edb6e/Stripe/STPPaymentHandler.swift#L1158-L1195

Thanks!

**Comment by csabol-stripe** [comment]
Thanks for the followup @mvarie! I've got a fix that we'll include in the next release so these errors are reported

**Comment by davidme-stripe** [comment]
This should be fixed in [21.4.0](https://github.com/stripe/stripe-ios/releases/tag/21.4.0).
