### ISSUE TITLE
Could not find module 'Stripe' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by jmgawecki** [stripe/stripe-ios#1771]
## Summary
Hey guys, I am having that issue:
Could not find module 'Stripe' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

I run my project on Silicon Macbook Pro.

Thanks for any help.
## iOS version
iOS 14.3

## Installation method
Cocoa pods intallation

## SDK version
 - Stripe (21.0.0-mc-beta-1):
 - Stripe/Stripe3DS2 (= 21.0.0-mc-beta-1)
 - Stripe/Stripe3DS2 (21.0.0-mc-beta-1)

**Comment by Moriquendi** [comment]
+1

**Comment by davidme-stripe** [comment]
Hi @jmgawecki, two ideas here:

* Are you pointed to the `mc-beta-2` branch? The `mc-beta-1` branch is using an older version of Stripe3DS2, which could be causing issues.
* Do you have "Build Active Architecture Only" set to `NO` for your app but `YES` for your Cocoapods or Stripe target? If so, you may be building your app for `x86_64` and  `arm64`, but building your pods for only `arm64`, so the final `x86_64` linking step will fail. If this is the case, you might want to set "Build Active Architecture Only" to `YES` for your app (to disable `x86_64` everywhere), or add this to your Podfile to always build both architectures:
```
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
```

Hope this helps!

**Comment by davidme-stripe** [comment]
Let us know if you're still experiencing this. We've released PaymentSheet as part of `21.5.0`, so you can move away from the `mc-beta-2` branch.

**Comment by Moriquendi** [comment]
@davidme-stripe I still can't build the app on the simulator - same error.
I have CocoaPods in the project but I added Stripe with the Swift Package Manager.
As far as I can say, all targets in my project have `Build Active Architecture Only` set to `YES` for debug builds. 🤷‍♂️

**Comment by davidme-stripe** [comment]
@Moriquendi From this error, it sounds like Xcode is trying to build Stripe for the arm64 iOS simulator, but it's trying to run it using the x86_64 simulator. Are you running Xcode in Rosetta? (You can check this from the "Get Info" pane on Xcode.app in Finder.) Do any of your other dependencies generate x86_64 binaries?

**Comment by Moriquendi** [comment]
@davidme-stripe I checked and neither Xcode nor Simulator is run in Rosetta. I'll investigate dependencies tomorrow to see if any of them might be causing problems.

**Comment by robm92** [comment]
Having the same issue:
`could not find module 'Stripe' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: ~/Library/Developer/Xcode/DerivedData/XXXXXX/Build/Products/Debug-iphonesimulator/Stripe.swiftmodule`

Xcode 13.4
Stripe 22.5.1 - tried both Cocoapods and SPM
Cleaned project, removed derived data, restarted Xcode.

**Comment by robm92** [comment]
My issue was related to implementing workarounds for the GoogleCast framework which didn't support M1 until recently.
I am now building without issues.
