### ISSUE TITLE
Xcode 12.5b3 - Unable to build when treating warnings as errors.

### ISSUE THREAD

**Issue by joshbuhler** [stripe/stripe-ios#1772]
If a project has the "Treat Warnings as Errors" build setting set to "Yes", Stripe will prevent a project from building in Xcode 12.5 beta 3.

Note: This is related to a closed issue [I logged previously.](https://github.com/stripe/stripe-ios/issues/1770)

## Summary
If a project as the "Treat Warnings as Errors" build setting set to "Yes", Stripe will prevent a project from building in Xcode 12.5 beta 3. This setting does not prevent apps from building with Stripe added in Xcode 12.4, but it will break in 12.5. To test this, you will need a project that was created in Xcode 12.4 or older, then re-opened in 12.5.

This setting will result in multiple `error: umbrella header for module 'Stripe3DS2' does not include header '<header_name>.h'` errors.

## Code to reproduce
A sample project that demos this issue is here: https://github.com/joshbuhler/stripeBuildError

## iOS version
iOS 14.0. Also able to reproduce when a deployment target is set to iOS 13.0

## Installation method
Swift Package Manager

## SDK version
21.3.1

**Comment by joshbuhler** [comment]
I have disabled the warnings as errors setting in our project for now, but we prefer to leave it enabled.

**Comment by davidme-stripe** [comment]
Hi, thanks for filing this! We've identified a fix and will release an update soon.

**Comment by davidme-stripe** [comment]
This should be fixed in [21.4.0](https://github.com/stripe/stripe-ios/releases/tag/21.4.0).

**Comment by joshbuhler** [comment]
Just validated that this does work in my project with warnings as errors enabled when using 21.4.0. Thanks folks.
