### ISSUE TITLE
didCreatePaymentResult Not called after add card detail

### ISSUE THREAD

**Issue by cnfuzedRk62** [stripe/stripe-ios#1773]
Hey team,
I am facing issue on your latest stripe sdk ios.
my Xcode version:- 12.0.1
iOS version:- 14.4

Here is my code snippet:-

let customerContext = STPCustomerContext(keyProvider: MyAPIClient())
var paymentContext : STPPaymentContext!

After hitting my local server api to get client secrate key i trigger this method

 DispatchQueue.main.async {
                        self.setupPayment()
                        self.paymentContext.requestPayment()
                        self.paymentContext.presentPaymentOptionsViewController()
     }

    func setupPayment(){
        let config = STPPaymentConfiguration.shared
        config.requiredBillingAddressFields = .none
        let paymentContext = STPPaymentContext(customerContext: self.customerContext,configuration: config, theme: .defaultTheme)
        paymentContext.paymentAmount = 50
        paymentContext.paymentCurrency = "usd"
        self.paymentContext = paymentContext
        self.paymentContext.delegate = self
        self.paymentContext.hostViewController = self
    }

Please help me if there is anything wrong in it.

**Comment by yuki-stripe** [comment]
Hi @cnfuzedRk62,

Nothing looks obviously wrong with your code to me. Please email support@stripe.com and link this issue, they're better suited to help you!  I'm tagging @shengwei-stripe as well.
