### ISSUE TITLE
swift package manager download hangs

### ISSUE THREAD

**Issue by leojkwan** [stripe/stripe-ios#1780]
I am on Xcode 12.4. When attempting to import Stripe via 'https://github.com/stripe/stripe-ios.git', and selecting "next major" or setting the branch to 'master', Xcode gets stuck 'resolving "stripe-iOS"'

Any instructions for SPM installation? Thanks.

**Comment by davidme-stripe** [comment]
Hi @leojkwan, thanks for filing this! Is Xcode outputting anything useful to the Console app?

It's also usually very slow to resolve, so you may just need to wait a bit longer for it to finish fetching the package.

**Comment by leojkwan** [comment]
@davidme-stripe thanks! It automagically worked today! I swear I let SPM wait for an hour with no resolve, but perhaps the issue was more SPM related.
