### ISSUE TITLE
Library not loaded: @rpath/Stripe.framework/Stripe

### ISSUE THREAD

**Issue by luckymehndiratta** [stripe/stripe-ios#1781]
As we are going to integrate Stripe in our project using Pod after install the Pod we are facing this issue please update us how we proceed with this and App Crash

**Comment by davidme-stripe** [comment]
Hi @luckymehndiratta, thanks for filing this. It sounds like the Stripe binary isn't building, or the binary is being built for the wrong architecture, or the binary isn't being copied to the `.app` bundle properly. Could you look through your build logs to see if there's a failure when building Stripe? It might also help to share your Podfile configuration. Thanks!

**Comment by luckymehndiratta** [comment]
![Screenshot 2021-03-24 at 10 14 30 PM](https://user-images.githubusercontent.com/58592267/112348945-502a8100-8cee-11eb-9cc1-247f13e163b3.png)

**Comment by luckymehndiratta** [comment]
This is my Podfile and If you have a good time to connect we can connect also and look into this together over the call and fixed this as soon as possible

**Comment by davidme-stripe** [comment]
Thanks for posting your Podfile! I don't see any obvious issues there, so the problem might be somewhere else in your integration. This might be easiest to debug over a call or chat: You can use https://support.stripe.com/contact/ to set that up.

**Comment by luckymehndiratta** [comment]
Sure I am going to setup the call.

Yes its a better to connect to understand all the things

**Comment by luckymehndiratta** [comment]
So Should I remove the podfile image from this chat?

**Comment by davidme-stripe** [comment]
You can if you'd like. I'll close this issue for now — our support team should be able to help you out!

**Comment by luckymehndiratta** [comment]
Sure
