### ISSUE TITLE
[mc-beta-2] SwiftUI assertion (presentingViewController is already presenting a view controller)

### ISSUE THREAD

**Issue by Moriquendi** [stripe/stripe-ios#1782]
## Summary
When using Stripe `mc-beta-2` in SwiftUI, I hit an assertion:
`assertionFailure("presentingViewController is already presenting a view controller")`
I believe it's a bug in how Stripe chooses a UIViewController responsible for presenting Stripe's UI.

## Code to reproduce
The assertion is hit when tapping a PaymentButton.
```
aymentSheet.PaymentButton(paymentSheet: paymentSheet, onCompletion: { ... } ) {
   Text("Pay now")
}
```
However, It is also related to the specific hierarchy of UIViewControllers in the app. Ours is quite unique.
More details below.

## iOS version
iOS 14.4.1

## Installation method
Swift Package

## SDK version
`mc-beta-2`

---

I believe this line is wrong:
https://github.com/stripe/stripe-ios/blob/afeb50345446f889ca4cc076299ff6e4143e222d/Stripe/PaymentSheet%2BSwiftUI.swift#L235
Specifically, it assumes that `presentedViewController` of `rootViewController` does not present any other modals which doesn't have to be true.
I think Stripe should be choosing the last presented UIViewController. So this line could be replaced with this code:

```
while (presentingViewController?.presentedViewController != nil) {
   presentingViewController = presentingViewController?.presentedViewController
}
```

**Comment by marius-se** [comment]
We have the same issue. Did you find any workaround @Moriquendi?

**Comment by Moriquendi** [comment]
@marius-se I just forked the repo and fixed that myself (the way I mentioned it in the issue description). 
Looking forward for the Stripe Team to fix it here 🙃

**Comment by marius-se** [comment]
Ah okay! Many thanks for the quick reply 🙏🏼 @Moriquendi ++

**Comment by yuki-stripe** [comment]
Sorry for the delay here. We've pushed this fix to the `mc-beta-2` branch, thank you for raising this!
