### ISSUE TITLE
Bug + Feature Request: STPAddCardViewController NavigationBar 

### ISSUE THREAD

**Issue by farhad-ris** [stripe/stripe-ios#1787]
![simulator_screenshot_0D7F0B2B-90DC-4740-8530-544B7D4F19E2](https://user-images.githubusercontent.com/2425335/113670957-151a4b80-96f9-11eb-839a-2e6aa2d037df.png)

## Summary
* The STPAddCardViewController NavigationBar title and buttons are not correctly customised also 
* more customisation on Nav title and buttons are needed. specially allowing us to add icons for those buttons

## Code to reproduce

     static var theme: STPTheme {
          let theme = STPTheme()
          theme.accentColor = UIColor.theme.payment.addCard.accentColor
          theme.primaryBackgroundColor = UIColor.theme.payment.addCard.primaryBackgroundColor
          theme.primaryForegroundColor = UIColor.theme.payment.addCard.primaryForegroundColor
          theme.secondaryBackgroundColor = UIColor.theme.payment.addCard.secondaryBackgroundColor
          theme.secondaryForegroundColor = UIColor.theme.payment.addCard.secondaryForegroundColor
          theme.errorColor = UIColor.theme.payment.addCard.errorColor
          theme.font = UIFont.markOffc(size: 14, weight: .bold)
          theme.emphasisFont = UIFont.ttTrailers(size: 32)
          return theme
      }

## iOS version
All

## Installation method & SDK version
  pod 'Stripe', '~> 21'
  - Stripe (21.3.1):
    - Stripe/Stripe3DS2 (= 21.3.1)

## Other information
We need to have more customisation parameters added to STPTheme for STPAddCardViewController, which allows different font and colour to be set for Nav title and buttons explicitly as well as being able to choose to use our own button icons instead.
These would be optional and revert back to default configuration if null or undefined.

**Comment by yuki-stripe** [comment]
Hi @farhad-ris,

Could you try using https://developer.apple.com/documentation/uikit/uiappearance to customize the navigation bar?

For example:
```
UIBarButtonItem.appearance(
  whenContainedInInstancesOf: [STPAddCardViewController.self]
).setTitleTextAttributes(
  [
      NSAttributedString.Key.font: /* your font */,
      NSAttributedString.Key.foregroundColor: /* your color */,
  ],
  for: .normal
)
```

**Comment by farhad-ris** [comment]
Thanks @yuki-stripe 🙂 can you please provide a working example with changed nav buttons' icons or fonts?

**Comment by davidme-stripe** [comment]
Sorry, but we don't intend to add support for custom icons to this UI. If you're interested in creating a custom payment form, it would be better to use `STPPaymentCardTextField`. If you'd like a more modern UI, we've added a new [Payments UI beta](https://stripe.com/docs/mobile/payments-ui-beta) to SDK version 21.5.0.
