### ISSUE TITLE
Question: Is it possible to add cards which require 3DS2 when using built in UI?

### ISSUE THREAD

**Issue by Ariandr** [stripe/stripe-ios#1789]
## Summary
Our application supports 3D Secure, we switched to Payment Intents API on mobile and backend and our payment flow is tested against all challenge flows with test cards: https://stripe.com/docs/payments/3d-secure#three-ds-cards

But the issue that many users are starting to face is that they cannot add a new card in the first place using your built in UI. It happens in Italy (because it's our target country). They need to confirm the card attachment by doing 3D Secure authentication, but the built in flow doesn't let them do it. And the card is declined.

We use this built in flow:
<img width="222" alt="Screenshot at Apr 14 11-24-28" src="https://user-images.githubusercontent.com/13591333/114678581-0b55a100-9d14-11eb-89e3-551e9beb813d.png">

## Code to reproduce
```
self.paymentContext = STPPaymentContext(customerContext: customerContext, configuration: configuration, theme: STPTheme.defaultTheme)
self.paymentContext.delegate = self
self.paymentContext.hostViewController = self
...
// Later
self.paymentContext.presentPaymentOptionsViewController()
```

## iOS version
14.4.2

## Installation method
Cocoapods

## SDK version
21.4

## Question
As I understand, we need to use Setup Intents to attach payment methods to customers instead of using built in UI? This will let cards be authenticated by users.

For that, we must build our own UI and cannot use any built in controllers, am I right?

<img width="284" alt="Screenshot at Apr 14 11-14-28" src="https://user-images.githubusercontent.com/13591333/114679480-dac23700-9d14-11eb-9663-e3e796413dbc.png">

Thanks in advance!

**Comment by davidme-stripe** [comment]
Hello! STPPaymentContext *does* support 3DS2 authentication, though it only supports PaymentIntents, not SetupIntents. We're working on adding support for SetupIntents to our [new UI product](https://stripe.com/docs/mobile/payments-ui-beta), but we don't have a release date set for that yet.

[Here is an example for how to use SetupIntents with 3DS2 confirmation](https://github.com/stripe-samples/mobile-saving-card-without-payment/blob/master/client/ios/App%20(Swift)/CheckoutViewController.swift). To use it with the UI in your screenshot, you'd want to use [STPPaymentOptionsViewController](https://stripe.dev/stripe-ios/docs/Classes/STPPaymentOptionsViewController.html) directly, and when `addCardViewController(_:,didCreatePaymentMethod:,completion:)` is called on your delegate, you can create and confirm a SetupIntent with that `PaymentMethod` and store the card to a customer. We'd like this to be more ergonomic, so we're planning to offer an easier path for this in our new Payments UI.

**Comment by Ariandr** [comment]
@davidme-stripe 
Thanks for guidance!

**Comment by Ariandr** [comment]
@davidme-stripe 
Sorry, I recalled one important detail and have a following question.

At the moment, the payment method is not even created for customers, the creation is declined, as far as I understand. In the banking application users get a transaction for 0 Euro (some kind of verification), and after that the card is declined.

<img width="1095" alt="Screenshot at Apr 14 21-00-00" src="https://user-images.githubusercontent.com/13591333/114757359-6dd68d80-9d64-11eb-9ce7-ad874825210e.png">

And according to this code, a SetupIntent is created not with an existing payment method, but with payment method params (before payment method creation).

So, probably the usage of `STPPaymentOptionsViewController` won't help :(

Do I understand it correctly?

**Comment by davidme-stripe** [comment]
I don't think PaymentMethod creation should trigger a 3DS2 challenge, only SetupIntent/PaymentIntent confirmation. But I might be missing something here, and it could be a bug on our end. Could you email me the ID (not the client secret) for an impacted SetupIntent or PaymentIntent to `davidme@stripe.com`? I can try to investigate what's going on.

**Comment by davidme-stripe** [comment]
Sorry, I just realized I misread your comment. You can create a SetupIntent with an existing PaymentMethod, just assign the `setupIntentParams.paymentMethodID` instead of the `setupIntentParams.paymentMethodParams`.

**Comment by Ariandr** [comment]
@davidme-stripe 
Well, actually that seems to be a problem. After Italy was forced to enforce SCA regulations (from April 1, 2021), a lot of people cannot add their cards as payment methods, they receive decline codes. We cannot understand why it happens. But it seems like some banks want to trigger some kind of validation and it doesn't go through.

I asked about SetupIntents to understand if it can solve the problem, but the initial problem is that we started seeing both inability to add cards as payment methods and some issues with 3DS2, even though in test mode and with test cards all challenge flows work perfectly.

I will send you more data to the email you specified, thanks a lot.
We were trying to understand the issue for several days without a result :(

**Comment by Ariandr** [comment]
@davidme-stripe 
I sent more details to you by email. Thanks!

**Comment by Ariandr** [comment]
The issue I described in email is happening to many users and it seems to be growing :(

**Comment by davidme-stripe** [comment]
We believe we've made improvements to resolve this on the 3DS2 service side, but we'd also recommend adopting [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet), our modern UI for SetupIntents.
