### ISSUE TITLE
Does Stripe Offer pay-pal as one of the payment methods 

### ISSUE THREAD

**Issue by kamarshad** [stripe/stripe-ios#179]
Hello @jflinter 

I am integrating stripe iOS sdk in my iOS application.
I want to give user pay-pal as one of the payment methods.
Is it possible in stripe to use pay-pal as one of the payment method.

Please help me

**Comment by jflinter** [comment]
No, we don't support PayPal integration. If you have further questions, feel free to reach out to support@stripe.com .
