### ISSUE TITLE
STPPaymentCardTextField IBOutlet crash with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by adrgrondin** [stripe/stripe-ios#1790]
## Summary

We have a `STPPaymentCardTextField` in a simple view controller that now crash the app with `Thread 1: EXC_BAD_ACCESS (code=2, address=0x281b00d64)` after upgrading the SDK to 21.4.0 (coming from 20.1.1) when pushing the view controller. Everything was working before and it does not seems that the way STPPaymentCardTextField works changed. No changes have been made to our view controller and both `Stripe.xcframework` and `Stripe3DS2.xcframework` are embedded.
The crash appear when the `delegate` is accessed but it will also crash for any property accessed. Removing these lines correctly push the view controller.

The console also log `[Storyboard] Unknown class STPPaymentCardTextField in Interface Builder file.`.

## Code to reproduce

```swift
  @IBOutlet private weak var paymentCardTextField: STPPaymentCardTextField! {
    didSet {
      paymentCardTextField.delegate = self //Thread 1: EXC_BAD_ACCESS (code=2, address=0x281b00d64)
      paymentCardTextField.postalCodeEntryEnabled = false
    }
  }
```

## iOS version

iOS 14.4.2

## Installation method

Carthage with XCFrameworks

## SDK version

21.4.0

## Other information

Recreating the setup on a single view controller app produce the same crash.

**Comment by davidme-stripe** [comment]
Hi, thanks for filing this! I think this might be an Interface Builder issue. Can you go into Interface Builder, click the STPPaymentCardTextField, then in the `Custom Class` pane on the right:
1. Change it from `STPPaymentCardTextField` to `UIView`.
2. Set it *back* to `STPPaymentCardTextField`.
3. Set the `Module` to `Stripe`.

In the end, it will look like this:
![image](https://user-images.githubusercontent.com/52758633/114744517-a2b1f880-9d02-11eb-87c8-5afbb2a83e29.png)

Let me know if this helps. Thanks!

**Comment by adrgrondin** [comment]
Thanks @davidme-stripe. This fixed it I also first thought it was an Interface Builder configuration issue but everything I tried failed. The weird thing is that I had to manually write `Stripe` into `Module`, IB didn't detect it.

![Capture d’écran 2021-04-15 à 12 29 18](https://user-images.githubusercontent.com/25119343/114855828-a8810a00-9de6-11eb-83d0-47633769dd50.jpg)

**Comment by Zaidkhattak** [comment]
> Hi, thanks for filing this! I think this might be an Interface Builder issue. Can you go into Interface Builder, click the STPPaymentCardTextField, then in the `Custom Class` pane on the right:
> 
> 1. Change it from `STPPaymentCardTextField` to `UIView`.
> 2. Set it _back_ to `STPPaymentCardTextField`.
> 3. Set the `Module` to `Stripe`.
> 
> In the end, it will look like this:
> ![image](https://user-images.githubusercontent.com/52758633/114744517-a2b1f880-9d02-11eb-87c8-5afbb2a83e29.png)
> 
> Let me know if this helps. Thanks!

yes bro, you save my days... thanks a lot for sharing this

**Comment by jesusClubSpark** [comment]
I had this issue when upgrading Stripe to 23.2.0
The Interface builder Module has been updated to **StripePaymentsUI**
