### ISSUE TITLE
[iOS push provisioning] check if card is already added

### ISSUE THREAD

**Issue by furaiev** [stripe/stripe-ios#1791]
Is it possible to check if a Stripe card has been added to Apple Wallet?

I managed to add a card from the app to Apple Wallet but can't check if it is added in order to show/hide the `Add to Apple Wallet` button.
`passes()` from `PKPassLibrary` doesn't return any available pass for the app.

I believe this happens due to missing an association between the app and added card.
Does Stripe SDK creates this association and send it to Apple during card provisioning (`associatedApplicationIdentifiers`)?

**Comment by yuki-stripe** [comment]
Hi @furaiev,

Unfortunately I don't believe we do this today - I would recommend writing in to support@stripe.com with this request.

**Comment by furaiev** [comment]
@yuki-stripe thank you,
So currently we don't have a possibility to check if the card is added to the wallet, correct?

**Comment by davidme-stripe** [comment]
Hello @furaiev! This *should* work by calling `passes()` on a `PKPassLibrary`. If it isn't working, please email push-provisioning-requests@stripe.com with:

* Your app's Team ID prefix (usually something like `2A23JCNE5E`)
* Your App ID (`2A23JCNE5E.com.companyname.myapp`)
* Your ADAM ID. (`128374743`) This is available on App Store Connect or in the App Store link to your app. (https://apps.apple.com/app/id128374743)

Once we make the change on our backend, your users will need to delete and re-add the card for the pass to appear in `passes()`. You'll know your app is linked correctly if a link to your app appears in the card's detail page in Wallet.
