### ISSUE TITLE
ErrorMessageKey=authenticationPresentingViewController is not in the window hierarchy. You should probably return the top-most view controller instead

### ISSUE THREAD

**Issue by murdeee** [stripe/stripe-ios#1793]
## Summary
STPPaymentHandler.shared().confirmPayment fails to show 3ds webView if STPAddCardViewController is pushed

## Code to reproduce
push STPAddCardViewController and try to call STPPaymentHandler.shared().confirmPayment with 4000 0027 6000 3184 test card

## iOS version
iOS 12+

## Installation method
cocoa pods

## SDK version
'21.4.0'

## Other information
STPPaymentHandler.shared().confirmPayment fails with "required action"
 temp fix is to pop STPAddCardViewController before call  "confirmPayment"

Printing description of error:
▿ Optional<NSError>
  - some : Error Domain=STPPaymentHandlerErrorDomain Code=7 "There was an unexpected error -- try again in a few seconds" UserInfo={NSLocalizedDescription=There was an unexpected error -- try again in a few seconds, com.stripe.lib:ErrorMessageKey=authenticationPresentingViewController is not in the window hierarchy. You should probably return the top-most view controller instead.}

**Comment by davidme-stripe** [comment]
You'll need to select the presented STPAddCardViewController as your authentication view controller. But I'd recommend instead adopting our new [Payments UI beta](https://stripe.com/docs/mobile/payments-ui-beta) in SDK version 21.5.0, which offers inline 3DS2 challenges.

**Comment by murdeee** [comment]
> You'll need to select the presented STPAddCardViewController as your authentication view controller. But I'd recommend instead adopting our new [Payments UI beta](https://stripe.com/docs/mobile/payments-ui-beta) in SDK version 21.5.0, which offers inline 3DS2 challenges.

Thanks for the reply!
