### ISSUE TITLE
When is 19.4.1 due on Cocoapods?

### ISSUE THREAD

**Issue by benomatis** [stripe/stripe-ios#1795]
Trying to upgrade to 19.4.1 to benefit from the Xcode 12.5 compatibility issue fix in #1766, but it doesn't appear to be available [on Cocoapods](https://cocoapods.org/pods/Stripe#changelog) yet (I hope it's 'yet'). Will it become available and if so, is there an ETA?

For everyone else reading this, unless you absolutely need Xcode 12.5, you may downgrade to 12.4 as a temporary workaround.

**Comment by s-ahmad88** [comment]
I am facing the same issue. Is there any ETA ?

**Comment by mclark4386** [comment]
Same! I've made a PR for the flutter package to use this, but it's not there yet ;_; Blocking an update for us at the moment: https://github.com/jonasbark/flutter_stripe_payment/pull/286

**Comment by benomatis** [comment]
@mclark4386 If this is blocking an update, I suggest downgrading Xcode to 12.4 in the interim unless you absolutely need 12.5 for some reason.

**Comment by mclark4386** [comment]
> @mclark4386 If this is blocking an update, I suggest downgrading Xcode to 12.4 in the interim, unless you absolutely need 12.5 for some reason.
> 
> Not ideal, but definitely a surer solution than having to wait for a yet unknown amount of time...

Only took an hour^^ Knew that comment was coming^^

**Comment by benomatis** [comment]
> Only took an hour^^ Knew that comment was coming^^

sorry, you never know what is helpful to others, so I thought I'm just going to make sure, in case you didn't think of this option, hope you don't mind ;)

**Comment by chaesung** [comment]
Well according #1767, it ain't coming....@mclark4386 would it be possible to move up more and change the min iOS version to 11?

**Comment by benomatis** [comment]
@chaesung My problem is a 3rd party plugin ([tipsi-stripe](https://github.com/tipsi/tipsi-stripe)), which I have to use because Stripe's own React Native library is not ready yet, and tipsi-stripe only appears to play well with version 19, if I upgrade to 21 I am facing compatibility issues.

**Comment by mclark4386** [comment]
> Well according #1767, it ain't coming....@mclark4386 would it be possible to move up to version 21.3.1 and change the min iOS version to 11?

There was a bit more to do than just move to iOS11, but that was the move I made, so hopefully it's stable and we(flutter_stripe_payments) can move forward with it^^

**Comment by davidme-stripe** [comment]
I applied a hack that will allow 19.4.1 to work with Cocoapods. Note that it will prevent you from building on Apple Silicon, and we'd still recommend that you update to 21.4.0 instead. Please give it a try and let me know if you have any issues.

**Comment by benomatis** [comment]
@davidme-stripe I'm part of the internal testing program of stripe-react-native, so I decided to try that instead, and until then I'll just keep on using Xcode 12.4
