### ISSUE TITLE
STPPaymentOptionsViewController loading forever

### ISSUE THREAD

**Issue by jhjones9** [stripe/stripe-ios#1796]
## Summary
STPPaymentOptionsViewController is hanging forever when trying to present it. I'm using 21.4.0. 

## Code to reproduce
`struct PaymentOptionsView: UIViewControllerRepresentable {
    
    @Environment(\.presentationMode) private var presentationMode
    
    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }
    
    class Coordinator: NSObject, STPPaymentOptionsViewControllerDelegate {
        
        var control: PaymentOptionsView
        
        init(_ control: PaymentOptionsView) {
            self.control = control
        }
        
        func paymentOptionsViewController(_ paymentOptionsViewController: STPPaymentOptionsViewController, didFailToLoadWithError error: Error) {
            
        }
        
        func paymentOptionsViewControllerDidFinish(_ paymentOptionsViewController: STPPaymentOptionsViewController) {
            
        }
        
        func paymentOptionsViewControllerDidCancel(_ paymentOptionsViewController: STPPaymentOptionsViewController) {
            
        }
    }
    
    func makeUIViewController(context: UIViewControllerRepresentableContext<PaymentOptionsView>) -> STPPaymentOptionsViewController {
        let config = STPPaymentConfiguration()
        config.requiredBillingAddressFields = .full
        config.canDeletePaymentOptions = true
                
        let customerContext = STPCustomerContext(keyProvider: StripeAPIClient())
        
        let vc = STPPaymentOptionsViewController(configuration: config, theme: STPTheme.defaultTheme, customerContext: customerContext, delegate: context.coordinator)
        
        return vc
    }
    
    func updateUIViewController(_ uiViewController: STPPaymentOptionsViewController, context: UIViewControllerRepresentableContext<PaymentOptionsView>) {
        
    }
}.` 

## iOS version
 What version of iOS are you observing the problem on?  14.1

## Installation method
How did you install our SDK? Cocoapods 

## SDK version

What version of our SDK are you using? 21.4.0.
 

## Other information
 I'm using SwiftUI which is why I'm using UIViewControllerRepresentable to display STPPayementOptionsViewController.

**Comment by csabol-stripe** [comment]
Hi @jhjones9 ,
This sounds like it might be https://github.com/stripe/stripe-ios/issues/1758 which was fixed in v21.3.0. Would you mind cleaning & deleting Derived Data to see if maybe you have an old version hanging around?

If that doesn't fix it could you verify if `getOrCreateKey` is being called on your keyprovider implementation from `listPaymentMethodsForCustomer` in STPCustomerContext?

**Comment by billgert** [comment]
We're experiencing the same issue. Still happens on 21.5.1

**Comment by davidme-stripe** [comment]
This ticket hasn't received any updates in a while. Feel free to re-open it if you're still experiencing this issue!
