### ISSUE TITLE
is there any way or delegate method which tell that card has been successfully added ?

### ISSUE THREAD

**Issue by sultan-arshi** [stripe/stripe-ios#1798]
Basically i ma using stripe SDK for Objective-C in a react-native project every thing is working as expected but the problem is when i add card to the stripe `presentPaymentOptionsViewController` dismiss without any acknowledgement that card added or not 
It is my requirement to show some custom message to let user know about added card and it status 
is there a way ?

my code is given blow 

```
dispatch_async(dispatch_get_main_queue(), ^{
    client = [[StripeApiClient alloc] init];
    client.phone = phone;
    STPCustomerContext *customerContext = [[STPCustomerContext alloc] initWithKeyProvider: client];
    STPPaymentConfiguration *noBillingConfig = [[STPPaymentConfiguration alloc] init];
    noBillingConfig.requiredBillingAddressFields = STPBillingAddressFieldsNone;
    STPTheme *theme = [[STPTheme alloc] init];
    STPPaymentContext *paymentContext = [[STPPaymentContext alloc] initWithCustomerContext:customerContext configuration:noBillingConfig theme:theme];
    UIViewController *controller = RCTPresentedViewController();
    [RCTUtilsUIOverride setPresentedViewController:controller];

    paymentContext.hostViewController = controller;
    paymentContext.delegate = self;
    
    dispatch_async(dispatch_get_main_queue(), ^{
      [paymentContext presentPaymentOptionsViewController];
    });

  });
```

**Comment by davidme-stripe** [comment]
You can use `STPAddCardViewController` directly to do this: Just set yourself as the [delegate](https://stripe.dev/stripe-ios/docs/Protocols/STPAddCardViewControllerDelegate.html) and implement the `addCardViewController(_:didCreatePaymentMethod:completion:)` method.

**Comment by sultan-arshi** [comment]
is it possible to use `PaymentOptionsViewController` wit `paymentContext` ?
