### ISSUE TITLE
Swift compiler error Xcode 12.5

### ISSUE THREAD

**Issue by azlekov** [stripe/stripe-ios#1802]
## Summary

Cannot build project on Xcode 12.5 mac OS 11.3.1 using Stripe version 21.4.0 and version 21.5.0 (not tested with others) even after clear build folder or delete derived data. Only few times randomly I'm able to run the project once when change the version, delete the derived data, clean and rebuild but next time I start the Xcode and try to run it start to fail. Most of the cases it gives swift compiler error.

- cocoa pods version: 1.10.1

<img width="349" alt="image" src="https://user-images.githubusercontent.com/2267270/117507028-32a83280-af8f-11eb-9f03-095e68f2114c.png">

## Code to reproduce

1. pod install
2. clean build folder
3. rebuild and install
4. close and open again xcode
5. try to build/re-build

## iOS version

14.5 (simulator)

## Installation method

Installed via pods install

## SDK version

- Stripe 21.5.0
- Stripe 21.4.0

## Other information

All kind of information how to fix this is welcomed as I'm not able to develop and build the project most of the time. Thanks! 🙏

**Comment by davidme-stripe** [comment]
Hi, thanks for filing this! That's a very strange error. The error text says "`init(coder:)` has been explicitly marked unavailable here": Can you click on that and share where it was marked as unavailable?
I also don't see `isEmpty` called in `STPInputTextFieldValidator.swift`, so I'm confused as to where that error is coming from.

**Comment by L3K0V** [comment]
Hey, @davidme-stripe 

Marked as unavailable seems to be inside `STPInputTextField.swift`

<img width="859" alt="image" src="https://user-images.githubusercontent.com/2267270/117562783-498f7780-b0aa-11eb-97bf-567068ccd3ba.png">

And `isEmpty` error: 

<img width="863" alt="image" src="https://user-images.githubusercontent.com/2267270/117562807-64fa8280-b0aa-11eb-92b8-b96bf2a5d1ab.png">

Indeed checking the code here on the repo differs from what I see inside the Xcode. 😮
Any ideas? Something related with some cocoa pods cache maybe 🤔

**Comment by L3K0V** [comment]
I have tried to cleanup pods using:

```
rm -rf ~/Library/Caches/CocoaPods
$ rm -rf Pods
$ rm -rf ~/Library/Developer/Xcode/DerivedData/*
$ pod deintegrate
$ pod setup
$ pod install
```

First build successful, next builds failed...

**Comment by davidme-stripe** [comment]
That's very weird! Those lines don't exist in the [current release version](https://github.com/stripe/stripe-ios/blob/master/Stripe/STPInputTextField.swift#L57). It looks like you're picking up source files from our old `mc-beta-2` branch: Do you have `mc-beta-2` or `mc-beta-1` specified anywhere in your Podfile?

**Comment by orinmurphy** [comment]
@L3K0V what was the solution here? Im also using Swiftformat

**Comment by L3K0V** [comment]
Hey @orinmurphy, what I forgot was to exclude the pods folder from the SwiftFormat configuration file.

**Comment by orinmurphy** [comment]
Ah of course, thanks @L3K0V
