### ISSUE TITLE
iOS - Zipcode field error - Takes extra space when user selects suggested zipcode from the keypad

### ISSUE THREAD

**Issue by tmhsyb3** [stripe/stripe-ios#1809]
## Summary

When a user tries to select the zip code that comes up on the keyboard suggestion for iOS, the selection takes an extra space which eventually gives an "Invalid Postal Code" error. The user has to go back to the zip field and delete that extra space in order to get to the next step

## iOS version
iOS - 14.5.1
## SDK version

21.5.1

**Comment by tmhsyb3** [comment]
https://user-images.githubusercontent.com/84404180/118693156-69244f80-b7d0-11eb-9ada-5e10f683ff6f.mp4

**Comment by yuki-stripe** [comment]
Hi @tmhsyb3,

This will be fixed in a new card form view that we will release soon. Alternatively, you can consider using our new [drop-in payments UI integration](https://stripe.com/docs/payments/accept-a-payment?platform=ios).

**Comment by davidme-stripe** [comment]
We've released the new [STPCardFormView](https://stripe.dev/stripe-ios/docs/Classes/STPCardFormView.html), which should resolve this issue. Let us know if you have any additional feedback!
