### ISSUE TITLE
Lexical or Processor Issue (<Stripe/Stripe.h> file not found)

### ISSUE THREAD

**Issue by nikunj1996** [stripe/stripe-ios#1810]
## Installation method

Using Cocoapod

## SDK version
Stripe 21.5.0

## Other information
XCode 12.5
Objective C

**Comment by davidme-stripe** [comment]
Hello! When updating to this version, please replace `#import <Stripe/Stripe.h>` with `@import Stripe;`. See https://stripe.com/docs/mobile/ios/sdk-21-migration?language=objc for more details.

**Comment by WelshDev** [comment]
I'm also getting the same issue. That import statement exists in a lot of files.
Is there a way to force use an old version of the Stripe IOS SDK so we don't have to modify all these files?

**Comment by davidme-stripe** [comment]
@WelshDev It should be possible to use Xcode's "Find and Replace in Workspace…" feature to do this in one operation over all of your files. Please let me know if that doesn't work for you, I might be missing context on your situation!
