### ISSUE TITLE
14.x users still have a common crash

### ISSUE THREAD

**Issue by shamilovtim** [stripe/stripe-ios#1811]
## Summary
In #1426 a crash was fixed but this was not backfilled to users still stuck on 14.x implementations due to `token` changes
We are requesting that this be cherrypicked onto a 14.0.3 release as this is the last working version of Stripe that many users have until they have to undergo a heavy migration

## SDK version
14.0.2

**Comment by shamilovtim** [comment]
@csabol-stripe any updates on this? we are upgrading SDK but users still receive this common crash for now.

**Comment by davidme-stripe** [comment]
We don't plan to backport this fix to the 14.x branch. I'd recommend [cherry-picking the patch](https://github.com/stripe/stripe-ios/pull/1427/files) to your local copy of the code. Sorry for the inconvenience!
