### ISSUE TITLE
Can you expose `billingAddressCollectionLevel` for PaymentSheet.Configuration

### ISSUE THREAD

**Issue by MrShiY** [stripe/stripe-ios#1813]
SDK version: 21.5.1
We are using PaymentSheet UI to do a payment. Our requirement is that user must input card address, zip, etc.
But billingAddressCollectionLevel is not public, how can I set it for PaymentSheet?

<img width="755" alt="Screen Shot 2021-05-31 at 1 00 35 PM" src="https://user-images.githubusercontent.com/16798715/120142099-418da800-c210-11eb-839b-777ce5085620.png">

**Comment by csabol-stripe** [comment]
Making this property part of the public API is on our roadmap :) We will update this ticket when it's released

**Comment by haid45** [comment]
Hi @csabol-stripe do you have any updates in regards to this? Is it also possible to pre populate those fields (defaultBillingDetails) such as is done on the android SDK. [https://stripe.dev/stripe-android/paymentsheet/com.stripe.android.paymentsheet/-payment-sheet/-configuration/index.html#1668077536%2FProperties%2F2002900378](url)

**Comment by yuki-stripe** [comment]
As an update 
- You can set [default billing details](https://stripe.dev/stripe-ios/stripe-paymentsheet/Classes/PaymentSheet/Configuration.html#/s:18StripePaymentSheet0bC0C13ConfigurationV21defaultBillingDetailsAC0fG0Vvp) on the Configuration 
- We are working on adding support for configurable levels of billing address collection, including full billing address.

**Comment by brenoxp** [comment]
setting the `defaultBillingDetails` is not reflecting on the payment sheet UI, when I click to add a new card, I still see Afghanistan as the selected country.

![Screenshot 2022-12-21 at 8 36 16 PM](https://user-images.githubusercontent.com/7716247/209035681-3d5ca61b-2d5a-4616-997a-8b8a2ad8eea7.png)

output: 
`country: Optional("Canada")`

![Screenshot 2022-12-21 at 8 37 36 PM](https://user-images.githubusercontent.com/7716247/209035792-cf14f6f1-fed4-42b8-8b02-591f9b6fcc3a.png)

**Comment by eurias-stripe** [comment]
Hello, this is available as of v23.6.
