### ISSUE TITLE
Type 'PaymentSheet' has no member 'ConfirmButton'

### ISSUE THREAD

**Issue by skywalkerlw** [stripe/stripe-ios#1814]
I'm working on 21.6 and following your document: https://stripe.com/docs/payments/accept-a-payment?platform=ios

then i found

> Type 'PaymentSheet' has no member 'ConfirmButton'

![image](https://user-images.githubusercontent.com/2090084/120142733-2166e480-c222-11eb-9bce-b15ec3f59391.png)

![image](https://user-images.githubusercontent.com/2090084/120142843-583cfa80-c222-11eb-993d-f2fd1bdfaad4.png)

**Comment by csabol-stripe** [comment]
Ah, that's an error in our sample code. If you use `PaymentSheet.FlowController.ConfirmButton` it should work. Thanks for flagging, I'll get this updated :)

**Comment by csabol-stripe** [comment]
Docs are updated. Thanks!
