### ISSUE TITLE
PanModal definitions conflict

### ISSUE THREAD

**Issue by james-ff** [stripe/stripe-ios#1818]
## Summary
When installing via Cocoapods the latest versions of Stripe's iOS SDK, and PanModal, there is a definition clash 

## Code to reproduce
```
pod "Stripe", "21.6.0"
pod "PanModal", "1.2.7"
```
Have tried to replicate with a fresh project, but can't seem to reproduce, although in our main project it is very reproducible.

## iOS version
Minimum set to 13

## Installation method
Cocoapods

## SDK version
21.6.0

## Other information
![Screenshot 2021-06-11 at 14 56 01](https://user-images.githubusercontent.com/1874352/121697677-31ee4900-cac5-11eb-991c-486f3a737f8e.png)
![Screenshot 2021-06-11 at 14 56 14](https://user-images.githubusercontent.com/1874352/121697685-331f7600-cac5-11eb-8911-5135d52a6d27.png)

**Comment by davidme-stripe** [comment]
Hello! This was an oversight on our part, very sorry about that. We'll namespace our internal PanModal and release a new version soon.

**Comment by davidme-stripe** [comment]
We fixed this in [version 21.7.0](https://github.com/stripe/stripe-ios/releases/tag/21.7.0).
