### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by BIGBANGDEVTRON** [stripe/stripe-ios#1821]
https://github.com/stripe/stripe-ios/blob/8ca9931984949fbce44c342d5cecdada03cda18f/Stripe/PaymentSheet.swift#L19-L34

**Comment by yuki-stripe** [comment]
Hi @BIGBANGDEVTRON, could you provide more information on the issue?

**Comment by davidme-stripe** [comment]
We haven't heard any updates about this issue, so I'm closing this for now. Please reach out to https://support.stripe.com/ if you need any additional help!
