### ISSUE TITLE
Unable to override brandImageRect

### ISSUE THREAD

**Issue by BaluNaik** [stripe/stripe-ios#1824]
## Summary

It seems that it is now impossible to override `brandImageRect` method.
`Overriding non-open instance method outside of its defining module`
<img width="1206" alt="Screen Shot 2021-06-22 at 10 19 10 AM" src="https://user-images.githubusercontent.com/17030110/122873879-61ae1400-d343-11eb-99f7-849ac33840d9.png">

## Code to reproduce

```
import UIKit
import Stripe

class MyPaymentCardTextField: STPPaymentCardTextField { 

    override func brandImageRect(forBounds bounds: CGRect) -> CGRect {

    }

}
```

## iOS version

14.x

## Installation method

Cocoa pod

## SDK version

Higher than `21.3.1`

## Other information

Here is previous discussion Details https://github.com/stripe/stripe-ios/issues/1768

**Comment by davidme-stripe** [comment]
Thanks for filing this! It should be resolved in [21.7.0](https://github.com/stripe/stripe-ios/releases/tag/21.7.0).
