### ISSUE TITLE
Payment sheet is not getting present in IOS swift (Stripe.PaymentSheetError error 0)

### ISSUE THREAD

**Issue by irfanabdulkhaliq** [stripe/stripe-ios#1825]

**Comment by yuki-stripe** [comment]
Hi @irfanabdulkhaliq,

Could you print out the error?  An error before presentation means it's likely misconfigured.

**Comment by irfanabdulkhaliq** [comment]
STPAPIClient.shared.publishableKey = publishableKey
        var configuration = PaymentSheet.Configuration()
        configuration.merchantDisplayName = "testing."


        self.paymentSheet = PaymentSheet(paymentIntentClientSecret: data.client_secret ?? "", configuration: configuration)


        // MARK: Start the checkout process
        DispatchQueue.main.async {
            self.paymentSheet?.present(from: self) { paymentResult in
                // MARK: Handle the payment result
                switch paymentResult {
                case .completed:
                    print("Your order is confirmed")
                    self.placeOrder()
                case .canceled:
                    print("Canceled!")
                case .failed(let error):
                    print("Payment failed: \n\(error.localizedDescription)")
                }
            }
        }
        
        
        
        I am using this code to present the UI but it was working fine in last week but now its showing  error 
A Blank payment sheet appears and after loading it disappears.

        Error :   Payment failed: 
The operation couldn’t be completed. (Stripe.PaymentSheetError error 0.)

**Comment by bohdansasko** [comment]
Hey everyone. We have the same behavior. 
@yuki-stripe I have attached more details. Please, look through.

**Code to reproduce:**
```
import UIKit
import Stripe

final class StripeViewController: ViewController<StripeView> {

    var paymentSheet: PaymentSheet?

    // MARK: - Lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()

        BackendService.shared.getpaymentInfo() { response in
            self.preparePaymentSheet(with: response)
        }

        contentView.payButton.whenTap { [unowned self] in
            presentPaymentSheet()
        }
    }

}

// MARK: - 

private extension StripeViewController {

    func preparePaymentSheet(with response: CreateOrder.Response) {
        var configuration = PaymentSheet.Configuration()
        configuration.merchantDisplayName = "YOUR.COMPANY"
        configuration.customer = .init(
            id: response.stripeCustomerId, 
            ephemeralKeySecret: response.ephemeralKey
        )

        paymentSheet = PaymentSheet(
            paymentIntentClientSecret: response.stripeClientSecret, 
            configuration: configuration
        )
    }

    func presentPaymentSheet() {
        paymentSheet?.present(from: self) { paymentResult in
            switch paymentResult {
            case .completed:
                print("Your order is confirmed")

            case .canceled:
                print("Canceled!")

            case .failed(let error):
                print("Payment failed: \(error.localizedDescription)")
            }
        }
    }

}
```

**iOS version:** 14.4.1

**Installation method:** Podfile
```pod 'Stripe'```

**SDKVersion:** 21.6.0
  - Stripe (21.6.0):
    - Stripe/Stripe3DS2 (= 21.6.0)
  - Stripe/Stripe3DS2 (21.6.0)


A Blank payment sheet appears for a second and then disappears.
In console output: ```Error :   Payment failed: ```
The operation couldn’t be completed. (Stripe.PaymentSheetError error 0.)

**Comment by yuki-stripe** [comment]
This error means the PaymentIntent is probably already completed, canceled, or confirmed. Can you check that your backend is creating a new PaymentIntent? 

We will add more informative error logs in the next release!

**Comment by irfanabdulkhaliq** [comment]
@yuki-stripe It is working when I am using custom Stripe UI  (STPPaymentMethodParams) . My payment is successfully created when I am using  STPPaymentMethodParams. If there is  an issues in backend then it should not work on STPPaymentMethodParams. 

This is the code I am using 

func createPayment(){
        guard let paymentIntentClientSecret = paymentData?.client_secret else {
            return;
        }
        print(paymentIntentClientSecret)
        
        // Collect card details
        let cardParams = cardTextField.cardParams
        let paymentMethodParams = STPPaymentMethodParams(card: cardParams, billingDetails: nil, metadata: nil)
        let paymentIntentParams = STPPaymentIntentParams(clientSecret: paymentIntentClientSecret)
        paymentIntentParams.paymentMethodParams = paymentMethodParams

        // Submit the payment
        let paymentHandler = STPPaymentHandler.shared()
        ProgressHUD.present(view: self.view, mview: self)
        paymentHandler.confirmPayment(withParams: paymentIntentParams, authenticationContext: self) { (status, paymentIntent, error) in
          switch (status) {
          case .failed:
            AlertController.present(error?.localizedDescription ?? "")
            ProgressHUD.dismiss()
              break
          case .canceled:
            AlertController.present(error?.localizedDescription ?? "")
            ProgressHUD.dismiss()
              break
          case .succeeded:
            self.placeOrder()
           // AlertController.present(paymentIntent?.description ?? "")
              break
          @unknown default:
              fatalError()
              break
          }
        }
      }

**Comment by yuki-stripe** [comment]
Can you try printing the error object itself? e.g. `print(error)`. This should contain more information.

**Comment by irfanabdulkhaliq** [comment]
@yuki-stripe 
print(error) Error : 
PaymentSheet received a PaymentIntent in an unexpected state: STPPaymentIntentStatus"

**Comment by suneelreddymunagala** [comment]
@yang-stripe ,
device details: -iphone6 and OS: 12.4.9
Stripe sdk: 21.6.0
I'm using stripe multi step in my project.

I'm unable to present payment sheet(Add card) in ios 12.4.9 version.

LOG ANALYTICS: ["apple_pay_enabled": 0, "additional_info": [], "app_version": "2.6", "os_version": "12.4.9", "publishable_key": "testkeyValue", "device_type": "iPhone7,2", "bindings_version": "21.6.0", "event": "mc_custom_sheet_newpm_show", "product_usage": ["PaymentSheet.FlowController"], "app_name": "Urban Tiller", "analytics_ua": "analytics.stripeios-1.0", "ocr_type": "none", "ui_usage_level": "partial"]

I tested in simulator (14.4) version, I'm able to present the add card UI.

![IMG_9899](https://user-images.githubusercontent.com/36402832/124586376-fd776e00-de73-11eb-9ca8-f97ec2b39118.PNG)

![IMG_9900](https://user-images.githubusercontent.com/36402832/124586385-ff413180-de73-11eb-96ad-5fd61033c07d.PNG)


link: https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet-custom

**Comment by MohamedRed** [comment]
I am facing the same issue, I manage to create a new PaymentIntent, I then call createPaymentSheet(), then a blank payment sheet appears for a second and then disappears with the error paymentResult.failed.

**Comment by Pic2490** [comment]
Just happened to come upon this, I was having issues before and I remember changing these values:

Problem line is here:

self.setupIntentParams = STPSetupIntentConfirmParams(clientSecret: cs)

Solution is to declare like this instead:

self.setupIntentParams.clientSecret = "seti_1JAfogGssij34eJ0SeRfiBGx_secret_JoIPZHWwq........."

**Comment by davidme-stripe** [comment]
> Just happened to come upon this, I was having issues before and I remember changing these values:
> Problem line is here:
> 
> self.setupIntentParams = STPSetupIntentConfirmParams(clientSecret: cs)
>
> Solution is to declare like this instead:
>
> self.setupIntentParams.clientSecret = "seti_1JAfogGssij34eJ0SeRfiBGx_secret_JoIPZHWwq........."

This is just a guess, but it sounds like you might have passed `self.setupIntentParams` somewhere else before setting the clientSecret. If that's the case, then your first line is creating a new STPSetupIntentConfirmParams and setting `self.setupIntentParams` to a reference to it, but whatever you passed `self.setupIntentParams` to previously still has a reference to the old STPSetupIntentConfirmParams and its clientSecret.

In your second line, you're accessing the reference to `self.setupIntentParams` and setting the clientSecret on it. You only have one STPSetupIntentConfirmParams with two references, so the new clientSecret is reflected in both locations.

This bug hasn't been updated in a while, so I'm going to close it out. Feel free to file a new issue if needed!
