### ISSUE TITLE
Fatal error in iOS SDK

### ISSUE THREAD

**Issue by kylowrobelek** [stripe/stripe-ios#1831]
## Summary

Fatal error after installing Stripe iOS SDK

## Code to reproduce

Just install official iOS SDK from Stripe

## iOS version

`>= 13`

## Installation method

via CocoaPods

## SDK version

21.6.0

## Other information

Error occurs when I try to launch my app (after installation of your SDK) -> Fatal error: init(coder:) has not been implemented: file Stripe/PaymentMethodTypeCollectionView.swift, line 62

**Comment by yuki-stripe** [comment]
Hi @kylowrobelek

How are you using the SDK?

**Comment by kylowrobelek** [comment]
I've done all the steps from https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=custom (on Android everything works fine)
