### ISSUE TITLE
There was an unexpected error -- try again in a few seconds

### ISSUE THREAD

**Issue by jensonjohn001** [stripe/stripe-ios#1832]
## Summary
Showing error on submitting payment, used PaymentSheet with paymentIntentClientSecret same issue facing in PaymentSheet Example BasicIntegration app

## iOS version
14.6

## Installation method
Installed using Swift Package Manager

## SDK version
21.6.0 - Next Major

## Other information

![IMG_DFFB1F447CB7-1](https://user-images.githubusercontent.com/35399770/124547282-875e1180-de49-11eb-82c4-0c29b769bfdc.jpeg)
![error stripe](https://user-images.githubusercontent.com/35399770/124547297-8cbb5c00-de49-11eb-8e8f-833ec497304e.png)

## Log
LOG ANALYTICS: ["company_name": "Apps", "publishable_key": "pk_test_51I9V3MKqqNkOglYTIucdPpLsuvLzWSlo20kgiR9UB6aHlVF9Esmt7NDFiA0kw3mn3hk4OOo3YkNR60mdPyUmBKg600RDAsrHBX", "apple_pay_enabled": 0, "app_name": "App", "required_billing_address_fields": "zip", "ui_usage_level": "partial", "apple_merchant_identifier": "unknown", "shipping_type": "shipping", "additional_payment_methods": "none", "os_version": "14.6", "product_usage": ["PaymentSheet"], "event": "stripeios.payment_intent_confirmation", "source_type": "card", "device_type": "iPhone10,4", "app_version": "0.2", "analytics_ua": "analytics.stripeios-1.0", "additional_info": [], "ocr_type": "none", "bindings_version": "21.6.0", "required_shipping_address_fields": "none"]

LOG ANALYTICS: ["bindings_version": "21.6.0", "ui_usage_level": "partial", "device_type": "iPhone10,4", "app_version": "0.2", "apple_pay_enabled": 0, "event": "mc_complete_payment_newpm_failure", "os_version": "14.6", "app_name": "App", "publishable_key": "pk_test_51I9V3MKqqNkOglYTIucdPpLsuvLzWSlo20kgiR9UB6aHlVF9Esmt7NDFiA0kw3mn3hk4OOo3YkNR60mdPyUmBKg600RDAsrHBX", "additional_info": [], "analytics_ua": "analytics.stripeios-1.0", "ocr_type": "none", "product_usage": ["PaymentSheet"]]

**Comment by Pic2490** [comment]
I got something similar for Setup Intent, here's my error log:

Error: Optional(Error Domain=STPPaymentHandlerErrorDomain Code=9 "There was an unexpected error -- try again in a few seconds" UserInfo={com.stripe.lib:ErrorMessageKey=The provided Intent client secret does not match the expected client secret format. Make sure your server is returning the correct value and that is passed to `STPPaymentHandler`., NSLocalizedDescription=There was an unexpected error -- try again in a few seconds})

**Comment by yuki-stripe** [comment]
Hello @Pic2490,

This error indicates you're not passing a client secret to PaymentSheet. It should look like "seti_123_client_secret_123".

**Comment by Pic2490** [comment]
> Hello @Pic2490,
> 
> This error indicates you're not passing a client secret to PaymentSheet. It should look like "seti_123_client_secret_123".

please see: https://github.com/stripe/stripe-ios/issues/1836

**Comment by jensonjohn001** [comment]
@yuki-stripe can you please help me to resolve the issue. Is it any server-side issue.

**Comment by Pic2490** [comment]
> @yuki-stripe can you please help me to resolve the issue. Is it any server-side issue.

I just solved my problem above ^. Have you tried using a new client secret for ever payment intent? It's a shame that having a new secret every time is nowhere to be found in the docs.

**Comment by davidme-stripe** [comment]
Closing this out. Please reach out to [our support team](https://support.stripe.com/) if you continue to experience this issue.
