### ISSUE TITLE
New Card doesn't save via PaymentSheet iOS Stripe

### ISSUE THREAD

**Issue by sunilmaurya04** [stripe/stripe-ios#1840]
Hi Team,

I'm using Stripe SDK via:
  pod 'Stripe', '~> 21.6'
And using PaymentSheet, as follows for saving cards:

var configuration = PaymentSheet.Configuration()
        configuration.merchantDisplayName = "ShearShare Inc."
        configuration.customer = .init(
            id: stripeCustomer?.customerId ?? "",
            ephemeralKeySecret: stripeCustomer?.ephemeralKey?.secret ?? ""
        )

        PaymentSheet.FlowController.create(paymentIntentClientSecret: stripeCustomer?.paymentIntentClientSecret ?? "",
                                                 configuration: configuration) { [weak self] result in
                switch result {
                case .failure(let error):
                  print(error)
                case .success(let paymentSheetFlowController):
                  self?.paymentSheetFlowController = paymentSheetFlowController
                    paymentSheetFlowController.presentPaymentOptions(from: onController) {

                      }
                }
              } 
              
              By using this code, paymentsheet gets opened.
               I fill the new card information. Then click on Add Card, it succeed. But, if I open payment sheet again, it won't show saved card. I'm using test environment.
               
![Simulator Screen Shot - iPhone 11 Pro - 2021-07-08 at 23 22 26](https://user-images.githubusercontent.com/61402643/124968818-9a3c3600-e043-11eb-9140-7841da75fcfa.png)

If I check paymentOption via  paymentSheetFlowController, I'm getting the added card, but if I open the paymentsheet again, added card is not being shown. 

Please help me on this asap.

**Comment by aliriaz-stripe** [comment]
@sunilmaurya04 hello, it might be that you are initializing PaymentSheet with a new Customer each time? 

Can you go through the flow and share the SetupIntent ID both times, one where you added the card the first time and the second one for when you don't see the previously attached card? 

Also, make sure to log Customer ID, Ephemeral Key secret and PaymentIntent ID to make sure the same ones are being passed both times for when you initialize and present PaymentSheet and are not using a new Customer each time.

**Comment by davidme-stripe** [comment]
We only save the card when you confirm the PaymentIntent. If you don't intend to accept a payment immediately, use [PaymentSheet with the Setup Intents API](https://stripe.com/docs/payments/save-and-reuse) instead.
