### ISSUE TITLE
ERROR ITMS-90085: No architectures in the binary.

### ISSUE THREAD

**Issue by Rushabh5** [stripe/stripe-ios#1843]
## Summary

The app runs fine on the device while attached with a cable and we are able to build an archive without any issues.

The issue is when we want to upload the build to the app store using Xcode 12.5, we get the following error:

**App Store Connect Operation Error

No architectures in the binary. Lipo failed to detect any architectures in the bundle executable.**

<img width="732" alt="j7ZvA" src="https://user-images.githubusercontent.com/16097116/125658366-7391d52e-1dda-4901-944b-f4377cef32c6.png">

If I Export that build and trying to install it on the device then it will give me an error like this.

![IMG_3383](https://user-images.githubusercontent.com/16097116/125660037-a749a49a-36ac-44cf-96d7-84b3f0b98efe.jpg)

This error is gone if I removed the stripe payment gateway. So is there any solution?

## iOS version

iOS 14.5

## Installation method

Via Pod

## SDK version
 #pod 'Stripe', '21.4.0'

## Other information

Xcode version-> Trying on 12.5 and 12.5.1

**Comment by csabol-stripe** [comment]
Hi @Rushabh5 we did a sanity check archiving a sample app for submission after adding Stripe in the podfile and weren't able to hit this issue. Would you be able to provide any additional error logs or info about your configuration?

**Comment by Rushabh5** [comment]
Solved error using this pod version **19.4.1**
