### ISSUE TITLE
Stripe pod is not working on production environment on simulator on Xcode 12.5.1 version 

### ISSUE THREAD

**Issue by Ashok1312** [stripe/stripe-ios#1845]
## Summary
stripe is working on staging as well as on a device but while running the app on simulator on production environment it is not working 

## iOS version
14.5

## SDK version
'Stripe', "19.4.1"

**Comment by davidme-stripe** [comment]
Hi @Ashok1312, this forum is generally for filing bugs and feature requests for the SDK. For help integrating the SDK into your app, I'd recommend reaching out via https://support.stripe.com/. Thanks!
