### ISSUE TITLE
Failed to build module 'Stripe' from its module interface - Swift compiler version incompatibility

### ISSUE THREAD

**Issue by DylanBettermannDD** [stripe/stripe-ios#1850]
## Summary
When attempting to use the .xcframework distribution via Swift Package Manager I get the following error:

```
<base_path>/Shared/Extensions/Stripe/STPAddress+Place.swift:9:8: Failed to build module 'Stripe' from its module interface; the compiler that produced it, 'Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)'
```

## Code to reproduce
In `Package.swift`:
```
// swift-tools-version:5.4
```
(Changing this to 5.3 did not fix)

```
.binaryTarget(
    name: "Stripe",
    url: "https://github.com/stripe/stripe-ios/releases/download/21.7.0/Stripe.xcframework.zip",
    checksum: "7be902ee0c537d7f9422aceb62d9ae731acbe827aefa35339fdcc42bf89a4685"
),
```

Lastly, the code mentioned in the error, but I think it's just the first instance of Stripe that was found:

```swift
import Foundation
import Stripe

/// STPAddress extension that allows to fill address information from instance of Place
public extension STPAddress {
    /// Filling address information for STPAddress from given instance of Place. Fields are mapped respectively
    ///
    /// - Parameter place: Instance of Place class which contains information that would be mapped into STPAddress's fields
    func fillFields(with place: PlaceModel) {
        country = place.country
        city = place.city
        postalCode = place.postalCode
        line1 = place.addressLine
    }
}
```

## iOS version
n/a

## Installation method
Swift Package Manager using the .xcframework attached to the 21.7.0 release.

## SDK version
21.7.0

## Other information
https://developer.apple.com/forums/thread/669440

https://swift.org/blog/library-evolution/

**Comment by davidme-stripe** [comment]
Hello, thanks for filing! We *do* create these xcframeworks with library evolution support (`BUILD_LIBRARIES_FOR_DISTRIBUTION=YES`), so I'm not sure what's going on here.

We generally recommend using a source-based distribution with Swift Package Manager, as there are still some edge cases with using binary dependencies in a Swift project in Xcode. Would it be possible to add Stripe as a dependency in your Package.swift instead of adding the binary directly? For example:
```
dependencies: [    
    .package(url: "https://github.com/stripe/stripe-ios", from: "21.7.0"),
]
```

Also, because of how Carthage expects us to distribute `Stripe.xcframeworks.zip`, there are now 3 frameworks inside the referenced `.zip` file: This may be causing issues with using `.binaryTarget()`. You may need to define each of them (Stripe, Stripe3DS2, and StripeCore) directly.

**Comment by davidme-stripe** [comment]
Closing this, as we haven't heard back in a while. Please let me know if you're still encountering this issue!

**Comment by jonathanlu813** [comment]
We are having a similar issue. Originally we were using Carthage + Rome(cache) to integrate Stripe, but we got compiler errors of the mismatched swift lang version. Then we moved to integrate using SPM, but it'll clone the git repo which was huge and slowed down the CI. 

Is there a chance that we can build our own xcframeworks with Carthage? Carthage and Rome support building and caching xcframeworks now. I think this might be the best way to distribute.

**Comment by davidme-stripe** [comment]
Yes, the `--no-use-binaries` flag should work for Carthage. You can also run `bundle install && bundle exec ruby ./ci_scripts/export_builds.rb` from this repo, which will generate the xcframeworks using the version of Xcode defined by `xcode-select`.
