### ISSUE TITLE
3D Secure 2 verification fails to redirect. Error: com.stripe3ds2 Code=101

### ISSUE THREAD

**Issue by SarannyaSalim** [stripe/stripe-ios#1853]
## Summary

3D Secure 2 verification fails with error `com.stripe3ds2 Code=101`
The sdk should redirect to the given url to enter OTP, but it is failing

## Error Description

`some : Error Domain=com.stripe3ds2 Code=101 "There was an unexpected error -- try again in a few seconds" 
UserInfo={errorCode=101, messageVersion=2.1.0, errorDescription=Server returned HTTP response code: 500 for URL: http://127.0.0.1:8080/auth/UniCredit/VA/OTP_SMS/app_pa.jsp?languages=bg%2Cen%2Chu&language=bg&base=https%3A%2F%2F3ds.borica.bg%2Fauth%2FUniCredit%2FVA%2F, errorComponent=A, errorDetail=Message Received Invalid, messageType=Erro, NSLocalizedDescription=There was an unexpected error -- try again in a few seconds}`

#### Steps

- Enter card details that require 3ds2 verification (probably with SMS Otp)
- Sdk returns the above mentioned error
Note: All the test cards pass the verification, the issue is occuring on real cards.

**Comment by SarannyaSalim** [comment]
Could this be due to the insecure content from `http://127.0.0.1:8080/auth/UniCredit/VA/OTP_SMS/app_pa.jsp` ?

**Comment by davidme-stripe** [comment]
Hi @SarannyaSalim, sorry for the trouble! This appears to be a misconfiguration on the card issuer's end — 127.0.0.1 would point to the device itself, so there's no way this would work. Can you write into support@stripe.com with this PaymentIntent's ID?

**Comment by SarannyaSalim** [comment]
Hi @davidme-stripe Thank you for answering. Yes I will write to the support with the details.
