### ISSUE TITLE
Scroll view getting bigger and bigger in STPAddCardViewController

### ISSUE THREAD

**Issue by Axort** [stripe/stripe-ios#1859]
## Summary

The scrollview's content view seems to grow bigger and bigger each time a field is focused and then unfocused. (Attached a short video)

## Code to reproduce

Here is the code I'm using to present the payment method list and then when user presses on "Add new card" the STPAddCardViewController is presented.

```
let paymentConfig = STPPaymentConfiguration()
paymentConfig.canDeletePaymentOptions = true
paymentConfig.cardScanningEnabled  = true
paymentConfig.requiredBillingAddressFields = STPBillingAddressFields.none

let theme = STPTheme()
theme.emphasisFont = .body17Medium
theme.primaryBackgroundColor = .coolGray100
theme.accentColor = .alxedoBlue800
theme.primaryForegroundColor = .coolGray9002
theme.errorColor = .red800
theme.font = .body17Light

let paymentOptionsVC = STPPaymentOptionsViewController(configuration: paymentConfig, theme: theme, customerContext: customerContext, delegate: self)
        
let navController = UINavigationController(rootViewController: paymentOptionsVC)
navController.modalPresentationStyle = .fullScreen
self.present(navController, animated: true, completion: nil)
```

## iOS version

iOS 14.7.1

## Installation method

Cocoapods

## SDK version

21.6.0

## Other information

I enabled the assistive touch feature so you can see where and when I am touching the screen. Hope it's clear.

https://user-images.githubusercontent.com/4009741/128941773-2d559754-29eb-4262-b1d1-bad0666a3671.mov

**Comment by davidme-stripe** [comment]
Sorry, but we're closing older bugs related to STPAddCardViewController. I'd recommend using [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet) instead.
