### ISSUE TITLE
Disordered view on secure checkout page with OTP 

### ISSUE THREAD

**Issue by skywalkerlw** [stripe/stripe-ios#1860]
## Summary
I'm working on SwiftUI based solution and found a very strange behavior following on this [document](https://stripe.com/docs/payments/accept-a-payment?platform=ios). Unfortunately, I could not reproduce this anymore.

Any suggestions?

![image](https://user-images.githubusercontent.com/2090084/129031954-0fc1b8e8-e286-4a3f-86f8-d8630dd38eb8.png)

## iOS version
iOS 14

## SDK version
21.6.0

## Other information
XCode 12.5 with SwiftUI

**Comment by davidme-stripe** [comment]
That is very strange, thanks for filing! This view is rendering HTML content provided by the bank, so we unfortunately don't have a lot of control over the presentation. Can you write into support@stripe.com and attach the PaymentIntent (pi_) ID? We can reach out to the issuer and ask them to fix it.

**Comment by davidme-stripe** [comment]
We're working on a solution for this. If you'd like to opt into our testing program, please email 3ds2-mobile-fallback@stripe.com with your [account ID](https://stripe.com/docs/dashboard#find-account-id). Thanks!

**Comment by sfriedman-stripe** [comment]
Closing this down since we haven't heard anything in a while. Please open a new issue if you're still encountering issues!
