### ISSUE TITLE
Request: expose individual Credit Card entry fields

### ISSUE THREAD

**Issue by fredadda-fiverr** [stripe/stripe-ios#1863]
## Summary
Expose the existing Credit Card entry fields, so we can build our own UI with it.

## SDK version
21.8.1

## Other information
`STPPaymentCardTextField` is the only exposed field that we can use to create our own UI.
![image](https://user-images.githubusercontent.com/62248743/130359712-c625e2da-4ea8-4229-805b-d57040460b21.png)

However, the `PaymentSheet` has a different presentation, but it's all-or-nothing.
It would be nice to have the following fields exposed as `public`:
- `STPCardExpiryInputTextField`
- `STPCardCVCInputTextField`
- `STPInputTextField`

Thanks!

**Comment by yuki-stripe** [comment]
Hi @fredadda-fiverr,

We don't have plans to offer these elements individually. We do provide [STPCardValidator](https://stripe.dev/stripe-ios/docs/Classes/STPCardValidator.html) to help you build your own UI!

**Comment by fredadda-fiverr** [comment]
Thanks for your answer @yuki-stripe 
Indeed I saw that STPCardValidator was exposed and usable to validate C/C and other fields.
I will contact you by mail to explain which component we are building here at Fiverr.
