### ISSUE TITLE
PaymentSheet with ApplePay

### ISSUE THREAD

**Issue by lazarte** [stripe/stripe-ios#1866]
## Summary
Using the code from your paymentsheet example. The applepay doesn't work on ios 13? Please see attached video.

https://user-images.githubusercontent.com/248630/130889468-e1ecf1fa-5d7d-4596-b74a-84ac7a60f8bb.mov

## iOS version
IOS 13.1 Simulator

**Comment by lazarte** [comment]
xcode Version 12.5

**Comment by 1038397** [comment]
Pada 8 Sep 2021 8:51 PTG, lyndee lazarte ***@***.***> menulis:
xcode Version 12.5

**Comment by davidme-stripe** [comment]
Sorry, we haven't been able to reproduce this locally. Closing this for now, let me know if you're still experiencing this issue!
