### ISSUE TITLE
Ability to charge Subscription using the IOS Prebuilt UI.

### ISSUE THREAD

**Issue by worstkiller** [stripe/stripe-ios#1868]
## Summary
This is to bring to notice that I'm somehow not able to configure and use the Stripe IOS SDK with the subscriptions.
I am able to integrate it with the one-time payment and docs as provided but there is no way i can charge the user based on subscription. If this is available please point me to Native iOS implementation for doing this,  otherwise please consider this as a feature request

## Code to reproduce
Follow the iOS docs for payment integration.

## iOS version
14 and above

## Installation method
cocoapods

## SDK version
21.8.1

## Other information
I have done the backend deployment part but not sure how to make it work at the frontend native. One more thing i would like to point it out is that i am using Swift UI implementation.

**Comment by davidme-stripe** [comment]
Hello! You should be able to do this by [creating a Subscription](https://stripe.com/docs/billing/subscriptions/overview#how-payments-work-subscriptions) with `payment_behavior: 'default_incomplete'`, which will give you a PaymentIntent client secret. You'll want to pass that client secret to PaymentSheet, then follow the rest of the PaymentSheet integration guide as usual. If you need help with this, our [support team](https://support.stripe.com/) can walk you through it.

I agree that we need an example to explain this, so I'll leave this issue open to track building one!

**Comment by worstkiller** [comment]
okay got it that should be the way to do it.
Thanks for sharing it 👏.

**Comment by edwardbeecroft** [comment]
> Hello! You should be able to do this by [creating a Subscription](https://stripe.com/docs/billing/subscriptions/overview#how-payments-work-subscriptions) with `payment_behavior: 'default_incomplete'`, which will give you a PaymentIntent client secret. You'll want to pass that client secret to PaymentSheet, then follow the rest of the PaymentSheet integration guide as usual. If you need help with this, our [support team](https://support.stripe.com/) can walk you through it.
> 
> I agree that we need an example to explain this, so I'll leave this issue open to track building one!

Sorry to bump this thread - but I thought it a) was quite an appropriate place given it might help others, and b) gives increased visibility to the need for this.

This worked for me, until I needed to set a custom start date for the subscription. If you set `billing_cycle_anchor` and `proration_behavior`, no payment intent is received (because `latest_invoice` is null).

So the question is - how does one set a start date for subscription payments - whilst using the Stripe iOS SDK?

**Comment by sfriedman-stripe** [comment]
Hi all, we now have a full guide on this [here](https://docs.stripe.com/billing/subscriptions/build-subscriptions?platform=ios). Please let us know if you have any feedback by opening a new issue. Thank you!
