### ISSUE TITLE
Any risk in using CardScanningView by itself?

### ISSUE THREAD

**Issue by skydivedan** [stripe/stripe-ios#1872]
Apologies if this isn't the correct place to ask...

But would there be any issue in using `CardScanningView` by itself, instead of using `PaymentSheet` to get to it? We're using Stripe in our product right now, but use a custom UI for payments. So, I'd like to just integrate `CardScanningView` into our custom UI that we already use. Just wondering if `CardScanningView` will be supported for a use like this.

**Comment by davidme-stripe** [comment]
We don't support that use case, but it should work! Just note that the API isn't public, so we can't make any guarantees that it won't change in a future update.

To share a bit of our roadmap, we recently acquired [Bouncer](https://github.com/getbouncer/cardscan-ios) and plan to integrate it into this SDK in early 2022. Once we do that, we'll replace `CardScanningView` in PaymentSheet with a Bouncer-based component, and you may need to change your integration to use the new interface.

Hope that helps!

**Comment by skydivedan** [comment]
Thanks for the info! This was very helpful.
