### ISSUE TITLE
ios  weChatPay

### ISSUE THREAD

**Issue by gaoyonghua986** [stripe/stripe-ios#1873]
weChatPay   Error Domain=com.stripe.lib Code=70 "The payment failed." UserInfo={com.stripe.lib:StripeErrorTypeKey=card_error, com.stripe.lib:StripeErrorCodeKey=payment_intent_payment_attempt_failed, NSLocalizedDescription=The payment failed., com.stripe.lib:ErrorMessageKey=The payment failed.}

**Comment by aliriaz-stripe** [comment]
Hello! Can you share clear details like the Issue template states? There are no details in your Issue, like Stripe iOS SDK version, the PaymentIntent ID, what reproduction steps were, etc.

Also relatedly, I noticed you mentioned WeChat Pay. WeChat Pay isn't supported in the iOS SDK currently.

**Comment by buiquangduc** [comment]
@aliriaz-stripe I want to implement the WeChat Pay feature on my App, but I notice that the WeChat Pay feature has been disabled in August. Do you why it is disabled? And do you guys have a plan to turn it on in the future?

**Comment by buiquangduc** [comment]
Are you guys have any plan in the near future to support WeChat pay? I notice that you guys temporarily disable WeChat pay feature in September 2021 and from this moment you guys did not enable the WeChat pay feature yet.

Thanks for your support.

**Comment by davidme-stripe** [comment]
Hi @buiquangduc! Mobile SDK support for WeChat Pay is still unavailable at the moment — if you're interested in adopting it, reach out to wechatpay@stripe.com so we can discuss your use case.
