### ISSUE TITLE
unknown attribute '_spi'

### ISSUE THREAD

**Issue by nihel-aheadIt** [stripe/stripe-ios#1878]
## Summary
I uptaded tipsi stripe, then when i build on x code it returns "unknown attribute '_spi'" in StripeCore

iOS version 11
stripe version 21.8.1
stripeCore version 21.8.1

## Installation method
pod install

**Comment by davidme-stripe** [comment]
Hello, thanks for filing this!

Can you share which version of Xcode you're using? We currently require Xcode 12 or later, which includes Swift 5.3 and is the earliest version supportable by Apple to submit to the App Store.

**Comment by porter-stripe** [comment]
Closing as stale, @nihel-aheadIt if you're still encountering issues feel free to re-open with additional details.
