### ISSUE TITLE
STPAddCardViewController allows for adding multiple cards

### ISSUE THREAD

**Issue by gkaimakas** [stripe/stripe-ios#1882]
## Summary
When using STPAddCardViewController if I tap on the `done` button multiple times it will create multiple cards on stripe. I have looked for ways to disable the button but unfortunately the STPAddCardViewControllerDelegate does not provide any methods that are called when either the button is called or the request is started.

## iOS version
14.x to 15.x

## Installation method
Cocoapods

## SDK version
21.2.0

**Comment by csabol-stripe** [comment]
cc @vineet-stripe

**Comment by gkaimakas** [comment]
@csabol-stripe I believe they do! I swap right / left bar button item/items in many places of the app from buttons to indicators and the sort without issue.

**Comment by csabol-stripe** [comment]
Ah, it looks like `setRightBarButton` (the function STPAddCardViewController uses to update the bar button item) does not trigger observations on the `rightBarButtonItem(s)` keypath. Putting the following in a playground you'll see only the direct set of the `.add` button gets caught by the observers

```
import UIKit
import PlaygroundSupport

class MyViewController : UIViewController {
    private var observations: [NSKeyValueObservation] = []
    
    override func loadView() {
        let view = UIView()
        view.backgroundColor = .white

        let label = UILabel()
        label.frame = CGRect(x: 150, y: 200, width: 200, height: 20)
        label.text = "Hello World!"
        label.textColor = .black
        
        view.addSubview(label)
        self.view = view
       
        
        
        let rightBarButtonItem = observe(\.navigationItem.rightBarButtonItem) { (viewController, value) in
            print("Right bar button item \(String(describing: viewController.navigationItem.rightBarButtonItem))")
        }
        
        
        let rightBarButtonItems = observe(\.navigationItem.rightBarButtonItems) { (viewController, value) in
            print("Right bar button itemS \(String(describing: viewController.navigationItem.rightBarButtonItems))")
        }
        
        
        observations.append(rightBarButtonItem)
        observations.append(rightBarButtonItems)
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            print("setting add")
            let barButtonItem = UIBarButtonItem(systemItem: .add)
            self.navigationItem.rightBarButtonItem = barButtonItem
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                print("setting cancel")
                let barButtonItem = UIBarButtonItem(systemItem: .cancel)
                self.navigationItem.setRightBarButton(barButtonItem, animated: false)
            }
        }

    }
}
// Present the view controller in the Live View window
PlaygroundPage.current.liveView = MyViewController()
```

**Comment by gkaimakas** [comment]
@csabol-stripe can you take a look if this can be fixed? I would appreciate it a lot!

**Comment by davidme-stripe** [comment]
Sorry, but I'm closing this issue as I don't believe we'll get around to fixing it. We'd recommend using [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet) instead of `STPAddCardViewController`.

**Comment by lukeirvin** [comment]
@davidme-stripe Is there a link to show how to wrap PaymentSheet? I want to use it without having to set up any backend work at the get-go.
