### ISSUE TITLE
Overridden errorImage(for:) & cvcImage(for:) is not called in subclass of STPPaymentCardTextField

### ISSUE THREAD

**Issue by ShengYuenIW** [stripe/stripe-ios#1886]
## Summary
Overridden method open class func errorImage(for cardBrand: STPCardBrand) -> UIImage? & open class func cvcImage(for cardBrand: STPCardBrand) -> UIImage? is not called in subclass of STPPaymentCardTextField

## Code to reproduce
```
import Stripe
import UIKit

final class PaymentCardTextField: STPPaymentCardTextField {
    override class func errorImage(for cardBrand: STPCardBrand) -> UIImage? {
        return nil
    }

    override class func cvcImage(for cardBrand: STPCardBrand) -> UIImage? {
        return nil
    }
}
```

## iOS version
iOS 15

## Installation method
Cocoapods

## SDK version
21.8.1

## Other information
line 1809 & 1818
should be Self.errorImage(for: ) instead of STPPaymentCardTextField.errorImage(for:).

same issue as https://github.com/stripe/stripe-ios/issues/1827.

**Comment by porter-stripe** [comment]
We fixed this in version 21.12.0.
