### ISSUE TITLE
[Question] Request Card holder name when using PaymentSheet

### ISSUE THREAD

**Issue by romansorochak** [stripe/stripe-ios#1890]
Is there any way to request the cardholder name when using `Stripe.PaymentSheet` ?
We're using carthage version - `github "stripe/stripe-ios" "21.6.0"`

<img width="399" alt="Screenshot 2021-10-22 at 16 30 25" src="https://user-images.githubusercontent.com/7702356/138462234-13dd856b-5aab-4eb9-a328-11e77c5ee245.png">

**Comment by ahmedg-stripe** [comment]
@romansorochak starting to think about this a bit, I was wondering, why did you need this field?

**Comment by jfougere** [comment]
Hi I am also wondering about this possibility. I see that the cardholder's name is asked in your checkout page which makes your different solutions (checkout vs PaymentSheet) not completely aligned in terms of functionality. See https://checkout.stripe.dev/

Another question also, if not asked in the PaymentSheet via a text field, is it an information that you retrieve from the banks ? If yes would it be possible to provide it in the events ?

**Comment by sfriedman-stripe** [comment]
Hi @romansorochak @jfougere sorry for the slow response on this GitHub issue, but in early 2023 we released `PaymentSheet.Configuration.defaultBillingDetails`, which allows you to always collect the customer's name via PaymentSheet. You can read more in our docs [here](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet#billing-details-collection). I'll be resolving this now, but please feel free to open another issue if you have further suggestions!
