### ISSUE TITLE
Error Message Improvement for wrong STPPaymentIntentStatus

### ISSUE THREAD

**Issue by AndreasVerhoeven** [stripe/stripe-ios#1899]
## Summary
We're running into some issues with intents and while trying to debug these, we see the following `debugDescription` of an error:

```
Stripe payment failed with error unknown(debugDescription: "PaymentSheet received a PaymentIntent in an unexpected state: STPPaymentIntentStatus")
```

This seems to come from the following line: `"PaymentSheet received a PaymentIntent in an unexpected state: \(paymentIntent.status)"`. It seems like the intention here is to print the actual value of the `STPPaymentIntentStatus`, but right now,  it only prints the type name because `STPPaymentIntentStatus` is an `@objc` enum, which do not have run time type information swift.

A fix could be to have a method on `STPPaymentIntentStatus` that returns the textual value, much like `STPPaymentIntentStatus.status(from: String)`, but the reverse.

**Comment by csabol-stripe** [comment]
Agreed! I'll get this fixed in the next release. Thanks for the report @AndreasVerhoeven :)

**Comment by porter-stripe** [comment]
Closing as this should now be resolved in the latest versions of the SDK
