### ISSUE TITLE
Text on Done Button truncated on iPhone 11 Pro Max

### ISSUE THREAD

**Issue by allisonpaigemcentire** [stripe/stripe-ios#1903]
## Summary

The doneItem (rightBarButtonItem) in STPAddCardViewController doesn't expand to show all characters in the button title on iPhone 11 Pro Max

![3070709B-5BC1-4159-B7FE-01AD6C106CCC](https://user-images.githubusercontent.com/79477856/142441783-580e1502-f665-4da8-9517-ec80c9edf11e.jpeg)

## Code to reproduce

We are using STPAddCardViewController with a default theme and configuration, very few items set in either file:

`let config: STPPaymentConfiguration = createStripeConfigFromDefault()
        config.requiredBillingAddressFields = .full

        let stripeTheme: STPTheme = createStripeThemeFromDefault()
        stripeTheme.primaryBackgroundColor = ourTheme.color.background
        stripeTheme.secondaryBackgroundColor = ourTheme.color.white
        stripeTheme.accentColor = ourTheme.color.primary
        stripeTheme.font = ourTheme.font.body.body.uiFont`

## iOS version

iOS 15

## Installation method

Swift Package Manager

## SDK version

21.9.0

## Other information

We are not using storyboards anywhere in the app

**Comment by yuki-stripe** [comment]
I'm unable to reproduce this with the default theme.  Can you try commenting out the code that configures `STPTheme` and see if it still happens?


![image](https://user-images.githubusercontent.com/47796191/142510008-9a676684-c08b-4b4b-89f5-9f6cc4a6d631.png)

**Comment by allisonpaigemcentire** [comment]
> I'm unable to reproduce this with the default theme. Can you try commenting out the code that configures `STPTheme` and see if it still happens?
> 
> ![image](https://user-images.githubusercontent.com/47796191/142510008-9a676684-c08b-4b4b-89f5-9f6cc4a6d631.png)

hi Yuki, the issue doesn't occur on the simulator, only on a physical device

**Comment by allisonpaigemcentire** [comment]
hi @yuki-stripe, were you able to recreate the issue on a real device? The issue doesn't occur in the simulator

**Comment by ramont-stripe** [comment]
Hi @allisonpaigemcentire, how did you set the font for the navigation bar title?

![](https://user-images.githubusercontent.com/88752322/143956618-33e5f0d6-df7b-43fa-b567-8af400e18988.png)

I noticed that the *Cancel* button, navigation bar title, and the *Done* button, each is using a different font. Normally the navigation bar title and the Done button use [`STPTheme.emphasisFont`](https://stripe.dev/stripe-ios/docs/Classes/STPTheme.html#/c:@M@Stripe@objc(cs)STPTheme(py)emphasisFont)

![](https://user-images.githubusercontent.com/88752322/143959468-0538924b-6e17-4acd-bf5d-c9bcdc4c9ea7.png)

Try setting `.emphasisFont` to your custom font and see if that fixes it.

**Comment by allisonpaigemcentire** [comment]
Thanks @ramont-stripe. We set .emphasisFont to our custom font but are still seeing the issue

**Comment by davidme-stripe** [comment]
I'm unable to reproduce this as well, but it might be a UIKit issue — this is just a guess, but can you try:
```
addCardViewController.navigationController!.setNavigationBarHidden(true, animated: false)
addCardViewController.navigationController!.setNavigationBarHidden(false, animated: false)
```
After the view controller appears? That should force it to re-layout.

**Comment by davidme-stripe** [comment]
Closing this, as we haven't heard back in a while. Let me know if you're still experiencing this issue!
