### ISSUE TITLE
[Question] Dedicate textfield for CVC Recollection feature

### ISSUE THREAD

**Issue by langtutheky** [stripe/stripe-ios#1905]
## Summary

I have checkout the current API and it looks like there is no dedicate field to recollect CVC in order to implement this feature [iOS Recollect CVC](https://stripe.com/docs/payments/save-during-payment-cards-only#ios-recollect-cvc). What is the current acceptable implementation for this feature? can I collect the CVC from my own text field and then follow the integration with `STPConfirmCardOptions`? Would this approach still make me PCI Compliant (eligible for an SAQ A)?

**Comment by davidme-stripe** [comment]
Hi @langtutheky — my understanding is that using CVC recollection in that way could make you ineligible for a SAQ A. We're going to keep this issue open as a request for a Stripe-provided CVC UI element, which would help keep you eligible for a SAQ A.

**Comment by jfougere** [comment]
I am also interested by this. Would it be possible to integrate this feature into the PaymentSheet as an option (configuration flag) or a flag in the payment intent ?

**Comment by sfriedman-stripe** [comment]
Hi all, we now have this available in beta using PaymentSheet. You can sign up [here](https://docs.stripe.com/payments/accept-a-payment?platform=ios&mobile-ui=payment-element&ui=payment-sheet#ios-cvc-recollection). Please open an issue if you have any feedback!
