### ISSUE TITLE
SwiftUI Payment Sheet Crashes With Multiple Views in Navigation Stack

### ISSUE THREAD

**Issue by benedelstein** [stripe/stripe-ios#1906]
## Summary
When multiple views hold a reference to the same payment sheet, the application crashes with this error: 

> 'Application tried to present modally a view controller <Stripe.BottomSheetViewController: 0x153e11060> that is already being presented by <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x150a5f620>.'

A common example is a checkout flow in a navigation view, where multiple paths end up leading to the checkout page with a PaymentButton. If the user taps on the PaymentButton in the view higher up in the navigation stack, it causes the crash.

## Code to reproduce

Modifying the setup from the `PaymentSheet Example` project:

```Swift
struct HostView: View {
    @StateObject var paymentModel = MyBackendModel()
    var body: some View {
        NavigationView {
            VStack {
                ExampleSwiftUIPaymentSheet(model: paymentModel)
                NavigationLink("next flow") {
                    ExampleSwiftUIPaymentSheet(model: paymentModel)
                }
            }
        }
    }
}

struct ExampleSwiftUIPaymentSheet: View {
    @ObservedObject var model: MyBackendModel

    var body: some View {
        VStack {
            if let paymentSheet = model.paymentSheet {
                PaymentSheet.PaymentButton(
                    paymentSheet: paymentSheet,
                    onCompletion: model.onCompletion
                ) {
                    ExamplePaymentButtonView() // just the UI for this button
                }
            } else {
                ExampleLoadingView()
            }
            if let result = model.paymentResult {
                ExamplePaymentStatusView(result: result)
            }
        }.onAppear { model.preparePaymentSheet() }
    }
}
```

## iOS version
15.0

## Installation method
Cocoapods

## SDK version
21.9.0

## Other information
I've seen 2 similar issues to this one:
https://github.com/stripe/stripe-ios/issues/1782
https://github.com/stripe/stripe-ios/issues/1900

The reason that this crash occurs is in `PaymentSheet+SwiftUI.swift` https://github.com/stripe/stripe-ios/blob/39abf35e84f2e284aabfa9ad9efc7ce6a13c5f1c/Stripe/PaymentSheet%2BSwiftUI.swift#L245-L252

When `ExampleSwiftUIPaymentSheet` loads, it regenerates a new payment sheet, so there are now 2 PaymentSheets. When you tap the payment button, it tries to present the payment sheet twice. The first time it succeeds, presenting the sheet from the top-most view controller. The second time it finds the `BottomSheetViewController` as the top-most VC, and tries to present from there, which causes the crash.

2 possible workarounds:

In 

1. In your view model method `preparePaymentsheet()`, check to see if the paymentSheet is nil, and return if not. I'd rather not do this since the user might modify the product to purchase on a previous view in the checkout flow, then I'd be presenting an outdated payment intent. I'd have to check if a payment intent should be regenerated.

```Swift
if paymentSheet != nil {
        return
}
// fetch from server...
```

2. In the UIViewRepresentable, only attempt to present the BottomSheetViewController if it is not already presented. To test this solution, I added `@State var isAlreadyPresented`, which fixed the crash.

```Swift
struct PaymentSheetPresenter: UIViewControllerRepresentable {
        @Binding var presented: Bool
        @State var isAlreadyPresented = false
        weak var paymentSheet: PaymentSheet?
        let onCompletion: (PaymentSheetResult) -> Void

        func makeCoordinator() -> Coordinator {
            return Coordinator(parent: self)
        }

        func makeUIViewController(context: Context) -> UIViewController {
            return UIViewController()
        }

        func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
            if presented && !isAlreadyPresented {
                context.coordinator.presentPaymentSheet(on: uiViewController)
                DispatchQueue.main.async {
                    isAlreadyPresented = true
                }
            } else if !presented {
                context.coordinator.forciblyDismissPaymentSheet(from: uiViewController)
                DispatchQueue.main.async {
                    isAlreadyPresented = false
                }
            }
        }
      
      class Coordinator {

            let parent: PaymentSheetPresenter

            init(parent: PaymentSheetPresenter) {
                self.parent = parent
            }

            func presentPaymentSheet(on controller: UIViewController) {
                let presenter = findViewControllerPresenter(from: controller)
                
                parent.paymentSheet?.present(from: presenter) { (result: PaymentSheetResult) in
                    self.parent.presented = false
                    self.parent.isAlreadyPresented = false
                    self.parent.onCompletion(result)
                }
            }

            func forciblyDismissPaymentSheet(from controller: UIViewControllerType) {
                if let bsvc = controller.presentedViewController as? BottomSheetViewController {
                    bsvc.didTapOrSwipeToDismiss()
                }
            }
        }
}
```
Another way to do this is in `findViewControllerPresenter()`, check if the top most VC is already a BottomSheetViewController, and don't present if so.

**Comment by porter-stripe** [comment]
Hi @benedelstein thanks for opening this issue, I was able to reproduce this crash. The crash you are receiving seems _correct/expected_ to some extent, as the PaymentSheet is being presented twice. For your use case have you considered moving the `preparePaymentSheet()` call onto `onAppear` for your `HostView` so that the PaymentSheet is only created once and you only fetch the data from your backend once? After doing this I no longer observe a crash in the scenario laid out above.

For example:
```swift
struct HostView: View {
    @StateObject var paymentModel = MyBackendModel()
    var body: some View {
        NavigationView {
            VStack {
                ExampleSwiftUIPaymentSheet(model: paymentModel)
                NavigationLink(destination: ExampleSwiftUIPaymentSheet(model: paymentModel)) {
                    Text("next flow")
                }
            }
        }.onAppear { paymentModel.preparePaymentSheet() }
    }
}

struct ExampleSwiftUIPaymentSheet: View {
    @ObservedObject var model: MyBackendModel

    var body: some View {
        VStack {
            if let paymentSheet = model.paymentSheet {
                PaymentSheet.PaymentButton(
                    paymentSheet: paymentSheet,
                    onCompletion: model.onCompletion
                ) {
                    ExamplePaymentButtonView()
                }
            } else {
                ExampleLoadingView()
            }
            if let result = model.paymentResult {
                ExamplePaymentStatusView(result: result)
            }
        }
    }
}
```

**Comment by benedelstein** [comment]
I don't think I'd want to call `preparePaymentSheet()` in the host view, since in the checkout flow the user might modify the item to buy, so I'd need to regenerate the payment intent. Ideally I'd like my navigation view to have multiple paths that all lead to the same final "checkout" page, at which point I generate the payment intent based on what the user selected.

It's still sort of odd that this happens though, since only 1 payment button was tapped, so only that payment button should attempt to present the sheet. Why is it trying to present twice?

**Comment by porter-stripe** [comment]
> Why is it trying to present twice?

I'm noticing that when I tap the nav link for "next flow" `onAppear()` is invoked twice, there appears to be others having similar [issues](https://stackoverflow.com/questions/63080830/swifui-onappear-gets-called-twice). This appears to cause some issues with the payment sheet presentation as there appears to be 2 instances of PaymentSheet trying to be presented at the same time (if I'm reading the memory address locations correctly). We'll look into this and see how we can be more resilient in this scenario and update this issue with more details.

**Comment by codeonomics** [comment]
@porter-stripe Any updates on this? Running into the same issue :)

**Comment by csabol-stripe** [comment]
Got a fix for this merged and we'll include it in our next release!

**Comment by Wmc05061970** [comment]
am i up and running? this has been very  hard im loosing money

**Comment by porter-stripe** [comment]
This is resolved in the latest release 21.12.0.

**Comment by raldred** [comment]
Sorry to drag up an old issue, but we're seeing (via `stripe-react-native`) on an increasing number of devices since moving to `23.28.3` a few weeks back.

Is it possible this has been regressed?

```
CoreFoundation +0x083f20 __exceptionPreprocess
libobjc.A +0x0172b4 objc_exception_throw
UIKitCore +0x56e2e8 -[UIViewController _presentViewController:withAnimationController:completion:]
UIKitCore +0x56f978 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke
UIKitCore +0x311edc -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:]
UIKitCore +0x311c6c -[_UIViewControllerTransitionContext _runAlongsideCompletions]
UIKitCore +0x311a80 -[_UIViewControllerTransitionContext completeTransition:]
Residently +0x922894 closure in BottomSheetPresentationAnimator.animatePresentation (StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/BottomSheet/BottomSheetPresentationAnimator.swift:48)
Residently +0x9229d8 closure in BottomSheetPresentationAnimator.animatePresentation (StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/BottomSheet/BottomSheetPresentationAnimator.swift:63)
Residently +0x9235a4 closure in BottomSheetPresentationAnimator.animate (StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/BottomSheet/BottomSheetPresentationAnimator.swift:99)
Residently +0x9235a4 closure in BottomSheetPresentationAnimator.animate (<compiler-generated>)
Residently +0x8f7b64 thunk for closure (<compiler-generated>)

```

**Comment by MMavrisPaleBlue** [comment]
> Sorry to drag up an old issue, but we're seeing (via `stripe-react-native`) on an increasing number of devices since moving to `23.28.3` a few weeks back.
> 
> Is it possible this has been regressed?
> 
> We have events on iOS 16, 17, 18
> 
> ```
> NSInvalidArgumentException: Application tried to present modally a view controller <STP_Internal_BottomSheetViewController: 0x107a0dc00> that is already being presented by <UIViewController: 0x105a1b6f0>.
> 
> 
> CoreFoundation +0x083f20 __exceptionPreprocess
> libobjc.A +0x0172b4 objc_exception_throw
> UIKitCore +0x56e2e8 -[UIViewController _presentViewController:withAnimationController:completion:]
> UIKitCore +0x56f978 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke
> UIKitCore +0x311edc -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:]
> UIKitCore +0x311c6c -[_UIViewControllerTransitionContext _runAlongsideCompletions]
> UIKitCore +0x311a80 -[_UIViewControllerTransitionContext completeTransition:]
> Residently +0x922894 closure in BottomSheetPresentationAnimator.animatePresentation (StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/BottomSheet/BottomSheetPresentationAnimator.swift:48)
> Residently +0x9229d8 closure in BottomSheetPresentationAnimator.animatePresentation (StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/BottomSheet/BottomSheetPresentationAnimator.swift:63)
> Residently +0x9235a4 closure in BottomSheetPresentationAnimator.animate (StripePaymentSheet/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/BottomSheet/BottomSheetPresentationAnimator.swift:99)
> Residently +0x9235a4 closure in BottomSheetPresentationAnimator.animate (<compiler-generated>)
> Residently +0x8f7b64 thunk for closure (<compiler-generated>)
> ```
> 
> ![screenshot](https://github.com/user-attachments/assets/a06ce890-9509-4339-80c6-17d7c5a546ed)

Any update on this? We are getting similar crashes as well

**Comment by davidme-stripe** [comment]
@MMavrisPaleBlue @raldred Thanks for the update — could you file this as an issue at https://github.com/stripe/stripe-react-native if you're still encountering crashes? You may also want to update to the latest version, which uses the new RN architecture.
