### ISSUE TITLE
confirmCardSetup on mobile

### ISSUE THREAD

**Issue by andrejcher** [stripe/stripe-ios#1908]
Is there a way to call https://stripe.com/docs/js/setup_intents/confirm_card_setup with iOS SDK?

If no, are there any workarounds to have this working on Mobile?

Thanks!

**Comment by ramont-stripe** [comment]
Hi @andrejcher,

On iOS you can use [STPPaymentHandler.confirmSetupIntent(with:completion:)](https://stripe.dev/stripe-ios/docs/Classes/STPPaymentHandler.html#/c:@M@Stripe@objc(cs)STPPaymentHandler(im)confirmSetupIntent:withAuthenticationContext:completion:), passing a [STPSetupIntentConfirmParams](https://stripe.dev/stripe-ios/docs/Classes/STPSetupIntentConfirmParams.html) object.

**Comment by andrejcher** [comment]
@ramont-stripe  thanks a lot!
