### ISSUE TITLE
Allow changing API version

### ISSUE THREAD

**Issue by harshal** [stripe/stripe-ios#191]
Maybe I am missing something, but I haven't been able to find a easy way to send the API version header with requests. This is useful when you have multiple different apps using the same account and so you do not want to switch the global default API version in the account to a later version. 

Java/android for example simply allows you to do
Stripe.apiVersion = "2015-07-28";

**Comment by jflinter** [comment]
Hey there! Our `/tokens` endpoint, which is basically the only endpoint our iOS SDK interacts with, hasn't changed in a really long time. Can you tell me a bit more about what you're actually trying to do where this is causing issues for you?

**Comment by jflinter** [comment]
Going to close this, but I'd still like to hear about the troubles you're having @harshal.

**Comment by harshal** [comment]
Sorry about the late reply - somehow I missed your earlier response here. 

Let me try and describe that problem I am trying to address: 

- The default API version that is set globally in our stripe account is pretty old. My understanding is that versions in Stripe API are "global" - in the sense that they do not apply to individual endpoints - but to all of them together.
- For various reasons, we would like to start using current versions of your API across our platform. The most important of these reasons was that we were asked by our Stripe contact to do so everywhere to ensure best availability of stripe's fraud detection features.
- We have multiple apps and components that interact with stripe which all use the same account. There are various server pieces and several different apps which call different APIs. The iOS app which uses this SDK is just one of them.
- Switching the global version in the account to a higher level is thus not a great option for us since it would imply that all those components switch in a non-reversible way at the same time. What I would like to do instead is start using newer version one component at a time so that we are able to independently test it and ship it without being gated by the global account version switch.
- I thought that the way to achieve the above is to leave the account setting as it was and send a version header from each place that we call any stripe API .... as described for example here : https://stripe.com/docs/api/curl#versioning . I have successfully used this approach in my server code and also in android.

This is why I asked for some way to set that header on iOS as well. We would have been able to test the API version change without switching the account version.

However, given your response, I think you are saying that /tokens is simple enough and has not changed at all - so its immaterial what API version gets used? Its also not material to any internal fraud detection functionality and that basically we can just  switch the api version in our account without affecting this endpoint. We do not have to worry about prior testing of the relevant iOS app with the new API version. Is that correct?

**Comment by jflinter** [comment]
Hey @harshal - yep, everything you've said is accurate. There haven't been any backwards-incompatible changes to our API that would affect our iOS SDK in quite some time, so adding any kind of versioning here would be currently unnecessary (that being said, if that changes, we'll certainly add a means to switch API versions here).
