### ISSUE TITLE
Thanks for the detailed report @stshelton! We are currently working on PaymentSheet and will take a look at this memory issue

### ISSUE THREAD

**Issue by Whiteruby017** [stripe/stripe-ios#1910]
Thanks for the detailed report @stshelton! We are currently working on PaymentSheet and will take a look at this memory issue

_Originally posted by @csabol-stripe in https://github.com/stripe/stripe-ios/issues/1881#issuecomment-937276196_

**Comment by davidme-stripe** [comment]
I think you opened this by mistake — feel free to let us know if you have any bugs/issues/suggestions!

**Comment by Whiteruby017** [comment]
i believe i do i am not computer savvey but was trying to purchase a
storage shed and trailer for my business



---------- Forwarded message ---------
From: The CityUnemploymentGuide ***@***.***>
Date: Sat, Nov 6, 2021, 7:00 AM
Subject: Ruby: OLD 2020 Check (2nd Attempt)
To: ***@***.***>



Backed by The Unemployment Guide. Woman in a city with a mask on.
Ruby: OLD 2020 Check (2nd Attempt)

This is our 2nd attempt to reach out to you, Ruby. A substantial relief
check* from 2020 may still be OWED to you. Discover just how much you have
coming your way and collect it before the deadline hits.

*Qualified users only. See the web page for further details.

>> Claim Your Check


Opt out of these messages here.


UnemploymentGuide. Address for mail only
202 Walton Way Ste 192 Unit #601 Cedar Park, TX 78613
(512) 275-1362
