### ISSUE TITLE
Icons disappears from payment method option in iOS Dark mode

### ISSUE THREAD

**Issue by jamesblasco** [stripe/stripe-ios#1911]
**Describe the bug**
Switching between payment methods leads to the disappearing of an icon from a card option.

**To Reproduce**
1. Set configuration.style = .alwaysLight on the Example app
1. Go to iPhone Settings > Display & Brightness > APPEARANCE
2. Turn on Dark mode
3. Try to change payment method selection a few times

https://user-images.githubusercontent.com/19904063/145671882-df08e53c-f871-4e21-ba3e-da1b3ee1ab12.mp4

**Expected behavior**
The icon should not disappear

**Smartphone / tablet**
 - Device: iPhone 13
 - OS: iOS 15.1
 - Stripe SDK version: Master(21.9.0)

**Comment by csabol-stripe** [comment]
Good catch! I am looking into this

**Comment by csabol-stripe** [comment]
This should be fixed in the latest release!
