### ISSUE TITLE
Stripe iOS SDK & Builtin UI  accepting card with wrong cvv code for second time

### ISSUE THREAD

**Issue by VipulDungranee** [stripe/stripe-ios#1912]
## Summary
Stripe iOS SDK (built in UI) accepting card with wrong cvv code for second time , also its accepting card with same detail with multiple time (even I enter wrong cvv code).

## Code to reproduce
 follow below steps to reproduce :-
  -> step 1 :- add 1 card with correct information like card number , expiry date and cvv number 
  -> step 2:- than try to add new card with same detail which you already added in first step

SS of multiple cards of same details 
![Screen Shot 2021-12-14 at 12 03 50 PM](https://user-images.githubusercontent.com/79624203/145946018-5d278deb-cbc3-4816-8077-0fe0eb6d0abe.png)

## iOS version
- 15.0.1

## Installation method
- using Swift Package Manager 

## SDK version
- 21.8.1.

## Other information
 - we have also tested in multiple device with iOS 13.0+ 
 - we have integrated stripe sdk same as below doc
    https://stripe.com/docs/mobile/ios/basic
 - we are using stripe's built-in ui for payment option and add new card
 - we notice that we getting proper error for wrong cvv and expiry date only when we trying to add that card 1st time, once we add 1 card than if we try to add new card with same detail than for wrong cvv its not showing errors, and we are able to add same card with infinite time( > 1 time) with wrong cvv and expiry

**Comment by yuki-stripe** [comment]
Hello @VipulDungranee,

This integration (https://stripe.com/docs/mobile/ios/basic) only does minimal validation when you add a card and we're no longer adding features for it. 

If you want Stripe to set up the card for future use _without_ making a payment, you'll want to use Stripe's SetupIntents API. The SDK's [new PaymentSheet integration supports SetupIntents](https://stripe.com/docs/payments/save-and-reuse?platform=ios&ui=payment-sheet) - would that work for you?

**Comment by ahmedg-stripe** [comment]
@VipulDungranee Curious why you are using this integration vs [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios)?

**Comment by sfriedman-stripe** [comment]
Resolving due to inactivity

**Comment by Wmc05061970** [comment]
And literally don't know how to use stripe I'm confused on how you use it
and where does the hub come in and why is there like digital coding and all
that crap and why did someone hack my stuff from it

**Comment by sfriedman-stripe** [comment]
@Wmc05061970 You can reach out to our support team at support.stripe.com for assistance
