### ISSUE TITLE
Japanese Mobile Phone Keyboard Not Showing Number Pad on Expiry, Cvc & Card Number Fields.

### ISSUE THREAD

**Issue by parK-dev** [stripe/stripe-ios#1913]
Hello Stripe devs,

We are working out of Japan and noticed that the keyboard type on mobile shows the character input keyboard on the card number, cvc and expiry date fields as opposed to the number pad. When I use my english phone there is no issue and the keyboard is the number pad. But when the phone is using the JP one, this is what they get: 

JP Phone:
![image](https://user-images.githubusercontent.com/77372584/145949667-98b6a4d9-beeb-480f-bb46-5cf9918bb4e1.png)

EN Phone:
![image](https://user-images.githubusercontent.com/77372584/145949717-02c06609-63a5-40a6-8f57-2b093bb3b89a.png)

Is there a way for us to control or access the inputs to try and force the numberpad?

Please advise,

**Comment by csabol-stripe** [comment]
Hi @parK-dev, could you provide some additional details on which version of the Stripe SDK you are using and which UI classes you are using for the card number, cvc and expiry date fields?

**Comment by parK-dev** [comment]
Hello,

I am using the built-in 

```
cardNumber = elements.create("cardNumber");
cardExpiry = elements.create("cardExpiry");
cardCvc = elements.create("cardCvc");
```
and mounting them on my elements

```
cardNumber.mount("#card-number");
cardExpiry.mount("#card-expiry");
cardCvc.mount("#card-cvc");
```

We are using ```"@stripe/stripe-js": "^1.16.0"```

**Comment by aliriaz-stripe** [comment]
@parK-dev hello! Could you write in to Stripe Support at https://support.stripe.com/contact with all the details you shared here? The Developer Support team there can help you out.

Going to close this as Issues should be limited to the Stripe iOS SDK itself but this seems to be in the Stripe Elements (web) + mobile-web intersection, so is not Stripe iOS SDK related.
