### ISSUE TITLE
[BUG] Release 21.10.0 and 21.11.0 shows warnings when included by SwiftPM

### ISSUE THREAD

**Issue by merrysuperstar** [stripe/stripe-ios#1917]
## Summary
3 warnings are generated by Xcode when version 21.10.0 or 21.11.0 is used in a project via SwiftPM

## Code to reproduce
Create a Project and include Stripe iOS using SwiftPM

Xcode starts to show warnings:
found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/DerivedData/XXX-bhjuciyddlzxgmfnuyavtvlsqvmo/SourcePackages/checkouts/stripe-ios/StripeCore/StripeCore/Source/API

found 2 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/DerivedData/XXX-bhjuciyddlzxgmfnuyavtvlsqvmo/SourcePackages/checkouts/stripe-ios/StripeIdentity/StripeIdentity/Resources/Images/illustration_id_card_front@3x.png
DerivedData/XXX-bhjuciyddlzxgmfnuyavtvlsqvmo/SourcePackages/checkouts/stripe-ios/StripeIdentity/StripeIdentity/Resources/Images/illustration_id_card_back@3x.png

## iOS version
iOS 15.2

## Installation method
SwiftPM

## SDK version
21.10.0 and 21.11.0

**Comment by davidme-stripe** [comment]
Hello, thanks for filing this! Apologies for the oversight, we'll have this fixed very soon.

**Comment by davidme-stripe** [comment]
We've released [version 21.11.1](https://github.com/stripe/stripe-ios/releases/tag/21.11.1) with a fix for this. Sorry for the inconvenience!

**Comment by merrysuperstar** [comment]
Thank you! :) That was fast!
