### ISSUE TITLE
Rename Button Class

### ISSUE THREAD

**Issue by aneurinc** [stripe/stripe-ios#1918]
## Is your feature request related to a problem? Please describe.
We cannot update to > `21.9.0` due to a naming collision with the `Button` class added [here](https://github.com/stripe/stripe-ios/commit/c7abe089400d3b1254880854998801e6f128ca58) and another SDK we are using

## Describe the solution you'd like
Rename the `Button` class to something less generic and unique to the Stripe SDK

## Describe alternatives you've considered
We cannot rename the file because we are using CocoaPods

## Additional context
![Screen Shot 2022-01-18 at 14 22 46](https://user-images.githubusercontent.com/35877937/150029385-a57c6266-92b3-4ce3-bd25-b31e09ccc613.png)

**Comment by csabol-stripe** [comment]
Thanks for the report @aneurinc I'll have a fix asap

**Comment by porter-stripe** [comment]
@csabol-stripe @aneurinc Closing this as this was resolved in the latest version (21.12.0), feel free to reopen if needed :)
