### ISSUE TITLE
[BUG] Interacting with STPCardFormView locks the UI on simulator 

### ISSUE THREAD

**Issue by jeannustre** [stripe/stripe-ios#1919]
## Summary
On simulator only, entering the last digit of a card in STPCardFormView (with hardware keyboard connected and software keyboard hidden) or simply interacting with the field (with software keyboard shown) causes the following warning :
`Can't find keyplane that supports type 11 for keyboard iPhone-PortraitChoco-NumberPad; using 27059_PortraitChoco_iPhone-Simple-Pad_Default `
to be shown in the console. The app then becomes unresponsive to any touch events.

None of this seems to happen on a real device.

## Code to reproduce
Our case is a STPCardFormView embedded in a UIStackView. Simulator tested was iPhone SE (2020) on iOS 15.2, Stripe pod version is 21.11.1.

## iOS version
iOS 15.2

## Installation method
Cocoapods

## SDK version
21.11.1

## Other information
Feel free to ask for precisions. I also can try to put together an example project if you are having difficulties reproducing the issue.

**Comment by csabol-stripe** [comment]
Thanks for the report @jeannustre! I'll look into this and reach back out if I have any trouble reproducing

**Comment by csabol-stripe** [comment]
@jeannustre I've been unable to reproduce this. The `Can't find keyplane that supports type 11 for keyboard iPhone-PortraitChoco-NumberPad` message can be ignored -- it is Xcode saying that it can't find a number pad on the connected hardware keyboard.

But I tried embedding `STPCardFormView` in a `UIStackView` and haven't been hitting any issues. Could you supply some more reproduction steps?

**Comment by jeannustre** [comment]
Hello @csabol-stripe.

I have tried to setup a sample app to showcase the issue, but now I can't reproduce it even from our app 😅
I will stay alert, investigate further, and reopen this if I can manage to reproduce it reliably.

Thanks for your reactivity !
