### ISSUE TITLE
Applepay payment panel does not display properly

### ISSUE THREAD

**Issue by lvhuidan** [stripe/stripe-ios#1922]
## Summary
When using Applepay to pay, there will be a problem that the payment panel cannot be displayed normally

## Code to reproduce
The following is the specific integration code implementation in our project：
  if ([StripeAPI deviceSupportsApplePay]) {
       if (countryCode.length == 0) {
           _complation(nil, [NSError errorWithDomain:@"" code:PDPayBuninessError userInfo:@{}]);
           return;
       }
        PKPaymentRequest * paymentRequest = [StripeAPI paymentRequestWithMerchantIdentifier:merchantId country:countryCode currency:currencyCode];
       //创建金额
        NSDecimalNumber *total = [NSDecimalNumber decimalNumberWithString:finalPrice];
       //Set the description of item商品信息
        PKPaymentSummaryItem *paymentTotal = [PKPaymentSummaryItem summaryItemWithLabel:paymentSummaryName amount:total];
        paymentRequest.paymentSummaryItems = @[paymentTotal];
        STPApplePayContext * applePayContext = [[STPApplePayContext alloc] initWithPaymentRequest:paymentRequest delegate:self];
       if (applePayContext) {
           _complation(nil, nil);
           [applePayContext presentApplePayFromWindow:PD_KEYWINDOW withCompletion:nil];
       } else {
           _complation(nil, [NSError errorWithDomain:@"" code:PDPayConfigurationError userInfo:@{}]);
       }
   } else {
       _complation(nil, [NSError errorWithDomain:@"" code:PDPayNoSupportApplePay userInfo:@{}]);
   }

## iOS version
Not limited to a certain version, such as iOS15, iOS14 have found this problem

## Installation method
Install via cocoapods

## SDK version
SDK Version 21.3.0

## Other information

https://user-images.githubusercontent.com/15951239/152904386-88ee7918-9bc9-4f91-ad8c-058ace6f3974.mov

**Comment by lvhuidan** [comment]
hello, I want to know what is the reason for this? please reply asap

**Comment by ramont-stripe** [comment]
Hi @lvhuidan, I tested the code you provided and so far I'm not able to replicate the issue.

From the video, it seems that you are trying to test the app in a real device. Have you added the **Apple Pay capability** as [described in our docs](https://stripe.com/docs/apple-pay?platform=ios#setup)? I also suggest to check the logs for any potential warnings/errors.

**Comment by lvhuidan** [comment]
> Hi @lvhuidan, I tested the code you provided and so far I'm not able to replicate the issue.
> 
> From the video, it seems that you are trying to test the app in a real device. Have you added the **Apple Pay capability** as [described in our docs](https://stripe.com/docs/apple-pay?platform=ios#setup)? I also suggest to check the logs for any potential warnings/errors.

yes, I have added the function of applepay. In fact, the initialized STPApplePayContext also has value, and the method [applePayContext presentApplePayFromWindow:PD_KEYWINDOW withCompletion:nil] is also called. But,in the SDK

applePayController.present { (presented) in
             stpDispatchToMainThreadIfNecessary {
                 completion?()
             }
         }

doesn't show applepay payment panel

**Comment by ramont-stripe** [comment]
Can you try changing this line:

```objc
[applePayContext presentApplePayFromWindow:PD_KEYWINDOW withCompletion:nil];
```

to this:

```objc
[applePayContext presentApplePayWithCompletion:nil];
```

Also, does it work when you run the app in the Simulator?

**Comment by lvhuidan** [comment]
> 您可以尝试更改此行：
> 
> ```objc
> [applePayContext presentApplePayFromWindow: PD_KEYWINDOW withCompletion : nil ];
> ```
> 
> 对此：
> 
> ```objc
> [applePayContext presentApplePayWithCompletion: nil ];
> ```
> 
> 另外，当您在模拟器中运行应用程序时，它是否有效？


I tried [applePayContext presentApplePayWithCompletion:nil]; this method, but the same problem occurs

**Comment by sfriedman-stripe** [comment]
Hi @lvhuidan, sorry for the delay here. In order for us to better assist you with this integration issue, I'd love to point you to our 24/7 support on [our Discord](https://stripe.com/go/developer-chat) where we have engineers ready to help you. Thank you!
