### ISSUE TITLE
PaymentSheet doesn't present using SwiftUI

### ISSUE THREAD

**Issue by JaiJaiJordan** [stripe/stripe-ios#1927]
## Summary
When using the ExampleSwiftUIPaymentSheet and MyBackEndModel the PaymentSheet does not present a pop up sheet. 

## Code to reproduce

struct VenueCheckOutView: View {
    
    @ObservedObject var backendModel = BackendModel()
    
    @Binding var showVenueCheckOutView: Bool
    @State var venueCheckOutViewIsShowing = false
    
    var body: some View {
        
        VStack {
            
              if let paymentSheet = backendModel.paymentSheet {
                  
                PaymentSheet.PaymentButton(
                  paymentSheet: paymentSheet,
                  onCompletion: backendModel.onPaymentCompletion
                  
                ) {
                    
                  Text("Buy")
                    
                }
                  
              }
            
              if let result = backendModel.paymentResult {
                  
                switch result {
                    
                case .completed:
                  Text("Payment complete")
                case .failed(let error):
                  Text("Payment failed: \(error.localizedDescription)")
                case .canceled:
                  Text("Payment canceled.")
                    
                }
              }
            }
        
        
    }
}

//
//
//
//

import Foundation
import Stripe
import SwiftUI

class BackendModel : ObservableObject {
    
    let backendCheckOutUrl = URL(string: "XXXXXXX")!
    
    @Published var paymentSheet: PaymentSheet?
    @Published var paymentResult: PaymentSheetResult?
    
    func preparePaymentSheet() {
        
        // MARK: - Fetch the PaymentIntent and Customer information from the backend
        var request = URLRequest(url: backendCheckOutUrl)
        request.httpMethod = "POST"
        let task = URLSession.shared.dataTask(with: request, completionHandler: { [weak self] (data, response, error) in
          guard let data = data,
                let json = try? JSONSerialization.jsonObject(with: data, options: []) as? [String : Any],
                let customerId = json["customer"] as? String,
                let customerEphemeralKeySecret = json["ephemeralKey"] as? String,
                let paymentIntentClientSecret = json["paymentIntent"] as? String,
                let publishableKey = json["publishableKey"] as? String,
                let self = self else {
            // Handle error
            return
          }

          STPAPIClient.shared.publishableKey = publishableKey
            
          // MARK: - Create a PaymentSheet instance
            
          var configuration = PaymentSheet.Configuration()
            configuration.returnURL = "XXXXXXXX"
          configuration.merchantDisplayName = "Example, Inc."
          configuration.customer = .init(id: customerId, ephemeralKeySecret: customerEphemeralKeySecret)
          // Set `allowsDelayedPaymentMethods` to true if your business can handle payment
          // methods that complete payment after a delay, like SEPA Debit and Sofort.
          configuration.allowsDelayedPaymentMethods = true

          DispatchQueue.main.async {
            
              self.paymentSheet = PaymentSheet(paymentIntentClientSecret: paymentIntentClientSecret, configuration: configuration)
          }
        })
        task.resume()
        
}
    
    func onPaymentCompletion(result: PaymentSheetResult) {
        
        self.paymentResult = result
        
        if case .completed = result {
                    // A PaymentIntent can't be reused after a successful payment. Prepare a new one for the demo.
                    self.paymentSheet = nil
                    preparePaymentSheet()
                }
      }
    
}

## iOS version
macOS Big Sur Version 11.6

## Installation methoda
Apple Swift Packages

## SDK version
  - Stripe (21.11.1):

## Other information

- Im using the Run Payments with Stripe extension within Firebase. 

- My Stripe console shows successful a payment intent.

**Comment by porter-stripe** [comment]
Hi @JaiJaiJordan I was able to get the PaymentSheet presenting by making a small change to your code, it looks like you are not calling [`backendModel.preparePaymentSheet()`](https://github.com/stripe/stripe-ios/blob/master/Example/PaymentSheet%20Example/PaymentSheet%20Example/PaymentSheet%20Example/ExampleSwiftUIPaymentSheet.swift#L30) to load the PaymentSheet on first load. I added a call to `preparePaymentSheet` in the `onAppear` of your `VStack` and I am able to see the PaymentSheet presenting and able to charge a test card.

Let me know if this resolves your issue.

```swift
VStack {
    if let paymentSheet = backendModel.paymentSheet {
      PaymentSheet.PaymentButton(
        paymentSheet: paymentSheet,
        onCompletion: backendModel.onPaymentCompletion
      ) {
        Text("Buy")
      }
    }
    
    if let result = backendModel.paymentResult {
        switch result {
        case .completed:
            Text("Payment complete")
        case .canceled:
            Text("Payment failed")
        case .failed(let error):
            Text("Payment failed: \(error.localizedDescription)")
        }
    }
    
}.onAppear { backendModel.preparePaymentSheet() }
```

**Comment by JaiJaiJordan** [comment]
Thanks Porter. Still can't get it to work. 
I guess the question is where do I put this VStack and how is it initiated? 
I guess I need to give more context regarding my implementation, as that might be the problem. I have a .fullScreenCover(Calendar) pop up that shows a calendar, the user can select a date which then prompts a new .fullScreenCover(Book and pay now) pop up that shows all of the booking details including the price and a pay button. Ive tried adding the paymentSheet VStack to the Book and pay now .fullScreenCover() pop up sheet, I have also tried adding it as a third .fullScreenCover() pop up. hope that makes sense?

**Comment by porter-stripe** [comment]
@JaiJaiJordan it's difficult to contextualize your environment without much code examples, if you can provide a sample project which reproduces this issue we can look into it, but without clear reproducible steps it's difficult to give recommendations.

**Comment by JaiJaiJordan** [comment]
// Payment details

import SwiftUI
import SDWebImageSwiftUI
import Firebase
import FirebaseAuth
import FirebaseFirestore
import Stripe

struct VenuePaymentPopUp: View {
    
    @ObservedObject var backendModel = BackendModel()
    
    var venue: Venue
    
    @Binding var currentDate: Date
    
    //Payment properties
    @Binding var showVenuePaymentPopUp: Bool
    @State var venuePaymentPopUpIsShowing = false
    
    @Binding var showVenueCheckOutView: Bool
    @State var venueCheckOutViewIsShowing = false
    
    //Venue booking properties
    @State var venueID: String = UUID().uuidString
    @State var venueBookingID: String = UUID().uuidString
    @State var venueFullDayCharge: String = ""
    
    //Custom button property
    @Environment(\.presentationMode) var presentationMode: Binding<PresentationMode>
    
    private func formatDate() -> [String] {
        
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "E, dd MMM yyyy"
        let formattedDateString = dateFormatter.string(from: currentDate)
        
        return ["\(formattedDateString)"]
    }
    
    var body: some View {
        
        VStack (spacing: 0) {
            
            Group {
                
                HStack {
                    
                    Text("Book & pay now")
                        .font(.largeTitle)
                        .bold()
                        
                    Spacer()
                    
                }
                .padding(.horizontal, 30)
                .padding(.vertical, 20)
                
                HStack {
                    
                Text("Venue details")
                    .font(.headline)
                
                    Spacer()
            
                }
                .padding(.horizontal, 30)
                .padding(.vertical, 20)
                
                HStack {
                    
                    WebImage(url: URL(string: venue.venueHeroImageUrl))
                        .resizable()
                        .aspectRatio(contentMode: .fill)
                        .frame(width: 120, height: 80)
                        .clipShape(RoundedRectangle(cornerRadius: 10))
                        .padding(.trailing, 5)
                    
                    VStack (alignment: .leading) {
                        
                        Text("\(venue.venueName)")
                            .font(.footnote)
                            .bold()
                            .padding(.bottom, 5)
                        
                        Text("\(venue.venueDisplayAddress)")
                            .font(.footnote)
                        
                    }
                    
                }
                .padding(.horizontal, 30)
                .padding(.bottom, 10)
                
                HStack {
                    
                Text("Event details")
                    .font(.headline)
                    
                Spacer()
        
                }
                .padding(.horizontal, 30)
                .padding(.vertical, 20)
                
                HStack {
                    
                    Text("No. of people:")
                    
                    Spacer()
                    
                    Text("\(venue.venueCapacity)")
                    
                }
                .padding(.horizontal, 30)
                .padding(.bottom, 10)
                
                HStack {
                    
                    Text("Date:")
                    
                    Spacer()
                    
                    Text("\(formatDate()[0])")
                    
                }
                .padding(.horizontal, 30)
                .padding(.bottom, 10)
                
                HStack {
                    
                    Text("Time:")
                    
                    Spacer()
                    
                    Text("All day")
                    
                }
                .padding(.horizontal, 30)
                .padding(.bottom, 30)
                
            }
            
            HStack {
            
            Text("Price details")
                .font(.headline)
                
                Spacer()
        
                }
                .padding(.horizontal, 30)
                .padding(.vertical, 20)
            
            HStack {
                
                Text("Full day venue hire")
                
                Spacer()
                
                Text("$\(Double(venue.venueFullDayCharge) ?? 0, specifier: "%.2f")")
                
                
            }
            .padding(.horizontal, 30)
            .padding(.bottom, 10)
            
            HStack {
                
                Text("Total")
                    .bold()
                
                Spacer()
                
                Text("$\(Double(venue.venueFullDayCharge) ?? 0, specifier: "%.2f")")
                    .bold()
                
            }
            .padding(.horizontal, 30)
            .padding(.bottom, 60)
            
            HStack {
                
                Button {
                    
                    self.deleteVenueBooking()
                    
                    self.presentationMode.wrappedValue.dismiss()
                    
                } label: {
                    
                    ZStack {
                        
                        Rectangle()
                            .frame(width: 180, height: 60)
                            .foregroundColor(Color("eventsGray"))
                            .cornerRadius(20)
                        
                        Text("Cancel")
                            .foregroundColor(.black)
                        
                    }
                    
                }
                
                Button {
                        
                        self.confirmVenueBooking()
                        venueCheckOutViewIsShowing = true
                    
                    } label: {
                        
                        ZStack {
                            
                            Rectangle()
                                .frame(width: 180, height: 60)
                                .foregroundColor(Color("getStartedBlue"))
                                .cornerRadius(20)
                            
                            Text("Pay")
                                .bold()
                                .foregroundColor(.white)
                            
                        }
                    }
                 
            }
            .padding(.horizontal, 30)
            
            Spacer()
            
        }
        .fullScreenCover(isPresented: $venueCheckOutViewIsShowing, content: {
            
            VenueCheckOutView(venue: venue, showVenueCheckOutView: $venueCheckOutViewIsShowing)
            
        })
        .onAppear {
            
            self.createDraftVenueBooking()
            
            createVenueCheckOutSession()
            
        }
        
    }
    
    func createVenueCheckOutSession() {
        
        let db = Firestore.firestore()
        let firebaseUser = Auth.auth().currentUser?.uid
        let venueRef = db.collection("customers").document("\( firebaseUser!)").collection("checkout_sessions").document()
        
        venueRef.setData([
            
            "client": "mobile",
            "mode": "payment",
            "amount": "\(venue.venueFullDayCharge)",
            "currency": "aud",
            
        ]) { error in
            
            if let error = error {
                
                print("Error updating document: \(error)")
                
            } else {
                
                print("Document successfully updated")
                
            }
            
        }
        
    }
}

//
//
// VenueCheckOutView

import SwiftUI
import Stripe
import Firebase
import FirebaseAuth

struct VenueCheckOutView: View {
    
    @ObservedObject var backendModel = BackendModel()
    var venue: Venue
    
    @Binding var showVenueCheckOutView: Bool
    @State var venueCheckOutViewIsShowing = false
    
    var body: some View {
        
        VStack {
            
                    if let paymentSheet = backendModel.paymentSheet {
                        
                        PaymentSheet.PaymentButton(
                            paymentSheet: paymentSheet,
                            onCompletion: backendModel.onPaymentCompletion
                        ) {
                            PaymentButton()
                        }
                        
                    } else {
                        
                        Loading()
                    }
            
            if let result = backendModel.paymentResult {
                
                        PaymentStatus(result: result)
                
                    }
                }
        .onAppear {
            
            backendModel.preparePaymentSheet() }
        
    }
    
}


//
//

import Foundation
import Stripe
import SwiftUI

class BackendModel : ObservableObject {
    
    let backendCheckOutUrl = URL(string: "https://pp-company-7f84a-default-rtdb.firebaseio.com")!
    
    @Published var paymentSheet: PaymentSheet?
    @Published var paymentResult: PaymentSheetResult?
    
    func preparePaymentSheet() {
        
        // MARK: - Fetch the PaymentIntent and Customer information from the backend
        var request = URLRequest(url: backendCheckOutUrl)
        request.httpMethod = "POST"
        let task = URLSession.shared.dataTask(with: request, completionHandler: { [weak self] (data, response, error) in
          guard let data = data,
                let json = try? JSONSerialization.jsonObject(with: data, options: []) as? [String : Any],
                let customerId = json["customer"] as? String,
                let customerEphemeralKeySecret = json["ephemeralKey"] as? String,
                let paymentIntentClientSecret = json["paymentIntent"] as? String,
                let publishableKey = json["publishableKey"] as? String,
                let self = self else {
            // Handle error
            return
          }

          STPAPIClient.shared.publishableKey = publishableKey
            
          // MARK: - Create a PaymentSheet instance
            
          var configuration = PaymentSheet.Configuration()
            
          configuration.merchantDisplayName = "Example, Inc."
            configuration.applePay = .init(
                               merchantId: "merchant.com.firebaseapp.pp-company-7f84a", merchantCountryCode: "AUD")
          configuration.customer = .init(id: customerId, ephemeralKeySecret: customerEphemeralKeySecret)
            configuration.returnURL = "https://pp-company-7f84a-default-rtdb.firebaseio.com"
          // Set `allowsDelayedPaymentMethods` to true if your business can handle payment
          // methods that complete payment after a delay, like SEPA Debit and Sofort.
          configuration.allowsDelayedPaymentMethods = true

          DispatchQueue.main.async {
            
              self.paymentSheet = PaymentSheet(paymentIntentClientSecret: paymentIntentClientSecret, configuration: configuration)
          }
        })
        task.resume()
        
}
    
    func onPaymentCompletion(result: PaymentSheetResult) {
        
        self.paymentResult = result
        
        if case .completed = result {
                    // A PaymentIntent can't be reused after a successful payment. Prepare a new one for the demo.
                    self.paymentSheet = nil
                    preparePaymentSheet()
                }
      }
    
}

///

Forgive me, but hopefully this what you need?

**Comment by bensnell-stripe** [comment]
Hi @JaiJaiJordan, is this issue still persisting for you? Do you already have a ticket open with our Support team for integration assistance?

**Comment by YasirAmeen** [comment]
Stripe Payment sheet is not shwoing for me as well, here is my code


//
//  StripePaymentIntentViewModel.swift
//  LhfazdezBarbering
//
//  Created by Yasir Ameen on 05/04/2024.
//

import Foundation
import Alamofire
import StripePaymentSheet



class StripePaymentIntentViewModel: ObservableObject {
    
    @Published var stripeResponse: StripeResponse?
    @Published var isError: Bool = false
    @Published var isLoading = false
    @Published var errorAlertMessage: String = ""
    @Published var showErrorAlert: Bool = false
    @Published var stripeCustomerId : String? = ""
    @Published var stripeEphermalKey : String? = ""
    @Published var stripePaymentIntent : String? = ""
    @Published var paymentSheet: PaymentSheet?
    @Published var paymentResult: PaymentSheetResult?
    

    
    func preparePaymentSheet() {
            // Ensure we have all the required details
            guard let customerId = stripeCustomerId,
                  let ephemeralKeySecret = stripeEphermalKey,
                  let paymentIntentClientSecret = stripePaymentIntent else {
                setError("Failed to obtain necessary details for payment sheet.")
                return
            }

            // Configure the Stripe API client with the publishable key
        
            STPAPIClient.shared.publishableKey = Constants.stripPublishableKeyTest

            // Configure the PaymentSheet with the customer, ephemeral key, and payment intent client secret
            var configuration = PaymentSheet.Configuration()
            configuration.merchantDisplayName = "Test"
            configuration.customer = .init(id: customerId, ephemeralKeySecret: ephemeralKeySecret)
            
            DispatchQueue.main.async {
                self.paymentSheet = PaymentSheet(paymentIntentClientSecret: paymentIntentClientSecret, configuration: configuration)
            }
        }
        
        func onPaymentCompletion(result: PaymentSheetResult) {
            DispatchQueue.main.async {
                self.paymentResult = result
                // Handle the result here, update your UI/flow as necessary
            }
        }
    
    
    func createStripeCustomer() async {
        DispatchQueue.main.async {
            self.isLoading = true
            self.showErrorAlert = false
            self.errorAlertMessage = ""
        }
        
        let url = "https://api.stripe.com/v1/customers"
       
        
        let headers: HTTPHeaders = [
            "Authorization": Constants.stripSecretTest // Replace with your actual Stripe secret key
        ]
        
        do {
            let responseModel = try await AF.request(url, method: .post, parameters: nil, encoding: URLEncoding.default, headers: headers)
                .serializingDecodable(StripeResponse.self)
                .value
            
            DispatchQueue.main.async {
                self.stripeResponse = responseModel
                self.stripeCustomerId = responseModel.id
                print("CustomerId: \(responseModel.id ?? "") ")
                self.isLoading = false
                
            }
            
        } catch {
            DispatchQueue.main.async {
                self.isError = true
                self.errorAlertMessage = "Request failed. Please check your connection and try again."
                self.showErrorAlert = true
                self.isLoading = false
            }
        }
    }
    
    func createEphemeralKey(customerId: String) async {
    
        DispatchQueue.main.async {
                self.isLoading = true
                self.showErrorAlert = false
                self.errorAlertMessage = ""
            }
            
            let url = "https://api.stripe.com/v1/ephemeral_keys"
            let parameters: [String: Any] = [
                "customer": customerId
            ]
            
            let headers: HTTPHeaders = [
                "Authorization": Constants.stripSecretTest, // Replace with your actual Stripe secret key
                "Stripe-Version": "2023-10-16"
            ]
            
            do {
                let responseModel = try await AF.request(url, method: .post, parameters: parameters, encoding: URLEncoding.default, headers: headers)
                  
                    .serializingDecodable(StripeResponse.self)
                    .value
                
                DispatchQueue.main.async {
                    self.stripeResponse = responseModel
                    self.stripeEphermalKey = responseModel.id
                    print("EphermalKey: \(responseModel.id ?? "") ")
                    self.isLoading = false
                   
                }
                
            } catch {
                DispatchQueue.main.async {
                    self.isError = true
                    self.errorAlertMessage = "Request failed. Please check your connection and try again."
                    self.showErrorAlert = true
                    self.isLoading = false
                }
            }
        }
    
    func createPaymentIntent(customerId: String, amount: Int, currency: String, description: String, customerName: String, address: String) async {
            DispatchQueue.main.async {
                self.isLoading = true
                self.showErrorAlert = false
                self.errorAlertMessage = ""
            }
            
            let url = "https://api.stripe.com/v1/payment_intents"
            let parameters: [String: Any] = [
                "customer": customerId,
                "amount": amount,
                "currency": currency,
                "description": description,
                "metadata": ["customer_name": customerName, "address": address] // Assuming you want to include these as metadata
            ]
            
            let headers: HTTPHeaders = [
                "Authorization": Constants.stripSecretTest, // Replace with your actual Stripe secret key
                "Content-Type": "application/x-www-form-urlencoded"
            ]
            
            do {
                let responseModel = try await AF.request(url, method: .post, parameters: parameters, encoding: URLEncoding.default, headers: headers)
                    
                    .serializingDecodable(StripeResponse.self)
                    .value
                
                DispatchQueue.main.async {
                    self.stripeResponse = responseModel
                    self.stripePaymentIntent = responseModel.client_secret ?? ""
                    print("Payment Inten: \(responseModel.client_secret ?? "") ")
                    self.isLoading = false
                    
                    
                }
            } catch {
                DispatchQueue.main.async {
                    self.isError = true
                    self.errorAlertMessage = "Request failed. Please check your connection and try again."
                    self.showErrorAlert = true
                    self.isLoading = false
                }
            }
        }
        
    
     func setError(_ message: String) {
        DispatchQueue.main.async {
            self.showErrorAlert = true
            self.errorAlertMessage = message
        }
    }
    
    
    
}

// ResponseModel and APIResult should be defined according to the data structure you're expecting from the Stripe API


//
//  NewPaymentTestSCreen.swift
//  LhfazdezBarbering
//
//  Created by Yasir Ameen on 06/04/2024.
//

import Foundation
import SwiftUI

struct NewPaymentTestSCreen: View {
    
    
    @StateObject var stripePaymentIntentViewModel = StripePaymentIntentViewModel()
    @State private var presentingPaymentSheet = false
    @State private var presentingCheckoutScreen = false
    
    
    var body: some View {
        Button("Create Payment Process") {
            Task {
                await createPaymentProcess()
            }
        }
        .alert(isPresented: $stripePaymentIntentViewModel.showErrorAlert) {
            Alert(title: Text("Error"), message: Text(stripePaymentIntentViewModel.errorAlertMessage), dismissButton: .default(Text("OK")))
        }
        .disabled(stripePaymentIntentViewModel.isLoading) // Disable the button when loading
    }
    
    private func createPaymentProcess() async {
        // 1. Create Stripe customer
        await stripePaymentIntentViewModel.createStripeCustomer()
        if stripePaymentIntentViewModel.isError { return }
        
        guard let customerId = stripePaymentIntentViewModel.stripeCustomerId, !customerId.isEmpty else {
            stripePaymentIntentViewModel.setError("Failed to obtain customer ID.")
            return
        }
        
        // 2. Create ephemeral key
        await stripePaymentIntentViewModel.createEphemeralKey(customerId: customerId)
        if stripePaymentIntentViewModel.isError { return }
        
        // Assume `amount`, `currency`, `description`, `customerName`, and `address` are provided correctly
        let amount = 100 // Example amount in cents
        let currency = "usd" // Example currency
        let description = "Test Payment" // Example description
        let customerName = "John Doe" // Example customer name
        let address = "123 Test Street" // Example address
        
        // 3. Create payment intent
        await stripePaymentIntentViewModel.createPaymentIntent(customerId: customerId, amount: amount, currency: currency, description: description, customerName: customerName, address: address)
        if stripePaymentIntentViewModel.isError { return }
        
        // Proceed with the successful result
        print("Payment intent created with ID: \(stripePaymentIntentViewModel.stripePaymentIntent ?? "")")
        
//        if presentingCheckoutScreen {
//            CheckoutViewControllerRepresentable(isPresented: $presentingCheckoutScreen, paymentIntentClientSecret: stripePaymentIntentViewModel.stripePaymentIntent ?? "")
//        }
        
                stripePaymentIntentViewModel.preparePaymentSheet()
        
                if !stripePaymentIntentViewModel.isError {
                    DispatchQueue.main.async {
                        self.presentingPaymentSheet = true
                    }
                }
        
    }
}

struct NewPaymentTestSCreen_Previews: PreviewProvider {
    static var previews: some View {
        NewPaymentTestSCreen()
    }
}

can any one help me? its urgent
