### ISSUE TITLE
[Feature] StripeApplePay module supports Objective-C

### ISSUE THREAD

**Issue by xuzhe** [stripe/stripe-ios#1929]
## Is your feature request related to a problem? Please describe.
I am using Stripe in my close-source SDK, in order to handle the situation that other developers do not include Stripe framework in their project, I use Objective-C to do the trick. The struct looks like below.
```Users App --(required)--> my SDK --(optional)--> Stripe```

Now, I am trying to use StripeApplePay for App Clips but the Swift only StripeApplePay module makes it must be included in other developers' project or the compile (or the bitcode compile) process won't be succeed. The problem here is StripeApplePay becomes a "must have" framework for Users App.
```Users App --(required)--> my SDK --(required)--> StripeApplePay``` 

## Describe the solution you'd like
Is there any plan to add Objective-C support to StripeApplePay in a near future?

## Describe alternatives you've considered
I tried to directly use the StripeApplePay module in my Swift code, but when other developers using my SDK building their project, they have to include StripeApplePay even they are not using Stripe at all. I am not suer but it seems that Objective-C Runtime Utilities are the only way I can do the trick?

## Additional context
none

**Comment by davidme-stripe** [comment]
Hi @xuzhe, thanks for the request. Due to limitations of the pre-iOS 13 Objective-C runtime, we don't plan to support Objective-C in this framework until we drop support for iOS 12. For full Objective-C support, you'll need to use the full Stripe framework instead of the minimal StripeApplePay framework.

That said, maybe we can find a way to make this work! Can you provide a code sample for how you'd like to integrate this? Were you planning to weak-link StripeApplePay.framework and use `NSClassFromString("STPApplePayContext")` and then call the methods dynamically?

**Comment by xuzhe** [comment]
@davidme-stripe Thank you for your reply and for sharing the details.

I'am basically using only two method to handle ApplePay in App Clips.

Here is my code working with full Stripe framework but not with StripeApplePay only (cause methods in StripeApplePay framework do not have @objc attribute, the runtime environment just cannot find them).

```
- (nullable STPApplePayContext *)createApplePayContextWithPaymentRequest:(PKPaymentRequest *)request
                                                                delegate:(id <ApplePayContextDelegateBridge>)delegate {
    self.delegate = delegate;
    return [[[StripeBridge safeSTPApplePayContext] alloc]
            initWithPaymentRequest:request delegate:self];
}

+ (void)presentApplePayContext:(STPApplePayContext *)context {
    [context presentApplePayWithCompletion:nil];
}

// - Delegate
- (void)applePayContext:(STPApplePayContext *)context
 didCreatePaymentMethod:(STPPaymentMethod *)paymentMethod
     paymentInformation:(PKPayment *)paymentInformation
             completion:(void (^)(NSString * _Nullable, NSError * _Nullable))completion {
    completion([self.delegate applePayContextGetClientSecret], nil);
}
    
- (void)applePayContext:(STPApplePayContext *)context
  didCompleteWithStatus:(enum STPPaymentStatus)status
                  error:(NSError *)error {
    StripeBridgePaymentStatus bridgeStatus;
    switch (status) {
        case STPPaymentHandlerActionStatusSucceeded:
            bridgeStatus = StripeBridgePaymentStatusSucceeded;
            break;
        case STPPaymentHandlerActionStatusFailed:
            bridgeStatus = StripeBridgePaymentStatusFailed;
            break;
        case STPPaymentHandlerActionStatusCanceled:
            bridgeStatus = StripeBridgePaymentStatusCanceled;
            break;
        default:
            break;
    }
    [self.delegate applePayContext:bridgeStatus error:error];
}

```

`[StripeBridge safeSTPApplePayContext]` returns the result of `NSClassFromString(@"STPApplePayContext");`.

Do you have any suggestion about how to dynamic call `initWithPaymentRequest:delegate:` and `presentApplePayWithCompletion:` in swift? Because as I know it requires `dynamic` attribute for these methods (I am not sure about this, if I am wrong, any key word for searching and learning would be appreciated).

**Comment by davidme-stripe** [comment]
I don't think there's a good way to do this — because the type of `didCreatePaymentMethod` is `StripeAPI.PaymentMethod`, a Swift struct, I'm not aware of a clean way to invoke it at runtime.

As one workaround, it might be possible to have two targets for your framework, "MyFramework" and "MyFrameworkWithStripe". You could have MyFrameworkWithStripe depend on StripeApplePay, and use `#if canImport` to branch your code's behavior:
```
#if canImport(StripeApplePay)
import StripeApplePay
#endif 

/* ... */

func useApplePay() {
#if canImport(StripeApplePay)
   let context = STPApplePayContext(paymentRequest: pr, delegate: self)
   /* ... */
#else
   // Do something else
#endif
}
```

**Comment by xuzhe** [comment]
@davidme-stripe Thank you for your advise. I am thinking the similar thing as you mentioned. Since there won't be an Objective-C supported StripeApplePay in the near future,  I decided to provide a separated Framework as a plug-in to support StripeApplePay only. And do the runtime tricks between the plug-in and my framework.

I am going to close this issue. Thank you again for all the details and helps.
Have a nice day!
