### ISSUE TITLE
[Feature] Allow more detailed customisation in `STPCardFormView`

### ISSUE THREAD

**Issue by le-tyang** [stripe/stripe-ios#1932]
## Is your feature request related to a problem? Please describe.
We are looking at to build a component which allows user to enter credit card details in a form like way.
😉 not the `STPPaymentCardTextField`.
We looked into `STPCardFormView` and found out it can support most of our requirements. 
Until we want to start doing customisation. 

Few things we were hoping that this component can support:
- Hide billing address fields
- Enable card scanning 
- Be able to change font color
- Be able to adjust spacing between fields. 

But due to `STPCardFormView` only expose `init(style:)` constructor as public, there is not much we can do :( 
![image](https://user-images.githubusercontent.com/80654466/156112537-8a787113-8a84-408b-931a-77e9f84cbe29.png)

## Describe the solution you'd like
We went through the source code for `STPCardFormView`, and found out most items in our wanted list are already supported, just not exposed for public usage. 

Would be good if we can make these constructors public, so we can start customising it. Constructors include:
```
convenience init(
        billingAddressCollection: PaymentSheet.BillingAddressCollectionLevel,
        includeCardScanning: Bool = true,
        mergeBillingFields: Bool = false,
        style: STPCardFormViewStyle = .standard,
        postalCodeRequirement: STPPostalCodeRequirement = .standard,
        prefillDetails: PrefillDetails? = nil,
        inputMode: STPCardNumberInputTextField.InputMode = .standard
    )

    required init(numberField: STPCardNumberInputTextField,
                  cvcField: STPCardCVCInputTextField,
                  expiryField: STPCardExpiryInputTextField,
                  billingAddressSubForm: BillingAddressSubForm,
                  includeCardScanning: Bool,
                  mergeBillingFields: Bool,
                  style: STPCardFormViewStyle = .standard,
                  postalCodeRequirement: STPPostalCodeRequirement = .standard,
                  prefillDetails: PrefillDetails? = nil,
                  inputMode: STPCardNumberInputTextField.InputMode = .standard
    )
```

## Describe alternatives you've considered
We also looked into `PaymentSheet` as what we actually wanted is just like how this component looks like in `PaymentSheet`.
![image](https://user-images.githubusercontent.com/80654466/156112864-e4b7a5c2-74b3-452a-9926-b14e5ebdedc2.png)

But due to UX preference and our user flow definition, we can't use a bottom sheet for this feature. 

And, we also considered forking the SDK, but I guess no one likes that idea 😉 

## Additional context
We've attached screenshots in above description.

**Comment by dqii** [comment]
Is there any updated timeline on this?

**Comment by dqii** [comment]
@yuki-stripe just checking if this feature is on any roadmap?

**Comment by mikeandike** [comment]
Yes i agree that this is an important feature to add.
Especially in order to allow iOS and Android to be similar. Android has CardMultilineWidget and there is no iOS equivalent

**Comment by remonh87** [comment]
Also on Android it is possible to supply a country code that makes sure you can prefill the localisation and country for the user. Would be great if you can take it along with this.

**Comment by sfriedman-stripe** [comment]
Hi all! We will not be adding further functionality to STPCardFormView or STPPaymentCardTextField. We encourage you to check out our modern replacement, the [Mobile Payment Element](https://stripe.com/docs/payments/accept-a-payment?platform=ios), and send us any feedback you have! Thank you

**Comment by remonh87** [comment]
@sfriedman-stripe  good to know will this element considered to be deprecated? Reason I ask is that we will follow your direction when it comes to our Flutter lib
