### ISSUE TITLE
Tap to Pay Support

### ISSUE THREAD

**Issue by ChaseKnowlden** [stripe/stripe-ios#1939]
## Is your feature request related to a problem? Please describe.
iOS 15.4 Adds Tap to Pay support so I would like that to be in the SDK.

## Describe the solution you'd like
Being able to pay with another phone running that version.

## Describe alternatives you've considered
iOS 15.4 Released Today

## Additional context
![IMG_0016](https://user-images.githubusercontent.com/46290258/158276989-459b9a6b-10a2-48bd-a7f8-d39e15eb0bd0.PNG)

**Comment by ramont-stripe** [comment]
Hi @ChaseKnowlden, thanks for reaching out! This feature is currently offered through the [Stripe Terminal iOS SDK](https://github.com/stripe/stripe-terminal-ios) (our SDK for in-person payments) and it is part of a closed beta program. Feel free to fill out the form in this page if you are interested in integrating Tap to Pay into your app:

https://stripe.com/terminal/tap-to-pay-on-iphone

**Comment by ChaseKnowlden** [comment]
OK, Got That.
