### ISSUE TITLE
Fingerprint is not coming in token response

### ISSUE THREAD

**Issue by Yogesh-MV** [stripe/stripe-ios#194]
I am using this library for generating the token. But I am not getting the fingerprint in API response. Then I have analysed the documentation, in that they mentioned for generating the token, we have to use the "Secret Key" but in the library "Publish Key" is used for generating the token. I hope this is the reason I am not getting the "fingerPrint" in API response. Because "fingerPrint" is needed to check the card duplicate issue.

**Comment by raycmorgan** [comment]
This is the correct behavior. What you will need to do is send the token ID to your server and refetch the token (via `GET /v1/tokens/{token_id}`) with your secret key. The response of this request will contain the fingerprint to perform this check.

**Comment by Yogesh-MV** [comment]
Thanks for the response.

I also checked about this. Using the secret key in client side is not advisable. So I will do this as you mentioned.
