### ISSUE TITLE
[BUG] Cannot Archive with Xcode 13.3

### ISSUE THREAD

**Issue by bhanuka96** [stripe/stripe-ios#1943]
Cannot Archive with Xcode 13.3

**Error Message**
`Incremental compilation has been disabled: it is not compatible with whole module optimization on Release build configuration`

**Comment by ramont-stripe** [comment]
Hi @bhanuka96, which version of the SDK are you using and how was it installed?

**Comment by mtallenca** [comment]
I'm also see this - works fine with Xcode 13.2.1, fails with Xcode 13.3 - I think it's a bug with Xcode 13.3

**Comment by samatron** [comment]
Also seeing the same issue with Xcode 13.3 - currently cannot archive even after updating minimum iOS deployment 12.0.

**Comment by bhanuka96** [comment]
> Hi @bhanuka96, which version of the SDK are you using and how was it installed?

Stripe SDK VERSION `21.12.0`

It's working fine with xCode 13.2.1

**Comment by davidme-stripe** [comment]
We're still having trouble reproducing this on our end — any additional info or sample projects would be helpful! We're also watching a similar issue on [Apple's dev forums](https://developer.apple.com/forums/thread/701981).

**Comment by jeannustre** [comment]
I have the same issue under Xcode 13.3.1, happening with both debug and release builds.
This seems like a problem of the error message being too generic - I wouldn't follow the leads of the Apple dev's forums as these seem a bit hacky. I'll try to provide some info.

I'm using version 21.11.1 (for backwards compatibility reasons, not sure if this is still relevant - we target iOS 12) through Cocoapods.
Interesting thing is, everything works fine under 13.3.1 until I embed a watchOS app target in the iOS target, which makes the error appear. It then goes away if I stop embedding the watchOS app.

The watchOS target doesn't use the Stripe pod so I'm not sure why this would occur.
As reported by others, everything is working fine under Xcode 13.2.1.

**Comment by lukeleleh** [comment]
If helps anyone, I experienced the same issue with Xcode 13.3 but with versions 13.2.1 and 13.4.1, the archive finishes with no errors! 🙌

**Comment by porter-stripe** [comment]
Closing as stale and since requiring Xcode 14 on the App Store is near.
