### ISSUE TITLE
[BUG] StripeIdentity not working for test client secret

### ISSUE THREAD

**Issue by heywhy** [stripe/stripe-ios#1950]
## Summary

Trying to test the StripeIdentity library does not work when given client secret generated under test mode. See https://github.com/stripe/stripe-ios/blob/bec29cf5dd0f288c19104ab8ac84ae7fcc809a3e/StripeIdentity/StripeIdentity/Source/VerificationClientSecret.swift#L35 for the reason. Session secrets generated in test mode has `vs_1Kn0IgBc800qdJSZyte9woRf_secret_test_YWNjdF8xSXNtTXFCYzgwMHFkSlNaLF9MVHlGbjRGTk1PSHE4Um52UDlYRFBqNXhVS1dLaEJT0100ifPMVh94` and the regex check does not cater for the `test` word.

## iOS version
15.4

## Installation method

Pod

## SDK version

v22.1

**Comment by heywhy** [comment]
And I will like to point out that StripeIdentity does not for live client secrets too because both secrets have the live or test word in them that's not catered for in the SDK.

**Comment by mludowise-stripe** [comment]
Thank you for filing this! We've incorporated a fix into [22.1.1](https://github.com/stripe/stripe-ios/releases/tag/22.1.1)
