### ISSUE TITLE
[BUG] you cannot perform the action on PaymentIntents created by checkout

### ISSUE THREAD

**Issue by haor1** [stripe/stripe-ios#1951]
## Summary

I am following the Stripe guide 'Online Payments' -> 'Accept a payment' for iOS. When I attempt a test payment, the Stripe PaymentSheet UI displays 'you cannot perform the action on PaymentIntents created by checkout' right above the "Pay" button. My backend returns the 'paymentIntentClientSecret' (client_secret field of the PI object) that is required when instantiating the PaymentSheet. I don't understand the issue and how can I resolve this?

https://stripe.com/docs/payments/accept-a-payment?platform=ios

## iOS version
iOS 12

## Installation method
Swift package manager

## SDK version
22.1.1

**Comment by ramont-stripe** [comment]
Hi @haor1 

Can you share more details on how the PaymentIntent is being created? For example: which backend library are you using, version, and API method.

**Comment by tnt-ndriqimrr** [comment]
@haor1 this issue is happening to me, can you explain the fix you used if you found any?
