### ISSUE TITLE
[Feature] allow to specify a pricing for setup intent payment sheet

### ISSUE THREAD

**Issue by dragouf** [stripe/stripe-ios#1952]
## Is your feature request related to a problem? Please describe.
when displaying payment sheet for a setup intent, price information is always shown as "Amount Pending".
Unfortunately in some countries it's not legal and consequently it's rejected by Apple validation.

## Describe the solution you'd like
I see here: https://github.com/stripe/stripe-ios/blob/f8bba7f97b350699ba238b83954beda7237bbbe6/Stripe/STPApplePayContext%2BPaymentSheet.swift#L73

a PKPaymentSummaryItem is always added with pending. We should be able to specify a price to display a fixed price. 
Ideally we should use PKRecurringPaymentSummaryItem 
 (https://developer.apple.com/documentation/passkit/pkrecurringpaymentsummaryitem) in case setup is linked with a subscription (most of the time).

## Describe alternatives you've considered
no solution right now

**Comment by ramont-stripe** [comment]
Thanks for reporting this. This feature is in our roadmap, but we don't have a timeline to share yet. We'll keep this issue updated with the progress.

**Comment by yuki-stripe** [comment]
@dragouf We've shipped a workaround that allows PaymentSheet users to directly supply Apple Pay line items https://github.com/stripe/stripe-ios/releases/tag/22.5.0. This API is a proxy for [PKPaymentRequest.paymentSummaryItems](https://developer.apple.com/documentation/passkit/pkpaymentrequest/1619231-paymentsummaryitems).
