### ISSUE TITLE
[BUG] Type 'PaymentSheet' has no member 'Configuration'

### ISSUE THREAD

**Issue by Ju-Long** [stripe/stripe-ios#1954]
## Summary

when using the `PaymentSheet.Configuration()` it returns `Type 'PaymentSheet' has no member 'configuration'`

## Code to reproduce

```
import SwiftUI
import Stripe
import StripeCore
import StripeUICore

var configuration = PaymentSheet.Configuration() //Error: Type 'PaymentSheet' has no member 'configuration'
configuration.customer = .init(id: customerID, ephemeralKeySecret: ephemeralKey) //Error: Cannot infer contextual base in reference to member 'init'
```

## iOS version

iOS 15, Xcode Version 13.3.1

## Installation method

pod

## SDK version

22.2.0

**Comment by davidme-stripe** [comment]
Hello, thanks for filing this! Do you have another type named `PaymentSheet` in your app, or are you importing another package that has a `PaymentSheet` class? 

If so, you should be able to resolve the ambiguity by using `Stripe.PaymentSheet.Configuration()`. If that works, could you let us know which package is causing the name collision?

**Comment by Ju-Long** [comment]
Hello thank you for the advice. Yes i miss out on the face that i had created the swift file name as `PaymentSheet` and it generated a struct along with the same name.

**Comment by davidme-stripe** [comment]
Ah, that explains it. Thanks for the update!
