### ISSUE TITLE
[BUG] Localized error strings not being translated to Spanish

### ISSUE THREAD

**Issue by maganap** [stripe/stripe-ios#1964]
## Summary

I'm using [flutter_stripe](https://pub.dev/packages/flutter_stripe) package for an app developed in Flutter. After some initial setup, this package automatically sets the payment bottom sheet language to the language configured on the cell phone.

We're working in Spanish es-ES. The bottom sheet certainly shows in Spanish, but the localizad error messages are always shown in English. For example, when closing the sheet without paying, a `StripeException` is received with a `LocalizedErrorMessage`. The `localizedMessage` property is supposed to be translated, but it is not.

I asked a question to this flutter package support and I was told the localized messages come directly from the native Stripe SDK, they're a bridge to Flutter so I should open a case here. I'm sorry I can't really give you more details on the problem since I don't know the way this package works internally.

## iOS version

iOS 15.4.1

## Installation method

Through [flutter_stripe](https://pub.dev/packages/flutter_stripe) package.

## SDK version

Stripe 22.0.0 from Podfile.lock

## Other information

This problem is actually happening in Android as well, but anyway I was told to report to the native SDK. If there's anything else you can explain me to verify so I can give you better information, please let me know. Thanks!

**Comment by yuki-stripe** [comment]
Hello @maganap, can you provide an example of an error string you're seeing in English?

**Comment by maganap** [comment]
@yuki-stripe Sure!

This is in iOS using es-ES language in the phone settings. The sheet is properly shown in Spanish:

<img src="https://user-images.githubusercontent.com/6942131/171698831-3ba814d2-9ba1-4f21-bae2-a0087c1759eb.PNG" width="300">

but when cancelled the error string is shown in English:

<img src="https://user-images.githubusercontent.com/6942131/171698856-5186e8c8-d690-4e60-86ae-6f89f9e6a65b.PNG" width="300">

The snackbar is showing: `errorMessage = 'Stripe: ${e.error.localizedMessage}';` after the exception is thrown when the sheet is closed without paying.

Thanks for taking a look at it

**Comment by yuki-stripe** [comment]
Thanks for the example! I'm not familiar with the flutter SDK, does it provide anything besides an error? For example, our native SDKs return a status _enum_ of success, cancel, or failure(error).  This way you can not show anything to the user if they merely canceled.

**Comment by yuki-stripe** [comment]
Hello @remonh87!  Super helpful, thank you.

The React Native SDK has something similar, I think - [ErrorType](https://github.com/stripe/stripe-react-native/blob/c2ec63fd24a98118033162f6d6e2ffd7e840927d/ios/Errors.swift#L3-L7) to let you know if this was merely a cancellation. The SDK converts the 'cancel' case [here](https://github.com/stripe/stripe-react-native/blob/3a5d2cc2d8294acbe5661dae18f5c25f2b23d37c/ios/StripeSdk.swift#L247).


Usage in RN looks something like
```
const { error } = await presentPaymentSheet();

if (!error) {
      // success
    } else if (error.code === PaymentSheetError.Failed) {
      // failed
    } else if (error.code === PaymentSheetError.Canceled) {
      // canceled
    }
}
```

**Comment by yuki-stripe** [comment]
@maganap Ah, yes this is confusing...thank you for the feedback!  Adding an item for us to improve the documentation here.

**Comment by AristideVB** [comment]
So if I understand @yuki-stripe  this correctly localizedMessage isn't actually... **localized** ? 😢

**Comment by maganap** [comment]
@AristideVB Yes, but no. 😅 

Internal error texts are indeed translated.

The only exception actually thrown that you can catch is the cancelled exception (which you can just avoid showing at all). This is the case that I reported that was not translated.

The other payment failure error texts are directly shown on the bottom sheet (properly translated) without your intervention.

For example, "insufficient funds" will be shown to the user on the bottom sheet if they try to pay without funds (and you won't even know in your source code, it's handled internally).
The user can either retry with a different card (so you receive a payment success) or close the bottom sheet (then you receive a thrown cancelled error).

**Comment by AristideVB** [comment]
Ok @maganap 🙂 but I'm not using the bottom sheet, I'm using the Credit Card field on it's own & I've seen a `localizedMessage` internal error `"Card details not complete" ` untranslated is that normal, should I expect all errors thrown in the `localizedMessage` not to be translated ?

**Comment by maganap** [comment]
@AristideVB oh, I'm not even using `stripe-ios` package directly, but through `flutter_stripe`, where the typical use is with the bottom sheet. Sorry I can't help with that.

**Comment by AristideVB** [comment]
@maganap Using flutter_stripe too but with the Credit Card field
