### ISSUE TITLE
[Feature] Qatar is not in the list of countries

### ISSUE THREAD

**Issue by kingkick2008** [stripe/stripe-ios#1967]
Qatar is not in the list of countries on iPhones devices.
![169064908-8cc029c0-d785-4806-b884-305d357fee4b](https://user-images.githubusercontent.com/23032240/169116626-5a7c5fbc-832d-43d5-aa17-55ccc37c66ce.png)

**Comment by porter-stripe** [comment]
Hi @kingkick2008 you are correct Qatar is missing! We have a fix submitted and hope to have it released on Monday. The fix will include Qatar and many African and Middle Eastern countries. I'll update this issue once released!

**Comment by porter-stripe** [comment]
This has been fixed in [22.4.0](https://github.com/stripe/stripe-ios/releases/tag/22.4.0)!
