### ISSUE TITLE
[Feature] Modernize STPJSONResponseCompletionBlock, or provide a Decodable type, or provide less painful signature 

### ISSUE THREAD

**Issue by rromanchuk** [stripe/stripe-ios#1972]
## Is your feature request related to a problem? Please describe.
I am trying to modernize my developer provided 
```swift 
class StripeUserService: NSObject, STPCustomerEphemeralKeyProvider
```
but `public typealias STPJSONResponseCompletionBlock = ([AnyHashable: Any]?, Error?) -> Void` makes this awkward.

Alamofire's `.responseJSON` will soon be removed as well
`@available(*, deprecated, message: "responseJSON deprecated and will be removed in Alamofire 6. Use responseDecodable instead.")`

## Describe the solution you'd like
In a modern swift context, transforming a network request to the expected `[AnyHashable: Any]` is clunky and anti-pattern. Ideally implementation would look something like this.

```swift
do {
  let key = try await  req.validate().serializingDecodable(STPEphemeralKey.self).value
  completion(key, nil)
catch {
  completion(nill, error)
}
```

## Describe alternatives you've considered

I was poking around  and saw some generics like `StripeDecodable` (not exposed, and specifically says not for public in comments) `STPEphemeralKey` (doesn't conform to Decodable).

I gave up, andnow  just taking the string body, and then used the compiler to auto complete my way through jamming it back into `[String: AnyObject]`

```swift
            do {
                let payload = try await req.validate().serializingString().value
                let data = payload.data(using: .utf8)!
                let json = try JSONSerialization.jsonObject(with: data)
                completion(json as? [String: AnyObject], nil)
                
            } catch {
                completion(nil, error)
            }
```

## Additional context
On a related note, this API (POST /ephemeral_keys) seems to have vanished off the internet.  Like every lazy developer, i was just trying to find an example payload without needing to fire up a terminal. 

Attempts to find an example payload: 
https://github.com/stripe/stripe-ruby/blob/ca8a36769e0db392e0ddb8d27e492d15052046b0/test/stripe/ephemeral_key_test.rb

https://stripe.com/docs/api?lang=curl

https://stripe.com/docs/api?lang=ruby

https://github.com/stripe/stripe-ios/blob/master/Stripe/STPEphemeralKeyProvider.swift#L19

For the fellow lazy, here is the payload

```ruby
Stripe::EphemeralKey.create({}).to_json
```

```json
{
"id": "ephkey_foo",           
  "object": "ephemeral_key",                         
  "associated_objects": [                            
    {"id":"cus_foo","type":"customer"}    
  ],                                                 
  "created": 1654288414,                             
  "expires": 1654292014,                             
  "livemode": false,                                 
  "secret": "ek_test_foo"
} 
```

Would be nice if it was just `String?`, and then stripe worried about backfilling, even if it required a GET 
```swift
struct MyEphemeralKey: Decodable {
    let secret: String
}
completion(MyEphemeralKey(secret: "foo").secret, nil)
```

**Comment by davidme-stripe** [comment]
Hello, thanks for filing this!

* It looks like you're using our older "Basic Integration" product. Our newer [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet) UI only requires that you pass in the ephemeral key's secret string, as you suggested here. Would this work for you?
* We're building a new `Codable` version of our public API bindings, but we don't have an ETA for that yet.
* Sorry, but we don't have documentation for `/v1/ephemeral_keys` — it started as a niche endpoint for this SDK, but grew to serve other purposes over time. We'll look into adding some documentation for it to the API reference.

**Comment by rromanchuk** [comment]
@davidme-stripe yeah i figured there would be new flows, or this was deprecated. I was just sweeping up some code. 

In this context i'm literally just using it to display payment methods, and to poll status, basically to offload this minor UI component direct to stripe, from the client. 

I'll check out this new product too, although i tend to always have to drop down to the lowest level intents API because my use case looks nothing like a "add items to cart and checkout"

**Comment by rromanchuk** [comment]
@davidme-stripe `PaymentSheet` is really great.  Check out this first pass, for an anywhere, on-demand `UIKit` extension using `async/await`.  Didn't have to re-implement any backend components, and was able to remove a huge amount of complexity.  I'm already using drawers for onboarding, so this works naturally, "as  is". The calling controller can do everything it needs with `PaymentSheetResult`, and removes a spaghetti mess of delegates, observers, and callbacks.  

```swift

import UIKit
import class Stripe.PaymentSheet
import enum Stripe.PaymentSheetResult

extension UIViewController {
    func showStripePaymentSheet() async throws -> PaymentSheetResult {
        guard let customerId = await SPAR.currentUser()?.stripe_customer_id else {
            throw SparRuntimeError.error("Missing required customer account.")
        }
        
        let setupIntent = try await BillingService.createSetupIntent()
        let ephemeralKey = try await StripeUserService.fetchEphemeralKey()
        
        var configuration = PaymentSheet.Configuration()
        configuration.allowsDelayedPaymentMethods = true
        configuration.customer = .init(id: customerId, ephemeralKeySecret: ephemeralKey.secret)
        configuration.returnURL = C.Stripe.config.return_url
        
        let paymentSheet = PaymentSheet(setupIntentClientSecret: setupIntent.client_secret, configuration: configuration)
        let result: PaymentSheetResult = await withCheckedContinuation { continuation in
            paymentSheet.present(from: self) { paymentResult in
                continuation.resume(returning: paymentResult)
            }
        }
        
        switch result {
        case .completed:
            break
        case .canceled:
            async let _ = try? await BillingService.cancelSetupIntent(setupIntent.id)
        case .failed(let error):
            async let _ = try? await BillingService.cancelSetupIntent(setupIntent.id)
            
        }
        
        return result
    }
}
```

**Comment by MarvinNazari** [comment]
> Hello, thanks for filing this!
> 
> * It looks like you're using our older "Basic Integration" product. Our newer [PaymentSheet](https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet) UI only requires that you pass in the ephemeral key's secret string, as you suggested here. Would this work for you?
> * We're building a new `Codable` version of our public API bindings, but we don't have an ETA for that yet.
> * Sorry, but we don't have documentation for `/v1/ephemeral_keys` — it started as a niche endpoint for this SDK, but grew to serve other purposes over time. We'll look into adding some documentation for it to the API reference.

@davidme-stripe: dosen't ephemeral key get expired after some time? how would it get refreshed?
