### ISSUE TITLE
[BUG] Build errors on Xcode 14 beta 1

### ISSUE THREAD

**Issue by robm92** [stripe/stripe-ios#1973]
## Summary

Xcode 14 beta 1 presents a build error in STPApplePayContext.swift l:240 

`'(any PKPaymentAuthorizationControllerDelegate) -> ((PKPaymentAuthorizationController, PKShippingMethod, @escaping (PKPaymentRequestShippingMethodUpdate) -> Void) -> Void)?' is not convertible to 'pkDidSelectShippingMethodSignature' (aka 'Optional<((PKPaymentAuthorizationControllerDelegate) -> (PKPaymentAuthorizationController, PKShippingMethod, @escaping (PKPaymentRequestShippingMethodUpdate) -> ()) -> ())>')`

## Code to reproduce
N/A

## iOS version
N/A

## Installation method
SPM

## SDK version
22.4.0

**Comment by gutaker** [comment]
Quick hotfix, to get rid of the error is to remove casting to `pkDidSelectShippingMethodSignature`, so the code looks like this:
```
let pk_didSelectShippingMethod = #selector(
            PKPaymentAuthorizationControllerDelegate.paymentAuthorizationController(
                _:didSelectShippingMethod:handler:))
```
Dunno how its gonna impact the whole `Stripe` component functionality, for me thou, it was enough to compile my app and start working on other features.

**Comment by davidme-stripe** [comment]
Thanks for filing this! There are a few issues with compiling on Xcode 14 — we'll try to have a branch up soon.

**Comment by stephengilroy-grx** [comment]
Thanks for being so quick on this!

**Comment by jhirshland-dackinc** [comment]
thank you!

**Comment by davidme-stripe** [comment]
Here's the branch: https://github.com/stripe/stripe-ios/tree/xcode-14-b1

We haven't had a chance to try everything yet — please don't release any builds using this branch to the App Store. We'll merge in these changes before the next minor SDK release.

**Comment by davidme-stripe** [comment]
These changes landed in [22.5.0](https://github.com/stripe/stripe-ios/releases/tag/22.5.0), so I'll close this out.

FYI, if you're running into similar issues in your own projects and need to support multiple Xcode versions, you can use the [`#if compiler(>=5.7)` directive](https://github.com/apple/swift-evolution/blob/main/proposals/0212-compiler-version-directive.md) to conditionally compile based on the Swift compiler version.

**Comment by EliteTechnicalCare** [comment]
> These changes landed in [22.5.0](https://github.com/stripe/stripe-ios/releases/tag/22.5.0), so I'll close this out.
> 
> FYI, if you're running into similar issues in your own projects and need to support multiple Xcode versions, you can use the [`#if compiler(>=5.7)` directive](https://github.com/apple/swift-evolution/blob/main/proposals/0212-compiler-version-directive.md) to conditionally compile based on the Swift compiler version.

I am still seeing this issue on 22.7.0 with Xcode 14 Beta 5

**Comment by FrankWuoO** [comment]
Same issue happens with 22.7.0 on Xcode 14 Beta 6

**Comment by zohairhadi** [comment]
Im having this issue with Xcode 14.0.1. Fixed it using the fix mentioned previously @gutaker

**Comment by idanCohenDev** [comment]
Downgrading XCode to 13.4.1 solved it for me

**Comment by zohairhadi** [comment]
> Downgrading XCode to 13.4.1 solved it for me
Yea that will work, but it should also work for 14.0.1

**Comment by BerkeAras** [comment]
I am using Xcode Version 14.2 (14C18) , Expo SDK 45, but nothing works 😞

**Comment by jorger5** [comment]
Having trouble too on Xcode v14.2! Maybe this should be re opened?

**Comment by davidme-stripe** [comment]
For users using Expo, are you on the latest version of the SDK? You may need to run `expo install @stripe/stripe-react-native` to update. https://github.com/stripe/stripe-react-native/issues/1183#issuecomment-1338479585

**Comment by emthomas** [comment]
> I am using Xcode Version 14.2 (14C18) , Expo SDK 45, but nothing works 😞

Same here. With Flutter

**Comment by seltsamonkel** [comment]
Using xcode 14.2 (14C18), Expo 45, stripe-react-native 0.6.1, we bumped into this issue and tried to fix it by: https://github.com/stripe/stripe-ios/issues/1973#issuecomment-1148364509

while it fixed that specific error but encountered `stored properties cannot be marked potentially unavailable with '@available'` errors in
- `Stripe/Stripe/CardDetailsEditView.swift:90:6`
- `Stripe/Stripe/STPAddCardViewController.switf:132:6`

changed those 2 parts of the code by creating a wrapper property, e.g. for `CardDetailsEditView.swift`
```
    private var _cardScanningView: Any?
    
    @available(iOS 13, macCatalyst 14, *)
    var cardScanningView: CardScanningView? {
        get { return _cardScanningView as? CardScanningView}
        set { _cardScanningView = newValue }
    }
```
then in `init` after `super.init`
```
        if #available(iOS 13, macCatalyst 14, *) {
            self.cardScanningView = {
                if !STPCardScanner.cardScanningAvailable() {
                    return nil  // Don't initialize the scanner
                }
                let scanningView = CardScanningView()
                scanningView.alpha = 0
                scanningView.isHidden = true
                return scanningView
            }()
        }
```

I don't know the full impact of the changes above, but as far as our app is concerned it's working no problem.

**Comment by Jitendrawebkul** [comment]
Thanks a lot!

**Comment by folusara** [comment]
> pkDidSelectShippingMethodSignature

please what file am i use this code. Ive been battling this since this morning. Kindly help!

**Comment by orgesballa** [comment]
@folusara 
STPApplePayContext is the name of the file.

Method: _delegateToAppleDelegateMapping()
