### ISSUE TITLE
[BUG] Xcode 14 beta 1 - Build error using @available on stored properties

### ISSUE THREAD

**Issue by robm92** [stripe/stripe-ios#1974]
## Summary

Xcode 14 beta 1 presents build errors on 
CardDetailsEditView l:90
STPAddCardViewController l:132

`Stored properties cannot be marked potentially unavailable with '@available'`
 
## Code to reproduce
N/A

## iOS version
N/A

## Installation method
SPM

## SDK version
22.4.0

## Other information
N/A

**Comment by davidme-stripe** [comment]
Duping this to https://github.com/stripe/stripe-ios/issues/1973.

**Comment by ParthAmexLoungeBuddy** [comment]
Apparently, it is not a bug in compiler. All SDKs need to be updated if they are incorrectly using @available

Stored properties in Swift can’t have type information that is potentially unavailable at runtime. However, prior to Swift 5.7 the compiler incorrectly accepted @available attributes on stored properties when the property had either the lazy modifier or an attached property wrapper. This could lead to crashes for apps running on older operating systems. The Swift compiler now consistently rejects @available on all stored properties. (82713248) (FB9594187)

Please check official release notes
https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes

**Comment by ParthAmexLoungeBuddy** [comment]
We are using 21.6.0 package, please advise what version should we update for xcode 14 compatibility
