### ISSUE TITLE
[BUG] stripeError not handled. SDK getting crash while making the payment using ApplePay

### ISSUE THREAD

**Issue by Rthangavel** [stripe/stripe-ios#1979]
## Summary
 App getting crash while trying to make the Apple Pay. Screenshot [attached](url)
<img width="1512" alt="Screenshot 2022-06-14 at 12 32 55 PM" src="https://user-images.githubusercontent.com/6559613/173805338-e535098a-7133-4adf-83d2-63bd8b1f60cb.png">

## iOS version
 15.0.1

## Installation method
 Pod and swift package dependence

**Comment by yuki-stripe** [comment]
Hello @Rthangavel, could you answer a few things for me to help debug?

- Can you print out the stripeError here (you can run the command `po stripeError` in the debugger)?
- What Xcode version are you using?
- Do you have exception breakpoints enabled?

**Comment by Rthangavel** [comment]
Hi Yuvi,

1. strripeError  -> nil
2. Xcode version -> 13.3.1 (13E500a)
3. Exception breakpoint not enabled.

**Comment by sfriedman-stripe** [comment]
Hi @Rthangavel, closing this down since we haven't heard from you in a while. Feel free to reopen if you're still having issues!
