### ISSUE TITLE
[BUG] 'AVCaptureDevice' is only available in Mac Catalyst 14.0 or newer

### ISSUE THREAD

**Issue by pmmlo** [stripe/stripe-ios#1980]
## Summary
Same issue as previously mentioned in issue #1797 

## Code to reproduce
Integrate Stripe with a project for mac catalyst with Xcode 13.4.1 on macOS 12.4 M1 Mac.

## iOS version
Mac Catalyst iOS 15.5
macOS 12.3

## Installation method
SPM

## SDK version
22.5.1

## Other information
The same issue was mentioned previously in issue #1797

**Comment by ramont-stripe** [comment]
Hi @pmmlo,

It seems that the project is including Stripe libraries that require Catalyst 14 (StripeCardScan or StripeIdentity). Can you check the linked libraries and make sure that these libraries aren't included?

| Before | After |
| --- | --- |
| <img width="739" alt="Screen Shot 2022-06-28 at 7 14 14 PM (1)" src="https://user-images.githubusercontent.com/88752322/176321456-4a3e1bf7-3b46-4ddf-81da-18517eb445b3.png"> | <img width="752" alt="Screen Shot 2022-06-28 at 7 16 10 PM (1)" src="https://user-images.githubusercontent.com/88752322/176321461-98e8b2e4-129b-4016-86cc-1da70a469ee1.png"> |

**Comment by pmmlo** [comment]
@ramont-stripe That fixed the errors.  Thanks for the help!  It may be beneficial to explicitly say no Catalyst for those two libraries, because I believe Catalyst apps are technically iOS apps.  Thanks, again.
