### ISSUE TITLE
[BUG] crash when calling `StripeAPI.deviceSupportsApplePay()`

### ISSUE THREAD

**Issue by davidweissler** [stripe/stripe-ios#1984]
## Summary

We're seeing crashes when calling `StripeAPI.deviceSupportsApplePay()`

## Code to reproduce
The code is just a series of calls that ends with a call to `StripeAPI.deviceSupportsApplePay()`

```
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
  	...
    AdNetworkHelper.reportAppOpenValue(sessionCount: count)
    ...
  }

  static func reportAppOpenValue(sessionCount: UInt) -> Int {
    let deviceSupportsApplePay = InAppProductManager.isStripeAvailable()
    ...
  }

  static func isStripeAvailable() -> Bool {
    return StripeAPI.deviceSupportsApplePay()
  }
```

## iOS version
15.3.1 (19D52)

## Installation method
SPM

## SDK version
22.3.0

## Other information

Example crash log

[stripe_crash.txt](https://github.com/stripe/stripe-ios/files/9095682/stripe_crash.txt)

**Comment by davidme-stripe** [comment]
That's an odd crash — it looks like this is an iPad Air 2, and the Secure Element isn't responding during the `[PKPaymentAuthorizationController canMakePaymentsUsingNetworks:]` call, which is causing the app to hang during launch and eventually be killed by the system watchdog.

This sounds like an Apple bug, so I think the only thing we can do is [file a Feedback Assistant ticket](https://feedbackassistant.apple.com/). How many of these crashes are you seeing? Are you able to reproduce it on your own devices?

**Comment by davidweissler** [comment]
In the last release of our app, it looks like there's about 30 devices crashing due to this.

<img width="856" alt="CleanShot 2022-07-12 at 15 17 30@2x" src="https://user-images.githubusercontent.com/2179815/178576175-0059dbfb-ca4d-4857-afd8-fe773156c1fc.png">

I have tried a lot but have not been able to repro this myself unfortunately. And the crash occurs on varying devices, iPhones and iPads.

**Comment by porter-stripe** [comment]
@davidweissler closing this out for as stale, feel free to re-open if needed.

**Comment by denggun** [comment]
@davidweissler Hi，Have you solved this problem? I also encountered the same problem
