### ISSUE TITLE
[BUG] invalid_request_error - billing_details[address][country] on POST /v1/payment_methods

### ISSUE THREAD

**Issue by jfougere** [stripe/stripe-ios#1985]
## Summary
We observed some request failures on POST /v1/payment_methods when using Apple Pay with Stripe IOS.

Below the reported error:
```
invalid_request_error - billing_details[address][country]
Country 'JA' is unknown. Try using a 2-character alphanumeric country code instead, such as 'US', 'EG', or 'GB'. A full list of country codes is available at https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements
```

From the Stripe dashboard, we can see that effectively the country code provided to the endpoint is wrong. 'JA' was provided for Japan instead of 'JP'. However we are not the ones filling the billing details.

Can it be a bug in the SDK or iOS ? 

For some other Japanese customers it just works fine.

## iOS version
iOS 15

## SDK version
21.13.0

**Comment by yuki-stripe** [comment]
@jfougere That's very odd, we pass the ISO two-letter country code directly from Apple Pay's `PKToken.billingContact.postalAddress.isoCountryCode`.  Can you get more information on the user's address as it appears when they use Apple Pay?

**Comment by jfougere** [comment]
@yuki-stripe unfortunately no, we don't have more details... It happened 3 times but each for the same user.

**Comment by yuki-stripe** [comment]
Got it, thanks @jfougere.  I was able to find those 3 failures in our logs but see no other similar failures (ApplePay w/ a country of "JA") in the past 30 days.  At this point I'd suggest reaching out to the user and seeing if they can update their Apple Pay billing information.

**Comment by jfougere** [comment]
Thanks @yuki-stripe. We will monitor to see if this case happen again.

**Comment by yuki-stripe** [comment]
Closing this issue but feel free to re-open
