### ISSUE TITLE
[Stripe iOS SDK x PayPal Integration] 

### ISSUE THREAD

**Issue by RichyZDenmark1332** [stripe/stripe-ios#1987]
## Is your feature request related to a problem? Please describe.
I see a bunch of references to PayPal in the Stripe iOS SDK but I am having trouble understanding how to allow a user to Use PayPal to send a payment to a Stripe Connect account?

**Comment by porter-stripe** [comment]
Hi @RichyZDenmark1332 PayPal support is currently in private beta, if you would like to see if you are eligible please reply to this issue and I can provide the contact information.

**Comment by skyeewers** [comment]
Sorry to bump an old (and closed) issue, but is there any way one could request access to this private beta? I work as a freelance developer on several projects that use Stripe and would love to go hands-on with this integration to test it for my clients & be able to maybe give helpful feedback.

**Comment by BerkeAras** [comment]
@porter-stripe I am interested, and as far as I know, there is on stable version or any public beta right now. Could you provide me the contact information?
