### ISSUE TITLE
Build fails when using STPPaymentCardTextField

### ISSUE THREAD

**Issue by pablogb** [stripe/stripe-ios#199]
I'm trying to migrate from PaymentKit to Stripe SDK, but I get the following linker error whenever I try to use STPPaymentCardTextField:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_STPPaymentCardTextField", referenced from:
      __TMaCSo23STPPaymentCardTextField in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any ideas?

**Comment by jflinter** [comment]
Would you mind running `pod update` and trying again? I literally just pushed a 5.1.1 release that likely fixes this issue.

**Comment by pablogb** [comment]
It's working now, thanks :)
