### ISSUE TITLE
Alignment and Localization issues with Arabic Language

### ISSUE THREAD

**Issue by yossefEl** [stripe/stripe-ios#1990]
## Summary
We have clients in Saudi Arabia and one of the scenarios that we may face is people setting their phone's language to Arabic so we tested the app for this case and found that there are so many issues with **PaymentSheet, especially for elements alignment and localizations (please check the attached screenshot)**.
<img src="https://user-images.githubusercontent.com/39236784/182891552-2ad0325c-5842-4056-b812-965f2d8ead0c.png" height="700px" align="right">

## Steps to reproduce
1. Change Phone language to Arabic
2. Try to make a payment using PaymentSheet 

## iOS version

- 15.5 (Emulator)
- 14.7 (Physical)

## Installation method
We're using the latest version of [flutter_stripe (4.0.0)](https://pub.dev/packages/flutter_stripe)

## SDK version
- Stripe (22.5.1):
    - Stripe/Stripe3DS2 (= 22.5.1)
    - StripeApplePay (= 22.5.1)
    - StripeCore (= 22.5.1)
    - StripeUICore (= 22.5.1)

**Comment by wooj-stripe** [comment]
Hi @yossefEl -

Unfortunately per #1968 -- PaymentSheet does not currently support the Arabic language.  It has been added to our internal tracker, and unfortunately, still don't have a timeline for supporting this. I will be closing this issue as a duplicate.
