### ISSUE TITLE
[BUG] Unable to build with Xcode 14 beta

### ISSUE THREAD

**Issue by jsahoo** [stripe/stripe-ios#1991]
## Summary

Our project fails to compile with Xcode 14 beta:
<img width="393" alt="Screen Shot 2022-08-04 at 11 06 46 AM" src="https://user-images.githubusercontent.com/6937424/182921069-f76692c2-ee95-4454-8e09-d9f526fc77ed.png">
Note that the project compiles successfully with Xcode 13

## SDK version

```
  - Stripe (22.6.0):
    - Stripe/Stripe3DS2 (= 22.6.0)
    - StripeApplePay (= 22.6.0)
    - StripeCore (= 22.6.0)
    - StripeUICore (= 22.6.0)
  - Stripe/Stripe3DS2 (22.6.0):
    - StripeApplePay (= 22.6.0)
    - StripeCore (= 22.6.0)
    - StripeUICore (= 22.6.0)
  - StripeApplePay (22.6.0):
    - StripeCore (= 22.6.0)
  - StripeCore (22.6.0)
  - StripeUICore (22.6.0):
    - StripeCore (= 22.6.0)
 ```

**Comment by wooj-stripe** [comment]
Hi @jsahoo

I don't think this error with regards to selecting a "development team" is specific to the Stripe SDK. I believe xcode is asking for you to select a development team in your project.  I will be optimistically closing this ticket as I do not believe this is related to the Stripe SDK, but feel free to re-open if I've misunderstood the problem you're encountering.

**Comment by jsahoo** [comment]
Hi @wooj-stripe, 

We've added the Stripe SDK to our project via CocoaPods, and as you can see from the screenshot, the signing errors are showing up under the Pods project and are specifically related to only Stripe-related targets. We have a bunch of other pods added to our project and none of them throw this signing error (or any error). The signing for our actual project and each target within is configured properly. As I mentioned, we have no problem building on Xcode 13. So I don't believe it's a signing issue on our side. 


The issue seems to be with these four blue targets within the Pods project:
<img width="167" alt="image" src="https://user-images.githubusercontent.com/6937424/182935363-78561dfa-ef01-4d10-a4c7-004ff004d456.png">


Upon closer inspection, it seems that for some reason each of these targets has automatic code signing enabled:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/6937424/182935883-916f252e-47a6-4b36-b76b-01e5f23aba45.png">


I'm not very familiar with the inner workings of CocoaPods, but I don't believe these should be signed? Other targets for other pods (e.g. `PromiseKit`) are not signed:
<img width="112" alt="image" src="https://user-images.githubusercontent.com/6937424/182936366-46555451-8e17-41f7-a75d-aa1ad4e35915.png">
<img width="437" alt="image" src="https://user-images.githubusercontent.com/6937424/182936400-4b412fe5-0ba8-423b-81d7-0567eec8761d.png">


In fact, even the plain "Stripe" target (highlighted) seems to correctly not be signed:
<img width="168" alt="image" src="https://user-images.githubusercontent.com/6937424/182936504-86c4d980-7efd-41f2-9dc3-9f5cf408247a.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/6937424/182936643-a639880e-bbf3-4822-bbee-ce301f356bb2.png">


So it seems like for some reason those four blue targets are getting automatic code signing enabled. In Xcode 13, though the same error message _does_ actually display under Signing & Capabilities, it doesn't actually cause compilation to fail.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/6937424/182937270-21f657b8-189d-48dd-be0d-63a624c9d0ce.png">

**Comment by wooj-stripe** [comment]
Hey @jsahoo,

Sorry to hear you are still having issues with this, and thank you for the detailed screenshots.  Based on on this, I suspect this has something to do with cocoapods and xcode 14 beta.

I believe this is related to this issue here:
https://github.com/CocoaPods/CocoaPods/issues/11402

Feel free to re-open the issue if this does not address your issue.

**Comment by jsahoo** [comment]
Thanks @wooj-stripe, that turned out to be the issue and the solution within worked. Thanks for finding that and pointing me to it!

**Comment by azadbaljeet** [comment]
func _delegateToAppleDelegateMapping() -> [Selector: Selector] {}, getting issue , please see image
<img width="1303" alt="Screenshot 2023-06-02 at 5 36 36 AM" src="https://github.com/stripe/stripe-ios/assets/14087089/03ae601b-a1b2-4648-a3e1-026470056ee6">
