### ISSUE TITLE
[BUG] PaymentSheet Landscape issue

### ISSUE THREAD

**Issue by imnikita1** [stripe/stripe-ios#1999]
## Summary
An issue with the keyboard on STPViewController.

## Code to reproduce
After rotation from portrait to landscape mode with opened keyboard, the payment view gets padding, while according to the view hierarchy it should be clearly visible.

Before rotation
![Screenshot 2022-08-24 at 12 07 25](https://user-images.githubusercontent.com/97101755/186391990-15075bf5-789f-4e4e-a2ff-2273bef46a40.png)

After rotation
![Screenshot 2022-08-24 at 12 00 17](https://user-images.githubusercontent.com/97101755/186390720-5d86ade2-8987-4dfc-8142-2d36ec1e72ca.png)

## iOS version
15.2

## Installation method
SPM

## SDK version
22.0.0

**Comment by porter-stripe** [comment]
Hi @imnikita1 thanks for reporting this, we are looking into it! I will update this issue when we have more details.

**Comment by yuki-stripe** [comment]
This should have been fixed in https://github.com/stripe/stripe-ios/releases/tag/22.7.1
