### ISSUE TITLE
Donate with Apple Pay

### ISSUE THREAD

**Issue by powerofpercy** [stripe/stripe-ios#2000]
Not sure if this is a feature request, do we currently have a way to change Apple Pay button to 'Donate with Apple Pay'? The app I'm trying to develop collects donations for a charity organisation and seems like Apple requires the Pay button to say 'Donate with Apple Pay' instead. Here's the Apple Developer link https://developer.apple.com/apple-pay/nonprofits/

**Comment by porter-stripe** [comment]
Hi @powerofpercy we don't currently have this on our roadmap, but I will create an internal ticket so we can track this closer. I'll be sure to update this issue with any future updates!

**Comment by nikitph** [comment]
Was there any update to this? we are also running into something similar

**Comment by davidme-stripe** [comment]
Yes, this was added in [23.1.0](https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#2310-2022-10-31).
