### ISSUE TITLE
[BUG] Does not compile for macOS/Catalyst on Xcode 14

### ISSUE THREAD

**Issue by davidhakki** [stripe/stripe-ios#2001]
## Summary
<img width="299" alt="Screenshot 2022-08-30 at 4 38 20 PM" src="https://user-images.githubusercontent.com/12222977/187538598-b24f0761-f92b-43ac-ae3e-bd33894aae5c.png">
Unable to compile/archive on Xcode 14 at all. I noticed there was several closed issues, however trying the alternate branch only fixed it for iOS. It still remains an issue on macOS/Catalyst. Other suggestions had fixes for cocoapods, I am using SwiftPM exclusively.

## iOS version
Xcode Version 14 BETA 5

## Installation method
Swift Package Manager

## SDK version
22.7.0

## Other information
Compiles and runs fine for iOS and iPadOS. Catalyst seems to keep throwing these errors. Attempting to clean, uninstall and reinstall the package.

**Comment by ramont-stripe** [comment]
Hi @EliteTechnicalCare,

Thank you for reporting this! I'm currently working on a fix. I will keep this issue updated with the progress.

**Comment by ramont-stripe** [comment]
Hi @davidhakki, we just released a new version that fixes the Catalyst issue on Xcode 14:

https://github.com/stripe/stripe-ios/releases/tag/22.7.1

I'm closing this issue for now. Feel free to re-open if needed :)

**Comment by lilongcnc** [comment]
您好，你的邮件我已收到。我尽快处理的哈~~么么哒~~~

**Comment by lilongcnc** [comment]
您好，你的邮件我已收到。我尽快处理的哈~~么么哒~~~
