### ISSUE TITLE
[BUG] Cannot build Stripe Swift Package Manager with Xcode 14.0 beta 6

### ISSUE THREAD

**Issue by Bengua27** [stripe/stripe-ios#2003]
## Summary
Cannot build Stripe SDK using Swift Package Manager with Xcode 14.0 beta 6

## Code to reproduce
Just add Stripe SPM to the project

## iOS version
All of them

## Installation method
SPM

## SDK version
21.13.0 SPM

## Other information
Using Xcode 14.0 beta 6

**Comment by jerometonnelier** [comment]
It's still here with Xcode 14 RC fyi. Any news on a fix ? Thanks.
