### ISSUE TITLE
Payment Link with setup type of Donate

### ISSUE THREAD

**Issue by jimsideout** [stripe/stripe-ios#2005]
### Describe the bug

When you create a payment link via the API or Dashboard with setup type (call to action) of Donate, the green success checkmark does not appear nor does the red heart afterwards when you're testing on mobile. Doing the testing in a computer works fine. If you change the setup type to "Pay", the green success checkmark appears fine on mobile and desktop.

Tested via iphone simulator and multiple real devices.

### To Reproduce

Create a payment link via API or Dashboard with call to action of "Donate" and use a test card on a mobile device.

### Expected behavior

Display green checkmark and transition to red heart icon.

**Comment by davidme-stripe** [comment]
Thanks for filing this, I do see that the animation is broken on iOS 16! `stripe-ios` is the repository for the native iOS SDK, so it probably isn't the right place for this issue either. We'll investigate this internally and follow up soon.

(Internal reference ID: RUN_PAYMENT_LINKS-635)

**Comment by martinm-stripe** [comment]
Thanks for reporting, @jimsideout! We've fixed this temporarily by making the animation a static heart icon--we'll restore the animation but need to do some more work to make it work with the updated build pipeline that caused this regression in the first place.
