### ISSUE TITLE
[Feature] Expose the selected payment method stripeId (paymentMethodId) from `PaymentSheet.FlowController`

### ISSUE THREAD

**Issue by jacobmoncur** [stripe/stripe-ios#2007]
## Is your feature request related to a problem? Please describe.

I'm using the `PaymentSheet.FlowController` to add, update, and change a customers default payment method, but I am unable to access the stripeId (paymentMethodId) of the selected/default payment method. 

FlowController exposes a `paymentOption: PaymentOptionDisplayData` to show high level information about the payment method, but hides the the identifying information about it. 

Is there another way to access the selected payment method in its entirety? Or is there a reason that this information isn't currently exposed? 

## Describe the solution you'd like
One solution is to make `_paymentOption: PaymentOption` public in some fashion to use that information as needed, but I'd like to hear if there are other ways to access this information. 

## Describe alternatives you've considered
N/A

**Comment by leslie-stripe** [comment]
@jacobmoncur Thanks for the feedback! You'll be able to access the paymentMethodId with server-side confirmation, which will be supporting in beta starting next week. If you'd like to be gated into this feature, just send us your account ID at mobile-deferred-intents-beta@stripe.com.

**Comment by sfriedman-stripe** [comment]
Hi @jacobmoncur, closing this down since we haven't heard from you. Please reopen if you're still having issues
