### ISSUE TITLE
[BUG] Brand new MacBook Pro M1 Pro with Xcode 14.0 not compiling because of @availability on lazy vars

### ISSUE THREAD

**Issue by johnoutdoorsy** [stripe/stripe-ios#2008]
## Summary

I just upgraded to a M1 Pro. I downloaded Xcode today, pulled down our code (working code on a non-M1 computer) and for some reason Stripe won't let Xcode compile the app. Other members on my team have M1+ devices and are on Xcode 14

Few things to note:

- The app is iOS deployment target 14.0
- I've cleared the SPM cache 100 times.
- I've cleared derived data
- I've run Xcode in both rosetta and non-rosetta (but the app requires rosetta)
- I installed both from Xcode XIP download and AppStore

## Code to reproduce

Download Xcode, run in rosetta and compile a SPM version 21.11.1 of Stipe in a project that was originally created on a non M1 computer.

## iOS version

- iOS 14, iOS 15 and iOS 16 Simulators
- Xcode Version 14.0 (14A309)

## Installation method

SPM

## SDK version

21.11.1 (I tried updated as well)

<img width="529" alt="Screen Shot 2022-09-12 at 8 25 25 PM" src="https://user-images.githubusercontent.com/67285550/189781273-25f3e296-b2f1-4972-a462-f6369b4e6aa4.png">

## Other information

Here's what the errors look like, always the same 3 errors.

<img width="246" alt="Screen Shot 2022-09-12 at 8 09 31 PM" src="https://user-images.githubusercontent.com/67285550/189779858-671b7ead-9c27-4cf7-8d84-39423a1b1705.png">
<img width="863" alt="Screen Shot 2022-09-12 at 8 09 00 PM" src="https://user-images.githubusercontent.com/67285550/189779782-71be3779-1067-4c32-84fc-fb1a0c9bea2c.png">
<img width="864" alt="Screen Shot 2022-09-12 at 8 09 09 PM" src="https://user-images.githubusercontent.com/67285550/189779798-e97d0f96-4c5d-4e5d-8484-ad8fef3a561e.png">

Here's the text versions of the errors for future people who search this problem:

`Stored properties cannot be marked potentially unavailable with '@available'`

**Comment by davidme-stripe** [comment]
Hi, thanks for filing this! I'd recommend updating to version 22.8.1. This was a known issue in previous versions, but we fixed it in [22.7.1](https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#2271-2022-08-31). The `@available()` attributes referenced in this screenshot don't exist in recent versions of the code.

**Comment by mirkancal** [comment]
I've fixed it by targeting iOS 14 from Podfile.

**Comment by johnoutdoorsy** [comment]
> Hi, thanks for filing this! I'd recommend updating to version 22.8.1. This was a known issue in previous versions, but we fixed it in [22.7.1](https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#2271-2022-08-31). The `@available()` attributes referenced in this screenshot don't exist in recent versions of the code.

This resolved it. The main reason we were trying to avoid upgrading to a newer version was because some how another team member's M1 Mac is compiling it fine. I'm guessing they're running on cache before upgrading to Xcode 14.

> I've fixed it by targeting iOS 14 from Podfile.

This might work, I wasn't able to verify because we are using SPM but I appreciate the suggestion for future eyes of this ticket.

---

Thank you both!
