### ISSUE TITLE
[BUG] Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by YiZheming** [stripe/stripe-ios#2011]
xcode 14 build  fails with  "Stored properties cannot be marked potentially unavailable with '@available' "
version : 'Stripe','21.13.0'
support : iOS 11.0

**Comment by ItsFlash10** [comment]
Getting this same issue after the new xCode 14 update

**Comment by suchanmaharjan** [comment]
I'm stuck with the same issue as well after updating to Xcode 14. Did you guys find any work around yet?

**Comment by YiZheming** [comment]
> Hi, thanks for filing this! The Xcode 14 compile errors have been fixed in recent versions of the SDK:
> 
> https://github.com/stripe/stripe-ios/releases
> 
> I would recommend upgrading to [v22.8.1](https://github.com/stripe/stripe-ios/releases/tag/22.8.1).

"For iOS 11 support, please use [v21.13.0]. For iOS 10, please use [v19.4.0]. If you need to support iOS 9, use [v17.0.2]"
The lowest version my app supports is iOS11，What is the lowest version supported by V22.8.1

**Comment by ramont-stripe** [comment]
@YiZheming v22.8.1 supports iOS 12.

**Comment by ankitpoplify** [comment]
> > Hi, thanks for filing this! The Xcode 14 compile errors have been fixed in recent versions of the SDK:
> > https://github.com/stripe/stripe-ios/releases
> > I would recommend upgrading to [v22.8.1](https://github.com/stripe/stripe-ios/releases/tag/22.8.1).
> 
> "For iOS 11 support, please use [v21.13.0]. For iOS 10, please use [v19.4.0]. If you need to support iOS 9, use [v17.0.2]" The lowest version my app supports is iOS11，What is the lowest version supported by V22.8.1

I am using [v21.13.0] and I'm still getting this error in ActivityIndicator.swift inside StripeUICore.

**Comment by ramont-stripe** [comment]
@ankitpoplify you will need upgrade to the latest version of the SDK to fix this error. Unfortunately, changes in the Swift compiler that ships with Xcode 14 broke the old versions.

**Comment by Ro-M** [comment]
@ramont-stripe so just to clarify: This means that clients of this SDK will not be able to use the Stripe-SDK with the latest Xcode 14 version while still supporting iOS 11?

Out app currently has a minimum deployment target of iOS 11 and still quite a few customers are on those versions. To my knowledge version `21.13.0` was the last version that still supported iOS 11 and is currently stripe's recommended version for targeting iOS 11. Is there no other option aside from either not upgrading to Xcode 14 (not a long term option) or raising our minimum deployment target?

**Comment by NgocLe1001** [comment]
I update version stripe to latest and it works

**Comment by UzairSamad** [comment]
How did you updated the version

**Comment by sara-Guesmi** [comment]
> > > Hi, thanks for filing this! The Xcode 14 compile errors have been fixed in recent versions of the SDK:
> > > https://github.com/stripe/stripe-ios/releases
> > > I would recommend upgrading to [v22.8.1](https://github.com/stripe/stripe-ios/releases/tag/22.8.1).
> > 
> > 
> > "For iOS 11 support, please use [v21.13.0]. For iOS 10, please use [v19.4.0]. If you need to support iOS 9, use [v17.0.2]" The lowest version my app supports is iOS11，What is the lowest version supported by V22.8.1
> 
> I am using [v21.13.0] and I'm still getting this error in ActivityIndicator.swift inside StripeUICore.

Please did you find a solution? 
Thanks
