### ISSUE TITLE
[BUG] Can not create app build using Xcode 14. Keep saying select development team for signing "stripe-stripe"

### ISSUE THREAD

**Issue by nirav-kotecha** [stripe/stripe-ios#2012]
## Summary
App run successfully in Xcode 14 and stripe version 22.6.0 but when i create build it will gives me following error.

<img width="402" alt="Screenshot 2022-09-15 at 4 45 55 PM" src="https://user-images.githubusercontent.com/35652030/190390711-3d663469-0706-4f8c-88b6-56c3717a8fda.png">

## Code to reproduce
Using Xcode 14.0 and Stripe version 22.6.0 --> Select your app --> Select iOS device --> create build by window+b or product menu and select build option

## iOS version
16.0

## Installation method
installed using cocoapods

## SDK version
22.6.0

**Comment by nirav-kotecha** [comment]
currently i found workaround by adding below code in pod file.

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end

**Comment by davidme-stripe** [comment]
This appears to be related to https://github.com/CocoaPods/CocoaPods/issues/11402. Your workaround should work for now, and hopefully Cocoapods can fix this in a future update.

**Comment by richieshilton** [comment]
We're getting this error too in our CICD but we're using SPM to manage the package. I haven't found a workaround, has anyone else?

**Comment by benstjohn** [comment]
This workaround does not work for M1/M2 MacBook pros.

`### Error

```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64))) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
`

**Comment by renishmithani** [comment]
![Screenshot 2022-12-16 at 6 01 28 PM](https://user-images.githubusercontent.com/86999018/208099046-3a51a3eb-a906-488a-8ce9-3667baeee4ff.png)

You have to select Pods in Project, then search Development Team, and select your Team name
