### ISSUE TITLE
[Feature] Support STPAPIClient.createToken in StripeApplePay

### ISSUE THREAD

**Issue by maksg-allset** [stripe/stripe-ios#2014]
## Is your feature request related to a problem? Please describe.
We are using [STPAPIClient.createToken](https://github.com/stripe/stripe-ios/blob/22.8.1/Stripe/STPAPIClient%2BApplePay.swift#L19-L27) method to make payments in our application. We also have an app clip which also uses Stripe for payments. And we would like to use `StripeApplePay` module to decrease it size, but `createToken` method is not available in this module.

## Describe the solution you'd like
Make method [STPAPIClient.createToken](https://github.com/stripe/stripe-ios/blob/22.8.1/Stripe/STPAPIClient%2BApplePay.swift#L19-L27) available in `StripeApplePay` module.

**Comment by davidme-stripe** [comment]
Hi @maksg-allset, would the new [StripePayments module](https://github.com/stripe/stripe-ios/tree/master/StripePayments) work for you? More info here: https://stripe.com/docs/mobile/ios/sdk-23-migration

**Comment by maksg-allset** [comment]
Yes, it works.
Thank you @davidme-stripe

**Comment by dingwilson** [comment]
Hey @davidme-stripe - I have tried to migrate off of Stripe-Min to use the new modularized StripeApplePay for AppClips, but found that when I have to integrate StripePayments (+ StripeCore dependency), the resulting binary is larger than Stripe-Min and pushes us over the allowed limit for App Clips size. Do you have any thoughts here?
