### ISSUE TITLE
[BUG] SimpleScanViewController displays garbled characters in languages such as Chinese in version 22.8.2

### ISSUE THREAD

**Issue by lszzy** [stripe/stripe-ios#2015]
## Summary
SimpleScanViewController displays garbled characters in languages such as Chinese

![WechatIMG1214](https://user-images.githubusercontent.com/4383651/191400668-053c327c-35ae-4217-b261-f4a25cd932d0.jpeg)

## Code to reproduce
SimpleScanViewController.swift line 270

```
if let attributedString = try? NSAttributedString(data: stringData, options: [.documentType: NSAttributedString.DocumentType.html], documentAttributes: nil) {
    privacyLinkText.attributedText = attributedString
}
```

## iOS version
All versions.

## Installation method
Podfile

## SDK version
22.8.2

## Other information
How to Fix:  Add parameter .characterEncoding and set it to utf8 when html decoding
Example:

```
if let attributedString = try? NSAttributedString(data: stringData, options: [.documentType: NSAttributedString.DocumentType.html, .characterEncoding: NSNumber(value: String.Encoding.utf8.rawValue)], documentAttributes: nil) {
      privacyLinkText.attributedText = attributedString
  }
```

**Comment by ramont-stripe** [comment]
Hi @lszzy,

Thank you for reporting this. We just released a fix for this issue in v22.8.3:
https://github.com/stripe/stripe-ios/releases/tag/22.8.3
