### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Anjie167** [stripe/stripe-ios#2016]
## Summary
Getting this "(any
PKPaymentAuthorizationCon trollerDelegate) while trying to build app

## Code to reproduce
on running app build

## iOS version
What version of iOS are you observing the problem on?

## Installation method
Running pod install

## SDK version
Using 22.3.2

**Comment by porter-stripe** [comment]
@Anjie167 Thanks for opening this, can you please fill out the required information for the issue so we can attempt to reproduce the issue on our end.

**Comment by porter-stripe** [comment]
@Anjie167 I'm going to close this as there isn't enough information to diagnose the issue. Please feel free to provide more details and re-open the issue.
