### ISSUE TITLE
[BUG] Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by LeoMarliereYassir** [stripe/stripe-ios#2021]
I have an error on a StoredProperties. 
I can't build my app anymore because of this. 
ERROR : Stored properties cannot be marked potentially unavailable with '@available'

![Screenshot 2022-10-04 at 12 12 37](https://user-images.githubusercontent.com/105651112/193794481-596895a7-902a-46ab-ba36-aace8365c51b.png)

**Comment by ramont-stripe** [comment]
Hi @LeoMarliereYassir,

The stored properties issues with Xcode 14 have been fixed in more recent versions of the SDK:
https://github.com/stripe/stripe-ios/releases

I would recommend upgrading to [v22.8.3](https://github.com/stripe/stripe-ios/releases/tag/22.8.3).
