### ISSUE TITLE
[BUG] "@import Stripe" in header file 'module not found' if that header is included in bridging header

### ISSUE THREAD

**Issue by jackgmarch** [stripe/stripe-ios#2022]
## Summary
We're moving Stripe to Swift Package Manager from CocoaPods. If we import Stripe to an Objective-C header file, it compiles without problems. However if this same header file is added to a bridging header, we get the following errors:

`failed to emit precompiled header '...Library/Developer/Xcode/DerivedData/StripeTest-dgjcrgoupugowfgvmikolsbuthay/Build/Intermediates.noindex/PrecompiledHeaders/StripeTest-Bridging-Header-swift_2KTEML3831MFC-clang_XVBV8HC285FH.pch' for bridging header '/.../StripeTest/StripeTest/StripeTest-Bridging-Header.h'`

Another error on the "@import Stripe" line:
`.../StripeTest/StripeTest/ViewController.h:8:9: error build: module 'Stripe' not found`

## Code to reproduce
https://github.com/jackgmarch/StripeHeaderBug

## iOS version
iOS 16

## Installation method
Swift Package Manager. 

_Our existing CocoaPods installation did not have this same error:_

`pod 'Stripe', '22.8.0', :modular_headers => true`

Cocoa
## SDK version
22.8.3

**Comment by ramont-stripe** [comment]
Hi @jackgmarch,

Thank you for reporting this. This appears to be a limitation on how Swift modules are imported and linked with SPM. I can 100% reproduce with other libraries as long as they are written in Swift.

Is there a way for you to move the `@import Stripe;` to the `.m` file?

**Comment by jackgmarch** [comment]
@ramont-stripe Thanks for the update! We ended up just moving the relevant code to Swift to fix the issue

I'll close this bug report given the issue the issue is not related to Stripe SDK.

**Comment by ramont-stripe** [comment]
👍 I'm closing this issue for now. Feel free to re-open, if needed :)

**Comment by Vaisakhk1990** [comment]
@ramont-stripe  Without moving the @import Stripe; to the .m file, Any other solution. Today we upgraded the Strip SDK to 23.9.1 and we are facing the similar issue
