### ISSUE TITLE
[Feature] Add support for macCatalyst to use the form sheet presentation, like in iPad

### ISSUE THREAD

**Issue by sergiocampama** [stripe/stripe-ios#2023]
## Is your feature request related to a problem? Please describe.
More than a problem, seems to be something that was overlooked, probably because macCatalyst hasn't been massively used yet.

## Describe the solution you'd like
macCatalyst should be treated similar to how iPads are treated when presenting view controllers.

## Describe alternatives you've considered
Forking stripe-ios and use custom presentation logic.

**Comment by ramont-stripe** [comment]
Fixed in [v22.8.4](https://github.com/stripe/stripe-ios/releases/tag/22.8.4) 🎉
