### ISSUE TITLE
Did you mean to use 'as!' to force downcast?

### ISSUE THREAD

**Issue by lextoc** [stripe/stripe-ios#2028]
![PixelSnap 2022-10-14 at 11 24 46](https://user-images.githubusercontent.com/4405004/195812558-a773209b-1472-4279-8de1-547465267b09.png)

**Comment by wooj-stripe** [comment]
Hi @lextoc -

Thanks for reaching out. Can you provide the version of xcode you are running?

**Comment by danielchangsoojones** [comment]
also having this issue, and it won't let me build my project because of this.

Version of Xcode: 14.0.1
Version of Stripe SDK: 21.13.0

**Comment by hasbund** [comment]
Having the same issue.

**Comment by wooj-stripe** [comment]
Hi @danielchangsoojones,

There have been some updates in Xcode 14 that has made this code incompatible.  This has been fixed in our latest version of the SDK -- would it be possible to update the version of the SDK you are using?

CC @hasbund @lextoc

**Comment by wooj-stripe** [comment]
I am optimistically closing this issue, given that this is has been fixed in our latest version, but feel free to reopen if you have additional concerns.
