### ISSUE TITLE
pod try for Stripe iOS Example (Custom) not working

### ISSUE THREAD

**Issue by loudnate** [stripe/stripe-ios#203]
Stripe.framework isn't found. I think Cocoapods example projects usually are building against source?

**Comment by sivaganeshsg** [comment]
@loudnate you should **not** open "Stripe iOS Example (Custom).xcodeproj" and Run.

Go to the **main folder** and open "Stripe.xcworkspace", select "Custom Example" and then "Run"

**Comment by loudnate** [comment]
You're right, if I was checking out the project, but I'm filing this ticket specifically for supporting `pod try` functionality.
