### ISSUE TITLE
Testing Example without Apple Merchant ID

### ISSUE THREAD

**Issue by sivaganeshsg** [stripe/stripe-ios#204]
1) I want to test the stripe payment and ran the example code available in the repo. However without Apple Merchant ID, it is not working. Any sandbox way or bypass Merchant ID?

2) Have Xcode 6.3.1 and still when I run in iOS simulator, it says "In-App Payment Service isn't supported on this device." Can't we use iOS Simulator to test the payment?

**Comment by jflinter** [comment]
You have 2 options here:
- We have a library called [ApplePayStubs](https://github.com/stripe/applepaystubs) which is designed to let you test the Apple Pay APIs with test data
- With Xcode 7/iOS 9, you can use Apple Pay in the simulator.
For more information, see the ApplePayStubs README.
