### ISSUE TITLE
STPPaymentCardTextField: CVC code is drawn outside the text field

### ISSUE THREAD

**Issue by zvonicek** [stripe/stripe-ios#205]
When STPPaymentCardTextField is smaller than 320px on wide, the CVC code is drawn outside the text field. This is not good especially on 3.5 and 4inch iPhones which have exactly 320px width and it's usually good to have some padding around.

![](https://s3.amazonaws.com/f.cl.ly/items/071Y3m2W3m2i0J261c0p/Sni%CC%81mek%20obrazovky%202015-08-19%20v%C2%A017.36.37.png)

**Comment by pblondin** [comment]
I have the same kind of issue if you change the font using the appearance proxy API.

<img width="406" alt="screen shot 2015-08-20 at 3 06 47 pm" src="https://cloud.githubusercontent.com/assets/1045929/9392937/3d10f9e2-474d-11e5-9907-2b20c90b139f.png">

**Comment by jflinter** [comment]
Interesting. I'm having trouble replicating either of these issues on my end. @zvonicek @pblondin, would either of you be willing to put together a small test app that demonstrates this issue?

**Comment by pblondin** [comment]
Sorry, I should've replied earlier with my fix. The problem in my case was that I was setting cornerRadius to 0.0. I've notice later you were doing :
```
- (void)setCornerRadius:(CGFloat)cornerRadius {
    self.layer.cornerRadius = cornerRadius;
    self.layer.masksToBounds = cornerRadius > 0;
}
```

which make the textfields overflow when masksToBounds is False.

**Comment by jflinter** [comment]
Ah, that makes sense. masksToBounds should always just be true anyways.
Fixing now.

**Comment by jflinter** [comment]
@pblondin, your issue is fixed in master, and I'll be cutting a 5.1.3 release shortly. @zvonicek, let me know if you're still having problems on the current master (and if so, how to reproduce them) and I'll reopen this if necessary.

**Comment by zvonicek** [comment]
This fix didn't solve my problem. I believe my problem has something to do with using ```STPPaymentCardTextField``` in storyboard. I've created a sample app demonstrating the problem only with a storyboard and one subview in that. http://cl.ly/3u3a0S0h1o1J

**Comment by jflinter** [comment]
Ah, I see the issue - this is indeed a bug that I've fixed in 13058d70aec84b4b4178298d85b53ca6f9c1c73f. I haven't cut the 5.1.3 release yet, so this'll be included there. Thanks @zvonicek!

**Comment by bdevore17** [comment]
Do you have an ETA for when 5.1.3 will be released?

**Comment by jflinter** [comment]
@bdevore17: probably in a week or so. Sorry for the delay, things have been
busy on our end and I'm out of town for the week.
