### ISSUE TITLE
Apple Pay entitlement is required even when not used

### ISSUE THREAD

**Issue by addoshi** [stripe/stripe-ios#207]
Using stripe-ios 5.1.2

Upon submission to Apple, got the message:

> We have discovered one or more issues with your recent delivery for "Kitchensurfing". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
>Missing Entitlement - App contains references to [Apple Pay] in 'Kitchensurfing', but is missing the required entitlement 'com.apple.developer.in-app-payments'.

Previously, this entitlement was not necessary. Looks like importing ApplePay frameworks is now part of the Core spec. 

```
s.subspec 'ApplePay' do |ss|
    # This has been merged with the core subspec and is now empty; it's still around to avoid breaking legacy Podfiles.
    ss.dependency 'Stripe/Core'
  end
```

Do you have any suggestions to get around this issue?

**Comment by jflinter** [comment]
Hey @addoshi,
We were under the impression that Apple had ceased sending these warnings, and have reached out to them to see what the status is. In the meantime, the email is just a warning, and will in no way affect your App Store submission.

**Comment by jflinter** [comment]
Hey @addoshi,
We've heard back from Apple - they won't be sending these emails anymore. Sorry for any trouble!

**Comment by addoshi** [comment]
Thanks for following up.

**Comment by jflinter** [comment]
No problem!

**Comment by Legoless** [comment]
Just a note, we got "Metadata rejected" because of this:

> Information Needed
> 
> We began the review of your app but aren't able to continue because we need additional information about your app.
>
> At your earliest opportunity, please review the following question(s) and provide as much detailed information as you can. The more information you can provide upfront, the sooner we can complete your review.
> 
> Does the app currently have Apple Pay functionality? If so, please provide detailed steps on where to find the Apple Pay functionality in the app.
>
> Once you reply to this message in Resolution Center with the requested information, we can proceed with your review.

We do not use Apple Pay.

**Comment by addoshi** [comment]
Hm, our review went through without any issues.

**Comment by jflinter** [comment]
@Legoless, how did your review go? I'm going to reach out to Apple about this as well.

**Comment by Legoless** [comment]
We went through review afterwards successfully. Looks like it just depends on which reviewer do you get. @addoshi
