### ISSUE TITLE
[Feature] Add card network logo in the card number input field

### ISSUE THREAD

**Issue by jfougere** [stripe/stripe-ios#2071]
Would it be possible to include the different card network logo in the card number input field in order to be consistent with what is done in web PaymentElement or Android SDK.

Below an example of web:
<img width="537" alt="Capture d’écran 2022-11-07 à 15 44 18" src="https://user-images.githubusercontent.com/6061575/200254198-6360b3a4-9de6-46cb-9ade-dba9ab72b2a8.png">

Below an example of the Android SDK:
<img width="235" alt="Capture d’écran 2022-11-07 à 15 44 40" src="https://user-images.githubusercontent.com/6061575/200254380-3856c4de-53ba-4b60-9933-82d57f5cc7c3.png">

And here what we currently have on the iOS SDK:
<img width="226" alt="Capture d’écran 2022-11-07 à 15 44 29" src="https://user-images.githubusercontent.com/6061575/200254487-422d7803-1c65-4c5a-9487-3d766611a307.png">

**Comment by eurias-stripe** [comment]
Hi @jfougere, just wanted to let you know that this was already in the works but slipped through the cracks, I retook it and it should be available soon.

**Comment by porter-stripe** [comment]
This is available as of v23.3.0.

**Comment by jfougere** [comment]
We recently upgraded to v23.21.1 and we were thinking that we would get this fix during the upgrade but we don't actually see any credit card logo, we are still seeing the default gray card icon. 

Was it changed back in post v23.3.x release ?

**Comment by porter-stripe** [comment]
Hi @jfougere you should be seeing the card logos, can you try the latest version [23.23.0](https://github.com/stripe/stripe-ios/releases/tag/23.23.0)?

Also, are you using [card brand choice](https://docs.stripe.com/co-badged-cards-compliance)? If you are, you will still see the grey icon.

**Comment by jfougere** [comment]
Hi @porter-stripe I did try with version 23.23.0 and it is the same.

For info we don't set the preferred networks. (I tried to set it to see if the dropdown would display, but it did not. I'm not sure how it is supposed to work).

However I did some debugging and it seems you are right, the rotating logo view is not displayed but instead force to show the unknown icon because a cardBrandDropDown is set. However inspecting the dropdown object, I can see it contains only 1 element which is the place holder. So I believe that in this case if only the placeholder is present that the rotating logo should be displayed.

Below the responsible part of the code in TextFieldElement+Card.swift:
```
func accessoryView(for text: String, theme: ElementsUITheme) -> UIView? {
            // If CBC is enabled...
            if let cardBrandDropDown = cardBrandDropDown {
                // Show unknown card brand if we have under 9 pan digits and no card brands
                if 9 > text.count && cardBrandDropDown.nonPlacerholderItems.isEmpty {
                    return DynamicImageView.makeUnknownCardImageView(theme: theme)
                } else if text.count >= 8 && cardBrandDropDown.nonPlacerholderItems.count > 1 {
                    // Show the dropdown if we have 8 or more digits and at least 2 brands, otherwise fall through and show brand as normal
                    return cardBrandDropDown.view
                }
            }

            let cardBrand = STPCardValidator.brand(forNumber: text)
            if cardBrand == .unknown {
                if case .invalid(Error.invalidBrand) = validate(text: text, isOptional: false) {
                    return DynamicImageView.makeUnknownCardImageView(theme: theme)
                } else {
                    // display all available card brands
                    rotatingCardBrandsView.cardBrands =
                        RotatingCardBrandsView.orderedCardBrands(from: STPCardBrand.allCases)
                    return rotatingCardBrandsView
                }
            } else {
                rotatingCardBrandsView.cardBrands = [cardBrand]
                return rotatingCardBrandsView
            }
        }
```
As you can see as long as a cardBrandDropDown is set, even if just filled with only a placeholder, then we won't see the proper rotating card brand view.

I hope this helps, if we are not supposed to have this empty cardBrandDropDown initialized with only the placeholder could you tell me how/why the card brand choice is activated ? I tried to follow what is the condition for this feature to be activated but it seems to be related to how the payment intent is created. For information on Android with the same payment intent, the rotating card icons are displayed.

Thanks for your help

**Comment by jfougere** [comment]
For info, I tried with another of our Stripe account which is not EU based and the rotating icons is correctly displayed.
So yes I confirm that CBC is automatically activated because of our account being EU based.

However, I do think the rotating card logo should be displayed when no card number has been entered in the text field.
This is the current behavior on Android and Web, so would be nice to align it to iOS.

**Comment by jfougere** [comment]
@porter-stripe Should I open a new issue specific to this ? (Meaning having the card logo not displayed by default when CBC is present but no card number entered which is not aligned with the current Android+Web behavior)

**Comment by porter-stripe** [comment]
Hi @jfougere yes please open a new issue and we'll look into this.

**Comment by jfougere** [comment]
Done @porter-stripe : https://github.com/stripe/stripe-ios/issues/3376
