### ISSUE TITLE
[BUG] Inconsistent error message

### ISSUE THREAD

**Issue by jfougere** [stripe/stripe-ios#2072]
## Summary
Error messages reported by the PaymentSheet are not consistent between iOS SDK, Android SDK and the JS library (PaymentElement).

Below error message in english returned for the different declined cases :
| Error                      | Web (Stripe-js)                                                         | iOS                                                                   | Android                                                                 |
|----------------------------|-------------------------------------------------------------------------|-----------------------------------------------------------------------|-------------------------------------------------------------------------|
| Generic decline            | Your card has been declined.                                            | Your card was declined                                                | Your card was declined.                                                 |
| Insufficient funds decline | Your card has insufficient funds.                                       | Your card was declined                                                | Your card has insufficient funds.                                       |
| Lost card decline          | Your card has been declined.                                            | Your card was declined                                                | Your card was declined.                                                 |
| Stolen card decline        | Your card has been declined.                                            | Your card was declined                                                | Your card was declined.                                                 |
| Expired card decline       | Your card has expired.                                                  | Your card has expired                                                 | Your card has expired.                                                  |
| Incorrect CVC decline      | Your card's security code is incorrect.                                 | Your card's security code is invalid                                  | Your card's security code is incorrect.                                 |
| Processing error decline   | An error occured while processing your card. Try again in a little bit. | There was an error processing your card -- try again in a few seconds | An error occured while processing your card. Try again in a little bit. |

The wording is different, on iOS sentences are not finished by a "." and the insufficient fund case return a generic message while it is more precise on Android and JS.

Could this be aligned on all platforms and for all languages ? (I tested only english here).

## SDK version
iOS: 22.8.4
Android: 20.5.0
JS: 1.41.0

## Other information
Not sure that raising the issue here is the appropriate action, but Android and web are the closest (but not identical).

**Comment by eurias-stripe** [comment]
Thanks for reporting this issue, we will take a look.

**Comment by eurias-stripe** [comment]
Hi @jfougere just wanted to let you know that this has been addressed, it will be available in the next release (and it's available now in master).
The error messages should be consistent between iOS and Android, but they might still be slightly different from web, but the differences should be minimal.

**Comment by jfougere** [comment]
Good news. Thanks @eurias-stripe !
