### ISSUE TITLE
[BUG] Crash - StripeCardScan/UxModel.swift:128: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by nickm01** [stripe/stripe-ios#2078]
## Summary
Using 23.1.1 when trying to present the `CardImageVerificationSheet`

## Code to reproduce

```
let sheet = CardImageVerificationSheet(cardImageVerificationIntentId: "xxx", cardImageVerificationIntentSecret: "yyy")
        sheet.present(from: navigationController) { result in
            print("-=- result: \(result)")
        }
```

## iOS version
15.6.1
iPhone 7 plus

## Installation method
Pods - 23.1.1

## SDK version
23.1.1

## Other information
this is the line it crashes on:
```
return bundle.url(forResource: "UxModel", withExtension: "mlmodelc")!
```

Trace below
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/1801782/200694716-1ffbe6cd-1466-4908-bbd1-3a75763e393c.png">

**Comment by eurias-stripe** [comment]
Hi @nickm01, thank you for reporting this, we are looking into it.

**Comment by jaimepark-stripe** [comment]
Hello @nickm01!
Thank you for bringing this to our attention. Let me take a look into it. Just to be thorough, do you mind telling me what XCode version you are using?

**Comment by nickm01** [comment]
@jaimepark-stripe Xcode 14.0.  Note also this did not crash with StripeCardScan 22.6.0

**Comment by nickm01** [comment]
22.8.4 also has the same problem (22.6.0 works fine)

**Comment by jaimepark-stripe** [comment]
Apologies for the late reply @nickm01. I got sick so I was out for a few days. Picking this ticket back up! Will update you with progress.

**Comment by nickm01** [comment]
Hi @jaimepark-stripe... wondering about any updates thanks!

**Comment by jaimepark-stripe** [comment]
Hello @nickm01!
Can you take a look into Pods project folder Pods -> StripeCardScan -> StripeCardScan -> Resources -> CompiledModels and see if the file `UxModel.mlmodelc` exists?

**Comment by nickm01** [comment]
@jaimepark-stripe it appears to yes

**Comment by jaimepark-stripe** [comment]
@nickm01 
So I figured out what's going on. The MLModel class is an autogenerated class and the bundle it points to doesn't have the compiled ML model in its immediate directory. The compiled ML model is in another bundle, StripeCardScan.bundle, so it can't be found. 

Let me put in a fix for this and will get it out by the next deploy. Let me ping you with the SDK version that contains the fix!

**Comment by nickm01** [comment]
Great thanks @jaimepark-stripe ... LMK

**Comment by nickm01** [comment]
@jaimepark-stripe when is the next deploy likely to be?

**Comment by jaimepark-stripe** [comment]
Earliest would be next Monday 2022-12-05 if I can get this PR ready, tested, and merged by EOD. I'm rapidly getting this PR out but in all likelihood will be out by the next deploy train 2022-12-12. What I can do is schedule a mid-week deploy next week to get it out earlier than 2022-12-12.

**Comment by jaimepark-stripe** [comment]
Hello @nickm01!
The new SDK version is slated to deploy today. I'll ping you in this thread when its out on Pods!

**Comment by jaimepark-stripe** [comment]
@nickm01 
The new SDK version is out! https://github.com/stripe/stripe-ios/releases/tag/23.3.1
Let me know when you try out the new version. I will close this issue now.
