### ISSUE TITLE
Issues with stringByAppendingString in STPAPIClient.m

### ISSUE THREAD

**Issue by davidrothera** [stripe/stripe-ios#208]
I have a few (small number) of crashes reported in my app and when looking at the traces of those crashes it has the following detail:

```
-[NSString stringByAppendingString:] @ 0x70
-[STPAPIClient createTokenWithData:completion:] @ 0x38, STPAPIClient.m : 83
-[STPAPIClient(CreditCards) createTokenWithCard:completion:] @ 0x60, STPAPIClient.m : 249
```

Checking the code for this it looks like this error is when calling [here](https://github.com/stripe/stripe-ios/blob/7cf5f691b11d87ffb26838907ce5c5dccea26c01/Stripe/STPAPIClient.m#L84):

```objc
[request setValue:[@"Bearer " stringByAppendingString:self.publishableKey] forHTTPHeaderField:@"Authorization"];
```

**Comment by davidrothera** [comment]
Hmm... from looking into this more I think it could be that for some reason my publishable key isn't being set sometimes.

Would be nice though to throw an error if you try and make a request with no key.

**Comment by jflinter** [comment]
Ah, glad you resolved things on your end. We can probably fail more gracefully here; I'll see what we can do. Thanks!
