### ISSUE TITLE
[BUG] Incorrect Payment Sheet Styling in Dark Mode

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [stripe/stripe-ios#2089]
## Summary

The check mark for successful payment uses the wrong color when the user's device uses dark appearance..

### Light mode (correct)

![image](https://user-images.githubusercontent.com/19204050/202160213-31c9f923-3dff-42c9-a965-220624a3e0f2.png)

### Dark mode (incorrect)

![image](https://user-images.githubusercontent.com/19204050/202160259-3797bff9-3864-44ad-8373-e787540957c9.png)

---

It appears that this cannot be changed via the payment sheet appearance configuration parameters.

## iOS version

iOS 16 on iPhone 14 Pro Max.

## SDK version

[23.2.0](https://github.com/stripe/stripe-ios/releases/tag/23.2.0)

## Other information

See also: https://github.com/flutter-stripe/flutter_stripe/issues/1021

**Comment by davidme-stripe** [comment]
Thanks for filing this! We'll fix it in the next release.

**Comment by porter-stripe** [comment]
The fix can be found in the latest version!
