### ISSUE TITLE
Card number formatting functionality from PaymentKit

### ISSUE THREAD

**Issue by billinghamj** [stripe/stripe-ios#209]
I'm trying to find the functionality for card number formatting which was available in PaymentKit. While I could continue to use an old version of PaymentKit, it is deprecated now and as such I'd like to find the equivalent way to achieve this in stripe-ios.

This is the code I was using before:

```objc
#import <PaymentKit/PTKTextField.h>
#import <PaymentKit/PTKCardNumber.h>

@implementation CUVTextFieldCardNumberDelegate

- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string
{
  NSString *result = [textField.text stringByReplacingCharactersInRange:range withString:string];
  result = [PTKTextField textByRemovingUselessSpacesFromString:result];

  PTKCardNumber *cardNumber = [PTKCardNumber cardNumberWithString:result];

  if (![cardNumber isPartiallyValid])
    return NO;

  if (string.length > 0)
    textField.text = [cardNumber formattedStringWithTrail];
  else
    textField.text = [cardNumber formattedString];

  [super textField:textField shouldChangeCharactersInRange:range replacementString:string];

  return NO;
}

@end
```

While this functionality could be rolled into `STPCard`, it is used mostly with incomplete & not-yet-valid card numbers. Maybe there is a case for creating an `STPCardNumber` class?

**Comment by jflinter** [comment]
Hey there @billinghamj, sorry for the slow reply.

We actually made a point of pursuing a different approach than this when implementing `STPPaymentCardTextField`. Formatting a card number by inserting spaces into the string itself has a lot of issues in practice - there's a lot more state to manage as the user edits the field, and ultimately it's confusing the presentation of data (in this case, the card number) with the data itself.
Instead, `STPPaymentCardTextField` displays card numbers by using a wider kerning where there should be spaces in the card number. I'd recommend pursuing a similar approach in your app.

You can see how we do this if you look at the [source](https://github.com/stripe/stripe-ios/blob/master/Stripe/UI/STPFormTextField.m#L56) for `STPFormTextField`, which is what `STPPaymentCardTextField` uses under the hood.

I'd adapt this for your app something like as follows:
```objc
@import Stripe;

@implementation CUVTextFieldCardNumberDelegate

- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string
{
    NSString *result = [textField.text stringByReplacingCharactersInRange:range withString:string];
    result = [STPCardValidator sanitizedNumericStringForString:result];
    if ([STPCardValidator validationStateForNumber:result validatingCardBrand:YES] == STPCardValidationStateInvalid) {
        return NO;
    }
    NSMutableAttributedString *attributedString = [[NSMutableAttributedString alloc] initWithString:result attributes:[textField defaultTextAttributes]];
    NSArray *cardSpacing;
    STPCardBrand currentBrand = [STPCardValidator brandForNumber:result];
    if (currentBrand == STPCardBrandAmex) {
        cardSpacing = @[@3, @9];
    } else {
        cardSpacing = @[@3, @7, @11];
    }
    for (NSUInteger i = 0; i < attributedString.length; i++) {
        if ([cardSpacing containsObject:@(i)]) {
            [attributedString addAttribute:NSKernAttributeName value:@(5)
                                     range:NSMakeRange(i, 1)];
        } else {
            [attributedString addAttribute:NSKernAttributeName value:@(0)
                                     range:NSMakeRange(i, 1)];
        }
    }
    textField.attributedText = attributedString;
    [super textField:textField shouldChangeCharactersInRange:range replacementString:string];

    return NO;
}

@end
```

I think this is a specific enough thing that it doesn't make sense to implement this directly in stripe-ios, but hopefully this should get you where you need to be. Hope that was helpful!
