### ISSUE TITLE
[BUG] CRASH - STDSACSNetworkingManager is not intended to handle multiple concurrent tasks

### ISSUE THREAD

**Issue by dan-koza** [stripe/stripe-ios#2094]
## Summary
We are receiving crash reports due to concurrent tasks within STDSACSNetworkingManager. Based on the crash log it appears when some users hit cancel on STDSChallengeResponseViewController, it results in this crash.

## Code to reproduce
I do not have any code to show as the crash is within the stripe SDK and pointed out in the stack trace of the attached crash report.

## iOS version
iOS 16, 15 & 14

## Installation method
Swift Package Manager

## SDK version
22.8.1

## Other information
Please see the stack trace from the crash log. 

This crash could be related to https://github.com/stripe/stripe-ios/issues/1858#issue-964945928, but our app already has `Enable Foundation Assertions` set to false for release builds.

![STDSACSNetworkingManager_crash_log](https://user-images.githubusercontent.com/89405839/202577234-805fca37-7ccc-4f6b-a2e9-45f86abf6638.png)

**Comment by davidme-stripe** [comment]
Thanks for filing this. NSAsserts should be disabled by default in release builds, but it appears that [SPM mistakenly enables them](https://forums.swift.org/t/assertions-in-swift-packages/42692).

We'll remove this NSAssert, as we already communicate this error via an NSError. Sorry for the inconvenience!

**Comment by porter-stripe** [comment]
The NSAssert was removed and the fix can be found in the latest release. Closing this out.
