### ISSUE TITLE
[BUG]  Trying to use Address component in SwiftIUI. Getting memory leak.

### ISSUE THREAD

**Issue by stshelton** [stripe/stripe-ios#2101]
## Summary
I want to implement the address component in swiftui. So I created a UIViewRepresentable of the address view controller. It works but when looking at memory graph im seeing some memory leakes within AddressSectionElement, Checkbox Element, FormElement, PhoneNumberElement, SectionElement, and TextFieldElement. Alot of the seem to keeping strong references to each other. Not sure if my swiftui implementation is causing it.

## Code to reproduce
```
struct StripeAddressView: UIViewControllerRepresentable {
  
    
    typealias UIViewControllerType = AddressViewController
    
    //var addressViewController: AddressViewController?
    
    private var addressConfiguration: AddressViewController.Configuration {
        return AddressViewController.Configuration(additionalFields: .init(phone: .optional), buttonTitle: "Purchase")
    }
    
    func makeUIViewController(context: Context) -> AddressViewController {
        var addressViewController = AddressViewController(configuration: addressConfiguration, delegate: context.coordinator)
        //let navigationController = UINavigationController(rootViewController: addressViewController)

        return addressViewController
    }
    
    func updateUIViewController(_ uiViewController: StripePaymentSheet.AddressViewController, context: Context) {
        
    }
    
    static func dismantleUIViewController(_ uiViewController: AddressViewController, coordinator: Coordinator) {
        uiViewController.delegate = nil
        //uiViewController.addressSection?.delegate = nil
        
    }
    
    func makeCoordinator() -> Coordinator {
        Coordinator(parent: self)
    }
    
    class Coordinator: NSObject, AddressViewControllerDelegate{
        var parent: StripeAddressView
       
        
        init(parent: StripeAddressView){
            self.parent = parent
        }
        
        func addressViewControllerDidFinish(_ addressViewController: StripePaymentSheet.AddressViewController, with address: StripePaymentSheet.AddressViewController.AddressDetails?) {
            
        }
    }
}

```

## iOS version
IOS 16.0.3

## Installation method
Swift package manager

## SDK version
23.2.0

## Other information
Leaks From Debug Memory Graph
![Screen Shot 2022-11-22 at 4 04 59 PM](https://user-images.githubusercontent.com/11301401/203420971-d0a7c81a-9b95-4726-a480-4b1b4ed30f38.png)

AddressSectionElement:
![Screen Shot 2022-11-22 at 4 01 01 PM](https://user-images.githubusercontent.com/11301401/203420281-04e4eb42-6278-4713-adeb-eca159cb54a9.png)

CheckBoxElement:
![Screen Shot 2022-11-22 at 4 01 34 PM](https://user-images.githubusercontent.com/11301401/203420378-bfe48526-3663-4a48-bcb1-b6c62f7d3730.png)
![Screen Shot 2022-11-22 at 4 02 03 PM](https://user-images.githubusercontent.com/11301401/203420455-f1b156e6-8e49-4dd6-b33d-6a480104ef18.png)

FormElement:
![Screen Shot 2022-11-22 at 4 02 30 PM](https://user-images.githubusercontent.com/11301401/203420521-5538a156-7d6a-45a5-9ed2-83da3ab97130.png)

PhoneNumberElement:
![Screen Shot 2022-11-22 at 4 03 01 PM](https://user-images.githubusercontent.com/11301401/203420615-726604b4-eada-4d57-95e5-66483d757c0d.png)

Section:
![Screen Shot 2022-11-22 at 4 03 25 PM](https://user-images.githubusercontent.com/11301401/203420747-683af666-9dc1-4dc8-bd6b-1aeb6d0dbaf6.png)

TextFieldElement:
![Screen Shot 2022-11-22 at 4 04 11 PM](https://user-images.githubusercontent.com/11301401/203420832-15b41bbe-1ff7-4175-b953-521e74641288.png)

Swift closure context:
![Screen Shot 2022-11-22 at 4 04 33 PM](https://user-images.githubusercontent.com/11301401/203420915-14f6ff55-f073-4052-8729-8d241dcf8c48.png)

## Extra Info

In my actual swiftui View I had to tell it to ignore safe area `.keyboard`.  Because both the addressviewcontroller and swiftui view would adjust for keyboard, which in return ends up cutting the addressviewcontroller content off. 
Also would be nice for a swiftUI implementation of this.

```
struct AddShippingDetailsView: View {
    var body: some View {
        ZStack{
            VStack{
                StripeAddressView().ignoresSafeArea(.keyboard)
            }
        }
    }
}
```

Example without ignoring safe area:
![IMG_0501](https://user-images.githubusercontent.com/11301401/203423054-d6df987f-6302-4468-84f2-729dbde9bf0b.PNG)

**Comment by wooj-stripe** [comment]
Hi @stshelton  -- thanks for reaching out.

I've taken a quick look at this an it does seem that we are leaking memory here.  I think I identified the issue you're seeing and submitted a proposed fix.  I'll update this thread when I have more information.

Thanks again!

**Comment by wooj-stripe** [comment]
@stshelton -- I've submitted a fix that has been pushed to our master branch and is expected to be in our next release.  If you have any other questions/concerns feel free to reach out. Thanks again!
