### ISSUE TITLE
[BUG] Current month expiration date on cards

### ISSUE THREAD

**Issue by passosfe** [stripe/stripe-ios#2114]
## Summary
Currently there is a discrepancy between iOS and Android SDK, when the user wants to add a card with an expiration date of the current month, the Android SDK accepts it as a valid expiration date, while the iOS SDK considers this as expired, making this card unusable.
After some research, I think the approach made by the Android SDK is correct, can you also make this possible on iOS as well? Right now we have those two different behaviors on our Android and iOS apps.

## Code to reproduce
I'm using the `.paymentSheet` modifier for SwiftUI views.

## iOS version
iOS 13/14/15/16

## Installation method
Cocoapods

## SDK version
22.6.0

## Other information
![IMG_2599B2771FBA-1](https://user-images.githubusercontent.com/54964713/204867065-60b794d1-78d5-4e8f-94ae-e67e9400ff5b.jpeg)
This was taken on November 2022, as you can see, I can't add a card with an expiration date of 11/22

**Comment by yuki-stripe** [comment]
Hello @passosfe, 

This bug should be fixed in 23.0.0 - see https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#2300-2022-10-24
> [Fixed] Fixed a validation issue where cards expiring at the end of the current month were incorrectly treated as expired.
