### ISSUE TITLE
Doesn't play well with auto layout

### ISSUE THREAD

**Issue by harrisnb** [stripe/stripe-ios#213]
Using Auto-layout. When entering card number the outer view border encroaches on other UI Elements:

![image](https://cloud.githubusercontent.com/assets/8995108/9492519/3e72068a-4bf0-11e5-9041-de2fe3594bd1.png)

My solution was to subclass and provide a crude intrinsicContentSize:

    - (CGSize)intrinsicContentSize {
        return self.stripePaymentView.frame.size;
    }

I suspect this would be better if `STPPaymentCardTextField` provided the `intrinsicContentSize` as it knows the correct size and would enhance support for auto-layout.

**Comment by jflinter** [comment]
All great points - taking a look at this now.
