### ISSUE TITLE
STPPaymentCardTextField - Layout issues

### ISSUE THREAD

**Issue by raphaelcruzeiro** [stripe/stripe-ios#215]
I started to migrate our app to stripe-ios as we now need iOS 9 support. All looks well apart from a few issues with the layout of the STPPaymentCardTextField. First of all, I wasn't able to use auto-layout on it so I settled for placing it inside a container. This approach resulted on a text field with the following problems:

- Placeholder text is not hidden when the textfield has a value
- After filling the credit card number, the expiration date and CVC filling occurred outside of the textfield's frame (The animation where the text is supposed to be shifted doesn't happen).

This is the code I use to create the STPPaymentCardField:
```
vi_payment = STPPaymentCardTextField(frame: CGRect(origin: CGPointZero, size: vi_container.frame.size))
vi_payment.delegate = self;
vi_container.addSubview(vi_payment)
```

Maybe it's something on my side. I followed the migration guide and things are mostly the same as they were when I was using the old PaymentKit.

Bellow are some screenshots of the problem:

![photo 27-08-15 12 48 05](https://cloud.githubusercontent.com/assets/425640/9522562/66786bc8-4ccd-11e5-91ea-f8c41411c95f.png)
![photo 27-08-15 12 48 10](https://cloud.githubusercontent.com/assets/425640/9522572/69dc638c-4ccd-11e5-9669-82dc09a31975.png)
![photo 27-08-15 12 48 14](https://cloud.githubusercontent.com/assets/425640/9522577/6d60b5f8-4ccd-11e5-8558-8779b4ae3794.png)
![photo 27-08-15 12 48 20](https://cloud.githubusercontent.com/assets/425640/9522581/7195e8be-4ccd-11e5-9c97-3fa64b9dd867.png)
![photo 27-08-15 12 48 23](https://cloud.githubusercontent.com/assets/425640/9522583/73783222-4ccd-11e5-8e5b-ac62a647e12e.png)

**Comment by jflinter** [comment]
Hey @raphaelcruzeiro,
Can you upload a small example app demonstrating the issues you're having? I'm not able to reproduce any of this locally. It almost looks like you've somehow instantiated 2 instances of STPPaymentTextField on top of each other...

**Comment by raphaelcruzeiro** [comment]
@jflinter, thanks for you prompt response. I first I thought that was not possible but then I noticed that the app was still being build with the STPPaymentTextField defined on the storyboard (from my previous autolayout attempt) and then STPPaymentTextField was instantiated again on viewDidLoad. Cleaning the project fixed this.

Thank you for pointing me in the right direction, and sorry for opening such a stupid issue ;)

**Comment by jflinter** [comment]
No problem, glad I could help.

On Thu, Aug 27, 2015 at 10:40 AM, Raphael Cruzeiro <notifications@github.com
