### ISSUE TITLE
[BUG] In SwiftUI, STPPaymentCardTextField does not clear or have a clear option

### ISSUE THREAD

**Issue by mtantawy1** [stripe/stripe-ios#2152]
## Summary

In SwiftUI I am using, STPPaymentCardTextField.Representable(paymentMethodParams: $paymentMethodParams).

User flow:
1. User enters card details
2. User clicks save
3. View updates and adds card in a ListView

The STPPaymentCardTextField still has all of the credit card information after saving. How do I clear the view so that the user can enter another credit card if they would like?

Code to reproduce

```
struct TestView: View {
    @StateObject var model = ...
    @State var paymentMethodParams: STPPaymentMethodParams?
    var body: some View {
        List {
            ForEach($model.cards, id:\.self) { card in
				…
            }
            
            Section {
                STPPaymentCardTextField
                    .Representable(paymentMethodParams: $paymentMethodParams)
                
                Button("Save") {
                            // API Call
                }
   
            } header: {
                Text("Add Card")
            }
        }
    }
}
```

## iOS version
16.0

## Installation method
Swift package Manager

## SDK version
23.2.0

**Comment by davidme-stripe** [comment]
Hello, thanks for filing this! This isn't the most elegant option, but you can clear the field by setting `paymentMethodParams` to an empty object:
```
            Section {
                STPPaymentCardTextField
                    .Representable(paymentMethodParams: $paymentMethodParams)
                Button("Save") {
                            // API Call
                            paymentMethodParams = STPPaymentMethodParams(card: STPPaymentMethodCardParams(), billingDetails: nil, metadata: nil)
                } 
            }
```
Would that work for your use case?

**Comment by mtantawy1** [comment]
Thank you! Yes this worked. 

One more question. If I want to validate the card details prior to making the API call or while the user is typing to disable/enable save button. How would you recommend doing that?

I saw the class STPCardValidator which has a class func for validate card but that takes an STPCard and STPPaymentMethod has STPPaymentMethodCard. 

Do I need to validate separately (validateNumber, validateExpiration etc)? What is the best practice?

**Comment by davidme-stripe** [comment]
You should be able to disable the button if the `paymentMethodParams` binding is nil — it should only be populated if the card is valid. Unfortunately, due to an oversight, this doesn't work if you manually set the paymentMethodParams. Very sorry about that! Here's a hack to get you unblocked, but we'll keep this issue open to fix the bug.
```
Section {
  STPPaymentCardTextField
   .Representable(paymentMethodParams: $paymentMethodParams)
  Button("Save") {
    // API Call
    // Then clear the card field and set paymentMethodParams to nil:
    DispatchQueue.main.async {
      paymentMethodParams = STPPaymentMethodParams(card: STPPaymentMethodCardParams(), billingDetails: nil, metadata: nil)
      DispatchQueue.main.async {
        paymentMethodParams = nil
      }
    }
  }.disabled(apiCallInProgress || paymentMethodParams == nil)
}
```

**Comment by porter-stripe** [comment]
Closing as it appears the suggested workaround satisfied the ask! Feel free to re-open if needed.
