### ISSUE TITLE
Add the ability to modify the placeholder for each components of the STPPaymentCardTextField

### ISSUE THREAD

**Issue by pblondin** [stripe/stripe-ios#216]
As for now, I have to do a dirty fix and expose some private properties using class extension.

Also the 'formatsCardNumbers' should be expose for the 'numberField' if we want the placeholder to be something else then a formatted card number.

**Comment by jflinter** [comment]
I've implemented this in 794d1d323284e4d992f7bb5192765c72ce7893d4. It wasn't actually necessary to expose the `formatsCardNumbers` property - instead we'll just only format strings that actually look like card numbers there.

**Comment by pblondin** [comment]
Perfect! Thanks a lot for this addition!
