### ISSUE TITLE
[BUG] Stripe Card Scan screen hangs with no internet access

### ISSUE THREAD

**Issue by nickm01** [stripe/stripe-ios#2185]
## Summary
Stripe Card Scan screen hangs with no internet access

Steps
1. Present the scan screen with valid civ and working internet. 
2. After the scan screen appears, remove internet access.
3. Now scan the correct card.  The spinner comes up and shortly the completion block is executed with an error status (expected)
4. The presented scan screen never is dismissed (see attached #2) (unexpected)
5. Also note restoring internet access does not dismiss the screen either - user is stuck.

## Code to reproduce
```
let sheet = CardImageVerificationSheet(
    cardImageVerificationIntentId: civId,
    cardImageVerificationIntentSecret: civClientSecret
)

sheet.present(from: navigationController) { verificationResult in
    ....
}
```

## iOS version
iOS 14.0

## Installation method
pods

## SDK version
`22.6.0` and also has the same problem on `23.3.1`

**Comment by jaimepark-stripe** [comment]
Closing this ticket since we resolved it on Slack!
