### ISSUE TITLE
Allow setting STPPaymentCardTextField values externally

### ISSUE THREAD

**Issue by alampila** [stripe/stripe-ios#219]
Setting card number, expiration, and cvc for STPPaymentCardTextField externally would be extremely useful. For example, when scanning a card with the camera there is no way to populate a STPPaymentCardTextField with the captured values.

**Comment by jflinter** [comment]
This is totally reasonable, and something we'll look into in a future release. It's a bit complicated as it adds some more state, but shouldn't be too bad.

**Comment by pblondin** [comment]
+1 for this one.

**Comment by pblondin** [comment]
@jflinter, do you have any timeline for this new feature? I'm willing to have a look at it if you need any help.

**Comment by lukabratos** [comment]
This feature would be extremely useful. It would work especially good with [card.io](https://github.com/card-io/card.io-iOS-source)

**Comment by fpillet** [comment]
+1. Currently using the hack way with a subclass of STPPaymentCardTextField, getting the fields with a -valueForKey: and filling them up. Dirty.

**Comment by zachlucas** [comment]
+1 :)

**Comment by zachlucas** [comment]
+1 :) @fpillet would you care to share your subclass?

**Comment by pblondin** [comment]
In my case, I came up with something like this :

```
/**
 *  Really dirty, but there is no current way to do otherwise with the provided API.
 *  Check update here: https://github.com/stripe/stripe-ios
 */
- (void)prefillWithCreditCard:(CreditCard *)cc {
    // we need to fake the color
    self.textErrorColor = self.textColor;

    self.numberField.text = [NSString stringWithFormat:@"000000000000%@", cc.last_four_number];

    NSString *expMonth2Digits = [NSString stringWithFormat:@"%02d", [cc.expiry_month intValue]];
    NSString *expYear2Digits = [NSString stringWithFormat:@"%02d", [cc.expiry_year intValue]];

    self.expirationField.text = [NSString stringWithFormat:@"%@/%@", expMonth2Digits, expYear2Digits];
    self.cvcField.text = @"***";

    STPCardBrand cardBrand = [PaymentCardTextField getCardType:cc];
    self.brandImageView.image = [PaymentCardTextField brandImage:cardBrand];

    [self setNumberFieldShrunk:YES animated:NO completion:nil];
}
```

**Comment by fpillet** [comment]
@zachlucas here is the subclass. Works just fine since it matches the internal behavior of `STPPaymentCardTextField`:

```objc
@interface PaymentCardEditorField : STPPaymentCardTextField
- (void)setExistingCard:(STPCard *)card;
@end
```

```objc
@implementation PaymentCardEditorField

- (void)setExistingCard:(STPCard *)card {
	[self replaceField:@"numberField" withValue:card.cardNumber];
	[self replaceField:@"expirationField" withValue:[NSString stringWithFormat:@"%02d/%02d", (int)card.expMonth,(int) card.expYear]];
}

- (void)replaceField:(NSString *)memberName withValue:(NSString *)value {
	UITextField *field = [self valueForKey:memberName];
	if ([(id<UITextFieldDelegate>)self textField:field shouldChangeCharactersInRange:NSMakeRange(0, field.text.length) replacementString:value]) {
		[field setText:value];
	}
}
@end
```

**Comment by zachlucas** [comment]
Thank you both, very helpful!

**Comment by ryanwaggoner** [comment]
+1

**Comment by togonow** [comment]
Thanks a lot for the work around, needed to use this with to add card.io

**Comment by garnett** [comment]
+1, looking forward for update

**Comment by Liampronan** [comment]
@fpillet +1 -- thanks for sharing!

**Comment by togonow** [comment]
@fpillet 
 seems we only need the last 2 digits of the expiration year otherwise it will always assume the year is 20 instead of 2016 for example.
```
- (void)setExistingCard:(STPCardParams *)card {

    [self replaceField:@"numberField" withValue:card.number];
   
    int cardexpYearLastTwoDigits = (int)card.expYear - 2000;
    [self replaceField:@"expirationField" withValue:[NSString stringWithFormat:@"%02d/%02d", (int)card.expMonth,(int) cardexpYearLastTwoDigits]];
    [self replaceField:@"cvcField" withValue:card.cvc];
}

- (void)replaceField:(NSString *)memberName withValue:(NSString *)value {
    UITextField *field = [self valueForKey:memberName];
    if ([(id<UITextFieldDelegate>)self textField:field shouldChangeCharactersInRange:NSMakeRange(0, field.text.length) replacementString:value]) {
        [field setText:value];
    }
}
```

**Comment by fpillet** [comment]
@togonow Thank you, good catch! I updated my sample above to use a simpler version (card.year % 100) of your patch, so that others who copy paste my code don't end up with buggy behavior.

**Comment by togonow** [comment]
@fpillet  yep!

**Comment by cartickn** [comment]
Thanks for the subclass solution! I am trying to convert this to swift and wonder what this means.

    if ([(id<UITextFieldDelegate>)self textField:field shouldChangeCharactersInRange:NSMakeRange(0, field.text.length) replacementString:value]) {
        [field setText:value];

I got this far and I'm not sure how to get a reference to the (id<UITextFieldDelegate>)self textField portion :(

    func setExistingCard(card: STPCardParams) {
        replaceField("numberField", withValue: card.number!)
        replaceField("expirationField", withValue: String(format: "%02d/%02d", card.expMonth, (card.expYear % 100)))
    }
    
    func replaceField(memberName: String, withValue value: String) {
        var field: UITextField = self.valueForKey(memberName) as! UITextField
        if [TODO:]textField(field, shouldChangeCharactersInRange: NSMakeRange(0, field.text.length), replacementString: value) {
            field.text = value
        }
    }

**Comment by fpillet** [comment]
It downcasts `self` to a `UITextFieldDelegate` (which it is) so as to be able to call the `-textField:shouldChangeCharactersInRange:replacement:` method. 

In Swift you can downcast this way:
```
let selfDelegate = self as! UITextFieldDelegate
if selfDelegate.textField(field, shouldChangeCharactersInRange: NSMakeRange(0, field.text.length), replacementString: value) {
    field.text = value
}
```

**Comment by cartickn** [comment]
Thank you so much! That makes sense. This is how the subclass looks now...

    import Stripe

    class PaymentCardEditorField: STPPaymentCardTextField {
    
        func setExistingCard(card: STPCardParams) {
            replaceField("numberField", withValue: card.number!)
            replaceField("expirationField", withValue: String(format: "%02d/%02d", card.expMonth, (card.expYear % 100)))
        }
    
        func replaceField(memberName: String, withValue value: String) {
            var field: UITextField = self.valueForKey(memberName) as! UITextField
            let delegate = self as! UITextFieldDelegate
            if delegate.textField?(field, shouldChangeCharactersInRange: NSMakeRange(0, field.length), replacementString: value) {
                field.text = value
            }
        }
    }

Is `var field: UITextField = self.valueForKey(memberName) as! UITextField` accurate conversion for `UITextField *field = [self valueForKey:memberName];`

field.length or field.text.length seems to be invalid. Still digging, not sure what I am doing wrong.

**Comment by andriantolie** [comment]
When I set it this way, STPPaymentCardTextField seems not to check the entered value and show them as red until I click on the textfield and press any button on the keyboard. Is there any workaround to check the validity of the entered card number using this hack?

**Comment by gmarm** [comment]
Hey, I just created my own solution using an Objective-C category based on the various solutions posted above. Seems to be working fine.

My approach seems to fix an issue with the previous solutions that the number text field is not validated and not getting shrunk when needed.

You can find it here:
[STPPaymentCardTextField+Filling.h](https://gist.github.com/gmarm/915580b1c3804e2bf99b)
[STPPaymentCardTextField+Filling.m](https://gist.github.com/gmarm/b2516bbd82284a31b9f1)

Any feedback or suggestions are very welcome!

**Comment by RajkumarThyadi** [comment]
if delegate.textField?(field, shouldChangeCharactersInRange: NSMakeRange(0, len!),                  replacementString: value) ?? false {
            field.text = value
             }
Not passing if condition.

Any help much appreciated.

**Comment by gmarm** [comment]
@RajkumarThyadi I believe there is no need for these workarounds anymore. 

Setting a card has been added with [this](https://github.com/stripe/stripe-ios/pull/290).

**Comment by RajkumarThyadi** [comment]
@gmarm Thanks for reply . In swift , I can't able to use "setCard" method as it is not mentioned in STPPaymentCardTextFieldDelegate methods. Add I can't able to edit this class.

**Comment by gmarm** [comment]
@RajkumarThyadi If I understand correctly from the PR, it should be as easy as doing some like `textField.card` = `STPCardParams(...)`.

Does this not work for you?

**Comment by RajkumarThyadi** [comment]
Its working , Thanks @gmarm
