### ISSUE TITLE
Unknown type name 'STPCard'

### ISSUE THREAD

**Issue by rahuljaswa** [stripe/stripe-ios#221]
Hi there, I'm sure there must be some configuration issue, but hard for me to understand where I could have gone wrong. Installed v5.1.2 via CocoaPods. 

The compiler can't find the interface declaration for STPCard (and looking through the STPPaymentCardTextField header file, I'm not seeing a class declaration for STPCard or and #import for the STPCard header file).

Please see the screenshot below. Thanks.

![image](https://cloud.githubusercontent.com/assets/561859/9623938/a0474f26-50fc-11e5-8cf5-7fa3504379c2.png)

**Comment by benzguo** [comment]
`STPCard` is imported in [`Stripe.h`](https://github.com/stripe/stripe-ios/blob/v5.1.2/Stripe/PublicHeaders/Stripe.h#L13). Are you importing `STPPaymentCardTextField.h` directly? Be sure to use `#import <Stripe/Stripe.h>` to import the library. Hope this helps!

**Comment by rahuljaswa** [comment]
Hi @benzguo, thanks for following up here. That was it. I was importing `STPPaymentCardTextField.h` directly, but just changing that to import `Stripe.h` didn't fix the problem. Strangely enough, I had to do one of two things to make it compile: 1) Add an import for `STPCard.h`, compile, then remove that import, or 2) delete and then reinstall the Stripe pod.

Separately, it seems like `STPCard.h` should be imported in `STPPaymentCardTextField.h`, as there's a (deprecated) `STPCard` subclass declared in that file. Doesn't seem inconsistent with the pattern used elsewhere (e.g. `STPCardValidator`), but just a thought. 

Thanks again for the help!

**Comment by benzguo** [comment]
Strange indeed. Maybe due to something something derived data? Glad I could help.
