### ISSUE TITLE
Dynamic publishableKey

### ISSUE THREAD

**Issue by tariq235** [stripe/stripe-ios#224]
As per Stripe documentation we are required to setup setDefaultPublishableKey as soon as possible in the app life cycle. Preferred place is didFinishLaunchingWithOptions.

But in our app we can have multiple publishableKey. Obviously we don't need multiple publishableKey at the same time.

But n different features in the app can support n different publishableKey. publishableKey is coming from our server so we cannot hardcode the value.

Can we call set method n number of times with different keys ?
like     [Stripe setDefaultPublishableKey:dynamic_key_from_api];

Let me know how to handle such use case.

**Comment by jflinter** [comment]
Hi there,
To support using multiple publishable keys, you can simply stop using `setDefaultPublishableKey` and `[STPAPIClient sharedClient]`. Instead, you can simply create a new `STPAPIClient` at the time you need to make a new request, and the designated initializer for `STPAPIClient` takes a publishable key:
```objectivec
STPAPIClient *client = [[STPAPIClient alloc] initWithPublishableKey:myPublishableKey];
// use client as you otherwise would, e.g. [client createTokenWithCard...]
```
