### ISSUE TITLE
[BUG] Xcode 14.2 Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by elkateeb88** [stripe/stripe-ios#2249]
## Summary
Stored properties cannot be marked potentially unavailable with '@available'

<img width="717" alt="Screen Shot 2023-01-30 at 3 10 01 PM" src="https://user-images.githubusercontent.com/94823498/215488125-5accae1b-e76c-40ec-8dbe-85a1598c2d5f.png">

## Installation method
podfile

## SDK version
21.13.0

## Other information
I have discovered that the issue in the updated SDK has been resolved, however, I am unable to proceed with the update due to my target app version being set at ios 11.

**Comment by yuki-stripe** [comment]
Hello  @elkateeb88,

Thanks for writing in. First suggestion - can you fork the repo and make the necessary updates to compile with Xcode 14?

**Comment by elkateeb88** [comment]
@yuki-stripe so just to clarify: This means that clients of this SDK will not be able to use the Stripe-SDK with the latest Xcode 14 version while still supporting iOS 11?
Out app currently has a minimum deployment target of iOS 11 and still quite a few customers are on those versions. To my knowledge version 21.13.0 was the last version that still supported iOS 11 and is currently stripe's recommended version for targeting iOS 11. Is there no other option aside from either not upgrading to Xcode 14 (not a long term option) or raising our minimum deployment target?

[2011#](https://github.com/stripe/stripe-ios/issues/2011#issuecomment-1331934394)

**Comment by asadmumtaz92** [comment]
@yacine-stripe 

Can you solve this issue for Xcode 14 or later?

**Comment by pranjali420** [comment]
I am facing the same issue,  is there any workaround that we can do? We also have a minimum iOS target of 12.

**Comment by sfriedman-stripe** [comment]
Hi all, the minimum supported version is iOS 13 for the latest version of the Stripe SDK, and this will become iOS 14 in Spring 2024. Version 21.13.0 of the Stripe SDK was the last to target iOS 11, and unfortunately it seems updates Apple made to the Swift compiler in Xcode 14.2 is causing issues. To work around the issues Apple has introduced and if you cannot upgrade to the latest version of the Stripe SDK, you will need to fork the SDK.

Please feel free to contact our support team at support.stripe.com if you are facing any issues upgrading to the latest version of the Stripe SDK version 23.
