### ISSUE TITLE
Stripe Framework is returning STPCardValidationStateIncomplete for 3-digit AMEX CVC

### ISSUE THREAD

**Issue by simX** [stripe/stripe-ios#225]
The new validationStateForCVC:cardBrand: method on STPCardValidator is returning STPCardValidationStateIncomplete for a 3-digit CVC and an STPCardBrandAmex brand.

This is better than returning STPCardValidationStateInvalid, but it's still wrong, because a 3-digit CVC is completely valid.  Whereas getting STPCardValidationStartIncomplete from a 2-digit CVC is *actually* incomplete.

This means that I'll once again have to special-case AMEX cards in my code.  Any idea when this can be fixed?

**Comment by jflinter** [comment]
This is now fixed on master, as well as the just-released version 5.1.3.
