### ISSUE TITLE
[Feature] Add the flag "BUILD_LIBRARY_FOR_DISTRIBUTION"

### ISSUE THREAD

**Issue by jesus-mg-ios** [stripe/stripe-ios#2255]
## Is your feature request related to a problem? Please describe.
We want to integrate directly the binary compiled by Stripe.
We cannot because it is compiled with a lower swift version than the version we use 

## Describe the solution you'd like
Making the build for distribution applies the abi stability and makes it possible to integrate directly into our app

**Comment by yuki-stripe** [comment]
Hello,

We do use `BUILD_LIBRARIES_FOR_DISTRIBUTION=YES`. Could you say more about how you are integrating the Stripe SDK?  In case it's helpful, check out https://github.com/stripe/stripe-ios/issues/1850 - sounds similar to yours.

**Comment by porter-stripe** [comment]
Closing this as stale, @jesus-mg-ios please re-open if you are still encountering the issue with the latest details.
