### ISSUE TITLE
[BUG] PaymentSheet Error on First Click of View

### ISSUE THREAD

**Issue by erichCompSci** [stripe/stripe-ios#2268]
## Summary
The first time that a user presses on a button that causes the payment sheet UI to come up in SwiftUI, an error message is displayed to the screen.  The error message instructs the user to try again in a few seconds.  Upon pressing the button a second time, the payment sheet appears normally and works as expected.  

This does not happen on Debug or Test Mode.  It only happens on Release and so far, I've only seen this happen on iOS 16, but I'm not sure it won't happen on iOS 15.  I just can't test.  We are using Stripe version 23.3.3.

## Code to reproduce
`VStack {
          Button(action: {
                     onSheetPresented.toggle()
                      }, label: { Text("Push") })
  }.paymentSheet(isPresented: $onSheetPresented, paymentSheet: local_payment_sheet, onCompletion: onSetupIntentCompletion)
`

## iOS version
16.0+

## Installation method
SwiftUI Package Manager

## SDK version
23.3.3

## Other information
I've attached a screenshot.  This was working in earlier versions of iOS without any issue, it seems to be something new that was introduced, but I can't say when.
![stripe_error_on_release](https://user-images.githubusercontent.com/8547309/216842802-e7f1c5b9-6cf7-433c-b92d-e5cb3c5d6e96.jpg)

**Comment by yuki-stripe** [comment]
Hey @erichCompSci, sorry we never answered this! Based on that error message, PaymentSheet was initialized using an empty string as the `setupIntentClientSecret`. I'm closing this issue but feel free to re-open.
