### ISSUE TITLE
Card account holder's name and address

### ISSUE THREAD

**Issue by rughvi** [stripe/stripe-ios#231]
Hi team,
I am using the iOS SDK to play with the card payments using Stripe.
The SDK (STPPaymentCardTextField) has got only 3 fields for generating token for the card :
1. credit card field
2. expiry date field
3. CVC field

Do we not require NAME and ADDRESS of the card holder for the banks to authorise the payment.
Does the SDK support the functionality to store the card information and retrieve the same for later use?

Thanks,
Venkat.

**Comment by henrystewart** [comment]
That's a great question Venkat. I was wondering if STPPaymentCardTextField has a way to add zipcode  as well? Or should that just be a separate form all together?

**Comment by jflinter** [comment]
Hi there,
If you're looking to collect your users' name and address, I'd suggest just using a `UITextField` of your own. You can add the values to an `STPCard` before calling `createTokenWithCard`. Our SDK doesn't support saving a card for reuse on the client, as we don't recommend this for PCI reasons. Instead, after you create a token, you should create a customer with that token on your backend if you want to charge their card again. For more information, see https://stripe.com/docs/tutorials/charges#saving-credit-card-details-for-later
