### ISSUE TITLE
ZatmanOptionz 

### ISSUE THREAD

**Issue by ZatmanOptionz24** [stripe/stripe-ios#2328]
https://github.com/GoogleCloudPlatform/golang-samples/blob/HEAD/run/helloworld/go.mod

**Comment by sfriedman-stripe** [comment]
@ZatmanOptionz24 This is the 4th issue with no content you have posted to our mobile repos in the past 3 days. If this continues, we will unfortunately have to restrict your access to our repos. Thank you
