### ISSUE TITLE
[Feature] Support auto-fill for CardFormView

### ISSUE THREAD

**Issue by hcq0618** [stripe/stripe-ios#2329]
## Is your feature request related to a problem? Please describe.
Provide a function which is able to enable auto-fill for credit card number/postal code/cvc/expired date of CardFormView

## Describe the solution you'd like
Set a `UITextContentType` may help: https://developer.apple.com/documentation/uikit/uitextcontenttype
A similar issue for Android https://github.com/stripe/stripe-android/issues/6274

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by davidme-stripe** [comment]
This isn't supported by Apple, unfortunately — they only allow credit card autofill in Safari or an SFSafariViewController. We'll add support for this as soon as Apple does.

**Comment by hcq0618** [comment]
Got it thanks
