### ISSUE TITLE
Adding zipcode field to STPPaymentCardTextField

### ISSUE THREAD

**Issue by henrystewart** [stripe/stripe-ios#233]
The iOS SDK's "STPPaymentCardTextField" has only 4 fields for generating a token for a card :
1. credit card number
2. expiration month
3. expiration year
4. CVC field

Is there another field available for programmatically adding zip/postal code to the STPPaymentCardTextField? Or should I use a separate textfield to handle this (and possibly other fields for the STPCard)?

**Comment by jflinter** [comment]
We don't currently offer a pre-built address collection component, sorry. I'd suggest just using a `UITextField`.

**Comment by imuhammadkhan** [comment]
Is the same field still unavailable? please do confirm me.

Thanks

**Comment by bg-stripe** [comment]
@imuhammadkhan you can now add a postal code field to `STPPaymentCardTextField` by setting `textField.postalCodeEntryEnabled = true`.

https://github.com/stripe/stripe-ios/blob/master/Stripe/PublicHeaders/STPPaymentCardTextField.h#L217

**Comment by galladivya** [comment]
Hey how to remove postalcode

**Comment by aliriaz-stripe** [comment]
@galladivya you can disable `postalCodeEntryEnabled = false` on your STPPaymentCardTextField

**Comment by galladivya** [comment]
It gives textField as unknow type name "textField". I have used textField.postalCodeEntryEnabled= False in STPPaymentCardTextField.h file

**Comment by aliriaz-stripe** [comment]
@galladivya you have to do this when you create an instance of STPPaymentCardTextField and set it up on your view controller, not in STPPaymentCardTextField.h

e.g. 
```
let paymentCardTextField = STPPaymentCardTextField()
// set up paymentCardTextField , add it to subview, etc
paymentCardTextField.postalCodeEntryEnabled = false```

**Comment by galladivya** [comment]
Thanks @aliriaz-stripe your suggested code worked.
