### ISSUE TITLE
[Feature] Make STPTheme affect all Stripe UI components

### ISSUE THREAD

**Issue by matijakregarGH** [stripe/stripe-ios#2331]
## Is your feature request related to a problem? Please describe.
I would like use Stripe UI components `STPCardFormView` or `STPPaymentCardTextField` and customise their appearance with `STPTheme` as described in the documentation.

## Describe the solution you'd like
For components without an initialiser that takes a `theme` the `defaultTheme` should affect the component appearance. 
The "lowest hanging fruit" I can see (but it doesn't solve font settings) is to map the `STPTheme` settings in the `InputFormColors`. 
Ideally the STPTheme would be expanded with a few other properties (`cursorColor`, `lineColor`, `activeLineColor`, `disabledLineColor`) and all Stripe UI components would be affected by it.

## Describe alternatives you've considered
I have tried recursively walking through subviews and tried setting fonts and colors on text fields, but most of the color settings are not accessible even this way. I could change the input fields spacing in the form view though.

**Comment by davidme-stripe** [comment]
Thanks for the feedback! Our current customization focus is on the [PaymentSheet Appearance API](https://stripe.com/docs/elements/appearance-api), but we'll continue to track this.

**Comment by sfriedman-stripe** [comment]
Hi @matijakregarGH, we will not be adding further functionality to `STPCardFormView` or `STPPaymentCardTextField`. We encourage you to check out our modern replacement, the [Mobile Payment Element](https://stripe.com/docs/payments/accept-a-payment?platform=ios), and send us any feedback you have! Thank you

**Comment by davidme-stripe** [comment]
Adding a little more context, as this issue has surprisingly good SEO: You can change the appearance of [STPPaymentCardTextField](https://stripe.dev/stripe-ios/stripepaymentsui/documentation/stripepaymentsui/stppaymentcardtextfield/) (including borders, fonts, and colors) and [STPCardFormView](https://stripe.dev/stripe-ios/stripepaymentsui/documentation/stripepaymentsui/stpcardformview) (only colors) using the parameters provided. We don't plan to add additional customization options at this time.
