### ISSUE TITLE
kind:improvement bitcode

### ISSUE THREAD

**Issue by ionutivan** [stripe/stripe-ios#234]
please add bitcode support

**Comment by jflinter** [comment]
Bitcode is already enabled for our SDK. Is there a specific issue you're seeing?

**Comment by ionutivan** [comment]
I added manually the Stripe framework. When I build the project I get this error: "'<...>/Stripe.framework/Stripe(STPCheckoutOptions.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64"  


     On Friday, September 18, 2015 2:13 AM, Jack Flintermann <notifications@github.com> wrote:
   

 Bitcode is already enabled for our SDK. Is there a specific issue you're seeing?—

**Comment by jflinter** [comment]
The framework that we host on https://github.com/stripe/stripe-ios/releases is a static framework, which don't support bitcode. If you're looking to enable bitcode, you'll need to include stripe-ios in your project as a dynamic framework. The easiest way to do this is by using a dependency manager like Cocoapods or Carthage - there are instructions on how to do this at stripe.com/docs/mobile/ios . You can also clone this repository and drag `Stripe.xcodeproj` into your project directly.

**Comment by ionutivan** [comment]
Thanks!
