### ISSUE TITLE
Setting a Value STPPaymentCardTextField on viewDidLoad

### ISSUE THREAD

**Issue by levisbotio** [stripe/stripe-ios#235]
How can i set a value for cardNumber,expirationMonth and expirationYear when the STPPaymentCardTextField is loaded instead of typing it manually? I tried

`var paymentField = STPPaymentCardTextField()
    override func viewDidLoad() {
        super.viewDidLoad()`
        
        paymentField.frame = CGRectMake(15, 110, CGRectGetWidth(self.view.frame) - 30, 44)
        paymentField.delegate = self
        paymentField.cardNumber = "42424242424242424242"
        self.view.addSubview(paymentField)
    }

But this gives me an error "Cannot assign to the result of this expression" on this line `paymentField.cardNumber = "42424242424242424242`

**Comment by jflinter** [comment]
This isn't currently supported, but something we'll look into in the future. I'm closing this as a duplicate of #219.

**Comment by mobiwebshweta** [comment]
Hi,
is there any solution for set a value for cardNumber,expirationMonth and expirationYear with STPPaymentCardTextField when loaded?

 paymentField.cardNumber = "42424242424242424242";

**Comment by benzguo** [comment]
Hey @mobiwebshweta – you can do this by setting the field's `cardParams`:

```
let cardParams = STPCardParams()
cardParams.number = "4242424242424242"
self.paymentField.cardParams = cardParams
```

https://github.com/stripe/stripe-ios/blob/c6330c36800734b23f76fa016dc482fa0df637a1/Stripe/PublicHeaders/STPPaymentCardTextField.h#L259-L265

**Comment by zykis** [comment]
Doesn't seems to reload an UI properly =/

**Comment by yuki-stripe** [comment]
> Doesn't seems to reload an UI properly =/

Hi @zykis 

Could you make a new issue with repro steps for what you're seeing?  Thanks!

**Comment by zykis** [comment]
Hey, @yuki-stripe !
Sure.
https://github.com/stripe/stripe-ios/issues/1451

**Comment by RamshadOnBeat** [comment]
I need to scan card and display the scanned values
I am using STPCardFormView() instead of STPPaymentCardTextField()
and i am unable to set the card numbers and others after scanning card


            let cardParams = STPCardParams()
            cardParams.number = info.cardNumber
            cardParams.expMonth = info.expiryMonth
            cardParams.expYear = info.expiryYear
            cardParams.cvc = info.cvv
            
            let card = STPCardFormView()
            card.cardParams = cardParams

I am getting an error "Cannot assign to property: 'cardParams' setter is inaccessible"

hoe can I set cardformview textfield values

**Comment by ankitpunchh** [comment]
Any luck on this yet ? Please
