### ISSUE TITLE
Expose textfield(s) via property or method

### ISSUE THREAD

**Issue by nickenchev** [stripe/stripe-ios#236]
Hey, I'd like to be able to change the keyboard color etc on the STPPaymentCardTextField. I currently can't find a public method/property that exposes the UITextField. Can you please provide guidance or add it to the public API.

Thanks

**Comment by jflinter** [comment]
Hey there, is `keyboardAppearance` the only property that you're looking to use? In the interest of being able to modify things under the hood more easily in the future, I'd rather not expose the underlying text fields directly if possible. That being said, I've added `keyboardAppearance
