### ISSUE TITLE
Can't return success upon 3D Secure validation [BUG] 

### ISSUE THREAD

**Issue by florianmonfort** [stripe/stripe-ios#2396]
## Summary
We are currently implementing's Stripe latest iOS SDK.
Upon successful test with 3D Secure test card, "Authenticate unless set up" https://stripe.com/docs/testing#authentication-and-setup
We always get response failure from Stripe iOS SDK. Android and Web work fine.

## Code to reproduce
The project is very big and we can't share it, confidential. We can only share this current implementation screenshot:
![4a402e64bb9b2cd63eeade5617c2b572](https://user-images.githubusercontent.com/1446429/226301925-4a477aa4-c871-4be2-8f37-bad836208961.png)

## iOS version
Any version

## Installation method
Cocoapods

## SDK version
22.8.4

## Other information
Result in XCode:
![5ccd7e04257183e86cfae34d645da26d](https://user-images.githubusercontent.com/1446429/226301457-ce609bda-1fc1-4303-b9c5-da1dc1afeda5.png)

**Comment by porter-stripe** [comment]
Hi @florianmonfort I am unable to reproduce this issue with the test card you provided. I tested on the latest version of the SDK [23.5.0](https://github.com/stripe/stripe-ios/releases/tag/23.5.0). Can you update from 22.8.4 to the latest and let us know if the issue persists.

**Comment by florianmonfort** [comment]
Hello @porter-stripe seems the issue had to do with our own code which was conflicting with Stripe SDK, we managed to fix it, you can close this.
