### ISSUE TITLE
[Feature] `UIDevice.currentDevice.name` access isn't allowed on iOS 16 from third party SDKs, but Stripe is using it.

### ISSUE THREAD

**Issue by amayers** [stripe/stripe-ios#2398]
## Is your feature request related to a problem? Please describe.
The Stripe SDK [accesses](https://github.com/stripe/stripe-ios/blob/94583773331718db238b78f261ef2e5822e46450/Stripe3DS2/Stripe3DS2/STDSDeviceInformationParameter.m#L227) `UIDevice.currentDevice.name`. [As of iOS 16](https://developer.apple.com/documentation/uikit/uidevice/1620015-name) that device name is no longer the user set device name. Instead it's a generic name like `iPhone` so to not leak PII. Apps can request access to an [entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_device-information_user-assigned-device-name) to gain access to the iOS <= 15 behavior. However this comes with some conditions. The relevant one for this discussion is: 
```
Your app doesn’t share the user-assigned device name with any service providers or third parties other than cloud-hosting service providers
```

Stripe is a third party to anybody's app, so per Apple's rules we can't get this entitlement while Stripe is accessing `UIDevice.currentDevice.name` in its SDK.

 
## Describe the solution you'd like
Delete `deviceName` from [STDSDeviceInformationParameter](https://github.com/stripe/stripe-ios/blob/94583773331718db238b78f261ef2e5822e46450/Stripe3DS2/Stripe3DS2/STDSDeviceInformationParameter.m#L227), or if you want to keep it, change it to use something else like `UIDevice.currentDevice.model` that won't contain PII.

## Describe alternatives you've considered
Not using Stripe's SDK.

## Implementation
I've opened a PR https://github.com/stripe/stripe-ios/pull/2400 that removes the `deviceName` param entirely.

**Comment by porter-stripe** [comment]
Hi @amayers, this has been resolved in version 23.5.1!
