### ISSUE TITLE
STPPaymentCardTextField UI error when second time adding the card after first time fails

### ISSUE THREAD

**Issue by haozeng** [stripe/stripe-ios#241]
I have implemented STPPaymentCardTextField in the viewDidLoad and it all works fine until I try to add the second card after the first one regardless of its success or failure.

Here is some code sample and screenshots:

```swift

    override func viewDidLoad() {
        super.viewDidLoad()

        paymentTextField = STPPaymentCardTextField()
        paymentTextField.delegate = self
        self.view.addSubview(paymentTextField)


        constrain(paymentTextField) { paymentTextField in
            paymentTextField.top == paymentTextField.superview!.top + 85
            paymentTextField.left == paymentTextField.superview!.left + 15
            paymentTextField.right == paymentTextField.superview!.right - 15
            paymentTextField.height == 44
        }
    }
```

![if card error shows up, and api returns a message](https://cloud.githubusercontent.com/assets/2443025/10037391/4d172c1c-616a-11e5-9053-29fb60b834c7.png)

![re-entering the card gives broken UI](https://cloud.githubusercontent.com/assets/2443025/10037392/5a8c9224-616a-11e5-89ef-7872a827527f.png)

![one more](https://cloud.githubusercontent.com/assets/2443025/10037399/7257f33a-616a-11e5-95e3-304d6a855975.png)

**Comment by jflinter** [comment]
Hi there,
I'm having trouble reproducing your issue; I suspect there's more to it than the code you've included. Could you possibly put together and link to a small example app that reproduces it?

**Comment by haozeng** [comment]
MBProgressHUD is messing up with the STPPaymentCardTextField as i found out.

**Comment by jflinter** [comment]
Ok, good to know. I'd be interested in hearing what was going wrong if you figured things out.

**Comment by haozeng** [comment]
i called MBProgressHUD.showHUDAddedTo(self.navigationController!.view, animated: true) to initiate the http request and block the user interaction, when i called MBProgressHUD.hideHUDForView(self.navigationController!.view, animated: true) after the http request, it messed up the textfield view.

**Comment by jflinter** [comment]
Cool, I've created https://github.com/stripe/stripe-ios/issues/243 to
remind me to take a look at this in the future. If MBProgressHUD and
STPPaymentCardTextField are both properly implemented, this kind of thing
shouldn't be possible.
