### ISSUE TITLE
Error after updating to Xcode 7.0: STPCheckoutInternalUIWebViewController.h:22:1: Property attributes 'nonnull' and 'weak' are mutually exclusive

### ISSUE THREAD

**Issue by robertoferraz** [stripe/stripe-ios#242]
I have just updated to Xcode 7 and I am getting this error:
STPCheckoutInternalUIWebViewController.h:22:1: Property attributes 'nonnull' and 'weak' are mutually exclusive

<img width="1144" alt="screen shot 2015-09-23 at 11 13 54" src="https://cloud.githubusercontent.com/assets/270483/10041382/379a2af4-61e4-11e5-99a7-6296980857d1.png">

**Comment by benzguo** [comment]
This has been fixed in 5.1.4. Let us know if you have any issues after updating!

https://github.com/stripe/stripe-ios/commit/6ff6c4ed25a3901a39d6a0f4d7a98cd506a89711#diff-bbf40050408da8ef199c2d7395897cceR22
