### ISSUE TITLE
Xcode 7 incompatibility 

### ISSUE THREAD

**Issue by drewpitchford** [stripe/stripe-ios#244]
Installing via cocapods, using Xcode 7, there is an error: "/workspace/app-name/Pods/Stripe/Stripe/Checkout/STPCheckoutInternalUIWebViewController.h:22:1: Property attributes 'nonnull' and 'weak' are mutually exclusive"

Please fix this so that cocoa pods installation will work again.

**Comment by jflinter** [comment]
This issue has been fixed as of the latest version of stripe-ios - I suggest updating your `Podfile` to version 5.1.4.
