### ISSUE TITLE
Paymentsheet Crash

### ISSUE THREAD

**Issue by vict1108** [stripe/stripe-ios#2444]
## Summary
IOS App crashing in swiftUI when  confirming payment.

## Code to reproduce
test card - 4000 0025 0000 3155
Close the 3DS web view on left "close" button before proceeding with success and fail

## iOS version
16.3

## Installation method
Swift Package Manager

## SDK version
23.6.0

## Other information
Attaching video

https://user-images.githubusercontent.com/84167727/229819912-13cc5ccc-b443-448b-b308-427bc45b2982.mp4

**Comment by davidme-stripe** [comment]
Hi @vict1108, thanks for filing this. I can't reproduce the issue in our SwiftUI test app — can you share the crash log from the crash you're experiencing?

**Comment by vict1108** [comment]
this results in an invalid NSError instance. It will raise an exception in a future release. Please call errorWithDomain:code:userInfo: or initWithDomain:code:userInfo:. This message shown only once.

**Comment by vict1108** [comment]
> Hi @vict1108, thanks for filing this. I can't reproduce the issue in our SwiftUI test app — can you share the crash log from the crash you're experiencing?

click the close button when weburl loading.
