### ISSUE TITLE
STRIPE_ENABLE_APPLEPAY no longer needed?

### ISSUE THREAD

**Issue by DimaVartanian** [stripe/stripe-ios#245]
We've been using Apple Pay via Stripe for about 8 months now and when I first integrated it we had to set this flag. I see that it is no longer in the documentation and I found the commit that removed the internal checks for this flag but I don't see any reference in the release notes that it is no longer needed. Is it safe to remove this flag now? It'd be good if this was in the release notes if that was the case. Thanks!

**Comment by jflinter** [comment]
Hey @DimaVartanian,
Yes, feel free to remove that flag. Sorry for any confusion you encountered; I'll update the changelog.
