### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by iOSyifeng** [stripe/stripe-ios#2456]
STPCardFormView 怎么隐藏地区和邮编啊

**Comment by seanzhang-stripe** [comment]
Hi @iOSyifeng , I believe you are asking if there is a way to hide the `countryPickerField` and `postalCodeField` from the `STPCardFormView`.  

I'm afraid that there's no options to hide them right now. 

A similar feature request https://github.com/stripe/stripe-ios/issues/1932 was raised and it's recorded in our internal tracker. However, please note that feature development on CardFormView isn't on our immediate roadmap.

**Comment by iOSyifeng** [comment]
有其他的方式可以实现吗 不用 STPCardFormView 其他的vc or view 实现隐藏 countryPickerField 和  postalCodeField

**Comment by iOSyifeng** [comment]
@seanzhang-stripe

**Comment by seanzhang-stripe** [comment]
I'd highly recommend you to use `PaymentSheet`, of which you can disable the billing address collection with `configuration.billingDetailsCollectionConfiguration.address = .never`

You can get started with `PaymentSheet` by following the [integration guide](https://stripe.com/docs/payments/accept-a-payment?platform=ios), or check out our example code [here](https://github.com/stripe/stripe-ios/blob/master/Example/PaymentSheet%20Example/PaymentSheet%20Example/ExampleCheckoutViewController.swift)
