### ISSUE TITLE
Expiration Date Format in Swift

### ISSUE THREAD

**Issue by daisyramos317** [stripe/stripe-ios#246]
I have a custom form for collecting card info. I'd like to have the expiration date in two separate fields for MM and YYYY. I've added the two fields with a forward slash embedded in the middle however when I try to complete a transaction it is returning an invalid card now even if I enter valid credit card numbers, listed here https://stripe.com/docs/testing. I originally had the expiration date set to one field and it was working fine. Did I go wrong somewhere? Thanks in advance

    var stripeCard = STPCard()
        
        if self.expMonth.text.isEmpty && self.expYear.text.isEmpty == false {
        
        let expMonth = UInt(self.expMonth.text.toInt()!)
        let expYear = UInt(self.expYear.text.toInt()!)
            
        //Get Stripe card info token
            
        stripeCard.number = self.creditCardField.text
        stripeCard.cvc = self.securityField.text
        stripeCard.expMonth = expMonth
        stripeCard.expYear = expYear
            
            
        }
        
        var underlyingError: NSError?
        stripeCard.validateCardReturningError(&underlyingError)
        if underlyingError != nil {
            self.handleError(underlyingError!)
            return
        }

**Comment by daisyramos317** [comment]
Closing issue because of semantical error in if statement

**Comment by jflinter** [comment]
Cool, glad you figured things out!
