### ISSUE TITLE
[Feature] Metadata support with Apple Pay

### ISSUE THREAD

**Issue by magouyaware** [stripe/stripe-ios#2468]
## Is your feature request related to a problem? Please describe.
We are writing our own SDK (Olo Pay SDK) built on top of the Stripe SDK for processing payments. At Stripe's recommendation we are using this [legacy documentation](https://web.archive.org/web/20190919134715/https://stripe.com/docs/apple-pay) to write our own Apple Pay implementation.

We need to insert metadata when creating payment methods for tracking various things like what version of our Olo Pay SDK was used to create a payment method.

We are unable to do this because this [createPaymentMethod()](https://github.com/stripe/stripe-ios/blob/3655def04f7494d3132ea841da0405a9e89001c4/StripePayments/StripePayments/Source/API%20Bindings/STPAPIClient%2BApplePay.swift#L57-L77) implementation doesn't take metadata as a parameter.

## Describe the solution you'd like
The easiest solution for our specific problem is to add an optional `metadata` parameter to this version of [createPaymentMethod()](https://github.com/stripe/stripe-ios/blob/3655def04f7494d3132ea841da0405a9e89001c4/StripePayments/StripePayments/Source/API%20Bindings/STPAPIClient%2BApplePay.swift#L57-L77). This would change the existing method to look like this, and amounts to changing only 3 lines of code, which I've marked with comments below:

```
@objc(createPaymentMethodWithPayment:metadata:completion:) // CHANGE: Update obj-c signature
public func createPaymentMethod(
    with payment: PKPayment,
    metadata: [String: String]? = nil, // CHANGE: Add optional metadata parameter in a way that doesn't break existing code
    completion: @escaping STPPaymentMethodCompletionBlock
) {
    createToken(with: payment) { token, error in
        if token?.tokenId == nil || error != nil {
            completion(nil, error ?? NSError.stp_genericConnectionError())
        } else {
            let cardParams = STPPaymentMethodCardParams()
            cardParams.token = token?.tokenId
            let billingDetails = STPAPIClient.billingDetails(from: payment)
            let paymentMethodParams = STPPaymentMethodParams(
                card: cardParams,
                billingDetails: billingDetails,
                metadata: metadata // CHANGE: Set metadata using passed in parameter, instead of nil
            )
            self.createPaymentMethod(with: paymentMethodParams, completion: completion)
        }
    }
}
```

## Describe alternatives you've considered
An alternative change we considered that would also allow us to move forward with adding metadata to our SDK would be to create a new method that creates and returns a `STPPaymentMethodParams` instance: 

```createPaymentMethodParams(with payment: PKPayment, completion: @escaping STPPaymentMethodParamsCompletionBlock)```

This would be a more involved change, would require defining a new completion block type, the method would likely only ever be used by us, and it would require adding and maintaining a lot more tests

## Additional context

This is the last piece of our metadata puzzle to solve... We have found ways to insert metadata into payment methods we create through every other mechanism we use in our SDK because are able to directly use the payment method params object, which allows us to add metadata prior to creating a payment method:
- Credit Card Input Fields: 
    - iOS: [STPPaymentCardTextField.paymentMethodParams](https://github.com/stripe/stripe-ios/blob/master/StripePaymentsUI/StripePaymentsUI/Source/UI%20Components/STPPaymentCardTextField.swift#L413)  
    - iOS: [STPCardFormView.cardParams](https://github.com/stripe/stripe-ios/blob/master/StripePaymentsUI/StripePaymentsUI/Source/UI%20Components/STPCardFormView.swift#L172)
    - Android: [CardInputWidget.paymentMethodCreateParams](https://github.com/stripe/stripe-android/blob/master/payments-core/src/main/java/com/stripe/android/view/CardInputWidget.kt#L208)
    - Android: [CardFormView.cardParams](https://github.com/stripe/stripe-android/blob/master/payments-core/src/main/java/com/stripe/android/view/CardFormView.kt#L117)
- Digital Wallets:
    - Google Pay: Not supported with GooglePayPaymentMethodLauncher, but using this [legacy documentation](https://github.com/stripe/stripe-android/blob/master/payments-core/src/main/java/com/stripe/android/model/PaymentMethodCreateParams.kt#L863-L880) we are able to roll our on Google Pay implementation and get access to the payment method params object and insert our own metadata
    - **_Apple Pay: Unable to add metadata_**

**_If given the approval, we would be more than happy to submit a PR with the changes outlined above._**

**Comment by porter-stripe** [comment]
@magouyaware Thanks for opening this detailed issue! The proposed solution makes sense to me, one minor caveat is modifying the Obj-C signature of `createPaymentMethod ` will break backwards compatibility for Obj-C users. One suggestion is to make the changes listed above plus provide an Obj-C only overload matching the old signature that calls the new modified method with `nil` or empty metadata (`[:]`) to ensure we don't break compatibility with existing Obj-C users.

If you can open a PR with these changes and assign me as the reviewer I'd be happy to take a look!

**Comment by magouyaware** [comment]
@porter-stripe Good callout on the obj-c backwards compatibility... I obviously wasn't thinking about that at all. I will work on getting a PR submitted and assigned to you... It might be a week or more before I can free up some time to work on it and submit it, but it will be coming. Thank you!

**Comment by magouyaware** [comment]
@porter-stripe Do I need to be granted permissions to create a branch and PR, or am I doing something wrong? When I try to push a branch with the changes, I get a permission denied error:

> ERROR: Permission to stripe/stripe-ios.git denied to magouyaware.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by porter-stripe** [comment]
@magouyaware I believe if you fork the repo then push your branch to the fork you should be able to create a pull request from the branch in your fork into our repo.

**Comment by magouyaware** [comment]
@porter-stripe Thanks for that info... I've never actually contributed to an open source project before. I've successfully created the PR, but I'm not able to assign it to you.

Here is the link: https://github.com/stripe/stripe-ios/pull/2518
