### ISSUE TITLE
[Feature] Credit card scanner should scan expiration date and not only "pan"

### ISSUE THREAD

**Issue by alessiolapenna** [stripe/stripe-ios#2484]
## Is your feature request related to a problem? Please describe.
When using the credit card scan without the payment sheet, the resulting object returns only the credit card "pan" and not the expiration date.

## Describe the solution you'd like
Make the expiration date available in the returning data.

## Describe alternatives you've considered
Using a different card scanner library

**Comment by yuki-stripe** [comment]
Hello @alessiolapenna, thanks for writing in!  The card scan feature in PaymentSheet does attempt to read the expiration date, but can fail. I've added improving this to our list of feature requests.

**Comment by jksk** [comment]
Any ETA on this? We're also using CardScanSheet without PaymentSheet.

**Comment by davidme-stripe** [comment]
This was fixed in recent versions of PaymentSheet: The expiration date scanning performance was subpar on newer devices, but it should be working consistently now. Let us know if you notice any other issues.
