### ISSUE TITLE
[Feature] Provide the option to customize the loading state of the text fields (opacity)

### ISSUE THREAD

**Issue by nicklbaert** [stripe/stripe-ios#2485]
## Is your feature request related to a problem? Please describe.
During loading after entering payment information, the input field content changes color (or opacity, not sure) and becomes almost invisible, which does not look very good.

## Describe the solution you'd like
An option to customize the look of the input field text during loading would be awesome!

## Describe alternatives you've considered
-

## Additional context
Screenshot of the state I am talking about:
<img width="567" alt="Screenshot 2023-04-18 at 18 12 30" src="https://user-images.githubusercontent.com/33283708/232839271-358bd09e-1246-43de-8deb-9f5783cf86b1.png">

Thank you guys <3

**Comment by eurias-stripe** [comment]
Hi @nicklbaert, have you made any changes using the appearance API? Looking at this state using the defaults the text is visible while loading:
![Simulator Screen Shot - iPhone 14 Pro - 2023-04-18 at 09 26 30](https://user-images.githubusercontent.com/114543737/232843487-2c9d1706-96f0-4192-8bc5-4d93c5d15edb.png)

**Comment by nicklbaert** [comment]
> Hi @nicklbaert, have you made any changes using the appearance API? Looking at this state using the defaults the text is visible while loading: ![Simulator Screen Shot - iPhone 14 Pro - 2023-04-18 at 09 26 30](https://user-images.githubusercontent.com/114543737/232843487-2c9d1706-96f0-4192-8bc5-4d93c5d15edb.png)

Hi, thanks for the quick reply!

We use these colors:

appearance.colors.background = .white
appearance.colors.primary = UIColor(red: 20/255, green: 20/255, blue: 20/255, alpha: 1)
appearance.colors.textSecondary = UIColor(red: 20/255, green: 20/255, blue: 20/255, alpha: 0.3)
appearance.colors.componentPlaceholderText = UIColor(red: 20/255, green: 20/255, blue: 20/255, alpha: 0.5)
appearance.colors.componentText = UIColor(red: 20/255, green: 20/255, blue: 20/255, alpha: 0.5)
appearance.colors.componentBorder = UIColor(red: 240/255, green: 240/255, blue: 240/255, alpha: 1)
appearance.colors.componentDivider = UIColor(red: 240/255, green: 240/255, blue: 240/255, alpha: 1)
appearance.colors.componentBackground = UIColor(red: 243/255, green: 248/255, blue: 250/247, alpha: 1)

**Comment by eurias-stripe** [comment]
Thanks for the info, I can see that we are hardcoding the color when the field is disabled [here](https://github.com/stripe/stripe-ios/blob/ea0402a0/StripeUICore/StripeUICore/Source/Elements/TextField/TextFieldView.swift#L201).
I'll file this internally as an improvement.

**Comment by eurias-stripe** [comment]
We addressed this by changing the disabled color to use a lower alpha in the disabled state, this should mitigate your issue. We might consider adding a custom option in the future.
Please reopen if this doesn't work for yout.

**Comment by nicklbaert** [comment]
Thank you @eurias-stripe <3
