### ISSUE TITLE
[BUG] PKPaymentAuthorizationControllerDelegate is not convertible to 'pkDidSelectShippingMethodSignature after updating Xcode to 14.2 cannot build the poject

### ISSUE THREAD

**Issue by pranjali420** [stripe/stripe-ios#2488]
## Summary

I have to update my Xcode to 14.2 because now App Store only accepts builds from the latest Xcode version.
After updating it I am getting the below error. I am using Stripe iOS SDK 21.13.0. The reason I am using 21.13.0 because we have an ios target from 12.0.
<img width="1251" alt="Screenshot 2023-04-19 at 11 52 15 AM" src="https://user-images.githubusercontent.com/22310234/232990580-ce2512bf-4fae-4b7c-bad1-3dbbc9c97b93.png">

## Code to reproduce

After updating Xcode to 14.2 and building the project you will get this error

## iOS version

iOS 16

## Installation method

Install using pod install
## SDK version

Xcode version - 14.2
Stripe iOS SDK - 21.13.0
swift - 5

## Other information

Please let me know if there is anything I can do to handle this. This is a high priority for me to resolve. I don't want to update my iOS target.

**Comment by porter-stripe** [comment]
Closing this as the issue appears to be resolved, if you continue to encounter this issue feel free to re-open.
