### ISSUE TITLE
Feature request: Formatted(Kerned) string from CC number string

### ISSUE THREAD

**Issue by DimaVartanian** [stripe/stripe-ios#254]
Any chance of this as a public API?

You are doing this privately in `STPFormTextField`(`- (NSAttributedString *)attributedStringForString:(NSString *)string attributes:(NSDictionary *)attributes`) but it'd be nice to get the functionality in `STPCardValidator`.

**Comment by jflinter** [comment]
Hey there -
We're still playing around with the way this code works internally, which
is why it's all under a private API. Once we settle on something we'll see
what makes sense to open up. In the meantime, it's not a lot of code if
you'd like to just copy/paste it into your app for now.

**Comment by DimaVartanian** [comment]
Hey! Yeah I ended up doing just that for now, thanks :)

**Comment by osrl** [comment]
Hello, any update on this? STPFormTextField is still private. `CardNumberEditText` and  `ExpiryDateEditText` are public and works great on Android. It's a bit disappointing that it's not available on iOS :(
