### ISSUE TITLE
[BUG]  (fatal) module 'StripeCore' not found xCode 14.3

### ISSUE THREAD

**Issue by ricky28chd** [stripe/stripe-ios#2564]
## Summary

When I am building the project in xCode 14.3 it's giving the error **(fatal) module 'StripeCore' not found**

## Code to reproduce

Just add the pods in project and build

## iOS version

16.4

## Installation method

Pods

## SDK version

Stripe 23.8.0

## Other information

No

**Comment by wooj-stripe** [comment]
Hey @ricky28chd -- Sorry for the delay, are you still seeing this issue?  If so, can you please share an example Podfile so that we can try and reproduce it on our end?

**Comment by yuki-stripe** [comment]
Closing this issue as stale.
