### ISSUE TITLE
[BUG] Decoding fails when calling STPCustomerContext.retrieveCustomer

### ISSUE THREAD

**Issue by aomathwift** [stripe/stripe-ios#2582]
## Summary

Decoding fails when calling [`STPCustomerContext.retrieveCustomer`](https://github.com/stripe/stripe-ios/blob/3b556ca05b793f1e1703e790d963941eb1c0e234/Stripe/StripeiOS/Source/STPCustomerContext.swift#L170-L200).

Looking at the implementation, `STPCustomer.updateSources` was executed inside `STPCustomerContext.retrieveCustomer` closure.
Also, it is designed to execute `STPCustomer.sources` in `STPCustomer.updateSources`.
In `STPCustomer.sources`, the response json when executing [`/v1/customer/:id`](https://stripe.com/docs/api/customers/retrieve) API is decoded as a dictionary.

However, during this decoding, we are accessing a key of `sources` that does not exist in the response of this API, so we cannot get some properties such as [`defaultSource`](https://stripe.dev/stripe-ios/stripe/documentation/stripe/stpcustomer/defaultsource) that should be available.

## Code to reproduce

```swift
STPCustomerContext(keyProvider: EphemeralKeyProvider()).retrieveCustomer { customer, error in
    guard let customer else { return }
    customer.defaultSource // nil
}
```

## iOS version

16.1

## Installation method

cocoapods 1.12.1

## SDK version

23.7.0

## Other information

`source` is now deprecated, but our project is currently not ready for migration. So I want this method to work properly as well.

**Comment by yuki-stripe** [comment]
Hello @aomathwift,

Like you've found, the `sources` field is no longer included by default on the Customer API object https://stripe.com/docs/api/customers/object#customer_object-sources.  We don't have plans to support `sources` anymore, unfortunately.  Based on the link above, the API will still include the `sources` field if you pass an `"expand": "sources"` parameter.

You could try forking our code to include this change.

```
diff --git a/Stripe/StripeiOS/Source/STPAPIClient+BasicUI.swift b/Stripe/StripeiOS/Source/STPAPIClient+BasicUI.swift
index 00e7889660..466e3e642b 100644
--- a/Stripe/StripeiOS/Source/STPAPIClient+BasicUI.swift
+++ b/Stripe/StripeiOS/Source/STPAPIClient+BasicUI.swift
@@ -144,7 +144,7 @@ extension STPAPIClient {
             self,
             endpoint: endpoint,
             additionalHeaders: authorizationHeader(using: ephemeralKey),
-            parameters: [:]
+            parameters: ["expand":"sources"]
         ) { object, _, error in
             completion(object, error)
         }
```

**Comment by aomathwift** [comment]
@yuki-stripe 

Thanks for letting me know the solution.
If I submit this proposed change as a PullRequest, can you merge it into master?
Or does it mean that you won't be releasing anymore changes for `sources`?

**Comment by yuki-stripe** [comment]
@aomathwift - The latter - we won't be making changes to support sources, unfortunately.

**Comment by aomathwift** [comment]
Thanks for your answer, Yuki. 
I will also consider responding to PaymentIntent, which is the recommended method.
