### ISSUE TITLE
[Feature] A way to cancel a subscription and even  and option to ask for a refund

### ISSUE THREAD

**Issue by jesus-mg-ios** [stripe/stripe-ios#2592]
## Is your feature request related to a problem? Please describe.
I was looking for a way to cancel a subscription from the sdk, but I didn't find it. The same to ask for a refund.

## Describe the solution you'd like
A clearly way to do it from the SDK api

## Describe alternatives you've considered
No one

## Additional context
If you can choose what products you want to cancel or ask for a refund would be nice.

**Comment by eurias-stripe** [comment]
Hi @jesus-mg-ios, we do not have these options on the SDK right now, but we are actively looking into subscriptions related improvements that we hope to include in the near future, we will take your feedback into account.
