### ISSUE TITLE
Stripe checkout Button shows incorrect amount (multiple of 100) on PKR currency.

### ISSUE THREAD

**Issue by hammadofficial** [stripe/stripe-ios#2601]
**Describe the bug**
Stripe checkout Button shows incorrect amount (multiple of 100) on PKR currency.

**To Reproduce**
1. Create a payment intent with currency set as 'pkr' (Pakistani Rupee)
2. Let's say the amount passed from the front end is PKR 1000.
3. On the backend, we are supposed to multiply the amount by 100 following the zero-decimal rule in Stripe.
4. when the intent API returns and the Stripe pop-up opens, it shows the amount as PKR 100000 instead of the original PKR 1000.
5. After doing the checkout, on stripe dashboard, the correct amount is shown which is PKR 1000

**Expected behavior**
The Stripe payments button should say "Pay PKR 1000" and NOT "Pay PKR 100000"

**Screenshots**
![WhatsApp Image 2023-05-21 at 2 31 06 PM](https://github.com/stripe/stripe-react-native/assets/129503907/25ff70d9-f2cd-4189-a871-a233e8114d52)

**Smartphone (please complete the following information):**
 - iOS
 - Version 16.2

**Comment by eurias-stripe** [comment]
Thanks for reporting this, this happens because officially PKR has two decimal places but in practice it has no decimals, so our API uses the official decimal number but some formatters, like swift's `NumberFormatter`, use zero.
I have fixed this and it will be available in the next release.

**Comment by porter-stripe** [comment]
Closing as this is fixed!
