### ISSUE TITLE
Examples on how to use checkout in iOS webview?

### ISSUE THREAD

**Issue by kkgelu** [stripe/stripe-ios#262]
So basically I would like to have this:   https://github.com/stripe/stripe-ios/issues/117

We would like to use the out-of-box checkout forms advertised on stripe.com without building our own form. I believe that it uses the webview instead of the native UIs.

It looks that the examples in the this repository don't use WebView but native UIs. Maybe I missed out the documentations, I did find this https://github.com/stripe/stripe-ios/tree/master/Stripe/Checkout but I don't know how to use them to get these beautiful/fullscreen checkout forms.

I tried to load html with checkout.js in webview, the result is bitter:

![simulator screen shot 24 oct 2015 22 34 56](https://cloud.githubusercontent.com/assets/11604017/10712626/99921040-7a9f-11e5-9e3f-15d1f7d5b039.png)

 I would like to have this: https://cloud.githubusercontent.com/assets/1910721/6383749/f6f078e2-bd4b-11e4-9f80-f02b785d867a.PNG instead

I think I might be misunderstanding some basics here, please help on how to achieve this! Thanks! @jflinter

**Comment by mbrochh** [comment]
Any update on this? I would like this as well. Stripe should either provide a native SDK that looks as nice as the Checkout.js mobile styles, or make it possible to use Checkout.js in a mobile webview.

**Comment by jflinter** [comment]
Unfortunately, Checkout on the web requires the payment sheet to be opened in a separate tab. As this isn't possible in a web view, we render a fallback experience that isn't as good-looking.

We're aware of the deficiency here, and are looking into ways to make this better. In the meantime, though it'll obviously require building a lot more of your own UI, I'd recommend having a look at `STPPaymentCardTextField`.
