### ISSUE TITLE
Any chance to have Card Icons in public API?

### ISSUE THREAD

**Issue by garnett** [stripe/stripe-ios#263]
I'm using `STPPaymentCardTextField` which is really handy, but now I have 2 sets of card icons in my app. Do you think is it worth to expose them?

**Comment by jflinter** [comment]
Hey there! That makes a lot of sense; we'll open up an API for them in a future release. In the meantime, you should be able to load them as follows:
```objc
[UIImage imageNamed:imageName inBundle:[NSBundle bundleForClass:[STPAPIClient class]] compatibleWithTraitCollection:nil];
```
where `imageName` is one of `stp_card_amex`, `stp_card_diners`, `stp_card_jcb`, `stp_card_mastercard`, `stp_card_visa`.

**Comment by bradfol** [comment]
@garnett I have submitted #284 to expose class methods that will return `UIImage`s for each `STPCardBrand`.

**Comment by jflinter** [comment]
Hey @garnett, we've added some additional helper methods in the 6.1.0 release - hope this gives you what you're looking for. Cheers!
