### ISSUE TITLE
[Feature] Product Modes

### ISSUE THREAD

**Issue by jesus-mg-ios** [stripe/stripe-ios#2638]
## Is your feature request related to a problem? Please describe.
We're facing a case where we want to keep the same product but change the subscription frequency. So, if we have a recurrent subscription, with a weekly period, maybe we want to extend it to a biweekly period for a time and then back to the weekly period.

## Describe the solution you'd like
Add a mode to the product to change the subscription period.

## Describe alternatives you've considered
No one.

## Additional context
If there's another way to do it, please provide me a hint.

**Comment by yuki-stripe** [comment]
Hello @jesus-mg-ios, sorry this never got replied to! If you'd still like help with this please reach out to support@stripe.com or our [discord channel](https://stripe.com/go/developer-chat). cc @shengwei-stripe
