### ISSUE TITLE
Option to enter postal code in STPPaymentCardTextField 

### ISSUE THREAD

**Issue by garnett** [stripe/stripe-ios#264]
Postal code might be needed to enter if you opt in in "Decline charges that fail postal code verification"

**Comment by cuilongzhe** [comment]
Hello, Stripe.

You guys clearly mentioned here that we have an option to put zip code.
https://stripe.com/docs/mobile/ios
But I can't see any snippet of code which shows zip code.

Could you let me know when zip code field will be embedded in STPPaymentCardTextField?
Or do I have to create another field for zip code?

Thanks!

**Comment by jflinter** [comment]
Hey there - we don't currently have anything in the way of a zip code text field, although you're obviously welcome to just use a `UITextField` for this. I've updated our documentation to reflect this.

**Comment by cowgp** [comment]
+1 for adding this as a feature request to STPPaymentCardTextField

**Comment by qazimusab** [comment]
is there still no option for zipcode?

**Comment by bdorfman-stripe** [comment]
Hi @qazimusab,

Thanks for your interest. Adding the option for a single line form that includes a zip code is on our near-term development roadmap. We hope to have it shipped soon. Thanks for your patience!

Brian

**Comment by qazimusab** [comment]
@bdorfman-stripe Would you be kind enough to give me a sense on when "near-term" is so that I can know when to look for it? Thanks!

**Comment by bdorfman-stripe** [comment]
I would advise you to either watch this repository, or subscribe to the rss feed[0] of new official releases to get notified when features are added

[0] [https://github.com/stripe/stripe-ios/releases.atom](https://github.com/stripe/stripe-ios/releases.atom)
