### ISSUE TITLE
STPPaymentCardTextField cursor color

### ISSUE THREAD

**Issue by iwasrobbed** [stripe/stripe-ios#265]
Feature request to expose a color property so we can show the text field cursor. You can set the `tintColor` for now and expose it that way, but figured you have 3 private text fields so didn't want to break anything. Feel free to close this issue if you'd rather people just use tint to do this

**Comment by jflinter** [comment]
Hey @iwasrobbed! Thanks for bringing this up - I've just added a `cursorColor` property to `STPPaymentCardTextField`. It just uses `tintColor` under the hood but given that less-than-well-documented behavior I like the idea of exposing it directly.

**Comment by iwasrobbed** [comment]
Thanks Jack!
