### ISSUE TITLE
[BUG] Failing build using Tuist • Carthage • Xcode 15

### ISSUE THREAD

**Issue by stherold** [stripe/stripe-ios#2650]
## Summary
I am unable to build the workspace with Tuist • Carthage • Xcode 15

## iOS version
We support iOS 14+ as deployment target

## Installation method
Install using Tuist and we use Carthage as dependency manager.

## SDK version
23.6.1

## Demo Project

[DependencyChecker-main.zip](https://github.com/stripe/stripe-ios/files/11744272/DependencyChecker-main.zip)

Just run `./build.sh` in the root of the demo project 👍

**Comment by porter-stripe** [comment]
@stherold could you provide some specific details about the error you are seeing along with some steps to reproduce the issue?

Thanks!

**Comment by stherold** [comment]
Glad you asked and yes I attached a simple demo project that demonstrates the issue. Hope that helps 👍

**Comment by stherold** [comment]
@porter-stripe can you confirm the issue with the Demo project?

**Comment by stherold** [comment]
It continues to fail with Xcode 15 Beta 2

**Comment by porter-stripe** [comment]
Hi @stherold you can find updates regarding Xcode 15 here: https://github.com/stripe/stripe-ios/issues/2673

**Comment by davidme-stripe** [comment]
Xcode 15 should work in the `master` branch now. We'll cut a release with the fixes in the next week or two.

**Comment by stherold** [comment]
I think this can be closed too. Thx for the quick replies 👍
