### ISSUE TITLE
[BUG] AddressViewController.Configuration. defaultValues： When the default address is set, the search button on the right side of the line1 textField is invalid, and can only be used after the country is changed.

### ISSUE THREAD

**Issue by Balopy** [stripe/stripe-ios#2658]
var addressConfiguration: AddressViewController.Configuration {
        var configuration = AddressViewController.Configuration(additionalFields: .init(phone: .optional), appearance: configuration.appearance)
        configuration.defaultValues = .init(
            address: .init(
                city: "San Francisco",
                country: "US",
                line1: "510 Townsend St.",
                postalCode: "94102",
                state: "California"
            ),
            name: "Jane Doe",
            phone: "5555555555"
        )
        configuration.allowedCountries = ["US", "CA"]
        configuration.additionalFields.checkboxLabel = "Save this address for future orders"
        return configuration
    }

    self.addressViewController = AddressViewController(configuration: self.addressConfiguration, delegate: self)
    present(UINavigationController(rootViewController: addressViewController!), animated: true)

![20230615-094143](https://github.com/stripe/stripe-ios/assets/35068028/5442b145-157a-4653-8301-ab13c150109f)

Bug：When the default address is set, the search button on the right side of the line1 textField is invalid, and can only be used after the country is changed.

**Comment by porter-stripe** [comment]
Thanks for reporting this @Balopy! I have a PR open with the fix and will update this issue when it is released. https://github.com/stripe/stripe-ios/pull/2656

**Comment by porter-stripe** [comment]
This is now resolved in [23.9.2](https://github.com/stripe/stripe-ios/releases/tag/23.9.2).
