### ISSUE TITLE
Support Checking current active form field type.

### ISSUE THREAD

**Issue by pocket7878** [stripe/stripe-ios#266]
Hi!

I want to use STPPaymentCardTextField becase I loved default form design.
But I also need updating outside UI when active form field changed (showing information about where CVC may found..etc)
I want to send PR to support it, but I have not come up to a good design.

Is there any way to do it or I should create custom field?

**Comment by jflinter** [comment]
Hey there,
This functionality isn't currently supported, although we'll look into making this easier in the future. Out of curiosity, what is the specific functionality you need this for? (`STPPaymentCardTextField` actually already changes the icon to show an indicator of where CVCs can be found when the CVC field is selected, if that's helpful to you).

**Comment by pocket7878** [comment]
Hmm... Thank you for your comment.
I need to update UI (outside of STPPaymentCardTextField) when active form field changed.
Ok, I'll create card form by myself.
