### ISSUE TITLE
[BUG] PNG 8 bit warnings

### ISSUE THREAD

**Issue by luispadron** [stripe/stripe-ios#2667]
## Summary

When building with Bazel we are seeing this warning:

```
From CopyPng Pods/Stripe/Stripe-intermediates/stp_icon_add@3x.png:
libpng warning: Warning: Input PNG does not have an 8 bit input depth.  Please convert your PNG to 8-bit for optimal performance on iPhone OS.
```

## iOS version

Min: iOS 14.0

## Installation method

Consumed via the CocoaPods podspec.

## SDK version

23.6.0

## Other information

Seems like the same as this previously resolved issue: https://github.com/stripe/stripe-ios/issues/278

**Comment by porter-stripe** [comment]
Hi @luispadron thanks for reporting this, I will log this internally and we will look into this!

**Comment by luispadron** [comment]
Thanks for fixing!
