### ISSUE TITLE
Issue with Swype keyboard

### ISSUE THREAD

**Issue by cuilongzhe** [stripe/stripe-ios#267]
@jflinter 

I have a trouble with STPPaymentCardTextField + Swype keyboard.
https://itunes.apple.com/us/app/swype/id916365675?mt=8

Here is bug:
I type 11 with swype keyboard enabled.
Swype keyboard sucks here, I have to switch keyboard to numberpad everytime I type a digit because it changes back to character board automatically.
Ok, so good so far.
When I click switch button to switch to number pad, the text I typed so far("") is cleared now and I can't type 11 anymore, and this problem persists all the time.

I've debugged this a bit and realised that a absurd text "qq" is sent to UITextfield(base class of STPFormTextField).
And then STPFormTextField clears up whole text in shouldChangeCharactersInRange delegate function of TextField.
To be clear, "qq" is hint text suggested by swype keyboard.

So, would you say this is totally Swype keyboard?
Is there anyway to avoid this?
I would say this issue does not happen in any other area of my iphone, so I hope this can be resolved from Stripe SDK.

Thanks.

**Comment by jflinter** [comment]
I think we want to just disable third-party keyboards entirely for `STPPaymentCardTextField`s. We'll look into what we can do on our end, but you can work around this for now by disabling third-party keyboards in your app as outlined here: http://stackoverflow.com/a/25884045/1337116
