### ISSUE TITLE
[Feature] Support GrabPay option when using automatic payment methods

### ISSUE THREAD

**Issue by danielleng** [stripe/stripe-ios#2672]
## Is your feature request related to a problem? Please describe.
The iOS SDK does not support showing GrabPay as a payment method in the paymentSheet. Developers would have to implement the flow manually as per: https://stripe.com/docs/payments/grabpay/accept-a-payment?platform=mobile&ui=ios     
I feel that having GrabPay needing to be implemented in a separate flow takes away the ease of use of the paymentSheet.

## Describe the solution you'd like
Support displaying GrabPay in the list of payment methods in the paymentSheet when using automatic_payment_methods: "true"

## Describe alternatives you've considered
N/A

## Additional context
GrabPay is widely used in Southeast Asia (especially Malaysia and Singapore). As the documentation itself says, its a "common payment method": https://stripe.com/docs/payments/grabpay
It would be great to have this option in the paymentSheet.

**Comment by yuki-stripe** [comment]
@danielleng Thank you for writing in.  I've tracked this request internally and very much agree that we should support this in PaymentSheet!

**Comment by seanzhang-stripe** [comment]
Hi @danielleng Just want to let you know that GrabPay support in PaymentSheet is added in SDK version [23.14.0](https://github.com/stripe/stripe-ios/blob/master/CHANGELOG.md#23140-2023-08-21). Give it a try and share your feedback with us!
