### ISSUE TITLE
[BUG] Failing to build on Xcode 15 beta + Swift 6

### ISSUE THREAD

**Issue by shkhaliq** [stripe/stripe-ios#2673]
## Summary
Running into an error: 

```
/Users/username/repos/my-project/Carthage/Checkouts/stripe-ios/StripePayments/StripePayments/Source/Internal/API Bindings/APIRequest.swift:129:30: error: generic parameter 'ResponseType' shadows generic parameter from outer scope with the same name; this is an error in Swift 6
    class func parseResponse<ResponseType: STPAPIResponseDecodable>(
```

## Code to reproduce
Just run the project with Xcode 15 beta and you should run into this

## SDK version
23.6.1

## Other information
This is happening while building with carthage

**Comment by yuki-stripe** [comment]
Hi @shkhaliq, we're working on an experimental branch that can compile on Xcode 15 beta - will update this issue when it's ready.

**Comment by shkhaliq** [comment]
Thank you @lyuxie-stripe

**Comment by yuki-stripe** [comment]
This branch should compile and work, but may have broken behavior and shouldn't be used in production: https://github.com/stripe/stripe-ios/tree/experimental/xcode-15-beta. 

In particular, there's a [bug](https://developer.apple.com/forums/thread/731374) with how Objective C bridging headers are being generated that meant we had to comment out some overriden `hash` methods and causes our tests to not compile. Expect more updates to come.

**Comment by Blackjacx** [comment]
When I compile this using the beanch `experimental/xcode-15-beta` I get the error

```
Dependency "stripe-ios" has no shared framework schemes for any of the platforms: iOS
```

**Comment by shkhaliq** [comment]
> When I compile this using the branch `experimental/xcode-15-beta` I get the error
> 
> ```
> Dependency "stripe-ios" has no shared framework schemes for any of the platforms: iOS
> ```

same here @lyuxie-stripe

**Comment by Blackjacx** [comment]
I think it looks better in terms of bilding the framework, but now I get the following error:
```
*** Skipped building stripe-ios due to the error:
Dependency "stripe-ios" has no shared framework schemes for any of the platforms: iOS
```

I think it is just a forgotten checkmark to share the scheme. Maybe Apple changed how this works 🤔

**Comment by davidme-stripe** [comment]
Xcode 15 should work in the `master` branch now. We'll cut a release with the fixes in the next week or two.

The Carthage `no shared framework schemes` error is because we use Tuist instead of committing our `.xcodeproj` files in the repo. Once we release version 23.13.0 on Monday, you'll be able to point Carthage at that version for Xcode 15 support.

**Comment by davidme-stripe** [comment]
Sorry for the ambiguity, we released it today: https://github.com/stripe/stripe-ios/releases/tag/23.13.0

**Comment by stherold** [comment]
Can confirm it works 👍

**Comment by Blackjacx** [comment]
Can confirm it works 👍
