### ISSUE TITLE
[BUG] PaymentSheet dismisses keyboard when auto-changing text fields

### ISSUE THREAD

**Issue by JRHonda** [stripe/stripe-ios#2681]
### Using PaymentSheet in 100% SwiftUI project. Manually tapping on a text field works as expected.

https://github.com/stripe/stripe-ios/assets/29804812/6740b4ad-3cec-4089-b5ed-af69666647cb

**Comment by wooj-stripe** [comment]
Hi @JRHonda -- Thanks for reaching out.

I'd like to take a look at reproducing this issue. Do you have an example app available that I can take a look at?

**Comment by JRHonda** [comment]
> Hi @JRHonda -- Thanks for reaching out.
> 
> 
> 
> I'd like to take a look at reproducing this issue. Do you have an example app available that I can take a look at?

Hi there. Yeah!

https://apps.apple.com/us/app/fanatics-live-break-your-way/id6450561371

**Comment by wooj-stripe** [comment]
Sorry for the confusion. I was referring to an example app with available code that I could use to reproduce the issue.

**Comment by jensonjohn001** [comment]
Same issue facing

iPhone 12 mini (iOS 17)

https://github.com/stripe/stripe-ios/assets/35399770/a6603b91-bdf9-44dd-b453-f8b90b614763

**Comment by yuki-stripe** [comment]
@JRHonda @jensonjohn001 I can't repro this. Could you try updating to the latest version?  [v23.0.0](https://github.com/stripe/stripe-ios/releases/tag/23.0.0) contains a related bugfix:
> [Fixed] Fixed a visual bug in iOS 16 where advancing between text fields would momentarily dismiss the keyboard.

**Comment by yuki-stripe** [comment]
Please re-open if you're still running into problems!
