### ISSUE TITLE
Stripe pod installing went wrong

### ISSUE THREAD

**Issue by malbaq** [stripe/stripe-ios#269]
I'm developing iOS App with Swift. I'm going to implement Stripe with Parse as backend. After I installed the Stripe pod I've got a dozen errors that all barely make sense for me.

Pls help!

![screen shot 2015-11-15 at 7 54 36 pm](https://cloud.githubusercontent.com/assets/2308235/11169792/d5eb9f90-8bd2-11e5-9d49-5db835aecd45.png)

**Comment by NasirMalik** [comment]
I am also facing same issue. Please tell what is wrong with this file STPAPIPostRequest. I am also using parse. I assume its an issue in edit that was lastly made on 10/14/15. Previously it was working fine. 

![screen shot 2015-11-16 at 11 23 07 am](https://cloud.githubusercontent.com/assets/3906649/11175495/acb0e9b4-8c54-11e5-8118-85fbe7e506c8.png)

**Comment by jflinter** [comment]
This sounds like one of two issues to me:
- There's some kind of Cocoapods caching issue at play. Try removing your `Pods` directory and re-running `pod install`.
- You're not on the latest Xcode - make sure you're using at least Xcode 7.1 to build and run your app.
