### ISSUE TITLE
[BUG] no stripe-ios/Stripe.xcworkspace found - even in Example area

### ISSUE THREAD

**Issue by ormaa** [stripe/stripe-ios#2695]
## Summary

no Stripe.xcworkspace found - even in Example area
note : some readme reference it

then :  I found no way to build and test the sample app, which could help me to progress in the integration of Stripe in my App.
some readme are 
I cloned de repo, targeted the latest master commit

**Comment by tillh-stripe** [comment]
Hi @ormaa 👋 The `Stripe.xcworkspace` file will be generated when you run `tuist generate` (see [here](https://github.com/stripe/stripe-ios#building-from-source)). Can you give that a try?

**Comment by ormaa** [comment]
Hello. I juste tested your solution, and it works well.
Thanks for the tips.

**Comment by tillh-stripe** [comment]
Glad it works now! Let us know if you’re running into any other issues.
