### ISSUE TITLE
validationStateForCVC: "123" marked as valid for Amex

### ISSUE THREAD

**Issue by andresgarza** [stripe/stripe-ios#273]
Despite the documentation saying that `validationStateForCVC` should return `"STPCardValidationStateIncomplete for @"123" and STPCardBrandAmericanExpress"` it returns a valid state

```
STPCardValidator.validationStateForCVC("123", cardBrand: STPCardBrand.Amex) //-> .Valid
```

**Comment by jflinter** [comment]
Ah yes, we recently changed that because amex sometimes actually does issue 3-digit CVCs. I've updated the documentation to reflect this change. Thanks!
