### ISSUE TITLE
STPCheckoutViewController is deprecated

### ISSUE THREAD

**Issue by pingzh** [stripe/stripe-ios#274]
Hi, 

There is a warning about STPCheckoutViewController which says it is deprecated. Can I still use it? Or is there a better alternative?

Thanks.

**Comment by jflinter** [comment]
Hey there,
As the deprecation warnings suggest, you shouldn't use it - I'd suggest taking a look at `STPPaymentCardTextField` instead.

**Comment by pingzh** [comment]
Thanks for response, can user save their credit card information if I use STPPaymentCardTextField?

**Comment by jflinter** [comment]
STPPaymentCardTextField doesn't support this out of the box, but you can
save your user's payment details as a customer on your backend - see
https://stripe.com/docs/tutorials/charges#saving-credit-card-details-for-later
for more info.

**Comment by pingzh** [comment]
I really love the feature that `STPCheckoutViewController` provides. So now I will need to save the credit card infomation in my backend.
Thanks for your answer.
