### ISSUE TITLE
Stripe test mode, why is token appended with (test mode)?

### ISSUE THREAD

**Issue by pingzh** [stripe/stripe-ios#277]
I got an issue when I tried to use Stripe-iOS test mode, the token returned was always appended with (test mode), which made the token invalid and payment fail.

Could you help me take a look?
Thanks.
```
{
   amount: "2130"
   currency: "usd"
   card: "tok_17EXIpD3Ob7SDhCAue2GmK3P (test mode)"
}
```

**Comment by davidrothera** [comment]
Could you provide some more example code on how you are getting the token

**Comment by jflinter** [comment]
I suspect this is because you're using the token's `description` property (or formatting it into an `NSString`) instead of its `tokenID` property. Nonetheless, this is definitely confusing behavior on our end - I've fixed this in https://github.com/stripe/stripe-ios/pull/279.
