### ISSUE TITLE
Fetch list of banks for iDeal

### ISSUE THREAD

**Issue by daliad007** [stripe/stripe-ios#2771]
Hello,

Our website uses Payment Elements to get the optimised list of banks for iDeal payment method.

```
const elements = this.stripeService.StripeConnect.elements({
      locale: this.locale
    });

    this.idealElement = elements.create('idealBank', {
      value: 'abn_amro',
      style: {
        base: {
          color: '#262626',
          fontSize: '16px',
          lineHeight: '24px',
          padding: '8px'
        }
      },
      classes: {
        base: 'form-control ideal',
        empty: 'StripeElementIdeal--empty',
        invalid: 'StripeElementIdeal--invalid'
      }
    });
```

Is there a similar way to achieve this on iOS to get the most up-to-date list of banks? At the moment we fetch the list of banks from a remote config, but we'd like to align with web if possible.

Thanks

**Comment by seanzhang-stripe** [comment]
Hi @daliad007 , there's no iOS equivalent of `idealBank` element in Stripe iOS SDK. You need to use your own UI to collect the payment information, and create `STPPaymentMethodiDEALParams` and `STPPaymentMethodBillingDetails` respectively (More details in this [doc](https://stripe.com/docs/payments/ideal/accept-a-payment?platform=mobile&ui=ios#ios-collect-payment-method-details)). 

You can also refer to the [Bank reference](https://stripe.com/docs/payments/ideal/accept-a-payment?platform=mobile&ui=ios#bank-reference) for the list of bank names.

**Comment by daliad007** [comment]
Thank you for your reply @seanzhang-stripe

**Comment by sasa-andjelic-nqode** [comment]
Hello,

Can anyone shed some light as to where to acquire the list of all banks supported by ideal?

**Comment by seanzhang-stripe** [comment]
Hi @sasa-andjelic-nqode Yes the link is changed. This is the [update URL ](https://docs.stripe.com/payments/ideal/accept-a-payment?web-or-mobile=mobile&payments-ui-type=ios#bank-reference) for the bank reference.

**Comment by sasa-andjelic-nqode** [comment]
@seanzhang-stripe Thank you very much!
