### ISSUE TITLE
STPPaymentCardTextField IBInspectable

### ISSUE THREAD

**Issue by bradfol** [stripe/stripe-ios#281]
I see that the properties on `STPPaymentCardTextField` are marked with `IBInspectable` (e.g. [`borderColor`](https://github.com/stripe/stripe-ios/blob/master/Stripe/PublicHeaders/UI/STPPaymentCardTextField.h#L88)). However, I am not seeing those properties appear in interface builder. Using Stripe 6.0.1 and Xcode 7.1.1.

**Comment by jflinter** [comment]
Hey, thanks @bradfol - this appears to have stopped working in Xcode 7. We'll take a look at this soon; in the meantime I've removed those `IBInspectable` annotations.
