### ISSUE TITLE
[BUG] No content when opening Stripe.xcworkspace

### ISSUE THREAD

**Issue by ramunasjurgilas** [stripe/stripe-ios#2820]
## Summary
Can not execute PaymentSheets Example project. The reason is, that Xcode screen is blank after opening Stripe.xcworkspace.

Fallowed this documentation: https://github.com/stripe/stripe-ios/tree/master/Example/PaymentSheet%20Example

<img width="963" alt="image" src="https://github.com/stripe/stripe-ios/assets/255732/f63b3742-ad26-4929-a24e-7d0b1e1c8a95">

## Code to reproduce
Just download source code as ZIP and open Stripe.xcworkspace.

## iOS version
Xcode: Version 14.3.1 (14E300c)

## Installation method
Downloaded source code from repository as zip archive.

**Comment by seanzhang-stripe** [comment]
Hi @ramunasjurgilas you should run `tuist generate` to generate Xcode related files, and open the generated workspace file. See [these instructions](https://github.com/stripe/stripe-ios#building-from-source) fore more details

**Comment by ramunasjurgilas** [comment]
Thanks @seanzhang-stripe
