### ISSUE TITLE
STPPaymentCardTextField is not always allowing users to add cvc and expiration code

### ISSUE THREAD

**Issue by santiagoprieto** [stripe/stripe-ios#283]
I'm having issues with STPPaymentCardTextField. It might be something I'm doing wrong, but some of my users cant add cvc and expiration code. Right after they complete adding the cardNumber, it just resigns responders or doesn't show the next view or the animation is not being triggered. 

I've tried a bunch of stuff, not able to figure this out.
Would other textField functions in my view interfere with STPPaymentCardTextField?

Any help or solution would be great.

The code is exactly as per the https://stripe.com/docs/mobile/ios#prebuilt "Using STPPaymentCardTextField" section, only in swift2: 

    override func viewDidLoad() {
        super.viewDidLoad()

        stripeCardView.delegate = self
        stripeCardView.frame = CGRectMake(0, 0, CGRectGetWidth(self.view.frame), 44)
        stripeCardView.borderWidth = 0
        view.addSubview(stripeCardView)
}

**Comment by santiagoprieto** [comment]
Ok, I just figured it out. If you have other textFields and programmatically add delegates to them based on tags, it will mess up STPPaymentCardTextField.

func addDelegates() {
         for i in 1...6 {
            if let textField = self.view.viewWithTag(i) as? UITextField {
                textField.delegate = self
            }
        }
}

**Comment by jflinter** [comment]
Yes, `STPPaymentCardTextField` contains several internal `UITextField`s, and changing their `delegate` will cause undefined behavior like this.

**Comment by irskep** [comment]
I'm actually seeing this same behavior on iOS 10 on iPad. Still trying to figure out exactly what's going on. We aren't doing anything weird with delegates. I'll try to update when I have more info, but for now I'll just say this is still happening to someone.

**Comment by bdorfman** [comment]
Hi @irskep. If you are having issues with STPPaymentCardTextField on the latest sdk, please open a new issue with all the details you can provide and we'll take a look at it as soon as we can. Thanks!
