### ISSUE TITLE
Problem with STPPaymentCardTextField error text color carrying over to other textfield

### ISSUE THREAD

**Issue by zachlucas** [stripe/stripe-ios#285]
I'm using an STPPaymentCardTextField to input card information.  I also have other text fields in the same view.  When I enter an invalid card number, the card number correctly turns red in the STP field.  However, when I do that and then I become first responder to a different text field, that text field's text inexplicably turns red.  Has anyone observed this?

**Comment by jflinter** [comment]
This sounds like it's unlikely to be the fault of `STPPaymentCardTextField`. You can see what is calling `setColor:` on your other textfield by changing it to a custom subclass of `UITextField`, then overriding `setColor:` on that subclass and inserting a breakpoint in the method.
