### ISSUE TITLE
[Feature] BECS Debit card support for Setup Intent in Payment Sheet

### ISSUE THREAD

**Issue by vinny821** [stripe/stripe-ios#2887]
## Is your feature request related to a problem? Please describe.
We are supporting multiple payment methods using the payment sheet. The current solution provide by Stripe ask for creating  STPAUBECSDebitFormView but we need it via paymentsheet

## Describe the solution you'd like
Addition of BECS debit card support to paymentsheet for setup intent like we have for payment intent

**Comment by yuki-stripe** [comment]
Thanks for writing in @vinny821 , we plan to add support for this in the few weeks.

**Comment by porter-stripe** [comment]
Closing this as the latest version supports BECS with SetupIntents!
