### ISSUE TITLE
[BUG] Keyboard inaccessible on clicking "Postal Code"/"Zip Code" input when UK is selected in "country" input

### ISSUE THREAD

**Issue by drakedeatonuk** [stripe/stripe-ios#2936]
## Summary

When selecting a country from the country selection picker, if I click directly onto the "Postal Code"/"Zip Code" input beneath of this, then the keyboard closes and it wont reopen until I change back to the previous input and reselect the "Postal Code"/"Zip Code" input again (this is demoed in a video below).

Note this does not happen if the country is set to the USA, but will happen if it's set to the UK... So I believe there may be some confusion happening with the keypad (which can be shown for the US), and the keyboard (which needs to be shown for the UK).

Please see this video for a demonstration: https://github.com/stripe/stripe-ios/assets/41165256/77429fba-77f5-4388-b655-8eb33e319d90

To reproduce exactly what this video shows:
1. Select the country as United Kingdom
2.  Click the "Postal Code"/"Zip Code" input
See error: you'll see that the keyboard closes and wont open again until you click on another input and re-click on the "Postal Code"/"Zip Code" input

I would expect that the keyboard should be open when the user clicks directly on this input after setting a country.

## Code to reproduce
https://github.com/capacitor-community/stripe/assets/41165256/d34218bb-c00d-4d87-a9dd-8666871209fb

## iOS version
Latest

## Installation method
via the capacitor-community/stripe library... I first reported this issue on that repo, which can be seen here: https://github.com/capacitor-community/stripe/issues/297

## SDK version
23.4.0

**Comment by porter-stripe** [comment]
@drakedeatonuk thanks for reporting this, a fix will be included in the next release!

**Comment by drakedeatonuk** [comment]
Thank you sir! That's great news 🙏 very much appreciated 😊

**Comment by porter-stripe** [comment]
Fixed in the latest release!
