### ISSUE TITLE
PKPaymentAuthorizationController init is not nullable

### ISSUE THREAD

**Issue by Frizlab** [stripe/stripe-ios#2937]
Context: https://github.com/stripe/stripe-ios/blob/04cd715b6fe232126bff29ee2fb2b9ed8c66f246/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPApplePayContext.swift#L114-L115

In this code, the authorization controller is instantiated, then there’s a check to verify the instantiation was successful. But it cannot _not_ be as the init is (surprisingly) not nullable.

This is probably an oversight on Apple’s part as the UI equivalent `PKPaymentAuthorizationViewController` does have a nullable init. Indeed, the payment request can be invalid and the `PKPaymentAuthorizationController` we get is unusable when that is the case.

So far I’m doing this in my code to properly handle invalid payment requests:
```swift
guard PKPaymentAuthorizationViewController(paymentRequest: paymentRequest) != nil,
      let applePayContext = STPApplePayContext(paymentRequest: paymentRequest, delegate: self)
else {
   throw SomeError()
}
```

**Comment by yuki-stripe** [comment]
Huh, nice find! Thanks for reporting, we'll fix this soon.

**Comment by yuki-stripe** [comment]
This is fixed and will go out in the next release.
