### ISSUE TITLE
example mentions non-existent

### ISSUE THREAD

**Issue by mr-fixit** [stripe/stripe-ios#294]
The file "stripe-ios/Example/Stripe iOS Example (Custom)/Constants.m" says:

    Make sure to replace the values in Example/Parse/config/global.json as well if you want to use Parse.

That file doesn't exist.  Is this comment stale or would it be clearer if I started using Parse?

**Comment by jflinter** [comment]
That's a stale comment - our example app used to use Parse, but now it doesn't. I'll clean this up. Thank you!
