### ISSUE TITLE
STPPaymentCardTextField.valid is "true" on 3digit CVC's with AMEX -> But should be 4digits

### ISSUE THREAD

**Issue by richardhoehn** [stripe/stripe-ios#299]
Hi All,

Great stuff!
I found a minor issue (I think) on the `STPPaymentCardTextField`. It has a "valid" flag that is set true when the user enters the card number, expiration date, and cvc. It seems like when you enter an AMEX card it goes true on 3digits of the CVC, however AMEX have 4digits. Initially I had my view close the "number" keypad once the `STPPaymentCardTextField.valid` was true and inadvertently gave users the impression it was ok.

I think the STPPaymentCardTextField control knows what card type it is and could then be cognisant of the 4digits on the AMEX cards?

Thanks

**Comment by jflinter** [comment]
Hey there - this stems from the little-known fact that some amex cards do in fact have 3-digit CVCs, so we'd rather err on the side of accepting them. Thanks for bringing this up though!
