### ISSUE TITLE
[Feature] When will the externalPaymentMethodConfiguration officially be released?

### ISSUE THREAD

**Issue by haojin2020** [stripe/stripe-ios#2995]
## Is your feature request related to a problem? Please describe.
When will the externalPaymentMethodConfiguration officially be released? I've noticed it in the 23.17.2 version but it is an internal beta feature. To use that I have to use @_spi(ExternalPaymentMethodsPrivateBeta) import StripePaymentSheet.

## Describe the solution you'd like
We have been looking for a solution to add external PayPal support to the payment sheet recently and I think this externalPaymentMethodConfiguration will resolve our problem. We want to know if this beta version is okay to use or if we need to wait for the official release. 

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by seanzhang-stripe** [comment]
Hi @haojin2020 If you are interested in joining the beta, you can register your interest in the form at the bottom of this [page](https://site-admin.stripe.com/docs/payments/external-payment-methods?handle-redirect=replace-button).

I'll close this ticket for now, feel free to re-open it or file a new ticket.
