### ISSUE TITLE
[Feature] PayPal payment option in `PaymentSheet` provided by `StripePaymentSheet` 

### ISSUE THREAD

**Issue by rb090** [stripe/stripe-ios#2998]
## Is your feature request related to a problem? Please describe.

I am not sure if this is correctly placed within a feature request. Maybe you already have it in the Stripe SDK and I cannot find it? However - following problem:

- I am on Stripe test mode
- I use Stripe iOS SDK within SwiftUI app v23.17.2, I integrated it with Swift Package Manager
- I use the wonderful `StripePaymentSheet` which I really like because it is easy to use
- I activated PayPal within my dashboard

<img width="1632" alt="Bildschirmfoto 2023-10-18 um 21 09 38" src="https://github.com/stripe/stripe-ios/assets/59200033/7a1a849b-fa3c-4887-a47a-81aafeaa4a8f">

- PayPal payment button is missing within `StripePaymentSheet` within my iOS app:

<img width="337" alt="Bildschirmfoto 2023-10-18 um 21 04 09" src="https://github.com/stripe/stripe-ios/assets/59200033/547f2dea-1135-4179-a0c2-3bd8168fc605">

I reached out to support and they couldn't really help me with this because they don't know why I do not see PayPal button within `StripePaymentSheet`.

Is this payment method not available yet within this `StripePaymentSheet`? Am I doing sth wrong? This is how I init the payment sheet:

```
@Published var paymentSheet: PaymentSheet?

func preparePaymentSheet(with intent: StripePaymentIntent) {
        STPAPIClient.shared.publishableKey = intent.publishableStripeKey
        
        var configuration = PaymentSheet.Configuration()
        
        configuration.merchantDisplayName = intent.merchantName
        
        configuration.customer = .init(id: intent.customerId, ephemeralKeySecret: intent.ephemeralKeySecret)
        
        configuration.applePay = PaymentSheet.ApplePayConfiguration(merchantId: "my.prototype.merchant", merchantCountryCode: "DE")
                
        DispatchQueue.main.async { [weak self] in
            self?.paymentSheet = PaymentSheet(paymentIntentClientSecret: intent.clientSecret, configuration: configuration)
        }
    }
```

## Describe the solution you'd like

It would be nice to have the PayPal payment option within this nice `PaymentSheet`

## Describe alternatives you've considered
`-`

## Additional context
`-`

Thanks in regards for each advice on this 🙂

**Comment by eurias-stripe** [comment]
Hi @rb090, a few questions:
- Are you setting the `returnUrl` property in the configuration? 
- Are you using automatic payment methods or are you manually setting the list of payment methods when creating your intent?
- Are you using setup_future_usage?

**Comment by rb090** [comment]
Hi @eurias-stripe, thank you so much for getting back to me regarding this 🙂.

> - Are you setting the returnUrl property in the configuration?

Do you mean as `PaymentSheet.Configuration. returnUrl` property in the iOS config? Or do I need to configure this somehow on the Stripe dashboard? Or within my backend configuration where I create a payment intent object with `PaymentIntentCreateParams`?

> - Are you using automatic payment methods or are you manually setting the list of payment methods when creating your intent?

When creating payment intent on my backend I do not specify any allowed/disallowed payment methods within `PaymentIntentCreateParams`. My understanding from the docs here is, that if nothing gets specified when creating a payment intent, the payment methods setup on the Stripe dashboard get used.

> - Are you using setup_future_usage?

No I do not specify this. Not in the `PaymentIntentCreateParams` when creating payment intent object in the backend and also not in the `PaymentSheet.Configuration` in the iOS app. Do I need to specify this? If so, can you please tell me where I need to specify this?

**Comment by eurias-stripe** [comment]
> Do you mean as `PaymentSheet.Configuration. returnUrl` property in the iOS config? Or do I need to configure this somehow on the Stripe dashboard? Or within my backend configuration where I create a payment intent object with `PaymentIntentCreateParams`?
> 
> I thought this `returnUrl` is only necessary when offering Stripe payments on web. But I offer them on mobile.

It is necessary on mobile when offering payment methods that redirect to a website or app, like paypal does, here is the documentation on it: https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet#ios-set-up-return-url, this is probably the reason why paypal is not available.

**Comment by rb090** [comment]
Ah yes - okay that does the trick 🙈. I oversaw that one in the docs I am sorry. When I put this in, there is now PayPal as payment option within the sheet. So everything solved ✅. Thanks a lot @eurias-stripe for the explanations on this.
