### ISSUE TITLE
[BUG] Enriching PaymentIntentParams.receiptEmail doesnt work for Apple Pay 

### ISSUE THREAD

**Issue by mwurm293** [stripe/stripe-ios#3007]
## Summary
We offer Apple Pay and Credit Card payment paths. Our flow is 

1. iOS Client requests BE to request a PaymentIntent (PI) from Stripe without providing a receiptEmail 
2. BE returns the paymentIntentClientSecret to the iOS Client, which both Credit Card (CC) and Apple Pay paths use to init a PI object
3. We enrich the PaymentIntentParams with shipping address, email, savePaymentMethodBool, paymentMethod, returnUrl
4. We pass the PI to our our custom btn for CC or to ApplePay sheet (via 

## Issue
Step 3 works for CC payment, but only partially works for Apple Pay: it doesn't respect receiptEmail being supplied to the PI on iOS client, but it does respect savePaymentMethod Bool on the client, which we know because we had previously accidentally set to true and it was saving Apple Pay cards. 

Step 3:
```
    func updatePaymentIntentWithFormInfo(stripePaymentMethod: StripePaymentMethod, savePaymentMethod: Bool = false) {
        
        // Update paymentMethodInfo
        switch stripePaymentMethod {
        case .applePay:
            // Apple handles this, so we nil out payment method and set not to save payment method (which would save the Apple Pay card
            paymentIntentParams?.paymentMethodId = nil
            paymentIntentParams?.paymentMethodParams = nil
            paymentIntentParams?.savePaymentMethod = NSNumber(value: false)
                        
        case .creditCard:
            // Ensure we hae a value Payment Intent and purchase metadata to supply it
            guard let paymentIntentParams = paymentIntentParams, ecommCheckoutForm.isShippingValid(), self.getIsPaymentValid() else {
                print("Payment information incomplete")
                return
            }
                    
            // Update paymentIntent with info from form
            // Prioritize saved card
            if selectedSavedPaymentId != nil {
                paymentIntentParams.paymentMethodId = selectedSavedPaymentId
            } else if let paymentMethodParams = cardFieldViewController?.paymentMethodParams, cardFieldViewController?.cardField.isValid == true {
                    paymentIntentParams.paymentMethodParams = paymentMethodParams
            } else {
                print("Payment information incomplete")
                return
            }
            
            // Set savePaymentMethod bool based on
            paymentIntentParams.savePaymentMethod = NSNumber(value: savePaymentMethod)

            // Set return URL for when Stripe kicks the user out to browser/banking app to do some authentication.
            paymentIntentParams.returnURL = "petpainterai://stripe-redirect"
        }

        // Update email, shipping, and billTo
        paymentIntentParams?.shipping = STPPaymentIntentShippingDetailsParams(address: ecommCheckoutForm.shipToAddress!.toStripe(), name: ecommCheckoutForm.shipToName)
        paymentIntentParams?.receiptEmail = ecommCheckoutForm.receiptEmail
        var billingDetails = STPPaymentMethodBillingDetails()
        billingDetails.name = ecommCheckoutForm.billToName
        paymentIntentParams?.paymentMethodParams?.billingDetails = billingDetails
        
    }
```

Step 4:
```
            PayWithApplePayButton(.plain) {
                Task {
                    await actionBeforeConfirmPurchase()
                    
                    if let pi = stripeClient.paymentIntentParams {
                        applePayStripeClient.pay(clientSecret: pi.clientSecret)
                    }
                }
            }

```

## SDK version
23.17.0

**Comment by seanzhang-stripe** [comment]
Hi @mwurm293 Can you share with me the ID of the relevant PaymentIntent that was paid with Apple Pay?

**Comment by mwurm293** [comment]
Hi @seanzhang-stripe  thanks for your help. Here's an example PI: pi_3O45b7DE0x8W1OuD0TYTjNck

**Comment by seanzhang-stripe** [comment]
Thanks for the ID!

I checked your request [log](https://dashboard.stripe.com/logs/req_s64EAzWSWSSbTg) and I don't see a `receipt_email` in the request. There's a possibility that your code somehow didn't specify a `receipt_email`. Can you put a breakpoint in your code and make sure `ecommCheckoutForm.receiptEmail` is set?

**Comment by mwurm293** [comment]
that's the point! When payment_method is creditcard, i can request the pi from the BE without a receipt_email, then enrich it on the client once i have the email. see this line of the code above:
`        paymentIntentParams?.receiptEmail = ecommCheckoutForm.receiptEmail`

This same code is fired before the pi is supplied to Stripe-Apple-Pay, but the the receipt_email doesnt seem to actually update the the pi. I suspect this is because the applePayContext uses the clientSecret from the original BE response, and so is unaware of any client-side changes? In other words, do i have to have the receiptemail when requesting the pi from the BE to set the receipt email for Apple Pay (this isnt the case for credit card)?


A second question: the Apple Pay payment method has an 'Owner email' on it. Why isnt that used for the receipt email by default?

**Comment by seanzhang-stripe** [comment]
Hi @mwurm293 did you get a chance to debug your application and ensure the `ecommCheckoutForm.receiptEmail` is set when your app confirm a PaymentIntent with Apple Pay?

**Comment by mwurm293** [comment]
yes i hardcoded stripeClient.receiptEmail to my email when testing just now. didn't come through

**Comment by seanzhang-stripe** [comment]
That's really strange. I added a `receipt_email` in the example [code](https://github.com/stripe/stripe-ios/blob/master/Example/Basic%20Integration/Basic%20Integration/CheckoutViewController.swift#L285), and I'm able to see the `receipt_email` in the resulting PaymentIntent. Can you also try it out at your end?

**Comment by mwurm293** [comment]
does the code you linked to fire for ApplePay too? 

-----

My code is drawn from the ApplePay section of that project. The payWithApplePayButton first runs the actionBeforeConfirmPurchase, which gets a new pi if necessary and enriches it with a receiptEmail (method above). 

            ```
PayWithApplePayButton(.plain) {
                Task {
                    await actionBeforeConfirmPurchase()
                    
                    if let pi = stripeClient.paymentIntentParams {
                        applePayStripeClient.pay(clientSecret: pi.clientSecret)
                    }
                }
            }

```

```
class ApplePayStripeClient : NSObject, ObservableObject, ApplePayContextDelegate {
    
    @Published var paymentStatus: StripeApplePay.STPApplePayContext.PaymentStatus?
    @Published var lastPaymentError: Error?
    var clientSecret: String?
    


    func applePayContext(_ context: StripeApplePay.STPApplePayContext, didCreatePaymentMethod paymentMethod: StripeCore.StripeAPI.PaymentMethod, paymentInformation: PKPayment, completion: @escaping StripeApplePay.STPIntentClientSecretCompletionBlock) {
        // Confirm the PaymentIntent
        if (self.clientSecret != nil) {
            // Call the completion block with the PaymentIntent's client secret.
            completion(clientSecret, nil)
        } else {
            completion(nil, NSError())
        }
    }

    func applePayContext(_ context: StripeApplePay.STPApplePayContext, didCompleteWith status: StripeApplePay.STPApplePayContext.PaymentStatus, error: Error?) {
        // When the payment is complete, display the status.
        self.paymentStatus = status
        self.lastPaymentError = error
        
        DispatchQueue.main.async {
            switch status {
            
...

            @unknown default:
                fatalError()
            }
        }

    }

    

    func pay(clientSecret: String?) {
        self.clientSecret = clientSecret
        // Configure a payment request
        let pr = StripeAPI.paymentRequest(withMerchantIdentifier: BuildConfiguration.shared.applePayMerchantId, country: "US", currency: "USD")
        
        ....

        // Present the Apple Pay Context:
        let applePayContext = STPApplePayContext(paymentRequest: pr, delegate: self)
        applePayContext?.presentApplePay()
    }
}
```

**Comment by seanzhang-stripe** [comment]
Thanks for sharing with me the additional code, and I know why the `receipt_email` wasn't updated in the PaymentIntent.

The example [code](https://github.com/stripe/stripe-ios/blob/master/Example/Basic%20Integration/Basic%20Integration/CheckoutViewController.swift#L287) that I shared previously confirms the payment with the whole `paymentIntentParams` object which contains the `receipt_email`, and that's why `receipt_email` is included the confirmation request sent to Stripe API.

However, when you call `complete` inside the `applePayContext(_:didCreatePaymentMethod:completion:)`, it only requires a `client_secret`, not the whole `paymentIntentParams` object. Therefore, the `receipt_email` that your set locally in the iOS app is not sent to Stripe API.

Instead of setting the `receipt_email` in iOS app, I'd suggest you to make a network to your backend and use your secret key to update the PaymentIntent with the `receipt_email`.

**Comment by porter-stripe** [comment]
Closing this, if you are still hitting this issue please re-open!
