### ISSUE TITLE
[BUG]  Initiating a Payment Gateway deduction failed code 4002

### ISSUE THREAD

**Issue by anotherNight** [stripe/stripe-ios#3017]
## Code to reproduce

```
extension ViewController: ApplePayContextDelegate {
    func requestApplePay(paymentInfo: PaymentInfo) {
        if(PKPaymentAuthorizationViewController.canMakePayments()){
            let merchantIdentifier = KMerchantId
            let request = StripeAPI.paymentRequest(withMerchantIdentifier: merchantIdentifier, country: "US", currency: "USD")
            // Configure the line items on the payment request
            request.paymentSummaryItems = [
                PKPaymentSummaryItem(label: "xxx", amount: NSDecimalNumber(string: String("xxx"))),
            ]
            request.merchantCapabilities = [PKMerchantCapability.capability3DS, PKMerchantCapability.capabilityDebit, PKMerchantCapability.capabilityCredit]
            // Initialize an STPApplePayContext instance
            if let applePayContext = STPApplePayContext(paymentRequest: request, delegate: self) {
                
                // Present Apple Pay payment sheet
                DispatchQueue.safe.mainAsync {
                    applePayContext.presentApplePay {
                    }
                }
            }
        }
    }

    func applePayContext(_ context: StripeApplePay.STPApplePayContext,
                         didCreatePaymentMethod paymentMethod: StripeCore.StripeAPI.PaymentMethod,
                         paymentInformation: PKPayment,
                         completion: @escaping StripeApplePay.STPIntentClientSecretCompletionBlock) {
        pkPaymentInfo = paymentInformation
        ServiceDao.getClientsecret { secret in
            completion(secret,nil)
        } faile: { error in
            completion(nil,error)
            ProgressHUD.showErrorInfo(error: error)
        }
    }
    
    func applePayContext(_ context: StripeApplePay.STPApplePayContext,
                         didCompleteWith status: StripeApplePay.STPApplePayContext.PaymentStatus,
                         error: Error?) {
        switch status {
        case .success:
           // success
            break
        case .error:
            // Payment failed, show the error
            if let error = error {
                self.paymentInfo = nil
                ProgressHUD.showErrorInfo(error: error)
            } else {
                ProgressHUD.showError("Error,Please retry")
            }
            break
        case .userCancellation:
            // User canceled the payment
            ProgressHUD.show("Cancel",icon: .message,delay: 3)
            break
        @unknown default:
            fatalError()
        }
    }    
}
```

## iOS version

iOs 16.2
## SDK version

pod 'StripeApplePay','~> 22.8.4'

## Other information

ApplePay success,but service check status return " Initiating a Payment Gateway deduction failed, code 4002",  Where is it wrong

**Comment by seanzhang-stripe** [comment]
Hi @anotherNight Can you share with me the ID of the PaymentIntent so that I can take a look at it? Also where exactly did you get the  " Initiating a Payment Gateway deduction failed, code 4002" error?

**Comment by anotherNight** [comment]
> Hi @anotherNight Can you share with me the ID of the PaymentIntent so that I can take a look at it? Also where exactly did you get the " Initiating a Payment Gateway deduction failed, code 4002" error?

pi_3O4eGOIYWWvaFc831UDdIvKg

**Comment by seanzhang-stripe** [comment]
The PaymentIntent's status is still `requires_payment_method`, and I don't see any request from your iOS app to confirm this PaymentIntent.

Following up on my question earlier, where do you get the "Initiating a Payment Gateway deduction failed, code 4002" error? Share with me the full logs if available.

**Comment by anotherNight** [comment]
> The PaymentIntent's status is still `requires_payment_method`, and I don't see any request from your iOS app to confirm this PaymentIntent.

"and I don't see any request from your iOS app to confirm this PaymentIntent"
thank your help, Can you share which API is iOS app to confirm this PaymentIntent, is AppleKit 、stripe  or my backend？

**Comment by seanzhang-stripe** [comment]
You can confirm the PaymentIntent from your frontend or backend. Please refer to the integration [guide](https://stripe.com/docs/apple-pay?platform=ios#client-side) for details

**Comment by anotherNight** [comment]
I record the confirm request, please talk a look:
https://api.stripe.com/v1/setup_intents/seti_1O4fNrIYWWvaFc83RuPFvEBY/confirm

response：
{
  "id": "seti_1O4fNrIYWWvaFc83RuPFvEBY",
  "object": "setup_intent",
  "automatic_payment_methods": null,
  "cancellation_reason": null,
  "client_secret": "seti_1O4fNrIYWWvaFc83RuPFvEBY_secret_OsQEYj3DQ1hw1ZbWYXqZlghoJj4tGyc",
  "created": 1698133839,
  "description": null,
  "last_setup_error": null,
  "livemode": true,
  "next_action": null,
  "payment_method": "pm_1O4fNqIYWWvaFc83NplpeyuO",
  "payment_method_configuration_details": null,
  "payment_method_types": [
    "card"
  ],
  "status": "succeeded",
  "usage": "off_session"
}

iOS app is try to confirm PaymentIntent, and  status=succeeded

**Comment by anotherNight** [comment]
> You can confirm the PaymentIntent from your frontend or backend. Please refer to the integration [guide](https://stripe.com/docs/apple-pay?platform=ios#client-side) for details

I record the confirm request, please talk a look:
https://api.stripe.com/v1/setup_intents/seti_1O4fNrIYWWvaFc83RuPFvEBY/confirm

response：
{
"id": "seti_1O4fNrIYWWvaFc83RuPFvEBY",
"object": "setup_intent",
"automatic_payment_methods": null,
"cancellation_reason": null,
"client_secret": "seti_1O4fNrIYWWvaFc83RuPFvEBY_secret_OsQEYj3DQ1hw1ZbWYXqZlghoJj4tGyc",
"created": 1698133839,
"description": null,
"last_setup_error": null,
"livemode": true,
"next_action": null,
"payment_method": "pm_1O4fNqIYWWvaFc83NplpeyuO",
"payment_method_configuration_details": null,
"payment_method_types": [
"card"
],
"status": "succeeded",
"usage": "off_session"
}

iOS app is try to confirm PaymentIntent, and status=succeeded

**Comment by seanzhang-stripe** [comment]
Hi @anotherNight `seti_1O4fNrIYWWvaFc83RuPFvEBY` is a SetupIntent, not PaymentIntent. You should use PaymentIntent if you want to collect a payment from your customer.

I'm still waiting for you to provide more information about the "Initiating a Payment Gateway deduction failed, code 4002" error that you reported previously. I'm happy to investigate further if you can share the relevant logs.

**Comment by anotherNight** [comment]
> Hi @anotherNight `seti_1O4fNrIYWWvaFc83RuPFvEBY` is a SetupIntent, not PaymentIntent. You should use PaymentIntent if you want to collect a payment from your customer.
> 
> I'm still waiting for you to provide more information about the "Initiating a Payment Gateway deduction failed, code 4002" error that you reported previously. I'm happy to investigate further if you can share the relevant logs.

Finish,I  should use clientSecret "pi_xxx_secret_xxx" to comfirm PaymentIntent, clientSecret "seti_xxx_secret_xxx" is for setupIntent;iOS AppClip

**Comment by anotherNight** [comment]
thank for your help
