### ISSUE TITLE
Expiry, CVC Settings

### ISSUE THREAD

**Issue by jeffblake** [stripe/stripe-ios#303]
It would be great to support the following use cases:

- all fields enabled, but allow CVC to be optional. i.e. `isValid` can still return `YES`
- selectively disable the expiry month, year, and/or CVC fields, and collect the card number only.

I'm using a hardware accessory that collects the number and expiry from the magnetic stripe tracks, but the CVC code is not in there and it's annoying to make the user collect a CVC, especially in a point of sale kind of environment. Yes, I could do it without the Stripe Field, but its nice-looking, so I want to keep it!

Thoughts?

**Comment by jflinter** [comment]
Hey Jeff,
We'll consider adding this as a feature at some point, although I can't say when we'll get to it as it's a relatively niche use-case. In the meantime, you can accomplish this by subclassing STPPaymentCardTextField. Thanks!
