### ISSUE TITLE
Unable to build in the native Mac run destination (SwiftUI + AppKit)

### ISSUE THREAD

**Issue by AustinConlon** [stripe/stripe-ios#3043]
https://github.com/stripe/stripe-ios/blob/538f26236bf454bb93660a107edbab6e192e89e1/Stripe3DS2/Stripe3DS2/UIColor%2BDefaultColors.h#L9

In `UIColor+DefaultColors.h` and `UIColor+DefaultColors.h`, I get the compiler error `UIKit is not available when building for macOS. Consider using #if __has_include(<UIKit/UIKit.h>) to conditionally import this framework.`

**Comment by seanzhang-stripe** [comment]
Hi @AustinConlon if you want to use stripe-ios to build an app in macOS, you should use [Catalyst](https://developer.apple.com/mac-catalyst/)
