### ISSUE TITLE
Is there a paymentCardTextFieldDidEndEditing?

### ISSUE THREAD

**Issue by AtheistP3ace** [stripe/stripe-ios#306]
Is there a way to know when the user has stopped making changes to the field? Similar to textFieldDidEndEditing. I see there are multiple beginEditing for card, expiration and cvc but nothing for end editing. Is there a work around to know the user has moved the focus away from the field? Thanks!

**Comment by jflinter** [comment]
Not right now, although we'll consider adding more delegate methods in the next release. Thanks for letting us know this would be useful.
