### ISSUE TITLE
[BUG] Apple asks for NSCameraUsageDescription 

### ISSUE THREAD

**Issue by artsmvch** [stripe/stripe-ios#3060]
## Summary
Apple asks for **NSCameraUsageDescription** even though cardScanningEnabled is not enabled.

## Code to reproduce
Archive and distribute the app via Xcode:
Product -> Archive -> Distribute -> App Store Connect

Apple then sends an email saying:
`ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “App Name” bundle should contain a NSCameraUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.`

## iOS version
Any

## Installation method
Swift Package Manager.

## SDK version
23.13.0

**Comment by seanzhang-stripe** [comment]
Hi @artsmvch This is expected and required by Apple. As explained in the [readme](https://github.com/stripe/stripe-ios#card-scanning), you need to set `NSCameraUsageDescription` in your application's plist, and provide a reason for accessing the camera.

**Comment by artsmvch** [comment]
> Hi @artsmvch This is expected and required by Apple. As explained in the [readme](https://github.com/stripe/stripe-ios#card-scanning), you need to set `NSCameraUsageDescription` in your application's plist, and provide a reason for accessing the camera.

It says 
> To enable card scanning, you'll need to set NSCameraUsageDescription in your application's plist
But I do not enable it. And yet, it is necessary to set `NSCameraUsageDescription`?
Sorry if I missed something, I am not an iOS dev.

**Comment by seanzhang-stripe** [comment]
Hi @artsmvch , based on Apple's message

> If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required.

Yes you still need to provide a purpose string.
