### ISSUE TITLE
Plan to add API for retrieving costumers saved Credit Cards?

### ISSUE THREAD

**Issue by JGiola** [stripe/stripe-ios#307]
Hello, I'm asking if there are some plans to add the Customers `HTTP` API calls to the native SDKs.

One thing that can be useful is to be able to retrieve all the credit cards that the user has used inside the application. Now for my understanding we have to rely or on crude `HTTP` requests or by asking our servers to do the calls and give the results back to us.
Having this call native would be a huge bonus, because we will have native objects at the end of the calls and not some `JSON` representation to parse and to transform, for example, in `STPCard` objects.

Is something that are you interested to add in the near future?

**Comment by jflinter** [comment]
Hey @JGiola - this is something we're interested in doing, but is non-trivial due to security concerns. I can't say when we'll have something ready, but please know that we're thinking about it.
