### ISSUE TITLE
[BUG] New payment method is accepted without confirming new selection on payment sheet

### ISSUE THREAD

**Issue by Agnsemo** [stripe/stripe-ios#3074]
## Summary
When you open the sheet and select another payment method, not press confirm, but dismiss the sheet, the new selected payment stays selected.

## iOS version
 iOS 16.4

## Installation method
 SPM

## SDK version
23.18.2

**Comment by yuki-stripe** [comment]
This is expected behavior. Feel free to re-open if you have more details on what you'd like to happen instead and why!
