### ISSUE TITLE
[BUG] Apple Pay stays selected as chosen payment method even after confirming a newly added card

### ISSUE THREAD

**Issue by Agnsemo** [stripe/stripe-ios#3075]
## Summary
Open the sheet for the first time. Confirm apple pay, close the sheet, open sheet again and then add a card, confirm the card, close the sheet and open the sheet again, it shows apple pay selected and not card.

## iOS version
 iOS 16.4

## Installation method
 SPM

## SDK version
23.18.2

**Comment by yuki-stripe** [comment]
Thanks for the bug report, this is a known issue that we're working on fixing!

**Comment by yuki-stripe** [comment]
This is fixed and will be in the next release.
