### ISSUE TITLE
[BUG] Klarna Integration `returnURL` as Universal Link not calling App Delegate

### ISSUE THREAD

**Issue by mihaicris-adoreme** [stripe/stripe-ios#3083]
## Summary
**Klarna Integration**: `returnURL` not working when defined as type Universal Link (however, URL scheme works)

## Code to reproduce
```swift
func confirmPayment(_ paymentParams: STPPaymentIntentParams,
    with authenticationContext: STPAuthenticationContext,
    completion: @escaping STPPaymentHandlerActionPaymentIntentCompletionBlock
)    
```

## iOS version
17.1.1 Device / Simulator (also below versions)

## Installation method
SPM installation
```swift
.package(url: "https://github.com/stripe/stripe-ios.git", exact: "23.18.2"),
```

## SDK version
`23.18.2`

## Other information
I worked on implementation of Klarna payments integration via Stripe SDK and I had some difficulties as follows:

1) First issue: After the Stripe SDK opens the Webview in a `SFSafariViewController` and the Klarna payment flow is finished, the AppDelegate is not called with the `returnURL` in order to validate with `StripeAPI.handleURLCallback(with: url)` and thus the webview to be closed. Calling the method

```swift
func confirmPayment(_ paymentParams: STPPaymentIntentParams,
    with authenticationContext: STPAuthenticationContext,
    completion: @escaping STPPaymentHandlerActionPaymentIntentCompletionBlock
)    
```
with `paymentParams.returnURL` as Universal Link (e.g: `https://www.adoreme.com/stripe-redirect`) the `UIApplicationDelegate` method `application(_:continue:restorationHandler:).` is not called. 
I suspect that this is not working since actually presenting the `SFSafariViewController` didn't leave the app. 

Note: Setting the `STPPaymentHandler.shared().simulateAppToAppRedirect = true` will open the Safari App instead, thus leaving the main app,  and `returnURL`as Universal Link will work as expected to open the initial app (app delegate is called). However using `simulateAppToAppRedirect ` is not an option for production environments.

In the documentation https://stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet#ios-set-up-return-url  Stripe SDK is advertised to be working also with universal links.

Using an URL scheme instead for `returnURL` (e.g. `adoreme://stripe-redirect`) works as expected.

2) Second issue. If the Klarna native app is installed on the device, Stripe SDK will still open the `SFSafariViewController` instead opening the Klarna app. Diving a little bit into the Stripe SDK codebase, I was expecting the external app to be launch if available. Please confirm if this is a bug or as designed.

**Comment by yuki-stripe** [comment]
Hey @mihaicris-adoreme, thanks for the report and I'm sorry you had to debug this. 

1. Unfortunately, universal links don't work with several payment methods including Klarna. I recommend using a custom URL scheme for `returnURL` instead, like you found. We need to update the docs to reflect this :(

I believe the problem w/ universal links is that they don't work, as a security feature, if you automatically redirect to it without user interaction (as opposed to opening the link in response to a user action like tapping a button). I'm surprised that `simulateAppToAppRedirect` changes the behavior, since we should be redirecting regardless of SFSafariViewController vs. the Safari app.

2. This is the expected behavior.

**Comment by grgmo** [comment]
@yuki-stripe 
just stumbled upon the docs and still mentions [Universal Links](https://docs.stripe.com/payments/accept-a-payment?platform=ios&mobile-ui=payment-element&ui=payment-sheet#ios-set-up-return-url) supported for `returnURL`
