### ISSUE TITLE
Issue with Carthage

### ISSUE THREAD

**Issue by Dodig** [stripe/stripe-ios#309]
Hi,

### Config
- Xcode 7.2.1 (7C1002)
- Carthage 0.15

### Cartfile
```
github "stripe/stripe-ios" == 6.0.1
```

### Carthage command
```
carthage update --platform iOS
```

### The issue
When I build and run my project on the device everything is ok 
If I try to build my project on the simulator it's generate some errors:

```
ld: warning: ignoring file .../Build/Products/Debug-iphonesimulator/Stripe.framework/Stripe, file was built for i386 which is not the architecture being linked (x86_64): .../Build/Products/Debug-iphonesimulator/Stripe.framework/Stripe
...
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_STPAPIClient", referenced from:
      type metadata accessor for __ObjC.STPAPIClient in Test.o
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by jflinter** [comment]
Hi there @Dodig,
Thanks for writing in, and I'm sorry for the huge delay in getting back to you.

I've noticed that you've opened a similar issue over at https://github.com/Carthage/Carthage/issues/1175. I think this is actually an issue with Carthage - according to their documentation, it will only attempt to download prebuilt binaries that contain `.framework` in their name. We do attach some artifacts to our releases, but they're static frameworks that won't work with Carthage. They don't contain `.framework` in their names, though, so Carthage shouldn't be trying to use them.

In the meantime, the advice on that issue should work - just add the `--no-use-binaries` flag to your Carthage command (e.g. `carthage update --platform iOS --no-use-binaries`).
