### ISSUE TITLE
STPPaymentCardTextField layout errors

### ISSUE THREAD

**Issue by Mrostgaard** [stripe/stripe-ios#310]
When i follow the tutorial i get stucked here: https://stripe.com/docs/mobile/ios#prebuilt
It seems like there are something wrong with the frame. expirationField and cvcField is behind numberField instead of under it, like in the images. I'm not sure if this is a bug or i've just misunderstood something. 
![screen shot 2016-03-06 at 02 17 17](https://cloud.githubusercontent.com/assets/1463327/13551656/f5e0147c-e341-11e5-8c88-e51f01a8e933.png)
<img width="471" alt="screen shot 2016-03-06 at 02 21 01" src="https://cloud.githubusercontent.com/assets/1463327/13551662/1d429c7e-e342-11e5-8c74-f6747dc63f46.png">

**Comment by Mrostgaard** [comment]
Had the same exact problem when i tried the examples in this repository and when i tried it on the phone and in a simulator.

**Comment by jflinter** [comment]
This is intentional. If you type a valid credit card number into the CC field, it will slide away to reveal the expiration and CVC fields.
