### ISSUE TITLE
I get error please give me any solution

### ISSUE THREAD

**Issue by gaminilesh** [stripe/stripe-ios#311]
![screen shot 2016-03-09 at 10 12 32 am](https://cloud.githubusercontent.com/assets/8748763/13625612/831ff9a2-e5df-11e5-81d2-767bf9f69dff.png)

**Comment by davidrothera** [comment]
Have you tried to clear all DerivedData and running a clean before you build? These kind of errors are usually solved by cleaning and rebuilding

**Comment by gaminilesh** [comment]
sir i clear all deriveddata but same error come again and again

**Comment by davidrothera** [comment]
How are you integrating/adding Stripe to your project?

**Comment by gaminilesh** [comment]
https://stripe.com/docs/mobile/ios
this link i follow to integrating my project
first i create new project add three fremwork
Stripe,security,passkit then import shippingManager.h,constants.h,paymentviewcontroller.h and .m file
second create viewcontroller and add all methods.
In my project settings, go to the "Build Settings" tab, and make sure -ObjC is present under "Other Linker Flags".

**Comment by jflinter** [comment]
This sounds like an issue that's unrelated to the Stripe SDK. The warnings at the top of your screenshot appear to be the cause of this issue, though - it looks like you have a typo somewhere when it comes to linking the Security and PassKit frameworks. I'd highly recommend using either Cocoapods or Carthage to build your dependencies, as they'll help solve issues like this.
