### ISSUE TITLE
No way to validate custom textFields?

### ISSUE THREAD

**Issue by r-a-o** [stripe/stripe-ios#312]
I have created 3 UITextFields (Swift 2.1) ie.,

- UITextField for card number
- UITextField for cvc &
- UITextField for Expiration mm/yy

Now, how do I use stripe's card validator on these? Is it possible to validate my card number, cvc fields using STPCardValidator?

**Comment by jflinter** [comment]
You can use the various `validationStateFor`... methods on `STPCardValidator` to validate the various fields of your card. For example:

```swift
let cardString = "4242424242424242"
if STPCardValidator.validationStateForNumber(cardString, validatingCardBrand: true) == .Valid {
  // card is valid
}
```

You can read more documentation on STPCardValidator here:
http://cocoadocs.org/docsets/Stripe/6.2.0/Classes/STPCardValidator.html

**Comment by r-a-o** [comment]
Thanks!
Also, how do I implement the card number spacing for my UITextField?

**Comment by jflinter** [comment]
That behavior isn't publicly exposed. If you're interested in building that kind of effect yourself, we accomplish it by creating an NSAttributedString with custom kerning. You can see the code that does this at https://github.com/stripe/stripe-ios/blob/fa97311ce779e95b5674c7899aa54700d1f719a6/Stripe/UI/STPFormTextField.m#L61
