### ISSUE TITLE
STPCardParams is really difficult to use

### ISSUE THREAD

**Issue by simX** [stripe/stripe-ios#313]
The new STPCardParams class is really difficult to use.  There are a couple issues that I've run into, trying to upgrade to using version 6 of the framework compared to version 5.

1.  STPCardParams is mutable, but the *subclass* — STPCard — is *immutable* for some properties.  (e.g. the setNumber: and setCVC: and setExpiration: methods are all marked as deprecated on STPCard).  This is in contrast to every other standard Cocoa class, where the *mutable* variant is the subclass.  That makes it very difficult to know how to create and pass these objects around.  I'm supposed to use STPCardParams when entering card information from the UI, but then to access properties on STPCard, I cast the superclass to a subclass?!  That doesn't seem to make sense.

2.  The brand property is only available on STPCard.  Combined with #1, it makes it next to impossible to correctly figure out the brand of a card without jumping through weird code hoops.

3.  There doesn't seem to be any documentation on this change or recommended practices w/r/t using STPCard and STPCardParams.  How are you supposed to change between the two?  Your iOS integration guide specifically mentions using STPCardParams, but nothing about STPCard anymore.

**Comment by simX** [comment]
Any word on this?

**Comment by jflinter** [comment]
Hey there @simX,

To answer your questions:

1) This change was driven from the observation `STPCard` and `STPCardParams` are actually pretty different classes, meant to serve pretty different purposes. `STPCard` now represents an immutable, tokenized card that's been processed by the Stripe API. `STPCardParams` is meant to represent a forthcoming request to the API that may be incomplete. The strange subclassing behavior you noted is actually for backwards compatibility - we didn't want to break people's existing usage of `STPCard` in a single release, so it subclasses `STPCardParams` but deprecates all of the setters for number, etc to encourage people to use `STPCardParams` in their code instead.

2) The lack of a `brand` property on `STPCardParams` is a fair point; we'll add this in a future release. Until then you can use `[STPCardValidator brandForNumber:cardNumber]`.

3) In practice, we think most apps won't need to use `STPCard` moving forward - if that's not the case, though, I'm curious what you're using it for.
