### ISSUE TITLE
[Question] Is there a way to require confirmation of a saved card's CVC within the PaymentSheet?

### ISSUE THREAD

**Issue by virginiacook** [stripe/stripe-ios#3130]
Hello!

Is there a PaymentIntent configuration (either server-side or within the PaymentSheet configuration) to require confirmation of a saved card's CVC within the iOS PaymentSheet? 

Thank you,
Virginia

**Comment by wooj-stripe** [comment]
Hi,
We are in the process prioritizing support for CVC recollection.  Could you provide more information about your integration shape?

1. Are you guys using the “Mobile Payment Element” (aka [Complete Flow](https://docs.stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet)) or the “Custom Payment Element” (aka [Flow Controller](https://docs.stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet#ios-flowcontroller))?
2. Do you have an [intent first integration](https://docs.stripe.com/docs/payments/accept-a-payment?platform=ios&ui=payment-sheet#add-server-endpoint), or a [deferred intent integration](https://docs.stripe.com/docs/payments/accept-a-payment-deferred?platform=ios&type=payment)?
3. Do you know if you are using client side confirmation, or if you need [server side confirmation](https://docs.stripe.com/docs/payments/finalize-payments-on-the-server?platform=ios&type=payment)?

Thanks!

**Comment by virginiacook** [comment]
@wooj-stripe sorry for my delayed response! We are using the PaymentSheet (not flow controller). Based on that, I believe we are using an intent-first integration, and need client-side confirmation, not server-side confirmation.

An ideal solution for us would be to have the PaymentSheet handle CVC recollection before actually charging the card (maybe have a boolean value for the configuration which is requireCVCRecollection or something along those lines to require cvc for saved cards), and pretty much work out of the box.

Thank you!

**Comment by ryanzhangdd** [comment]
Hi @wooj-stripe -- would you be able to provide a rough estimate on when cvc recollection will be supported in the ios sdk?

**Comment by wooj-stripe** [comment]
@ryanzhangdd -
Thanks for reaching out!. Unfortunately, I don't have a rough estimate as to when CVC Recollection will be GA'ed in the iOS SDK. If you'd like, [you can sign up for our beta](https://docs.stripe.com/payments/accept-a-payment?platform=ios&mobile-ui=payment-element&ui=payment-sheet#ios-cvc-recollection) :).

cc: @virginiacook

**Comment by sfriedman-stripe** [comment]
Hi all, I'm going to close this issue down since the beta John mentioned has been available for a bit now. If you have any feedback on the beta, please open a new issue! Thank you
