### ISSUE TITLE
Type 'Locale' has no member 'stp_isoRegionCodes' 

### ISSUE THREAD

**Issue by Mohsenkhodadadzadehthelist** [stripe/stripe-ios#3139]
## Summary

After I updated the `Stripe`, and `StripeUICore` got an error on a class in the `StripeUICore` framework
the error is in `StripeUICore` -> `String+CountryEmoji.swift`

## Installation method

Cocoapods
## SDK version

23.20.0
## Other information

<img width="1010" alt="Screenshot 2023-12-20 at 5 22 08 PM" src="https://github.com/stripe/stripe-ios/assets/98982026/55a29627-bb2c-45aa-aaad-8950fdb7042f">

**Comment by davidme-stripe** [comment]
Can you try a clean build and re-running `pod install`? It sounds like the StripeCore version is out of sync with the StripeUICore version.

**Comment by porter-stripe** [comment]
Hi @Mohsenkhodadadzadehthelist I'm going to close this as stale, if you're still hitting this issue please re-open with details!
