### ISSUE TITLE
Cannot find type 'PaymentSheet' in scope

### ISSUE THREAD

**Issue by muhammadabbas001** [stripe/stripe-ios#3141]
## Summary

I am getting `Cannot find type 'PaymentSheet' in scope`. I have tried a lot but getting the following error.

<img width="1386" alt="Screenshot 2023-12-21 at 1 52 25 AM" src="https://github.com/stripe/stripe-ios/assets/73989872/b33bdc9f-96dd-4a1d-aa02-35139dc6e5a1">

When I import the `import StripePaymentSheet` then getting following error 

<img width="1398" alt="Screenshot 2023-12-21 at 1 54 06 AM" src="https://github.com/stripe/stripe-ios/assets/73989872/b1be0909-f8db-46ec-b795-3c036e742f20">

Could you please help me to solve that problem? 

## iOS version

IOS 17 - Simulator 

## Installation method

XCode Package Manager

## SDK version

23.20.0

**Comment by rajstigasoft** [comment]
I am also have same error in Xcode 17

**Comment by muhammadabbas001** [comment]
I have resolved that issue by adding the PaymentSheet in `Link Binary With Libraries`

- Select project `Root Folder`
- Go to the `App Target`
- Select `Build Phases`
- Press the add button and then add the `StripePaymentSheet` package 
- After that `import StripePaymentSheet`

<img width="1380" alt="Screenshot 2023-12-26 at 5 39 20 AM" src="https://github.com/stripe/stripe-ios/assets/73989872/8987064c-7d77-4315-a794-6d1a98c74c82">

After that, all errors related to `StripePaymentSheet` will be resolved.
