### ISSUE TITLE
`STPCardValidator` should work on raw values, not format strings

### ISSUE THREAD

**Issue by irace** [stripe/stripe-ios#315]
`STPCardValidator` currently operates on the strings that the view model exposes. Instead, it should operate on the raw values that the `STPPaymentCardTextField` exposes.

**Comment by jflinter** [comment]
@irace - just fixed this in https://github.com/stripe/stripe-ios/pull/329. I took the other way around, adding `formattedExpMonth` and `formattedExpYear` properties to `STPCardParams` - I didn't want `STPCardValidator` to lose the ability to semantically differentiate between, say, `@"1"` and `@"01"`.

**Comment by irace** [comment]
Not sure that actually addresses my issue, but also not sure that you necessarily should.

To reiterate, I want to be able to validate the `expirationMonth`, `expirationYear` etc. that I get from `STPPaymentCardTextField`. Currently, the only way for me to do that is to turn them into strings first.

In other words, I think `STPPaymentCardTextField`’s outputs should match `STPCardValidator`’s inputs.

**Comment by jflinter** [comment]
@irace - you can do e.g. `[STPCardValidator validationStateForExpirationMonth:textField.card.formattedExpiration]`. A little all-over-the-place, I admit, but should get you what you want.

OOC, there's also `[STPCardValidator validationStateForCard:textField.card]`.

**Comment by jflinter** [comment]
@irace - I tweaked this a little bit in https://github.com/stripe/stripe-ios/commit/deeddf21b86fa5cc0fb96a882203b2778e8d541f - now you can just do e.g. `[STPCardValidator validationStateForExpirationMonth:textField.formattedExpirationMonth]`
