### ISSUE TITLE
[BUG] Failed to find an image named icon_x_standalone

### ISSUE THREAD

**Issue by clementmorissard** [stripe/stripe-ios#3156]
## Summary
I'm having a crash on an image not found
`StripeUICore/ImageMaker.swift:51: Assertion failed: Failed to find an image named icon_x_standalone`

The weird thing is that the crash happens on the PaymentSheet.present, but it does not crash on the CustomerSheet.present somewhere else in the app...
And other thing which is weird, it seems that the crash only happens when i use the app when it's still linked to xcode

## Code to reproduce

`public func presentPaymentSheet(customerId: String, ephemeralKey: EphemeralKey, paymentIntentClientSecret: String, completion: @escaping (StripePaymentSheetResultEnum) -> Void) {`

        var applePayConfiguration: PaymentSheet.ApplePayConfiguration? = nil
        if let merchantId = Bundle.main.object(forInfoDictionaryKey: "MerchantId") as? String {
            applePayConfiguration = PaymentSheet.ApplePayConfiguration(merchantId: merchantId, merchantCountryCode: "FR")
        }

        var configuration = PaymentSheet.Configuration()
        configuration.merchantDisplayName = "Rythmetech."
        configuration.customer = .init(id: customerId, ephemeralKeySecret: ephemeralKey.secret)
        configuration.appearance.font.base = RawFonts.latoLight.font(size: 14)
        configuration.appearance.colors.primary = Asset.DesignSystem.primaryColor
        configuration.appearance.colors.danger = Asset.Colors.redE4.color
        configuration.applePay = applePayConfiguration
        
        let paymentSheet = PaymentSheet(paymentIntentClientSecret: paymentIntentClientSecret, configuration: configuration)
        paymentSheet.present(from: sourceViewController!) { result in
            switch result {
            case .canceled:
                completion(.canceled)
            case .completed:
                completion(.completed)
            case .failed(let error):
                completion(.failed(error: error))
            }
        }`

## Installation method
I'm using cocoapods
> def stripe_pods
>   pod 'Stripe', '~> 23.20.0'
>   pod 'StripePaymentSheet', '~> 23.20.0'
> end
> 
> def shared_pods
>   pod 'PhoneNumberKit', '~> 3.7.0'
>   pod 'SwiftGen', '~> 6.6.0'
>   pod 'ScanditBarcodeCapture', '~> 6.20.0'
>   pod 'RealmSwift', '~> 10.32.0'
>   pod 'Intercom', '~> 14.1.0'
>   pod 'MessageKit'
> 
>   common_pods
>   stripe_pods
>   pod 'SGSegmentedProgressBarLibrary'
> end
> 
> target "RythmePayment" do
>   project './RythmePayment/RythmePayment.xcodeproj'
>   common_pods
>   stripe_pods
> end
> 
> target 'Rythme' do
>   shared_pods
>   firebase_pods
> 
>   target 'RythmeTests' do
>     inherit! :search_paths
>     # Pods for testing
>   end
> 
>   target 'RythmeUITests' do
>     # Pods for testing
>   end
> end

`

But i'm using frameworks, so Rythme is using RythmePayment framework to present the PaymentSheet

## SDK version
23.20.0'

## Other information
I'm wondering if my podfile is wrong, and i got 2 instances of the stripe pod and there is a conflict

**Comment by Mycose** [comment]
Hello @yuki-stripe, I justed tested to remove `pod 'Stripe', '> 23.20.0'` and changing my imports from `import Stripe` with `import StripePaymentsSheet` but i'm having the same crash

**Comment by Mycose** [comment]
I did some tests: 

      var image = UIImage(
        named: imageName, in: BundleLocator.resourcesBundle, compatibleWith: traitCollection)

      if image == nil {
          image = UIImage(named: imageName, in: nil, compatibleWith: traitCollection)
      }

      if templateIfAvailable {
        image = image?.withRenderingMode(.alwaysTemplate)
      }
    
        print("ImageMakerBundleLocator = \(BundleLocator.resourcesBundle), imageName = \(imageName)")

      return image
    }
`

The crash occurs when the BundleLocator search in the StripeUICore bundle

`</var/containers/Bundle/Application/751A6ABF-2BDB-4909-BB3B-432FF9CA13C7/Rythme.app/Frameworks/StripePaymentSheet.framework/StripePaymentSheet.bundle> (not yet loaded), imageName = icon_x_standalone
ImageMakerBundleLocator = NSBundle </var/containers/Bundle/Application/751A6ABF-2BDB-4909-BB3B-432FF9CA13C7/Rythme.app/Frameworks/StripeUICore.framework/StripeUICore.bundle> (not yet loaded), imageName = icon_chevron_down`

I feel like it's random whether it looks in StripeUICore (crash), StripePaymentsSheet (no crash) or StripePaymentsUI (no crash)

**Comment by samirmakadia** [comment]
I am using latest version of stripe in iOS also facing same issue in device but in simulator it working fine so @yuki-stripe can you please solve this issue and update new version

**Comment by porter-stripe** [comment]
Closing this as stale! I believe we found the root cause of this in ~March 2024, if you are still hitting this issue please re-open.

**Comment by chrisjenx** [comment]
Still facing this with SPM on 24.+

**Comment by chrisjenx** [comment]
OK this is a bug in the way the stripe sdk looks up resources, if you use the root view controller it crashes, I changed to use the updated view controller from the callback and it started working:

Cross posting to hopefully help others

```
func updateUIViewController(_ uiViewController: UIViewController, context: Self.Context) {
        paymentsLauncher.rootViewController = uiViewController
    }
```

**Comment by chrisjenx** [comment]
OK only way I seem to get this to work is literally build the app back to back, the second build must bundle the assets correctly, the first time doesn't.

Could we request that you don't crash the damn app because you can't load a f*ing icon, it's not that important vs taking payment...

**Comment by chrisjenx** [comment]
Still broken: `icon_x_standalone` is missing, from pure Swift/SPM Xcode project now

**Comment by chrisjenx** [comment]
Finally worked around the Stripe-SPM module issues by just manually importing the xcframeworks:

Script for anyone else struggling with this bug: https://gist.github.com/chrisjenx/79fe87fc45a3821afe2715832e3770be
