### ISSUE TITLE
How i check one field only valid or not?

### ISSUE THREAD

**Issue by gaminilesh** [stripe/stripe-ios#316]
i use STPPaymentCardTextField but i cant understand only card valid or not? not other field check one textfield

**Comment by jflinter** [comment]
@gaminilesh, sorry for the slow reply. You can use the various utility methods in `STPCardValidator` to do this; I'd recommend reading the documentation for it: https://github.com/stripe/stripe-ios/blob/master/Stripe/PublicHeaders/STPCardValidator.h
