### ISSUE TITLE
[BUG]  Assertion failed: `secret` format does not match expected client secret formatting.

### ISSUE THREAD

**Issue by Maks273** [stripe/stripe-ios#3162]
Keep getting Assertion failed: `secret` format does not match expected client secret formatting.
<img width="838" alt="Screenshot 2024-01-08 at 11 31 09" src="https://github.com/stripe/stripe-ios/assets/41189987/ea007c91-8c89-478f-a3a3-b24a75e1733a">

**Comment by Maks273** [comment]
I have no idea why I get the crash with swiftui project, just doing same stuff as I used to do for UIKit project

**Comment by seanzhang-stripe** [comment]
You should check `model.paymentIntent` and make sure it holds the value of a valid PaymentIntent [client_secret](https://stripe.com/docs/api/payment_intents/object#payment_intent_object-client_secret).  A valid `client_secret looks` has the following format: `pi_ABC_secret_XYZ`.

**Comment by Maks273** [comment]
@seanzhang-stripe is there validator? my client secret looks good.

**Comment by Maks273** [comment]
@seanzhang-stripe here is how I call payment sheet
f let paymentSheet = viewModel.paymentSheet {
                    PaymentSheet.PaymentButton(
                        paymentSheet: paymentSheet,
                        onCompletion: viewModel.onPaymentCompletion
                    ) {
                        Text("Buy")
                    }
                } else {
//                    Text("Loading…")
                }

**Comment by seanzhang-stripe** [comment]
If the PaymentIntent was created in test mode, can you share with me the PaymentIntent client_secret that you specified in your application? 

By the way, here's the [sample code](https://github.com/stripe/stripe-ios/blob/master/Example/PaymentSheet%20Example/PaymentSheet%20Example/ExampleSwiftUIPaymentSheet.swift) about using PaymentSheet in SwiftUI. Hope it's helpful.
