### ISSUE TITLE
[Feature] VisionOS Support

### ISSUE THREAD

**Issue by thatvirtualboy** [stripe/stripe-ios#3163]
Stripe 23.3.2 SPM installed won't build for VisionOS due to use of `UIScreen`:

`UIScreen is unavailable in visionOS`

**Comment by davidme-stripe** [comment]
Can you try the latest version, 23.20.0? It should be fully compatible with visionOS.

**Comment by thatvirtualboy** [comment]
Updating the SPM package from Xcode doesn't pull that build. Does it require removing the current SPM and using a new URL?

**Comment by davidme-stripe** [comment]
That's strange, both https://github.com/stripe/stripe-ios and https://github.com/stripe/stripe-ios-spm (our SPM mirror repo) should select the latest version by default. If Xcode isn't picking up the new version automatically, you can adjust it from your Xcode project settings:  
![CleanShot 2024-01-08 at 13 12 24@2x](https://github.com/stripe/stripe-ios/assets/52758633/ddb9742f-907e-4312-bdfb-49b59b3212e4)

**Comment by thatvirtualboy** [comment]
Ah, I had it set to Exact Version somehow. Thank you

**Comment by thatvirtualboy** [comment]
Resolved with latest build

**Comment by davidme-stripe** [comment]
Great, glad that worked! Let us know if you run into any other issues with our visionOS support, we'd love to get more feedback on it.

**Comment by JazKingX** [comment]
I am having the same issue, but no luck resolving atm

<img width="928" alt="Screenshot 2024-01-22 at 19 53 24" src="https://github.com/stripe/stripe-ios/assets/21957803/5f96cd1d-2437-426c-9bf6-76d2db3a39e1">

<img width="296" alt="Screenshot 2024-01-22 at 20 05 17" src="https://github.com/stripe/stripe-ios/assets/21957803/a8d0e099-abcd-4d43-9bdd-104088348771">

**Comment by davidme-stripe** [comment]
Can you import the StripePaymentSheet [module](https://github.com/stripe/stripe-ios?tab=readme-ov-file#modules) directly? StripePayments and StripePaymentsUI should work as well. We don't plan to support Basic Integration on visionOS.
