### ISSUE TITLE
[BUG] Compiler Version Mismatch with Stripe SDK 23.21.0 on Xcode 15.2 and macOS 14.2.1

### ISSUE THREAD

**Issue by jalxp** [stripe/stripe-ios#3182]
## Summary
I am experiencing a build failure when integrating the Stripe SDK into my iOS project. The error message indicates a compiler version mismatch. The Stripe SDK is built with 'Apple Swift version 5.7.1', whereas my compiler version is 'Apple Swift version 5.9.2'. This issue arises when I try to import the Stripe module in my project. The version I've had before with no problems was version 22.5.1.

## Code to reproduce
The problem occurs when importing the Stripe module into any Swift file in the project. The issue is not specific to any particular piece of code but rather the integration of the Stripe SDK as a whole.

## iOS version
I am working on macOS 14.2.1 (23C71) and using Xcode Version 15.2 (15C500b) and I'm targeting iOS 17.0.1

## Installation method
I downloaded the xcframework.zip of Stripe release 23.21.0 and manually integrated it into my project. The modules I am using are Stripe, Stripe3DS2, StripeApplePay, StripeCore, StripePayments, and StripeUICore.

## SDK version
I am using Stripe SDK version 23.21.0, as indicated by the downloaded xcframework.zip from the official Stripe GitHub releases.

## Other information
The issue persists even after ensuring that I am using the latest version of Xcode (Version 15.2) and the latest Stripe SDK version. There seems to be a mismatch in the Swift compiler version expected by the Stripe SDK and the one available in my development environment. Any guidance on resolving this issue or confirmation if this is a known bug would be greatly appreciated.

**Comment by yuki-stripe** [comment]
Hi @JalxP, is it possible for you to use Swift Package Manager instead?  

If not, could you post the specific error you're seeing? The xcframework binary is built using Xcode 14 to maximize compatibility, but it should work on Xcode 15 too.

**Comment by davidme-stripe** [comment]
This should be fixed now — we're now building binaries with Xcode 15.
