### ISSUE TITLE
Xcode 7.3: lot of warnings

### ISSUE THREAD

**Issue by TofPlay** [stripe/stripe-ios#319]
Hi,
After installed Xcode 7.3 when I build with Carthage I have a lot of warnings:
```
warning: 'var' parameters are deprecated and will be removed in Swift 3
warning: '++' is deprecated: it will be removed in Swift 3
warning: keyword 'protocol' does not need to be escaped in argument list
warning: use of 'typealias' to declare associated types is deprecated; use 'associatedtype' instead
```

**Comment by jflinter** [comment]
Hi there,
Those don't sound like warnings for the Stripe SDK - those sound like warnings elsewhere in your project. Xcode 7.3 [uses Swift 2.2](https://swift.org/blog/swift-2-2-released/), which adds a lot of warnings for Swift code that uses features that will be removed in a later version of Swift.
