### ISSUE TITLE
[BUG] Potential memory leak detected in PaymentSheet sample app

### ISSUE THREAD

**Issue by Tulakshana** [stripe/stripe-ios#3212]
## Summary
I ran the Xcode profile tool that detects memory leaks in the sample app and found a potential memory leak.

## Code to reproduce
Launch the sample app using Xcode profile tool that detects memory leaks (on a real device)
Wait in the first screen until the tool says no memory leaks
Tap on the PaymentSheet (SwitfUI)
Wait until the tool says no memory leaks
Tap on 'Buy'

## iOS version
16.2

## Installation method
Sample app: https://github.com/stripe/stripe-ios/tree/master/Example/PaymentSheet%20Example

## SDK version
Master downloaded on 23rd of January 2024

## Other information
![Screen Shot 2024-01-25 at 11 34 54 AM](https://github.com/stripe/stripe-ios/assets/1791770/18265883-fac9-44ee-95ea-f0f29bb42883)

**Comment by porter-stripe** [comment]
Hi @Tulakshana thanks for bringing this to our attention, I have submitted a fix!
