### ISSUE TITLE
validateCardReturningError() is deprecated, using STPCardValidator instead: Syntax question in Swift 2.1

### ISSUE THREAD

**Issue by daisyramos317** [stripe/stripe-ios#322]
So I was using an older version of Stripe, v5.1.4 until recently hence the numerous deprecation warnings I've received :)
Anyhow I am using STPCardValidator and wanted to know if my syntax is correct when calling the .validationState() methods.

Here is what I have. Note: I am using a regex function to validate the card type

`if (self.validateCardType(creditCardField.text!) == "Visa") {
           STPCardValidator.validationStateForCVC(self.securityField.text!, cardBrand: STPCardBrand.Visa)
            STPCardValidator.validationStateForNumber(self.creditCardField.text!, validatingCardBrand: true)
        }
`

**Comment by jflinter** [comment]
Hey there @daisyramos317,
Sorry for the slow reply on our end. That syntax isn't correct - you'll actually need to check the validation state returned by those functions. I'd recommend you do something like:

```swift
let cardParams = STPCardParams()
cardParams.number = ...
cardParams.expMonth = ...
cardParams.expYear = ...
cardParams.cvc = ...
if STPCardValidator.validationStateForCard(cardParams) == .Valid {
  // the card is valid.
}
```

**Comment by daisyramos317** [comment]
thank you!

**Comment by phungnet** [comment]
thanks

**Comment by hemraj-shaqawal** [comment]
thanks
