### ISSUE TITLE
 StripeUICore/ImageMaker.swift:51: Assertion failed: Failed to find an image named icon_x_standalone

### ISSUE THREAD

**Issue by umerafzal3** [stripe/stripe-ios#3220]
## Summary
I have call PaymentSheet in swift and show this error  and crash my app"StripeUICore/ImageMaker.swift:51: Assertion failed: Failed to find an image named icon_x_standalone" 

## Code to reproduce
   STPAPIClient.shared.publishableKey = publishableKey
   paymentSheet = PaymentSheet(paymentIntentClientSecret: paymentIntent, configuration: .init())

## iOS version 
 iOS 16.0 and 17.0

## Installation method
 pod 'StripePaymentSheet'

## SDK version
 StripeApplePay (23.21.1) 
 StripeCore (23.21.1) 
 StripePaymentSheet (23.21.1) 
 StripePayments (23.21.1) 
 StripePaymentsUI (23.21.1) 
 StripeUICore (23.21.1)

**Comment by porter-stripe** [comment]
Duplicate of https://github.com/stripe/stripe-ios/issues/3156

**Comment by chrisjenx** [comment]
OK this is a bug in the way the stripe sdk looks up resources, if you use the root view controller it crashes, I changed to use the updated view controller from the callback and it started working:

Cross posting to hopefully help others

```
func updateUIViewController(_ uiViewController: UIViewController, context: Self.Context) {
        paymentsLauncher.rootViewController = uiViewController
    }
```

**Comment by chrisjenx** [comment]
OK only way I seem to get this to work is literally build the app back to back, the second build must bundle the assets correctly, the first time doesn't.

Could we request that you don't crash the damn app because you can't load a f*ing icon, it's not that important vs taking payment...

**Comment by chrisjenx** [comment]
Still broken: `icon_x_standalone` is missing, from pure Swift/SPM Xcode project now

**Comment by chrisjenx** [comment]
Finally worked around the Stripe-SPM module issues by just manually importing the xcframeworks:

Script for anyone else struggling with this bug: https://gist.github.com/chrisjenx/79fe87fc45a3821afe2715832e3770be
