### ISSUE TITLE
Apple Pay sheet not displayed in TestFlight build

### ISSUE THREAD

**Issue by pixelier** [stripe/stripe-ios#3221]
## Summary
I added Apple Pay by following all the steps. I am able to successfully perform payments on Test mode. On prod mode, I am able to perform payments when the build is in debug mode (launched through Xcode). However, when using the build from Testflight that I am submitting to the App Store, the Apple Pay button is displayed but when it is clicked, the payment sheet re-appears, as if the Apple Pay checks are failing internally in the SDK (check the screen recording). The app is not yet available on the App Store, it's under review.
As per Stripe's customer support, I checked canMakePayments after submitting a new build on TF and it's returning `true`.
Note also that I was able to perform a payment on live mode on the same build by manually adding a card instead of using Apple Pay.

## iOS version
iOS 17.3

## Installation method
SPM

## SDK version
23.21.1 (latest)

## Other information

https://github.com/stripe/stripe-ios/assets/11842099/114dd0f4-648b-4b3f-b40b-5b8b16d0c151

**Comment by r-thefork** [comment]
Update: I verified that the flow is working fine on Testflight in test mode. So it's only live mode + Testflight that has the issue.
