### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by codegastudio** [stripe/stripe-ios#324]
> pod install
> Updating local specs repositories
> Analyzing dependencies
> [!] An unexpected version directory `ApplePay` was encountered for the `/Users/.../.cocoapods/repos/stripe/Stripe` Pod in the `Stripe` repository.

Something wrong ?

**Comment by jflinter** [comment]
Hey there @codegastudio,

I'm guessing there's something wrong with your Podfile. Based on a quick search, it seems other people who have had similar issues with other pods in the past have used the wrong value for `source` in their Podfile: http://stackoverflow.com/questions/27384551/cocoapods-an-unexpected-version-directory-was-encountered-how-do-i-fix-this

I'd first read https://guides.cocoapods.org/using/the-podfile.html to understand how the Podfile works a little bit better. Then I'd make sure that there aren't any `source` entries in your Podfile referencing Stripe (i.e. nothing like `source 'https://github.com/stripe/stripe-ios.git'`). If you're still having trouble after that, post your Podfile and your Podfile.lock here and I'll have a look at them.
