### ISSUE TITLE
while saving card STPPaymentCardTextField is returning null

### ISSUE THREAD

**Issue by chatvenkat** [stripe/stripe-ios#325]
Hi,

I don't have an expert understanding on delegate's.

I'm trying to use story board to configure the STPPaymentCardTextField. I have a table view and i would like to have STPPaymentCardTextField as one of the tableviewcell. Once user's enter the required CC data they would click on save (UIButton) next to it and i would like to call createtoken method for that.

I tried this, created UItableview & UItableviewcell (custom). Added a view to uitableviewcell and assigned it to STPPaymentCardTextField. When i type the CC info it works (after entering card number it show EXP/CVC) well, however in button click method the [self.STPPaymentCardTextField isValid] is return nil and [self.STPPaymentCardTextField cardnum] is also num.

What am i missing, how can i access STPPaymentCardTextField without assigning a delegate, 

![screen shot 2016-04-12 at 4 14 04 pm](https://cloud.githubusercontent.com/assets/9665439/14474222/f21d62e0-00c9-11e6-81fd-0182484cd389.png)

**Comment by jflinter** [comment]
Hello there,

It's hard to say for certain what's going wrong in your code, but as a hunch I would make sure that you've correctly wired up your text field outlet in your storyboard. I have a feeling that is nil.

I'd recommend reading https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaEncyclopedia/DelegatesandDataSources/DelegatesandDataSources.html to learn more about how the delegate pattern works.
