### ISSUE TITLE
Card scan Camera access denied UI issue

### ISSUE THREAD

**Issue by nigeshvenu** [stripe/stripe-ios#3303]
## Summary
Card scan Camera access denied UI issue

## iOS version
17.3
![Image_20240216_155956_790](https://github.com/stripe/stripe-ios/assets/29941422/64874afa-e468-4715-b303-896633a5d842)

## SDK version
23.22.0

**Comment by sfriedman-stripe** [comment]
Hi @nigeshvenu, in order for us to better assist you with this integration issue, I'd love to point you to our 24/7 support on [our Discord](https://stripe.com/go/developer-chat) where we have engineers ready to help you. If you find a bug in the SDK itself, please feel free to open an issue here with more detail about what you've tried and what exactly is broken. Thank you!
