### ISSUE TITLE
Non numerical 'numberPlaceholder' text being formatted as Card Number

### ISSUE THREAD

**Issue by gemmakbarlow** [stripe/stripe-ios#333]
As of 7.0.0, the text I'm setting as `numberPlaceholder` is being formatted like a card number, i.e.

![formatted](https://cloud.githubusercontent.com/assets/337963/14923011/ad2c7b3e-0e08-11e6-8dae-fae3dd97070e.png)

Wanted to check in and see if this was a deliberate choice; if not, one fix could be to add an `isNumeric` check prior to applying the formatting.

**Comment by gemmakbarlow** [comment]
(Happy to help whip up a fix!) :)

**Comment by jflinter** [comment]
Ah, thanks @gemmakbarlow and sorry for the trouble - I've fixed this in https://github.com/stripe/stripe-ios/commit/0b06ab55a58eab072b9d8d34496f568defdbe240 and will cut a 7.0.1 release shortly.

**Comment by gemmakbarlow** [comment]
Champion, thanks for the speedy turnaround @jflinter.
