### ISSUE TITLE
7.0.1 credit card number entry skipping last four digits for some numbers

### ISSUE THREAD

**Issue by chrismanderson** [stripe/stripe-ios#337]
On 7.0.0 and 7.0.1, I'm seeing a card entry bug for certain Visa card numbers. When entering an affected number, the cursor will jump to the date field after completing the first three blocks of numbers instead of continuing to type in the . `4147 2589 1247 1216` is an example of an afflicted card number. (Not a real number, but passes the Luhn test so valid for purposes of this test. `4012888888881881` is another example, one of the Stripe sample cards.

As a user, I can tap on the card number to force the cursor to jump back to card entry, but the cursor should not be jumping forward to begin with.

I'm not sure how many card numbers this bug affects, but I could find failing numbers fairly easily, so I don't think it's a tiny outlier (and even if it is, still a major issue).

There are no code changes between the two versions in my recordings. This bug also occurs in the Stripe Custom example project in the repo.

Correctly working on 6.2.0
![](http://cl.ly/1N2t3D3B3a0v/Screen%20Recording%202016-05-10%20at%2004.29%20PM.gif)

Failing on 7.0.1
![](http://cl.ly/2Z0A3A2g2B0z/Screen%20Recording%202016-05-10%20at%2004.36%20PM.gif)

**Comment by jflinter** [comment]
Thanks for the bug report, @chrismanderson. We added support for 13-digit Visa numbers (which are apparently a thing) in version 7.0.0. Unfortunately it seems that Visa numbers whose first 13 digits are themselves luhn valid will prematurely validate here.

I'm going to look and see if there are any additional identifying features of a 13-digit Visa card that would allow us to distinguish between these two cases. That'll inform what we can do about this.

**Comment by RonKliffer** [comment]
Hi @jflinter 
I'm experiencing this bug as well, in production.
Any eta for a fix or should I roll back to 6.2?

**Comment by jflinter** [comment]
Hey @chrismanderson and @RonKliffer,
I think we've figured out a way to fix this on our end, and are aiming to have a fix by the end of the week. Thanks for your patience, and sorry for the trouble!

**Comment by jflinter** [comment]
OK @chrismanderson @RonKliffer - this should be fixed as of #339. I've also pushed a 7.0.2 version containing the fix. Thanks again for the bug report, and your patience!
