### ISSUE TITLE
[BUG] Card logo not showing for EU stripe account (having CBC) when the credit card number is not yet entered

### ISSUE THREAD

**Issue by jfougere** [stripe/stripe-ios#3376]
Contrary to the behavior on Android & Web, the credit rotating card logos only show up on iOS when CBC is not active on the Stripe account, where on Android & Web even with CBC is active the rotating card logos are displayed when the credit card number is empty.

CBC dropdown can only be shown once you detect a co-branded credit card, so the default behavior when the credit card number is empty should be to display the rotating credit card logo irrespective to the CBC being active on the Stripe account or not. 

This would align the iOS SDK on the Android & Web behavior.

**Comment by porter-stripe** [comment]
Hi @jfougere, version 23.25.0 of the SDK now shows the card brands when the card number is empty.
