### ISSUE TITLE
Add @objc attribute for Kotlin cinteropt support

### ISSUE THREAD

**Issue by chrisjenx** [stripe/stripe-ios#3377]
## Is your feature request related to a problem? Please describe.
The iOS Pods are unusable with Kotlin Multiplatform because the cinteropt can't see pure swift classes see: https://kotlinlang.org/docs/multiplatform-configure-compilations.html#configure-interop-with-native-languages "Swift Via Objective-C" 

I.e: https://github.com/stripe/stripe-ios/blob/master/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheet.swift

is not interopted because of the missing attribute

## Describe the solution you'd like
add @objc attributes to public API so we can use them.

## Describe alternatives you've considered
Create a Compose Multiplatform Library which supports Android and iOS from common code.

**Comment by porter-stripe** [comment]
Hi @chrisjenx adding Objective-C support to PaymentSheet is not currently on our roadmap.

As an alternative, you might consider wrapping your use of PaymentSheet within Swift. We've applied a similar workaround for our framework implemented in React Native that you can refer to here: [React Native](https://github.com/stripe/stripe-react-native/blob/master/ios/StripeSdk.swift#L119).

To do this, you could create a Swift file that wraps your PaymentSheet usage, then make it visible to Objective-C by using the @objc annotation.

**Comment by chrisjenx** [comment]
Hacks and Workarounds are not really a good solution, that means I now have to maintain additional API on top of yours. Please suggest a better solution.
