### ISSUE TITLE
Still v 6.2.0 in Fabric app

### ISSUE THREAD

**Issue by JGiola** [stripe/stripe-ios#338]
I don't know if is something you can act upon or if it is a responsibility of the Fabric team, but if you integrate the Stripe SDK through the Fabric app, the last available version is the 6.2.0 and not the 7.0.1.

A bypass of this issue is to manually update the SDK or via cocoapods, but the Fabric app is constantly opening for naggin me that the launched app has an issue (and the issue is, "App has version 7.0.1 installed, 6.2.0 is the current version." that per se is a comical thing).

Can you upgrade the version that is seen by the Fabric app? Or do you have a direct link to the Fabric team for letting them know that the version is not updating correctly?

**Comment by jflinter** [comment]
Hey, sorry about this! We've sent the latest version (v7.0.2) to the Fabric team, it should be up within the next day.
