### ISSUE TITLE
Stripe Bug with V(23.25.0) in PaymentSheet FlowController

### ISSUE THREAD

**Issue by ideal8173** [stripe/stripe-ios#3407]
Please help here

We are trying to change "Continue" Button title  But not change 

Using SDK V(23.25.0)  version 

===============================================
By using this code:-

var paymentSheetFlowController: PaymentSheet.FlowController?

var configuration = PaymentSheet.Configuration()
 configuration.primaryButtonLabel = "Submit"
 
  let intentConfig = PaymentSheet.IntentConfiguration(
            mode: .setup()
        ) { [weak self] paymentDetails, _, intentCreationCallback in
        }
 
  PaymentSheet.FlowController.create(
                   intentConfiguration: intentConfig,
                   configuration: configuration
        ) { [weak self] result in
            switch result {
            case .failure(let error):
                break
            case .success(let paymentSheetFlowController):
             self?.paymentSheetFlowController = paymentSheetFlowController
            }
        }
        
        ================================================
        
        Please see below screenshot and we are using this code  for present screen
        
        paymentSheetFlowController?.presentPaymentOptions(from: self) {
       }
       
<img width="348" alt="Screenshot 2024-03-14 at 5 46 17 PM" src="https://github.com/stripe/stripe-ios/assets/25863052/928e980e-c66e-43e1-bff7-b50ca30abc01">

**Comment by porter-stripe** [comment]
Hi @ideal8173 thank you for reporting this! I have submitted a fix and it will be released in the next version of the SDK.

**Comment by ideal8173** [comment]
Thanks, We are waiting for next release version.

**Comment by porter-stripe** [comment]
Fixed in 23.25.1
