### ISSUE TITLE
Stripe Bug with V(23.25.0) on "Cancel" Button Click in PaymentSheet FlowController

### ISSUE THREAD

**Issue by ideal8173** [stripe/stripe-ios#3416]
Please help here 

Using SDK V(23.25.0) version

We are clicking on "Cancel", "Out Side Tap" and "Continue" Buttons in PaymentSheet FlowController. We have got same callback in all cases. 

When we have filling Card informations and click any of these buttons on "Cancel", "Out Side Tap" and "Continue", close PaymentSheet  and again re-open this payment sheet then showing all Card informations pre-filled.

No any card information fill And click on"Cancel" button, app crash on Cancel button Click:- 
StripePaymentSheet/PaymentSheetFlowController.swift:324: Fatal error: `confirmPayment` should only be called when `paymentOption` is not nil

==============================================================
By using this code:-

var paymentSheetFlowController: PaymentSheet.FlowController?

var configuration = PaymentSheet.Configuration()

let intentConfig = PaymentSheet.IntentConfiguration(
mode: .setup()
) { [weak self] paymentDetails, _, intentCreationCallback in
}

PaymentSheet.FlowController.create(
intentConfiguration: intentConfig,
configuration: configuration
) { [weak self] result in
switch result {
case .failure(let error):
break
case .success(let paymentSheetFlowController):
self?.paymentSheetFlowController = paymentSheetFlowController
}
}

================================================
    
   We are using this code  for present screen and click on buttons call back
    
    paymentSheetFlowController?.presentPaymentOptions(from: self) {
    
     // Get only single call back in all clicking "Cancel", "Out Side Tap" and "Continue" Buttons
     
     didTapSaveButton()
   }
   
   ### func didTapSaveButton() {
        paymentSheetFlowController?.confirm(from: self) { paymentResult in
          switch paymentResult {
          case .completed:
            // Setup completed - show a confirmation screen.
              break
          case .failed(let error):
            // PaymentSheet encountered an unrecoverable error. You can display the error to the user, log it, etc.
              break
          case .canceled:
            // Customer canceled - you should probably do nothing.
              break
          }
        }
      }
=============================================
 Please see below screenshot and 
   
<img width="348" alt="Screenshot 2024-03-14 at 5 46 17 PM" src="https://github.com/stripe/stripe-ios/assets/25863052/aee1e7dc-b7b6-4823-8ccb-320e38ecfc16">

**Comment by davidme-stripe** [comment]
Hello! Where are you calling `confirmPayment()`? It seems like you may be calling it when the payment information hasn't been added to PaymentSheet yet, which would not work.

And sorry for the delayed response: This GitHub Issues page is intended to report bugs with the SDK. For faster help, I'd recommend reaching out to [Stripe Support](https://support.stripe.com/) — they can provide live support for your integration. Thanks!
