### ISSUE TITLE
Stripe SDK support google pay ?

### ISSUE THREAD

**Issue by CodeBrewLabs7** [stripe/stripe-ios#3444]
## Is your feature request related to a problem? Please describe.
We want to do payment through google pay in our iOS device.

## Describe alternatives you've considered
Currently we successfully using google pay in our android device.

## Additional context
We want to do payment thorough google pay for our both android and iOS device.

**Comment by seanzhang-stripe** [comment]
Hi @CodeBrewLabs7 I'm afraid that Google Pay for payments isn't available for iOS devices.
