### ISSUE TITLE
[BUG] No such module 'StripePaymentSheet'

### ISSUE THREAD

**Issue by HandyappGroup** [stripe/stripe-ios#3447]
## Summary

I've tried to use StripePaymentSheet in my project but it doesnt recognize it and asks me to import, when i do that then i will see this message from xCode.
## iOS version

17.3
## Installation method

SPM
## SDK version

23.25.1

**Comment by seanzhang-stripe** [comment]
Hi @HandyappGroup Did you follow these [steps](https://docs.stripe.com/payments/accept-a-payment?platform=ios&mobile-ui=payment-element#setup-client-side) to add Stripe iOS SDK to your project? Make sure that you have added `StripePaymentSheet` product to [the target of your app](https://developer.apple.com/documentation/xcode/adding-package-dependencies-to-your-app).

**Comment by wooj-stripe** [comment]
Due to inactivity of this ticket, I will be optimistically closing this issue.
