### ISSUE TITLE
StripeiOS.zip does not contain card images

### ISSUE THREAD

**Issue by ryhart18** [stripe/stripe-ios#345]
When using the packaged Stripe framework for iOS found [here](https://github.com/stripe/stripe-ios/releases/tag/v7.0.2), no card images are displayed when using the `STPPaymentCardTextField` custom text field. This is because the framework does not include the card images.

The CocoaPods pod does include the required images.

**Comment by jflinter** [comment]
Hey @ryhart18! Apologies, this is one of the limitations of distributing a "fake" static framework like this. We'll look into a workaround in time for our next release. As you mentioned, in the meantime installing our SDK with a tool like Cocoapods or Carthage will prevent this issue.
