### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RupinderKaur16** [stripe/stripe-ios#3453]
## Summary
My team is integrating the stripe SDK for adding payment method solution and we are unable to update the text for "Pay" button. Our requirement is to use "Save" as the primary button instead of "Pay".

## Code to reproduce
Not applicable

## iOS version
15.0 and above

## Installation method
Not relevant to the issue reported

## SDK version
Version 23.26.0

**Comment by wooj-stripe** [comment]
Hi @RupinderKaur16 -

Thanks for reaching out. We have many UI's within our SDK, so I would like to verify what screen you're trying to update. Would you be able to provide a screenshot of what button you'd like to see saying "Save" instead of "Pay"?

**Comment by porter-stripe** [comment]
Hi @RupinderKaur16 we haven't heard back so I am going to close this issue. If you are using PaymentSheet you can configure the text on the primary button with `primaryButtonLabel`.
https://github.com/stripe/stripe-ios/blob/master/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheetConfiguration.swift#L112
