### ISSUE TITLE
Warnings in STPAPIClient.h

### ISSUE THREAD

**Issue by wanelo-pair** [stripe/stripe-ios#346]
Using Stripe (v7.0.2) with Cocoapods generates following warnings:

In file included from Pods/Headers/Private/Stripe/Stripe.h:9:
Pods/Headers/Private/Stripe/STPAPIClient.h:67:1: warning: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Wobjc-property-no-attribute]
@property (nonatomic, nonnull) NSOperationQueue *operationQueue;
^
Pods/Headers/Private/Stripe/STPAPIClient.h:67:1: warning: default property attribute 'assign' not appropriate for non-GC object [-Wobjc-property-no-attribute]
In file included from /Users/wanelo/workspace/ios-app/ios-app/wanelo-Prefix.pch:32:
In file included from Pods/Headers/Private/Stripe/Stripe.h:21:
Pods/Headers/Private/Stripe/STPPaymentCardTextField.h:250:1: warning: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Wobjc-property-no-attribute]
@property(nonatomic, readwrite, nonnull) STPCardParams *cardParams;
^
Pods/Headers/Private/Stripe/STPPaymentCardTextField.h:250:1: warning: default property attribute 'assign' not appropriate for non-GC object [-Wobjc-property-no-attribute]
Pods/Headers/Private/Stripe/STPPaymentCardTextField.h:252:1: warning: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Wobjc-property-no-attribute]
@property(nonatomic, readwrite, nullable) STPCardParams *card __attribute__((deprecated("This has been renamed to cardParams; use that instead.")));
^
Pods/Headers/Private/Stripe/STPPaymentCardTextField.h:252:1: warning: default property attribute 'assign' not appropriate for non-GC object [-Wobjc-property-no-attribute]
Pods/Headers/Private/Stripe/STPPaymentCardTextField.h:278:1: warning: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Wobjc-property-no-attribute]
@property(nonatomic, readwrite, nonnull) PTKCard *card;
^
Pods/Headers/Private/Stripe/STPPaymentCardTextField.h:278:1: warning: default property attribute 'assign' not appropriate for non-GC object [-Wobjc-property-no-attribute]
8 warnings generated.

**Comment by wanelo-pair** [comment]
@jflinter Hi Jack, do you think you will have a chance to check this sometime soon?

**Comment by benzguo** [comment]
@wanelo-pair I haven't been able to reproduce this yet on my end. We can just add the attributes, but I'm curious how our configurations differ – what's your compiler set to in Xcode? 

![screenshot 2016-06-21 13 01 30](https://cloud.githubusercontent.com/assets/894119/16238955/a9a503b0-37b0-11e6-99ba-ceefc1ef5837.png)

**Comment by atrohn** [comment]
Default compiler (Apple LLVM 7.1)

**Comment by benzguo** [comment]
ah, I was able to reproduce this by disabling ARC. thanks!

**Comment by atrohn** [comment]
@benzguo Thanks!
