### ISSUE TITLE
[BUG] Missing an expected key: 'NSPrivacyCollectedDataTypes' Stripe_StripeCore.bundle/PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by mihaicris-adoreme** [stripe/stripe-ios#3468]
I have this error while generating the Privacy Report in Xcode 15.3, Stripe 23.26.0
Missing an expected key: 'NSPrivacyCollectedDataTypes' Stripe_StripeCore.bundle/PrivacyInfo.xcprivacy

**Comment by davidme-stripe** [comment]
This is correct: StripeCore itself doesn't collect any data without use of the other frameworks. I'll investigate this, thanks for filing!

**Comment by porter-stripe** [comment]
Hi @mihaicris-adoreme this should be fixed in the latest version of the SDK, if you are still encountering this issue after upgrading, please re-open!

**Comment by daveluong** [comment]
@porter-stripe Thank you for the quick response. May I check if you guys have plan to support older version? We're still support iOS 12 so we need to be on StripeSDK `22.8.4`
