### ISSUE TITLE
Fix "This is an error in Swift 6" warnings

### ISSUE THREAD

**Issue by filippopassante** [stripe/stripe-ios#3509]
Is Stripe working on fixing "This is an error in Swift 6" type of warnings?

For instance, if you follow the steps at https://docs.stripe.com/payments/quickstart and enable complete strict concurrency checking in Xcode 15.3, you get many warnings in CheckoutViewController, the first being "Reference to class property 'defaultPublishableKey' is not concurrency-safe because it involves shared mutable state; this is an error in Swift 6", caused by the line `StripeAPI.defaultPublishableKey = "pk_test_51HNYvGL7qPFrjsUBKZYLMaWPav85CLd1BqZT9aJyCvwY9Ze15N0R1lzYgyehphIiFjCUz4dZcSs1y6XI0Og4aF3s00fekexikN"`, which I don't think I can solve.

**Comment by davidme-stripe** [comment]
Thanks for filing this! We do plan to fix these, tracking in: https://github.com/stripe/stripe-ios/issues/3324

**Comment by filippopassante** [comment]
I'm glad to hear that.

Maybe Stripe support should be informed about this, since they previously told me that they cannot make such guarantees.

I made sure to explain to them that the warnings that I'm getting let it be understood that the SDK won't work at all with Swift 6, to which they replied that I should consider other payment service providers.

In fact, I was implementing Adyen until I received your update.

**Comment by davidme-stripe** [comment]
I'm very sorry about that support experience, thanks for flagging it. We'll look into what went wrong. Our policy is to support every new version of Xcode before GA.

**Comment by BenShutt** [comment]
A workaround for now could be to add `@preconcurrency` to the import.
This is discussed in Apple's [Common Compiler Errors](https://www.swift.org/migration/documentation/swift-6-concurrency-migration-guide/commonproblems#Preconcurrency-Import).

Once the change is made, this should be removed.

```swift
@preconcurrency import StripePaymentSheet
```
