### ISSUE TITLE
[BUG] Couldn't find PrivacyInfo.xcprivacy in the StripePayments framework

### ISSUE THREAD

**Issue by command-not-found** [stripe/stripe-ios#3521]
## Summary
I downloaded the latest version of the SDK, but I couldn't find PrivacyInfo.xcprivacy in the StripePayments framework.

## iOS version
iOS 14

## Installation method
pod 'StripePaymentsUI', '~> 23.27.0'
pod 'StripePaymentSheet', '~> 23.27.0'

## SDK version
23.27.0

## Other information
<img width="1065" alt="image1" src="https://github.com/stripe/stripe-ios/assets/17892680/9a3a5c93-dac1-43ce-a3fc-41b498af745a">
![image2](https://github.com/stripe/stripe-ios/assets/17892680/5c983cbb-c25c-4ada-b67c-c6474c07abcc)

**Comment by porter-stripe** [comment]
@command-not-found thank you for reporting this, I have submitted a fix which will be released with our next SDK version.

**Comment by command-not-found** [comment]
@porter-stripe Thank you for your reply. May I ask when the next version will be? Apple requires it to be processed before May 1st.

**Comment by porter-stripe** [comment]
April 22 will be the next release.

**Comment by command-not-found** [comment]
Okay, thank you

**Comment by porter-stripe** [comment]
Hi, this has been fixed in https://github.com/stripe/stripe-ios/releases/tag/23.27.1!
