### ISSUE TITLE
[BUG] Cannot integrate stripe-iOS using SPM using Xcode 15.3

### ISSUE THREAD

**Issue by OJDee** [stripe/stripe-ios#3536]
## Summary
When attempting to archive app, at the point of checking out dependencies via SPM, the following error is produced and archive fails

```
xcodebuild: error: Could not resolve package dependencies:
  Dependencies could not be resolved because no versions of 'stripe-ios' match the requirement 23.27.1..<24.0.0 and root depends on 'stripe-ios' 23.27.1..<24.0.0.
```

Using Xcode-select 15.1, with exact same project and settings, the app is archived correctly

## Code to reproduce
Add stripe-iOS using SPM, with following properties:
Up to next major version 23.27.1 < 24.0.0

## Xcode version
Xcode 15.3

## Installation method
Swift Package Manager

**Comment by davidme-stripe** [comment]
Hello, thanks for filing! Not sure about this, but I'm seeing a [similar issue with other SPM packages](https://stackoverflow.com/questions/70975125/xcode-failed-to-resolve-dependency-firebase-googleappmeasurement-does-not-matc). Could you try setting a version number as shown there and see if it resolves the issue?

As another tip, try using https://github.com/stripe/stripe-ios-spm as your SPM URL: It should make your checkout process significantly faster.

**Comment by porter-stripe** [comment]
@OJDee if you are still experiencing this issue please re-open this issue with some more info! Thanks!

**Comment by AhmedAminFarid** [comment]
@OJDee @porter-stripe I have the same issue on Xcode 16, any advice?

**Comment by OJDee** [comment]
I changed to using the stripe-ios-spm repo which appears to work as expected.
