### ISSUE TITLE
[BUG] Crash when trying to pay with Apple Pay

### ISSUE THREAD

**Issue by hak-ioki** [stripe/stripe-ios#3537]
## Summary
When I try to pay anything with Apple Pay, the app crashes because of Stripe 3DS2.

## Code to reproduce
<img width="407" alt="image-1" src="https://github.com/stripe/stripe-ios/assets/155530524/0ba2411b-dd50-436b-91bd-02279283af63">
<img width="842" alt="image-2" src="https://github.com/stripe/stripe-ios/assets/155530524/2a6a79e9-653d-4948-b72e-d07919882635">

## iOS version
iOS 17.2 & iOS 17.4

## Installation method
SPM

## SDK version
3.27.1

## Other information
This problem only happens when I install the SDK via SPM. With Carthage installation, there was no problem.

**Comment by davidme-stripe** [comment]
Hello, thanks for filing! It seems like Tuist was [generating this file incorrectly](https://github.com/tuist/tuist/issues/5959). Try updating to the latest version of Tuist, [v4.4.0 or later](https://github.com/tuist/tuist/pull/5999).
