### ISSUE TITLE
XCode 15.3 unable to build on device

### ISSUE THREAD

**Issue by RushanB** [stripe/stripe-ios#3549]
## Summary
Able to build and run on simulator, but on device it keeps saying library not loaded

 ```
Library not loaded: @rpath/CaptureCore.framework/CaptureCore
  Referenced from: <86ED1679-C998-3378-B8CD-E6D368549409> /private/var/containers/Bundle/Application/7CBB2F91-307E-4CD8-A36A-899CAFF4DA13/ABCD.app/Frameworks/ABCD.framework/ABCD
  
  Reason: tried: '/Users/abcd/Library/Developer/Xcode/DerivedData/ABCD-glawfeexxlunkjdqtsoifnzacoot/Build/Products/Debug-iphoneos/PackageFrameworks/CaptureCore.framework/CaptureCore' (no such file), '/private/preboot/Cryptexes/OS/Users/abcd/Library/Developer/Xcode/DerivedData/ABCD-glawfeexxlunkjdqtsoifnzacoot/Build/Products/Debug-iphoneos/PackageFrameworks/CaptureCore.framework/CaptureCore' (no such file), '/private/var/containers/Bundle/Application/7CBB2F91-307E-4CD8-A36A-899CAFF4DA13/ABCD.app/Frameworks/CaptureCore.framework/CaptureCore' (no such file), '/private/var/containers/Bundle/Application/7CBB2F91-307E-4CD8-A36A-899CAFF4DA13/ABCD.app/Frameworks/ABCD.framework/Frameworks/CaptureCore.framework/CaptureCore' (no such file), '/Users/abcd/Library/Developer/Xcode/DerivedData/ABCD-glawfeexxlunkjdqtsoifnzacoot/Build/Products/Debug-iphoneos/PackageFrameworks/CaptureCore.framework/CaptureCore' (no such file),
```

## Code to reproduce
Just trying to build on device

## iOS version
17.4.1

## Installation method
Swift package manager

## SDK version
23.27.1

When I check the contents of PackageFramework folder, it is empty and the CaptureCore.framework is located in the folder level with all the other frameworks

**Comment by davidme-stripe** [comment]
Hello, thanks for filing this! Which framework are you trying to use? Is it StripeIdentity, or a payments-related framework?

**Comment by RushanB** [comment]
StripeIdentity framework

> davidme-stripe

**Comment by RushanB** [comment]
@davidme-stripe Also got this email from Apple when submitting a build to the app store

<img width="949" alt="image" src="https://github.com/stripe/stripe-ios/assets/16970644/47947507-832a-45b5-8a0e-cae360b027bf">

**Comment by mohit-kapadia-at-lirisoft** [comment]
Even I see this issue, but a different framework

**Comment by davidme-stripe** [comment]
Hi @RushanB, this dependency has been removed. Please try updating to version [23.27.6](https://github.com/stripe/stripe-ios/releases/tag/23.27.6). Thanks!
