### ISSUE TITLE
Prevent user from removing a card via stripe payment element

### ISSUE THREAD

**Issue by TYuan6** [stripe/stripe-ios#3552]
## Is your feature request related to a problem? Please describe.
Our team is integrating the stripe payment element. In the stripe payment element, user is able to remove a payment method.

## Describe the solution you'd like
I'm trying to figure out if there's a way to prevent users from deleting a specific card from the payment element. I was wondering if you know whether Stripe supports this feature, or whether there's a way to attach extra information to the card, such as additional labels or metadata, to prevent it from being deleted.

**Comment by davidme-stripe** [comment]
Hi @TYuan6, thanks for filing this! This isn't part of our public API today, but we'll consider the request for a future update.
