### ISSUE TITLE
Proximity Reader Token for Tap to Pay on iPhone

### ISSUE THREAD

**Issue by Alex-Farago** [stripe/stripe-ios#3575]
Hi! As I understand Stripe SDK wraps it's reader discovery concept around Tap to Pay on iPhone with delegation pattern. 

Would it be possible to get the ProximityReader token from the Stripe SDK? (https://developer.apple.com/documentation/proximityreader/paymentcardreader/token) 

Alternatively could you maybe expose at least 
`[func isAccountLinked(using: PaymentCardReader.Token) async throws -> Bool](https://developer.apple.com/documentation/proximityreader/paymentcardreader/isaccountlinked(using:))`

and 
`[func linkAccount(using: PaymentCardReader.Token) async throws](https://developer.apple.com/documentation/proximityreader/paymentcardreader/linkaccount(using:))
Presents a sheet for the merchant to accept Tap to Pay on iPhone’s Terms and Conditions on a device.`
?

Apple has a very neat API with async functions and event streams it would be easier for us to use it. Alternatively if you could provide an additional wrapper that wraps the Stripe SDK and provides 
isAccountLinked
linkAccount
prepare
... 
methods, that would also work.

**Comment by Alex-Farago** [comment]
This is also a question to the developer community if you are already using Stripe SDK for Tap to Pay on iPhone in your app and you already wrapped it in a structured concurrency API I would appreciate if you shared it.

**Comment by seanzhang-stripe** [comment]
Hi @Alex-Farago I believe your inquiry is related to Stripe Terminal iOS SDK, and we have a dedicated [Github repo](https://github.com/stripe/stripe-terminal-ios) for it.

I'd close this ticket, feel free to open another ticket in Stripe Terminal iOS SDK repo.

**Comment by mauescurraiosepayco** [comment]
Are Apple-certified providers the only ones who use the proximity reader framework? Or can iOS developers from companies not authorized by Apple use it?

**Comment by DvdMeneses** [comment]
@mauescurraiosepayco All good? You can use Tap to Pay on iPhone, but you need to request a specific entitlement from Apple. To use the ProximityReader framework directly, your company usually needs to be an authorized Payment Service Provider (PSP). If you are not authorized by Apple, you must use an SDK provided by a supported PSP (like Stripe Terminal) rather than accessing the framework directly
