### ISSUE TITLE
Example Objective C still use old version of iOS SDK.

### ISSUE THREAD

**Issue by giftdigital** [stripe/stripe-ios#360]
Hi, looks like you recently updated the version of IOS SDK to V8.0. But the code example (Objective C) on your githut still uses old version of IOS SDK. 

Also I found some inconsistency in your documentation. For example, "- retrieveCustomerSources:completion: " does not exist but "- retrieveCustomer:completion: " exists. 

Can you update your documentation and provide me with the latest App example code in Objective-C please? 

Siyang

**Comment by jflinter** [comment]
Hey there,

Thanks for noting the inconsistency on our docs page; we've gone and fixed it.

We're looking into adding additional example apps in the future, but right now I'd just recommend looking at our (documentation)[https://stripe.com/docs/mobile/ios] and (SDK reference)[http://stripe.github.io/stripe-ios/docs/index.html], both of which have code available in both Swift and Objective-C.
