### ISSUE TITLE
"Pay By Link" Stripe Payment Sheet Breaking SDK Payments Flow ** URGENT FIX NEEDED POTENTIALLY!

### ISSUE THREAD

**Issue by SMGLOBAL-ops** [stripe/stripe-ios#3628]
## Summary

**_"Pay by link" recent refactoring in 23.727.2 potentially causing breaking change in Stripe PaymentSheet "Success" state transition - PaymentSheet "Pay By Link". 

TLDR: 

I am seeing the "Pay By Link" Stripe Payment Sheet component show, **_even when disabled_** from the backend in the software I am building for physiotherapy clinics around London, on my frontend iOS SwiftUI application. This intermittently keeps happening, even though the Stripe Dashboard Payment Methods remain set the same, and the code for my StripePaymentManager has not been changed and this still sometimes occurs (showing "Pay By Link" and then not showing it on instances). 

<img width="1158" alt="Screenshot 2024-06-02 at 09 22 39" src="https://github.com/stripe/stripe-ios/assets/68763259/e7984bc3-9e0e-414b-9cae-daf8e35682fb">

<ins>**The real issue**

I am not 100% on this, but I can see the above might be causing the stripe SDK to think no payment method type has been provided, and hence blocks the execution of a successful payment.

**What potential SDK file could be causing this?**

**PaymentSheetUIKitAdditions.swift
line 77** - returns message suggesting no payment method is specified, even though one is (even hardcoded to ensure but no luck)

-> Payment execution shows as complete, and I weirdly get 200 response for "create-payment-intent" but not for following states for payment sheet completion i.e. "success" - and then warning message (yellow exclamation mark triangle) suggesting line 77 in the above mentioned file is causing the issue - suspecting various SDK patches keep changing things somewhere e.g. delegate refactoring_**

## Code to reproduce

```
 func preparePaymentSheet() {
        guard !isPaymentSheetInitialized else {
                   return
               }
        isLoading = true
        stripePaymentService.fetchStripeKey { [weak self] publishableKey, error in
            guard let self = self, let publishableKey = publishableKey else {
                // Handle error
                return
            }

            STPAPIClient.shared.publishableKey = publishableKey
            let postData: [String: Any] = ["paymentMethodType": "card", "currency": currency, "amount": amount]
            self.stripePaymentService.preparePaymentSheet(postData: postData) { clientSecret, error in
                guard let clientSecret = clientSecret else {
                    print("Error occured preparing the Stripe Payment Sheet!")
                    return
                }

                var configuration = PaymentSheet.Configuration()
                configuration.merchantDisplayName = "Some Merchant Name"
                configuration.defaultBillingDetails.address.country = "GB"
                configuration.paymentMethodOrder = ["card"] // ensures only card is used instead of e.g. 'pay by link' extension (for now...)

                DispatchQueue.main.async {
                    self.paymentSheet = PaymentSheet(paymentIntentClientSecret: clientSecret, configuration: configuration)
                    self.isLoading = false
                    self.isPaymentSheetInitialized = true
                }
            }
        }
    }
```

See latest patch version for PaymentSheet - think it's potentially buggy as seeing "Pay by Link" when not enabled and also Stripe logs show warning for failure to see correct payment method and thus this blocks execution of payment success!

## iOS version

iOS 17.1.2

## Installation method

From Xcode 15 Package URL entry (GitHub pull via Xcode functionality to add package)

## Other information

I'm an iOS developer for London Banks so familiar with payments implementations, and just spotted this issue today and couldn't for the life of me figure out why it was occurring. I noticed adding this line of code in my `StripePaymentManager` class: 

   `configuration.paymentMethodOrder = ["card"]` // ensures only card is used instead of e.g. 'pay by link' extension (for now...)
   
   fixed the issue of making the "Pay By Link" disappear (Note: I checked the Stripe Dashboard Payment Methods and it's also disabled from there via my connected API key in test mode).
   
   Hope I helped you guys debug this (if it is indeed a bug!)
   
   Best,

Saif.

**Comment by seanzhang-stripe** [comment]
Hi @SMGLOBAL-ops can you share with me the ID of the relevant PaymentIntent that you passed to PaymentSheet?

**Comment by SMGLOBAL-ops** [comment]
Hi Sean, thanks for the prompt response! 

Are you suggesting the PaymentIntent is not being properly created on my side? I am also currently suspecting it could be something as simple as adjusting an @EnvironmentObject injectable into the relevant payments views in the app, but I am receiving a "200 OK" from my backend code and it was previously working.

**Comment by seanzhang-stripe** [comment]
Hi @SMGLOBAL-ops  I'm more interested in knowing the [payment_method_types](https://docs.stripe.com/api/payment_intents/object#payment_intent_object-payment_method_types) associated with that PaymentIntent, and see if it includes `link`.

**Comment by SMGLOBAL-ops** [comment]
Hi, apologies for the delayed response on this!!! 

I assume the issue must be with the PaymentIntent creation due to a recent refactoring performed. Please close this ticket for now and if i am facing the same issue still I will make a new ticket including the payment intent - thank you :)
