### ISSUE TITLE
Description with release version

### ISSUE THREAD

**Issue by TofPlay** [stripe/stripe-ios#365]
Hi,
![image](https://cloud.githubusercontent.com/assets/1082222/16678105/49bfbff6-44dc-11e6-8d34-22589ad1a912.png)
Usually with a release we add a description

**Comment by TofPlay** [comment]
Without any description we don't know what is new with a new release, what is obsolete or do we have to be careful.  ☹️

**Comment by jflinter** [comment]
Hey @TofPlay - just have a look at https://github.com/stripe/stripe-ios/blob/master/CHANGELOG .
