### ISSUE TITLE
[BUG] finViewController function return always nil in PaymentSheetPresent Coordinator of PaymentSheet+SwiftUI.swift

### ISSUE THREAD

**Issue by YeshApp** [stripe/stripe-ios#3657]
## Summary
Hello,

Until last week my app presented the paymentSheet without any problem, but now when I try to present it the loader remains in a deadlock since the findViewController function never manages to find the view where to present the paymentSheet always returning nil.

PaymentSheet+SwiftUI
`class Coordinator {

            var parent: PaymentSheetPresenter
            let view = UIView()
            var presented: Bool {
                didSet {
                    switch (oldValue, presented) {
                    case (false, false):
                        break
                    case (false, true):
                        guard let viewController = findViewController(for: view) else {
                            parent.presented = false
                            return
                        }
                        presentPaymentSheet(on: viewController)
                    case (true, false):
                        guard let viewController = findViewController(for: view) else {
                            parent.presented = true
                            return
                        }
                        forciblyDismissPaymentSheet(from: viewController)
                    case (true, true):
                        break
                    }
                }
            }`

## Code to reproduce
// The view where should appear the PaymentSheet

`struct TicketsDetailView: View {
    @Environment(\.presentationMode) var presentation
    
    @ObservedObject var userInfo: UserInfoViewModel
    @StateObject private var stripeViewModel: StripePaymentSheetViewModel
    @StateObject private var viewModel: TicketsDetailViewModel
    
    @State private var shineAnimation: Bool = false
    
    @State private var sheetHeight: CGFloat = .zero
    @State private var scrollOffset: CGPoint = .zero
    @State private var headerVisibleRatio: CGFloat = 1
    @State private var presentPaymentSheet: Bool = false
    
    private let headerHeight: CGFloat = 10
    
    init(userInfo: UserInfoViewModel,
         event: Binding<EventModel>, 
         ticket: Binding<UserTicketModel>
    ) {
        self.userInfo = userInfo
        
        _viewModel = StateObject<TicketsDetailViewModel>(
            wrappedValue: TicketsDetailViewModel(
                user: userInfo.user,
                event: event.wrappedValue,
                ticket: ticket.wrappedValue
            )
        )
        
        _stripeViewModel = StateObject<StripePaymentSheetViewModel>(
            wrappedValue: StripePaymentSheetViewModel()
        )
    }
    
    var body: some View {
        NavigationView {
            ZStack {
                Color.black.ignoresSafeArea()
                
                ScrollViewWithStickyHeader(header: scrollViewHeader,
                                           headerHeight: headerHeight,
                                           onScroll: handleScrollOffset) {
                    VStack(spacing: 8) {
                        ticketDetailCard
                        cancellationPolicy
                    }
                    .scrollTargetLayout()
                }
            
                bottomCancelView.disabled(viewModel.isBooking || stripeViewModel.isLoading)
                
                if viewModel.isBooking || stripeViewModel.isLoading {
                    loader
                }
            }
            .disabled(stripeViewModel.isPresentedPayment || viewModel.isBooking || stripeViewModel.isLoading)
            .yeshAlert(alertContent: $viewModel.alertContent, isPresented: $viewModel.showAlert)
            .toolbar(.hidden, for: .tabBar)
            .toolbar {
                ToolbarItem(placement: .topBarLeading) {
                    toolbarLeading
                }
                
                ToolbarItem(placement: .topBarTrailing) {
                    toolbarTrailing
                }
            }
            .onChange(of: viewModel.isCancelled) { _, _ in
                viewModel.objectWillChange.send()
                presentation.wrappedValue.dismiss()
            }
            .sheet(isPresented: $viewModel.shouldPresentScannedSheet, onDismiss: {
                viewModel.objectWillChange.send()
                presentation.wrappedValue.dismiss()
            }) {
                ConfirmScannedView(event: $viewModel.event, sheetHeight: $sheetHeight)
                    .presentationDetents([.height(sheetHeight)])
                    .presentationDragIndicator(.visible)
            }
            .onReceive(viewModel.$ticket) { ticket in
                if !stripeViewModel.isLoading {
                    showPaymentSheetIfNeeded(ticket)
                }
            }
            .paymentSheet(
                isPresented: $stripeViewModel.isPresentedPayment,
                paymentSheet: stripeViewModel.paymentSheet,
                onCompletion: viewModel.onCompletionPaymentSheet
            )
        }
        .preferredColorScheme(.dark)
        .navigationBarBackButtonHidden(true)
    }
    
    private func showPaymentSheetIfNeeded(_ ticket: UserTicketModel) {
        let isScanned = ticket.isScanned
        let isNotPayed = isScanned && !ticket.isPaymentCompleted
        let isShowingPaymentSheet = !stripeViewModel.isLoading && stripeViewModel.isPresentedPayment
        
        if viewModel.isFREETicket && isNotPayed {
            viewModel.onCompletionPaymentSheet(result: .completed)
        } else if isNotPayed || !isScanned && isShowingPaymentSheet {
            stripeViewModel.isLoading = true
            stripeViewModel.preparePaymentSheet(
                user: userInfo.user,
                ticketSelected: viewModel.eventTicket
            )
        }
    }`

// The view model responsable to manage stripe actions
`import FirebaseFirestore
import StripePaymentSheet
import SwiftUI

@MainActor
final class StripePaymentSheetViewModel: ObservableObject {
    @Published var isLoading: Bool = false
    @Published var isPresentedPayment: Bool = false
    
    @Published var paymentSheet: PaymentSheet = .init(paymentIntentClientSecret: "",
                                                      configuration: .init())
    var checkoutSessionModel: CheckoutSessionModel = .empty
    
    private var configuration: PaymentSheet.Configuration = .init()
    private var checkoutSessionListener: ListenerRegistration?
    
    init() {
        setupPayementSheetAppearance()
    }
    
    func setupPayementSheetAppearance() {
        configuration.appearance.font.sizeScaleFactor = 1.15
        configuration.appearance.colors.primary = .white
        configuration.appearance.colors.text = .white
        configuration.appearance.colors.icon = .white
        configuration.appearance.colors.textSecondary = .white
        configuration.appearance.colors.background = .secondaryYesh
        configuration.appearance.colors.componentBackground = .primaryYesh
        configuration.appearance.colors.componentText = .white
        configuration.appearance.colors.componentPlaceholderText = .davysGrey
        configuration.appearance.colors.componentDivider = .davysGrey
        configuration.appearance.colors.componentBorder = .davysGrey
        configuration.allowsDelayedPaymentMethods = true
        configuration.merchantDisplayName = "Yesh SRL"
        configuration.returnURL = "yeshapp://stripe-redirect"
        configuration.applePay = .init(merchantId: "merchant.com.yesh", merchantCountryCode: "IT")
        configuration.savePaymentMethodOptInBehavior = .requiresOptIn
    }
    
    func preparePaymentSheet(user: YeshUser, ticketSelected: Ticket?) {
        guard let amount = ticketSelected?.price.getAmountInCents(), amount > 0 else {
            CustomLog.log("TICKET PRICE IS NOT VALID OR ZERO", logType: .error)
            return
        }
        
        FirestoreService.createCheckoutSession(
            uid: user.uid ?? "",
            amount: amount,
            sellerId: "acct_1OzFY2FhoS2hiCva"
        ) { [weak self] documentReference in
            if let documentReference {
                self?.setCheckoutSessionObserver(user: user, documentReference: documentReference)
            } else {
                CustomLog.log("ERROR TO CREATE CHECKOUT SESSION", logType: .error)
            }
        }
    }
    
    func preparePaymentSheet(user: YeshUser, totalAmount: Int) {
        guard let amount = totalAmount.description.getAmountInCents(), amount > 0 else {
            CustomLog.log("TICKET PRICE IS NOT VALID OR ZERO", logType: .error)
            return
        }
        
        FirestoreService.createCheckoutSession(
            uid: user.uid ?? "",
            amount: amount,
            sellerId: "acct_1OzFY2FhoS2hiCva"
        ) { [weak self] documentReference in
            if let documentReference {
                self?.setCheckoutSessionObserver(user: user, documentReference: documentReference)
            } else {
                CustomLog.log("ERROR TO CREATE CHECKOUT SESSION", logType: .error)
            }
        }
    }
    
    private func setCheckoutSessionObserver(user: YeshUser, documentReference: DocumentReference) {
        checkoutSessionListener = FirestoreService.observeCheckoutSessionUpdates(
            uid: user.uid ?? "",
            sellerId: "acct_1OzFY2FhoS2hiCva",
            documentReference: documentReference
        ) { [weak self] checkoutSessionModel in
            self?.updatePayment(user: user, with: checkoutSessionModel)
        }
    }
    
    private func updatePayment(user: YeshUser, with model: CheckoutSessionModel?) {
        guard let model else {
            CustomLog.log("ERROR TO CREATE CHECKOUT SESSION", logType: .error)
            return
        }
        
        checkoutSessionModel = model
        CustomLog.log("CHECKOUT SESSION UPDATE \(model)", logType: .debug)
        
        setupPayementSheetAppearance()
        setupConfiguration(user: user, checkoutSessionModel: model)
        
        initializePaymentSheet(checkoutSessionModel: model)
    }
    
    private func setupConfiguration(user: YeshUser, checkoutSessionModel: CheckoutSessionModel) {
        configuration.defaultBillingDetails.email = user.email
        configuration.defaultBillingDetails.name = user.fullname
        configuration.defaultBillingDetails.phone = user.phoneNumber
        configuration.billingDetailsCollectionConfiguration.name = .always
        configuration.billingDetailsCollectionConfiguration.email = .always
        configuration.billingDetailsCollectionConfiguration.phone = .always
        configuration.billingDetailsCollectionConfiguration.attachDefaultsToPaymentMethod = true
        configuration.customer = .init(id: checkoutSessionModel.customer ?? "",
                                       ephemeralKeySecret: checkoutSessionModel.ephemeralKeySecret ?? "")
    }
    
    private func initializePaymentSheet(checkoutSessionModel: CheckoutSessionModel) {
        paymentSheet = PaymentSheet(
            paymentIntentClientSecret: checkoutSessionModel.paymentIntentClientSecret ?? "",
            configuration: configuration
        )
        
        isLoading = false
        isPresentedPayment = true
        checkoutSessionListener?.remove()
    }
    
    func resetPayment() {
        isLoading = false
        isPresentedPayment = false
        checkoutSessionListener?.remove()
    }
    
    deinit {
        checkoutSessionListener?.remove()
    }
}`
## iOS version
18.0 Beta

## Installation method
xCode - Debug Mode

## SDK version
23.27.2

**Comment by porter-stripe** [comment]
@YeshApp Hi, thank you for reporting this. We were able to reproduce the issue on iOS 18 beta and have a fix ready for the next release, which is happening today.

**Comment by porter-stripe** [comment]
This is fixed in the latest version, please let us know if you continue to encounter this issue: https://github.com/stripe/stripe-ios/releases/tag/23.27.3

**Comment by YeshApp** [comment]
Hey @porter-stripe ,
Thanks for resolving the fix so quickly, seems working now!
