### ISSUE TITLE
[BUG] PayPal set up button disabled until billing address entered for card

### ISSUE THREAD

**Issue by jvanderwee** [stripe/stripe-ios#3683]
## Summary

When selecting PayPal in the payment sheet the "Set up" button is disabled, blocking the user from paying with PayPal. It does not enable until you select to use card, enter a billing address, then switch back to PayPal.

## iOS version

17.5.1

## Installation method

SPM

## SDK version

23.27.4 - we have reverted to 23.27.2 for now 

## Other information

![CleanShot 2024-06-19 at 19 54 12](https://github.com/stripe/stripe-ios/assets/3587922/eab8281d-85ce-4e90-bba6-483c077484d2)

**Comment by porter-stripe** [comment]
@jvanderwee Thanks for reporting this, we're working on a fix. I'll update back when it's released.

**Comment by porter-stripe** [comment]
Hi @jvanderwee this has been resolved in our latest release, https://github.com/stripe/stripe-ios/releases/tag/23.27.5
