### ISSUE TITLE
[BUG] Fix IDR Formatting

### ISSUE THREAD

**Issue by doganaltinbas** [stripe/stripe-ios#3747]
## Summary

When processing payments in Indonesian Rupiah (IDR), the SDK adds two extra zeros to the displayed amount. For example, an amount of 186,332 IDR is shown as 18,633,200 IDR at the checkout button as it can be seen below. 

![checkout_button](https://github.com/stripe/stripe-ios/assets/5463479/77355e5d-c3c5-4b2f-a010-ec20ee506332)

## iOS version
iOS 17.5

## Installation method
SPM

## SDK version
23.27.5

**Comment by yuki-stripe** [comment]
Hi @doganaltinbas, thank you for the report. Can you provide a PaymentIntent id with 186,332 IDR as the amount and currency?

**Comment by yuki-stripe** [comment]
I believe you're actually providing an amount of 186,332,200 IDR on the PaymentIntent. If so, based on my research we should indeed show "IDR 186,332" in that case.

**Comment by doganaltinbas** [comment]
Hi @yuki-stripe,
In test environment, you can check this PaymentIntent id: pi_3PYivxHrTWtWHJGF0u48xwRu

**Comment by yuki-stripe** [comment]
@doganaltinbas This is fixed in 23.28.0!

**Comment by doganaltinbas** [comment]
Thanks! @yuki-stripe
