### ISSUE TITLE
[BUG]  https://api.stripe.com/v1/setup_intents/seti_1P...../confirm

### ISSUE THREAD

**Issue by vbarskov** [stripe/stripe-ios#3754]
## Summary
https://api.stripe.com/v1/setup_intents/seti_1P...../confirm) is not responding and fail on timeout

## Code to reproduce
stripeService.stripeAddCardPreSetup {[weak self] (preSetup) in
            let cardInfo = STPPaymentMethodCardParams(cardSourceParams: card)
            let billingDetails = STPPaymentMethodBillingDetails()
            let paymentMethodParams = STPPaymentMethodParams(card: cardInfo, billingDetails: billingDetails, metadata: nil)
            
            let setupIntentParams = STPSetupIntentConfirmParams(clientSecret: preSetup?.clientSecret ?? "")
            setupIntentParams.paymentMethodParams = paymentMethodParams
            
            let paymentHandler = STPPaymentHandler.shared()
            paymentHandler.confirmSetupIntent(setupIntentParams, with: self!) ....
}

## iOS version
17.4

## Installation method
Cocoapods 

## SDK version
- Stripe (23.27.6):
    - StripeApplePay (= 23.27.6)
    - StripeCore (= 23.27.6)
    - StripePayments (= 23.27.6)
    - StripePaymentsUI (= 23.27.6)
    - StripeUICore (= 23.27.6)
  - StripeApplePay (23.27.6):
    - StripeCore (= 23.27.6)
  - StripeCore (23.27.6)
  - StripePayments (23.27.6):
    - StripeCore (= 23.27.6)
    - StripePayments/Stripe3DS2 (= 23.27.6)
  - StripePayments/Stripe3DS2 (23.27.6):
    - StripeCore (= 23.27.6)
  - StripePaymentSheet (23.27.6):
    - StripeApplePay (= 23.27.6)
    - StripeCore (= 23.27.6)
    - StripePayments (= 23.27.6)
    - StripePaymentsUI (= 23.27.6)
  - StripePaymentsUI (23.27.6):
    - StripeCore (= 23.27.6)
    - StripePayments (= 23.27.6)
    - StripeUICore (= 23.27.6)
  - StripeUICore (23.27.6):
    - StripeCore (= 23.27.6)

**Comment by sfriedman-stripe** [comment]
Hi @vbarskov, for help troubleshooting an integration issue like this, I'd love to point you to our 24/7 support on [our Discord](https://stripe.com/go/developer-chat), where we have engineers ready to help you with this.
