### ISSUE TITLE
3DS Support

### ISSUE THREAD

**Issue by billinghamj** [stripe/stripe-ios#376]
Hi Jack :) 

Just wondering whether you're planning on integrating support for 3D Secure into the iOS SDK - similar to how Stripe.js works.

At present, 3DS is quite painful to use with iOS:
- you can't navigate directly to the `redirect_url` in a `SFSafariViewController` because it requires a POST
- you can't provide an app scheme URL as the `return_url`

If it's not currently on the roadmap, I'd love it if it was considered!

**Comment by jflinter** [comment]
Hey James - short answer, yes, this is something we'll be working on in the next few months. Thanks for the feedback!

**Comment by billinghamj** [comment]
Nice - looking forward to it 👍🏼

As an aside, we're currently handling the first issue by using a data URI containing a tiny bit of HTML to do the form post.

**Comment by billinghamj** [comment]
Actually just to quickly follow up - for anyone who is searching for a solution and comes across this:

The data URI trick does not work in SFSafariViewController. It will not allow you to provide a data URI as the URL. It does work with WKWebView, but then you lose out on the cookies, card details, etc. which are all provided via Safari.

**Comment by billinghamj** [comment]
@jflinter Any idea where this sits on the roadmap? We've had more problems with using SFSafariViewController :(

**Comment by jack-stripe** [comment]
@billinghamj - we're working on it now, but don't have a timeline for when it'll be done, i'm afraid.

**Comment by lucasgerard** [comment]
Hey guys, any update on that? 3DS is a key feature for fraud prevention, and the current flow has too much frictions... We'd love to have the same fluidity on the 3DS secure flow than on the rest of your payment flow!

Please keep us posted :) Thanks!
