### ISSUE TITLE
[HELP] A required parameter was invalid or missing. Collecting a PaymentMethod for a Paymentintent 'on_behalf_of' a Connected Account requires providing that Connected Account's ID in 'SCPLocalMobileConnectionConfigu- ration

### ISSUE THREAD

**Issue by Maks273** [stripe/stripe-ios#3797]
<img width="940" alt="Screenshot 2024-07-18 at 09 15 17" src="https://github.com/user-attachments/assets/1b35bdb9-be61-4943-bddb-59039aa4b8f1">
I keep getting this error on Terminal.shared.collectPaymentMethod(paymentIntent).

I assume it's API issue. Any suggetions please?

**Comment by seanzhang-stripe** [comment]
Hi @Maks273 your inquiry is related to Stripe terminal iOS SDK, and we have another github repo for this. 

I'll close this ticket. Can you create a new one in Stripe terminal iOS SDK [repo](https://github.com/stripe/stripe-terminal-ios) ?
