### ISSUE TITLE
[BUG] Klarna, after pay payments fails due to return Url

### ISSUE THREAD

**Issue by vishwa-drip** [stripe/stripe-ios#3810]
## Summary
We are integrating additional payment types like klarna, after pay, affirm, cash app. 
While accepting payments, payment handler requires a returnURL, else we get below error.

Stripe payment failed-Optional(Error Domain=com.stripe.lib Code=50 "There was an unexpected error -- try again in a few seconds" UserInfo={com.stripe.lib:StripeRequestIDKey=req_454AjWj9R3nJXD, com.stripe.lib:StripeErrorCodeKey=, com.stripe.lib:ErrorMessageKey=You must provide a `return_url` when confirming a PaymentIntent with the payment method type afterpay_clearpay., com.stripe.lib:StripeErrorTypeKey=invalid_request_error, NSLocalizedDescription=There was an unexpected error -- try again in a few seconds})

Due to the returnURL, user experience is not great in the application, post payment browser doesn't close automatically. User has to manually close the browser.

## Code to reproduce
        let paymentIntentParams = STPPaymentIntentParams(clientSecret: "client_secret")
            paymentIntentParams.paymentMethodParams = params
            paymentIntentParams.returnURL = returnUrl
        let paymentHandler = STPPaymentHandler.shared()
        paymentHandler.confirmPayment(paymentIntentParams, with: self) { [weak self] (status, paymentIntent, error) in }

## iOS version
iOS 17.x

## Installation method
SPM

## SDK version
23.28.1

## Other information
We have our android application as well, in android SDK returnURL is not mandatory, post payment browser is closed automatically.

**Comment by porter-stripe** [comment]
Hi @vishwa-drip, this is expected behavior and an integration difference from Android. These payment method types do require a return URL. 
Example docs: https://docs.stripe.com/payments/cash-app-pay/accept-a-payment?web-or-mobile=mobile&payments-ui-type=ios#confirm-cash-app-pay-payment

**Comment by davidme-stripe** [comment]
Note that the browser *should* close automatically if you implement the `return_url` as shown in the docs using `StripeAPI.handleURLCallback`. Let us know if that isn't working. Thanks!

**Comment by vishwa-drip** [comment]
@davidme-stripe The solution worked thank you.
