### ISSUE TITLE
[BUG] Error on using PaymentMethodMessagingView in ios

### ISSUE THREAD

**Issue by vishwa-drip** [stripe/stripe-ios#3812]
## Summary
We are integrating additional payment methods like Afterpay and klarna, and would like to show promotional message. 
In our checkout flow we wanted to show promotional message as per the documentation. 
/// A view that displays promotional text and images for payment methods like Afterpay and Klarna. For example, "As low as 4 interest-free payments of $9.75". When tapped, this view presents a full-screen SFSafariViewController to the customer with additional information about the payment methods being displayed. 

We have followed the sample demo code but we are getting below error, in our application and sample demo code both are showing same error as below. 

▿ StripeError 
▿ apiError : StripeAPIError 
- type : StripeCore.StripeAPIError.ErrorType.invalidRequestError 
- code : nil 
- docUrl : nil 
▿ message : Optional 
- some : "Unrecognized request URL (GET: /content). Please see https://stripe.com/docs or we can help at https://support.stripe.com/." 
- param : nil 
▿ statusCode : Optional 
- some : 404 
▿ _allResponseFieldsStorage : Optional 
- some : 2 fields 

## Code to reproduce
        let config = PaymentMethodMessagingView.Configuration(
            paymentMethods: [.afterpayClearpay, .klarna],
            currency: "USD",
            amount: 2499
        )
        PaymentMethodMessagingView.create(configuration: config) { [weak self] result in
            switch result {
            case .failure(let error):
                print(error)
            case .success(let paymentMethodMessagingView):
                paymentMethodMessagingView.adjustsFontForContentSizeCategory = true
                // Add a border
                paymentMethodMessagingView.layer.borderWidth = 0.5
                paymentMethodMessagingView.layer.borderColor = UIColor.lightGray.cgColor
                paymentMethodMessagingView.layer.cornerRadius = 5

                self?.addPaymentMethodMessagingView(paymentMethodMessagingView)
            }
        }

## iOS version
iOS 17.x

## Installation method
SPM

## SDK version
23.28.1

**Comment by davidme-stripe** [comment]
Sorry, but this class isn't available publicly at this time — we've gated it behind an `@_spi` flag for now. We'll register your interest in it for a future update. Thanks!

**Comment by porter-stripe** [comment]
Closing this out based on @davidme-stripe!
