### ISSUE TITLE
[BUG][SwiftUI] PaymentSheet Present Coordinator for the case (true, false) that calls forciblyDismissPaymentSheet has controller.presentedViewController as? BottomSheetViewController always nil

### ISSUE THREAD

**Issue by YeshApp** [stripe/stripe-ios#3822]
## Summary
When I present the paymentSheet in SwiftUI by setting the isPresent parameter to true the PaymentSheet is presented correctly, but when perhaps closing the paymentSheet always resetting the binding of the isPresented variable to false, the PaymentSheet Present Coordinator for the case (true, false) calls forciblyDismissPaymentSheet has controller.presentedViewController as? BottomSheetViewController is always nil not closing the paymentSheet even though isPresented is setted to false and therefore the paymentSheet remains open but should be closed.

## Code to reproduce
        
 `
// TicketsDetailView.swift
.paymentSheet(
                isPresented: $stripeViewModel.isPresentedPayment,
                paymentSheet: stripeViewModel.paymentSheet,
                onCompletion: viewModel.onCompletionPaymentSheet
          )
`

The variable below is true and then the paymentSheet is open correctly
`$stripeViewModel.isPresentedPayment`

but if i reset `$stripeViewModel.isPresentedPayment` to false forcing the paymentSheet to be close, then in the Coordinator of `PaymentSheetPresenter` for the case `case (true, false)` which call `forciblyDismissPaymentSheet(from: viewController)`   the variable `if let bsvc` is always nil and then doesn't close the paymentSheet

`
func forciblyDismissPaymentSheet(from controller: UIViewController) {
                if let bsvc = controller.presentedViewController as? BottomSheetViewController {
                    bsvc.didTapOrSwipeToDismiss()
                }
            }
`

`class Coordinator {

            var parent: PaymentSheetPresenter
            let view = UIView()
            var presented: Bool {
                didSet {
                    switch (oldValue, presented) {
                    case (false, false):
                        break
                    case (false, true):
                        guard let viewController = findViewController(for: view) else {
                            parent.presented = false
                            return
                        }
                        presentPaymentSheet(on: viewController)
                    case (true, false):
                        guard let viewController = findViewController(for: view) else {
                            parent.presented = true
                            return
                        }
                        forciblyDismissPaymentSheet(from: viewController)
                    case (true, true):
                        break
                    }
                }
            }

            init(parent: PaymentSheetPresenter) {
                self.parent = parent
                self.presented = parent.presented
            }

            func presentPaymentSheet(on controller: UIViewController) {
                let presenter = findViewControllerPresenter(from: controller)

                parent.paymentSheet?.present(from: presenter) { (result: PaymentSheetResult) in
                    self.parent.presented = false
                    self.parent.onCompletion(result)
                }
            }

            func forciblyDismissPaymentSheet(from controller: UIViewController) {
                if let bsvc = controller.presentedViewController as? BottomSheetViewController {
                    bsvc.didTapOrSwipeToDismiss()
                }
            }
        }
`

## iOS version
iOS 18.0

## Installation method
SDK iOS

## SDK version
SPM - https://github.com/stripe/stripe-ios-spm

**Comment by yuki-stripe** [comment]
Hello @YeshApp, it seems like the view's view controller isn't the one presenting PaymentSheet.  Do your views change while PaymentSheet is presented?  Could you provide some sample code to reproduce?  My own testing shows that setting `isPresented=false` dismisses the sheet as expected.

**Comment by YeshApp** [comment]
Hello @yuki-stripe ,
Thank you for you reply on this matter.

Yeah i am still having problem.

When the PaymentSheet is presented and then listening to this firestore variable

`$stripeViewModel.isPresentedPayment`

when it become false is not closing automatically the PaymentSheet.

Precisely when i receive an update from backend which updates my tickets with isScanned false is calling a method which call this nsippet of code:

`.onReceive(viewModel.$ticket) { ticket in
               showPaymentSheetIfNeeded(ticket)
            }`
            
            then first guard in the showPaymentSheetIfNeeded function

`guard ticket.isScanned else {
            stripeViewModel.resetPayment()
            return
        }`
        
        `func resetPayment() {
        isLoading = false
        isPresentedPayment = false
        checkoutSessionListener?.remove()
    }`

**Comment by yuki-stripe** [comment]
I would breakpoint in https://github.com/stripe/stripe-ios/blob/80baf90513c3d5d16217712c341c447d4a199451/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheet%2BSwiftUI.swift#L309 and https://github.com/stripe/stripe-ios/blob/80baf90513c3d5d16217712c341c447d4a199451/StripePaymentSheet/StripePaymentSheet/Source/PaymentSheet/PaymentSheet%2BSwiftUI.swift#L315 and compare the values of `viewController` to pinpoint the reason - my guess the second one is different or perhaps nil.  A video of the problem would also help confirm what you're seeing.

If you can provide a fully reproducible example then I can debug myself!

**Comment by YeshApp** [comment]
yes exactly, the second one called in forciblyDismissPaymentSheet is nil and plus i noticed that both view controller are different.

Attached you can find the video. Thank you in advance.

https://github.com/user-attachments/assets/7b8e32d8-dc72-4666-8138-084f2a008798

**Comment by yuki-stripe** [comment]
Thanks @YeshApp!  Interesting, I _think_ this should fix the issue https://github.com/stripe/stripe-ios/pull/3930 - can you try pointing your Stripe dependency to `yuki/fix-forcibly-dismiss-swiftui` and see if that fixes it?

**Comment by YeshApp** [comment]
Is giving me an error, I am using SPM

<img width="573" alt="Screenshot 2024-08-13 at 23 16 52" src="https://github.com/user-attachments/assets/4e8c9083-f152-43df-a85b-bd2005804575">

**Comment by yuki-stripe** [comment]
Ah right, our SPM repo is https://github.com/stripe/stripe-ios-spm, not this repo. You could try temporarily switching the repo to https://github.com/stripe/stripe-ios and using the branch, I think that should work.

Hopefully the fix will ship in next Monday's release so you can also wait until then.

**Comment by YeshApp** [comment]
SPM doesn't found any repo related to  https://github.com/stripe/stripe-ios

**Comment by YeshApp** [comment]
Podfile as well, not working

`pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git', :branch => 'yuki/fix-forcibly-dismiss-swiftui'`

[!] Error installing Stripe
[!] Failed to download 'Stripe': [!] /usr/bin/git clone https://github.com/stripe/stripe-ios.git /var/folders/xj/pd8cvw514cx74nzy_shdmpzw0000gp/T/d20240815-2866-grndht --template=

Cloning into '/var/folders/xj/pd8cvw514cx74nzy_shdmpzw0000gp/T/d20240815-2866-grndht'...
error: RPC failed; curl 18 Transferred a partial file
error: 4103 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by yuki-stripe** [comment]
@YeshApp Sorry for the trouble, but this is now available in the latest SDK version (23.29.2). Please let me know if that fixes the issue!

**Comment by YeshApp** [comment]
Hey @yuki-stripe seems to be solved. Thanks a lot for your support as always. 💯
