### ISSUE TITLE
Ability to hide the Email row in STPAddCardViewController

### ISSUE THREAD

**Issue by mthole** [stripe/stripe-ios#386]
I'd like to be able to hide the "Email" row in the STPAddCardViewController, etc. I know that I can use a STPUserInformation to prefill the email, but I'd like to remove it from the UI altogether. Is this possible without going down the full-custom approach?

**Comment by benzguo** [comment]
@mthole – the email row allows users to securely autofill their card details if they've ever made a purchase from another app that uses `STPAddCardViewController` or from Stripe Checkout on the web [0]. 

If you'd like to disable this functionality, you can set `smsAutofillDisabled = true` on your `STPPaymentConfiguration`.

[0] https://stripe.com/docs/mobile/ios/custom#sms-autofill

**Comment by mthole** [comment]
I didn't realize the email was tied to the autofill. That makes sense, thanks @benzguo.

**Comment by jspenc72** [comment]
Is this still necessary to hide the email field in the latest release?

**Comment by bg-stripe** [comment]
@jspenc72 nope! the SMS autofill feature was removed in [v11.0](https://github.com/stripe/stripe-ios/tree/v11.0.0), so STPAddCardVC no longer has an email field.
