### ISSUE TITLE
Cannot set payment currency for Apple Pay

### ISSUE THREAD

**Issue by mattmcneeney** [stripe/stripe-ios#387]
## Summary

When using STPPaymentContext as described [here](https://stripe.com/docs/mobile/ios), setting the payment currency does not change the currency displayed when the Apple Pay dialog is shown (`US$` is always shown).

## Code to reproduce

Set the currency to GBP:
```swift
self.paymentContext.paymentCurrency = "GBP"
```

- Run the app (e.g. the example app)
- Select "Apple Pay"
- When `self.paymentContext.requestPayment()` is called, `US$` is shown as the currency.

## iOS version

9.3.3

## Installation method

Cocoapods

## SDK version

8.0.3

## Other information

That's it! FYI I emailed this issue to your support email yesterday, but thought this may be a better channel for technical help.

**Comment by benzguo** [comment]
@mattmcneeney thanks for the bug report! we'll be shipping a new SDK version with the fix [0] soon (tomorrow at the latest).

[0] https://github.com/stripe/stripe-ios/commit/9f7ba6846d0034de5f2156fdf649e0caeea74a0d

**Comment by mattmcneeney** [comment]
@benzguo Many thanks for the quick response and fix.
