### ISSUE TITLE
Apple Pay icon rejected by App Store review

### ISSUE THREAD

**Issue by billinghamj** [stripe/stripe-ios#393]
## Summary

Using the included Apple Pay icons will cause App Store rejection.

## Code to reproduce

Apple review feedback was as follows:

> We noticed that the Apple Pay button in your app has been significantly revised, which does not comply with the [Apple Pay Identity Guidelines](https://developer.apple.com/apple-pay/Apple-Pay-Identity-Guidelines.pdf).
> 
> We've attached screenshot(s) for your reference.

Screenshot: http://imgur.com/d0vu1ue

## iOS version

iOS 9

## Installation method

CocoaPods

## SDK version

v8.0.3

## Other information

Examples of how other apps show Apple Pay:

- http://imgur.com/FmBwQl4
- http://imgur.com/1R1apQD

**Comment by bdorfman** [comment]
I just released SDK version 8.0.5. If you call `[STPImageLibrary applePayCardImage]' in this version, it should now return to you the official Apple-sanctioned Apple Pay mark. Please let us know if you have any more trouble!
