### ISSUE TITLE
[BUG] Stripe: framework requires SDK 'iphoneos17.0' which is not installed.

### ISSUE THREAD

**Issue by cmydur** [stripe/stripe-ios#3939]
## Summary
I'm trying to create a binding for iOS manually using this library and I have Xcode  Version 15.4 (15F31d) and iOS 17.5, however I get an error this SDK requires "Stripe: framework requires SDK 'iphoneos17.0' which is not installed. You may need a newer Xcode." 

I'm trying to create binding library for dotnet MAUI using sharpie and this is the command I use

sharpie bind \
 -sdk iphoneos \
 -output ./ \
 -namespace StripeIosBinding \
 -framework ./Stripe.xcframework/ios-arm64_x86_64-simulator/Stripe.framework

**Comment by porter-stripe** [comment]
Hi @cmydur this appears to not be an issue with the Stripe SDK but rather sharpie or the configuration being used. Here is a similar issue reported in the repo: https://github.com/xamarin/xamarin-macios/issues/15922

**Comment by cmydur** [comment]
Thank, however do you have support for iphonoeos17.5 ?
