### ISSUE TITLE
[REQUEST] Publish 22.8.4-Privacy to SPM lightweight repo

### ISSUE THREAD

**Issue by vijaytholpadi** [stripe/stripe-ios#3958]
## Summary

Related to https://github.com/stripe/stripe-ios/issues/3409

There was a release made on top of 22.8.4 for privacy manifest requirements and tagged as [22.8.4-Privacy](https://github.com/stripe/stripe-ios/issues/3409#issuecomment-2195270645).

However this release is missing from the lightweight SPM repo ([stripe-ios-spm](https://github.com/stripe/stripe-ios-spm))

This cause our SPM checkout of stripe to be 1.3GB in size which is not-feasible to cache on the CI.

Kindly help tag `22.8.4-privacy` release on the [stripe-ios-spm](https://github.com/stripe/stripe-ios-spm) repo too.

**Comment by vijaytholpadi** [comment]
@porter-stripe Need your help on this pls 🙇

**Comment by porter-stripe** [comment]
Hi @vijaytholpadi, I'll look into this but it may not be possible with how the repo is setup.

In the meantime can you share why you are not able to upgrade to the latest?

**Comment by porter-stripe** [comment]
Hi, I have published 22.8.4-privacy to the lightweight SPM repo. Let me know if you hit any issues, as a courtesy warning, we won't be supporting this version much longer, Xcode 16 is coming soon!
https://github.com/stripe/stripe-ios-spm/releases/tag/22.8.4-privacy
