### ISSUE TITLE
STPAddCardViewController :Cannot change right bar button text color OR spinning color

### ISSUE THREAD

**Issue by kandarpesw** [stripe/stripe-ios#399]
## Summary

I can change text color of left bar item but cannot change right bar button color to match my app's theme color.
Way to set color.
UINavigationBar.appearance().backgroundColor = UIColor.UCAColor.AppThemeTxtColor
        UINavigationBar.appearance().barTintColor = UIColor.UCAColor.AppThemeColor
        UIBarButtonItem.appearance().tintColor = UIColor.UCAColor.AppThemeTxtColor
        UINavigationBar.appearance().titleTextAttributes = [NSForegroundColorAttributeName : UIColor.UCAColor.AppThemeTxtColor]

## Code to reproduce

Just open STPAddCardViewController and add card details. You can find text color of right bar button item is blue (Default color of ios).

## iOS version

IOs version is 9.3.2

## Installation method

"using Cocoapods"

## SDK version

using latest version of Stripe on Cocoapods

## Other information
STPAddCardViewController also gives an error when pressing phone number switch is on - off.
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 1 from section 3 which only contains 1 rows before the update'

**Comment by benzguo** [comment]
@kandarpesw You'll need to use `STPTheme` to change the look and feel of the SDK's UI elements. (More info [here](https://stripe.com/docs/mobile/ios#theming)).

I haven't been able to reproduce the phone number switch crash you mentioned – would you mind sending us an example project demonstrating the crash? (You can email the zipped project to bg@stripe.com).
