### ISSUE TITLE
Error in adding StripeCore in AppDelegate xcode

### ISSUE THREAD

**Issue by leoginnayre13** [stripe/stripe-ios#4006]
After adding "pod 'StripePaymentsUI' in Podfile, and adding "@import StripeCore;" in Appdelegate, this error shows up:

"Use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules"

<img width="925" alt="Screenshot 2024-09-11 at 6 07 37 PM" src="https://github.com/user-attachments/assets/f02d2e75-e130-4b82-b68a-878acbd1fc94">

Reference of Stripe Documentation: https://docs.stripe.com/payments/cash-app-pay/set-up-payment?web-or-mobile=mobile&payments-ui-type=ios

**Comment by davidme-stripe** [comment]
Thanks for filing this! Do you have `-fno-modules` anywhere in your Xcode Settings or Podfile? 

This setting in your target should also be set to `Yes`: ![CleanShot 2024-09-17 at 11 31 26@2x](https://github.com/user-attachments/assets/c8e8bbb8-b122-4532-8762-91a5cd3139ae)

**Comment by porter-stripe** [comment]
Closing this out as stale, if this is still an issue please re-open with further details. Thanks!
