### ISSUE TITLE
[BUG] Unable to archive release version on command line using SPM on latest MacOS and Xcode versions

### ISSUE THREAD

**Issue by OJDee** [stripe/stripe-ios#4102]
## Summary
Using Xcode 16 and MacOS Sequoia 15.0 , archiving from command line returns error

```
xcodebuild: error: Could not resolve package dependencies:
  Failed to resolve dependencies Dependencies could not be resolved because no versions of 'stripe-ios' match the requirement 23.31.0 and root depends on 'stripe-ios' 23.31.0.
```

Exactly the same project archives and exports to a working app fine on Xcode 15 and MacOS Ventura 13.6.

Build and run in Xcode works 

## Code to reproduce

Archive command:

`/Applications/Xcode_16.app/Contents/Developer/usr/bin/xcodebuild clean archive -project ******.xcodeproj -scheme ***** -sdk iphoneos -configuration Release DEVELOPMENT_TEAM=***** CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER=****** -derivedDataPath DerivedData -archivePath "build/*****.xcarchive"`

## iOS version

N/A

## Installation method

SPM

## SDK version

 23.31.0

**Comment by porter-stripe** [comment]
👋  Are you using the https://github.com/stripe/stripe-ios-spm/ to include the Stripe package?

**Comment by OJDee** [comment]
Yes I am now and it resolved issue - thanks
