### ISSUE TITLE
XCode UI testing and STPPaymentCardTextField

### ISSUE THREAD

**Issue by lukeivers** [stripe/stripe-ios#411]
## Summary

Because STPPaymentCardTextField is not, in fact, an actual text field, I can't use the standard XC UI test recording methodology, nor find it via the textFields property of an XCUIElement

## Code to reproduce

This code would work for a regular textField, but does not for STPPaymentCardTextField:
```
let app = XCUIApplication()
let textField = app.textFields["ENTER CARD"]
textField.tap()
textField.typeText("4242424242424242")
```

Firstly, it can't find a text field named that, because it isn't a real text field.
Secondly, even if I use other code to select the appropriate control, such as:
```
app.scrollViews.otherElements.containingType(.Image, identifier:"add-card-icon").childrenMatchingType(.Other).elementBoundByIndex(1)
```

When I try to have to use typeText, it says:
```
Neither element nor any descendant has keyboard focus on secureTextField
```

## iOS version

XCode 7.3.1, iOS version 9.3

## Installation method

CocoaPods

## SDK version

8.0.4

## Other information

The only solution I've found that works is by double tapping on the element once it is selected via the code above, and then paste in a string.  This becomes even more unworkable for typing into the CVC field, as the default doubleTap() location for an object is it's center-point.

Here is the code I ended up using for testing an STPPaymentCardTextField:
```
let textField = app.scrollViews.otherElements.containingType(.Image, identifier:"add-card-icon").childrenMatchingType(.Other).elementBoundByIndex(1)
textField.tap()
        
UIPasteboard.generalPasteboard().string = "4242424242424242"
textField.doubleTap()
app.menuItems["Paste"].tap()

UIPasteboard.generalPasteboard().string = "1220"
textField.doubleTap()
app.menuItems["Paste"].tap()

UIPasteboard.generalPasteboard().string = "555"
textField.coordinateWithNormalizedOffset(CGVectorMake(0.8, 0.5)).doubleTap()
app.menuItems["Paste"].tap()
```

**Comment by benzguo** [comment]
Hey @lukeivers – I've added accessibility labels to `STPPaymentCardTextField` in #413 (on master, but not yet in a published release), which you should be able to use to access fields in UI tests:

```
let numberField = app.textFields["card number"]
numberField.tap()
numberField.enterText("4242424242424242")
```

**Comment by stanfeldman** [comment]
Whoa guys, I spent an hour trying to type into the card field in a UI test until I found this. 
You should add this to the docs.
