### ISSUE TITLE
Use of undeclared identifier 'STPPaymentConfiguration'

### ISSUE THREAD

**Issue by asifalikhokhar** [stripe/stripe-ios#420]
## Summary

I have installed Stripe using cocoapods, and it gives me following error:
**Use of undeclared identifier 'STPPaymentConfiguration'**
## Code to reproduce

@import Stripe;

and following lines in didFinishLaunching method

[[STPPaymentConfiguration sharedConfiguration] setPublishableKey:@"pk_test_5eSJ5lHrSXft5hi373TX038m"];
## Installation method

Cocoapods
## SDK version

Installing Stripe (7.0.2)

**Comment by bdorfman** [comment]
It looks like you are running an out of date version of the Stripe SDK. The current version is 8.0.5, released just a few minutes ago. Can you try updating to the newest version? If your Podfile is currently pinned to 7.x versions, you should be able to change the relevant line to just `pod 'Stripe'` or `pod 'Stripe', '~> 8.0'`, and then `pod install` to have Cocoapods download and update your project.

**Comment by bdorfman** [comment]
Closing this issue for now. Please reopen if you continue you to have this error after updating to version 8!

**Comment by ktgriffiSFU** [comment]
I found cocoa pods found the version  7.05. Is it really version 8?

**Comment by joeydong-stripe** [comment]
hi @aayush-ios,

I just double checked to be safe and our current published version is 12.1.2: https://cocoapods.org/?q=on%3Aios%20stripe

Can you try cleaning your build products so that we can start off fresh? (Xcode > Product > Clean) I find this is often necessary when switching between versions of any pod.
