### ISSUE TITLE
[Feature] iOS Subscription not currently compliance

### ISSUE THREAD

**Issue by unxavi** [stripe/stripe-ios#4202]
## Is your feature request related to a problem? Please describe.
Yes, we are currently having compliance issues with the AppStore

We are selling service outside of the app and therefore using Stripe as a payment option with Apple Pay. After more than 2 years sending updates to the store we got rejected today, Apple Reviewer message says the following:

Upon further review, we found that your submission does not comply with the following guidelines:

> Guideline 4.9 - Design - Apple Pay
> 
> The app uses Apple Pay to offer recurring payments but does not provide the necessary information to the user prior to the sale of goods or services.
> 
> 
> Specifically, the app does not include the following:
> 
> 
> - How to cancel
> 
> 
> Additionally, the payment sheet does not:
> 
> 
> - The length of the renewal term and the fact that it will continue until canceled
> 
> 
> Next Steps
> 
> 
> To resolve this issue, please revise the app to include the missing information.
> 
> 
> Resources
> 
> 
> For more information on [Apple Pay](https://developer.apple.com/documentation/passkit/apple_pay), please review the Apple Pay documentation.

In our case is a subscription that renews automatically every 4 weeks using stripe and they complaint that on the pay button there is no frequency

## Describe the solution you'd like
We should be compliance with apple comments on the payment sheet for subscriptions

**Comment by joyceqin-stripe** [comment]
@unxavi I'm sorry that you're experiencing difficulties. You can set [paymentSummaryItems](https://stripe.dev/stripe-ios/stripepaymentsheet/documentation/stripepaymentsheet/paymentsheet/applepayconfiguration/paymentsummaryitems) in your [Apple Pay configuration ](https://stripe.dev/stripe-ios/stripepaymentsheet/documentation/stripepaymentsheet/paymentsheet/applepayconfiguration) to display subscription information in compliance with Apple's policy. If you have any issues implementing this, I'd love to point you to our support channel on [our Discord](https://stripe.com/go/developer-chat), where we have engineers ready to help you 24/5. Thank you!
