### ISSUE TITLE
[BUG] Cannot add payment method in CustomerSheet on iOS 18

### ISSUE THREAD

**Issue by csyke00** [stripe/stripe-ios#4213]
## Summary
I have added a CustomerSheet for managing and selecting saved payment methods. When the sheet is opened, the customer's saved payment methods are correctly fetched and saved payment methods can be deleted. However, when attempting to add a new card, the new card is not created and no error displays in the UI. An error appears in the logs as follows: 

Calling -viewDidAppear: directly on a view controller is not supported, and may result in out-of-order callbacks and other inconsistent behavior. Use the -beginAppearanceTransition:animated: and -endAppearanceTransition APIs on UIViewController to manually drive appearance callbacks instead. Make a symbolic breakpoint at UIViewControllerAlertForAppearanceCallbackMisuse to catch this in the debugger. View controller: <STP_Internal_SavedPaymentMethodsCollectionViewController: 0x102030000>

There is an additional log before this error which suggests the setup intent was successful, but confirming in the dashboard, the payment method is not created and attached to the customer.

LOG ANALYTICS: stripeios.paymenthandler.confirm.finished - [(key: "status", value: "succeeded"), (key: "payment_method_type", value: "card"), (key: "intent_id", value: "seti_1QGPKvFKKJ5EQslyvkY7Lbkz")]

## Code to reproduce
```swift
import StripePaymentSheet

struct PaymentMethodSelectorView: View {
    @State private var isPresented = false
    @State private var customerSheet: CustomerSheet
    @State private var stripeCustomerAdapter: StripeCustomerAdapter

    init() {
        // omitted - initialize customer adapter and customer sheet 
    }

    var body: some View {
        Button {
            isPresented.toggle()
        } label: {
            // omitted 
        }
        .customerSheet(isPresented: $isPresented, customerSheet: customerSheet, onCompletion: onCompletion)
    }
}
```

## iOS version
18

## Installation method
Swift package manager

## SDK version
23.32.0

**Comment by joyceqin-stripe** [comment]
Hi @csyke00 , in order for us to better assist you with this integration issue, I'd love to point you to our support channel on [our Discord](https://stripe.com/go/developer-chat), where we have engineers ready to help you 24/5. Thank you!

**Comment by csyke00** [comment]
Hi @joyceqin-stripe, I actually posted on the Discord channel earlier today and I was directed to file my issue as a bug.

**Comment by joyceqin-stripe** [comment]
Hi @csyke00, I'm sorry about that! I didn't realize. Let me look into this issue, and I'll get back to you when I know more. Again, sorry for the inconvenience!

**Comment by csyke00** [comment]
No worries - thank you very much!

**Comment by wooj-stripe** [comment]
Hi, we did some investigation and it looks like the UIKit error you are seeing is unrelated to this problem.  It seems that you are not including the `customer_id` parameter when creating the setup Intent, which explains why the payment method isn't being attached the customer. See documentation [here](https://docs.stripe.com/elements/customer-sheet?platform=ios&mobile-customer-session=legacy-customer-ephemeral-key#ios-add-endpoints).

**Comment by wooj-stripe** [comment]
Optimistically closing this issue, but feel free to re-open if you have additional questions regarding this issue.
