### ISSUE TITLE
[BUG] After dismiss PaymentSheet, the UI breaks down

### ISSUE THREAD

**Issue by maxhartung** [stripe/stripe-ios#4243]
## Summary
After dismiss of PaymentSheet using SwiftUI or UIKit, my navigationController/UITabBarController goes crazy...What I mean by that ? 

I try to go back but now there is no animation of my navigation controller and now the whole app is without padding 

## Code to reproduce

`paymentSheet.present(from: UIApplication.shared.visibleViewController!, completion: { result in
                            self.viewModel.onPaymentCompletion(result: result)
                        })`

OR

`.paymentSheet(isPresented: , paymentSheet:, onCompletion:  -> )`

Both give the same results inside my app

## iOS version
iOS 18.1

## Installation method
SPM

## SDK version
24

## Other information
My app has the following navigation structure: UITabBarController -> UINavigationController -> UIHostingController with native SwiftUI (this is where I present the Payment Sheet)

The Payment Sheet is working great without issues but after is dismissed (doesn't matter if's successful payment or close it by X button), my app doesn't have any padding on UINavigationBar.

**Comment by DrHazemAli** [comment]
I think i've addressed a similar bug like this here #4246

**Comment by jp-vekta** [comment]
I just ran into this exact same issue after implementing the payment sheet. As you described @maxhartung, the padding is gone and all the animations have ceased to work.

**Comment by plevetsky** [comment]
I encountered a similar issue when presenting the payment sheet from a View Controller within a Navigation Controller. Opening the payment sheet somehow interferes with the view layouts. Everything works as expecting when downgrading to version 23.32.0.

**Comment by stokkeAtMonta** [comment]
Also encountered this issue. After dismissing the payment sheet the UI breaks completely. What @plevetsky suggested worked for me. Just a shame I have to downgrade.. would be nice to get this fixed 👍

**Comment by haojin2020** [comment]
Same issue on the SDK version 24.0.1

**Comment by porter-stripe** [comment]
Hi all, thank you for bringing this to our attention. We have shipped a new version of the SDK [24.0.2](https://github.com/stripe/stripe-ios/releases/tag/24.0.2) which resolves this issue.
