### ISSUE TITLE
[BUG]  Stripe Card Scanning Fails to Detect RuPay Cards with '60' Prefix

### ISSUE THREAD

**Issue by shilpeshsimform** [stripe/stripe-ios#4253]
## Summary
We’re using StripeCardScan for card scanning in our app but are unable to detect RuPay cards that have the prefix '60'.

## Code to reproduce
Use the card scanning feature from StripeCardScan.
## iOS version
iOS 18.1

## Installation method
Carthage

## SDK version
23.29.0

## Other information
The issue is reproducible using the scanning feature in the CardImageVerification example.

**Comment by seanzhang-stripe** [comment]
Hi @shilpeshsimform RuPay isn't one of the supported card brands. Kindly refer to this [page](https://docs.stripe.com/payments/cards#supported-card-brands) for the list of card brands that Stripe supports.

**Comment by shilpeshsimform** [comment]
Hello @seanzhang-stripe Thanks for the update
 Is it supported in Android,Can you please let me know when it will be supported for iOS.
