### ISSUE TITLE
Localize feature on v8.0.5 replaced localization file in current project

### ISSUE THREAD

**Issue by mthuong** [stripe/stripe-ios#429]
## Summary

Upgrade Stripe to v8.0.5 on current project already have localization string file
Actually the Localization string was replaced by the localization file on Stripe resouce
## Installation method

Use CocoaPods to integrate Stripe

Get back on version 8.0.4 and worked fine

**Comment by bdorfman** [comment]
Sorry about this. Working on a fix now and will push a new update ASAP.

**Comment by bdorfman** [comment]
I just released version 8.0.6 which should fix this issue. Please reopen if you have any further problems!

**Comment by tranngoclinh88** [comment]
Still not fixed in version 8.0.6
It replaced my localization.strings file in my project.

**Comment by bdorfman** [comment]
@tranngoclinh88 Hmm, what does your Podfile look like? I have changed the podspec for 8.0.6 to create a Stripe.bundle resources bundle instead of copying all the files into the root of the integrated app. On my own Cocoapods test apps this resolves the problem. Maybe you can also try running Clean in your Xcode project and rebuilding?

**Comment by tranngoclinh88** [comment]
@bdorfman 
I cleared all pods and re-install.
All localization.strings still in folder **Resources>Localizations**, not in **Stripe.bundle**
Does not have any folder name ** Stripe.bundle** in Pod folder.

**Comment by tranngoclinh88** [comment]
Sorry @bdorfman.
After clear all pods and re-install. It worked.
Thanks!

**Comment by bdorfman** [comment]
Great! Sorry for all the trouble with 8.0.5, please let us know if you have any further difficulties and we'll try to get it straightened out as soon as possible!
