### ISSUE TITLE
Payment Information Entered in PaymentSheet.FlowController Does Not Appear as Saved Payment Method for the Customer

### ISSUE THREAD

**Issue by aomathwift** [stripe/stripe-ios#4315]
## Summary

I am currently migrating from Basic Integration to Mobile Payment Element.
In the process, I use `PaymentSheet.FlowController` to collect payment methods in the setup flow. 
I’ve encountered an issue in my implementation and would like to seek advice.

After displaying the bottom sheet via `PaymentSheet.FlowController.presentPaymentOptions`, I enter new card details and press the "Continue" button. Then, I tap the payment button and call PaymentSheet.FlowController.confirm, which triggers the intentCreationCallback. At this point, the payment method selected is the card that was just entered in the bottom sheet.

However, if I reopen the bottom sheet before tapping the payment button, the payment information I entered earlier does not appear as a saved payment method for the customer.

What additional configuration is needed to ensure that the entered payment information is immediately added to the customer’s saved payment methods list? Or is this the intended behavior?

For reference, I have already configured the Customer ID and the ephemeral key’s client secret as follows to enable the saved payment methods for the customer:

```swift
var configuration = PaymentSheet.Configuration()
configuration.customer = .init(id: customerId, ephemeralKeySecret: customerEphemeralKeySecret)
```

## Code to reproduce

1. Present the the bottom sheet to enter payment information
2. Enter new card number and press the "Continue" button
3. Reopen the closed bottom sheet
4. The card information entered earlier is not displayed in the list

## iOS version
iOS18

## Installation method
cocoapods

## SDK version
23.32.0

**Comment by seanzhang-stripe** [comment]
Hi @aomathwift I'm unable to reproduce the problem. Can you share with me an sample iOS project so that I can run and replicate?

**Comment by aomathwift** [comment]
Hi @seanzhang-stripe , thank you for your reply.
Since this issue is occurring in a real product, it is difficult to share the exact code as is. Instead, I am sharing simplified code that reproduces the issue. Could you please take a look at this?

```Swift
final class CheckoutViewController: UIViewController {
    var flowController: PaymentSheet.FlowController?

    // Called when the `Payment Method` button is pressed
    func presentPaymentSheet() {
        let customerID = getCustomerIDFromMyServer()
        let ephemeralKeySecret = getEphemeralKeySecretFromMyServer()

        let intentConfig = PaymentSheet.IntentConfiguration(
            mode: .setup(currency: "JPY")
        ) { [weak self] _, _, intentCreationCallback in
            self?.handleConfirm(intentCreationCallback)
        }
        var configuration = PaymentSheet.Configuration()
        configuration.customer = .init(id: customerID, ephemeralKeySecret: ephemeralKeySecret)

        PaymentSheet.FlowController.create(
            intentConfiguration: intentConfig,
            configuration: configuration
        ) { [weak self] result in
            switch result {
            case .failure(let error):
                print(error)
            case let .success(paymentSheetFlowController):
                self?.flowController = paymentSheetFlowController
                self?.flowController.presentPaymentOptions(from: self)
            }
        }
    }
    
    // Called when the `Buy` button is pressed
    func presentConfirm() {
        if let flowController {
            flowController.confirm(from: self) { result in
                switch result {
                case .completed:
                    print("completed")
                case .failed(let error):
                    print(error)
                case .canceled:
                    print("canceled")
                }
            }
        }
    }

    private func handleConfirm(_ intentCreationCallback: @escaping (Result<String, Error>) -> Void) {
        let setupIntentSecret: String = getSetupIntentSecretFromMyServer()
        intentCreationCallback(.success(setupIntentSecret))
    }
}
```

This code was implemented following the guide below.
https://docs.stripe.com/payments/accept-a-payment-deferred?platform=ios&type=setup&integration=paymentsheet-flowcontroller

**Comment by aomathwift** [comment]
I see. I now understand that this is the intended behavior.
I will review the payment flow in my app to address this issue. 
Thank you for your support.
