### ISSUE TITLE
Can't use currency with STPAddCardViewController

### ISSUE THREAD

**Issue by jacobrharris** [stripe/stripe-ios#439]
## Summary

I'm using STPAddCardViewController for iOS. I can generate a token for a card, but because we're setting up managed accounts, I need to pass in the currency type (https://stripe.com/docs/api#create_card_token-card-currency). I don't see a way to do this using STPAddCardViewController.

## Installation method

CocoaPods

## SDK version

Stripe (8.0.6)

**Comment by jflinter** [comment]
@jacobrharris, thanks for bringing this up! I've just fixed this on the master branch, `STPAddCardViewController` now has a `managedAccountCurrency` property. Let me know if there's anything else you need here.
