### ISSUE TITLE
Wrong CVC validation for AMX cards 

### ISSUE THREAD

**Issue by PeterMosaad** [stripe/stripe-ios#440]
To make it easier to diagnose your issue, please fill out the following:

## Summary

In Class _STPCardValidator_ method _validationStateForCVC: cardBrand:_
There is an issue that it could validate an AMX card with only 3 digits, which is incorrect, as AMX cards has 4 digits CVC.
Cause of that issue is that method minCVCLength returns 3 for all credit card types, 
For AMX it should return 4.

## Code to reproduce
STPCardValidationState cvcValidation = [STPCardValidator validationStateForCVC:card.cvc cardBrand:STPCardBrandAmex];
NSAssert(cvcValidation != STPCardValidationStateIncomplete, @"3 digits CVC for AMX cards Should be Incomplete")

If possible, please include a brief piece of code (or ideally, a link to an example project) demonstrating the problem you're having.
STPCardValidationState cvcValidation = [STPCardValidator validationStateForCVC:card.cvc cardBrand:STPCardBrandAmex];
NSAssert(cvcValidation != STPCardValidationStateIncomplete, @"3 digits CVC for AMX cards Should be Incomplete")

## iOS version
All
## Installation method
Cocoapods
## SDK version
Latest from Cocoapods

## Other information
I think to solve this, 
In STPCardValidator change method minCVCLength to be:
+(NSUInteger)minCVCLengthForCardBrand:(STPCardBrand)brand {
    switch (brand) {
        case STPCardBrandAmex:
        case STPCardBrandUnknown:
            return 4;
        default:
            return 3;
    }
}
*Or I assume* that all Credit card types has the same CVC length so no need to max and min CVC length and just one method 

 +(NSUInteger)CVCLengthForCardBrand:(STPCardBrand)brand {
    switch (brand) {
        case STPCardBrandAmex:
        case STPCardBrandUnknown:
            return 4;
        default:
            return 3;
    }
}

and use it everywhere.

Thanks

**Comment by jflinter** [comment]
Hey there @PeterMosaad,

This is actually a common misconception about American Express cards - while the majority of them have 4-digit CVCs, there are several types of amex card that have a 3-digit CVC. Many amex cards also have a 3-digit "CID" printed on the front, which also works for verification purposes. As such we have to be slightly ambiguous in our validation.

Thanks for raising though!
