### ISSUE TITLE
County field in billing information is confusing in many locales

### ISSUE THREAD

**Issue by sadlerjw** [stripe/stripe-ios#444]
## Summary

In Canada (where I live) we expect to see "Province" where the "County" field currently is. (If the address is American, it correctly uses "State".)  Although I have no experience with international addresses, according to [Wikipedia](https://en.wikipedia.org/wiki/Address_(geography)#Mailing_address_format_by_country) there are many locales that don't have an equivalent to the "County" field.

I'm not sure what the "most correct" fix here is. While I'd like to see Canadian addresses use "Province" instead of "County", I understand that you may not want to implement a case-by-case exception list. (I think an eventual ideal solution might be providing a plist or something with address configuration values for each country.) 

I think making the field optional for some locales might be a good start?

## SDK version

`8.0.6` via Cocoapods

**Comment by jflinter** [comment]
Hey @sadlerjw!
Better localization is something we're actively working on for our next release. We should have something for you here in the next week or two. Sorry for the trouble!

**Comment by sadlerjw** [comment]
Great to hear, thanks!

**Comment by benzguo** [comment]
Hey @sadlerjw – we shipped a fix for this (#448) in the latest version of the SDK, [8.0.7](https://github.com/stripe/stripe-ios/releases/tag/v8.0.7). Thanks for reporting the issue!

**Comment by bdorfman** [comment]
To be clear, #448 just fixes the problem where the field was required. Better localization for things like State/County/Province labels are still on the roadmap, but we don't have an exact timeline for you at this moment.
