### ISSUE TITLE
Localize missing in Add Card VC

### ISSUE THREAD

**Issue by davidhilario** [stripe/stripe-ios#458]
To make it easier to diagnose your issue, please fill out the following:

Two Strings are hardcoded "Card" and "Billing Address". I'm sure it will be and easy fix! :) 

File:  STPAddCardViewController.m
Line 611 and 614

## Installation method

POD

## SDK version

8.0.7

Thx alot for the great work!
David

**Comment by bdorfman** [comment]
Ah, good catch, thanks! I'll make sure these get localized.

**Comment by bdorfman** [comment]
The strings in question have been marked for localization. Changes should be in the next release (https://github.com/stripe/stripe-ios/pull/488) Thanks again for pointing this out!
