### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by technoj** [stripe/stripe-ios#46]
Can you add support for iOS's newest programming language - swift. It comes out in October and I would like to have it in my app when iOS 8 comes out.

**Comment by cartickn** [comment]
@watsonbox thanks for the suggestion! I am trying to run your sample project but getting "No Such Module Stripe" while trying to "import Stripe" into one the Swift class files. I have the latest Stripe library installed through Cocoapods and have the Objective-C Bridging Header updated with the import statements for Stripe.h file etc. Not sure what I am missing.

**Comment by watsonbox** [comment]
@cartickn If you can link an example project I'll take a look and try to point you in the right direction.

**Comment by cartickn** [comment]
@watsonbox Really appreciate the quick response. I created a sample project with the minimal requirement to import Stripe into Swift project, to keep things simple. I can reproduce the "No such module Stripe" error.

Here is the link to the sample.

https://github.com/cartickn/Stripe-SwiftSample

Thanks for your time on this!!

**Comment by watsonbox** [comment]
@cartickn See my [commit](https://github.com/cartickn/Stripe-SwiftSample/commit/980e8a765cd8735bd05a74e8f23b29194da9dcfc) fixing your project.  The two build errors were due to ApplePay not being [integrated](https://stripe.com/docs/mobile/ios#applepay).  Everything Swift-related seems to be working just fine - I see no module errors as you had indicated.

![screen shot 2015-03-16 at 10 28 24](https://cloud.githubusercontent.com/assets/17737/6663778/32766c1e-cbca-11e4-82c6-36e7479d3d46.png)

**Comment by watsonbox** [comment]
@cartickn Note: it's possible that you have an issue with iOS 8.2 support.  I used iOS 8.1 for these tests.  If that's the case then you should probably open another issue.

**Comment by ElliotCambo** [comment]
Hi guys i have this issue as well. i have created the bridging header and have added the needed import statement 

But still seem to be getting the error No such module Stripe in the swift files. 

Its odd as when i hover over the import stripe declaration while holding command i can see the public methods the stripe framework/module exposes, so clearly xcode knows about the module/framework but it isnt picking it up at compile time, so odd. Any suggestions. I am compiling for iOS 9 if that helps at all
<img width="405" alt="screen shot 2017-04-18 at 00 53 43" src="https://cloud.githubusercontent.com/assets/5942626/25109040/00896e2e-23d2-11e7-9552-3c441cf7db93.png">

**Comment by bdorfman-stripe** [comment]
Hi @ElliotCambo,

If your error is at compile time, it may be that the Stripe framework is not located in the correct spot based on your framework search path. How did you integrate Stripe? Cocoapods?

I recommend writing in to support@stripe.com, they can help you with integration problems with the SDK. The SDK does work with Swift and we even bundle a Swift example app, so hopefully they can get you sorted out.
