### ISSUE TITLE
Stripe Apple Pay crash iOS 9.3

### ISSUE THREAD

**Issue by aleclaws** [stripe/stripe-ios#460]
## Summary

After update to xcode 8, the project has started crashing on the `-STPAPIClient createTokenWithPayment:completion method`

No other code has changed, I have updated to the most recent stripe SDK and followed the new integration instructions (included the bundle) and set the AppleMerchantIdentifier. 

The Deployment Target is iOS 8, and the issue is reproduced when running against iOS 9 (simulator and device). Issues doesn't exist on iOS 10 simulator
Using our stripe test key

## Code to reproduce

Just passing a `PKPaymentToken` from the `paymentAuthorizationViewController:didAuthorizePayment:completion` delegate

## iOS version

iOS 9.3

## Installation method

Static framework, recently downloaded from this github repo (https://stripe.com/docs/mobile/ios)

## SDK version
`static NSString *const STPSDKVersion = @"8.0.7";`

## Other information

From the assembly backtrace is looks like the issue has to do with the ABAddressBook

![screen shot 2016-09-23 at 4 27 01 pm](https://cloud.githubusercontent.com/assets/2133341/18800402/c1dcc898-81aa-11e6-80bd-12406da0248b.png)
![screen shot 2016-09-23 at 4 27 16 pm](https://cloud.githubusercontent.com/assets/2133341/18800403/c1de1d88-81aa-11e6-8578-2946c8aaa188.png)
![screen shot 2016-09-23 at 4 27 34 pm](https://cloud.githubusercontent.com/assets/2133341/18800404/c1dec6b6-81aa-11e6-85d0-55efe7b4af24.png)
![screen shot 2016-09-23 at 4 27 41 pm](https://cloud.githubusercontent.com/assets/2133341/18800405/c1df7f20-81aa-11e6-97e5-2fe680656202.png)

Thanks for your help!

**Comment by aleclaws** [comment]
We already had a similar crash related to us the AddressBook framework when updating to iOS 10.  The `kABPersonAddress*` tokens we're crashing when accessed, not sure if it's because of the deprecation of this framework. I can see these token are used here: [STPClient+ApplePay.m](https://github.com/stripe/stripe-ios/blob/master/Stripe/STPAPIClient%2BApplePay.m)

**Comment by jflinter** [comment]
Hey @aleclaws - we'll look into this right away. If you have the time to put together a sample project that reproduces the crash, we'd really appreciate it.

**Comment by aleclaws** [comment]
Thanks for the fast response! I continued to investigate and it is now resolved. Removed the `AddressBook.framework` and then re-add it to my project. Now able to use the `kABPersonAddress*` tokens again...

**Comment by jflinter** [comment]
Great, I'm glad that cleared things up for you.
