### ISSUE TITLE
Stripe iOS Example (Custom) App : No Linked Source Error

### ISSUE THREAD

**Issue by sao101** [stripe/stripe-ios#461]
To make it easier to diagnose your issue, please fill out the following:

## Summary

The Simple App Works. The Custom App does not.

I am trying to get the Stripe iOS Example (Custom) App working with a instance of the [example-ios-backend](https://github.com/stripe/example-ios-backend).

I have an instance of said` example-ios-backend` deployed successfully on heroku. 

I have the  Stripe iOS Example (Simple) App talking to this instance without any problems.

Both Applications i.e. the Custom and Simple Apps are configured to use the same Stripe Publishable Key and Backend Charge URL string.

In Constants.m for the Objective-C Custom App.
and
In CheckoutViewController.swift for the Simple App.

## Stripe Logs

The Custom App 

makes a `POST /v1/charges` which has a status of `404` 

and a reponse body of

```
error:
type: "invalid_request_error"
message: "Customer cus_9FplGbq9oabQML does not have a linked source with ID tok_18xK8nKhiv4UboVETGBw38db."
param: "source"
code: "missing"
```

Is a call missing here in the example app?

I note that the Simple App makes a 

`POST /v1/customers/cus_9FpezEQZUW7PaO/sources` and has no issues.

Any help on resolving this would be greatly appreciated.

Many Thanks,
Shane

**Comment by benzguo** [comment]
Hey Shane,

Thanks for pointing this out – I've updated the example backend in https://github.com/stripe/example-ios-backend/pull/7 . The fix hasn't been merged to master yet, but for now you can deploy the backend from [my branch](https://github.com/stripe/example-ios-backend/tree/bg-charge-custom).

Note that we haven't updated the "Custom" example app to use our UI components [0] yet. The "Custom" example simply demonstrates creating a token using either Apple Pay or `STPPaymentCardTextField`, and the charge flow is slightly different. The "Simple" example creates a customer, adds a source to the customer, and charges that source, while the "Custom" example simply charges a card directly.

We're planning on improving our example apps in the coming months – apologies for the confusion!

-Ben
