### ISSUE TITLE
EXC_BAD_ACCESS crash when total $0.00 and using paymentSummaryItems

### ISSUE THREAD

**Issue by janderson-primary** [stripe/stripe-ios#462]
## Summary

I am working on an iOS app in which we are trying to charge the user $0.00, and the app crashes.  We are using STPPaymentContext and building out the 'paymentSummaryItems' array with PKPaymentSummaryItem(s).  Each item in the array, has an 'amount' of 0.

I assume the previous devs did it this way, to show each line item in the Apple Pay view, as discounted to $0.00.

I realize now thanks to ywain in IRC, they the minimum amount is $0.5.  

## Code to reproduce
```
NSDecimalNumber *foodCost = [NSDecimalNumber decimalNumberWithString:@"0.00"];
PKPaymentSummaryItem *foodDetails = [PKPaymentSummaryItem summaryItemWithLabel:kFoodLabel
                                                          amount:foodCost];

NSDecimalNumber *taxCost = [NSDecimalNumber decimalNumberWithString:@"0.00"];
PKPaymentSummaryItem *taxDetails = [PKPaymentSummaryItem summaryItemWithLabel:kTaxLabel
                                                          amount:taxCost];

NSDecimalNumber *shippingCost = [NSDecimalNumber decimalNumberWithString:@"0.00"];
PKPaymentSummaryItem *shippingDetails = [PKPaymentSummaryItem summaryItemWithLabel:kShippingLabel
                                                          amount:shippingCost];

NSDecimalNumber *totalCost = [NSDecimalNumber decimalNumberWithString:@"0.00"];
PKPaymentSummaryItem *totalDetails = [PKPaymentSummaryItem summaryItemWithLabel:kTotalLabel
                                                          amount:totalCost];

[self.paymentContext setPaymentSummaryItems:@[foodDetails, taxDetails, shippingDetails, totalDetails]];
```

## iOS version

9.3.5

## Installation method

Cocoapods   

pod 'Stripe'

## SDK version

8.0.6

## Other information

I've done some digging, and it looks like the following method in **STPPaymentContext** is where our nil object originates:

```
- (PKPaymentRequest *)buildPaymentRequest {
    FAUXPAS_IGNORED_IN_METHOD(APIAvailability);
    if (!self.configuration.appleMerchantIdentifier || !self.paymentAmount) {
        return nil;
    }
    PKPaymentRequest *paymentRequest = [Stripe paymentRequestWithMerchantIdentifier:self.configuration.appleMerchantIdentifier];
    
    NSArray<PKPaymentSummaryItem *> *summaryItems = self.paymentSummaryItems;
    paymentRequest.paymentSummaryItems = summaryItems;
    paymentRequest.requiredBillingAddressFields = [STPAddress applePayAddressFieldsFromBillingAddressFields:self.configuration.requiredBillingAddressFields];
    paymentRequest.currencyCode = self.paymentCurrency.uppercaseString;
    return paymentRequest;
}
```

You can see that !self.paymentAmount is evaluating to true, since our total payment amount is 0.  self.paymentAmount is a derived property, which ultimately gets the value from 'STPPaymentContextAmountModel.paymentAmountWithCurrency:(NSSring*) currency'.  In our case, since we're using paymentSummaryItems, it grabs the last one and uses it's value for amount.

**Comment by bdorfman** [comment]
Apple Pay requires your grand total to be greater than 0, and as such we do not support the situation you mention (this is noted in the documentation for `paymentAmount` but not for `paymentSummaryItems`). I will update the documentation to make this clearer and provide a better error when you do not provide 0 as the total, but you must provide a total greater than 0 for Apple Pay to work.
