### ISSUE TITLE
Migration from stripe 4.0 to latest stripe 8.x

### ISSUE THREAD

**Issue by parthadrojasa** [stripe/stripe-ios#467]
I have not updated stripe from a long time and i now it seems that paymentkit is integrated into stripe. So i have used multiple things from paymentkit and i am not able to find proper thing how to migrate the code. I have some queries below.

I am using PTKCardNumber like let cardNumber:PTKCardNumber = PTKCardNumber(string:strCardNumber)
PTKCardTypeAmex like to determine which card is it.
PTKTextField for the card like PTKTextField.textByRemovingUselessSpacesFromString(str as String)
What is used in place of above this all in new stripe?

**Comment by benzguo** [comment]
Hey @parthadrojasa,

- There's no equivalent for `PTKCardNumber` in the latest SDK. To determine brand from a card number, you can use `STPCardValidator`:

`STPCardValidator.brandForNumber("4242424242424242")`

https://stripe.github.io/stripe-ios/docs/Classes/STPCardValidator.html

- `PTKTextField` is now `STPPaymentCardTextField`. To set the card number of an `STPPaymentCardTextField`, you can set its `cardParams`:

```swift
let textField = STPPaymentCardTextField()
let cardParams = STPCardParams()
cardParams.number = "4242424242424242"
textField.cardParams = cardParams
```

https://stripe.github.io/stripe-ios/docs/Classes/STPPaymentCardTextField.html
