### ISSUE TITLE
dyld: Symbol not found: _kABPersonAddressCityKey XCODE 8 issue

### ISSUE THREAD

**Issue by akixie** [stripe/stripe-ios#478]
To make it easier to diagnose your issue, please fill out the following:

## Summary

dyld: Symbol not found: _kABPersonAddressCityKey
  Referenced from: /var/containers/Bundle/Application/E2C01CB7-1CBB-4C1A-B4DD-937BF725BB6F/Get.app/Get
  Expected in: /System/Library/Frameworks/PassKit.framework/PassKit
 in /var/containers/Bundle/Application/E2C01CB7-1CBB-4C1A-B4DD-937BF725BB6F/Get.app/Get

## Code to reproduce

STPAPIClient+ApplePay.m  code

ABMultiValueRef addressValues = ABRecordCopyValue(billingAddress, kABPersonAddressProperty);
        if (addressValues != NULL) {
            if (ABMultiValueGetCount(addressValues) > 0) {
                CFDictionaryRef dict = ABMultiValueCopyValueAtIndex(addressValues, 0);
                NSString *line1 = CFDictionaryGetValue(dict, kABPersonAddressStreetKey);
                if (line1) {
                    params[@"address_line1"] = line1;
                }
                NSString *city = CFDictionaryGetValue(dict, kABPersonAddressCityKey);
                if (city) {
                    params[@"address_city"] = city;
                }

## iOS version

My code was running perfectly in xcode 7.x.x

my app with a target of iOS-8 ran fine with iOS-10 in Xcode-8, but would crash with anything previous to iOS-10.

## SDK version

Stripe, 8.0.7

## Other information

http://stackoverflow.com/questions/39485826/dyld-symbol-not-found-kabpersonaddresscitykey-xcode-8-issue

**Comment by benzguo** [comment]
Hey @akixie – looks like there's an answer in the SO thread you linked to (http://stackoverflow.com/a/39533397/1571693). I'm going to close this, but let us know if you have any further issues!
