### ISSUE TITLE
Stripe.bundle: bundle format unrecognized, invalid, or unsuitable

### ISSUE THREAD

**Issue by jeremypiednoel** [stripe/stripe-ios#489]
Hello,

## Summary
When i try to update my app to iOS10 - swift 3 i have this error when i build **only on simulator**

## iOS version
iOS 10 

## Installation method
`pod 'Stripe'`

## SDK version
`Stripe (9.0.0)`

## Other information
I already make a lot of search on the web like remove Derived Data
http://stackoverflow.com/questions/29271548/code-sign-error-bundle-format-unrecognized-invalid-or-unsuitable
I uninstall / reinstall simulators.

<img width="1184" alt="screen shot 2016-10-31 at 2 53 11 pm" src="https://cloud.githubusercontent.com/assets/3902298/19867417/1eafda78-9f7a-11e6-9e43-a9310f2d933b.png">

Thanks

**Comment by bdorfman-stripe** [comment]
What version of Xcode and Cocoapods are you using? Also, do you have the `use_frameworks!` feature enabled in your Podfile?

**Comment by jeremypiednoel** [comment]
Ok well done it was my Cocoapod version I update to `1.1.1`.
Thanks for reactivity and have a good day @bdorfman-stripe

**Comment by bdorfman-stripe** [comment]
Glad I was able to help! :)
