### ISSUE TITLE
Cartfile should not include facebook/ios-snapshot-test-case

### ISSUE THREAD

**Issue by kballard** [stripe/stripe-ios#492]
## Summary

The latest release adds "facebook/ios-snapshot-test-case" to the Cartfile. This is a really bad idea. This adds this dependency to all projects that use stripe-ios, even though they don't want it. You're using this for your test target, so you should be adding this to a file called "Cartfile.private", not to your Cartfile. Cartfile.private is for test dependencies, and they're only fetched/built when running `carthage` from within this repository. Any other repos that use stripe-ios will not fetch anything from your Cartfile.private.

## SDK version

9.1.0

**Comment by bdorfman-stripe** [comment]
Sorry about that. Fix is already PR'd here: https://github.com/stripe/stripe-ios/pull/493 Will merge and release a 9.1.1 as soon as travis finishes.

**Comment by bdorfman-stripe** [comment]
Fix is in 9.2.0. Thanks for your patience!
