### ISSUE TITLE
deprecated API needs updating

### ISSUE THREAD

**Issue by daver234** [stripe/stripe-ios#496]
Line 83 of Networking.swift says the return is deprecated as of iOS 9
`return CFURLCreateStringByAddingPercentEscapes(nil, string as CFString!, nil, legalURLCharactersToBeEscaped, CFStringBuiltInEncodings.UTF8.rawValue) as String
`

What is the new return value to use?
Thanks

**Comment by bdorfman-stripe** [comment]
Thanks for the report. The example app no longer uses this deprecated api as of version 9.2.0.
