### ISSUE TITLE
charging token generated with one api key with another api key

### ISSUE THREAD

**Issue by vondiplo** [stripe/stripe-ios#497]
I'm not sure if this is the right place to post this question, if it isn't I aplogoies in advance. 

My application tokenizes users credit cards using one stripe api key (call it api key 1)
It then sends the token to another server to perform the actual credit clearing and charging  which uses another stripe api key (call it api key 2).

Would server 2 using api key 2 be able to charge the token generated by api key 1?

Thank you

**Comment by bg-stripe** [comment]
Hi @vondiplo ,

The Stripe SDK in your app will tokenize credit cards using your publishable API key [0], while your backend will perform the actual charging using your private API key. You can find both these keys on the account settings page [1]. Let me know if you have any other questions!

Ben

[0] https://stripe.com/docs/mobile/ios#configure-your-stripe-integration-in-your-app-delegate
[1] https://dashboard.stripe.com/account/apikeys
