### ISSUE TITLE
Country Picker Doesn't Update on First Selection

### ISSUE THREAD

**Issue by hyerra** [stripe/stripe-ios#509]
## Summary
This should be a relatively simple fix; however, on first selection the country code picker doesn't update. For example, when I click on the picker the option United States shows up but I actually have to scroll to Afghanistan and then scroll back up to United States for the value to update.

## Code to reproduce
Any project using Stripe's STPShippingAddressViewController has this issue. Just present the View Controller and try changing the country. When you select it the value isn't updated. You have to scroll it to Afghanistan and back to the United States in order to select the US.

## iOS version
iOS 10.1.1 (14B100)

## Installation method
Cocoapods

## SDK version
9.2.0

**Comment by bg-stripe** [comment]
Hey @hyerra ,
Thanks for bringing this to our attention – we'll have a fix [0] in the next version of the SDK. 

As a workaround for now, you can not pass `prefilledInformation` to your `STPPaymentContext`. (e.g. comment out this line in the example app: [1])

Sorry for the inconvenience!

[0] https://github.com/stripe/stripe-ios/pull/511
[1] https://github.com/stripe/stripe-ios/blob/master/Example/Stripe%20iOS%20Example%20(Simple)/CheckoutViewController.swift#L83

**Comment by hyerra** [comment]
Hey @bg-stripe actually I'm not using the standard implementation. I'm using the custom one. Does this pull request fix that as well?

**Comment by bg-stripe** [comment]
yep, this PR will also fix the issue if you're creating a `STPShippingAddressViewController` yourself, rather than using `STPPaymentContext`.

**Comment by hyerra** [comment]
@bg-stripe I actually realize you might be thinking of a different issue as I had the issue you just fixed in my app as well. But there is one more issue with countries. Like you know when you tap on the country the picker shows up, and in my case, United States is automatically selected for me. However, the country text field doesn't update. Basically, I have to scroll up and then scroll down in order to trigger a "refresh" and then the text field has "United States". Do you get what I'm saying? I wish I was able to upload an image maybe to better show you.

**Comment by bg-stripe** [comment]
@hyerra – yep, that issue should be fixed to (the text field will now be filled automatically). The fix is now in `master` – we haven't released a new version containing the fix yet, but we will soon.
