### ISSUE TITLE
Debugging didFailToLoadWithError:method Swift

### ISSUE THREAD

**Issue by davidoliverdoswell** [stripe/stripe-ios#518]
Hey,

So I am having an issue fetching initial data for my current logged-in customer using STPPaymentContextDelegate. I keep calling didFailToLoadWithError and popping the view despite my configurations on my backend set up to correspond with my front-end.  

<// MARK: - STPPaymentContextDelegate
    func paymentContextDidChange(_ paymentContext: STPPaymentContext) {
        if let paymentMethod = paymentContext.selectedPaymentMethod {
            self.paymentRow.detail = paymentMethod.label
        }
        else {
            self.paymentRow.detail = "Select Payment"
        }
        self.totalRow.detail = self.numberFormatter.string(from: NSNumber(value: Float(self.paymentContext.paymentAmount)/100))!
    }
    
    func paymentContext(_ paymentContext: STPPaymentContext, didCreatePaymentResult paymentResult: STPPaymentResult, completion: @escaping STPErrorBlock) {
        MyAPIClient.sharedClient.completeCharge(paymentResult, amount: paymentContext.paymentAmount, completion: completion)
    }
    
    func paymentContext(_ paymentContext: STPPaymentContext, didFinishWith status: STPPaymentStatus, error: Error?) {
        // MARK: - Payment Succeeded and Auxillary UIs are Dismissed
        // MARK: - Present Updated UI to Giver
        let title: String
        let message: String
        switch status {
        case .error:
            title = "Error ⚠️"
            message = error?.localizedDescription ?? "☹️"
        case .success:
            title = "Success 🎉"
            message = "You Have Successfully Made a Charge 🛩"
        case .userCancellation:
            return
        }
        let alert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        let action = UIAlertAction(title: "Heard", style: .default, handler: nil)
        alert.addAction(action)
        self.present(alert, animated: true, completion: nil)
    }
    
    func paymentContext(_ paymentContext: STPPaymentContext, didFailToLoadWithError error: Error) {
       _ = self.navigationController?.popViewController(animated: true)
    }>

I have essentially followed the Standard iOS Integration and the API References. 

iOS 10.2 
Swift 3
Xcode
Stripe 9.0.0
Cocoapods

**Comment by bdorfman-stripe** [comment]
Sorry to hear you're having trouble. Usually if you are receiving that callback, it means an error was passed to the `STPCustomerCompletionBlock` from your `STPBackendAPIAdapter`'s `retrieveCustomer:` method. I would try putting a breakpoint in there and make sure you aren't passing an error in the completion block.

 Let me know if this doesn't fix the issue, and we can try something else!

**Comment by davidoliverdoswell** [comment]
Worked. Thanks!
