### ISSUE TITLE
Shipping Picker View not Updating When Country is Automatically Selected

### ISSUE THREAD

**Issue by hyerra** [stripe/stripe-ios#519]
To make it easier to diagnose your issue, please fill out the following:

## Summary
When I tap on the country the picker shows up, and in my case, United States is automatically selected for me. However, the country text field doesn't update and it basically stays empty even with United States selected (remember it's automatically selected when I tap on the textfield so I never even scrolled). Basically, I have to scroll up and then scroll down in order to trigger a "refresh" and then the text field has "United States". Do you get what I'm saying? Here's an image to better explain the issue:
![img_0411](https://cloud.githubusercontent.com/assets/16071306/20993608/0689df62-bcb1-11e6-97d4-b85e421fce24.PNG)
See how United States is automatically selected but it doesn't update the textfield? I have to manually scroll down to Afghanistan and scroll back up to United States to have the text field update accordingly.

## Code to reproduce
Any project with STPShippingAddressViewController has this issue.

## iOS version
10.1.1
## Installation method
Cocoapods

## SDK version
9.2.0

**Comment by bg-stripe** [comment]
@hyerra Thanks for reporting this again. The fix is now in `master`, but we haven't published a new version of the SDK yet. For now, you can use point to the `master` branch to get the change.
```
pod 'Stripe', :git => 'https://github.com/stripe/stripe-ios.git'
```
