### ISSUE TITLE
It seems that 

### ISSUE THREAD

**Issue by kennebecstars** [stripe/stripe-ios#526]
To make it easier to diagnose your issue, please fill out the following:

## Summary

A simple summary of the problems you're having.

PAUL> STPPaymentContext's property is not nullable and needs to be. I am setting us up to sell objects that have no shipping needed as they are tips to service people. Filing this issue to help Zach from your staff to resolve.

## Code to reproduce

If possible, please include a brief piece of code (or ideally, a link to an example project) demonstrating the problem you're having.

PAUL> I have references to the stripe-ios repo, Stripe iOS Example (Simple), CheckoutViewController.swift:

        let paymentContext = STPPaymentContext(apiAdapter: MyAPIClient.sharedClient,
                                               configuration: config,
                                               theme: settings.theme)
        paymentContext.shippingMethods? = nil

gives an error for trying to set a get-only property.

## iOS version

What version of iOS are you observing the problem on?

PAUL> Xcode 8.2, iOS 10.0

## Installation method

How did you install our SDK?

PAUL> As a git clone of the stripe-iso repo from github.com.

## SDK version

What version of our SDK are you using? You can find this by either looking at your `Podfile.lock` (if you're using Cocoapods), your `Cartfile.resolved` (if you're using Carthage), or by looking at the value of `STPSDKVersion` in `STPAPIClient.h`.

PAUL> 9.2.0

## Other information

Anything else you can include that'll make it easier for us to help you!

PAUL> Here is a transcript between me and Zach:

Also tried, to no avail, I might add:

        let noShippingMethods : Array<PKShippingMethod>? = nil
        paymentContext.shippingMethods? = noShippingMethods

I think the root of the issue may be that the property is defined in the .m file as nonatomic, but also needs to be nullable:

@property(nonatomic)NSArray<PKShippingMethod *> *shippingMethods;

and in the .h file, you define it as nullable:

/**
 *  An array of STPShippingMethod objects that describe the supported shipping methods. May be nil.
 */
@property(nonatomic, readonly, nullable)NSArray<PKShippingMethod *> *shippingMethods;
 

Is this a bug in Stripe API? I cannot rebuild this myself, as I get an identity issue with signing.

Best regards,

-Paul Crowell

On Dec 17, 2016, at 4:52 PM, Paul Crowell <ksapps17@gmail.com> wrote:

Hi, Zach!

  I finally had a chance to try setting the shippingMethods to nil on the payment context. It’s an error to do so in Xcode 8.2 because it’s a get-only object.

  Ideas? Maybe I’ve done this wrong?

-Paul Crowell

From the code on your website, stripe-ios repo, Stripe iOS Example (Simple), CheckoutViewController.swift:

        let paymentContext = STPPaymentContext(apiAdapter: MyAPIClient.sharedClient,
                                               configuration: config,
                                               theme: settings.theme)
        paymentContext.shippingMethods? = nil

stripe-ios/Example/Stripe iOS Example (Simple)/CheckoutViewController.swift:84:41: error: cannot assign to value: 'shippingMethods' is a get-only property
        paymentContext.shippingMethods? = nil
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^


On Dec 13, 2016, at 8:20 AM, Stripe Support <support@stripe.com> wrote:

Hi there,
Hopefully I can help clear up your confusion.

For your Shipping Address collection question, you should be able to set `shippingMethods` to `nil` on the `STPPaymentContext` object in your app which should then not collect shipping info (see https://stripe.github.io/stripe-ios/docs/Classes/STPPaymentContext.html#/c:objc(cs)STPPaymentContext(py)shippingMethods for more info). If that isn't the case, I'll keep digging as our SDK may have changed since I last dug through it.

As for your second question, sending an Apple Push Notification is something that you will have to configure and set up on your server yourself. This is not part of the Stripe iOS SDK, nor is it something that can be done via the Stripe Dashboard. You must follow the steps at https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1 in order to set up and configure your iOS app and APN integration.

I hope that this clears up any confusion that you had, and if not, please feel free to reach back out to me.

Good luck and happy hacking!
-zach

**Comment by kennebecstars** [comment]
This is regards work I am doing for your client TipGenie.co, Contact: Elle Rustique.

**Comment by bdorfman-stripe** [comment]
Hi @kennebecstars,

You don't need to set that shipping method property, it is intentionally read-only. If you actually wanted to support shipping methods, you would do so by returning the available methods in the `paymentContext:didUpdateShippingAddress:completion:` delegate callback.

But since you don't want shipping: make sure the `requiredShippingAddressFields` in your STPPaymentConfiguration is set to `PKAddressFieldNone` and don't call `presentShippingViewController` or `pushShippingViewController`to ensure the shipping address entry screen will not be displayed.

**Comment by marcus-hiles** [comment]
Hi I got mine to work!!!!!
Here's a link to the solution.
https://github.com/stripe/stripe-ios/issues/817#issuecomment-462417169

Checkout more about me from https://marcus-hiles.com/
