### ISSUE TITLE
validationState(forCVC:, cardBrand:) returns .valid for a 3 digit amex security code

### ISSUE THREAD

**Issue by liamnichols** [stripe/stripe-ios#538]
I have this bit of code

    let result = STPCardValidator.validationState(forCVC: "123", cardBrand: .amex) // .valid

I'm not an expert here but according to [Wikipedia](https://en.wikipedia.org/wiki/Card_security_code) the length of an American Express security code can only ever be four digits. 

Should this method not return either `.incomplete` or `.invalid` for the above?

**Comment by bdorfman-stripe** [comment]
Hi @liamnichols,

Thanks for your report, but some American Express cards can actually have 3 digit CVC numbers. As such we have to allow entries of both lengths. Hope that clears things up!
