### ISSUE TITLE
Apple Pay logos on PaymentMethodsViewController does not comply with Apple Pay Identity Guidelines

### ISSUE THREAD

**Issue by idris** [stripe/stripe-ios#543]
## Summary

The Apple Pay logos displayed in the `PaymentMethodsViewController` have a light blue stroke, which does not comply with the [Apple Pay Identity Guidelines](https://developer.apple.com/apple-pay/Apple-Pay-Identity-Guidelines.pdf)

My app was rejected from the app store because of this.

Screenshot of the view I'm referring to:
<img width="768" alt="attachment-4675181280058593238screenshot_0126_150429" src="https://cloud.githubusercontent.com/assets/13989/22354357/d4b56394-e3d9-11e6-85dc-c010def48f72.png">

## SDK version

v9.3.0

**Comment by bdorfman-stripe** [comment]
Sorry about the trouble, we are investigating now.

**Comment by idris** [comment]
@bdorfman-stripe thanks.  I think it's just a matter of using the official Apple Pay logos (black with white background or white with black background) instead of using the colors provided in the theme.

Do you have an ETA on a fix for this?

**Comment by bdorfman-stripe** [comment]
We should have an updated sdk version with these images changed later today. Sorry again, thanks for your patience.

**Comment by bdorfman-stripe** [comment]
We just released 9.4.0 which now only has the officially provided Apple Pay logo without any color changes. Hopefully this resolves your issue with app review, please comment or open a new issue if you continue to have problems! Sorry for the trouble.
