### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by arpandesai** [stripe/stripe-ios#546]
Module file was created by an older version of the compiler; rebuild 'PassKit' and try again: ********/Desktop/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/x86_64/PassKit.swiftmodule

Podfile 

 use_frameworks!
   
    pod 'Stripe'
![screen shot 2017-01-28 at 6 52 04 pm](https://cloud.githubusercontent.com/assets/507842/22396934/e54a2f02-e58a-11e6-89c3-f144e2b3e8e6.png)

**Comment by rvishal1991** [comment]
I am facing same issue.

**Comment by bdorfman-stripe** [comment]
This appears to be an issue with your Xcode, not Stripe. PassKit is a standard Apple framework. I would advise cleaning your build folder and trying again.
