### ISSUE TITLE
UI probem in STPAddCardViewController.m

### ISSUE THREAD

**Issue by LingLingL** [stripe/stripe-ios#549]
I think there is one line missing in updateAppearance:
- (void)updateAppearance {
    self.view.backgroundColor = self.theme.primaryBackgroundColor;
    [self.doneItem stp_setTheme:self.theme];
    [self.backItem stp_setTheme:self.theme];
// missed this line
    [self.cancelItem stp_setTheme:self.theme];
...

Also I would like to know how to config the navigationBar batTintColor in STPAddCardViewController as well as STPShippingAddressViewController. Thx.

**Comment by bdorfman-stripe** [comment]
We've unified a lot of the appearance and theming code in our view controllers in master, so hopefully this will be fixed in the next release (which should hopefully be out later today).

**Comment by bdorfman-stripe** [comment]
Version 9.4.0 was just released, which I think should fix this issue. Feel free to open a new issue if you continue to have problems!
