### ISSUE TITLE
[Query] STPCardValidator rules around distant expiry dates

### ISSUE THREAD

**Issue by liamnichols** [stripe/stripe-ios#552]
Hi,

So we use the `STPCardValidator` class to perform a local validation before we then attempt to create tokens however if I provide an expiry date of 01/88 (Jan 2088), the local library will deem this valid.

If I then go to create a token via the `STPAPIClient` I then get an error "Your card's expiration year is invalid".

Exact error:
```
(lldb) po error!
Error Domain=com.stripe.lib Code=70 "Your card's expiration year is invalid" UserInfo={com.stripe.lib:ErrorMessageKey=Your card's expiration year is invalid., com.stripe.lib:CardErrorCodeKey=com.stripe.lib:InvalidExpiryYear, com.stripe.lib:ErrorParameterKey=expYear, NSLocalizedDescription=Your card's expiration year is invalid}
```

I'm not sure what the boundaries are for this but could the logic for this be included in the `STPCardValidator` methods? 

Also please let me know if there is somewhere else I should be raising queries like this?

**Comment by fred-stripe** [comment]
Hi @liamnichols, great question! As you can see from the STPCardValidator logic, an expiration date in 2088 would pass:

https://github.com/stripe/stripe-ios/blob/master/Stripe/STPCardValidator.m#L78-L107

The error you're seeing there is returned directly from the Stripe API, as there are no known issuers that would issue a card good for 72 years. There is some sanity-checking in the API to make sure the card's expiration date seems reasonably close to the present. If your bank issued you a card with a date that far in the future, I'd be extremely curious—I've never known a bank to do that. :)

I'm happy to answer this question here, but in the future these kind of questions would be best directed to support@stripe.com; this gets your question in front of the right folks sooner, and also helps us track areas where we can improve our documention and/or API behavior.

Closing this issue for now!
