### ISSUE TITLE
Add property attributes to non-GC Object

### ISSUE THREAD

**Issue by ogres** [stripe/stripe-ios#578]
Hello,

I am getting following compilation warning in few places: 
>"No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed".

Would be good to add proper attributes ( strong/weak/copy) to silence compiler.

Properties missing attributes:

- `STPUserInformation.billingAddress`
- `STPAddCardViewController.prefilledInformation`
- `STPPaymentContext.prefilledInformation`
- `STPPaymentMethodsViewController.prefilledInformation`

Stripe 9.4.0 via Cocoapods.

**Comment by bdorfman-stripe** [comment]
Ah thanks, I'll add those.

By the way, any idea what project setting you have turned on to enable this warning? Not seeing it in our Xcode and would like to turn this on for us to prevent future regressions.

**Comment by ogres** [comment]
I am not sure how to enable this by default in Xcode, but the warning only appears if a project contains mix of ARC enabled/disabled files.

**Comment by bdorfman-stripe** [comment]
Ah ok. I couldn't find any specific setting to turn it on either, but fixed the issues you pointed out. In master now, and we should have a new official release with it imminently. Let me know if you find any other issues like this. Thanks again!

**Comment by ogres** [comment]
Thank you!
