### ISSUE TITLE
STPPaymentContext - How to remove saved Credit card?

### ISSUE THREAD

**Issue by tuanphung** [stripe/stripe-ios#580]
Hey team,

According Standard iOS Integration Guide (https://stripe.com/docs/mobile/ios/standard), I wonder how to remove card added before? Now can only remove card from Stripe Dashboard.

I see there is API to remove card, it should be abstracted in STPBackendAPIAdapter, right?

Thanks!

**Comment by bdorfman-stripe** [comment]
Hi @tuanphung,

Unfortunately we currently don't support letting the user delete saved cards through STPPaymentContext. We may add built in support for this in the future, but at the current time if you want to let your users do this you will have to add the functionality yourself using the Stripe API. 

Also a caveat: If you add this functionality to your app and you support recurring payments, you should be careful to block your users from deleting the cards they are using for their recurring payments.

Hope this helps. We'll keep your request to have this functionality added in mind when planning our future feature development!

**Comment by heyzooi** [comment]
@bdorfman-stripe is this still true? not possible to delete (or maybe detached) credit cards (or any other source)?

**Comment by bdorfman-stripe** [comment]
Hi @heyzooi,

`STPPaymentContext` now allows deleting saved cards. The setting is `canDeletePaymentMethods`on `STPPaymentConfiguration`[0] however you must use `STPCustomerContext` for it to work. The user is also currently not allowed to delete their currently selected payment method (they must always have at least one valid payment method remaining).

If you have any further questions about integrating with the Stripe SDK, please write in to support@stripe.com

Thanks,
Brian

[0] https://stripe.github.io/stripe-ios/docs/Classes/STPPaymentConfiguration.html#/c:objc(cs)STPPaymentConfiguration(py)canDeletePaymentMethods

**Comment by heyzooi** [comment]
I'm using a custom view controller, so, not able to call the private method `STPPaymentContext. removePaymentMethod()`. Why not allow this method to be public? Should I open an issue requesting this?

https://github.com/stripe/stripe-ios/blob/e61f12d8b5a2d0f10292d7d70a4ccf5a6b62d24a/Stripe/STPPaymentContext%2BPrivate.h#L21

**Comment by bdorfman-stripe** [comment]
`STPPaymentContext` is not intended to be used with custom view controllers. If you are not using our provided UI, the only officially supported path is for you to implement the relevant logic and API calls yourself. To edit information from a customer you would have to make calls to `v1/customer` endpoints from your backend using your private key.

Again, I recommend writing in to support@stripe.com with any further questions you have about using the SDK and integrating it into your app.
