### ISSUE TITLE
Type 'MyAPIClient' does not conform to protocol STPBackendAPIAdapter

### ISSUE THREAD

**Issue by garymansted** [stripe/stripe-ios#583]
To make it easier to diagnose your issue, please fill out the following:

## Summary

A simple summary of the problems you're having.

## Code to reproduce

If possible, please include a brief piece of code (or ideally, a link to an example project) demonstrating the problem you're having.

## iOS version

What version of iOS are you observing the problem on?

## Installation method

How did you install our SDK?

## SDK version

What version of our SDK are you using? You can find this by either looking at your `Podfile.lock` (if you're using Cocoapods), your `Cartfile.resolved` (if you're using Carthage), or by looking at the value of `STPSDKVersion` in `STPAPIClient.h`.

## Other information

Anything else you can include that'll make it easier for us to help you!

**Comment by bdorfman-stripe** [comment]
HI @garymansted,

Sorry you're having trouble with the release. Are you trying to run our example app, or do you have a class also named `MyAPIClient` in your own app? Version 10.0.0 is a breaking api change, you might need to update some of your code to support the changes. Check out the MIGRATING.md doc for a list of breaking changes in the new version.

You should also be able to either click on or expand that Xcode error to have it show you specifically which methods it thinks your class is not conforming to, which might help pinpoint the problem.

**Comment by garymansted** [comment]
I just pulled the latest pod and its crashing with error: Type 'MyAPIClient' does not conform to protocol STPBackendAPIAdapter. The error is showing in the MyAPIClient Class. Ive tried cleaning and rebuilding. Any help would be appreciated. Cheers

**Comment by garymansted** [comment]
All good now. Yeah i integrated the SDK in my own project. FIX: I just replaced the MyAPIClient Class (from the simple project in the repository). Thanx for the fast response!

**Comment by bdorfman-stripe** [comment]
Glad you got it working. However I would like to point out that `MyAPIClient` is intended for example purposes only (as well as the matching example Heroku backend). We do not recommend you use that class as-is in your own production apps.
