### ISSUE TITLE
Reload the payment list view controller when a new method is added

### ISSUE THREAD

**Issue by irace** [stripe/stripe-ios#584]
To make it easier to diagnose your issue, please fill out the following:

## Summary

Currently, the payment list view controller is not reloaded when a new payment method is added.

## Code to reproduce

```swift
extension SettingsCoordinator: STPPaymentMethodsViewControllerDelegate {
    func paymentMethodsViewController(_ paymentMethodsViewController: STPPaymentMethodsViewController, didSelect paymentMethod: STPPaymentMethod) {
        // Do nothing
    }
    
    func paymentMethodsViewController(_ paymentMethodsViewController: STPPaymentMethodsViewController, didFailToLoadWithError error: Error) {
        paymentMethodsViewController.hideViewController()
        
        AlertPresenter.errorPresenter(message: NSLocalizedString("Unable to load payment options", comment: ""))
            .present()
    }
    
    func paymentMethodsViewControllerDidFinish(_ paymentMethodsViewController: STPPaymentMethodsViewController){
        /*
         This will pop both the list controller and “add card” controller, necessary when a new card is added because 
         the underlying list doesn’t reload on its own.
         */
        paymentMethodsViewController.dismiss(completion: nil)
    }
}
```

## iOS version

9-10

## Installation method

CocoaPods

## SDK version

10

**Comment by bg-stripe** [comment]
Thanks for reporting this @irace ! Added in #585 – we're planning on shipping a new SDK version this week, and we'll include this in that release.

**Comment by yujia917** [comment]
Looks like the issue is not fixed. The paymentMethod view controller is still not refreshed when a new card is added.

**Comment by FahadIqbal** [comment]
i have same issue open stppaymentview controller then try to add new card viewcontroller not dismissing activty indicator on right side jus spinning
