### ISSUE TITLE
Card image moves too far up when keyboard enters

### ISSUE THREAD

**Issue by antonholmquist** [stripe/stripe-ios#587]
iOS: 10.2.1
Device: iPhone7

![img_0654 png](https://cloud.githubusercontent.com/assets/505089/23937151/54dcf306-0956-11e7-8299-69f3e2d24be4.png)

**Comment by bg-stripe** [comment]
Hey @antonholmquist , thanks for the report! When you begin editing a field in one of our forms, we scroll the content so that the field is centered. I see your point about this behavior seeming a bit off if there's only one field in the form. We'll keep your feedback in mind for future iterations!

**Comment by maksTheAwesome** [comment]
Actually, it does move too far on smaller devices, especially when you hide and show keyboard a couple times.
