### ISSUE TITLE
 bundle format unrecognized, invalid, or unsuitable codesign failed

### ISSUE THREAD

**Issue by jjhesk** [stripe/stripe-ios#588]
To make it easier to diagnose your issue, please fill out the following:

## Summary
Cannot complete the compile process

## Code to reproduce
`Command /usr/bin/codesign failed with exit code 1`
and this
```
/Users/.../Documents/.../.../ios/build/gl/Build/Products/Debug-iphoneos/gl.app/Frameworks/Stripe.framework: bundle format unrecognized, invalid, or unsuitable
````

## iOS version
10.2
What version of iOS are you observing the problem on?

## Installation method

How did you install our SDK?

## SDK version
10.0.0
manual install with fabric

**Comment by bg-stripe** [comment]
Hey @jjhesk – I've tested this on my end, and a Fabric install of Stripe is working for me. Maybe try cleaning your build folder (Option+Shift+Command+K)?
