### ISSUE TITLE
Ability to customize the inputView of the STPPaymentCardTextField

### ISSUE THREAD

**Issue by Chandlerdea** [stripe/stripe-ios#593]
For iPads, the number keyboard is not a true number keyboard like on the iPhone. So if someone wants to use a custom keyboard with the STPPaymentCardTextField, they cannot because the inputView property is readonly. It would be helpful if this was readwrite, so we could customize the keyboard.

I am currently using v10.0.1

**Comment by bdorfman-stripe** [comment]
Thanks for the suggestion. We'll consider adding this feature to a future version!
