### ISSUE TITLE
Opt-in to compile Apple Pay code

### ISSUE THREAD

**Issue by jflinter** [stripe/stripe-ios#60]
It seems that Apple will send you a nastygram via email if you submit an iOS8 app that uses the new bindings but doesn't have an Apple Pay entitlement because it references new PassKit symbols.\* We should find a way to make sure these don't get compiled unless people actually want them.
- Note: they'll still accept your app, just send you a warning email

**Comment by Legoless** [comment]
Has this changed? I've updated the library to 5.x and now I received the email from Apple on two different projects already.

**Comment by jflinter** [comment]
Hey @Legoless - this changed as of 5.x, as we had heard from Apple that they stopped sending those emails. Would you mind forwarding me the email you received? I'm jack@stripe.com.

**Comment by Legoless** [comment]
I've sent the email to you, but posting what I received here as well for clarity:

>Dear developer,
> 
>We have discovered one or more issues with your recent delivery for "App name". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
>Missing Entitlement - App contains references to [Apple Pay] in 'App name', but is missing the required >entitlement 'com.apple.developer.in-app-payments'.
>
>After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
>
>Regards,
>
>The App Store team

**Comment by tomvd79** [comment]
Hi @Legoless. I haven't submitted an app update since my last messages from september. But my fix was : Added passkit framework as optional. I think I had the exact same email, but they do approve. Hope this helps some.

**Comment by jflinter** [comment]
Thanks, @Legoless. I'll update here with any updates, but in the meantime the email is just a warning, and you shouldn't have any issues with App Store submission.

**Comment by Legoless** [comment]
We've just got rejected with "Metadata rejected":

> Information Needed
> 
> We began the review of your app but aren't able to continue because we need additional information about your app.
> 
> At your earliest opportunity, please review the following question(s) and provide as much detailed information as you can. The more information you can provide upfront, the sooner we can complete your review.
> 
> Does the app currently have Apple Pay functionality? If so, please provide detailed steps on where to find the Apple Pay functionality in the app.
> 
> Once you reply to this message in Resolution Center with the requested information, we can proceed with your review.

**Comment by zkirill** [comment]
Just got a rejection with 'Metadata Rejected':

> We have begun review of your app but aren’t able to continue because we need additional information about your app.

> At your earliest opportunity, please review the following question/s and provide as detailed information as you can in response. The more information you can provide upfront, the sooner we can complete your review.

> Does the app currently have Apple Pay functionality? If so, please provide detailed steps on where to find the Apple Pay functionality in the app.

**Comment by jflinter** [comment]
Hey @zkirill, thus far it looks like most apps that have been metadata rejected for this are accepted without any issues after telling Apple that there isn't any Apple Pay functionality. That being said, we're sorry for this inconvenience, and working with Apple to try and get them to stop doing this. Would you mind letting me know the name of your app, either here or privately at jack@stripe.com?

**Comment by zkirill** [comment]
@jflinter Thank you! Sent you an email.

**Comment by gregorpichler** [comment]
@jflinter I've got the same rejection reason like @zkirill for the latest two app updates. Is there any way to avoid this? Have sent the app name to you via email.

**Comment by zkirill** [comment]
@gregorpichler I now put the following in App Review Information > Notes:

```
Dear Reviewer,

Our app does not use Apple Pay or IAP.

Thank you kindly for your time and consideration,
Name
```

**Comment by gregorpichler** [comment]
@zkirill good idea!
