### ISSUE TITLE
PaymentMethodsViewController does not show up

### ISSUE THREAD

**Issue by unoiatech** [stripe/stripe-ios#602]
I am trying to retrieve user's card detail in PaymentMethodsViewController by following this [article](https://stripe.com/docs/mobile/ios/standard) and the Stripe example. I am done with preparing my APIAdapter and "retrieveCustomer " is getting called too. But when I try to push view controller to PaymentMethodsViewController, it just shows a loader on screen. Nothing else. 
Here is my code to setup STPPaymentContext : 

```
STPPaymentConfiguration *config = [STPPaymentConfiguration sharedConfiguration];
    STPTheme *theme = [STPTheme defaultTheme];
    paymentContext = [[STPPaymentContext alloc]initWithAPIAdapter:[O3StripeCheckOutAPI sharedInstance] configuration:config theme:theme];
    STPUserInformation *userInformation = [[STPUserInformation alloc]init];
    paymentContext.prefilledInformation = userInformation;
//    paymentContext.paymentAmount = price
  //  paymentContext.paymentCurrency = self.paymentCurrency
    paymentContext.delegate = self;
    paymentContext.hostViewController = self;
```
I installed Stipe using Cocoa Pods. 

Please help me on this.

**Comment by bdorfman-stripe** [comment]
Hi @unoiatech,

Sorry you're having trouble. It sounds based on your description that your APIAdapter is timing out or not returning valid data. I would double check that it is successfully reaching your server and getting valid json back.

However, this forum is primarily for bugs with the Stripe iOS SDK. For help with getting it integrated into your app, the best route is to email support@stripe.com—there are many experts with our SDK there that will be able to help you diagnose and debug, and they can help determine if it's an issue with the SDK vs an issue with your implementation. Closing this issue for now, hope that helps!
