### ISSUE TITLE
How can I add card image on top of paymentTextField?

### ISSUE THREAD

**Issue by ainurb** [stripe/stripe-ios#630]
## Summary
I set up paymentTextField using STPPaymentCardTextField, and want to add animated card image also like in the swift example app (Simple). How can I do it without using pushPaymentMethodsViewController?
## Code to reproduce
```
let paymentTextField = STPPaymentCardTextField()
    let payButton = UIButton(type: .system)

    override func viewDidLoad() {
        super.viewDidLoad()
        payButton.setTitle("PAY", for: .normal)
        payButton.addTarget(self, action: #selector(payButtonTapped), for: .touchUpInside)
        view.addSubview(payButton)
        paymentTextField.frame = CGRect(origin: CGPoint(x: 0,y : 160), size: CGSize(width: 326, height: 44))
        paymentTextField.delegate = self
        view.addSubview(paymentTextField)
        self.payButton.isHidden = true

    }
    
     func paymentCardTextFieldDidChange(_ textField: STPPaymentCardTextField) {
        if textField.isValid {
            self.payButton.isHidden = false
        }
    }
```

**Comment by bdorfman-stripe** [comment]
Hi @ainurb,

It looks like you are already on the right track here! You can listen for `paymentCardTextFieldDidChange:` in your delegate and update any surrounding UI you want when the card changes. You can use `STPCardValidator` to get information about what brand of card the inputted number is as well if that is helpful for your design. 

If you are creating your own view controller and not using our prebuilt screens, you will have to provide your own images/views for any surrounding UI. Note that you can use `STPPaymentMethodsViewController` directly without having to use `[STPPaymentContext pushPaymentMethodsViewController]` if that is easier for your setup.

Github issues are intended mainly for reporting bugs in our SDK. If you have further questions about integrating the SDK that are not answered by our docs[0] or api reference[1], I recommend you write in to support@stripe.com, as they will be able to give you more thorough help.

Hope that helps!
Brian

[0] https://stripe.com/docs/mobile/ios
[1] https://stripe.github.io/stripe-ios/docs/index.html
