### ISSUE TITLE
STPCardValidator validationStateForNumber: is incorrect for "6"

### ISSUE THREAD

**Issue by chillpop** [stripe/stripe-ios#632]
## Summary

STPCardValidator validatationStateForNumber returns STPCardValidationStateInvalid for an input of "6" when validating card brand.  This should be STPCardValidationStateIncomplete, as it could be a Discover card.

## Code to reproduce

```swift
STPCardValidator.validationState(forNumber: "6", validatingCardBrand: true)
```
## iOS version

10.3

## Installation method

Cocoapods

## SDK version

10.0.1

**Comment by bdorfman-stripe** [comment]
Thanks for the report! I agree that this is definitely wrong currently. We will work on adding a fix for this issue in our next release.
