### ISSUE TITLE
Russian localization of checkout is incomplete?

### ISSUE THREAD

**Issue by backmeupplz** [stripe/stripe-ios#657]
## Summary
Looks like Russian localization of checkout is incomplete, please see the screenshot attached. This might be an issue on my side (if I broke something in my app), but worth checking :)

## Code to reproduce

https://itunes.apple.com/ca/app/controlio/id997857994?mt=8 — the app is up on the appstore, the best way to check is to open it on device with Russian language, login with magic link, go to settings and open payment methods section of settings menu.

## iOS version

10.3

## Installation method

I installed stripe through cocoapods.

## SDK version

10.0.1

## Other information

It might be an issue on my end — but I would be really gladful if you check it :) It's just that some labels are localized and some aren't.

![2017-04-27_10 34 10](https://cloud.githubusercontent.com/assets/3192028/25509570/d45f8ca8-2b6e-11e7-849f-1dfa5a36d073.jpg)

**Comment by bdorfman-stripe** [comment]
Hi @backmeupplz,

Unfortunately, we do not provide Russian translations for the iOS SDK. The currently supported localizations are: English, simplified Chinese, Dutch, French, German, Italian, Japanese, and Spanish.

If your app is set to a locale that does not have built in support, the SDK will use translations that are present in your main bundle. This may be why you are seeing "partial" localization, as some of the strings in your own app may be the same as SDK strings. You can provide your own localization for any languages Stripe does not currently provide by simply putting the translations in your own app's strings files.

I hope this helps,
Brian

**Comment by backmeupplz** [comment]
@bdorfman-stripe thanks a lot!
