### ISSUE TITLE
Apple pay ~ canMakePayments / deviceSupportsApplePay

### ISSUE THREAD

**Issue by Abreu0101** [stripe/stripe-ios#668]
Hello guys,

## Summary
How is possible that `canMakePayments` (`PKPaymentAthoriziationViewController`) return `NO`, but when I use `[stripe deviceSupportsApplePay]` return `YES` (I check that you just check `canMakePaymentsUsingNetworks`, but for some reason is returning YES ~ but doesn't have any card configured)? Is it reliable to just check `deviceSupportsApplePay` or should I check if can make payments directly through `PKPaymentAthorizationVC`?

## iOS version
iOS 8.1 and iOS 8.2 (both tested in simulator iPhone 6 plus)

## Installation method
Cocoapods, SDK v. 10.0.1

**Comment by bg-stripe** [comment]
Hey @Abreu0101 ,

We recommend first creating a `PKPaymentRequest`, and then using `[Stripe canSubmitPaymentRequest:paymentRequest]` to determine whether your customer can complete the payment with Apple Pay. Under the hood, this method checks `deviceSupportsApplePay`, and also makes sure the payment request has a merchant ID and amount. You can check out our example Apple Pay integration here:

 https://github.com/stripe/stripe-ios/blob/master/Example/Stripe%20iOS%20Example%20(Custom)/ApplePayExampleViewController.m#L56-L62

Hope that helps!
Ben

**Comment by bdorfman-stripe** [comment]
I think part of the confusion might stem from the difference between `canMakePayments` and `canMakePaymentsUsingNetworks`. The former returns YES if the device is capable of Apple Pay regardless of if any cards are actually set up. On the other hand, the latter will return NO if there are no cards even if the device is technically capable of Apple Pay.

From the `canMakePayments` docs:

> On devices that support making payments but don’t have any payment cards configured, the presentWithCompletion: method returns YES because the hardware and parental controls allow making payments, but the canMakePaymentsUsingNetworks: method returns NO regardless of network.

As far as determining whether the user can make Apple Pay payments using our SDK, I recommend you follow bg's advice above. 

Hope that clears things up!
