### ISSUE TITLE
Missing files in Stripe pod

### ISSUE THREAD

**Issue by sakshigidwani93** [stripe/stripe-ios#669]
I have installed pod of stripe. It does not contain files like the files in Github project. I wanted to implement Shipping functionality.

**Comment by bg-stripe** [comment]
Hey @sakshigidwani93 ,
What files does it seem like you're missing? In order to collect shipping info from your user, you can use either the `presentShippingViewController` or `pushShippingViewController` methods on `STPPaymentContext`.
https://stripe.com/docs/mobile/ios/standard#let-your-user-enter-their-shipping-info

**Comment by sakshigidwani93** [comment]
Hi thanks for replying. It does not consist of STPShippingAddressViewController i install from pod.
Do you know any link where stripe implementation is done in Objective c?

**Comment by bg-stripe** [comment]
Could you share more details on the error you're seeing? It would also be helpful to know the version of the SDK you're using, and whether your Podfile has the `use_frameworks!` line.

We don't have an example app using our UI components in Objective-C, but you can switch the code examples on our documentation pages to Objective-C. If you're interested in using `STPShippingAddressViewController` on its own, this section should be helpful:
https://stripe.com/docs/mobile/ios/custom#stpshippingaddressviewcontroller

**Comment by sakshigidwani93** [comment]
Thanks for replying. I will get back if there is any other problem.

**Comment by bg-stripe** [comment]
Great, hope this helps. We generally reserve github issues for bug reports – if you're still having trouble with your integration, you can email support@stripe.com .
