### ISSUE TITLE
Implementing STPPaymentCardTextField inside tableview cell

### ISSUE THREAD

**Issue by sakshigidwani93** [stripe/stripe-ios#672]
I want to implement STPPaymentCardTextField inside tableview cell. Is it possible? If yes then how?

**Comment by dbeast86** [comment]
@sakshigidwani93 You can place a UIView into the UITableViewCell, and then set the class of the UIView to STPPaymentCardTextField. It should then display the payment field in the tableview cell.

<img width="612" alt="screen shot 2017-05-11 at 9 11 46 pm" src="https://cloud.githubusercontent.com/assets/11068491/25982116/7cc8f68e-368e-11e7-8787-10bf95167357.png">

**Comment by sakshigidwani93** [comment]
Thanks for replying. It worked.
