### ISSUE TITLE
Incorrect nullable attribute in `STPCustomerDeserializer::initWithData:urlResponse:error:`

### ISSUE THREAD

**Issue by teddynewell** [stripe/stripe-ios#674]
To make it easier to diagnose your issue, please fill out the following:

## Summary

Calling the initializer `initWithData:urlResponse:error:` on `STPCustomerDeserializer` with a null `data` parameter causes a `Fatal Exception: NSInvalidArgumentException` when the unchecked `data` is passed to `NSJSONSerialization::JSONObjectWithData:options:error:`.

## Code to reproduce

This alone causes the exception, but compiles successfully in Swift:
```
let deserializer = STPCustomerDeserializer(data: nil, urlResponse: nil, error: nil)
```

In context:
```
enum CustomerExtractionResult {
  case success(customer: STPCustomer)
  case error(error: NSError)
}

fileprivate func extractCustomer(from data: Data?,
                                                        urlResponse: URLResponse?,
                                                        error: Error?,
                                                        completion: (_ result: CustomerExtractionResult) -> Void) {
  let deserializer = STPCustomerDeserializer(data: data, urlResponse: urlResponse, error: error)
  if let error = deserializer.error {
     completion(.error(error: error as NSError))
    return
  } else if let customer = deserializer.customer {
    completion(.success(customer: customer))
  }
}

// This will crash with unhandled NSInvalidArgumentException: 
extractCustomer(from: nil, urlResponse: nil, error: nil, completion: { (result: CustomerExtractionResult) in 
  // never reached
})
```

## iOS version
iOS 10.1.1

## Installation method
How did you install our SDK?
Via Carthage

## SDK version

v8.0.7

## Proposed Change

Remove the `nullable` attribute from the initializer declaration.

**Comment by bdorfman-stripe** [comment]
Thanks for the report, we'll fix for our next release!

**Comment by bdorfman-stripe** [comment]
Fixed by https://github.com/stripe/stripe-ios/pull/677
