### ISSUE TITLE
STPPaymentCardTextField clear() method not working as expected.

### ISSUE THREAD

**Issue by zackperdue** [stripe/stripe-ios#685]
## Summary

When calling `clear()` on a STPPaymentCardTextField(), the credit card number field should become focused. This is not the case. The form gets reset, however, the cvc field remains in focus.

## Code to reproduce

```
    let cardField = STPPaymentCardTextField()

.......... 

    func cancelAddingCreditCard() {
        cardField.clear()
        delegate?.addCreditCardWasCancelled()
    }
```

## iOS version
10.1.1

## Installation method

Cocoapods

## SDK version
Stripe (10.1.0)

## Other information

After clear is called, i have to hit the back keyboard key to get it to return to the card number field.

**Comment by bg-stripe** [comment]
Hey @zackperdue , thanks for the report. I haven't been able to reproduce the issue on my end – would you mind putting together a small example project demonstrating the behavior? You can email it to bg@stripe.com . Thanks!
