### ISSUE TITLE
Type 'STPCustomer' has no member 'decodedObject'

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#689]
To make it easier to diagnose your issue, please fill out the following:

## Summary

I'm getting the error:

`Type 'STPCustomer' has no member 'decodedObject'
`
in the retrieveCustomer method on the API file for this line:

`                    if let customer = STPCustomer.decodedObject(fromAPIResponse: result as? [String: AnyObject]) {
`  

## Code to reproduce

I had an app running with the last version that used the task sessions requests, and changed the code there to the updated version that used Alamofire. 

## iOS version

10

## Installation method

How did you install our SDK?
Cocoapods

## SDK version

10.1.0

## Other information

Anything else you can include that'll make it easier for us to help you!

**Comment by bg-stripe** [comment]
@odedharth The change that gives `STPCustomer` a `decodedObject` method is on `master`, but isn't available in the SDK version you're on (10.1.0). For now, you should use `STPCustomerDeserializer` to decode the customer object from your API response. You can refer to the example app in v10.1.0 to see this in action:

https://github.com/stripe/stripe-ios/blob/v10.1.0/Example/Stripe%20iOS%20Example%20(Simple)/MyAPIClient.swift#L81-L87
