### ISSUE TITLE
In our requirement we need user to enter both shipping and billing address but in stripe we have the ability to add only Billing address via STPAddress

### ISSUE THREAD

**Issue by sakshigidwani93** [stripe/stripe-ios#702]
In our requirement we need user to enter both shipping and billing address but in stripe we have the ability to add only Billing address via STPAddress. Is there a way to provide both billing and shipping adresses?Please reply asap. Below is the code for entering only billing address.

```
-(void) setDataToStripe{
    STPAddress *address=[[STPAddress alloc]init];
    
    self.stripeCard.name = self.txtName.text;
    self.stripeCard.number=_txtCardPayment.cardNumber;
    self.stripeCard.cvc=_txtCardPayment.cvc;
    self.stripeCard.expMonth=_txtCardPayment.expirationMonth;
    self.stripeCard.expYear=_txtCardPayment.expirationYear;
    self.stripeCard.addressCountry=_txtCountry.text;
    self.stripeCard.addressCity=_txtCity.text;
    self.stripeCard.addressState=_txtState.text;
    self.stripeCard.addressLine1=_txtAddress1.text;
    self.stripeCard.addressLine2=_txtAddress2.text;
    
    address.name=_txtName.text;
    address.country=_txtCountry.text;
    address.state=_txtState.text;
    address.city=_txtCity.text;
    address.line1=_txtAddress1.text;
    address.line2=_txtAddress2.text;
    self.stripeCard.address=address;
}
```

**Comment by bdorfman-stripe** [comment]
Hi @sakshigidwani93,

I'm a little confused what Stripe object you want to store the shipping address on? Card objects themselves do not have shipping addresses, only billing addresses. You can attach shipping addresses to charges, but the iOS SDK cannot make charges directly (as it requires your public key) so if you want to pass that information through to the `v1/charges` call, you will have to do it on your backend.

I also want to mention based on this code snippet: Simply setting an address object on to the local Objective-C card object will not send any data to the Stripe servers. Those objects are just locally cached representations of what was returned by the server. If you want billing address to actually be stored in the Stripe API, you have to attach the address to the `STPCardParams` or `STPSourceParams` you use when you create the card token/source.

I would recommend contacting support@stripe.com for further help getting your app integrated with Stripe, as they can walk you through how to best set this up.

I hope that helped,
Brian
