### ISSUE TITLE
Test to build Stripe with Xcode 9 and Swift 3.2

### ISSUE THREAD

**Issue by TofPlay** [stripe/stripe-ios#709]
## Summary

I'm preparing the migration of my application on iOS 11 under Xcode 9 Beta and Swift 3.2. Swift 4 will come later.

## iOS version

iOS 11

## Installation method

Cartfile:
```
github "stripe/stripe-ios" == 10.1.0
```
Output:
```
$ carthage update --platform iOS --no-use-binaries
*** Fetching stripe-ios
*** Checking out stripe-ios at "v10.1.0"
*** xcodebuild output can be found in /var/folders/rw/gbr9wvs91cz91mcpgdxv4q340000gn/T/carthage-xcodebuild.8JRlhv.log
*** Building scheme "StripeiOS" in Stripe.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace 
../Carthage/Checkouts/stripe-ios/Stripe.xcworkspace -scheme StripeiOS -configuration Release -derivedDataPath /Users/TofPlay/Library/Caches/org.carthage.CarthageKit/DerivedData/stripe-ios/v10.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
```

## SDK version

10.1.0

**Comment by bg-stripe** [comment]
Hey @TofPlay – we have a working branch with our iOS 11 updates, which you can point your Cartfile to:
```
github "stripe/stripe-ios" "ios11"
```

Note that this branch is not production-ready. We'll be evaluating our iOS 11 support more closely closer to the GM.

**Comment by TofPlay** [comment]
Hi @bg-stripe 
I perfectly understand "ios11" branch is not for production but it's help me to prepare my app for iOS 11 and very soon for Swift 4
Thanks 🙂

**Comment by fabiomassimo** [comment]
Sorry to bring this conversation up again but I was wondering if the team would consider the option to provide a bumped version that just compiles with Swift 3.2 (without changing the base SDK) to allow projects, that wants to use Xcode 9, to not have a broken dependency.
Due to the compiler version compatibility to Swift 3.0 the change would make the dependency working on both Xcode 8 and 9.

**Comment by bg-stripe** [comment]
Hey @fabiomassimo – our SDK is in Objective-C, so no changes should be necessary to use it with Swift 3.2 or 4.0. (Our Swift example app currently compiles with 3.2, and we'll update it to 4.0 closer to the GM).

**Comment by fabiomassimo** [comment]
Thank you for providing me these details.

It seems indeed that what prevented me to properly build the stripe framework was the fallback to the latest iOS SDK as base SDK (critical for Stripe as it integrates some Apple Pay features shipped within the SDK) rather than the Swift version in use.
