### ISSUE TITLE
3D Verification dismissing issue

### ISSUE THREAD

**Issue by gravera** [stripe/stripe-ios#717]
## Summary

If a redirection flow is started from an already presented view controller, pressing the 'Done' button on the SFSafariViewController causes the presented controller to dismiss also. The reason is pressing the 'Done' dismisses the SFSafariViewController by default and then in the delegate you are dismissing it again through -handleRedirectCompletionWithError method, which calls:
STPRedirectContext line 147
[self.safariVC.presentingViewController dismissViewControllerAnimated:YES
                                                                   completion:^{
                                                                       stpDispatchToMainThreadIfNecessary(^{
                                                                           [self handleRedirectCompletionWithError:nil];
                                                                       });
                                                                   }];

and since the SFSafariViewController is auto dismissed, this code makes the presentingViewController to dismiss also.

## Code to reproduce

Initiate redirection flow from already presented view controller.

## iOS version

9, 10

## Installation method

Cocoa pods

## SDK version

10.2.0

## Other information

A temporary fix for us would be to dismiss only self.safariVC in STPRedirectContext line 147, rather than self.safariVC.presentingViewController.

**Comment by bdorfman-stripe** [comment]
Thanks for the report! I'll look into it and get a fix for this out as soon as possible.

**Comment by bdorfman-stripe** [comment]
This should be fixed in version 11.0.0, released just now! Thanks again for the bug report.

**Comment by gravera** [comment]
Awesome. Thank you!
