### ISSUE TITLE
Card number validation methods not checking length for card type

### ISSUE THREAD

**Issue by simX** [stripe/stripe-ios#72]
STPCard's validation method validateNumber:error: does not validate against the length for the card type.  For example, this method returns YES for the number 5115 9151 1591 51, which needs two more digits to be a valid MasterCard number, and YES for 1231 2312 312, which is an unknown card type.

I'm not sure if this is a "bug" or not, because I could see the rationale for being a bit more permissive in validation for unknown card types, but it seems like at least known credit card types should validate against their proper length, which the framework is not doing.

Is there a better way to get more restrictive and accurate validation on credit card numbers?

**Comment by jflinter** [comment]
I know it's a bit hilariously late, but this is now addressed! Version 5.1.0 of stripe-ios now includes an `STPCardValidator` class, which should gracefully handle the failure modes you've described. Feedback welcome!
