### ISSUE TITLE
Integrate with Appcelerator

### ISSUE THREAD

**Issue by juanagu** [stripe/stripe-ios#722]
Hi, I trying integrate stripe for appcelerator using native appcelerate module, integrate stripe sdk using static framework method, but I have an exception when compile the project.

Error:

Undefined symbols for architecture arm64:
[TRACE] :    "_OBJC_CLASS_$_STPAPIClient", referenced from:
[TRACE] :        objc-class-ref in libco.clarika.stripe.a(CoClarikaStripeModule.o)
[TRACE] :    "_OBJC_CLASS_$_STPCard", referenced from:
[TRACE] :        objc-class-ref in libco.clarika.stripe.a(CoClarikaStripeModule.o)
[TRACE] :    "_OBJC_CLASS_$_Stripe", referenced from:
[TRACE] :        objc-class-ref in libco.clarika.stripe.a(CoClarikaStripeModule.o)
[TRACE] :  ld: symbol(s) not found for architecture arm64
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any suggestions?

**Comment by bg-stripe** [comment]
Hey @juanagu ! We generally reserve github issues for bug reports – if you're having trouble with your integration, you can email support@stripe.com
