### ISSUE TITLE
Mastercard Image Incomplete(non-template)

### ISSUE THREAD

**Issue by geeksweep** [stripe/stripe-ios#727]
To make it easier to diagnose your issue, please fill out the following:

## Summary

In the resources folder, the mastercard template has the "MasterCard" text in front of the logo but in the non-template version the "MasterCard" text is not there. Not sure if there is a reason here or just an oversight. 

## Code to reproduce

just looking at the images provided in the resources folder

## iOS version

n/a

## Installation method

via Cococapods 

## SDK version

What version of our SDK are you using? You can find this by either looking at your `Podfile.lock` (if you're using Cocoapods), your `Cartfile.resolved` (if you're using Carthage), or by looking at the value of `STPSDKVersion` in `STPAPIClient.h`.

STPSDKVersion = 10.2.0

## Other information

n/a

**Comment by geeksweep** [comment]
hey everyone - this might not even be a thing but wanted to create this in case this was just an oversight and if fixed would be more consistent with the other images.

**Comment by bdorfman-stripe** [comment]
Thanks for the report. I think this might be an oversight, I'll look into it!

**Comment by bg-stripe** [comment]
@geeksweep Sharp eye! The template and non-template images are used in different places in our UI – the MasterCard template image is used for saved cards in  `PaymentMethodsViewController`, while the non-template version is used when entering a new card in `PaymentCardTextField`.

<img src="https://user-images.githubusercontent.com/23086960/28539197-b88c697e-7065-11e7-95e7-57a65bd9f6fe.png" width="300px">___<img src="https://user-images.githubusercontent.com/23086960/28539245-d68e211a-7065-11e7-9fc7-583db32f4629.png" width="300px">

**Comment by geeksweep** [comment]
@bg-stripe the reason I was needing the logo for both was because I wasn't using the out of the box UI elements and using those images in my custom built UI - where I am not necessarily using it in the same way. I forget now but I am pretty sure that all the template and non-template images had the text in them except the mastercard one - so at the very least brought it up for consistency reasons. (to avoid confusion to anyone perhaps not using the built in UI elements). 

hope that makes sense.
