### ISSUE TITLE
Use of undeclared type 'STPEphemeralKeyProvider'

### ISSUE THREAD

**Issue by nitishrana28** [stripe/stripe-ios#730]
I am getting compile time errors. Attaching screenshot  
  
![screen shot 2017-07-11 at 11 15 41 am](https://user-images.githubusercontent.com/1484780/28052738-560fb886-662a-11e7-8b98-85ac35e18613.png)

Also many of the files are missing after installing via pod, like STPEphemeralKeyManager, STPEphemeralKey. Maybe more.
Already integrated Stripe and Alamofire

**Comment by bdorfman-stripe** [comment]
Hi @nitishrana28,

What version of the sdk do you have installed? The latest version (11.0) is a breaking change which added and removed many files. It looks like you have a mismatched version between the example code you are trying to run in `MyAPIClient` and the version of the sdk you have installed. If you are installing via cocoapods, I would double check that your Podfile has the version set to 11.0 or greater.

If you continue to have issues, I recommend writing in to support@stripe.com, as they can help you with all sorts of integration issues when using the iOS SDK.

Brian
