### ISSUE TITLE
STPSource Object Support alipay?

### ISSUE THREAD

**Issue by RushRunnerBoston** [stripe/stripe-ios#733]
To make it easier to diagnose your issue, please fill out the following:

Need create a STPSource object for alipay, helper constructor are available for any other payment method but not alipay.  Could you update that 

## SDK version 
11.0.0

**Comment by bdorfman-stripe** [comment]
Hi @RushRunnerBoston,

Thanks for your interest! We'll be adding helpers/constants/enum values for Alipay in an upcoming release. I'll post an update here when it ships.

Brian

**Comment by RushRunnerBoston** [comment]
Awesome, thank you so much

**Comment by bdorfman-stripe** [comment]
Alipay bindings are in version 11.2.0, released just a few seconds ago. Let us know if you any trouble with it!

Brian
