### ISSUE TITLE
Feature request: ability to supply STPPaymentMethodsViewController with a custom footer view

### ISSUE THREAD

**Issue by irace** [stripe/stripe-ios#756]
## Summary

I’d like to be able to supply a custom view in order to add a message akin to the “A standard 3% fee applies...” disclosure from the following Venmo screenshot.

![pasted image at 2017_07_31 09_15 am](https://user-images.githubusercontent.com/399560/28796350-3aa4247e-760b-11e7-8117-a5632c6a6b1b.png)

## Proposal

This is a little tricky since `STPPaymentMethodsViewController` wraps two other potential child view controllers that are each loaded asynchronously. Here’s a first pass at how this could work (note: my Objective-C is _super_ rusty):

`STPPaymentMethodsViewControllerDelegate` could have a new optional method that allows the delegate to supply a custom footer view (this delegate method would take the superview as an argument so that the superview’s width could be used to determine the view’s frame). Ideally this doesn’t leak the fact that it’s going to be installed as the `tableViewFooter`, but the documentation should indicate that Auto Layout is basically a no-go as a result, and that this view’s frame should already be set.

```objc
@optional

- (UIView *)paymentMethodsViewController:(STPPaymentMethodsViewController *)paymentMethodsViewController footerViewForSuperview:(UIView *)superview;
```

Next, both `STPPaymentMethodsInternalViewController` and `STPAddCardViewController` could get new methods like:

```objc
- (void)setFooterView:(UIView *)footerView {
    self.tableView.tableFooterView = footerView;
}
```

After installing a child view controller `STPPaymentMethodsViewController` could ask the delegate for a footer view, and if it gets one, pass it through to the child, whose view should be fully sized at this point.

```objc
// There might be a better way to do this. Again, my Objective-C has lapsed quite a bit
if ([self.delegate respondsToSelector@selector(paymentMethodsViewController:paymentMethodsViewController footerViewForSuperview:)] && [internal respondsToSelector:@selector(setFooterView:)]] {
    UIView *footerView = [self.delegate paymentMethodsViewController:self footerViewForSuperview:internal.view];
    [internal setFooterView:footerView];
}
```

I seem to *mostly* have this working, though had to make a couple of tweaks to avoid excess padding in the case where the “Remember me” cell is hidden (not feeling 100% confident that these are the “right” changes, but they seem to work for my needs):

![screen shot 2017-07-31 at 4 18 28 pm](https://user-images.githubusercontent.com/399560/28796565-09b27c16-760c-11e7-8e56-60251bd436dd.png)

Anyway, since I mostly have this working, I’m happy to open a formal pull request, I just wanted to make sure this was actually a desired addition and approach. Thanks!

**Comment by irace** [comment]
One alternative – which would be a little easier for developers who just want to add a string (but less flexible as well) – would be to have the delegate method simply return a string, and have the Stripe SDK responsible for specifying the label’s font/frame/etc.

**Comment by bdorfman-stripe** [comment]
Support for this (in a slightly different format than discussed here) was merged in https://github.com/stripe/stripe-ios/pull/792

We should have a new official release out soon that includes this, but you can try it out on latest master if you want. Thanks again for your work on this @irace !
