### ISSUE TITLE
STPPaymentMethodsViewController delegate is read only

### ISSUE THREAD

**Issue by raphaelcruzeiro** [stripe/stripe-ios#766]
To make it easier to diagnose your issue, please fill out the following:

## Summary

`STPPaymentMethodsViewController`'s delegate is read only.

## Code to reproduce

This code from Stripe's own Custom Integration guide will fail to compile due to the delegate property being ready only:
```
func paymentMethodsButtonTapped() {
    let paymentMethodsViewController = STPPaymentMethodsViewController()
    paymentMethodsViewController.delegate = self
    // STPShippingAddressViewController must be shown inside a UINavigationController.
    let navigationController = UINavigationController(rootViewController: paymentMethodsViewController)
    self.present(navigationController, animated: true, completion: nil)
}
```

## iOS version

Any

## Installation method

Cocoapods

## SDK version

11.2.0

**Comment by joeydong-stripe** [comment]
Hi @raphaelcruzeiro,

Thanks for the report. I see what you mean and will look into it. My initial impression is that we'll fix the example in the documentation. We recommend that you set the `delegate` during `init` only.

**Comment by raphaelcruzeiro** [comment]
Understood. Thanks for the answer @joeydong-stripe

I was under the impression that by initializing STPPaymentMethodsViewController with the parameterless initializer, I could avoid having to create a STPCustomerContext (as is the case of STPAddCardViewController). It seems that's not the case then?

As a follow up question: why does STPPaymentMethodsViewController works without explicitly creating a context and STPPaymentMethodsViewController doesn't?

**Comment by bdorfman-stripe** [comment]
`STPPaymentMethodsViewController` uses a Stripe Customer object as a backing store for its data (to fetch saved cards and save new cards). As such, it needs access to that data via an `STPCustomerContext`. In contrast, `STPAddCardViewController` on its own does not directly talk to or know about Customer objects, and so can be used standalone (but will not on its own save the customer's cards anywhere).

**Comment by raphaelcruzeiro** [comment]
I see. And that means that if I want to give my users the option of managing payment methods later own, I should ditch `STPAddCardViewController` and use `STPPaymentMethodsViewController` for both things, correct?

**Comment by raphaelcruzeiro** [comment]
That makes sense. Thanks @bdorfman-stripe

**Comment by joeydong-stripe** [comment]
Hi @raphaelcruzeiro,

Thanks again for notifying us about the outdated documentation. We just wrapped up a quick refresh of our "iOS Custom Integration" page along with updated sample code:

https://stripe.com/docs/mobile/ios/custom

If you need any further integration support, please email our team at support@stripe.com. Have a good one!
