### ISSUE TITLE
Feature request: Allow for providing a custom transitioningDelegate when presenting/pushing stripeVC

### ISSUE THREAD

**Issue by zaidmian** [stripe/stripe-ios#770]
To make it easier to diagnose your issue, please fill out the following:

## Summary

Our app uses custom transitions and we'd like to have the Stripe VC use the same transition as it's presented.

## Code to reproduce

N/A

## iOS version

All.

## Installation method

CocoaPods.

## SDK version

10.2

## Other information

N/A

**Comment by bg-stripe** [comment]
Hey @zaidmian , thanks for the feature request! We'll look into adding a `transitioningDelegate` property to `STPPaymentContext` to support custom transitions.
