### ISSUE TITLE
STPPaymentCardTextField: `placeholderColor` Does Nothing 

### ISSUE THREAD

**Issue by lukeharries** [stripe/stripe-ios#774]
## Summary

When using the STPPaymentCardTextField, setting the placeholderColor does not change the placeholder colour or tint of the card image placeholder. Even subclassing STPPaymentCardTextField and overriding the getter and setter of placeholderColor does not get around this issue.

## iOS version
iOS 10.3

## Installation method
Cocoapods

## SDK version
11.2.0

**Comment by lukeharries** [comment]
I found out that another library was overriding the style settings of the STPPaymentCardTextField. This can be closed

**Comment by bg-stripe** [comment]
Thanks for the update – glad you got to the bottom of this!
