### ISSUE TITLE
Crash on viewDidLoad.

### ISSUE THREAD

**Issue by LinhTN-AltPlus** [stripe/stripe-ios#775]
To make it easier to diagnose your issue, please fill out the following:

## Summary

I got this issue.

2017-08-18 10:03:26.518 Govi[24761:2488430] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[STPPaymentMethodsViewController viewDidLoad]: unrecognized selector sent to instance 0x7fdea3c78900'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010a67eb0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010a0ea141 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010a6ee134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   Stripe                              0x0000000106f2f3ac __STP_ASPECTS_ARE_BEING_CALLED__ + 6092
	4   CoreFoundation                      0x000000010a605656 ___forwarding___ + 534
	5   CoreFoundation                      0x000000010a6053b8 _CF_forwarding_prep_0 + 120
	6   Stripe                              0x0000000106f3fca6 -[STPCoreViewController viewDidLoad] + 54
	7   UIKit                               0x000000010755801a -[UIViewController loadViewIfRequired] + 1235
	8   UIKit                               0x000000010755845a -[UIViewController view] + 27
	9   UIKit                               0x00000001075a493b -[UINavigationController preferredContentSize] + 197
	10  UIKit                               0x0000000107537c0f -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 64
	11  UIKit                               0x0000000107533be3 __56-[UIPresentationController runTransitionForCurrentState]_block_invoke + 109
	12  UIKit                               0x00000001073c1853 _runAfterCACommitDeferredBlocks + 318
	13  UIKit                               0x00000001073ae81c _cleanUpAfterCAFlushAndRunDeferredBlocks + 532
	14  UIKit                               0x00000001073e0560 _afterCACommitHandler + 137
	15  CoreFoundation                      0x000000010a624717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	16  CoreFoundation                      0x000000010a624687 __CFRunLoopDoObservers + 391
	17  CoreFoundation                      0x000000010a609720 __CFRunLoopRun + 1200
	18  CoreFoundation                      0x000000010a609016 CFRunLoopRunSpecific + 406
	19  GraphicsServices                    0x000000010fa9fa24 GSEventRunModal + 62
	20  UIKit                               0x00000001073b5134 UIApplicationMain + 159
	21  Govi                                0x0000000101e92577 main + 55
	22  libdyld.dylib                       0x000000010b5f465d start + 1
	23  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

## iOS version

What version of iOS are you observing the problem on?

## Installation method

Installed via cocoapods v1.3.1

## Other information

Anything else you can include that'll make it easier for us to help you!

**Comment by bg-stripe** [comment]
Hey @LinhTN-AltPlus ,

Without more details on your integration, it's difficult for us diagnose what's going on here. I would recommend contacting support@stripe.com for further help getting your app integrated with Stripe, as they will likely be able to help walk you through this issue.

Best,
Ben

**Comment by LinhTN-AltPlus** [comment]
@bg-stripe 
I found the reason. It crash when I using **SFEmptyBackButton** with code:
                `SFEmptyBackButton.removeTitleFromAllViewControllers()`
Please check!

**Comment by bdorfman-stripe** [comment]
@LinhTN-AltPlus 

I'm not sure what `SFEmptyBackButton` is? It is not a class in our code. It sounds like you are using some other third party framework that may have a bug in it or that is interacting poorly with our framework. I would advise contacting the creators of `SFEmptyBackButton` or contacting Stripe developer support at support@stripe.com
