### ISSUE TITLE
Move “Add New Card” button to right bar button item (instead of section footer)

### ISSUE THREAD

**Issue by irace** [stripe/stripe-ios#776]
To make it easier to diagnose your issue, please fill out the following:

## Summary

Currently, `STPAddCardViewController`’s **Add New Card** button is stored in a table view section footer. This is fine when there are no cards (or a small amount), but after a few are added, a user may not realize that this button is there (it will be pushed off-screen, especially on smaller phones).

Instead, if put in a bar button item, it’ll always be visible regardless of how many cards the user has. Huzzah!

## Other information

I’m happy to open a PR for this – it’ll be real straightforward – just wanted to ensure this was desired before taking the time.

Thanks!
-Bryan

**Comment by bg-stripe** [comment]
Hey Bryan!

Thanks for the feedback – it's definitely not ideal that the Add New Card button can so easily disappear off screen. We currently have an "Edit" button where an "Add" button might go (for removing payment methods), so we'll have to think about this a bit more. I'll raise this with our team and see if we can come up with a good solution.

Ben

<img src="https://user-images.githubusercontent.com/23086960/29473630-7d186c92-8426-11e7-98e4-378aadc57c57.png" width="400px">
