### ISSUE TITLE
Adding new credit card results in Error using the Swift Demo project as well as own implementation.

### ISSUE THREAD

**Issue by davidseek** [stripe/stripe-ios#778]
To make it easier to diagnose your issue, please fill out the following:

## Summary

The title sums it up. Using the demo project as well as my own implementation I'm receiving the following error when trying to add a new Credit Card:

![img_5974](https://user-images.githubusercontent.com/17073950/29496190-0c6231be-85ce-11e7-9286-d4a49543aff3.PNG)

The Server is the provided Heroku Server and (test) Payments using Apple Pay are working just fine.

## Code to reproduce

```
func initPaymentContent(on: UIViewController) {
        
        let customerContext = STPCustomerContext(keyProvider: self)
        
        let context = STPPaymentContext(
            
            customerContext: customerContext,
            configuration: self.getConfig(),
            theme: STPTheme.default()
            
        )
        
        let userInformation = STPUserInformation()
        
        userInformation.billingAddress = self.getPrefferedShippingAddress()
        userInformation.shippingAddress = self.getPrefferedShippingAddress()
        
        context.prefilledInformation = userInformation
        context.paymentCurrency = "usd"
        
        context.hostViewController = on
        context.delegate = self
        
        self.paymentContext = context
        
    }
    
    func getConfig() -> STPPaymentConfiguration {
        
        let config = STPPaymentConfiguration.shared()
        
        config.publishableKey = self.stripeID
        config.appleMerchantIdentifier = self.merchantID
        config.companyName = "AppName"
        config.requiredBillingAddressFields = STPBillingAddressFields.full
        config.requiredShippingAddressFields = PKAddressField.all
        config.shippingType = STPShippingType.shipping
        config.additionalPaymentMethods = .all
        
        return config
        
    }

func getPaymentMethodsViewController(completion: @escaping STPContextDidChangeHandler) {
        
        self.stpContextDidChangeHandler = completion
    
        self.paymentContext.pushPaymentMethodsViewController()
        
    }

```

## iOS version

latest release version

## Installation method

pods

## SDK version

latest release version

## Other information

none

**Comment by bdorfman-stripe** [comment]
Hi @davidseek,

Sorry you're having trouble, let me see if I can help you work out the problem

The message you see is a somewhat generic error that can occur for several reasons so we'll have to do some more debugging. If you are seeing it when adding a card, the two most likely problems are: The card you are passing in is not valid (I would recommend using one of the [Stripe test card numbers](https://stripe.com/docs/testing#cards)) or your ephemeral key is not set up correctly and the new card can not be attached to the customer object.

I would recommend putting in breakpoints in at `StripeError.m` lines 53 and 57. One of these should be where the API response is being turned into that error message, and from here you can look at the full json response to see what is being returned, and the stack trace to see what API call is failing.

We try to keep Github Issues just for bug reports, so I would recommend writing in to Stripe support (support@stripe.com), as there is a full team of people ready to help you out with integration problems when using the SDK. 

I hope this helps!
Brian
