### ISSUE TITLE
Bitcoin

### ISSUE THREAD

**Issue by santiagofm** [stripe/stripe-ios#781]
Hey guys !
I'm trying to have bitcoin payments in my app and can't figure out how.

I'm creating a bitcoin source like so:
```objc
STPSourceParams *params = [STPSourceParams bitcoinParamsWithAmount:amount
                                                          currency:currency
                                                             email:email];
[[STPAPIClient sharedClient] createSourceWithParams:params completion:^(STPSource *source, NSError *error) {   
    ...
}];
```

The thing is that can't figure out a way to know when the user has paid and thus create the charge.
On the web sdk sources have webhooks to deal with this, on mobile is there another way to observe the status ?

Cheers

**Comment by joeydong-stripe** [comment]
Hi @santiagofm 😃 

I'm not sure what you mean by "web sdk sources". I believe you can set a [webhook handler](https://stripe.com/docs/sources/best-practices#the-required-use-of-webhooks) in the Stripe dashboard and have it ping your backend server when the source becomes `chargeable`. Can you please email support@stripe.com? They will help you get going with the integration.
