### ISSUE TITLE
ShippingViewController not displaying correctly

### ISSUE THREAD

**Issue by timroesner** [stripe/stripe-ios#782]
## Summary

When presenting (or pushing) the shipping view controller I don\t have the ability to enter an address. Both the back and next button return me to the previous VC and do not update any information (obviously)
 See screenshot below. 

## Code to reproduce

`paymentContext.pushShippingViewController()`

## iOS version

iOS 10.3.3

## Installation method

CocoaPods 

## SDK version

11.2.0

## Other information

 
![img_3563](https://user-images.githubusercontent.com/13894518/29908069-345ed65a-8dd4-11e7-9172-555d81a2ae58.PNG)

**Comment by joeydong-stripe** [comment]
Hi @timroesner,

Can you check if you set a value to `paymentContext.configuration.requiredShippingAddressFields`? Looks like I can reproduce this state when that is set to the default value of `None`.

**Comment by timroesner** [comment]
Thank you so much that helped a bunch.

Could you also give me a hint how to ask for the shipping method. paymentContext.configuration.shippingType only seems to take one value. In the docs you mentioned that when tapping next there should be a view to select that

**Comment by joeydong-stripe** [comment]
Glad that worked! We'll look into making that clearer.

Looks like our [Custom iOS Integration](https://stripe.com/docs/mobile/ios/custom#stpshippingaddressviewcontroller) documentation can help you out. Otherwise, please email support@stripe.com for integration help.

Have a good one!
