### ISSUE TITLE
Incorrect description of default card number placeholder

### ISSUE THREAD

**Issue by benpackard** [stripe/stripe-ios#784]
To make it easier to diagnose your issue, please fill out the following:

## Summary

The description for the card number placeholder does not match the behavior. According to the description:

> The placeholder for the card number field. Default is @"1234567812345678". If this is set to something that resembles a card number, it will automatically format it as such (in other words, you don't need to add spaces to this string).

However, the observed default placeholder is actually `4242424242424242`

## Code to reproduce

Observe any `STPPaymentCardTextField` with a default placeholder

## iOS version

iOS 10.3

## Installation method

Cocoapods

## SDK version

11.1.0

**Comment by benpackard** [comment]
Apologies, this is already fixed in the latest version (commit `bb9de9fbf56868de2173962b5d9449e88b2d8e43`)

**Comment by joeydong-stripe** [comment]
👍
