### ISSUE TITLE
Deleting Standard Connect Account

### ISSUE THREAD

**Issue by timroesner** [stripe/stripe-ios#788]
## Summary

A couple of test accounts have piled up in our test dashboard and I'd like to get rid of them, since this isn't possible with the dashboard I wrote a method on our backend which utilizes 
`account = Stripe::Account.retrieve(params[:acct])
    account.delete`

Unfortunately when calling this from the iOS SDK with Alamofire I get the error "Error: This application is not authorized to delete this account."

## Code to reproduce

iOS:
<code> func deleteMerchant(stripe_account_id: String) {
        let url = self.baseURL.appendingPathComponent("delete")
        let params: [String: Any] = [
            "acct": stripe_account_id
        ]
        Alamofire.request(url, method: .post, parameters: params)
        .responseString { response in
            switch response.result {
            case .success(let json):
                print(json)
            case .failure(let error):
                print(error)
            }
        }
    } </code>

Backend:
<code> post "/delete" do
  begin
    account = Stripe::Account.retrieve(params[:acct])
    account.delete
  rescue Stripe::StripeError => e
    status 402
    return "Error: #{e.message}"
  end

  status 200
  return "Deleted Account"
end </code>

## iOS version

iOS 10.3.3    Swift 3   Xcode 8.3.3

## Installation method

CocoaPods

## SDK version

11.2.0

## Comment

I'm aware that this isn't directly an iOS issue, but since the documentation is lacking important parts in this area I opened this issue here.

**Comment by bg-stripe** [comment]
Hey @timroesner – since this isn't an issue with the iOS SDK, can you contact support@stripe.com ? They'll be able to help you with using our ruby bindings to delete those test accounts.

**Comment by wcandillon** [comment]
@timroesner Are you able to delete connect accounts via this API method? I'm getting the same error.

**Comment by timroesner** [comment]
So on the server I have this code in Ruby:
```ruby
post '/disconnect_account' do
  begin
    account = Stripe::Account.retrieve(params[:acct])
    account.deauthorize("YOUR_PLATFORM_ID")
  rescue Stripe::StripeError => e
    status 402
    return "Error: #{e.message}"
  end

  status 200
  return "Disconnected Account"
end
```

And on the client in Swift I have this:

```swift
func disconnectMerchant(stripe_account_id: String) {
        let url = self.baseURL.appendingPathComponent("disconnect_account")
        let params: [String: Any] = [
            "acct": stripe_account_id
        ]
        Alamofire.request(url, method: .post, parameters: params)
        .responseString { response in
            switch response.result {
            case .success(let json):
                print(json)
            case .failure(let error):
                print(error)
            }
        }
    }
```

Working pretty well for us
