### ISSUE TITLE
Not working Swift 3 application integration using xcode "Version 8.3.3 (8E3004b)"  

### ISSUE THREAD

**Issue by gsalve** [stripe/stripe-ios#793]
To make it easier to diagnose your issue, please fill out the following:

## Summary
Giving following parsing error
"module file was created by an older version of the compiler; rebuild 'PassKit' and try again: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/x86_64/PassKit.swiftmodule"

## Code to reproduce
Not able to run sample codes. Objective C project is working but swift project not working giving parsing error.

## iOS & SDK version 
- Version 8.3.3 (8E3004b)
- Swift 3 
- Deployment target default 10.3

## Installation method
Pod installation
Run Sample code 

## Other information
Sample objective C project running without any issues
<img width="1675" alt="objective c" src="https://user-images.githubusercontent.com/5080586/30339710-863c09a0-980d-11e7-9eec-817cabf9dd52.png">
Sample Swift Code project giving following issues
<img width="1676" alt="swift" src="https://user-images.githubusercontent.com/5080586/30339709-85e091d8-980d-11e7-9bfe-c79b63917077.png">

**Comment by bdorfman-stripe** [comment]
PassKit is an Apple Framework, so this seems like an issue with your local setup, and not with Stripe. You should try cleaning your build folder and/or restarting Xcode and trying again. (hold down Option key then click Product -> Clean Build Folder).

**Comment by gsalve** [comment]
Thanks for the info. Resolved the issue. Deleted all the Paskit modules from that directory and it's working now... 
rm -rf /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/x86_64/PassKit.swiftmodule
