### ISSUE TITLE
Feature request: Access to Card metadata from STPCard

### ISSUE THREAD

**Issue by davidsantiago** [stripe/stripe-ios#807]
To make it easier to diagnose your issue, please fill out the following:

## Summary

It's currently inconvenient to access the metadata on an STPCard, as there's no accessor on the class as far as we can tell. This metadata is stored and accessible when using another API (we do this with Java on the backend). 

## Code to reproduce

No code for this. 

## iOS version

iOS 10/11

## Installation method

Via Cocoapods

## SDK version

11.1.0

## Other information

We'd be glad to submit code for this, if that's agreeable to you.

**Comment by joeydong-stripe** [comment]
Hi @davidsantiago, thanks for opening the issue.

That definitely sounds like a good idea! We will take a look.

In the meantime, if you haven't already done so, you should be able to read the `metadata` like so:

```
STPCard *card = ...;

NSDictionary *metadata = card.allResponseFields[@"metadata"];
```

**Comment by davidsantiago** [comment]
Thanks so much!
