### ISSUE TITLE
iOS7 Crash

### ISSUE THREAD

**Issue by huguesbr** [stripe/stripe-ios#81]
Is this example suppose to support iOS7?

It crash on https://github.com/stripe/stripe-ios/blob/master/Example/StripeExample/ViewController.m#L55
as it try to do 

```
 PKShippingMethod *shippingMethod = [PKShippingMethod summaryItemWithLabel:@"Llama Express Shipping" amount:[NSDecimalNumber decimalNumberWithString:@"20.00"]];
 [paymentRequest setShippingMethods:@[shippingMethod]];
```

and `shippingMethod` is nil because `PKShippingMethod` is iOS8 only

**Comment by indoracer** [comment]
I'm seeing this crash too using your latest SDK on a Swift app.  Our deployment target is iOS 7 and we are seeing the crash when running iOS 7 (not 8).  The crash (EXC_BAD_ACCESS) happens at: if test != nil or whenever I next access test

        let test = Stripe.paymentRequestWithMerchantIdentifier(Constants.ApplePayMerchantID)
        
        if test != nil {
            println("not nil")
        }
