### ISSUE TITLE
Feature Request: Access to methods to delete the user's cards

### ISSUE THREAD

**Issue by davidsantiago** [stripe/stripe-ios#812]
To make it easier to diagnose your issue, please fill out the following:

## Summary

We've designed a custom UI for allowing users to control their payment methods that we think works better with how our app works, and we'd like to be able to let the user delete cards in it. The problem is that the SDK appears to keep all methods useful for this private. There are a number of workarounds that I imagine would work, including forking the SDK and changing 'private' to 'public' on a function, manually hitting the Stripe API endpoint, or creating endpoints on our servers to perform this operation. So it's hard to see why this is kept private from us. 

## Code to reproduce

No code. The useful function would be `- (void)detachSourceFromCustomer:(id<STPSourceProtocol>)source completion:(STPErrorBlock)completion` in STPCustomerContext or `+ (void)deleteSource:(NSString *)sourceID fromCustomerUsingKey:(STPEphemeralKey *)ephemeralKey completion:(STPSourceProtocolCompletionBlock)completion` in STPAPIClient, but both are inaccessible to users outside the module. 

## iOS version

All versions.

## Installation method

CocoaPods.

## SDK version

11.3

## Other information

**Comment by bdorfman-stripe** [comment]
Hi @davidsantiago,

We just released version 11.4.0 which makes the two previously private `STPCustomerContext` methods public. We hope this improves the integration for your use case. Don't hesitate to reach out with any other bugs or feature requests you have!

Thanks,
Brian

**Comment by davidsantiago** [comment]
Wonderful! Such a quick turnaround! Thank you so much guys!
