### ISSUE TITLE
Dismiss shipping without shipping method

### ISSUE THREAD

**Issue by nikolas7892** [stripe/stripe-ios#817]
To make it easier to diagnose your issue, please fill out the following:

## Summary

I'm trying to (in Swift) simply record the user shipping address without the shipping method.

## Code to reproduce
I've attempted to dismiss and return on the "didUpdateShippingAddress" method.

` func paymentContext(_ paymentContext: STPPaymentContext, didUpdateShippingAddress address: STPAddress, completion: @escaping STPShippingMethodsCompletionBlock) {
        
        guard let countryAddress = address.country else { return }
        guard let postalCodeAddress = address.postalCode else { return }
        guard let cityAddress = address.city else { return }
        guard let nameAddress = address.name else { return }
        guard let streetLineAddress = address.line1 else { return }
        guard let apartmentLineAddress = address.line2 else { return }
        guard let stateAddress = address.state else { return }
        guard let phoneAddress = address.phone else { return }
        
        shippingCountry = countryAddress
        shippingZipCode = postalCodeAddress
        shippingCity = cityAddress
        shippingName = nameAddress
        shippingStreetLine = streetLineAddress
        shippingApartmentLine = apartmentLineAddress
        shippingState = stateAddress
        shippingPhone = phoneAddress
        return
      
    }`

or 

` func paymentContext(_ paymentContext: STPPaymentContext, didUpdateShippingAddress address: STPAddress, completion: @escaping STPShippingMethodsCompletionBlock) {
        
        guard let countryAddress = address.country else { return }
        guard let postalCodeAddress = address.postalCode else { return }
        guard let cityAddress = address.city else { return }
        guard let nameAddress = address.name else { return }
        guard let streetLineAddress = address.line1 else { return }
        guard let apartmentLineAddress = address.line2 else { return }
        guard let stateAddress = address.state else { return }
        guard let phoneAddress = address.phone else { return }
        
        shippingCountry = countryAddress
        shippingZipCode = postalCodeAddress
        shippingCity = cityAddress
        shippingName = nameAddress
        shippingStreetLine = streetLineAddress
        shippingApartmentLine = apartmentLineAddress
        shippingState = stateAddress
        shippingPhone = phoneAddress
        completion(.valid, nil, [], nil)
      
    }`

## iOS version

iOS11

## Installation method

cocoapods

**Comment by bg-stripe** [comment]
Hey @nikolas7892 ,

You should be be able to get the shipping view controller to dismiss without showing shipping methods by passing nil for shipping methods (rather than an empty array). We should handle the empty array case too though – thanks for catching the bug!

```
completion(.valid, nil, nil, nil)
```

Best,
Ben

**Comment by nikolas7892** [comment]
The only problem is that the payment cannot be completed after the successful dismissal. Every time I try to complete the purchase, I receive the shipping dialogue..

**Comment by marcus-hiles** [comment]
Hi had same issue, but got mine to work!!!

Here's what I did:
In the CheckoutViewController.swift stripe file, I modified the lines codes below

@objc func didTapBuy() {
        self.paymentInProgress = true
        self.paymentContext.requestPayment()
}

TO:

@objc func didTapBuy() {
        self.paymentInProgress = true
        self.newMethodToProcessPayment(amount: self.paymentAmount,
                                    shippingAddress: self.paymentContext.shippingAddress,
                                    shippingMethod: self.paymentContext.selectedShippingMethod)
    }


AND created a new method in that file that fires to my server to make the payment, without going through the normal process of asking for shipping method. Below is the newMethodToProcessPayment() function:

func newProcessPaymentAction(amount: Double, shippingAddress: STPAddress?, shippingMethod: PKShippingMethod?){
        
        let url = URL(string: "https://your-api-url-to-make-stripe-charge")
        var params: [String: Any] = [
            "customer": "your-customer-id",
            "amount": (amount * 100), //stripe accepts only integers...so when u send 1520, stripe sees it as 15.20
            "currency": "USD"
        ]
        params["shipping"] = STPAddress.shippingInfoForCharge(with: shippingAddress, shippingMethod: shippingMethod)
        Alamofire.request(url!, method: .post, parameters: params)
            .validate(statusCode: 200..<300)
            .responseString { response in
                switch response.result {
                    case .success:
                        print("###### SUCCESSFUL STIPE PAYMENT)")
                    case .failure(let error):
                        print("###### ERROR STIPE PAYMENT :: \(error)")
                }
        }
    }


AND that should work for you ... VOILAAA!!!
