### ISSUE TITLE
stripe not working with paypal library in a single project

### ISSUE THREAD

**Issue by vuevrn** [stripe/stripe-ios#820]
To make it easier to diagnose your issue, please fill out the following:

## Summary

A simple summary of the problems you're having.

## Code to reproduce

If possible, please include a brief piece of code (or ideally, a link to an example project) demonstrating the problem you're having.

## iOS version

What version of iOS are you observing the problem on?

## Installation method

How did you install our SDK?

## SDK version

What version of our SDK are you using? You can find this by either looking at your `Podfile.lock` (if you're using Cocoapods), your `Cartfile.resolved` (if you're using Carthage), or by looking at the value of `STPSDKVersion` in `STPAPIClient.h`.

## Other information

Anything else you can include that'll make it easier for us to help you!

stripe version 10.2.0
installed with   pod 'Stripe'
ios version 10.2.1

I had installed stripe sdk and it was working fine, I was getting the token in
addCardViewController didCreateToken delegate of STPAddCardViewController which was passed to our server and was receiving success for payment charging.

however, I had to integrate paypal too. After I installed paypal in the same project through pods, paypal works fine, but I got following issues with stripe 

- I do get the token from addCardViewController didCreateToken but that token never works with our server web service and I get "No such token No payment was made" in the response.

after that I added paypal library through manual drag and drop, paypal still works fine. but stripe didn't worked either. same issue as above.

so stripe alone works fine. but doesn't work when integrating paypal in the same project. 

can you please help solve this? or tell me why is this happening?

thank you.

**Comment by bdorfman-stripe** [comment]
HI @vuevrn,

This Github page is reserved for bugs with the Stripe iOS SDK. I suggest you write in to support@stripe.com as they can help you with integration issues getting the SDK to work with your app.

Brian
