### ISSUE TITLE
Text field moves up

### ISSUE THREAD

**Issue by AlexanderSokira** [stripe/stripe-ios#824]
## Summary

Text field moves up in the page of adding a card. 
It looks like an issue in interaction between STPAddCardViewController and STPKeyboardDetectingViewController controllers.

## Code to reproduce

1. Present presentPaymentMethodsViewController from STPPaymentContext
2. Try to add a new card. See Add a Card view
3. Verify that keyboard appears
4. Tap Done button on the keyboard to hide it
5. Tap on the text field again to make keyboard visible
6. Text field moves up
7. Repeat 4-6 steps twice or thrice. Note that the text field hides under a top bar

## iOS version

iOS 10.1.1, 11+

## Installation method

Via CocoaPods

## SDK version

11.4.0

**Comment by bdorfman-stripe** [comment]
Hi @AlexanderSokira,

I'm having trouble reproducing your issue. What hardware are you running on? What are your `STPPaymentConfiguration` settings around adding cards?  Can you send me a video of the bug?

Thanks,
Brian

**Comment by AlexanderSokira** [comment]
Hi Brian,

I have example with simulator at this moment. It is just to show how it looks. And that issue looks the same on devices. I got the same behavior on iPhone 5C (iOS 10.1.1), iPhone 6 (iOS 10.1.1), iPhone 7(iOS 11.0.3)





Best regards,
Alex

**Comment by bdorfman-stripe** [comment]
Are you using a non-standard keyboard? I am not sure how to do your step 2 "Tap Done button on the keyboard". In my simulator I see a numpad keyboard that does not include a done button.

**Comment by AlexanderSokira** [comment]
Ops, you absolutely right. I’ve found the reason. There was used IQKeyboardManagerSwift pod and it warns that third-party libraries are not responsible to handle it in a correct way. So I close it issue.

Thanks Brian
