### ISSUE TITLE
Has anyone got the sample Standard Integration to work?

### ISSUE THREAD

**Issue by nboyd-sportdx** [stripe/stripe-ios#825]
No matter what I try, I get an error.  Response status code was unacceptable:  403.  Tried a few months ago, didn't work...gave up for another day.

A simple summary of the problems you're having.
I have an account with strip and I'm using my publishable test key.
I have deployed to Heroku.  Everything seems fine there

## Code to reproduce

No code to provide...this happens when I tap on an item and it navigates to a screen.  There is an activity indicator in the Payment textfield and that's where the error occurs after a few seconds

## iOS version

What version of iOS are you observing the problem on? 10 and 11

## Installation method

Using the instructions provided here:  https://github.com/stripe/stripe-ios

## SDK version

static NSString *const STPSDKVersion = @"11.4.0";

## Other information

Keep up the good work.  (no sarcasm)

**Comment by bdorfman-stripe** [comment]
Hi @nboyd-sportdx,

I recommend you write in to support@stripe.com. They can help you with integration problems with the SDK.

Brian
