### ISSUE TITLE
Crash (unrecognized selector sent to instance) in 11.4.0 when deserialize STPCustomer

### ISSUE THREAD

**Issue by andproff** [stripe/stripe-ios#826]
To make it easier to diagnose your issue, please fill out the following:

## Summary

After update to 11.4.0 we got next problem:
When the SDK attempts to deserialize STPCustomer with sources, app even crash.

```
-[__NSArray0 stp_dictionaryByRemovingNonStrings]: unrecognized selector sent to instance 0x60c00000c650
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArray0 stp_dictionaryByRemovingNonStrings]: unrecognized selector sent to instance 0x60c00000c650'
```
## Code to reproduce

Actually problem in your code:
STPCard.m line 201:
`card.metadata = [dict[@"metadata"] stp_dictionaryByRemovingNonStrings];` that means you try to work with the `NSDictionary`
but your API return `metadata = ( );` that means metadata is an Array

## iOS version

Found in iOS11 but I think this not matter

## Installation method

Cocoapods

## SDK version

11.4.0

## Other information

Anything else you can include that'll make it easier for us to help you!

**Comment by bdorfman-stripe** [comment]
Hi @andproff,

Sorry you're having trouble. Can you send us an example of the raw JSON you are seeing? As far as we can tell from our end the Stripe API should always return a dictionary value for metadata so we are trying to track down what is happening for you. 

Also, how are you getting the data you are feeding into the customer parsing code? Are you using ephemeral key / STPCustomerContext or do you have a custom backend api adapter?

Thanks,
Brian

**Comment by andproff** [comment]
Hello Brian
> Can you send us an example of the raw JSON you are seeing?

find below raw JSON
```
{
  "status": "ok",
  "stripeCustomer": {
    "id": "cus_B5D9SdDuEfqLkm",
    "object": "customer",
    "account_balance": 0,
    "created": 1500887973,
    "currency": null,
    "default_source": "card_1BGSkxHGJFW1N235uGxYRAA3",
    "delinquent": false,
    "description": "Leonardo DiCaprio",
    "discount": null,
    "email": null,
    "livemode": false,
    "metadata": {
      "UUID": "8C636BAD-82EE-4252-AEDE-8A304D164A2F"
    },
    "shipping": null,
    "sources": {
      "object": "list",
      "data": [
        {
          "id": "card_1BGSkxHGJFW1N235uGxYRAA3",
          "object": "card",
          "address_city": "London",
          "address_country": "United Kingdom",
          "address_line1": "Basement",
          "address_line1_check": "pass",
          "address_line2": "2a Wetherby Place",
          "address_state": "",
          "address_zip": "SW7 4ND",
          "address_zip_check": "pass",
          "brand": "Visa",
          "country": "US",
          "customer": "cus_B5D9SdDuEfqLkm",
          "cvc_check": "pass",
          "dynamic_last4": null,
          "exp_month": 4,
          "exp_year": 2024,
          "fingerprint": "LNcufKWmhM6U3vWO",
          "funding": "credit",
          "last4": "4242",
          "metadata": [],
          "name": "Leonardo DiCaprio",
          "tokenization_method": null
        }
      ],
      "has_more": false,
      "total_count": 1,
      "url": "\/v1\/customers\/cus_B5D9SdDuEfqLkm\/sources"
    },
    "subscriptions": {
      "object": "list",
      "data": [],
      "has_more": false,
      "total_count": 0,
      "url": "\/v1\/customers\/cus_B5D9SdDuEfqLkm\/subscriptions"
    }
  }
}
```
> Also, how are you getting the data you are feeding into the customer parsing code? Are you using ephemeral key / STPCustomerContext or do you have a custom backend api adapter?

Actually we use a custom backend api adapter

Don't hesitate to ask me any questions.
Andrei

**Comment by bdorfman-stripe** [comment]
Great thanks! Is this the raw data you are receiving in your iOS app from your server, or the data your server is receiving from the Stripe API? Often parsing bugs like this are caused by a merchant's server side code not forwarding the json through completely un-modified to the iOS app's backend api adapter, so I just want to rule that cause out.

**Comment by andproff** [comment]
> Is this the raw data you are receiving in your iOS app from your server, or the data your server is receiving from the Stripe API?
This raw data from our server

**Comment by bdorfman-stripe** [comment]
Can you check what JSON data your server is receiving from the Stripe API? It seems possible that on your own backend some code path is converting an empty or absent metadata key into an empty array instead of an empty dictionary.

**Comment by andproff** [comment]
Already I am doing that (after your question about receiving data). 
I need few time.

**Comment by bdorfman-stripe** [comment]
Great thanks! Sorry I didn't mean to rush you :)

**Comment by andproff** [comment]
Finally got direct response from Stripe API
```
{
        "id": "card_1BEDd8HGJFW1N235jC9p3zoo",
        "object": "card",
        "address_city": "",
        "address_country": "United Kingdom",
        "address_line1": "",
        "address_line1_check": null,
        "address_line2": "",
        "address_state": "",
        "address_zip": "",
        "address_zip_check": null,
        "brand": "MasterCard",
        "country": "US",
        "customer": "cus_Bb3QzzNvmp7XZV",
        "cvc_check": "pass",
        "dynamic_last4": null,
        "exp_month": 12,
        "exp_year": 2018,
        "fingerprint": "wdiYL4AmR0jmYB84",
        "funding": "credit",
        "last4": "4444",
        "metadata": {},
        "name": "John Mastercard",
        "tokenization_method": null
      }
```
but problem appear after using PHP library

```
$stripeCustomerData = $stripeService->getCustomer($stripeCustomer->Payment_Platform_ID);

           return response()->json(
                [
                    'status'         => 'ok',
                    'stripeCustomer' => $stripeCustomerData,
                ]
            );
```
anyway best practice before call any function from undefined NSObject, is check if can respond to selector or if is kind of some class

**Comment by bdorfman-stripe** [comment]
Thanks for the update! We'll investigate putting in more guards around json response objects for a future release, but for now going to mark this as closed.
