### ISSUE TITLE
Apple Pay currency code documentation

### ISSUE THREAD

**Issue by toemat** [stripe/stripe-ios#828]
## Summary

PKPaymentAuthorizationViewController:paymentRequest returns nil when currencyCode is "usd" but works correctly for "USD". However, the documentation at https://stripe.com/docs/mobile/ios/custom#apple-pay specifies "usd".

The lowercase "usd" has worked in the past... Does the documentation need to be updated?

## Code to reproduce

`
let paymentRequest = Stripe.paymentRequest(withMerchantIdentifier: merchantIdentifier, country: "US", currency: "usd")`
`...`
`let paymentAuthorizationViewController = PKPaymentAuthorizationViewController(paymentRequest: paymentRequest)`

## iOS version

11.0.1

## Installation method

Cocoapods

## SDK version

11.4.0

## Other information

Noticed after updating from Stripe 10.*

**Comment by bdorfman-stripe** [comment]
Hmm, possibly Apple's implementation of `PKPaymentRequest` or `PKPaymentAuthorizationViewController` has silently changed in iOS11 to require capitalized currency codes. Thanks for flagging we'll investigate either updating our docs or auto-capitalizing the strings for you.
