### ISSUE TITLE
largeTitleDisplayMode on shipping and payments controller 

### ISSUE THREAD

**Issue by ReeceHumphreys** [stripe/stripe-ios#830]
**## Summary**

There is no method to override the default behavior on the shipping and payments controllers navigationItem to support largeTitleDisplayMode for iOS 11

**## Code to reproduce**

N/A

**## iOS version**

iOS 11.1

**## Installation method**

Cocoapods

**## SDK version**

11.4.0

**Comment by danj-stripe** [comment]
Hi Reece,

Thanks for opening this issue. We'd like to fix this for you, but I need to know more about it. Can you provide some more details about how you're integrating with the SDK, and what you're trying to accomplish?

Are you using `STPPaymentContext` with the `present...` methods or the `push...` methods? Or are you using the Custom Integration Guide, and directly instantiating the VCs?

Thanks!
Dan

**Comment by ReeceHumphreys** [comment]
Hi Dan,

I am currently utilizing the push method on STPPaymentContext. It is inheriting the current largeTitleDisplayMode behavior from the previous controller which is resulting in some layout issues on the Simulator. I have attached a screenshot of the simulator that demonstrates this issue.
It was produced on the iPhone X simulator running iOS 11.1.

As you can see in the screenshot there appears to be a large amount of space between the top of the box image and the navigation bar. I attempted to resolve this issue by setting largeTitleDisplayMode = .never on the payment controller and shipping controller but there is no way to access the navigationItem when presenting these controllers using STPPaymentContext.

![simulator screen shot - iphone x - 2017-11-11 at 16 50 22](https://user-images.githubusercontent.com/14209515/32693895-f3dd8354-c700-11e7-8218-68ca36516571.png)

**Comment by bg-stripe** [comment]
Hey @ReeceHumphreys – thanks for the additional info. We'll try to get a fix out in an upcoming release.
