### ISSUE TITLE
Remove "Use Billing" button

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#831]
## Summary

At the payment method view controller, we are not asking for a billing address. 
Nevertheless, In the standard shipping view controller, it shows the "Use Billing" button. When clicking on the "Use billing" button - the button simply disappears and nothing happens. 

## Code to reproduce

Setup the config like that:
```
        let config = STPPaymentConfiguration.shared()
        config.requiredBillingAddressFields = .none
        config.requiredShippingAddressFields = [.postalAddress, .phone]
        config.shippingType = .shipping

```

## iOS version

11

## Installation method

Github

## SDK version

11.4.0

**Comment by danj-stripe** [comment]
Thanks for the bug report. I'm able to reproduce the bug, and we'll be looking into a fix for it.

**Comment by danj-stripe** [comment]
@odedharth We've just released [11.5.0](https://github.com/stripe/stripe-ios/releases/tag/v11.5.0), which should fix this issue. (If it doesn't, please let us know!)

**Comment by odedharth** [comment]
@danj-stripe yep, it's fixed now, thanks!

**Comment by yonilevy** [comment]
This seems to still be happening in some scenarios. E.g. if I call `[paymentContext presentShippingViewController]` twice, the "Use Billing" button will show up on the 2nd open. Also if the shipping VC is presented by a call to `[paymentContext requestPayment]`. Using iOS 12.2, Stripe SDK 15.0.1 (on an iPad if it matters).

**Comment by yonilevy** [comment]
btw from a little debugging, the button seems to show up because the `billingAddress` returns true to `hasPartialPostalAddress`, because its country is set to `"US"`. Not sure if it's a test-card behavior, but I'd say it's a bit unexpected.
