### ISSUE TITLE
Dispatch email upon payment completion?

### ISSUE THREAD

**Issue by nikolas7892** [stripe/stripe-ios#832]
Is there anyway to dispatch an email automatically to a customer without server side code?

**Comment by danj-stripe** [comment]
Hi @nikolas7892,

The Stripe documentation on sending Email Receipts may be what you're looking for:  
https://stripe.com/docs/dashboard/receipts

We generally reserve Github issues for bugs and feature requests for the Stripe iOS SDK. You should send an email to support@stripe.com if you have more questions about this.
