### ISSUE TITLE
Add UITextContentType for any relevant text fields to support auto-fill on iOS 11

### ISSUE THREAD

**Issue by dmcgloin** [stripe/stripe-ios#836]
## Summary

Feature request: Add UITextContentType attribute for any relevant text fields to support auto-fill iOS 11.

Examples:

Address, City, State, Zip, Credit Card

## iOS version

iOS 11

## Installation method

UI Examples 

## SDK version

11.5.0

**Comment by bg-stripe** [comment]
@dmcgloin Thanks for the feature request! We'll try to get this into an upcoming release.
