### ISSUE TITLE
"Use of unresolved identifier PaymentContextFooterView"

### ISSUE THREAD

**Issue by halinebr** [stripe/stripe-ios#837]
To make it easier to diagnose your issue, please fill out the following:

## Summary

Trying to create a customer footer view in Payment Methods View Controller. Using the code from the standard integration example, I receive the aforementioned compile error.

## Code to reproduce

Using almost the exact same CheckOutViewController from Standard Integration Example.

## iOS version

Not relevant, but iOS 11 & iOS 10.3, XCode 9.1

## Installation method

pods (Stripe (11.5.0))

## SDK version

Stripe (11.5.0)

## Other information

Thanks!

**Comment by bdorfman-stripe** [comment]
Hi @halinebr,

`PaymentContextFooterView` is the example footer view included in the project at `PaymentContextFooterView.swift`. It is not necessarily intended to be used in your own projects, you should replace references to that footer view class with whatever view you want to be the footer in your app.

If you're having trouble integrating the Stripe SDK, I suggest writing in to support@stripe.com, as they can help you with any questions you might have.

Hope that helps,
Brian
