### ISSUE TITLE
Incomplete workflow when using STPShippingTypeDelivery as shipping type

### ISSUE THREAD

**Issue by flexaddicted** [stripe/stripe-ios#839]
## Summary

I'm using the standard integration example. If I set the shipping type as `STPShippingTypeDelivery`, the payment context does not complete correctly (i.e. when `paymentContext.requestPayment()` is invoked through the buy button). After having inserted the details of the card, a delivery view is presented. On tapping Done the delivery controller is presented again.

## Code to reproduce

Set the delivery type using Settings view. Choose a product to buy. Tap Buy button. Insert the card details. Tap Done. Insert delivery details. Tap Done. Delivery details are presented again.

## iOS version

iOS 11

## Installation method

Carthage and Dynamic Framework

## SDK version

11.5.0

**Comment by danj-stripe** [comment]
@flexaddicted You're right, that's a bug. We'll try to get a fix into an upcoming version.

If you need a workaround in the mean time, deleting the implementation of `paymentContext:didUpdateShippingAddress:completion:` in the `STPPaymentContextDelegate` should work.

In our standard integration sample code, that's [implemented here](https://github.com/stripe/stripe-ios/blob/243da135f73840c781011c92610197be5ca41ffc/Example/Standard%20Integration%20(Swift)/CheckoutViewController.swift#L250-L252).
