### ISSUE TITLE
Versioning strategy [discussion/suggestion]

### ISSUE THREAD

**Issue by raylillywhite** [stripe/stripe-ios#84]
As a Stripe user that uses Cocoapods, I would find it very helpful if the Stripe iOS library followed [Semantic Versioning](http://semver.org), or at least had a well documented versioning strategy. This would allow us to immediately know from the version number whether there are breaking changes (indicated by a new major version), or new functionality (new minor version), or simply bug fixes (new patch version). With Cocoapods, I had previously used `pod 'Stripe', '~> 1.0'`, which under Semantic Versioning would allow me to automatically install any non-breaking updates via Cocoapods. But with Stripe 1.2 introducing breaking changes, I had to change that to something like '~> 1.1.0' so that only new patch versions will be installed.

I'm not sure if this warrants opening another issue on the PaymentKit repo, but I believe there were also breaking changes with the transition to a 3-letter prefix, without incrementing the major version, that would cause similar issues.

I'm not particularly tied to the Semantic Versioning method - it just seems to be the most commonly used versioning strategy. The useful part would just be having a reliable way to know when to expect breaking changes just from the version number.

**Comment by billinghamj** [comment]
Same issue just happened with the deprecation of PaymentKit...
