### ISSUE TITLE
Billing address no postal code issue for countriesWithNoPostalCodes

### ISSUE THREAD

**Issue by snamrata007** [stripe/stripe-ios#840]
## Summary
I have integrated this SDK to My app which has requirement to show postal code in STPAddCardViewController class.

```
Code:
STPPaymentConfiguration.shared().requiredBillingAddressFields = .zip
```

But when an user selects **"Macau(China)"** as his region, SDK is restricting postal code field to be appeared in UI and also done button is always been disabled because some countries have optional postal code.
So how can we check device region dynamically and based on that set requiredBillingAddressFields as (zip or none) ?

## iOS version

11.1

## Installation method
CocoaPods

## SDK version
11.5.0

![simulator screen shot - iphone 7 plus - 2017-11-25 at 03 25 55](https://user-images.githubusercontent.com/25499330/33224537-6c20fa96-d190-11e7-83a8-68a62e01e1f8.png)

**Comment by danj-stripe** [comment]
Hi @snamrata007,

`requiredBillingAddressFields = .zip` is *supposed* to work the way you're asking: it requires a postal code for regions that use them, and it skips the postal code in regions (like Macau) that do not.

We'll work on getting a fix into an upcoming version that ensures the Done button is properly enabled when the user has finished entering their card details & there's no postal code.
