### ISSUE TITLE
STPPaymentCardTextField.becomeFirstResponder not working when STPPaymentCardTextField filled out

### ISSUE THREAD

**Issue by DanielTrov** [stripe/stripe-ios#841]
## Summary

When STPPaymentCardTextField is completely filled out and is not the first responder, trying to set it as first responder doesn't work.

## Code to reproduce

```
import Stripe
import UIKit

class ViewController: UIViewController {

    @IBOutlet weak var paymentCardTextField: STPPaymentCardTextField!
    
    @IBAction func editButtonTapped(_ sender: Any) {
        paymentCardTextField.becomeFirstResponder()
    }
    
    @IBAction func doneButtonTapped(_ sender: Any) {
        paymentCardTextField.resignFirstResponder()
    }
}
```

## iOS version

iOS 11

## Installation method

Pod

## SDK version

11.5.0

## Other information

Repro steps:
1. Fill out STPPaymentCardTextField
2. Tap Done button
3. Tap Edit button
4. STPPaymentCardTextField doesn't become the first responder. The user should be able to edit the payment card.

**Comment by danj-stripe** [comment]
Hi @DanielTrov, thanks for the bug report. I'm able to reproduce your issue, and we'll try to get a fix out in an upcoming release.
