### ISSUE TITLE
Request: Please re-enable enumeration of Apple Pay sources

### ISSUE THREAD

**Issue by davidsantiago** [stripe/stripe-ios#842]
To make it easier to diagnose your issue, please fill out the following:

## Summary

Previous to v11.4.0, the STPCustomer object would give you all the customer's cards and sources. With #810 in v11.4.0, the STPCustomer's deserializer filters out ApplePay cards and sources. This makes things very difficult for our custom integration, which is not using STPPaymentContext as its payment UI. We use a custom integration that works through STPCustomerContext because it works better for our app, which is more of a subscription service and we think our payment UI is better designed for our app's needs.

This change presents a problem for us because now we can't show the user which payment source they are using for their subscription if it is an ApplePay card. We can't even just present "ApplePay" in the UI, because it appears that the user has no default source set when their default source is an ApplePay card for subscription, so we can't even tell that that is the case. 

This is a particularly frustrating limitation, because the API itself is not filtering this at the backend. Subscription payments are also a [supported transaction type/business model for Apple Pay](https://developer.apple.com/apple-pay/get-started/), so this seems like something we should be able to do. We could recreate the client code with changes, or write our own code to hit that endpoint with the ephemeral key, or just fork the SDK and modify those lines. But of course, we'd rather just use the stock SDK and not have to maintain those things ourselves. 

Given that this change was surely made for good reason, it would be great if we could change the "filter ApplePay sources" feature to be optional in some way, perhaps as a flag to the `retrieveCustomer()` function, or with a second function that does not do the filtering. 

Thanks.

## Code to reproduce

```swift
customerContext.retrieveCustomer { customer, error in 
  let customerSources = customer.sources
  for source in customerSources {
    // customerSources has sources except the ApplePay ones. 

    if source.stripeID == customer.defaultSource?.stripeID {
      // Nope, this customer's default source in the dashboard is an ApplePay card, but
      // this if statement will never be entered. 
    }
  }
}
```

## iOS version

iOS 11, but almost certainly on earlier versions as well. 

## Installation method

CocoaPods

## SDK version

v11.5.0 (v11.4.0 also has the issue).

## Other information

Anything else you can include that'll make it easier for us to help you!

**Comment by bg-stripe** [comment]
Hey @davidsantiago , thanks for the feedback! We'll try to get a change into the next release that allows disabling CustomerContext's Apple Pay filtering.
