### ISSUE TITLE
Test card was declined

### ISSUE THREAD

**Issue by Appsteamvasant** [stripe/stripe-ios#845]
Hi,

I am using test card to createToken in swift4. I have one error the card was declined. how to test with testing cards. can you please help me?

This is my code

 let cardParams = STPCardParams()
        cardParams.number = "4000056655665556"
        cardParams.expMonth = 10
        cardParams.expYear = 18
        cardParams.cvc = "123"
        
        STPAPIClient.shared().createToken(withCard: cardParams) { (token: STPToken?, error: Error?) in
            
            if error != nil {
                
                let alert = UIAlertController(title: "Alert", message: error?.localizedDescription, preferredStyle: UIAlertControllerStyle.alert)
                alert.addAction(UIAlertAction(title: "OK", style: UIAlertActionStyle.default, handler: nil))
                self.present(alert, animated: true, completion: nil)
                return
            }
            
            print(token as Any)
        }

**Comment by bg-stripe** [comment]
Hi @Appsteamvasant ,

We reserve github issues for bug reports and feature requests. For help with your integration, please write in to support@stripe.com – they'll be happy to help you with your issue.

Best,
Ben
