### ISSUE TITLE
Complete card number from STP card

### ISSUE THREAD

**Issue by parasdaff** [stripe/stripe-ios#857]
Hi,

Is there any way to get complete card number instead of last 4 digit, i am stuck when creating STPCardParams while dealing with 3d secure cards.

**Comment by bdorfman-stripe** [comment]
Hi @parasdaff,

No, there is no way to get the complete card number out. Generally you should never access or store the complete card number anywhere in your own app's code, as that may be a violation of PCI requirements. 

You do not need to have the full card number to create 3d secure source params, you only need to pass in the card source's Stripe ID string (accessible at `source.stripeID`).

If you have further integration questions, I suggest writing in to support@stripe.com.

Brian
