### ISSUE TITLE
UIBarButtonItem layout issues with STPPaymentMethodsViewController

### ISSUE THREAD

**Issue by jaredegan** [stripe/stripe-ios#868]
## Summary

I'm pushing a `STPPaymentMethodsViewController` instance using the `pushPaymentMethodsViewController()` method of `STPPaymentContext`. When the view controller appears, the positions of the "Cancel" and "Done" buttons are bad. After I enter valid credit card information, the done button is updated and the position is correct. If I touch and "touch up outside" of the cancel button, its position is also fixed. Screenshots below.

## Code to reproduce

`presentPaymentMethods()` is called from a button press

```
func presentPaymentMethods() {
        guard ephemeralKeyResponse != nil else {
            customerContext = STPCustomerContext(keyProvider: self)
            paymentContext = STPPaymentContext(customerContext: customerContext)

            paymentContext.delegate = self
            paymentContext.hostViewController = hostViewController

            paymentContext.paymentAmount = viewModel.stripeTransactionTotal
            return
        }

        paymentContext.pushPaymentMethodsViewController()
    }

func createCustomerKey(withAPIVersion apiVersion: String, completion: @escaping STPJSONResponseCompletionBlock) {
        let req = ThirdPartyTokenRequest(
            type: ThirdPartyTokenRequest.ModelType.key,
            options: ["api_version": apiVersion]
            )

        delegate?.showActivityIndicator(withText: nil)
        DefaultAPI.thirdPartyTokenPost(request: req) { [weak self] response, error in
            self?.delegate?.hideActivityIndicator()

            var keyResponse: [AnyHashable : Any]? = nil
            if let fullResponse = response?.token as? [AnyHashable : Any] {
                keyResponse = fullResponse["key"] as? [AnyHashable : Any]
            }

            self?.ephemeralKeyResponse = keyResponse

            completion(keyResponse, error)
            if let error = error {
                // TODO
            }

            if self?.ephemeralKeyResponse != nil {
                // Continue on in payment flow if successful
                DispatchQueue.main.async {
                    self?.presentPaymentMethods()
                }
            }
        }
    }
```

## iOS version

Testing on iOS 11.0 simulator and a iPhone 7 running iOS 11.1.2.

## Installation method

Cocoapods.

## SDK version

From Podfile.lock: `Stripe (11.5.0)`

## Other information

I've ensure that this is getting called on the main thread using `DispatchQueue.main.async`. If the `guard` doesn't catch in the first method listed above, then the call comes from a button press, which should be on the main thread.

I tried allocating the view controller instance myself and pushing that, I get the same result.

I experimented a bit with Stripe's Objective C code, and while I don't fully understand the reason behind the navigation item proxy decision, I think the fact that the setting of the bar button item is animated may be a contributing factor.

![img_3784](https://user-images.githubusercontent.com/303795/34166292-88db54b8-e4ac-11e7-99fc-c7ce346b8f14.PNG)
![img_3785](https://user-images.githubusercontent.com/303795/34166301-8eadbec6-e4ac-11e7-814c-0792ee1979ae.PNG)

**Comment by jaredegan** [comment]
If I include this delayed hack after pushing the view controller, the UIBarButtonItems snap to the correct positions.

```
        // Dumb hack for nav bar items
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 2) { [weak self] in
            guard let _self = self else { return }
            guard let stripeVC = _self.hostViewController?.navigationController?.viewControllers.last else { return }
            let leftBarButtonItem = stripeVC.navigationItem.leftBarButtonItem
            let rightBarButtonItem = stripeVC.navigationItem.rightBarButtonItem

            stripeVC.navigationItem.leftBarButtonItem = nil
            stripeVC.navigationItem.rightBarButtonItem = nil
            stripeVC.navigationItem.leftBarButtonItem = leftBarButtonItem
            stripeVC.navigationItem.rightBarButtonItem = rightBarButtonItem

        }
```

**Comment by bg-stripe** [comment]
Hey @jaredegan,

It looks like you're creating a `PaymentContext` when a button is pressed, and then using `createCustomerKey` to present the payment methods screen after `PaymentContext` finishes loading. Do you have a reason to be creating your `PaymentContext` on the fly in this way? If not, I suggest creating a `PaymentContext` instance on initialization, storing it to a property, and calling `self.paymentContext.presentPaymentMethodsViewController()` when your button is pressed. You probably shouldn't call `self.presentPaymentMethods()` as a side effect of `createCustomerKey`, as our SDK may call `createCustomerKey` at any point (not just after the initial load).

Hope that makes sense!
Ben

**Comment by jaredegan** [comment]
For the record, I moved the `STPPaymentContext` initialization to the `UIViewController`'s `init` and the same problems persist. While your suggestion surely saved me some other bug down the line, I don't think it would be connected to the `UIBarButtonItem` visual bugs.

Setting the `stp_theme` of my `UINavigationBar` doesn't seem to do anything when I do it in my view controller's `viewDidLoad`. When I move it to immediately before pushing the payment methods view controller, it is effective.

I'm using a similar, but more sensible workaround as I mentioned above. I'd prefer to not to do this workaround, but after a couple quick attempted changes in the Stripe code I couldn't isolate the issue. If you can't reproduce this, I'm surprised since my `UINavigationController` nav stack management is as simple as possible.

**Comment by danj-stripe** [comment]
Hi @jaredegan,

I agree that workaround shouldn't be necessary, and we'd like to figure this out with you.

Are you willing to try reproducing this in the "Standard Integration (Swift)" sample app, from this repository? Or taking a look to see how your app differs?

Thanks,
Dan

----
Some details about how the sample app is structured:

`BrowseProductsViewController` is the [`UINavigationController.rootViewController`](https://github.com/stripe/stripe-ios/blob/cc072bcdb051a2e2591307c4def98011e513b540/Example/Standard%20Integration%20(Swift)/AppDelegate.swift#L17-L20), and sets up the navigation bar with the selected theme in [`viewDidAppear`](https://github.com/stripe/stripe-ios/blob/cc072bcdb051a2e2591307c4def98011e513b540/Example/Standard%20Integration%20(Swift)/BrowseProductsViewController.swift#L47-L57). It doesn't (currently) use `stp_theme`, but I don't think that's relevant.

`CheckoutViewController` [sets up the `STPPaymentContext`](https://github.com/stripe/stripe-ios/blob/cc072bcdb051a2e2591307c4def98011e513b540/Example/Standard%20Integration%20(Swift)/CheckoutViewController.swift#L75-L129), and [calls `pushPaymentMethodsViewController()`](https://github.com/stripe/stripe-ios/blob/cc072bcdb051a2e2591307c4def98011e513b540/Example/Standard%20Integration%20(Swift)/CheckoutViewController.swift#L154-L156) when the user taps on the Payment cell (just like your `presentPaymentMethods()` button handler).

To run the sample, you'll have to set [`CheckoutViewController.stripePublishableKey`](https://github.com/stripe/stripe-ios/blob/cc072bcdb051a2e2591307c4def98011e513b540/Example/Standard%20Integration%20(Swift)/CheckoutViewController.swift#L14-L16) and [`CheckoutViewController.backendBaseURL`](https://github.com/stripe/stripe-ios/blob/cc072bcdb051a2e2591307c4def98011e513b540/Example/Standard%20Integration%20(Swift)/CheckoutViewController.swift#L18-L22).
