### ISSUE TITLE
Getting error: "Your PKPaymentRequest.merchantCapabilities needs be set to the value: PKMerchantCapability3DS" 

### ISSUE THREAD

**Issue by Vjsharma** [stripe/stripe-ios#87]
I am integrating Stripe iOS library and while testing it on device I am getting error at the time of Token generation i.e. -> "Your PKPaymentRequest.merchantCapabilities needs be set to the value: PKMerchantCapability3DS" in "createTokenWithPayment" method.

I have checked it is setting in - ""Stripe+ApplePay.h" file.

**Comment by alexvbush** [comment]
@AbhishekA have you ever were able to resolve that error? experiencing same `Connection to remote alert view service failed` message for my app. apply pay controller never shows up
