### ISSUE TITLE
Subscribing using Apple Pay 

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#873]
## Summary

We'd like to add an option to subscribe using Apple Pay in addition to the regular credit card option. According to Stripe's documentation, it's supposed to be possible, but it's not clear to us how to do it.

We've followed the Stripe Apple pay tutorial, and now when we run presentPaymentMethodsViewController()
It shows Apple pay as one of the options.   

The question is how to initiate the subscription after the user has selected Apple Pay as the payment method. 

With a regular credit card, it's possible by subscribing the user using Stripe's Ruby gem for example after he added a credit as a payment method in the ios app.  How can we set Apple Pay as a payment method on iOS?

**Comment by bg-stripe** [comment]
Hey @odedharth – it currently isn't possible to save an Apple Pay source as a customer's default payment method using our pre-built UI components. PaymentContext is mainly intended for use with one-time purchases, and Apple Pay sources can only be re-used for subscriptions. 

I'm sorry we don't have a better answer for you right now. You may want to take a look at this PR [0], which adds an `includeApplePaySources` switch to `CustomerContext`. While this option shouldn't be used with `PaymentContext`, you could use it to build your own subscriptions payment method UI driven by `CustomerContext`.

[0] https://github.com/stripe/stripe-ios/pull/864

**Comment by odedharth** [comment]
@bg-stripe Thanks for the reply. So just to have a better understanding - is it possible to create a recurring payment using Apple Pay when building the UI using CustomerContext?
Is there a code example that we can reference when building this?

**Comment by bg-stripe** [comment]
Hey @odedharth – unfortunately we don't have any code examples for this, but it is indeed possible. After creating an Apple Pay source (`[apiClient createSourceWithPayment:]`), you can add that source to your customer with `CustomerContext`, and then set it as the customer's default source. 

We'll definitely consider adding better support for Apple Pay subscriptions to Apple Pay in a future release. If you have any additional integration questions, feel free to write in to support@stripe.com :)

**Comment by Elshad** [comment]
It seems, still "it currently isn't possible to save an Apple Pay source as a customer's default payment method using our pre-built UI components" in 2020

**Comment by dragouf** [comment]
I successfully display apple pay for setup intent but it failed to pass apple validation because they say it doesn't display price on payment sheet.

Since it's just to record the card (setup) and not to pay directly, it seems normal to me. Did someone successfully use apple pay for setup intent and was able to pass apple validation ?

Also, is it possible to display information about future payment (like the next payment price and date) on the setup intent sheet ?
