### ISSUE TITLE
Genetare token of Bank account without routing number

### ISSUE THREAD

**Issue by paynd** [stripe/stripe-ios#874]
## Summary

It is impossible to create bank account token without routing_number, even if it is marked as [optional](https://stripe.com/docs/api#customer_create_bank_account) and country-specific, and there is no `routing_number` in some countries ([for example in Singapore](https://github.com/tipsi/tipsi-stripe/issues/208)). 

## iOS version

any

## Other information

How can we get bank account token without this parameter?

**Comment by Happudada** [comment]
In **stripe/stripe**'s document to create bank account token routing number is given as an optional, but we can't leave it as optional.

To solve that issue I research some bank related sites and find one solution.
The Routing number is a 7 digit number which is a combination of **Bank code** and **Branch code**.

**Bank code is 4 digit number** and **Branch code is 3 digit** number. By combine that two respected number we can make routing number.

Parameter to pass in **createTokenWithBankAccount** method
```js
let params = {
                accountNumber: this.state.accountNo,
                countryCode: 'sg',
                currency: 'sgd',
                routingNumber: `${this.state.bankCode}${this.state.branchCode}`
            };
```

I design Payment screen as under

![simulator screen shot 20-dec-2017 2 59 56 pm](https://user-images.githubusercontent.com/31007929/34200331-b5d4a826-e596-11e7-8a22-cb47f95abc1c.png)

**Comment by bg-stripe** [comment]
Hey @paynd – if you're having trouble with your integration, we suggest sending an email describing your issue to support@stripe.com . They'll be happy to help :)

**Comment by paynd** [comment]
Thank you @bg-stripe!
