### ISSUE TITLE
Changing publishableKey during runtime won't work

### ISSUE THREAD

**Issue by matibzurovski** [stripe/stripe-ios#880]
## Summary

I am working on an application that allows two currencies: `USD` & `EUR`. Then, we have two Stripe accounts, one for saving the `USD` cards and one for the `EUR` cards. The user is able to select his currency, and depending on which one he selects, the Stripe account we will use.

The problem is that, after the user has added a card for `USD`, even if he changes to selection to `EUR` (which in the background changes the `STPPaymentConfiguration.publishableKey` to the `EUR` one), the next card added will also be saved on the `USD` account.

## Code to reproduce

```Swift
let usdKey = "pk_test_usdKey"
let eurKey = "pk_test_eurKey"

// Start the app with the key corresponding to the USD account
STPPaymentConfiguration.shared().publishableKey = usdKey

// Create a token for the credit card on the USD account
let cardParams = STPCardParams()
cardParams.name = "Homer Simpson"
cardParams.number = "4242424242424242"
cardParams.expMonth = 5
cardParams.expYear = 2020
cardParams.cvc = 123
STPAPIClient.shared().createToken(withCard: cardParams) { token, error in
    print(token)  // Prints a token that is generated on the Stripe USD account
}

// Change the key to be the one corresponding to the EUR account
STPPaymentConfiguration.shared().publishableKey = eurKey
print("Publishable key is: \(STPAPIClient.shared().publishableKey)") // prints "pk_test_eurKey"

// Create a token for the credit card on the EUR account
STPAPIClient.shared().createToken(withCard: cardParams) { token, error in
    print(token)  // Prints another = token that is generated on the Stripe USD account (instead of EUR)
}

```

## iOS version

iOS 11

## Installation method

Cocoapods

## SDK version

`Stripe (9.0.0)`

**Comment by bg-stripe** [comment]
Hey @matibzurovski ,

Thanks for reporting this issue! Instead of setting the `publishableKey` on `STPPaymentConfiguration`, you can call:

```
STPAPIClient.shared().publishableKey = eurKey;
```

We'll look into fixing the bug you encountered in a future release.

Out of curiosity, is there a reason you're using two Stripe accounts for different currencies, rather than adding multiple bank accounts to the same Stripe account? 

https://stripe.com/docs/payouts#multiple-bank-accounts

Ben

**Comment by bg-stripe** [comment]
Following up @matibzurovski – I just noticed that you're on `v9.0.0` of our SDK, and I don't think the fix I suggested will work in that version. 

If you upgrade to the latest version, setting `STPAPIClient.shared().publishableKey` will work as expected.

Best,
Ben

**Comment by matibzurovski** [comment]
Hey @bg-stripe, thanks for the hotfix! I had to update the SDK for it to work, as you mention.

One question though, is there any benefit on doing:
`STPPaymentConfiguration.shared().publishableKey = eurKey`
instead of:
`STPAPIClient.shared().publishableKey = eurKey`?

Basically, I am asking if I should notice any difference on other behavior of the SDK.

**Comment by bg-stripe** [comment]
Hey @matibzurovski ,

If you're just using `STPAPIClient` to tokenize card details, you shouldn't experience any differences in behavior.

Ben
