### ISSUE TITLE
Intercept return key on keyboard when using STPPaymentCardTextField

### ISSUE THREAD

**Issue by fictorial** [stripe/stripe-ios#885]
## Summary
 
I am developing an app that is for less ios-savvy users.  Part of the UX includes support for the return key of the iOS keyboard to act as if it were "goto next step".  I don't see how we can detect the return key being pressed on the keyboard when used from STPPaymentCardTextField since the UITextFields are managed internally.  This leads to a UX inconsistency with the app.  

## iOS version

iOS 11

## Installation method

CocoaPods

## SDK version

11.5.0

**Comment by bg-stripe** [comment]
Hi @fictorial ,

Thanks for the feature request! We'll look into adding an additional delegate method to `STPPaymentCardTextField` in a future update.

Best,
Ben

**Comment by fictorial** [comment]
Is this the place to track this feature request for the future or should I just keep an eye on releases?

**Comment by bg-stripe** [comment]
Yep! We'll reference this issue in the PR and release.

**Comment by korsour** [comment]
Any update?
