### ISSUE TITLE
Un-deprecate STPCard constructor

### ISSUE THREAD

**Issue by edenman** [stripe/stripe-ios#886]
I have a "mock" mode of my app where I stub out all the servers involved.  As part of that mock mode, I want to return fake STPCard objects, so I need to create them programmatically.  I'm seeing an Xcode warning: `You cannot directly instantiate an STPCard. You should only use one that has been returned from an STPAPIClient callback.` and I'd like to request that this method be un-deprecated.

Cocoapods 1.4.0
Stripe SDK 11.5.0

**Comment by billinghamj** [comment]
You could subclass it?

**Comment by edenman** [comment]
Subclassing it doesn't seem to help.  My subclass still has to delegate to one of the superclass's constructors, and the only visible constructor is the deprecated one, so I still get the warning.

**Comment by bg-stripe** [comment]
Hey @edenman ,

Since `new` isn't marked unavailable, you can instantiate an `STPCard` by calling `[STPCard new]`.

We do want to prevent most users from directly instantiating a `STPCard`, so we'll probably keep `init` unavailable for now (or perhaps mark it deprecated so that you can use it and just `#pragma` ignore the warning).

Hope that helps,
Ben

**Comment by edenman** [comment]
@bg-stripe hey sorry, just coming back to this: this is still really annoying.  I can't use #pragma in Swift afaict, so I just have this warning forever in my app.  And I can't figure out how to call `[STPCard new]` either to avoid this.  I get why you want to discourage people from using this constructor, but given the limitations of Swift tooling, could we maybe make an exception here and un-deprecate it?

**Comment by flutterq** [comment]
[[Solved] ‘new’ is unavailable: You cannot directly instantiate an STPIssuingCardPin
](https://exerror.com/solved-new-is-unavailable-you-cannot-directly-instantiate-an-stpissuingcardpin/)

**Comment by csabol-stripe** [comment]
As a followup here, you can manually create an `STPCard` instance by putting the desired params in a dictionary and calling `STPCard.decodedObject(fromAPIResponse: jsonDictionary)` You can see an example [here](https://github.com/stripe/stripe-ios/blob/39abf35e84f2e284aabfa9ad9efc7ce6a13c5f1c/Tests/Tests/STPCardTest.swift#L190)
