### ISSUE TITLE
No delegate methods are invoked other than paymentContextDidChange:

### ISSUE THREAD

**Issue by lyptt** [stripe/stripe-ios#887]
## Summary

No delegate methods are called for STPPaymentContextDelegate other than paymentContextDidChange. Literally no other delegate method is called.

I'm calling the completion block in my custom STPEphemeralKeyProvider, with JSON taken directly from the equivalent server Stripe API.

I can then show the payment methods view controller with presentPaymentMethodsViewController(). This works fine.

When tapping on a card from the list, or adding a new card, or hitting cancel, or literally any action within this Stripe-provided view controller, I get no delegate callbacks whatsoever other than paymentContextDidChange:.

## iOS version

iOS 11

## Installation method

Carthage

## SDK version

Latest

## Other information

Customer ID used for testing: cus_CDmdZKDvvO7mTY

**Comment by bg-stripe** [comment]
Hi @lyptt ,

The other methods in `STPPaymentContextDelegate` (`didCreatePaymentResult`, `didFinish`) will be called after you initiate a payment using `requestPayment`. 

https://stripe.com/docs/mobile/ios/standard#setting-the-delegate-and-host-view-controller

If you'd like more help with your integration, don't hesitate to reach out to support@stripe.com – they'd be happy to help answer any additional integration questions you have.

Best,
Ben
