### ISSUE TITLE
Release/Debug - Stripe API Key

### ISSUE THREAD

**Issue by IHEARTCOOKIES** [stripe/stripe-ios#888]
Hi,

It would be really helpful if you could add a warning/error statement for if the key that I'm using is a test or production key when running release/debug.

That way, I could ensure that the builds that I'm pushing to the App Store contain the right key.

Just a thought. Wouldn't be too hard to implement either. Let me know if you'd require my assistance to do this.

**Comment by billinghamj** [comment]
I believe it does this already?

See: https://github.com/stripe/stripe-ios/blob/master/Stripe/STPAPIClient.m#L186-L201

**Comment by bg-stripe** [comment]
Thanks for the reply @billinghamj ! :)

**Comment by IHEARTCOOKIES** [comment]
Looks like you're right @billinghamj. One quick follow-up question, why wouldn't this be an NSAssert if the key is a test mode key? Lastly, shouldn't `BOOL secretKey = [publishableKey hasPrefix:@"sk_"];` be `BOOL secretKey = [publishableKey.lowercaseString hasPrefix:@"sk_"];`?

**Comment by billinghamj** [comment]
They’re never distributed starting as anything other than the lowercase `sk_` and I suspect wouldn’t even work on the API if you did mistakenly uppercase them, so it isn’t likely that anyone will be entering non-lowercase keys anyway
