### ISSUE TITLE
Amex CVC check

### ISSUE THREAD

**Issue by yemodin** [stripe/stripe-ios#890]
## Summary

Amex CVC can be 3-digits only? Or no such thing like 3-digits CVC amex?

## Code to reproduce

Currently for 3-digits this method result is valid:
https://github.com/stripe/stripe-ios/blob/262e56bfefbb35f35dfdbadf0bba19adf3578f9c/Stripe/STPCardValidator.m#L114

It's confusing if amex must have 4-digits CVC only.

**Comment by bg-stripe** [comment]
Hi @yemodin – see #440 

> This is actually a common misconception about American Express cards - while the majority of them have 4-digit CVCs, there are several types of amex card that have a 3-digit CVC. Many amex cards also have a 3-digit "CID" printed on the front, which also works for verification purposes. As such we have to be slightly ambiguous in our validation.
