### ISSUE TITLE
Static analysis shows couple of issues in latest release

### ISSUE THREAD

**Issue by bielikb** [stripe/stripe-ios#895]
## Summary

Static code analysis unveils couple of issues in latest release

## Code to reproduce

Run static analysis

## iOS version

11.2

## Installation method

cocoa pods

## SDK version
12.1.0

## Other information

![screen shot 2018-02-14 at 15 55 56](https://user-images.githubusercontent.com/4924709/36210923-fe4f6b60-119f-11e8-8939-01bb0748a2a5.png)

**Comment by bg-stripe** [comment]
Thanks for pointing this out @bielikb , we'll look into it. I think this is a new analyzer warning – are you using the Xcode 9.3 beta ?

**Comment by bielikb** [comment]
@bg-stripe Im using Xcode version 9.2 (9C40b)

**Comment by danj-stripe** [comment]
Thanks again for reporting, @bielikb. We just released v12.1.1, which has a fix for this.
