### ISSUE TITLE
STPAPIClient.m is pointing to an older version of Stripe? Apple Pay not working

### ISSUE THREAD

**Issue by halinebr** [stripe/stripe-ios#898]
To make it easier to diagnose your issue, please fill out the following:

## Summary

A simple summary of the problems you're having.

In the most recent pod, the Stripe API version is set to "2015-10-12" (in the file Stripe/STPAPIClient.m). This is resulting in Apple Pay transactions to return a "No such card" 400 error.

_Edit:_ I changed the API version to the latest version and I am still seeing this error. I am using Stripe's Standard iOS integration. I have already uploaded a new Apple Pay certificate and uploaded it to Stripe, as well as creating a new merchant ID, turning Apple Pay on and off in the app as troubleshooting instructions allow. In my previous app builds, Apple Pay works as expected and the only differences I am able to identify between my current build and previous builds are updates in pods. 

## Code to reproduce

If possible, please include a brief piece of code (or ideally, a link to an example project) demonstrating the problem you're having.

## iOS version

What version of iOS are you observing the problem on?
All versions.

## Installation method

How did you install our SDK?
Cocoapods, but I see this error also in this git hub repo. 

## SDK version

What version of our SDK are you using? You can find this by either looking at your `Podfile.lock` (if you're using Cocoapods), your `Cartfile.resolved` (if you're using Carthage), or by looking at the value of `STPSDKVersion` in `STPAPIClient.h`.

Cocoapod version 12.1.0
Most recent

## Other information

Anything else you can include that'll make it easier for us to help you!

**Comment by danj-stripe** [comment]
Hi @halinebr,

If I understand correctly, you've previously successfully integrated with the Stripe SDK. You've updated to the latest (v12.1.0) through cocoapods, and now you're getting an error message.

1. What version are you upgrading from?
2. Can you be more specific about the error message and what steps lead up to it? What methods of the SDK are you calling, and which one returns the error?

Thanks

**Comment by halinebr** [comment]
Hi Dan!

1. Upgrading from 12.0.1 to latest. 
2. This error happens within paymentContextDidChange - I'm assuming it has something to do with validating the card. The error message I receive is the following:
["com.stripe.lib:StripeErrorTypeKey": invalid_request_error, "com.stripe.lib:ErrorParameterKey": source, "com.stripe.lib:ErrorMessageKey": No such token: card_1By6fsAVT3n4MkhnqEdIRxnc, "NSLocalizedDescription": No such token: card_1By6fsAVT3n4MkhnqEdIRxnc]

Thanks

**Comment by bg-stripe** [comment]
Hey @halinebr ! Thanks for reporting this issue. We've fixed the regression in the latest version of the SDK, 12.1.1.
