### ISSUE TITLE
STPRedirectContextCompletionBlock's error param should be optional.

### ISSUE THREAD

**Issue by toseefkhilji** [stripe/stripe-ios#901]
I'am using Source  method for payment.

I Creating **STPRedirectContext** object using init method.
Below CompletionBlock is used for this.
`typedef void (^STPRedirectContextCompletionBlock)(NSString *sourceID, NSString *clientSecret, NSError *error);
`

## Code to reproduce
```
self.redirectContext = STPRedirectContext.init(source: source!, completion: { (sourceId, clientSecret, error) in
 if error != nil {
   debugPrint("Error:\(error)")
 }
```
getting warning in checking Error (

> Comparing non-optional value of type 'Error' to nil always returns true

).

## Summary
So I think Error param in **STPRedirectContextCompletionBlock** should be **_nullable_** (i.e in Swift Optional), Like below:
`typedef void (^STPSourceCompletionBlock)(STPSource * __nullable source, NSError * __nullable error);
`

## Installation method

How did you install our SDK?
Using **CocoaPod**.

**Comment by danj-stripe** [comment]
It looks like you're correct. Thanks for reporting!

I've opened #902 with this change, and it should go out in our next release.

**Comment by toseefkhilji** [comment]
@danj-stripe : Thanks for quick update.
