### ISSUE TITLE
STPAddCardViewController done button disabled

### ISSUE THREAD

**Issue by niazoff** [stripe/stripe-ios#903]
## Summary
When initializing `STPAddCardViewController` with a theme and filling out the credit card information, the done button doesn't become enabled upon finishing. It works, however, when not initializing with a theme.

## Code to reproduce
```swift
let theme = STPTheme()
theme.accentColor = UIColor(named: "Mocha")
let addCardViewController = STPAddCardViewController(theme: theme)
addCardViewController.delegate = self
navigationController?.pushViewController(addCardViewController, animated: true)
```

## iOS version
iOS 11.2

## Installation method
Cocoapods

## SDK version
12.1.1

**Comment by bg-stripe** [comment]
Hi @niazoff ,

Thanks for reporting this issue. You should use the initializer for AddCardVC that includes a configuration parameter. The `init(theme:` initializer you're using shouldn't be public – we'll make sure it's private in the next release.

```swift
let theme = STPTheme()
theme.accentColor = UIColor(named: "Mocha")
let config = STPPaymentConfiguration()
let addCardViewController = STPAddCardViewController(configuration: config, theme: theme)
...
```

Hope that helps!

**Comment by niazoff** [comment]
Thanks!
