### ISSUE TITLE
Simulator architecture issue

### ISSUE THREAD

**Issue by aarizhov** [stripe/stripe-ios#907]
I can't use simulator for run stripe-ios framework.
For device all works fine
Valid architectures: armv7s  armv7 arm64

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_STPTheme", referenced from:
      objc-class-ref in ActiveSessionViewController.o
      objc-class-ref in 1DetailsViewController.o
  "_OBJC_CLASS_$_STPPaymentConfiguration", referenced from:
      objc-class-ref in ActiveSessionViewController.o
      objc-class-ref in 1DetailsViewController.o
  "_OBJC_METACLASS_$_STPAddCardViewController", referenced from:
      _OBJC_METACLASS_$_MorePaymentViewController2 in MorePaymentViewController2.o
  "_OBJC_CLASS_$_STPAddCardViewController", referenced from:
      _OBJC_CLASS_$_MorePaymentViewController2 in MorePaymentViewController2.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by joeydong-stripe** [comment]
Hi @aarizhov, what steps are you taking exactly? The "Valid Architectures" build setting does not affect the build's capability of running in the iOS Simulator.
