### ISSUE TITLE
Using Apple Pay with a 3rd party merchant id and a live key gives an error.

### ISSUE THREAD

**Issue by ivanmkc** [stripe/stripe-ios#908]
## Summary
We are using Stripe to handle payments that are then passed onto a 3rd party server. We do this by using their Stripe public key, getting the credit card payment as a token from Stripe and passing that on to the 3rd party. When we do this with Apple Pay (we use their merchant id, which may be the issue), it works fine when using the Stripe test key, but with the live key, we get the error: 

> Your payment information is formatted improperly. Please make sure you're correctly using the latest version of our iOS library. For more information see https://stripe.com/docs/mobile/ios .

## Code to reproduce

```swift
//Create payment request
let paymentRequest = Stripe.paymentRequest(withMerchantIdentifier: merchantId, country: countryCode, currency: currencyCode)

//Configure the line items on the payment request
var totalPrice: Double = 0
var paymentSummaryItems = products.map { (product) -> [PKPaymentSummaryItem] in
    let amount = productToAmountMap[product.productId] ?? 0
    let price = product.retailPrice.value
    let name = product.name
    totalPrice += price*Double(amount)
    return Array(repeating:PKPaymentSummaryItem(label: name, amount: NSDecimalNumber(decimal: Decimal(price))), count: amount)
}
.reduce([], +)

//Add the summary line
paymentSummaryItems.append(PKPaymentSummaryItem(label: companyName, amount: NSDecimalNumber(decimal: Decimal(totalPrice))))
paymentRequest.paymentSummaryItems = paymentSummaryItems

if Stripe.canSubmitPaymentRequest(paymentRequest),
    let paymentAuthorizationViewController = PKPaymentAuthorizationViewController(paymentRequest: paymentRequest) {
    // Setup payment authorization view controller
    paymentAuthorizationViewController.delegate = self
    
    // Present payment authorization view controller
    viewController?.present(paymentAuthorizationViewController, animated: true)
}
```

## iOS version
11.2

What version of iOS are you observing the problem on?

## Installation method

How did you install our SDK?
Cocoapods

## SDK version
12.1.1

What version of our SDK are you using? You can find this by either looking at your `Podfile.lock` (if you're using Cocoapods), your `Cartfile.resolved` (if you're using Carthage), or by looking at the value of `STPSDKVersion` in `STPAPIClient.h`.

## Other information
Not sure if Stripe or Apple even supports using a 3rd party merchant id (one not linked to your app id), but I couldn't find much useful info about this use case.

**Comment by joeydong-stripe** [comment]
Hi @ivanmkc, thanks for opening an issue. I am aware that Apple is restricting usage of Merchant IDs to the app owner's account (https://techcrunch.com/2017/12/20/apple-revises-its-controversial-guidelines-on-template-based-apps/) but let me dig into this to be sure.

**Comment by joeydong-stripe** [comment]
> Not sure if Stripe or Apple even supports using a 3rd party merchant id (one not linked to your app id), but I couldn't find much useful info about this use case.

We do not support but it should work in your case since you're using their public key in addition to their Merchant ID (Apple is supposed to start denying apps in the review process for apps using foreign Merchant ID). 

Regarding the error message you got, it's due to a formatting issue in the request but I don't have any more specifics right now. Can you double check that you are using the correct public key?

**Comment by joeydong-stripe** [comment]
Can you privately email me (joeydong@stripe.com) the Stripe account number so that I can investigate the request logs? I see that the validation is more strict when you are not in test mode but don't have more information on why you are getting a "format" error on the request.

A wild guess, maybe the iOS version needs to be updated to the latest 11.2.6?

**Comment by ivanmkc** [comment]
Thanks for the in-depth response, I will get this to your email asap. Btw, I am testing on simulator.

**Comment by fred-stripe** [comment]
Hi @ivanmkc, I wanted to mention that the iOS Simulator cannot make live Apple Pay payments. Apple Pay in live mode will only work with a real iOS device, as the simulator will not allow you to add a real credit card to the wallet. However, if you run your application on a supported device[1] things should work as expected. You can still use an instrumented build and the Xcode debugger to monitor your application over a device cable. Hope that helps!

[1] https://support.apple.com/kb/KM207105

**Comment by sleep9** [comment]
Is this still a problem in 2024? I would like to have third-party merchantids payable through my app. Would I need to bundle their merchantId with the app and upload their certificate to my stripe account?
