### ISSUE TITLE
Stripe-Connect WebKit View

### ISSUE THREAD

**Issue by corbinhudson** [stripe/stripe-ios#909]
Hello,

Im using the most update to date xcode, iOS & stripe to sign up users for Stripe-Connect. 

Recently the width of the sign up screen on webkit view has been cut off (see photo). Im not sure why this is the case but it also  appears zooming in and out is disabled on this webpage, with no way to enable? This would fix the problem and is expected functionality from the user. I have tried many different solutions to no avail , please help.   

This is my URL which is pre-loading the variable correctly.

`URL(string: "https://connect.stripe.com/oauth/authorize?response_type=code&client_id=\(Constants.PlatformIds.stripeClientIdLive)&scope=read_write&state=\(PFUser.current()!.objectId!)&stripe_user[country]=\(country)&stripe_user[first_name]=\(firstName)&stripe_user[last_name]=\(lastName)&stripe_user[email]=\(email)&stripe_user[phone_number]=\(phoneNumber)&stripe_user[url]=\(website)&stripe_user[street_address]=\(address)&stripe_user[product_description]=\(productDescription)&stripe_user[business_name]=\(businessName)")`

![screen shot 2018-03-14 at 10 39 01 am](https://user-images.githubusercontent.com/26608161/37410737-9c5c06c8-2777-11e8-886a-26175f3d3bf2.png)

**Comment by joeydong-stripe** [comment]
Hi @corbinhudson, I see your problem.

I've reproduced the non-mobile friendly page in Safari but the page can be panned and zoomed in that app so I'm going to try doing the same test in a web view now.

**Comment by joeydong-stripe** [comment]
We have this non-scrolling page issue reported by a few other people recently so we're going to take a look at it.

**Comment by joeydong-stripe** [comment]
Hi @corbinhudson, we released a patch to undo this problem. Can you try again and let me know if it works for you now?

**Comment by corbinhudson** [comment]
Looks good now! Thanks

**Comment by joeydong-stripe** [comment]
🙌
