### ISSUE TITLE
PKAddress Field Deprecation Warnings

### ISSUE THREAD

**Issue by dmerfeld** [stripe/stripe-ios#912]
## Summary

Compiler warnings of PKAddress Field Deprecation in iOS 11 when building project.

## Code to reproduce

<img width="271" alt="screen shot 2018-03-17 at 3 30 46 pm" src="https://user-images.githubusercontent.com/1771887/37559704-7b210ca0-29f8-11e8-8c56-c6ec26a4d06b.png">

Warnings appear when compiling a project after doing a "Clean Build Folder", archiving and building.

## iOS version

Occurs in projects targeting: iOS 11, 11.1 and 11.2

## Installation method

Installed SDK using Pods

## SDK version

Issue occurred on 12.1.1 and after upgrading to 12.1.2

## Other information
Xcode version 9.2 (9C40b).

Issue was also reported here: 
https://github.com/stripe/stripe-ios/issues/814

**Comment by bg-stripe** [comment]
Hey @dmerfeld , thanks for reporting the issue. We've reproduced the deprecation warnings, and we'll silence them in our next release.

Ben
