### ISSUE TITLE
Customizing default theme does not work as documented

### ISSUE THREAD

**Issue by Blackjacx** [stripe/stripe-ios#916]
To make it easier to diagnose your issue, please fill out the following:

## Summary

Customizing default theme does not work as documented in https://stripe.com/docs/mobile/ios/standard#theming. What I need to do is the following:

```
/// Customizes default theme exactly once per app start.
    static let theme: STPTheme = {
        var theme = STPTheme.default()
        theme.primaryBackgroundColor = UIColor.backgroundColor
        theme.secondaryBackgroundColor = UIColor.backgroundColor
        theme.primaryForegroundColor = UIColor.textColor
        theme.secondaryForegroundColor = UIColor.brightTextColor
        theme.accentColor = UIColor.contrast2
        theme.errorColor = UIColor.contrast3
        theme.font = Fonts.body3.font
        theme.emphasisFont = Fonts.body3Medium.font
        return theme
    }()
```

and then explicitly use that theme for the payment context. Normally I can just leave out the theme  parameter when init the payment ctx. 

## iOS version

iOS 11.3

## Installation method

Cocoapods

## SDK version

The newest from today

**Comment by Blackjacx** [comment]
Nope, as far as I understood static let properties, the theme block is evaluated when the enclosing class is used the first time. And since all I do with stripe is in that class it is evaluated before any UI interaction. What I tried to do is sth like:

```
STPTheme.default().primaryBackgroundColor = UIColor.backgroundColor
STPTheme.default().secondaryBackgroundColor = UIColor.backgroundColor
STPTheme.default().primaryForegroundColor = UIColor.textColor
STPTheme.default().secondaryForegroundColor = UIColor.brightTextColor
STPTheme.default().accentColor = UIColor.contrast2
STPTheme.default().errorColor = UIColor.contrast3
STPTheme.default().font = Fonts.body3.font
STPTheme.default().emphasisFont = Fonts.body3Medium.font
```

In my PaymentHandler's initializer and then create the STPPaymentContext using the short format: `STPPaymentContext(customerContext: context)`. But then the payment context used another default theme 😅 not that what I configured. 

We use a pure Swift app. Could it be that something gets confused with the default values?

**Comment by joeydong-stripe** [comment]
Hi @Blackjacx,

After a day I still don't have any ideas given the information that's posted here. I would really double check to make sure this customization code is executed before displaying anything. Please email support@stripe.com so they can privately debug the issue with you.

> We use a pure Swift app. Could it be that something gets confused with the default values?

I'm not sure what you mean here. The `default` text does get a weird highlighting in Xcode but it doesn't have any effect.

**Comment by Blackjacx** [comment]
You where totally right! I double checked this issue. Thanks for the hint. I forgot that static let variables are implizitly lazy which means they are initialized only if needed! Changing this solved my problem!

**Comment by joeydong-stripe** [comment]
🙌
