### ISSUE TITLE
Pod contains old API version

### ISSUE THREAD

**Issue by odedharth** [stripe/stripe-ios#918]
## Summary

The stripe-ios pod sends the API calls with the following stripe version (STPAPIClient.m line 49)
`static NSString * const APIVersion = @"2015-10-12";
`

I'm wondering if this is on purpose? Should I change it to the API version we use on our server? If yes, how?

**Comment by joeydong-stripe** [comment]
Hi @odedharth, thanks for opening an issue.

The `APIVersion` constant inside this SDK is only used for requests made from this SDK directly with Stripe. Therefore, you can still use any API Version for your server/backend. We are definitely looking into upgrading this constant to something more modern. Again, this has no impact on the API version you use elsewhere.

Does that make sense?

**Comment by odedharth** [comment]
@joeydong-stripe Got it, just wanted to make sure that this will not cause issues. 
And yes like @billinghamj mentioned, because of that it shows in the Stripe dashboard a lot of requests from this old API version.

**Comment by billinghamj** [comment]
Might still be worth leaving open - it's still worth updating the version, just not urgent.

**Comment by toddgower-hiatus** [comment]
any update on this issue?

**Comment by tmaly1980** [comment]
I've been recommended by Stripe's Tech Support to upgrade my API version, which is hardcoded in this library. Is there a way to override this? Can I somehow set the Stripe-Version header from my iOS code?

**Comment by CarlosCondor** [comment]
> I've been recommended by Stripe's Tech Support (due to an unknown 500 error in testing Apple Pay payments) to upgrade my API version, which is hardcoded in this library. Is there a way to override this? Can I somehow set the Stripe-Version header from my iOS code?

any update?

**Comment by csabol-stripe** [comment]
We are working on updating the binded API version for our next release. We do not currently plan to support manually setting the preferred API version

**Comment by yuki-stripe** [comment]
We've updated the API version in the latest 17.0.0 release to `2019-05-16`

**Comment by tmaly1980** [comment]
Is there a way to change the API version on the fly? Right now I've been using 14.0.0 and would hate to recompile and resubmit all my apps (white labeled).

**Comment by davidme-stripe** [comment]
No, the API version is sent from your app, so it isn't possible to change it without resubmitting your app to the App Store. We don't have any plans to deprecate the old API version, so you shouldn't need to worry about this unless you need some functionality from a newer version.

**Comment by tmaly1980** [comment]
The problem is Apple pay is broken in the older API. Getting a token gives me an unknown error.

**Comment by tmaly1980** [comment]
@CarlosCondor Sadly, what I have to do is something like this in my Podfile (but it works):

```
post_install do |installer|
  # Modify APIVersion in Stripe 14.0.0 (more recent so working) - fix "unknown error" when processing
  # tipsi-stripe doesn't have androidX yet, and not compatible with Stripe 17.0.0
  filepath = "Pods/Stripe/Stripe/STPAPIClient.m"
  text = File.read(filepath)
  replace = text.gsub(/const APIVersion = @"2015-10-12";/, 'const APIVersion = @"2018-11-08";')
  File.open(filepath, "w") {|file| file.puts replace}
end
```

I can't update to a newer version of the SDK because the library I use with it (tipsi-stripe) doesn't yet support the SDK rewrite. So my only choice is to hack the library files.

**Comment by tmaly1980** [comment]
@davidme-stripe Honestly, what would have been even better is having a method ported back to older versions (ie 14.0.0) that can customize the API version. Pretty much every other Stripe library out there can do that. I don't see the sense in having the API version hardcoded and not customizable.

**Comment by davidme-stripe** [comment]
Thanks @tmaly1980, we're looking into why some Apple Pay transactions would fail on the 2015-10-12 but not the 2018-11-08 API. We don't want existing apps in the store to break, so it's important that the 2015-10-12 API continues to work.

We'll take your feedback into account and continue to discuss the idea of a configurable API version internally.

**Comment by aymanosman** [comment]
@tmaly1980 It may be worth investigating whether [our fork](https://github.com/b-social/tipsi-stripe) of `tipsi-stripe` meets your needs. We had to migrate some code to work with the newer Stripe API, and to get access to new features. I'd be happy to fix up some bits that were only modified to suit our needs.
