### ISSUE TITLE
add SegmentedController in navbar

### ISSUE THREAD

**Issue by shatk0vskiy** [stripe/stripe-ios#922]
Hey everyone,

I need to add SegmentedController in navbar on the screen which appears after pushPaymentMethodsViewController(). Any suggestions?

Thanks.
<img width="390" alt="stripe" src="https://user-images.githubusercontent.com/5717621/38681887-77299732-3e72-11e8-8664-9c3e6d7f9e08.png">

**Comment by joeydong-stripe** [comment]
Hi @shatk0vskiy,

I would recommend that you create a subclass of `STPAddCardViewController` and swap out the `self.title` and `self.titleView`. Then investigate customizing the `self.navigationItem` to modify the current "Cancel" and "Done" buttons.

Please email support@stripe.com and they'll privately answer any further questions you may have. Keep in mind that it's support specific to Stripe problems and not iOS development in general.
