### ISSUE TITLE
Why is the Stripe-Version still at 2015-10-12?

### ISSUE THREAD

**Issue by andrewmccafferty** [stripe/stripe-ios#923]
In our team, we were doing some Charles proxying while using the SDK, and noticed that the API version is 2015-10-12 (which corresponds to what I can see in the master version of STPAPIClient in this repo).

The current version of the Stripe API is 2018-02-28. Is there a reason why the iOS SDK is still using such an old version?

**Comment by joeydong-stripe** [comment]
Hi @andrewmccafferty, thanks for posting an issue.

Yep you are totally right. There's nothing really stopping us from updating to a newer version. We just haven't done the legwork yet of validating that it works.

We'll handle it in https://github.com/stripe/stripe-ios/issues/918

**Comment by andrewmccafferty** [comment]
Ah I see, sorry, didn't spot the other issue...
