### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by fxo140130** [stripe/stripe-ios#934]
Is there any way to display charge errors from back-end server attached to stripe on the ios client screen? 
Like this error example 
Stripe: Cannot charge a customer that has no active card
Please, can you help me how to handle the error on the client side? 
Thanks

**Comment by joeydong-stripe** [comment]
Hi @fxo140130, thanks for the message.

In this particular error case, you should make sure the user has added a card before attempting to create a charge.

For example, one way you can check is to see if there is 1 or more source in `customer.sources`: https://github.com/stripe/stripe-ios/blob/master/Stripe/PublicHeaders/STPCustomer.h#L50.

Please email support@stripe.com and they will help you further with your integration.
