### ISSUE TITLE
Can't run Standard Integration Example

### ISSUE THREAD

**Issue by guidolodetti** [stripe/stripe-ios#935]
Hello!

I can't find a way to make work the standard integration example. `UI Examples` works just fine: I open the Xcode Workspace and it compiles and launches correctly. However, the `Standard Integration` doesn't compile in any way and it tells that `Stripe` cannot be found. What can I do? I couldn't find anything in previous issues and it seems a really stupid problem!

[Screenshot of the error](https://i.imgur.com/gTuMOYP.png)

Thanks,

Guido

**Comment by guidolodetti** [comment]
Closing because I've just read I should email the support team instead. Sorry

**Comment by joeydong-stripe** [comment]
👍 (but yes, we have a todo open to improve directions for the Standard and Custom Integration examples)
