### ISSUE TITLE
Buggy back button in Payment Methods VC

### ISSUE THREAD

**Issue by guidolodetti** [stripe/stripe-ios#941]
I am using the latest version of the iOS SDK, and when I call `presentPaymentMethodsViewController` I always have the following graphical bug in the "add card" section. Sorry for the Italian language in the screenshot; the bug is the same in every language.

<img width="545" alt="screen shot 2018-05-21 at 15 56 19" src="https://user-images.githubusercontent.com/7063023/40311512-4b51309a-5d10-11e8-950d-0a9f7a592108.png">

**Comment by joeydong-stripe** [comment]
Hi @guidolodetti, thanks for opening an issue.

The `presentPaymentMethodsViewController` is implemented to use UINavigationController's `presentViewController` so it should present with "Cancel/Done" instead of a back button:

https://github.com/stripe/stripe-ios/blob/fedad463c9a4afdf1e9ad7f606a61c5e937d8f8a/Stripe/STPPaymentContext.m#L284-L315

![simulator screen shot - iphone x - 2018-05-21 at 13 13 20](https://user-images.githubusercontent.com/28276156/40327699-bdb5a318-5cf8-11e8-9c3e-7bd982c1dc44.png)

Can you check if you made any customizations that would prevent `[self.hostViewController presentViewController:navigationController animated:[self transitionAnimationsEnabled] completion:nil];` to work?

**Comment by joeydong-stripe** [comment]
Also, can you try `pushPaymentMethodsViewController`? I think that would behave as you expected.

https://github.com/stripe/stripe-ios/blob/fedad463c9a4afdf1e9ad7f606a61c5e937d8f8a/Stripe/STPPaymentContext.m#L317-L345

**Comment by guidolodetti** [comment]
Hi @joeydong-stripe and thanks for the answer!

We _present_ the view controller because we want it to appear from the bottom as a modal. We haven't tried the `pushPaymentMethodsViewController` because we liked the first option more.
The button works correctly even if it is displayed badly.

Please note that we are writing a new React Native wrapper since the currently most popular library, [tipsi](https://github.com/tipsi/tipsi-stripe), does not support your beautiful fully-integrated payment method interfaces (iOS & Android) 🙂. The wrapper is extremely simple and we present the payment methods vc in the following way:

```objc
// `paymentContext` was previously initialised...
paymentContext.hostViewController = RCTPresentedViewController();
[paymentContext presentPaymentMethodsViewController];
```

**Comment by joeydong-stripe** [comment]
> Please note that we are writing a new React Native wrapper since the currently most popular library, tipsi, does not support your beautiful fully-integrated payment method interfaces (iOS & Android) 🙂. 

That's really great, we fully support your efforts!

I don't know what would cause the left bar button item to show a back arrow like in your screenshot then if you use `presentPaymentMethodsViewController`. Maybe there's some global UIViewController customization that's doing something unexpected.

**Comment by joeydong-stripe** [comment]
Do you have the project / pull request somewhere online that I can take a look at?

**Comment by guidolodetti** [comment]
Hey @joeydong-stripe, sorry for the late answer! We have almost completed an internal user library and I will personally share it publicly in the following days! Thanks for your patience. I will post it here!

**Comment by guidolodetti** [comment]
Fixed by updating to version 13. Sorry! 🙂 
Uploading our React Native wrapper as soon as we find out why the Android version is creating `src_` objects instead of `card_` objects for sources (this is a problem)! [Issue here](https://github.com/stripe/stripe-android/issues/582)

**Comment by karybekov22** [comment]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-02-09 at 17 38 50](https://user-images.githubusercontent.com/55115453/155110727-47623d09-f53b-4cfe-8ba4-20eb271c5950.png)

Also got this kind of flaw in UI, should I update to a newer version?
