### ISSUE TITLE
Checkmark Overlaps Last 4 Digits of AMEX in SE/5

### ISSUE THREAD

**Issue by carsongee** [stripe/stripe-ios#948]
To make it easier to diagnose your issue, please fill out the following:

## Summary

When you add an Amex card and select it, the checkmark overlaps the numbers:
![image](https://user-images.githubusercontent.com/596029/40550576-80deefa4-6008-11e8-835c-3f037387ea6a.png)

## Code to reproduce

Add an Amex card to list of cards and select it:

## iOS version

11

## Installation method

CocoaPod

## SDK version

12.1.2

## Other information

Nothing to add

**Comment by danj-stripe** [comment]
@carsongee,

Thanks for the bug report! I've merged a fix, and it should go out in our next release.

Dan
