### ISSUE TITLE
To build the example app, you'll need to first run the setup script.

### ISSUE THREAD

**Issue by Premal-Khetani** [stripe/stripe-ios#950]
## Summary

The sample application is not running. producing a build-time error. 

## Code to reproduce

No code just downloaded the zip and run the project. showing below error :

**

> error: To build the example app, you'll need to first run the setup script.
> error: Please run ./setup.sh , and then try building again.

** 

## iOS version
11.3

## Installation method

Running your downloaded application code. 

## SDK version

latest

## Other information

Please find the image below : 

![screen shot 2018-05-28 at 10 24 37 am](https://user-images.githubusercontent.com/13691970/40597855-c92fe7c6-6261-11e8-811e-a8d7256fde2d.png)

**Comment by danj-stripe** [comment]
Hi @Premal-Khetani,

As the message states, you do need to run the setup script first. There are also a couple more steps you must take, and they're documented in our README: https://github.com/stripe/stripe-ios#examples

**Comment by MahipalV12** [comment]
in Terminal 
cd path_to_setup.sh
then Run
`sudo bash ./setup.sh`
