### ISSUE TITLE
App crashes when redirect from stripe SDK with 3D secure payments

### ISSUE THREAD

**Issue by raihan** [stripe/stripe-ios#953]
## Summary

App crashes when redirect from stripe SDK with 3D secure payments
## Code to reproduce

I have uploaded a sample project here: https://www.dropbox.com/s/m05i6omjrqj6qs6/TestStripe.zip?dl=0

## iOS version
iOS 11.3

## Installation method
pods

How did you install our SDK?
cocoapods

## SDK version
13.0.2

**Comment by danj-stripe** [comment]
Hi @raihan,

I'm not able to reproduce the crash with your sample code. Can you provide more details about the crash: the steps to reproduce, a stack trace, and console log?

When I run it, I do see that the `SFSafariViewController` isn't being dismissed. The url scheme `sampleAppUrl:` is being lowercased to `sampleappurl:`, so you should change your `returnURL` to be all lowercase, but that's not crashing.

I think you already found the sample code to use as a reference, but I'll mention it in case it helps. [ThreeDSExampleViewController.m](https://github.com/stripe/stripe-ios/blob/master/Example/Custom%20Integration%20(ObjC)/ThreeDSExampleViewController.m) and the corresponding [AppDelegate.m](https://github.com/stripe/stripe-ios/blob/master/Example/Custom%20Integration%20(ObjC)/AppDelegate.m) are really close to what you have (close enough that I can't find any meaningful differences).

I also see your implementation of `application(_:continue:restorationHandler:)`. We don't use universal links in the `returnURL`, so I'm not actually sure how well it'll work. However, the sample project is using an app-specific scheme, so I think this is unrelated to the crash you're reporting.

Dan

**Comment by raihan** [comment]
I was getting that yesterday, not getting anymore, will knock you again if I get the issue. Thanks for your support.
