### ISSUE TITLE
Setting expiration month alone doesn't update UI

### ISSUE THREAD

**Issue by ericlewis** [stripe/stripe-ios#955]
## Summary

Setting the expiration month does not update the UI unless you also set the year. We use a custom number pad input as opposed to the proper keyboard, so this is important for us.

## Code to reproduce

Try setting the month without setting the year.

## iOS version

All

## Installation method

Cocoapod

## SDK version

11.2.0

## Other information

Setting month I would expect it to show the partial. "01/"

**Comment by csabol-stripe** [comment]
Thanks for the report, and apologies for the delay in getting back to you! I am looking into this now

**Comment by csabol-stripe** [comment]
@ericlewis would you mind confirming which class(es) you are setting the expiration on?

**Comment by ericlewis** [comment]
@csabol-stripe STPPaymentCardTextField

**Comment by csabol-stripe** [comment]
By default `STPPaymentCardTextField` should be setting the `rawExpiration` property on the `STPPaymentCardTextFieldViewModel`, which does allow for month only strings:

![image](https://user-images.githubusercontent.com/36750494/41262824-ee673544-6d97-11e8-9d02-869869d07ae3.png)

Is there additional configuration you are doing on the `STPPaymentCardTextField`?

**Comment by ericlewis** [comment]
Nope, nothing special. Maybe a version mismatch?

**Comment by csabol-stripe** [comment]
@ericlewis which version are you using now? Does updating to a newer version resolve the issue for you?

**Comment by danj-stripe** [comment]
Hi @ericlewis,

Have you tried using the `inputView` property on the `STPPaymentCardTextField` for your custom keyboard?

If I understand you correctly, you're trying to use `setCardParams:` in conjunction with a custom keyboard to enter the expiration month and have the UI live update, and I don't think that's supported.

We haven't heard from you in a month, so I'm closing this issue, but we'll keep an eye out for any updates from you.

Dan
