### ISSUE TITLE
Order api

### ISSUE THREAD

**Issue by podycust** [stripe/stripe-ios#966]
I just wondering if there is a swift example on using the order api?

**Comment by joeydong-stripe** [comment]
Hi @podycust, looks like something we should definitely consider! Which part of the Orders API would you expect an example for? 

https://stripe.com/docs/orders

**Comment by podycust** [comment]
order which uses a product and sku

**Comment by joeydong-stripe** [comment]
Thanks for the feedback @podycust. I've put it on our internal tracking system and we will consider it :)
