### ISSUE TITLE
Please support optional CVC Code

### ISSUE THREAD

**Issue by jaz-ah** [stripe/stripe-ios#970]
## Summary
Feature Request: make CVC Code optional like PostalCode

## iOS version
(Any)

## Installation method
Pods

## SDK version
13.0.3

**Comment by remi-stripe** [comment]
@jaz-ah CVC is highly recommended to avoid fraud on your account. Client-side, when collecting card details, you should always collect it from the customer so this is not something we would add support for.

If you have a specific reason to need to skip CVC, I would recommend discussing this directly with our support team instead: https://support.stripe.com/email
