### ISSUE TITLE
Deleting the selected payment method

### ISSUE THREAD

**Issue by epacces** [stripe/stripe-ios#971]
## Summary
The `STPPaymentMethodsInternalViewController` does not allow the user to delete the selected payment method, although the endpoints https://stripe.com/docs/api#delete_card, https://stripe.com/docs/api#detach_source allow to do so. 

## iOS version
N/A

## Installation method
Cocoapods

## SDK version
13.0.2

## Other information
This seems to be the expected behaviour according to  https://github.com/stripe/stripe-ios/blob/b17dd1265473a19b01b36dabc7e399359ea7bcff/Stripe/PublicHeaders/STPPaymentConfiguration.h#L110. So my question would be if there is any future plan to enable users to delete the default payment methods through the standard integration of the Stripe SDK since this seems to be technically possible.

**Comment by epacces** [comment]
Hi @danj-stripe,

Thanks for your answer. 

Unfortunately, I don't know any detail on the use case yet. I am going to ask my client and get back to you as soon as provided with further requirements. 

Best, 
Eri

**Comment by joeydong-stripe** [comment]
Thanks @epacces, let us know!

**Comment by lmendezk9** [comment]
hello, how can I implement, the edit button in the "paymentMethodsViewController"?
