### ISSUE TITLE
Other supported PKPaymentNetworks for Apple Pay

### ISSUE THREAD

**Issue by bcomeau** [stripe/stripe-ios#972]
## Summary

In the current SDK only the following networks are supported for Apple Pay payment:
- Amex
- MasterCard
- Visa
- Discover (iOS 9+ only)

As described in `[STPAPIClient supportedPKPaymentNetworks]`

Is there any plan to update the SDK to support other networks?

## SDK version

Version: 13.0.3

## Other information

iOS 10 added a [method](https://developer.apple.com/documentation/passkit/pkpaymentrequest/1833288-availablenetworks) to return the list of available payment networks that are supported by Apple Pay.

**Comment by danj-stripe** [comment]
Hi @bcomeau,

The SDK doesn't support all of the networks that are available through Apple Pay. The `supportedPKPaymentNetworks` are the ones that the Stripe backend can currently process for us.

Dan
