### ISSUE TITLE
how to get notified when STPPaymentContext#loading is becoming true ?

### ISSUE THREAD

**Issue by wangjiejacques** [stripe/stripe-ios#981]
## Summary
For now, the `STPPaymentContextDelegate` doesn't have a method like `- (void)paymentContext:(STPPaymentContext *)paymentContext didFinishToLoad;`.
but it's quite important to get notified when the STPPaymentContext is finishing to load, is it a good idea to add this method to the `STPPaymentContextDelegate`, or am I get something wrong ?

## Installation method
Pod

## SDK version
13.0.3

**Comment by joeydong-stripe** [comment]
Hi @wangjiejacques, thanks for opening an issue.

This seems like a reasonable delegate method to add. What do you plan on doing with this notification?

**Comment by wangjiejacques** [comment]
@joeydong-stripe thanks, I have found `- (void)paymentContextDidChange:(STPPaymentContext *)paymentContext;` is enough, I don't need `- (void)paymentContext:(STPPaymentContext *)paymentContext didFinishToLoad;`

**Comment by joeydong-stripe** [comment]
👍
