### ISSUE TITLE
How can we prefill user shipping method?

### ISSUE THREAD

**Issue by felixkli** [stripe/stripe-ios#991]
## Summary

Hi, I would like to implement the standard integration with both shipping address and shipping method pre filled or set to a default. Currently, the properties for selected shipping method is read only. Is there a way to do this without having to prompt the shipping address form to select the shipping method?

## iOS version
11.3

## Installation method
Cocoapods

## SDK version
13.0.3

**Comment by danj-stripe** [comment]
Hi @felixkli,

I don't believe that's supported. Can you describe a little more about your use case?

Thanks,
Dan

**Comment by felixkli** [comment]
Hi Dan,

Currently, our user can retrieve their previously entered shipping address, but in order to select a shipping method, they are forced to enter the shipping address screen before they can select a shipping method. We would like to set a default shipping method so that the user does not have to go through the shipping address flow every time they would like to purchase a product.

Thanks,
Felix

**Comment by danj-stripe** [comment]
Thanks Felix, I appreciate the additional context.

I've moved this feature request into our internal issue tracker for a future update, and I'm going to close this github issue.

**Comment by felixkli** [comment]
Also, in the didUpdateShippingAddress delegate method, when I call the completion(status, error, nil, nil) block, I am unable to request payment. It will launch the shipping address form over and over even if I complete the shipping address form.

**Comment by danj-stripe** [comment]
Hi @felixkli,

I think that's expected behavior. If you implement the `paymentContext:didUpdateShippingAddress:completion:` delegate method, the SDK expects a valid shipping address to have some shipping methods, and that you'll pass them to the completion callback (instead of `nil, nil`).

You can write into Stripe support at https://support.stripe.com/email/login for more help with your integration.

Dan
